### DISCUSSION TITLE
Why dependabot not support `widen` even though the docs stated it

### DISCUSSION THREAD

**Discussion by kiraware** [dependabot/dependabot-core#10677] [Q&A] [answered]
As the docs inform https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy, there is `widen` in `versioning-strategy`. But why it says error like this `The property '#/updates/0/versioning-strategy' value "widen" did not match one of the following values: lockfile-only, auto, increase, increase-if-necessary`. I use Python Poetry as dependency manager.

This is my dependabot.yml

```yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    versioning-strategy: widen
```
