### DISCUSSION TITLE
Github workflow doesn't trigger after Dependabot commits bun.lockb file

### DISCUSSION THREAD

**Discussion by kristian-nst** [dependabot/dependabot-core#11051] [Q&A]
We're using Bun, so to enable the updates of the bun lockfile, we need to do a custom action like this:

```
name: 'Dependabot: Update bun.lockb'

on:
  pull_request:
    paths:
      - 'package.json'

permissions:
  contents: write

jobs:
  update-bun-lockb:
    name: 'Update bun.lockb'
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Bun install
        run: |
          bun install --ignore-scripts
      - name: Configure git author
        run: |
          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'dependabot[bot]@users.noreply.github.com'
      - name: Commit bun.lockb
        run: |
          git add bun.lockb
          git commit --amend --no-edit
      - name: Push bun.lockb
        run: git push --no-verify --force
```

Taken from:
https://github.com/dependabot/dependabot-core/issues/6528

However, on this second commit and push, my regular pipeline doesn't run. What am I missing?

![image](https://github.com/user-attachments/assets/0c1231ef-5ffe-47cc-a7ba-7b20c7463430)

![image](https://github.com/user-attachments/assets/23e2d796-65bc-4219-9bd3-bfd4a5f8dd34)

My other workflow looks like:

```
name: CI
on:
  pull_request:
    branches: [main]
jobs:
  lint:
    steps:
      ...etc
  tsc:
    steps:
      ...etc
```
