### DISCUSSION TITLE
Is bun fully supported

### DISCUSSION THREAD

**Discussion by tembbo** [dependabot/dependabot-core#11858] [General]
I've had this dependabot.yml for some time now:

```yml
version: 2
updates:
    - package-ecosystem: bun
      directory: /
      schedule:
          interval: daily
```

It's worked and created PRs correctly, but now it has started throwing errors on some deps like this:

```sh
updater | 2025/03/20 03:34:58 INFO <job_983606249> Requirements to unlock update_not_possible
updater | 2025/03/20 03:34:58 INFO <job_983606249> Requirements update strategy widen_ranges
2025/03/20 03:34:58 INFO <job_983606249> No update possible for <dep>
```

I solved this after some tinkering by adding `enable-beta-ecosystems: true`

But looking at the [official docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-) it doesn't specify that it's required for bun

So is this is a bug or is it still required to enable beta ecosystems, and why did it update some dependencies without it?
