### DISCUSSION TITLE
Is there an easy way to have Dependabot scan all package.jsons for NPM?

### DISCUSSION THREAD

**Discussion by Gemberkoekje** [dependabot/dependabot-core#11972] [Q&A]
Hi there,

I am new to dependabot, and I'm trying to set it up for a monorepo in Azure.
So I set it to scan \ and let it run. The error I got was "/package.json not found"
This makes sense, there is no package.json in my root, but there are multiple ones in apps/app1/package.json apps/app2/package.json etc.

I can of course manually set up all the directories with package.jsons, however, that means that every time someone adds a new app, they need not forget to add it to the dependabot config, so i'd rather not do that.

Is there an easy way to have dependabot scan every package.json in order?

My azure yaml looks something like this:
```
jobs:
  - job:
    pool:
      name: $(pool)
      demands:
      - $(demands)
    steps:
    - task: dependabot@2
      inputs:
        skipPullRequests: true
        abandonUnwantedPullRequests: true
        commentPullRequests: true
        setAutoComplete: true
        mergeStrategy: 'squash'
        authorEmail: 'dependabot@tjip.com'
        authorName: 'dependabot'
```

And my dependabot.yml looks something like this:
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
```

Thanks in advance!
