### DISCUSSION TITLE
How to group dependancies by file?

### DISCUSSION THREAD

**Discussion by qqii** [dependabot/dependabot-core#12176] [Q&A]
For example I have `requirements.txt` and `requirements-dev.txt`. I want to group updates to `requirements-dev.txt` into a single PR, but leave updates to `requirements.txt` separate.

In essence, I'd like to write something like this:

```yml
  - package-ecosystem: "pip"
    directory: "requirements.txt"
  - package-ecosystem: "pip"
    directory: "requirements-dev.txt"
    groups:
      all:
        patterns:
          - "*"
```

But this fails with the following error:

```
+---------------------------------------------------------------------------------+
|                                     Errors                                      |
+---------------------------+-----------------------------------------------------+
| Type                      | Details                                             |
+---------------------------+-----------------------------------------------------+
| dependency_file_not_found | {                                                   |
|                           |   "message": "No files found in /requirements.txt", |
|                           |   "file-path": null                                 |
|                           | }                                                   |
+---------------------------+-----------------------------------------------------+
```

Is there a good way to do this?
