### DISCUSSION TITLE
🚀 Beta Release: Multi-Ecosystem Updates

### DISCUSSION THREAD

**Discussion by robaiken** [dependabot/dependabot-core#12437] [Announcements]
We're excited to announce the beta release of **multi-ecosystem updates** for Dependabot! This feature allows you to create groups that span multiple package ecosystems and get a single PR with updates across all supported ecosystems.

## How It Works

Instead of receiving separate PRs for each ecosystem (docker, terraform, pip, etc.), you can now configure groups that consolidate updates into a single PR per group.

## Example Configuration

```yaml
version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
  
  full-stack:
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
  
  - package-ecosystem: "terraform"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    
  - package-ecosystem: "pip"
    directory: "/"
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: "npm"
    directory: "/frontend"
    multi-ecosystem-group: "full-stack"
    
  - package-ecosystem: "bundler"
    directory: "/backend"
    multi-ecosystem-group: "full-stack"
```

## Use Cases

- **Infrastructure projects**: Group docker, terraform, and configuration management updates
- **Full-stack applications**: Coordinate frontend and backend dependency updates
- **Cross-platform libraries**: Keep the same library versions aligned across different ecosystems
- **Microservices**: Group related services that should be updated together

## Getting Started

1. Add `multi-ecosystem-groups` to your `.github/dependabot.yml`
2. Define your groups with scheduling preferences
3. Assign ecosystems to groups using `multi-ecosystem-group`
4. Commit and watch for consolidated PRs!

## Known Issues

**YAML Schema Validation**: You may see red underlines in your config file. This is expected as we haven't updated the schema validation rules yet. The configuration will still work correctly.

## We Want Your Feedback!

This is a beta release, and we'd love to hear about your experience:

- **What use cases are you trying to solve?**
- **How well does the grouping work for your projects?**
- **Any issues or unexpected behavior?**
- **Feature requests for future improvements?**

Please share your thoughts, configurations, and experiences in the comments below. Your feedback will help us improve this feature before general availability.

## Related Issues

- Original feature request: #8126
- Documentation updates: Coming soon

Thanks for being part of the beta! 🙏

**Comment by broksonic21** [comment]
Fantastic! Can you give an example where you want just one package always grouped, but not others, in terms of configuration.

As an example, say:

* NPM and Bundler to be separate groups
* But playwright (NPM) and playwright-ruby-client (Bundler) to be grouped together as they should be updated in sync

Thanks!

**Reply by robaiken** [reply]
@broksonic21 Absolutely! This is a great use case for the `patterns` feature. You can have most packages stay separate while grouping only specific related packages together:

```yaml
version: 2

multi-ecosystem-groups:
  playwright-sync:
    schedule:
      interval: "weekly"

updates:
  # Regular NPM updates (excluding playwright)
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "playwright"

  # Regular Bundler updates (excluding playwright-ruby-client)  
  - package-ecosystem: "bundler"
    directory: "/"
    ignore:
      - dependency-name: "playwright-ruby-client"

  # Playwright packages grouped together across ecosystems
  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["playwright"]
    multi-ecosystem-group: "playwright-sync"

  - package-ecosystem: "bundler" 
    directory: "/"
    patterns: ["playwright-ruby-client"]
    multi-ecosystem-group: "playwright-sync"
```

This configuration will give you:
- **Separate PRs** for all other NPM and Bundler updates
- **One consolidated PR** whenever playwright or playwright-ruby-client need updates, ensuring they stay in sync

The key is using `patterns` to target specific packages for grouping while using `ignore` on the regular ecosystem updates to exclude those same packages from separate PRs.

**Documentation links:**
- [Dependabot configuration options](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference)
- [Controlling which dependencies are updated](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated)
- [Configuring Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)

**Comment by kyle-leonhard** [comment]
@robaiken - heads up, configuration similar to the example produces an error: `The property '#/updates/0/patterns' is required when 'multi-ecosystem-group' is set.` But setting patterns produces: `The property '#/updates/0/' contains additional properties ["patterns", "multi-ecosystem-group"] outside of the schema when none are allowed`

**Reply by robaiken** [reply]
Thanks for the config! The main issue I see is the schedule structure, it should be:
```yaml
version: 2

multi-ecosystem-groups:
  all:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all"
  # ...
```

The Dependabot schema expects the `schedule` to be a nested object with `interval` as a property inside it, not interval as a direct property of the group. Also, the patterns property isn't valid at the `multi-ecosystem-groups` level, it only belongs in the individual `updates` entries. So the corrected config removes `patterns` from the group definition entirely and keeps them only in the individual update blocks.

The confusing part is that the error messages are misleading, they're complaining about `patterns` being required/not allowed, when the real issue is the malformed schedule structure. It seems like the schema validation is getting confused and throwing the wrong error messages when it encounters the incorrectly structured `interval` field.

So the root cause is a schema structure issue, but the error reporting is pointing to the wrong field entirely

**Reply by kyle-leonhard** [reply]
Thanks @robaiken, good eye! 

The updated config made dependabot actions run successfully and I see logs that indicate updates ought to have happened but no PR.

Any ideas?

The updated config triggered an on demand job which, at least for per-ecosystem groups, will open PRs off schedule.

([action](https://github.com/kosolabs/koso/actions/runs/15708622658/job/44260434964)): 

```
+----------------------------------------------------------------+
|              Changes to Dependabot Pull Requests               |
+---------+------------------------------------------------------+
| created | docker/setup-buildx-action ( from 3.10.0 to 3.11.0 ) |
+---------+------------------------------------------------------+
```


Config:

```
version: 2
multi-ecosystem-groups:
  all:
    schedule:
      interval: monthly
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all"
  - package-ecosystem: "npm"
    directories:
      - "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all"
  - package-ecosystem: "docker"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all"
```

**Reply by kyle-leonhard** [reply]
@robaiken Something seems buggy with opening pull requests.

I noticed an error message: `Dependabot failed to create a pull request` in one of the [jobs](https://github.com/kosolabs/koso/network/updates/1036018280) (npm), though not for the other ecosystem with updates (github-actions). But the logs don't show any errors: [logs](https://github.com/kosolabs/koso/actions/runs/15708622589/job/44260434585).

The branch with updates from both ecosystems was created but the PR was not.

I re-ran one of the checks ([job](https://github.com/kosolabs/koso/actions/runs/15739331127/job/44360395784)) with similar results. Though, no branch or PR was created and there wasn't an error message. Job logs show:

```
updater | 2025/06/18 17:18:18 INFO <job_1036747723> Creating a pull request for 'all-deps'
<snip>
+----------------------------------------------------------------------------+
|                    Changes to Dependabot Pull Requests                     |
+---------+------------------------------------------------------------------+
| created | svelte ( from 5.34.2 to 5.34.6 ), vitest ( from 3.2.3 to 3.2.4 ) |
+---------+------------------------------------------------------------------+
```

And github-actions ([logs](https://github.com/kosolabs/koso/actions/runs/15739495716/job/44360947182)):

```
+----------------------------------------------------------------+
|              Changes to Dependabot Pull Requests               |
+---------+------------------------------------------------------+
| created | docker/setup-buildx-action ( from 3.10.0 to 3.11.1 ) |
+---------+------------------------------------------------------+
```

**Reply by robaiken** [reply]
@kyle-leonhard sorry for the delay! It looks like Docker doesn't have any available updates, which prevents us from creating an update. We only group ecosystems together when all of them have updates available. If you remove Docker from the config (and possibly Cargo too if it has no updates), you should start getting your bump pull requests

**Reply by kyle-leonhard** [reply]
> @kyle-leonhard sorry for the delay! It looks like Docker doesn't have any available updates, which prevents us from creating an update. We only group ecosystems together when all of them have updates available. If you remove Docker from the config (and possibly Cargo too if it has no updates), you should start getting your bump pull requests

Thanks for the reply, @robaiken . Oh! My two cents - that behaviour is unexpected, surprising. I'd expected all available updates to be created, even if some ecosystems don't have available updates, a very common occurrence in my experience. 

Is that behavior something you've considered changing?

**Reply by MatMoore** [reply]
I think I've run into the same issue. My expectation was the same as @kyle-leonhard - I thought that dependabot would create the update PR at the first opportunity, and then later on it might add updates from the other ecosystem to the PR.

Not creating a PR straight away makes sense if you are filtering with `patterns` and you know that every update to one ecosystem implies a corresponding update will land in the other ecosystem, but I didn't get that sense from the feature description or the infrastructure/full-stack example.

I'm also finding it a little bit hard to debug what's going on when testing this feature. If the updates array in my yaml contains multiple items per ecosystem (as in [this example](https://github.com/dependabot/dependabot-core/discussions/12437#discussioncomment-13449744)) then I end up with multiple entries on the /network/updates page for the same ecosystem, with no obvious way to distinguish them.

![Screenshot showing 2 rows for npm and 2 rows for pip](https://github.com/user-attachments/assets/335e87e1-9782-4426-9c27-9d7dd3966f97)

In case it is helpful, [here is the configuration I tried](https://github.com/NHSDigital/dtos-manage-breast-screening/blob/9bfbe580a82d8de99cddbc99baf90b4a874350cb/.github/dependabot.yaml#L11). What I was trying to test was
- 1 multi ecosystem group that covers a specific pair of dependencies
- Certain other things are grouped together within ecosystems
- Everything else is a single PR

When the npm dependency was updated within the multi ecosystem group, I had the same result as @kyle-leonhard: the branch was created, I see a "Dependabot ran into an issue when attempting to create the pull request" error, and the logs show the job as successful.

**Reply by kyle-leonhard** [reply]
@robaiken what do you think? Is this behavior something you'd consider adjusting? Otherwise, for my purposes, the feature is unusable.

**Reply by robaiken** [reply]
@kyle-leonhard @MatMoore  I need to correct my previous response - we've actually reversed this decision after further discussion with the team.

Multi-ecosystem groups will now create pull requests even when only a subset of the configured ecosystems have available updates. The group will include whichever ecosystems have updates available at the time, so you should start seeing your bump pull requests even if some ecosystems don't have updates.

Thanks for your patience while we worked through this behavior!

**Comment by AppSecCharlie** [comment]
Very cool! Can we also use the `applies-to` and `dependency-type` keys? e.g. if I wanted one group for all security updates (`applies-to: security-updates`, and one for all prod updates (`dependency-type: production`).. how might that be configured? 

When I try the config below, getting errors:

```
The property '#/updates/0/' contains additional properties ["applies-to"] outside of the schema when none are allowed
The property '#/updates/1/' contains additional properties ["dependency-type"] outside of the schema when none are allowed
The property '#/updates/2/' contains additional properties ["dependency-type"] outside of the schema when none are allowed
```

Sample config (I'd like to also include `npm` updates in the prod/dev/security groups, but keeping it simple for now):

```yml
version: 2

multi-ecosystem-groups:
  prod:
    schedule:
      interval: "monthly"
  dev:
    schedule:
      interval: "monthly"
  security:
    schedule:
      interval: "weekly"
    
updates:
  - package-ecosystem: "pip"
    directories:
      - "**/*"
    multi-ecosystem-group: "security"
    applies-to: "security-updates"
    patterns:
      - "*"

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    multi-ecosystem-group: "prod"
    dependency-type: "production"
    patterns:
      - "*"

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    multi-ecosystem-group: "dev"
    dependency-type: "development"
    patterns:
      - "*"
```

**Reply by parkerbxyz** [reply]
Does it work if you put `applies-to` and `dependency-type keys` under `groups`?

```yaml
version: 2

multi-ecosystem-groups:
  prod:
    schedule:
      interval: "monthly"
  dev:
    schedule:
      interval: "monthly"
  security:
    schedule:
      interval: "weekly"
    
updates:
  - package-ecosystem: "pip"
    directories: ["**/*"]
    patterns: ["*"]
    multi-ecosystem-group: "security"
    groups:
      security-updates:
        applies-to: "security-updates"

  - package-ecosystem: "pip"
    directories: ["**/*"]
    patterns: ["*"]
    multi-ecosystem-group: "prod"
    groups:
      prod-deps:
        dependency-type: "production"
      
  - package-ecosystem: "pip"
    directories: ["**/*"]
    patterns: ["*"]
    multi-ecosystem-group: "dev"
    groups:
      dev-deps:
        dependency-type: "development"
```

**Reply by AppSecCharlie** [reply]
@parkerbxyz closer.. I ended up having to do `patterns: - "*"` in a few places to make Dependabot's YAML parser happy. Currently using something like this, but it _seems_ to lump everything together in the `security` group (e.g. I'm getting updates that should be in the `prod` or `dev` group all just going to the `security` group):

```yaml
version: 2

multi-ecosystem-groups:
  prod:
    schedule:
      interval: "monthly"
  dev:
    schedule:
      interval: "monthly"
  security:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "pip"
    directories:
      - "**/*"
    multi-ecosystem-group: "security"
    patterns:
      - "*"
    groups:
      python-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    multi-ecosystem-group: "prod"
    patterns:
      - "*"
    groups:
      python-prod:
        dependency-type: "production"

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    multi-ecosystem-group: "dev"
    patterns:
      - "*"
    groups:
      python-dev:
        dependency-type: "development"
```
