### DISCUSSION TITLE
Configure dependabot.yml using pnpm

### DISCUSSION THREAD

**Discussion by cexra** [dependabot/dependabot-core#8831] [Q&A] [answered]
here is my dependabot.yml

```yaml
version: 2
updates:
  - package-ecosystem: "pnpm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
```

but why github show me this error
`The property '#/updates/0/package-ecosystem' value "pnpm" did not match one of the following values: npm, bundler, composer, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub, swift`

can you show me how to fix this

**Comment by cexra** [comment, marked as answer]
I'm sorry, it turns out that I was not careful in reading the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)

to configure the project with pnpm then the package-ecosystem is set with the value "npm". like this

```yaml
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
```
