### DISCUSSION TITLE
How can I make dependabot put all updates into one pull request?

### DISCUSSION THREAD

**Discussion by RealTriassic** [dependabot/dependabot-core#8857] [Q&A] [answered]
Hello, I am trying to get dependabot to just open one pull request for all npm package updates every Monday, instead of opening a pull request for each dependency, which results in many pull requests being opened at once. I currently have this as my dependabot configuration and I was hoping it'd do the trick, but unfortunately woke up today to a lot of pull requests opened.

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      dev-dependencies:
        patterns: 
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
```

Any help is appreciated, thanks!
