### DISCUSSION TITLE
Updating Dockerfiles within a monorepo

### DISCUSSION THREAD

**Discussion by Nithos** [dependabot/dependabot-core#9120] [Q&A] [answered]
Currently I have a monorepo with multiple modules within it with their own Dockerfiles. My dependabot configuration contains the following to update docker images however it does not seem to detect any Dockerfiles. It seems that unlike other ecosystems (npm for instance) you can not specify the root `/` as the directory for it it recursively scan down for all files. Is there a way around this as doing a configuration for each module is not ideal.

```
  # Maintain docker image dependencies
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      minor-patch:
        update-types:
          - 'minor'
          - 'patch'
    labels:
      - 'dependency'
      - 'bot'
```

Is there a way to do this?
