### DISCUSSION TITLE
Ignores not working

### DISCUSSION THREAD

**Discussion by Jord-anC** [dependabot/dependabot-core#9281] [Q&A]
Hi,

This may turn out to be something extremely obvious, but I am new to Dependabot and struggling to get this to work.

I have a very simple config file, it seems to be working in most senses e.g. the private registry is being accessed fine with this setup. However, the **ignore** section doesn't seem to be working and I have no idea why.

My config is below, it is based on the docs and can't seem to see why there would be an issue. I am testing Dependabot on a completely new .NET project, have installed vulnerable versions of both **log4net** and **Newtonsoft.Json**, then when I check those in Dependabot is opening security issues even though I would expect it to ignore those.

Please can anyone let me know if the config is incorrect or if there is something else I'm missing! Thanks a lot in advance 

```
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    # stop version updates and only create PRs for security updates
    open-pull-requests-limit: 0
    registries:
      - nuget-azure-artifacts
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "log4net"
      - dependency-name: "Newtonsoft.Json"
registries:
  nuget-azure-artifacts:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/asos/_packaging/dependabot-test/nuget/v2
    token: "${{ secrets.AZURE_ARTIFACTS_PAT }}:"
```
