### DISCUSSION TITLE
Is it possible to group dependabot package-ecosystems?

### DISCUSSION THREAD

**Discussion by bm-fez** [dependabot/dependabot-core#9418] [Q&A]
I have two Node projects in single repo with dependabot configured to update both. It is configured using the `groups` parameter to minimize the number of PRs created.

```
version: 2
updates:
          - "*"
  - package-ecosystem: "npm" 
    directory: "/Extensions/BuildUpdating/BuildRetensionTask" 
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns: 
          - "*"
  - package-ecosystem: "npm" 
    directory: "/Extensions/BuildUpdating/BuildVariableTask" 
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns: 
          - "*"
```

This working, so if a module common to both projects is update I get two PRs e.g.

- PR1 - Update Module 1.1.1 > 1.1.2 (in /Extensions/BuildUpdating/BuildRetensionTask)
- PR 2- Update Module 1.1.1 > 1.1.2 (in /Extensions/BuildUpdating/BuildVariableTask)

I need to deploy both these projects via a single CI/CD workflow, so it would be useful to group the dependabot updates both within each application and across the two `package-ecosystem` i.e. just getting a single PR that updates two eco systems

Is this currently possible or on the roadmap?
