### DISCUSSION TITLE
For wildcard / globbing support in the dependabot.yml file, what behavior would you expect to see if directories overlap?

### DISCUSSION THREAD

**Discussion by carlincherry** [dependabot/dependabot-core#9823] [Polls]
A quick informal straw poll for a gut check: what behavior would you expect to see if directories overlap?

I.e. 

Given an _existing_ configuration file like 👇 

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers: ["@person1"]

  - package-ecosystem: "npm"
    directories:
      - "/frontend"
    schedule:
      interval: "weekly"
    reviewers: ["@person2"]

  - package-ecosystem: "npm"
    directories:
      - "/backend"
    schedule:
      interval: "daily"
    reviewers: ["@person3"]
```

And a user _adds_ the following entry 👇 

```yaml
  - package-ecosystem: "npm"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    reviewers: ["@person4"]
```

When would you expect or want Dependabot to run? And who would you expect or want to be assigned as a reviewer?

**Comment by tylerbenson** [comment]
More specific should take priority.

`foo/bar/baz` should be applied over `foo/bar/*` which should take priority over `foo/**/baz`.

**Comment by lucacome** [comment]
>add a "negation" functionality to make configuration + customization easier

Can you expand on how this would work? Maybe an example of a configuration?

**Reply by carlincherry** [reply]
Something like this:
```
updates:
  - ecosystem: npm
    directories: 
      - "**/*"
      - "!foo/bar"
      - "!foo/baz"
    assignees: ["carlin"]
  - ecosystem: npm
    directories:
        - foo/bar
        - foo/baz
    assignees: ["nish"]
```
