### DISCUSSION TITLE
Ignoring Minor Version Upgrades Ending with `-legacy`

### DISCUSSION THREAD

**Discussion by Ilyesbdlala** [dependabot/dependabot-core#9867] [Q&A]
I am trying to ignore all upgrade attempts to a minor version ending with `-legacy`. 
Example: https://github.com/secureCodeBox/secureCodeBox/pull/2500/files#diff-c3287fe15c76cf3b64f4e87ee6f55b27aaf384d63a0ac9f3ad9ee6c5e91de008R27 
Things I tried:
dependabot.yml
```yaml
  - package-ecosystem: "gradle"
    directory: "/hooks/persistence-defectdojo/hook"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.kubernetes:client-java:*-legacy"
```
and 
```yaml
  - package-ecosystem: "gradle"
    directory: "/hooks/persistence-defectdojo/hook"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.kubernetes:client-java"
        versions: ["*-legacy"]
```
I don't see any other options from the documentation. So I would appreciate the help :)
