### ISSUE TITLE
Dependabot selects the wrong file as a dependency under the pip ecosystem

### ISSUE THREAD

**Issue by Zxilly** [dependabot/dependabot-core#10007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip 24.0

### Language version

Python 3.12

### Manifest location and content before the Dependabot update

https://github.com/Zxilly/go-size-analyzer/blob/master/scripts/requirements.txt

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

#  - package-ecosystem: "npm"
#    directory: "/ui"
#    schedule:
#      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

dependabot should read dependecies from `requirements.txt` which locates at https://github.com/Zxilly/go-size-analyzer/blob/master/scripts/requirements.txt. However, it reads data from [`binaries.csv`](https://github.com/Zxilly/go-size-analyzer/blob/master/scripts/binaries.csv), which is a data file which not related to the package manager.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/Zxilly/go-size-analyzer/actions/runs/9508733973/job/26210566565

### Smallest manifest that reproduces the issue

```yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "daily"
```
