### ISSUE TITLE
Looks like these dependencies are updatable in another way, so this is no longer needed.

### ISSUE THREAD

**Issue by conan** [dependabot/dependabot-core#10019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Language version

20.14.0

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "dir1"
      - "dir2"
      ... etc - currently 11 directories
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 30
    groups:
      npm:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"     
```          

### What you expected to see, versus what you actually saw

This is the same as https://github.com/dependabot/dependabot-core/issues/439

Dependabot raised a group PR that updated a number of dependencies.  This caused some of our tests to fail, so I pushed several commits to the same branch to fix those tests.  The PR was reviewed by my colleague.

# Expected:

I was expecting Dependabot to leave this PR alone, because I'd pushed to it.  

# Actual:

Dependabot subsequently closed the PR with the message:

> Looks like these dependencies are updatable in another way, so this is no longer needed.

- I now realise the [docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#allowing-dependabot-to-rebase-and-force-push-over-extra-commits) state:

> By default, Dependabot will stop rebasing a pull request once extra commits have been pushed to it.

This doesn't say that Dependabot won't close the PR and create a new one, but that it does feels like a bug - otherwise I'll always have to branch off from a Dependabot branch to add fixes, which is unintuitive.  I don't expect PRs I'm actively developing to be closed by Dependabot.

### Images of the diff or a link to the PR, issue, or logs

![image](https://github.com/dependabot/dependabot-core/assets/3037019/c8d5075f-53dc-4bf1-8e11-a55f1b8487b7)
