### ISSUE TITLE
Multi-directory configuration for pub ecosystem times out easily

### ISSUE THREAD

**Issue by NicolaVerbeeck** [dependabot/dependabot-core#10084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pub

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "pub"
    directories:
      - "/packages/*"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "meta"       
      - dependency-name: "test"       
      - dependency-name: "collection" 
      - dependency-name: "path"       
      - dependency-name: "http"       
    commit-message:
      prefix: "[NO-TICKET][DEPENDABOT]"
      include: "scope"
```

### What you expected to see, versus what you actually saw

We expect to have it run and create the appropriate PR if applicable. What we see is that it always times out. With a monorepo of 23 packages, we see 1200+ log lines about installing flutter (in this case 3.22), so perhaps the culmination of all these installs is triggering the timeout
