### ISSUE TITLE
Dependabot timed out during its update

### ISSUE THREAD

**Issue by huehnerlady** [dependabot/dependabot-core#10083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 

### Language version

Nodejs 20.14

### Manifest location and content before the Dependabot update

/package.json
[package.json](https://github.com/user-attachments/files/15986916/package.json)

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      angular: # group angular dependencies together
        patterns:
          - "@angular*"
      all: # group all minor/patch updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

```

### What you expected to see, versus what you actually saw

I expect dependabot to run through

What I get is an error saying `Dependabot timed out during its update`

### Native package manager behavior

```
➜  app git:(main) ✗ npm outdated
Package                           Current   Wanted   Latest  Location                                       Depended by
@ngneat/spectator                  18.0.2   18.0.2   19.0.0  node_modules/@ngneat/spectator                 app
@types/node                       20.14.6  20.14.9  20.14.9  node_modules/@types/node                       app
@typescript-eslint/eslint-plugin   7.13.1   7.13.1   7.14.1  node_modules/@typescript-eslint/eslint-plugin  app
@typescript-eslint/parser          7.13.1   7.13.1   7.14.1  node_modules/@typescript-eslint/parser         app
eslint                             8.57.0   8.57.0    9.5.0  node_modules/eslint                            app
typescript                          5.4.5    5.4.5    5.5.2  node_modules/typescript                        app
```

### Images of the diff or a link to the PR, issue, or logs

[dependabot.log](https://github.com/user-attachments/files/15987008/dependabot.log)
