### ISSUE TITLE
Dependabot is not creating PRs and there are no logs

### ISSUE THREAD

**Issue by cahrens** [dependabot/dependabot-core#10096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Language version

Java 17

### dependabot.yml content

https://github.com/DataBiosphere/terra-resource-buffer/blob/master/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I am enabling dependabot on the repository, using the same dependabot.yml file that works for us in other repositories. No PRs have been opened, and I see the following message in Insights, but the logs are empty.

Version update 848295178
Errored with the message "Dependabot encountered an unknown error"
No PRs affected 9 minutes ago [view logs](https://github.com/DataBiosphere/terra-resource-buffer/network/updates/848295178)

Dependabot encountered an unknown error
Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details. (But there aren't any)

**Comment by rujutaghanekar** [comment]
I think I am experiencing similar issue. In my case, I am using the gomod environment.
And logs exist mentioning PR creation:
```
updater | 2024/06/28 04:46:06 INFO <job_848580854> Creating a pull request for 'dependencies'
...
updater | 2024/06/28 04:54:06 INFO <job_848580854> Finished job processing
updater | 2024/06/28 04:54:06 INFO Results:
updater | +------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | github.com/**** ( from 1.56.1 to 1.57.0 ), github.com/aws/aws-sdk-go-v2 ( from 1.26.1 to 1.30... |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
```
However, no PR is actually created. It was working fine till yesterday. 
Dependabot configuration:
```
version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Asia/Kolkata"
  groups:
    dependencies:
      patterns:
        - "*"
  commit-message:
    prefix: "gomod"
    include: "scope"
  labels:
  - "dependencies"
 ```
