### ISSUE TITLE
Ignore is not respecting in a group dependencies

### ISSUE THREAD

**Issue by AlexcastroDev** [dependabot/dependabot-core#10122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

2.4

### Language version

ruby 3.2.2

### dependabot.yml content

version: 2

updates:
  - package-ecosystem: "bundler" 
    directory: "/" 
    schedule:
      interval: "daily"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
 dependabot.yml-file#ignore
    ignore:
      - dependency-name: "parser"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

### Updated dependency

parser

### What you expected to see, versus what you actually saw

I want to ignore all major and minor, only accept patches, but it changing my Gemlock to major.

### Smallest manifest that reproduces the issue

https://github.com/AlexcastroDev/dependabot_parse/pull/1

**Comment by AlexcastroDev** [comment]
Updates: if I ignore all version, it works, but if I ignore major and minor, dependabot create a PR updating major version

**Comment by tvdijen** [comment]
I suspect I have the same issue [here](https://github.com/simplesamlphp/simplesamlphp-module-authX509/pull/14) with Dependabot-config [here](https://github.com/simplesamlphp/simplesamlphp-module-authX509/blob/master/.github/dependabot.yml)

**Comment by neotrow** [comment]
+1 

We have the use case where we would like to exclude major updates for certrain dependencies for a group:
```
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.EntityFrameworkCore"
        update-types: ["version-update:semver-major"]
    groups:
      nuget-ecosystem:
        patterns:
          - "*"
```

Because we use dotnet 8 and don't want to update `Microsoft.EntityFrameworkCore` to 9.x. 

But this above code won't work and will still produce an update for `Microsoft.EntityFrameworkCore` to 9.x which is really annoying.
