### ISSUE TITLE
Using Directories in dependabot.yml gives error

### ISSUE THREAD

**Issue by CAKDanny** [dependabot/dependabot-core#10136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### dependabot.yml content

``` YML
version: 2
registries:
   nugetorg:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: "nuget"
    directories: 
      - "/test/<>"
      - "/source/<>"
    schedule:
      interval: "daily"
    groups:
      opentelemetry:
        patterns:
          - "OpenTelemetry*"  
          - "Splunk.OpenTelemetry*"
      microsoft:
        patterns:
          - "Microsoft*"   
          - "System.Diagnostics.DiagnosticSource"   
      serilog:
        patterns:
          - "Serilog*"
      swashbuckle:
        patterns:
          - "Swashbuckle*"
      aspnetcore:
        patterns:
          - "AspNetCore*"    
    milestone: $(WorkItemId)  
    ignore:
      - dependency-name: "SolidToken.SpecFlow.DependencyInjection"
    labels:
      - "DependaBot"
      - "Nuget"
      - "LCM"
    open-pull-requests-limit: 30
    registries:
      - nugetorg
```

### What you expected to see, versus what you actually saw

Dependabot says this in the logs:
`
##[error]The value 'directory' in dependency update config is missing
`
