### ISSUE TITLE
Dependabot not closing "old" PRs after proposing updates for newer versions of the same dependency

### ISSUE THREAD

**Issue by ferrarimarco** [dependabot/dependabot-core#10169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip and others

### Package manager version

N/A

### Language version

N/A

### Manifest location and content before the Dependabot update

[dependencies/python/checkov.txt](https://github.com/super-linter/super-linter/blob/main/dependencies/python/checkov.txt)

### dependabot.yml content

https://github.com/super-linter/super-linter/blob/main/.github/dependabot.yml

### Updated dependency

Happens with several dependencies.

Example: `checkov`

From:

### What you expected to see, versus what you actually saw

Dependabot should close PRs that propose old versions of the same dependencies.
The example is about `pip` and `python`, but happens with other ecosystems as well.

This looks like a regression.

Thanks for your support!

### Native package manager behavior

Not needed because the dependency updates are proposed as expected. The issue is that Dependabot doesn't close old PRs about the same dependency.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/super-linter/super-linter/pull/5848
https://github.com/super-linter/super-linter/pull/5831
https://github.com/super-linter/super-linter/pull/5803
https://github.com/super-linter/super-linter/pull/5782

### Smallest manifest that reproduces the issue

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    commit-message:
      prefix: "deps(python)"
    directory: "/dependencies/python/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
```

**Comment by Elikill58** [comment]
It doesn't appear in my case with maven. Maybe it's only related to python or with specific options
My config:
```yml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
```
