### ISSUE TITLE
Permit overlapping rules

### ISSUE THREAD

**Issue by jonhoo** [dependabot/dependabot-core#10160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

After a lot of fiddling with dependabot rules for the Rust (well, `cargo`) ecosystem over the years, I thought I'd finally arrived at [a dependabot configuration](https://github.com/jonhoo/rust-ci-conf/blob/dcf68836181145511a35a269e8392d0a0f0c61e1/.github/dependabot.yml) that follows Rust's preferred semantics for updates without too much noise:

- Major versions should get dedicated PRs, should update `Cargo.toml`, and should happen in a timely fashion.
- Minor/patch version updates should never touch `Cargo.toml`, should happen jointly in a single PR, and should happen on a regular-but-sparse cadence.

Unfortunately, no such luck; the setup I'd come up with requires multiple dependabot rules for the `cargo` package ecosystem, and that is [disallowed](https://github.com/jonhoo/obs-do/runs/27126328084), giving the error:

> Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'. Ecosystem 'cargo' has overlapping directories.

They're not _technically_ overlapping since they have `ignore` clauses that make them distinct, though I suspect it'd be quite difficult to have dependabot check for that property for arbitrary `ignore` blocks.

Ultimately, I'd love to see dependabot approach rules the same way it approaches the new(ish) `groups`, specifically:

> Dependabot creates groups in the order they appear in your `dependabot.yml file`. If a dependency update could belong to more than one group, it is only assigned to the first group it matches with.

That is, for overlapping rules to be permitted where the first one that matches takes precedence. That would unlock use-cases like mine, which as far as I can tell at least cannot be achieved with dependabot's current configuration structure.

**Comment by jonhoo** [comment]
Worth pointing out that with https://github.com/dependabot/dependabot-core/issues/4009, I could get _pretty_ close with a single rule with multiple `groups`, though I'd have to settle for using a single cadence for all update types.

**Comment by mistic100** [comment]
Another usecase for this request : configure different update interval for specific NPM packages. Here I try to get daily NPM updates but for eslint/stylelint.

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - mistic100
    ignore:
      - dependency-name: '*eslint*'
      - dependency-name: '*stylelint*'
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor']
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    assignees:
      - mistic100
    allow:
      - dependency-name: '*eslint*'
      - dependency-name: '*stylelint*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor']
```

See alos #8938
