### ISSUE TITLE
Add a groups option for matched directory when using directories

### ISSUE THREAD

**Issue by anthonysomerset** [dependabot/dependabot-core#10200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Tangentially related to #10090 

I can workaround that issue there by using the `groups` config, specifically in my case:

```
  - package-ecosystem: "terraform" # See documentation for possible values
    directories: 
      - "/*" # Location of package manifests
    groups:
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"
    schedule:
      interval: "weekly"
```

this works but gives me 1 PR basically, i would like to support a scenario where i could configure a groups config option that would create a PR for each matched directory, for example

```
  - package-ecosystem: "terraform" # See documentation for possible values
    directories: 
      - "/*" # Location of package manifests
    groups:
      matched-directories-group:
        group-by: directories
    schedule:
      interval: "weekly"

```

so for a given set of directories

```
azure-networking
azure-dns
azure-firewall
```

it would create 3 PR's, one for each folder with the folder mentioned in the PR subject
