### ISSUE TITLE
Add Support For Breaking Change In Conventional Commit Messages

### ISSUE THREAD

**Issue by fergoid** [dependabot/dependabot-core#10221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When managing dependencies on major version for our code base we perform automated version bumping.  Since we want to indicate to our own consumers that there may be an update that requires them to make a change in their code being able to convey this in the pull request commit message will help (as we will do a major version bump on our own code as a result).

With conventional commits this can be done in one of two ways
```
fix(scope)!: some commit message
```
or
```
fix(scope): some commit message

BREAKING CHANGE: this will break stuff
```
So there are two ways we could go, make the change specific to breaking changes with a `breaking change` option or be more flexible and add a commit footer option. The latter would allow dependabot users to use the footer for other purposes as well as breaking changes.
```
    commit-message:
      prefix: "fix"
      include: "scope"
      footer: "BREAKING CHANGE: major version update"
```
