### ISSUE TITLE
"Dependabot ran out of disk space during its update" in a Git LFS Repository

### ISSUE THREAD

**Issue by hf-kklein** [dependabot/dependabot-core#10273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### dependabot.yml content

```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/dependencies" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "@Hochfrequenz/python-developers-review-team"
  # ...
```

### What you expected to see, versus what you actually saw

I expect Github to update the dependencies in various requirements.txt files in the specified directory.

My best guess is, that dependabot runs out of disk space because the repository is a LFS repository with lots of data. It's actually public:
https://github.com/Hochfrequenz/edi_energy_mirror

What I actually saw is:
> Dependabot ran out of disk space during its update
Dependabot failed to update your dependencies because there was not enough disk space available.

>  proxy | 2024/07/22 05:54:08 proxy starting, commit: f375444b32b70ee41e6084e7b6ffc09599dcc194
  proxy | 2024/07/22 05:54:08 Listening (:1080)
updater | 2024-07-22T05:54:09.102045576 [858535007:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-07-22T05:54:11Z" level=info msg="guest starting" commit=226fd9d91dcda64ed8ff9c59ecfef72fe02fe945
updater | time="2024-07-22T05:54:11Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=858535007 updater_timeout=45m0s updater_version=1e2315df764599c2612d5cf44ae1e3f3ed88a1b9-pip
updater | 2024/07/22 05:54:15 INFO <job_858535007> Starting job processing
updater | 2024/07/22 05:54:15 INFO <job_858535007> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"include-scope":null,"prefix":null,"prefix-development":null},"credentials-metadata":[{"host":"github.com","type":"git_source"}],"debug":null,"dependencies":null,"dependency-group-to-refresh":null,"dependency-groups":[],"existing-group-pull-requests":[],"existing-pull-requests":[],"experiments":{"dependency-change-validation":true,"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"pip","proxy-log-response-body-on-auth-failure":true,"reject-external-code":false,"repo-private":false,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"api-endpoint":"https://api.github.com/","branch":null,"directory":"/dependencies","hostname":"github.com","provider":"github","repo":"Hochfrequenz/edi_energy_mirror"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false}}
updater | 
  proxy | 2024/07/22 05:54:15 [002] GET https://github.com:443/Hochfrequenz/edi_energy_mirror/info/refs?service=git-upload-pack
  proxy | 2024/07/22 05:54:15 [002] * authenticating git server request (host: github.com)
  proxy | 2024/07/22 05:54:15 [002] 200 https://github.com:443/Hochfrequenz/edi_energy_mirror/info/refs?service=git-upload-pack
  proxy | 2024/07/22 05:54:15 [004] POST https://github.com:443/Hochfrequenz/edi_energy_mirror/git-upload-pack
  proxy | 2024/07/22 05:54:15 [004] * authenticating git server request (host: github.com)
  proxy | 2024/07/22 05:54:15 [004] 200 https://github.com:443/Hochfrequenz/edi_energy_mirror/git-upload-pack
  proxy | 2024/07/22 05:54:15 [006] POST https://github.com:443/Hochfrequenz/edi_energy_mirror/git-upload-pack
  proxy | 2024/07/22 05:54:15 [006] * authenticating git server request (host: github.com)
  proxy | 2024/07/22 05:54:15 [006] 200 https://github.com:443/Hochfrequenz/edi_energy_mirror/git-upload-pack
  proxy | 2024/07/22 05:55:08 Posting metrics to remote API endpoint
  proxy | 2024/07/22 05:55:08 Successfully posted metrics data via api client
updater | 2024/07/22 05:55:22 ERROR <job_858535007> Error during file fetching; aborting: Dependabot::OutOfDisk
updater | 2024/07/22 05:55:23 INFO <job_858535007> Finished job processing
updater | 2024/07/22 05:55:23 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------+
updater | |   Errors    |
updater | +-------------+
updater | | out_of_disk |
updater | +-------------+
updater | time="2024-07-22T05:55:23Z" level=info msg="task complete" container_id=job-858535007-file-fetcher exit_code=0 job_id=858535007 step=fetcher
updater | time="2024-07-22T05:55:23Z" level=warning msg="failed during fetch, skipping updater" job_id=858535007
