### ISSUE TITLE
Problem with grouping updates

### ISSUE THREAD

**Issue by Maggus85** [dependabot/dependabot-core#10287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### Language version

C#

### dependabot.yml content

```
version: 2
registries:
  farm-cloud:
    type: nuget-feed
    url: https://agrisolutionseu.pkgs.visualstudio.com/_packaging/FarmCloud/nuget/v3/index.json
    token: PAT:${{VSS_NUGET_ACCESSTOKEN}}
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
schedule:
  interval: "daily"
updates:
  - package-ecosystem: "nuget"
    directory: 
      - /src/API/AS.FarmCloud.Sensor.Storage/
    open-pull-requests-limit: 20
    registries:
      - farm-cloud
      - nuget
groups:
  internal-libs:
    applies-to: version-updates
    patterns:
      - "AS.Farm*
  external-libs:
    applies-to: version-updates
    patterns:
      - *
```
  

### What you expected to see, versus what you actually saw

I wanted to create one pr that updates the packages from our internal feed and a second that updates the others nugets.
For this reason, I added a section

```
groups:
  internal-libs:
    applies-to: version-updates
    patterns:
      - "AS.Farm*"
  external-libs:
    applies-to: version-updates
    patterns:
      - "*"

```
Without this section, everything works, but a lot of pr is created, which is not the expected behavior

Translated with DeepL.com (free version)

### Images of the diff or a link to the PR, issue, or logs

```
running NuGet updater:
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/tmp/agrisolutionseu/Agri\%20Solutions/_git/FarmCloud --solution-or-project /home/dependabot/dependabot-updater/tmp/agrisolutionseu/Agri\%20Solutions/_git/FarmCloud/src/API/AS.FarmCloud.Sensor.Storage/tests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests.csproj --dependency coverlet.collector --new-version 6.0.2 --previous-version 3.0.3 --result-output-path /tmp/update-result.json --verbose
  No dotnet-tools.json file found.
  No global.json file found.
Running for project file [src/API/AS.FarmCloud.Sensor.Storage/tests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests.csproj]
Updating project [/home/dependabot/dependabot-updater/tmp/agrisolutionseu/Agri%20Solutions/_git/FarmCloud/src/API/AS.FarmCloud.Sensor.Storage/tests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests.csproj]
  Running for SDK-style project
    Package [coverlet.collector] already meets the requested dependency version in [/home/dependabot/dependabot-updater/tmp/agrisolutionseu/Agri%20Solutions/_git/FarmCloud/src/API/AS.FarmCloud.Sensor.Storage/tests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests/AS.FarmCloud.Sensor.Storage.Domain.UnitTests.csproj].
Update complete.
  Writing update result to [/tmp/update-result.json].
I, [2024-07-24T19:53:23.971283 #7]  INFO -- : update result: {
  "ErrorType": null,
  "ErrorDetails": null
}
Submitting coverlet.collector pull request for creation.
E, [2024-07-24T19:53:23.973486 #7] ERROR -- : Error while generating commit message: Passed `nil` into T.must
E, [2024-07-24T19:53:23.973531 #7] ERROR -- : /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/_types.rb:222:in `must'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:285:in `pr_name_directory'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:185:in `solo_pr_name'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11493/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:115:in `pr_name'

```
