### ISSUE TITLE
Python requirements.txt index-url is used for all dependencies instead of the specific

### ISSUE THREAD

**Issue by nikstuckenbrock** [dependabot/dependabot-core#10313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip 23.0.1

### Language version

Python 3.11.2

### Manifest location and content before the Dependabot update

```requirements.txt
fastapi[all]==0.111.0
fastapi-azure-auth==4.4.0
beanie==1.26.0
fastapi-pagination==0.12.25
fastapi-cache2==0.2.1

--index-url https://mypersonalinstance/api/v4/projects/123/packages/pypi/simple
my-personal-package==5.6.7
```

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: pip
    insecure-external-code-execution: "allow"
    directory: /
    schedule:
      interval: daily
```

### What you expected to see, versus what you actually saw

I expected the dependabot to resolve the dependencies before the `--index-url` using the deafault pypi registry and after that using the custom private registry, but it turns out it tries to resolve all dependencies using the given `--index-url`.

### Native package manager behavior

The described expected behavior.

### Smallest manifest that reproduces the issue

Given above.

**Comment by v-thavaahariharangit** [comment]
Tested and working as expected

Repo: https://github.com/dsp-testing/python-dependabot-private-registry-issue-10313

Requirements.txt
```
fastapi[all]==0.111.0
fastapi-azure-auth==4.4.0
beanie==1.26.0
fastapi-pagination==0.12.25
fastapi-cache2==0.2.1

--extra-index-url https://jfrogghdemo.jfrog.io/artifactory/api/pypi/dependabot-pip/simple
thavaahariharangit_project==0.1.0
```
Note: use `--extra-index-url`

dependabot.yml
```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    registries:
      - python-artifactory

registries:
  python-artifactory:
    type: "python-index"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/pypi/dependabot-pip/simple"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.PYTHON_TOKEN }}"
```
Note: no `replaces-base: true`

PR's generated as per the expectation

<img width="1563" height="593" alt="Image" src="https://github.com/user-attachments/assets/393ecaae-5fed-4d11-a5ed-9b1bb2eff116" />
