### ISSUE TITLE
Python multi-dir update results in duplicate PRs

### ISSUE THREAD

**Issue by jakecoffman** [dependabot/dependabot-core#10340]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Python

### What you expected to see, versus what you actually saw

Reproducible with the following input file:

```yml
job:
  allowed-updates:
    - dependency-type: direct
      update-type: all
  package-manager: pip
  source:
    provider: github
    repo: opentracing-contrib/nginx-opentracing
    commit: 69dd153598307375363650ea301c92cb59d997f3
    api-endpoint: https://api.github.com/
    hostname: github.com
    directories:
      - "/**/*"
```

Run with the Dependabot CLI: `dependabot update -f input.yml`

The issue seems to be caused by the FileFetcher's behavior in the Python ecosystem of searching subdirectories for requirements files:

https://github.com/dependabot/dependabot-core/blob/4420d677450d0e685c6b2f49aed16a3b14aec788/python/lib/dependabot/python/file_fetcher.rb#L243-L257

This results in the same requirements file appearing twice, thus it puts up 2 PRs.

We'll need to analyze why this behavior exists and maybe remove it. Ideally Dependabot would only process the directory it was given.
