### ISSUE TITLE
Dependabot cannot detecting changes when Both .NET SDK and Alpine version changed

### ISSUE THREAD

**Issue by WuDotNetTech** [dependabot/dependabot-core#10385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Package manager version

nuget 6.10.0.97

### Language version

.NET 8.0

### Manifest location and content before the Dependabot update

FROM mcr.microsoft.com/dotnet/sdk:8.0.301-alpine3.18-amd64 AS build
WORKDIR "/src"
COPY . .
RUN dotnet restore MyTestProbject.sln

### dependabot.yml content

``` yaml
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    # target-branch: "develop" # target branch      
    open-pull-requests-limit: 10 # higher limit if needed
    groups: # ensure to have a group updates
      all-updates:
        patterns:
          - "*"
    allow: # allow all dependencies updates
      - dependency-type: "all"              
    commit-message:
      prefix: "[docker] "
    # ignore:  
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
```

### What you expected to see, versus what you actually saw

According to https://mcr.microsoft.com/v2/dotnet/sdk/tags/list listed version.  the latest is version 8.0.303.

and I want to see the `8.0.301-alpine3.18-amd64` updated to  `8.0.303-alpine3.19-amd64`
