### ISSUE TITLE
Apply `open-pull-requests-limit` to multiple directories

### ISSUE THREAD

**Issue by iainlane** [dependabot/dependabot-core#10395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have a monorepo. Inside there are a bunch of projects which have `Dockerfile`s. The projects tend to be written similarly, which means they have a common base image. We're currently listing each one out with separate `directory` entries. When the base image gets bumped we can get flooded with pull requests. The flood is not too bad in itself, but there are knock-on effects: each PR triggers several Actions workflows and we quickly get rate limited.

I'm looking for ways around it, to stagger the opening of PRs.

I've just tried out the newish `directories` feature because I thought it might let me achieve this. But upon experimentation it doesn't, unfortunately. Given the following configuration:

```yaml
version: 2
updates:
  - package-ecosystem: docker
    directories:
      - /a
      - /b
      - /c
      - /d
      - /e
      - /f
      - /g
      - /h
      - /i
      - /j
      - /k
      - /l
      - /m
      - /n
      - /o
      - /p
      - /q
      - /r
      - /s
      - /t
      - /u
      - /v
      - /w
      - /x
      - /y
      - /z
    schedule:
      interval: daily
      time: "06:00"
    open-pull-requests-limit: 10
```

...a `Dockerfile` in each one containing `FROM golang:1.22.5`, and a pending update to `1.22.6` (this is the situation at the time of writing), I wanted to receive 10 PRs at a time each day until we were done.

What I got instead was 26 PRs. Firstly I couldn't quite tell from [the documentation][docs] what to expect here. It wasn't clear if `directories` is a shorthand for writing out the same thing multiple times or if it created one group. That meant I had to experiment.

After reading the docs even harder it seems there's not a way to do this at the minute, so the feature request is for a way to let `open-pull-requests-limit` apply to an entire `directories` block, or something like that. A global limit per-ecosystem would work for us too.

The second thing I tried was adding:

```yaml
    groups:
      golang:
        patterns:
          - golang
```

What this does is create 1 PR with 26 updates, and that means we can merge all or none of the updates at once. That's a bit challenging as the different images are owned by different teams.

[docs]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories
