### ISSUE TITLE
Dependabot raising PR for only one directory when multiple directories in a group are affected

### ISSUE THREAD

**Issue by cpswan** [dependabot/dependabot-core#10428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Package manager version

NA

### Language version

NA

### Manifest location and content before the Dependabot update

In https://github.com/atsign-foundation/at_server

```
./packages/at_root_server/Dockerfile
./tools/build_virtual_environment/ve_base/Dockerfile
./tools/build_virtual_environment/ve/Dockerfile.vip
./tools/build_virtual_environment/ve/Dockerfile.canary_to_vip
./tools/build_virtual_environment/ve/Dockerfile
./tools/build_secondary/Dockerfile.observe
./tools/build_secondary/Dockerfile.canary_to_prod
./tools/build_secondary/Dockerfile
```

https://github.com/atsign-foundation/at_server/pull/2059/files provides an example of the Dockerfile diff

### dependabot.yml content

https://github.com/atsign-foundation/at_server/blob/trunk/.github/dependabot.yml contains:

```yaml
version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/tools/build_secondary"
      - "/tools/build_virtual_environment/ve"
      - "/tools/build_virtual_environment/ve_base"
      - "/packages/at_root_server"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directories:
      - "/packages/at_root_server"
      - "/packages/at_secondary_server"
    schedule:
      interval: "daily"
    groups:
      pub:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/tools" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      pip:
        patterns:
          - "*"
```

### Updated dependency

Bumps the docker group with 2 updates in the /tools/build_virtual_environment/ve_base directory: dart and debian.

Updates `dart` from `47385e3` to `17d83a1`

Updates `debian` from stable-20240722-slim to stable-20240812-slim

### What you expected to see, versus what you actually saw

This should have been: Bump the docker group across 4 directories with 2 updates.

In a similar repo, that shares similar dependencies a [PR](https://github.com/atsign-foundation/noports/pull/1261) was correctly opened for: Bump the docker group across 2 directories with 2 updates

Dependabot has previously managed to correctly [raise a PR](https://github.com/atsign-foundation/at_server/pull/2011) for a similar set of dependency bumps on this repo.

### Native package manager behavior

NA

### Images of the diff or a link to the PR, issue, or logs

Original PR was https://github.com/atsign-foundation/at_server/pull/2058 but I went into Insights to re-run Dependabot as I know that Debian bumps flow through to Dart bumps (and I'd seen a PR with both in another repo). That resulted in https://github.com/atsign-foundation/at_server/pull/2059 being opened (and 2058 being closed). But nothing for the other 3 directories.
