### ISSUE TITLE
Configure Maven profile for dependency updates

### ISSUE THREAD

**Issue by fbiville** [dependabot/dependabot-core#10431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### dependabot.yml content

version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily

### Updated dependency

org.neo4j.driver:neo4j-java-driver

### What you expected to see, versus what you actually saw

https://github.com/liquibase/liquibase-neo4j is built with Maven.

The regular build has a JDK 8 baseline and [uses the 4.4 Neo4j Java driver](https://github.com/liquibase/liquibase-neo4j/blob/f5febb4d0c2e6b4cdb976b621783f6df39a1a552/pom.xml#L51). This is what gets built and released to users.

Dependabot has nicely kept the Neo4j driver up-to-date there (see [latest example](https://github.com/liquibase/liquibase-neo4j/commit/25e75768e2e164653c0df485dde00d3825e4329e)).

There is another build variant that just makes sure the 5.x Neo4j Java driver (which requires a JDK 17) passes the end-to-end tests just fine. This is a nice safety check for users running that kind of setup.
This variant is defined with [a Maven profile](https://github.com/liquibase/liquibase-neo4j/blob/f5febb4d0c2e6b4cdb976b621783f6df39a1a552/pom.xml#L190-L217).

I have not found a way to tell Dependabot to also watch for updates for the 5.x Neo4j Java driver there.

Since I'm not a robot 🤖, [I actually missed a few releases](https://github.com/liquibase/liquibase-neo4j/commit/ae84f762d8ae8852d4e3d579cdd7933a711a9b1a) before realizing the 5.x Neo4j driver was not up-to-date.

I would love to be able to add an extra configuration entry to `dependabot.yml` along the lines of:

```
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  activated-profiles: ["5x-driver"] # this is not available today
  allow: ["org.neo4j.driver:neo4j-java-driver"]
```
