### ISSUE TITLE
Dependabot is not running the check for updates as per the scheduled time (Delay time varies)

### ISSUE THREAD

**Issue by thavaahariharangit** [dependabot/dependabot-core#10455]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

all ecosystem

### Manifest location and content before the Dependabot update

Scheduled check for updates in 5 minutes future

https://github.com/dsp-testing/e2e-6738/blob/main/.github/dependabot.yml

```
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "12:30"
    ignore:
      - dependency-name: lodash
        versions: "> 4.17.21"
```
12:30 UTC time

and waiting for an hour now, I dint see any update yet

### What you expected to see, versus what you actually saw

actual
![Image](https://github.com/user-attachments/assets/02ffead7-984c-48fe-9345-698a16f0ff0b)

expected 

One more run in 10 minutes
