### ISSUE TITLE
Python 3.12.5 not supported by dependabot

### ISSUE THREAD

**Issue by Greesb** [dependabot/dependabot-core#10469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

poetry

### Package manager version

poetry `1.8.3`

### Language version

Python `3.12.5`

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      # yamllint disable-line rule:quoted-strings
      time: "08:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*"
        dependency-type: all
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      # yamllint disable-line rule:quoted-strings
      time: "08:00"
      timezone: Europe/Paris
    ignore:
      # Dependabot fails when GitHub action is internal or private
      - dependency-name: mergifyio/heroku-oidc
```

### What you expected to see, versus what you actually saw

Expected dependabot to successfully upgrade dependencies, but it failed with the following error:
```text
updater | 2024/08/20 06:50:04 ERROR <job_871632205> Error during file fetching; aborting: Dependabot detected the following Python requirement for your project: '>=3.12.5,<4.0'.

Currently, the following Python versions are supported in Dependabot: 3.12.*, 3.11.*, 3.10.*, 3.9.*, 3.8.*.
```

`3.12.*` should include `3.12.5`
