### ISSUE TITLE
Dependabot encountered an unknown error

### ISSUE THREAD

**Issue by AlexWayfer** [dependabot/dependabot-core#10513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Language version

Ruby '>= 3.0', '< 4'

### Manifest location and content before the Dependabot update

`/flame_app_generator.gemspec`

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    groups:
      bundler:
        patterns:
          - 'bundler'
          - 'bundler-*'
      toys:
        patterns:
          - 'toys'
          - 'toys-*'
          - '*_toys'
      rubocop:
        patterns:
          - 'rubocop'
          - 'rubocop-*'
      simplecov:
        patterns:
          - 'simplecov'
          - 'simplecov-*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      remark:
        patterns:
          - 'remark'
          - 'remark-*'
```

### What you expected to see, versus what you actually saw

Running Dependabot.

### Native package manager behavior

OK.

### Images of the diff or a link to the PR, issue, or logs

```
updater | /home/dependabot/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:77:in `eval': (eval at /home/dependabot/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:77):1: syntax error, unexpected ',', expecting end-of-input (SyntaxError)
'>= 3.0', '< 4'
```

https://github.com/AlexWayfer/flame_app_generator/actions/runs/10604867879/job/29392453827

[logs_27725288555.zip](https://github.com/user-attachments/files/16789363/logs_27725288555.zip)
