### ISSUE TITLE
Directory with special characters incorrectly flagged as containing glob

### ISSUE THREAD

**Issue by csssuf** [dependabot/dependabot-core#10525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### dependabot.yml content

https://github.com/csssuf/dependabot-special-char-glob/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I expected dependabot to validate the configuration and run against the target directory, but instead, it reports `The property '#/updates/0/directory' must not include a glob pattern`. This is true with various combinations of escape characters (escaping space, escaping `{`/`}`, and both/neither).

### Images of the diff or a link to the PR, issue, or logs

https://github.com/csssuf/dependabot-special-char-glob/runs/29485132581

### Smallest manifest that reproduces the issue

The linked repo is already a minimal repro.

**Comment by luzfcb** [comment]
Maintainers of template projects based on https://github.com/cookiecutter/cookiecutter and https://github.com/copier-org/copier are also experiencing this issue. Both projects use the Jinja2 syntax to define placeholders in directory and file names, which involves the use of `{{` and `}}`.

After reviewing the changelog, it seems that this particular real-world use case not have been thoroughly tested when https://github.blog/changelog/2024-06-25-simplified-dependabot-yml-configuration-with-multi-directory-key-directories-and-wildcard-glob-support/ was implemented.

Related support ticket https://support.github.com/ticket/personal/0/3007442

**Comment by luzfcb** [comment]
This error still happens in production https://github.com/cookiecutter/cookiecutter-django/runs/31435188434

**Comment by cmahnke** [comment]
This also happens if there is a space (' ') character in the path.

This one is related, but this is certainly not a fix (just in case they're somehow related):
https://github.com/dependabot/dependabot-core/issues/10527

**Comment by welsh** [comment]
> Maintainers of template projects based on https://github.com/cookiecutter/cookiecutter and https://github.com/copier-org/copier are also experiencing this issue. Both projects use the Jinja2 syntax to define placeholders in directory and file names, which involves the use of `{{` and `}}`.
> 
> After reviewing the changelog, it seems that this particular real-world use case not have been thoroughly tested when https://github.blog/changelog/2024-06-25-simplified-dependabot-yml-configuration-with-multi-directory-key-directories-and-wildcard-glob-support/ was implemented.
> 
> Related support ticket https://support.github.com/ticket/personal/0/3007442

I was able to work around by using the wildcard pattern for my maven cookiecutter:
```yaml
version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
```
I originally wanted to target:
```yaml
    directory: "{{cookiecutter.output_dir}}"
```
But this worked well enough.

**Comment by v-abhishekbhaskar** [comment]
Issue has been fixed. Special characters need to be escaped with `\\` in the dependabot config file.
Sample dependabot.yml provided below:
```
# Sample dependabot.yml file to test curly brace directory handling
#
# This file demonstrates various directory patterns that should work
# after the fix for GitHub issue #10525
version: 2

updates:
  # Test case 1: Template directories (the original issue)
  # These should now be accepted after the fix
  - package-ecosystem: "pip"
    directory: "\\{\\{ dir.with.special.chars \\}\\}"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
```

Attaching screenshot of the fix in a test repo:

<img width="1723" height="965" alt="Image" src="https://github.com/user-attachments/assets/ab0531ba-03ab-4bfc-913d-c3c584b203df" />

<img width="1724" height="999" alt="Image" src="https://github.com/user-attachments/assets/25fa3cde-366f-49ca-87c9-fb511dff3fc3" />
