### ISSUE TITLE
Incorrect TOML parsing of multi-line literal strings for `pyproject.toml`

### ISSUE THREAD

**Issue by daniil-berg** [dependabot/dependabot-core#10523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Description

Apparently Dependabot is using the very outdated and poorly supported [`toml`](https://github.com/uiri/toml) package to parse the `pyproject.toml` for some reason. It seems the people that wrote the Python helpers were aware that TOML support was included in Python 3.11, yet still use that third-party package here:

https://github.com/dependabot/dependabot-core/blob/7835cbdad710c359c689a22021d5daab77d09b3c/python/helpers/lib/parser.py#L17-L19

This causes a very ugly and hard to decipher error, if you are unlucky enough (as I was) to have a [multi-line string literal](https://toml.io/en/v1.0.0#string) in your `pyproject.toml` with certain characters that trip up the parser. I have not looked into the implementation of that `toml` package, so I don't know _exactly_ what the cause of the error is. But it was frustrating enough to try and figure out, what caused Depenadabot to fail. Turns out, it was this array:

```toml
exclude_also = [
    '''if __name__ == ['"]__main__['"]:''',
]
```

<details>
<summary>Click here to see the full TOML file</summary>

```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dependabot-pyproject-toml-error"
description = '''foo'''
version = "0.0.1"
requires-python = ">=3.12"
license = { text = "GNU General Public License v3 or later (GPLv3+)" }
classifiers = [
    '''Development Status :: 4 - Beta''',
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    '''pydantic==2.7.0''',
]

[tool.coverage.report]
exclude_also = [
    '''if __name__ == ['"]__main__['"]:''',
]
```

There are a few experiments with triple quotes here to figure out, what worked and what didn't.

</details>

Here is the traceback from the Dependabot error log:

```
Traceback (most recent call last):
  File "/opt/python/run.py", line 16, in <module>
    print(parser.parse_pep621_dependencies(args["args"][0]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/parser.py", line 27, in parse_pep621_dependencies
    project_toml = toml.load(pyproject_path)['project']
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.12.5/lib/python3.12/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.12.5/lib/python3.12/site-packages/toml/decoder.py", line 213, in loads
    raise TomlDecodeError("Key name found without value."
toml.decoder.TomlDecodeError: Key name found without value. Reached end of line. (line 22 column 2 char 534)
```

See the [full log here](https://github.com/daniil-berg/dependabot-pyproject-toml-error/actions/runs/10632673662/job/29476101479).

To reproduce, you can fork this minimal repo: [daniil-berg/dependabot-pyproject-toml-error](https://github.com/daniil-berg/dependabot-pyproject-toml-error)

Trigger Dependabot checks, see the error.
Remove the lines mentioned above from `pyproject.toml`, trigger Dependabot again, see it work without errors. 

Needless to say, this is a bug because that string literal is valid TOML and meaningful for regular expressions etc.

---

It is surprising to me that the built-in [`tomllib`](https://docs.python.org/3/library/tomllib.html) is not used, since Dependabot already uses Python 3.12 by default.

If there are ways to use Dependabot with an _older_ Version of Python, (first of all, please let me know **how** you can do that) then you could still use a package like [`tomli`](https://github.com/hukkin/tomli), which is faster, up-to-date, and has no issues parsing the `pyproject.toml` shown above. It works with Python `>=3.8` and is actually the basis for the built-in library in Python `>=3.11`.

Maybe I'll find the time this weekend to provide PR for this. But since I am not sure, I wanted to leave this issue here.

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '12:00'
      timezone: 'Europe/Berlin'
```

### What you expected to see, versus what you actually saw

Expected no errors.

Actually saw [this](https://github.com/daniil-berg/dependabot-pyproject-toml-error/actions/runs/10632673662/job/29476101479).

### Smallest manifest that reproduces the issue

```toml
# pyproject.toml

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dependabot-pyproject-toml-error"
description = '''foo'''
version = "0.0.1"
requires-python = ">=3.12"
license = { text = "GNU General Public License v3 or later (GPLv3+)" }
classifiers = [
    '''Development Status :: 4 - Beta''',
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    '''pydantic==2.7.0''',
]

[tool.coverage.report]
exclude_also = [
    '''if __name__ == ['"]__main__['"]:''',
]
```
