### ISSUE TITLE
PR Summary includes nonsensical leading `/` in path

### ISSUE THREAD

**Issue by jsoref** [dependabot/dependabot-core#10547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github

### Manifest location and content before the Dependabot update

There is no dependabot configuration committed to the repository.

https://github.com/jsoref/case/settings/security_analysis
- [x] Dependabot alerts
- [x] Dependabot security updates
- [x] Dependabot on Actions runners

https://github.com/jsoref/case/pull/1

### Updated dependency

```
actions/download-artifact@v2
```

### What you expected to see, versus what you actually saw

Actual PR summary:
`Bump actions/download-artifact from 2 to 4.1.7 in /.github/workflows`

Expected PR summary (one of):
* `Bump actions/download-artifact from 2 to 4.1.7 in .github/workflows`
* `Bump actions/download-artifact from 2 to 4.1.7 in .github/workflows/spelling.yml `

### Smallest manifest that reproduces the issue

A subset of: https://github.com/jsoref/case/blob/4971ebfb1f7224a06eb7478195de206e1188cfeb/.github/workflows/spelling.yml#L1-L27

```yaml
on:
  push:

jobs:
  spelling:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: checkout-merge
      uses: actions/checkout@v2
```
