### ISSUE TITLE
Dependabot fails to upgrade package with index using Pipenv

### ISSUE THREAD

**Issue by ysk24ok** [dependabot/dependabot-core#10578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Pipenv

### Language version

Python 3.8

### Manifest location and content before the Dependabot update

`/Pipfile` and `/Pipfile.lock`. Both exist at the root directory of the repository.

I can't share the files as they are in a private repo, but here are the rough looks.

Pipfile

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
name = "internal"
url = "..."  # Our internal package index URL
verify_ssl = true

[packages]
...
xxx = {extras = ["yyy"], version = "*", index = "internal"}
...

[requires]
python_version = "3.8"
```

Pipfile.lock
```
{
    "_meta": {
        "hash": {
            "sha256": "c7cffd3c8ce342f480c55ff642f417ad3885e1a35f636e2852fa11b82d842f96"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            },
            {
                "name": "internal",
                "url": "...",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        ...
        "xxx": {
            "extras": [
                "yyy"
            ],
            "hashes": [
                ...
            ],
            "index": "internal",
            "version": "==1.2.3"
        },
        ...
    }
}
```

```

### dependabot.yml content

```yaml
version: 2
registries:
  jfrog:
    type: python-index
    url: ...
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.TOKEN }}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - internal
    schedule:
      day: "monday"
      interval: "weekly"
      time: "07:30"
      timezone: "Asia/Tokyo"
```

### What you expected to see, versus what you actually saw

Expected to see: upgrading the version succeeds.

Actually saw: 

```
Dependabot failed to update your dependencies because there was an error resolving your Python dependency files.

Dependabot encountered the following error:

CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install xxx==1.2.3 because these package versions have conflicting dependencies.
INFO:pipenv.patched.pip._internal.resolution.resolvelib.factory:
The conflict is caused by:
    The user requested xxx==1.2.3
    The user requested (constraint) xxx==1.2.3
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
Traceback (most recent call last):
  File "/usr/local/.pyenv/versions/3.8.18/lib/python3.8/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/.pyenv/versions/3.8.18/lib/python3.8/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pipenv.patched.pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('xxx==1.2.3')
[Troubleshoot Dependabot errors](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)
```

The package is uploaded to our internal package, but we have a dummy package of the same name on PyPI as well to prevent dependency confusion attack. The dummy package has only `0.0.0` version.
My guess is that dependabot ignores the index (`internal`) and tries to load the current version (`1.2.3`) from PyPI, where only `0.0.0` is available.

**Comment by v-thavaahariharangit** [comment]
The issue could not be reproduced.

Validation was performed using the following test repository: 
🔗 [dsp-testing/python-dependabot-private-registry-issue-7947](https://github.com/dsp-testing/python-dependabot-private-registry-issue-7947)

Dependabot successfully generated a pull request: 
🔗 [PR #1](https://github.com/dsp-testing/python-dependabot-private-registry-issue-7947/pull/1)

<img width="1908" height="1036" alt="Image" src="https://github.com/user-attachments/assets/1cdf0fb3-8f10-40d9-8b13-76094aaf1671" />


`Pipfile` Configuration:
```
[[source]]
url = "https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple"
verify_ssl = true
name = "jfrog"

[packages]
requests = {version = "==2.32.2", index = "jfrog"}

[dev-packages]

[requires]
python_version = "3.12"
```

`dependabot.yml` Configuration:
```
version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    registries:
      - python-artifactory

registries:
  python-artifactory:
    type: "python-index"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.PYTHON_TOKEN }}"
    replaces-base: true
```

Note: 
I used index="jfrog" here
`requests = {version = "==2.32.2", index = "jfrog"}`
