### ISSUE TITLE
Ignore unsupported registries with Terraform

### ISSUE THREAD

**Issue by joonvena** [dependabot/dependabot-core#10572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Ignore unsupported registries. In my case my Terraform modules are stored inside GCS bucket and sourced like this:
https://developer.hashicorp.com/terraform/language/modules/sources#gcs-bucket

It would be nice that Dependabot could just ignore unsupported module sources and still continue update. Now it will just fail for unsupported module source.

**Comment by akselleirv** [comment]
Hello @joonvena, did you figure out a way to ignore those type of modules?

**Comment by joonvena** [comment]
@akselleirv unfortunately no. We ended up switching to using RenovateBot.

**Comment by akselleirv** [comment]
Thanks for the quick response! Dependabot is nice when it works, but a pain when it does not 😔

**Comment by joonvena** [comment]
We also ended up switching because Dependabot lacks behind with supported version of Terraform

**Comment by lindeskar** [comment]
Bumping this and providing another example; Terraform modules in OCI makes Dependabot break and not check _any_ dependency in the repo:

> Dependabot encountered the following error:
> ```
> Invalid registry source specified: 'oci://<redacted>'
> ```

and a dependabot.yml with `ignore` does not help:

```yaml
---
version: 2
updates:
  - package-ecosystem: terraform
    directories:
      - "**/*"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "oci*"
```
