### ISSUE TITLE
PyPI maximum version not respected. 

### ISSUE THREAD

**Issue by carltongibson** [dependabot/dependabot-core#10571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

PyPI

### Package manager version

Pip

### Manifest location and content before the Dependabot update

```
Django==5.0.9,<5.1
```

### dependabot.yml content

```
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  groups:
       PyPI:
          patterns:
            - "*"  # Group all PyPI updates into a single larger pull request
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
```

### Updated dependency

Django from 5.0.9 to 5.1.1

### What you expected to see, versus what you actually saw

Expected no change, the less than 5.1 constraint should be respected. 

As an adjunct, assuming correct behaviour, when updating the pinned version, the maximum version specifier should be retained. So, for example, on the release of Django 5.0.10, the following should output: 

```
Django==5.0.10,<5.1
```

Actual update: 

```
Django==5.1.1
```

### Native package manager behavior

If you run the same with pip… 

    pip install -r requirements.txt

… there is no update. Django==5.0.9 is the correct version.
