### ISSUE TITLE
Ignoring a path-based pip dependency does not work

### ISSUE THREAD

**Issue by ghinch** [dependabot/dependabot-core#10583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

24.2

### Language version

3.11

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: ".model/*"
```

### What you expected to see, versus what you actually saw

We need to pip install the spacy model via the requirements, but this file is not kept in our repo. Instead, it is downloaded during the build phase and put into the `.model/` folder. This file is referenced in the requirements.txt file

Dependabot is breaking because it cannot access the local file (it does not exist). However, I have put in an instruction in the dependabot.yml file to ignore files in the `.model/` folder. Dependabot is not ignoring this as instructed.

### Smallest manifest that reproduces the issue

``` requirements.txt
spacy==3.4.4
# Model downloaded during build
.model/en_core_web_sm-3.4.1.tar.gz
```
