### ISSUE TITLE
`pyproject.toml` optional-dependencies are not considered `dependency-type: "development"`

### ISSUE THREAD

**Issue by seamuslowry** [dependabot/dependabot-core#10606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
```

### What you expected to see, versus what you actually saw

I'd expect to see the two optional dependencies `pyright` and `pylint` to be updated as a group in a single PR. However, they are instead updated separately and the dependabot action logs

```
Please check your configuration as there are groups where no dependencies match:
- dev-dependencies
```

Separately, it's not really clear what should/shouldn't be considered a development dependency type for the pip package manager.

### Smallest manifest that reproduces the issue

[build-system]
requires = ["setuptools >= 74.0"]
build-backend = "setuptools.build_meta"

[project]
name = "example"
version = "0.0.1"
description = "example"
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
lint = [
    "pyright==1.1.379",
]
test = [
    "pytest==8.3.2",
]

**Comment by VictorColomb** [comment]
Optional dependencies are _not_ development dependencies. Optional dependencies can very well be used in production, should your library be listed as `example[lint, test]`.

I believe that you should be using dependency groups [^1]:

> This specification defines dependency groups, a mechanism for storing package requirements in pyproject.toml files such that they are not included in project metadata when it is built.
>
> Dependency groups are suitable for internal development use-cases like linting and testing, as well as for projects which are not built for distribution, like collections of related scripts.

```toml
[project]
name = "example"
version = "0.0.1"
dependencies = []

[dependency-groups]
lint = [
  "pyright==1.1.379",
]
test = [
  "pytest==8.3.2",
]
```

[^1]: https://packaging.python.org/en/latest/specifications/dependency-groups/
