### ISSUE TITLE
No Such Host - registry.npmjs.org:443http:

### ISSUE THREAD

**Issue by celsowhite** [dependabot/dependabot-core#10623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

10.2.4

### Language version

Node.js v20.10.0

### dependabot.yml content

```yml
version: 2

registries:
  github-com:
    type: git
    url: https://github.com
    username: ${{token}}
    password: ${{token}}
  custom:
    type: npm-registry
    url: https://npm.custom.org
    token: ${{token}}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    # Need "/" for dependabot to update package-lock.json
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 100
    registries: "*"
    groups:
      eslint-prettier:
        patterns:
          - "eslint*"
          - "prettier*"
          - "@types/eslint"
          - "eslint-plugin-storybook"
          - "eslint-plugin-tailwindcss"
          - "prettier-plugin-tailwindcss"
          - "@remix-run/eslint-config"
```

### Updated dependency

This error is happening for most of our dependencies but for purposes of debugging, here is one from the eslint group. After the initial `GET` then all calls to the registry are malformed with an incorrect host.

@remix-run/eslint-config - from: 2.11.2 - to 2.12.0

### Expected

I expected to see the following GET request with correct host and url scheme for registry.npmjs.org.

```
GET https://registry.npmjs.org:443/@remix-run%2feslint-config
```

### Actual

I actually see the following where the url is duplicated with mixed protocols. Leading to an incorrect host.

```
updater | 2024/09/16 18:25:14 INFO <job_885562196> Latest version is 2.12.0
  proxy | 2024/09/16 18:25:28 [023] GET [https://registry.npmjs.org:443http://registry.npmjs.org:443/@remix-run%2feslint-config](https://registry.npmjs.org:443http//registry.npmjs.org:443/@remix-run%2feslint-config)
  proxy | 2024/09/16 18:25:28 [023] WARN: Cannot read TLS response from mitm'd server lookup registry.npmjs.org:443http: no such host
updater | 2024/09/16 18:25:14 INFO <job_885562196> Latest version is 2.12.0
  proxy | 2024/09/16 18:25:28 [023] GET [https://registry.npmjs.org:443http://registry.npmjs.org:443/@remix-run%2feslint-config](https://registry.npmjs.org:443http//registry.npmjs.org:443/@remix-run%2feslint-config)
  proxy | 2024/09/16 18:25:28 [023] WARN: Cannot read TLS response from mitm'd server lookup registry.npmjs.org:443http: no such host
```

### Context

Here are a few lines from the output that suggests the proxy is using the correct registry url and then changes to using a malformed one.

```
updater | 2024/09/16 18:25:13 INFO <job_885562196> Checking if @remix-run/eslint-config 2.11.2 needs updating
  proxy | 2024/09/16 18:25:13 [019] GET [https://registry.npmjs.org:443/@remix-run%2Feslint-config](https://registry.npmjs.org/@remix-run%2Feslint-config)
  proxy | 2024/09/16 18:25:14 [019] 200 https://registry.npmjs.org:443/@remix-run%2Feslint-config
  proxy | 2024/09/16 18:25:14 [021] HEAD https://registry.npmjs.org:443/@remix-run/eslint-config/-/eslint-config-2.12.0.tgz
  proxy | 2024/09/16 18:25:14 [021] 200 https://registry.npmjs.org:443/@remix-run/eslint-config/-/eslint-config-2.12.0.tgz
updater | 2024/09/16 18:25:14 INFO <job_88[55](https://github.com/repo/actions/runs/{{#}}/job/{{#}}#step:3:57)62196> Latest version is 2.12.0
  proxy | 2024/09/16 18:25:28 [023] GET https://registry.npmjs.org:443http://registry.npmjs.org:443/@remix-run%2feslint-config
  proxy | 2024/09/16 18:25:28 [023] WARN: Cannot read TLS response from mitm'd server lookup registry.npmjs.org:443http: no such hostupdater | 2024/09/16 18:25:13 INFO <job_885562196> Checking if @remix-run/eslint-config 2.11.2 needs updating
  proxy | 2024/09/16 18:25:13 [019] GET [https://registry.npmjs.org:443/@remix-run%2Feslint-config](https://registry.npmjs.org/@remix-run%2Feslint-config)
  proxy | 2024/09/16 18:25:14 [019] 200 https://registry.npmjs.org:443/@remix-run%2Feslint-config
  proxy | 2024/09/16 18:25:14 [021] HEAD https://registry.npmjs.org:443/@remix-run/eslint-config/-/eslint-config-2.12.0.tgz
  proxy | 2024/09/16 18:25:14 [021] 200 https://registry.npmjs.org:443/@remix-run/eslint-config/-/eslint-config-2.12.0.tgz
updater | 2024/09/16 18:25:14 INFO <job_88[55](https://github.com/repo/actions/runs/{{#}}/job/{{#}}#step:3:57)62196> Latest version is 2.12.0
  proxy | 2024/09/16 18:25:28 [023] GET https://registry.npmjs.org:443http://registry.npmjs.org:443/@remix-run%2feslint-config
  proxy | 2024/09/16 18:25:28 [023] WARN: Cannot read TLS response from mitm'd server lookup registry.npmjs.org:443http: no such host
```

### Native package manager behavior

When I use the native package manager I get a successful output with no errors and properly updated dependencies.

### package.lock.json entry

An example of this module in my package.lock which shows the correct registry url.

```
"node_modules/@remix-run/eslint-config": {
      "version": "2.11.2",
      "resolved": "https://registry.npmjs.org/@remix-run/eslint-config/-/eslint-config-2.11.2.tgz",
      "integrity": "##",
      "dev": true,
      "dependencies": {
        "@babel/core": "^7.21.8",
        "@babel/eslint-parser": "^7.21.8",
        "@babel/preset-react": "^7.18.6",
        "@rushstack/eslint-patch": "^1.2.0",
        "@typescript-eslint/eslint-plugin": "^5.59.0",
        "@typescript-eslint/parser": "^5.59.0",
        "eslint-import-resolver-node": "0.3.7",
        "eslint-import-resolver-typescript": "^3.5.4",
        "eslint-plugin-import": "^2.27.5",
        "eslint-plugin-jest": "^26.9.0",
        "eslint-plugin-jest-dom": "^4.0.3",
        "eslint-plugin-jsx-a11y": "^6.7.1",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-react": "^7.32.2",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-testing-library": "^5.10.2"
      },
      "engines": {
        "node": ">=18.0.0"
      },
      "peerDependencies": {
        "eslint": "^8.0.0",
        "react": "^18.0.0",
        "typescript": "^5.1.0"
      },
      "peerDependenciesMeta": {
        "typescript": {
          "optional": true
        }
      }
    },
```

### npmrc

The npmrc contains registry details for a custom registry that is also used.

```
@custom:registry=https://npm.custom.org
//npm.custom.org/token
```

## Investigation

- I took a look at dependabot-core and believe the issue could be coming from how the uri is constructed in the [file fetcher](https://github.com/dependabot/dependabot-core/blob/a602925368311fd558723688b1635db1795a3ca0/npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb#L156).
- This issue was not happening before August 15th. In case there were any adjustments to dependabot around then.
