### ISSUE TITLE
dependabot corrupts versions of other packages (nuget / dotnet)

### ISSUE THREAD

**Issue by CZEMacLeod** [dependabot/dependabot-core#10625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

dotnet c#

### Manifest location and content before the Dependabot update

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="6.0.31" Condition="'$(TargetFramework)'=='net6.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.20" Condition="'$(TargetFramework)'=='net7.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.6" Condition="'$(TargetFramework)'=='net8.0'" />
    <PackageReference Include="Microsoft.Playwright" Version="1.46.0" />
  </ItemGroup>
```

https://github.com/CZEMacLeod/C3D.Extensions.Playwright.AspNetCore/pull/70/files#diff-bf19e3b9129de562b09dd63b4286aa6b64b2f58d14c7cc3778950a3c479a6671

### dependabot.yml content

https://github.com/CZEMacLeod/C3D.Extensions.Playwright.AspNetCore/blob/main/.github/dependabot.yml

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.AspNetCore.Mvc.Testing"
        update-types: ["version-update:semver-major"] # Don't try to upgrade 6.x to 7.x as we target both frameworks.
```

### Updated dependency

Bump Microsoft.Playwright from 1.46.0 to 1.47.0

https://github.com/CZEMacLeod/C3D.Extensions.Playwright.AspNetCore/pull/70/files#diff-bf19e3b9129de562b09dd63b4286aa6b64b2f58d14c7cc3778950a3c479a6671

### What you expected to see, versus what you actually saw

Expected:
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="6.0.31" Condition="'$(TargetFramework)'=='net6.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.20" Condition="'$(TargetFramework)'=='net7.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.6" Condition="'$(TargetFramework)'=='net8.0'" />
    <PackageReference Include="Microsoft.Playwright" Version="1.47.0" />
  </ItemGroup>
```

Actual:
https://github.com/CZEMacLeod/C3D.Extensions.Playwright.AspNetCore/pull/70/files#diff-bf19e3b9129de562b09dd63b4286aa6b64b2f58d14c7cc3778950a3c479a6671

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.6" Condition="'$(TargetFramework)'=='net6.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.6" Condition="'$(TargetFramework)'=='net7.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.6" Condition="'$(TargetFramework)'=='net8.0'" />
    <PackageReference Include="Microsoft.Playwright" Version="1.47.0" />
  </ItemGroup>
```

### Native package manager behavior

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="6.0.31" Condition="'$(TargetFramework)'=='net6.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.20" Condition="'$(TargetFramework)'=='net7.0'" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.6" Condition="'$(TargetFramework)'=='net8.0'" />
    <PackageReference Include="Microsoft.Playwright" Version="1.47.0" />
  </ItemGroup>
```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/CZEMacLeod/C3D.Extensions.Playwright.AspNetCore/pull/70

### Smallest manifest that reproduces the issue

I think if there are packages with different versions it resets them all (despite conditionals).
It also ignored the ignore in the yml.
This is a pretty minimal file to repo it on in the first place.
