### ISSUE TITLE
Add a configuration option to specify a prefix for security updates

### ISSUE THREAD

**Issue by klaustopher** [dependabot/dependabot-core#10627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently we can define a `prefix` for all updates and `prefix-development` for the updates of development dependencies. In our application we prefix the dependabot PRs using a `chore(deps):`  prefix. In our release process, this triggers no special actions

For security updates, we actually want the prefix to change to `fix(deps)` because this will trigger a bugfix release and directly forward a release to our customers. We currently do this manually by changing the PR title and then squash-merging the PR, but it would be great if dependabot automatically allowed prefixing security PRs with a custom prefix.

**Comment by eptekov** [comment]
Tesla also [raised a ticket](https://github.zendesk.com/agent/tickets/2997790) about this issue, where PR titles do not always honor the `commit-message.prefix` value, but it does work for the commit message.

According to [our docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message): "prefix specifies a prefix for all commit messages and it will also be added to the start of the PR title."

Based on the screenshots shared by Tesla, we can see that PRs that resolve a Dependabot alert do not get the prefix:

![Image](https://github.com/user-attachments/assets/e72e1e38-950d-44d4-bb64-b801c7d93b2b)

While PRs that update a package's version without a Dependabot alert  do:

![Image](https://github.com/user-attachments/assets/846d1435-d41d-45ba-9750-e80929a840a6)

`dependabot.yaml` for reference:

```
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    commit-message:
      prefix: 'chore: EFPM-10618 '
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled'
    reviewers:
      - 'digital-experience/grid-team'
    schedule:
      interval: 'monthly'
    groups:
      major:
        update-types:
          - 'major'
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'mocha'
      - dependency-name: 'node'
      - dependency-name: 'node-fetch'
      - dependency-name: 'p-queue'
      - dependency-name: 'yarn'

      # Ignore only major updates
      - dependency-name: '@types/chai'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/mocha'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: '@typescript-eslint/*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'chai'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint*'
        update-types: ['version-update:semver-major']
```
