### ISSUE TITLE
"Error: Error fetching updater images" in job "Run Dependabot"

### ISSUE THREAD

**Issue by Quving** [dependabot/dependabot-core#10624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### dependabot.yml content

```yaml
# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2


updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
```

### What you expected to see, versus what you actually saw

 I expect that the mentioned job "Run Dependabot" runs flawlessly. For some reason it stops (see screenshot).

We are using github-enterprise with self-hosted runners. On the runner itself there also not helpful informations what could us solving this issue. 

Also we dont know if the error below "AggregateError" is the follow-up error or not.

### Images of the diff or a link to the PR, issue, or logs

![image](https://github.com/user-attachments/assets/bb1af235-f177-4527-979c-863ba2603735)
