### ISSUE TITLE
Organization secrets not considered

### ISSUE THREAD

**Issue by Makoehle** [dependabot/dependabot-core#10665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm@9.1.0

### Language version

Node.js 20

### Manifest location and content before the Dependabot update

/api/package.json
/api/.npmrc

### dependabot.yml content

```yaml
version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.MY_ORG_SECRET }}

updates:
  - package-ecosystem: npm
    registries:
      - npm-github
    directory: /api
```

### What you expected to see, versus what you actually saw

I expected Dependabot to successfully access a single package hosted on private github registry.
I expect the section `registries` to be sufficiant without the need of commiting a `.npmrc`. Because this `.npmrc` file is then going to be considered from my local development. Not nice at all.
I expect Dependabot by default to access the public npm registry and only for package hosted on private registry to access them somewhere else. Currently without .npmrc the default is going to be the private registry.

### Native package manager behavior

With native package manager locally I have no 401 error instead it simply access the package hosted in private registry on Github.
