### ISSUE TITLE
[npm] update is created for ignored packages

### ISSUE THREAD

**Issue by OmarTawfik** [dependabot/dependabot-core#10675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Manifest location and content before the Dependabot update

https://github.com/NomicFoundation/slang/blob/828eff3a73204db74bc64456ae32099d18c04502/crates/solidity/testing/perf/package.json#L5

### dependabot.yml content

https://github.com/NomicFoundation/slang/blob/828eff3a73204db74bc64456ae32099d18c04502/.github/dependabot.yml#L39

### Updated dependency

`@openzeppelin/contracts` from `5.0.0` to `5.0.2`

### What you expected to see, versus what you actually saw

This shouldn't be updated, as I have this in my `dependabot.yml`:

```yml
    ignore:
      # openzeppelin contracts used in perf tests. don't update/change, to prevent variations/failures in results:
      - dependency-name: "@openzeppelin/contracts"
```
