### ISSUE TITLE
Nuget dependencies not having patch versions updates

### ISSUE THREAD

**Issue by kevin-oliveira-zocdoc** [dependabot/dependabot-core#10714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

```yml
version: 2
updates:
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  - dependency-name: Verify.NUnit
    update-types:
    - version-update:semver-minor
```

### What you expected to see, versus what you actually saw

With the following dependabot.yml config file, I'd expect that for all dependencies, dependabot would update the minor and patch versions (as I'm ignoring `semver-major` with a wildcard), but for the `Verify.NUnit` dependency, it would only update the patch versions (as I'm configuring it to ignore `semver-minor`). Instead dependabot is ignoring all updates for `Verify.NUnit`, even the patch ones, and is not opening any PR.

Am I missing something in the dependabot.yml config file?

### Images of the diff or a link to the PR, issue, or logs

This is a `.csproj` file to reproduce the behavior described:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ServiceName>test</ServiceName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Verify.NUnit" Version="25.0.0" />
  </ItemGroup>
</Project>
```

These are the logs from the dependabot execution:

```
updater | 2024/10/02 17:47:27 INFO <job_894849970> Checking if Verify.NUnit 25.0.0 needs updating
updater | 2024/10/02 17:47:27 INFO <job_894849970> Ignored versions:
updater | 2024/10/02 17:47:27 INFO <job_894849970>   version-update:semver-major - from .github/dependabot.yml
updater | 2024/10/02 17:47:27 INFO <job_894849970>   version-update:semver-minor - from .github/dependabot.yml
updater | 2024/10/02 17:47:29 INFO <job_894849970> Filtered out 141 pre-release versions
updater | 2024/10/02 17:47:29 INFO <job_894849970> All updates for Verify.NUnit were ignored
```

In this case where I have `Verify.NUnit==25.0.0` I'd expect that dependabot updated it to `25.0.4`, as its the latest patch version for `25.0.*` according to nuget: https://www.nuget.org/packages/Verify.NUnit/27.0.0-beta.5#versions-body-tab, but none PR is opened.
