### ISSUE TITLE
Dependabot not Updating terraform module using commit sha

### ISSUE THREAD

**Issue by Osazz** [dependabot/dependabot-core#10787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Terraform

### dependabot.yml content

```
---
version: 2
registries:
  git-terraform-modules:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.TESTER_GITHUB_TOKEN }}
updates:
  - package-ecosystem: terraform
    directories:
      - /live/**/*
    schedule:
      interval: weekly
    groups:
      terraform-live:
        patterns:
          - "*"
    registries:
      - git-terraform-modules
```

### Updated dependency

I am trying to update terraform module used in my project, the source file is like this 
`source = "git::ssh://git@github.com/private/infra-live.git//modules/btg/first-module?ref=dc7c47554614c3d3d3065a45e020fc7f44adbscx"`

Project is a monorepo with something like this

```
.
live/
  /something
      /another folder
module/
   /btg
       /first_module
       /second_module
```

`git ls-remote` result 

```
ad0ea10cdc73a7229c40efbede6a3586a0555544	refs/tags/second-module-v1.1.0
dc7c47554614c3d3d3065a45e020fc7f44adbscx	refs/tags/first-module-v1.1.0
5a9792a8ec05d876314c2a977dcf8194c2333333	refs/tags/first-module-v1.1.1
```

### What you expected to see, versus what you actually saw

When dependabot runs, all dependency with commit sha `dc7c47554614c3d3d3065a45e020fc7f44adbscx` should be updated to `5a9792a8ec05d876314c2a977dcf8194c2333333`

### Images of the diff or a link to the PR, issue, or logs

Dependabot log is returning no update and empty latest version when there is one : 
```
 => checking for updates 1/2
🌍 --> GET https://github.com/private/infra-live.git/info/refs?service=git-upload-pack
🌍 <-- 200 https://github.com/private/infra-live.git/info/refs?service=git-upload-pack
 => latest available version is
    (no update needed as it's already up-to-date)
````
