### ISSUE TITLE
Failure to handle multitargeted csproj

### ISSUE THREAD

**Issue by james-asebp** [dependabot/dependabot-core#10791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content
``` yml
version: 2

registries:
  azure-devops:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/<redacted>/_packaging/<redacted>/nuget/v3/index.json
    token: PAT:${{AZURE_ARTIFACTS_TOKEN}}

updates:
  - package-ecosystem: "nuget" 
    directory: "/src"
    registries:
      - azure-devops
    ignore:
        # ignore major version updates for "*" (all) dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

        # ignore minor version updates for "xunit.runner.visualstudio"
      - dependency-name: "xunit.runner.visualstudio"
        update-types: ["version-update:semver-minor"]
            
    open-pull-requests-limit: 5 # default is 5
    milestone: 22567 # work item to which the created pull requests will be attached
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "nuget"
    labels:
      - "dependencies"
      - "nuget"
```

### What you expected to see, versus what you actually saw

Expected for only the package that has updates for each targetted .net version to be updated. See Manifest section for .csproj file contents

In the example below only .net 6 should have updated `Microsoft.AspNetCore.Authentication.JwtBearer` to 6.0.35 and .net 8 should have updated to 8.0.10

### Native package manager behavior

Updating the dependency in visual studio nuget client works as expected

### Images of the diff or a link to the PR, issue, or logs

Log snippets from dependabot run

```
updater | dotnet build in GetAllPackageDependenciesAsync failed. STDOUT:   Determining projects to restore...
updater | /tmp/package-dependency-resolution_8tEMpK/Project.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8], Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8], Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8], Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8], Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8].
updater | /tmp/package-dependency-resolution_8tEMpK/Project.csproj : error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 8.0.8 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.Authentication.JwtBearer 8.0.8 supports: net8.0 (.NETCoreApp,Version=v8.0)
updater |   Failed to restore /tmp/package-dependency-resolution_8tEMpK/Project.csproj (in 3.53 sec).
```

```
updater | dotnet build in GetAllPackageDependenciesAsync failed. STDOUT:   Determining projects to restore...
updater | /tmp/package-dependency-resolution_QsW6FN/Project.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8], Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8], Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8], Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8], Microsoft.AspNetCore.Authentication.JwtBearer [8.0.8].
updater | /tmp/package-dependency-resolution_QsW6FN/Project.csproj : error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 8.0.8 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.AspNetCore.Authentication.JwtBearer 8.0.8 supports: net8.0 (.NETCoreApp,Version=v8.0)
updater |   Failed to restore /tmp/package-dependency-resolution_QsW6FN/Project.csproj (in 756 ms).
```

these log patterns are repeated for all targetted versions except for .net 8

Followed by 
```
 running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/src/<redacted>.csproj --dependency Microsoft.AspNetCore.Authentication.JwtBearer --new-version 8.0.10 --previous-version 8.0.8 --result-output-path /tmp/update-result.json
```

and then finally the error
```
updater | Update complete.
updater |   Writing update result to [/tmp/update-result.json].
updater | 2024/10/15 16:09:20 INFO <job_update_0_nuget_all> update result: {
updater |   "ErrorType": null,
updater |   "ErrorDetails": null
updater | }
  proxy | 2024/10/15 16:09:20 [273] POST http://host.docker.internal:38399/update_jobs/update_0_nuget_all/record_update_job_error
{"data":{"error-type":"update_not_possible","error-details":{"dependencies":["Microsoft.AspNetCore.Authentication.JwtBearer"]}},"type":"record_update_job_error"}
  proxy | 2024/10/15 16:09:20 [273] 200 http://host.docker.internal:38399/update_jobs/update_0_nuget_all/record_update_job_error
updater | 2024/10/15 16:09:20 INFO <job_update_0_nuget_all> Handled error whilst updating Microsoft.AspNetCore.Authentication.JwtBearer: update_not_possible {:dependencies=>["Microsoft.AspNetCore.Authentication.JwtBearer"]}
```

```
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------------------------------------------------+
updater | |                    Dependencies failed to update                    |
updater | +-----------------------------------------------+---------------------+
updater | | Microsoft.AspNetCore.Authentication.JwtBearer | update_not_possible |
updater | +-----------------------------------------------+---------------------+
```

### Smallest manifest that reproduces the issue

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netcoreapp3.1;net6.0;net7.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>CS1591</NoWarn>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <DebugType>Full</DebugType>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <!-- Include xml documentation files for intellisense in consuming app when packaging the .nupkg -->
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(RootNamespace).xml</DocumentationFile>
    <!-- Include symbol files (*.pdb) when packaging the .nupkg -->
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <!-- Conditionally obtain references for the 'netstandard2.0' target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="2.2.0" />
  </ItemGroup>

  <!-- Conditionally obtain references for the 'netcoreapp3.1' target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.1' ">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.32" />
  </ItemGroup>

  <!-- Conditionally obtain references for the 'net6.0' target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.33" />
  </ItemGroup>

  <!-- Conditionally obtain references for the 'net7.0' target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.20" />
  </ItemGroup>

  <!-- Conditionally obtain references for the 'net8.0' target -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
  </ItemGroup>

</Project>
```
