### ISSUE TITLE
Reviewer assignment requests from team and single person from team

### ISSUE THREAD

**Issue by rH4rtinger** [dependabot/dependabot-core#10827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "rH4rtinger"
    schedule:
      interval: "weekly"
```

### What you expected to see, versus what you actually saw

The reviewers in the dependabot file is set to one person. This person is a member of the `@aditosoftware/devs-designer` team. 
In my branch protection rules is the checkbox **Require review from Code Owners** set.
In my team are the following code review settings set.
![image](https://github.com/user-attachments/assets/b00d4e3a-102b-4772-a43d-30494fe37464)

I expect, since the user set as a reviewer is a member of the team no one else will be notified or assigned as reviewer.

Actual behavior:
The team is requested and the user, resulting in two persons assigned to review

### Images of the diff or a link to the PR, issue, or logs

Example PR:
https://github.com/aditosoftware/vscode-logging/pull/14
