### ISSUE TITLE
NuGet `update_not_possible` for group update

### ISSUE THREAD

**Issue by rhyskoedijk** [dependabot/dependabot-core#10834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Manifest location and content before the Dependabot update

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>
</Project>
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: 'nuget'
    directory: '/'
    groups:
       microsoft:
         patterns:
         - "Microsoft.*"
```

### Updated dependency

- Microsoft.Extensions.DependencyInjection from 8.0.0 to 8.0.1
- Microsoft.Extensions.Logging from 8.0.0 to 8.0.1
- Microsoft.Extensions.Logging.Abstractions from 8.0.1 to 8.0.2

### What you expected to see, versus what you actually saw

I expect the update to complete without error, creating one pull request

### Images of the diff or a link to the PR, issue, or logs

<details>
<summary>Dependabot CLI log output</summary>
...
</details>

### Smallest manifest that reproduces the issue

https://github.com/rhyskoedijk/dependabot-test-nuget-update-not-possible

`dependabot update -f job.yml -o out.yml`
```yml
job:
  package-manager: nuget
  allowed-updates:
    - update-type: all
  dependency-groups:
    - name: microsoft
      rules:
        patterns:
          - 'Microsoft.*'
  source:
    provider: github
    repo: rhyskoedijk/dependabot-test-nuget-update-not-possible
    directory: /
```
