### ISSUE TITLE
'registries' key can not take wildcard even though documentation uses as example.

### ISSUE THREAD

**Issue by tjsr** [dependabot/dependabot-core#10854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Language version

Node 20.17

### Manifest location and content before the Dependabot update

https://github.com/tjsr/user-session-middleware/blob/main/package.json as example

### dependabot.yml content

Variants of https://github.com/tjsr/user-session-middleware/blob/main/.github/dependabot.yml

Update to below for an example:

```yaml
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
    - "*"
    schedule:
      interval: 'daily'
```

### What you expected to see, versus what you actually saw

When the dependabot yaml verification step runs, I get the error
```
The property '#/updates/0/registries' includes the "*" registry which is not defined in the top-level 'registries' definition
```

However this is the same usage specified by the example in the documentation at The property '#/updates/0/registries' includes the "*" registry which is not defined in the top-level 'registries' definition

I have tried this both with `registries: '*'` and
```yaml
registries:
- '*'
```

I can't tell if this is no longer supported, but I want dependabot to check both the Github NPM registry and the NPM global registry (without special credentials). However, if you define a registries block like
```yaml
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
```

This gets rejected by the dependabot yaml check as not valid.  The documentation doesn't say anything about `token`, `username`/`password` or `key` being required, but that seems to be what causes it - so you MUST specify a token if you want to specify npmjs as an upstream registry.

### Smallest manifest that reproduces the issue

Try something like:

```yaml
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GITHUB_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries: "*"
    schedule:
      interval: 'daily'
```

You can also try 
```yaml
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GITHUB_TOKEN}}
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
    - npm-github
    - npm-npmjs
    schedule:
      interval: 'daily'
```
To likely see the alternative failure.

The docs just seem outdated on this, and don't match how we should be using dependabot in situations where we have deps in both GH private and the public npm registry - but it's incredibly difficult (and I've not found) to find the recommended pattern as of October 2024.

**Comment by MattIPv4** [comment]
👋 I'm also running into this and am not sure what the expected pattern is when you have both public npmjs dependencies + GitHub Package Registry npm dependencies.

**Comment by v-thavaahariharangit** [comment]
According to the [official documentation](https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#configuring-private-registries), the following configuration is supported:

```
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries: "*"
    schedule:
      interval: "monthly"
```

This configuration has been tested on the following repository: https://github.com/dsp-testing/npm-private-registry-10854, and it is functioning as expected.

With this confirmation, I am closing the ticket.
