### ISSUE TITLE
Dependabot doesn't support pnpm versions > 9.4.0

### ISSUE THREAD

**Issue by eiskrenkov** [dependabot/dependabot-core#10871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

pnpm@^9.12.3

### Language version

node@^22.5.1

### Manifest location and content before the Dependabot update

`package.json`

```json
{
  "engines": {
    "node": "^22.5.1",
    "pnpm": "^9.12.3"
  }
}
```

### dependabot.yml content

```yaml
version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.CI_GITHUB_PACKAGES_RO_USER }}:${{ secrets.CI_GITHUB_PACKAGES_RO_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 4
    registries:
      - npm-github
    commit-message:
      prefix: "[DEV] "
```

### What you expected to see, versus what you actually saw

Recently we started getting the following error from dependabot:

![Screenshot 2024-10-31 at 12 41 56@2x](https://github.com/user-attachments/assets/365036b0-9493-44fc-9ad2-1cbddd00fa98)

although dependabot's documentation clearly says that pnpm v9 is supported here https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories

I expected dependabot to be working with with any `pnpm` version of 9th major

I assume this issue could be related to us having `pnpm` version specified in `package.json` `engines` field
