### ISSUE TITLE
Create dependabot PRs as a custom user

### ISSUE THREAD

**Issue by drstrangelooker** [dependabot/dependabot-core#10885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have github actions for CI/CD that rely on secrets. When dependabot authors a PR, the "user" of the PR is the dependabot user. Only members of our org have access to secrets. Since the dependabot user does not have access to our secrets, we need to accept the PR into a special branch, then create another PR as a user that can access the secrets in order to get the CI/CD actions to run properly.

The google release-please action handles this situation by allowing the config to specify a user to author the PR. We have a special user we created called "${OUR_ORG}_automation_bot". The automation bot owns the PR and has access to the secrets so CI/CD runs properly.

The token associated with that bot is a secret in our repos. We configure the action like this...
```
    steps:
      - uses: googleapis/release-please-action@v4.1.2
        with:
          token: ${{ secrets.AUTO_BOT_RP_TOKEN }}
```

Please provide a dependabot config so that the PR can be opened with a custom user.
