### ISSUE TITLE
globstar directory path for github-actions ecosystem makes duplicate PRs

### ISSUE THREAD

**Issue by wallentx** [dependabot/dependabot-core#10884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

.github/workflows/

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - '**/*'
    schedule:
      interval: weekly
    commit-message:
      prefix: github-actions
      include: scope
```

### What you expected to see, versus what you actually saw

Expected:
Dependabot would find a file located at `.github/workflows/actionlint.yml`, scan it once, and create a single PR for each `uses:` action that is being updated.

Actual:
Using the globstar directory path, dependabot is identifying the file located at `.github/workflows/actionlint.yml` as 2 separate files, and scan it twice, and create 2 PRs for each item that it is changing.

I discovered this bug in my org's private enterprise cloud, so I used my sandbox repo to reproduce this bug for the purpose of this report.

In my private org, I did see that if there are composite actions present in some folder like `actions/my-composite-action/action.yml`, then the use of `**/*` as a `directories:` path does _not_ result in duplicate scan and duplicate PR creation. I've only seen this behavior when the only actions in the repo are the ones located at default gh workflows path.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/wallentx/gh-sandbox/actions/runs/11635007676/job/32403443687

https://github.com/wallentx/gh-sandbox/pull/30
https://github.com/wallentx/gh-sandbox/pull/31

Note the name of the PRs..
`github-actions(deps): bump actions/checkout from 2 to 4`
and
`github-actions(deps): bump actions/checkout from 2 to 4 in /.github/workflows`

This to me seems like a hint as to what is happening, which is that
```yaml
    directories:
      - '**/*'
```
is evaluating the files from the default gh workflows path, and is simultaneously "finding" action *.yml files at "some" location. If there is some implicit default workflow location that gets scanned, then the globstar pattern should exclude the default path.
It seems like this IS being handled appropriately if there are actions that are actually located in a path other than the default, but I haven't sorted through the code to determine what exactly is going on.

### Smallest manifest that reproduces the issue

`dependabot.yml`
```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - '**/*'
    schedule:
      interval: weekly
    commit-message:
      prefix: github-actions
      include: scope
```

`action.yml`
```yaml
name: Action

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
```
