### ISSUE TITLE
Pull request title and body do not mention all the updated versions

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#10901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### Manifest location and content before the Dependabot update

https://github.com/yeikel/dependabot-playground/blob/main/docker/java.Dockerfile

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/gradle"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "azul/zulu-openjdk"
        update-types: ["version-update:semver-major"]   

```

### Updated dependency

azul/zulu-openjdk

### What you expected to see, versus what you actually saw

Expected: The title and the body should reflect that multiple updates are happening

Actual: The title and the pull request body only mention one

`Bump azul/zulu-openjdk from `f80dd77` to `acc0b3c` in /docker` 

```diff

diff --git a/docker/java.Dockerfile b/docker/java.Dockerfile
index 823e198..4cfc414 100644
--- a/docker/java.Dockerfile
+++ b/docker/java.Dockerfile
@@ -1,8 +1,8 @@
 
-FROM azul/zulu-openjdk:8-latest@sha256:f80dd775450e8fd089ddbc52d1e3aa7ea3df45b008591079b3a8ae8f5c6aa90a AS java-8
+FROM azul/zulu-openjdk:8-latest@sha256:acc0b3c09276f753e93604aab840868f20104698f32ec357d1c84430e505a3c4 AS java-8
 
-FROM azul/zulu-openjdk:11-latest@sha256:ff62af7e572dec2c82d84f9ee1c099973e66312b941af3dbff9cd0d4a82b9a36 AS java-11
+FROM azul/zulu-openjdk:11-latest@sha256:53314b445bcf8eabac3ee466d075ea7f44aa904dfb2415a20b361dae06363305 AS java-11
 
-FROM azul/zulu-openjdk:17-latest@sha256:4e32936bc094d8cdea273d13f0eeca97609f5c7ffd31ca165a5f2f99bf437d6d AS java-17
+FROM azul/zulu-openjdk:17-latest@sha256:52edbd7a0a0b89eedd1941ba0928d52b8c3432e77ab1d6feadf6d6223bdc1017 AS java-17
 
-FROM azul/zulu-openjdk:21-latest@sha256:fb1980bbce801e18fef2e32295e1bf7011c3dd24b7afbf991f47089cad1c454a AS java-21
+FROM azul/zulu-openjdk:21-latest@sha256:c3202401e8c3aa536dd9e6eaae7498f1413b7f8c6ac1490724c3e369d2319780 AS java-21

```

### Smallest manifest that reproduces the issue

```

FROM azul/zulu-openjdk:8-latest@sha256:f80dd775450e8fd089ddbc52d1e3aa7ea3df45b008591079b3a8ae8f5c6aa90a AS java-8

FROM azul/zulu-openjdk:11-latest@sha256:ff62af7e572dec2c82d84f9ee1c099973e66312b941af3dbff9cd0d4a82b9a36 AS java-11


```
