### ISSUE TITLE
dependabot version update is failing with yarn

### ISSUE THREAD

**Issue by MDSLKTR** [dependabot/dependabot-core#10928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn, Docker, Github Actions

### Package manager version

4.1.1

### Language version

Node.js 22.9.0

### dependabot.yml content

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

```
version: 2
registries:
  github: # Define access for a private registry
    type: npm-registry
    url: xxxx
    token: ${{ secrets.CDM_GITHUB_PACKAGE_REGISTRY_SECRET }}
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    open-pull-requests-limit: 2
    schedule:
      interval: 'monthly'
    versioning-strategy: 'increase'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
    ignore:
      # For all deps
      - dependency-name: '*'
        # ignore all major updates
        update-types: ['version-update:semver-major']
    registries:
      - github
```

### What you expected to see, versus what you actually saw

I expect that dependabot can run version updates without error:

I See:
[0_Dependabot.txt](https://github.com/user-attachments/files/17718893/0_Dependabot.txt)

### Native package manager behavior

No errors

### Images of the diff or a link to the PR, issue, or logs

[0_Dependabot.txt](https://github.com/user-attachments/files/17718893/0_Dependabot.txt)

### Smallest manifest that reproduces the issue

I believe you can add a yarn.config.cjs to the project with the following contents or simliar. The import of @yarnpkg/types is important.

```
/** @type {import('@yarnpkg/types')} */
const { defineConfig } = require('@yarnpkg/types');
const rootPackageJson = require('./package.json');

const { engines } = rootPackageJson;

module.exports = defineConfig({
    async constraints({ Yarn }) {
        for (const workspace of Yarn.workspaces()) {
            workspace.set('engines.node', engines.node);
        }

        if (process.versions.node !== engines.node.replace(/[\^<>=]/g, '')) {
            throw new Error(`Invalid node version: ${process.version}, required version: ${engines.node}`);
        }
    },
});

```

We have this dependency installed in the root package.json (so running it locally will work). Then try to update the dependencies using the dependabot
