### ISSUE TITLE
@Dependabot API ignore major version seemingly not working 

### ISSUE THREAD

**Issue by smcvb** [dependabot/dependabot-core#10923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### Manifest location and content before the Dependabot update

pom.xml

### dependabot.yml content

```yml
version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
  open-pull-requests-limit: 5
  labels:
    - "Type: Dependency Upgrade"
    - "Priority 1: Must"
  milestone: 96
  reviewers:
    - "AxonFramework/framework-developers"
  groups:
    github-dependencies:
      update-types:
        - "patch"
        - "minor"
        - "major"

- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
  open-pull-requests-limit: 5
  labels:
    - "Type: Dependency Upgrade"
    - "Priority 1: Must"
  milestone: 96
  reviewers:
    - "AxonFramework/framework-developers"
  groups:
    maven-dependencies:
      update-types:
        - "patch"
        - "minor"
        - "major"
```

### What you expected to see, versus what you actually saw

By using the Dependabot bot ignore rules inside a pull request, I expected that my project **does not** upgrade dependency that no longer supports JDK8.
As it stands, dependencies of for example Mockito and Spring Boot have been upgraded to a none-JDK8 supporting version for the last 4 weeks.

I was originally led to issue #10798 by @amazimbe.
Although the issue is marked completed, I still noted the unexpected behavior this week and last week.
I replied to the issue referred to last week with [this](https://github.com/dependabot/dependabot-core/issues/10798#issuecomment-2454290443) comment, but I figured making an issue would be the right approach.

An example culprit that does not adhere to the ignore rules I have set up is pull request [#3182](https://github.com/AxonFramework/AxonFramework/pull/3182) from the Axon Framework project.
I have an additional 10 or so other repositories that show similar behavior, though.

### Images of the diff or a link to the PR, issue, or logs

Issue [#3182](https://github.com/AxonFramework/AxonFramework/pull/3182) of the Axon Framework project.
