### ISSUE TITLE
Update version and comment for SHA-pinned Terraform modules

### ISSUE THREAD

**Issue by kristian-lesko** [dependabot/dependabot-core#10926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Similarly to GitHub Actions versions that are [recommended to point to a full commit SHA](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) instead of a Git tag or branch name, Terraform modules are susceptible to a similar kind of supply chain attack, and an identical solution is recommended by security tools (e.g., [Checkov](https://docs.prismacloud.io/en/enterprise-edition/policy-reference/supply-chain-policies/terraform-policies/ensure-terraform-module-sources-use-git-url-with-commit-hash-revision)).

Currently, Dependabot seems to skip SHA-pinned versions in Terraform module references, only considering semantic versions.

I would essentially like to request porting https://github.com/dependabot/dependabot-core/pull/5951 for Terraform module dependencies, including both the update of the commit hash itself as well as the human-readable version comment.

Thank you very much for considering this!

**Comment by chrisponton** [comment]
I would also like to request this feature. We had to revert to using tags to enable this functionality for modules stored in Git.

**dependabot.yml**

```yaml
version: 2
registries:
  # Ensure we can also access our private GitHub packages
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GIT_GITHUB_TOKEN }}
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    registries:
      - github
    directory: "/"
    schedule:
      interval: daily
  # Maintain dependencies for Terraform
  - package-ecosystem: terraform
    registries:
      - github
    directories:
      - "terraform/**/*"
    schedule:
      interval: daily
```

**Sha git module use**

```hcl
module "platform_code_build" {
  source      = "git@github.com:My-Org/terraform-aws-codebuild.git?ref=e3a79b46c8f127f75f55ac1c4d7ab3bd205b382e"
  name        = "${local.platform}-codebuild-project"
}
```

Logs:

```text
2025/06/24 19:05:04 INFO <job_1040556196> Checking all dependencies for version updates...
updater | 2025/06/24 19:05:04 INFO <job_1040556196> Checking if platform_code_build::github::My-Org/terraform-aws-codebuild::e3a79b46c8f127f75f55ac1c4d7ab3bd205b382e  needs updating
  proxy | 2025/06/24 19:05:04 [014] GET https://github.com/My-Org/terraform-aws-codebuild.git/info/refs?service=git-upload-pack
  proxy | 2025/06/24 19:05:04 [014] * authenticating git server request (host: github.com)
  proxy | 2025/06/24 19:05:04 [014] 200 https://github.com/My-Org/terraform-aws-codebuild.git/info/refs?service=git-upload-pack
updater | 2025/06/24 19:05:04 INFO <job_1040556196> Latest version is 
updater | 2025/06/24 19:05:04 INFO <job_1040556196> No update needed for platform_code_build::github::My-Org/terraform-aws-codebuild::e3a79b46c8f127f75f55ac1c4d7ab3bd205b382e 
```

Doesn't detect the latest version: `Latest version is `

**Tag git module use**

```text
module "platform_code_build" {
  source      = "git@github.com:My-Org/terraform-aws-codebuild.git?ref=v1.0.0"
  name        = "${local.platform}-codebuild-project"
}
```

Logs (removed a few lines):

```text
updater | 2025/06/26 08:36:51 INFO <job_1041538336> Checking if platform_code_build::github::My-Org/terraform-aws-codebuild::v1.0.0 1.0.0 needs updating
  proxy | 2025/06/26 08:36:51 [033] GET https://github.com/My-Org/terraform-aws-codebuild.git/info/refs?service=git-upload-pack
2025/06/26 08:36:51 [033] * authenticating git server request (host: github.com)
  proxy | 2025/06/26 08:36:51 [033] 200 https://github.com/My-Org/terraform-aws-codebuild.git/info/refs?service=git-upload-pack
  proxy | 2025/06/26 08:36:52 [036] GET https://api.github.com/repos/platform_code_build::github::My-Org/terraform-aws-codebuild::v1.0.0/releases
  proxy | 2025/06/26 08:36:52 [036] * authenticating github api request with token for api.github.com
updater | 2025/06/26 08:36:52 INFO <job_1041538336> Allowed version tags after filtering versions in cooldown:
              1.1.0, v0.0.1, v0.0.2, v0.0.3, v0.0.4, v0.0.5, v0.1.0, v0.1.1, v1.0.0, v1.1.0
updater | 2025/06/26 08:36:52 INFO <job_1041538336> Latest version is 1.1.0
```

```text
updater | 2025/06/26 08:36:54 INFO <job_1041538336> Updating platform_code_build::github::My-Org/terraform-aws-codebuild::v1.0.0 from 1.0.0 to 1.1.0
updater | 2025/06/26 08:36:54 INFO <job_1041538336> Submitting platform_code_build::github::My-Org/terraform-aws-codebuild::v1.0.0 pull request for creation
```

Another issue is raised https://github.com/dependabot/dependabot-core/issues/10787 but assume closed as duplicate of this?
