### ISSUE TITLE
Dependabot updates the all images in a yaml spec that have the same tag (despite for only one the new tag exists)

### ISSUE THREAD

**Issue by chicco785** [dependabot/dependabot-core#10930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### dependabot.yml content

```
version: 2
registries:
  ghcr:
    type: docker-registry
    url: ghcr.io
    username: ${{secrets.PACKAGE_READ_USERNAME}}
    password: ${{secrets.PACKAGE_READ_PAT}}
  github:
    type: git
    url: github.com
    username: x-access-token
    password: ${{ secrets.REPO_PRIVATE_READ_PAT }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "kubernetes/demo"
    reviewers:
      - zaphiro-technologies/backend-devs
    registries:
      - ghcr
      - github
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

given two images that currently have the same tag version, only the one where the docker image tag was updated should be updated.

### Smallest manifest that reproduces the issue

```
    service1:
      image:
        registry: ghcr.io
        repository: zaphiro-technologies/image1
        tag: 0.0.3
    service2:
      image:
        registry: ghcr.io
        repository: zaphiro-technologies/image2
        tag: 0.0.3
    service3:
      image:
        registry: ghcr.io
        repository: zaphiro-technologies/image3
        tag: 0.0.3
```

an update from 0.0.3 to 0.0.4 of image1 resulted in update of all tree images, where 0.0.4 does not exist for service2 and service3.

the bug is kind of expected, given this line in the code:
https://github.com/dependabot/dependabot-core/blob/main/docker/lib/dependabot/docker/file_updater.rb#L174

**Comment by v-thavaahariharangit** [comment]
I am unable to reproduce this issue.

Please find the contents of my testing repo

`compose.yml`
```
version: '3.8'
services:
  service-1:
    image: jfrogghdemo.jfrog.io/e2e-tests-dependabot-docker-repo/docker-package:1.0
    ports:
      - "3000:3000"
    restart: unless-stopped
  service-2:
    image: jfrogghdemo.jfrog.io/e2e-tests-dependabot-docker-repo/second-docker-app:1.0
    ports:
      - "3030:3030"
    restart: unless-stopped
```

`.github/dependabot.yml`
```
version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - dockerhub

registries:
  dockerhub:
    type: docker-registry
    url: jfrogghdemo.jfrog.io
    username: thavaahariharangit@github.com
    password: ${{secrets.MY_DOCKERHUB_PASSWORD}}
    replaces-base: true
```

PR generated as expected

<img width="1420" height="920" alt="Image" src="https://github.com/user-attachments/assets/b4071f29-cef4-4335-9326-d794d77c0128" />

Only the expected package updated
Please try using `package-ecosystem: "docker-compose"`
