### ISSUE TITLE
Dependabot group for patterns "rack" and "rack-*" including unexpected gems

### ISSUE THREAD

**Issue by bjeanes** [dependabot/dependabot-core#10940]
See PR description:

![Screenshot 2024-11-15 at 1 51 27 pm](https://github.com/user-attachments/assets/8999b144-3134-4916-beb8-1f7d87c1aa1b)

Further, it is including `rails`, even though `rails` is explicitly excluded (both via `@dependabot ignore` and in `dependabot.yml` now).

Configuration:

```yml
version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: Australia/Melbourne
    ignore:
      - dependency-name: "rails"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 3
    groups:
      linter:
        patterns:
          - "rubocop"
          - "rubocop-*"
          - "standard"
          - "standard-*"

      rodauth:
        patterns:
          - "roda"
          - "rodauth"
          - "rodauth-*"

      pry:
        patterns:
          - "pry"
          - "pry-*"

      test:
        patterns:
          - "rspec"
          - "rspec-*"
          - "capybara"
          - "capabara-*"
          - "webmock"
          - "vcr"
          - "timecop"
          - "selenium-devtools"
          - "selenium-webdriver"
          - "factory_bot"
          - "factory_bot_rails"
          - "db-query-matchers"

      rack:
        patterns:
          - "rack"
          - "rack-*"

      sentry:
        patterns:
          - "sentry-ruby"
          - "sentry-rails"

      lsp:
        patterns:
          - "ruby-lsp*"

      shrine:
        patterns:
          - "shrine"
          - "shrine-*"

      dry:
        patterns:
          - "dry-*"

      state-machines:
        patterns:
          - "state_machines"
          - "state_machines-*"

      elasticsearch:
        patterns:
          - "elasticsearch"
          - "elasticsearch-*"
          - "searchkick"
```

Ignore conditions in same PR:

![Screenshot 2024-11-15 at 1 53 31 pm](https://github.com/user-attachments/assets/670d83bb-3bbd-41e3-81e1-92757902b5ed)

This is driving me bonkers because it keeps closing and re-opening this PR daily and is practically upgrading the world so naturally this falls apart.
