### ISSUE TITLE
[berry] when `.yarnrc.yml` have plugin, fail as `dependency_file_not_resolvable`

### ISSUE THREAD

**Issue by ncaq** [dependabot/dependabot-core#10961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm(yarn)

### Package manager version

yarn `4.5.1`

### Language version

node `v22.11.0`

### Manifest location and content before the Dependabot update

Sorry, it is private.

### dependabot.yml content

``` yaml
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'Status: Review Needed'
      - 'Type: Dependencies'
      - 'Type: Maintenance'
      - 'Type: CI'
      - 'Type: Meta'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    groups:
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - '*eslint*'
      jest:
        patterns:
          - '*jest*'
      babel:
        patterns:
          - '*babel*'
      i18next:
        patterns:
          - '*i18next*'
    labels:
      - 'Status: Review Needed'
      - 'Type: Dependencies'
      - 'Type: Maintenance'
```

### Updated dependency

for instance.

```
updater | | created | typescript-eslint ( from 8.14.0 to 8.15.0 )    |
```

### What you expected to see, versus what you actually saw

expect.

The dependabot create PR.

actual.

```
updater | 2024/11/18 20:17:45 INFO <job_918691824> Checking if typescript-eslint 8.14.0 needs updating
proxy | 2024/11/18 20:17:45 [138] GET https://registry.npmjs.org:443/typescript-eslint
proxy | 2024/11/18 20:17:45 [138] 200 https://registry.npmjs.org:443/typescript-eslint
proxy | 2024/11/18 20:17:45 [140] HEAD https://registry.npmjs.org:443/typescript-eslint/-/typescript-eslint-8.15.0.tgz
proxy | 2024/11/18 20:17:45 [140] 200 https://registry.npmjs.org:443/typescript-eslint/-/typescript-eslint-8.15.0.tgz
updater | 2024/11/18 20:17:45 INFO <job_918691824> Latest version is 8.15.0
updater | 2024/11/18 20:17:53 INFO <job_918691824> Requirements to unlock own
updater | 2024/11/18 20:17:53 INFO <job_918691824> Requirements update strategy bump_versions
updater | 2024/11/18 20:17:53 INFO <job_918691824> Updating typescript-eslint from 8.14.0 to 8.15.0
proxy | 2024/11/18 20:18:01 [142] POST /update_jobs/918691824/record_update_job_error
2024/11/18 20:18:01 [142] 204 /update_jobs/918691824/record_update_job_error
updater | 2024/11/18 20:18:01 INFO <job_918691824> Handled error whilst updating typescript-eslint: dependency_file_not_resolvable {:message=>"Network error while resolving dependency."}
```

### Native package manager behavior

``` console
2024-11-19T15:26:26 ⬢ [Systemd] ❯ yarn upgrade-interactive
 Press <up>/<down> to select packages.            Press <enter> to install.
 Press <left>/<right> to select versions.         Press <ctrl+c> to abort.

? Pick the packages you want to upgrade.          Current          Range            Latest

   typescript-eslint --------------------------- ◉ ^8.14.0 ------ ◯ ^8.15.0 ------
```

### Images of the diff or a link to the PR, issue, or logs

Sorry, it is private.

### Smallest manifest that reproduces the issue

I found this problem cause by plugin.
My `.yarnrc.yml` below.

``` yml
nodeLinker: node-modules

plugins:
  - checksum: 374f735053958b77583ef7b70e56a59540d1d9c681f04b8ab7a600f4325301d2e1fb67c51d34ba75bbbc4e71f8c003fbc52b1f22d7daa30dca655f1a1bf205a1
    path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.15.0/bundles/@yarnpkg/plugin-licenses.js'
```

I change to `.yarnrc.yml`.

``` yml
nodeLinker: node-modules
```

I checked to fine by my cli `dependabot update npm_and_yarn repo`.

Maybe, This problem because I gitignore `.yarn/plugins`.
However `yarn install` automatic install plugin, So I do not want commit plugin binary.

I did some research and noticed that it was responding to the `YARNRC_EAI_AGAIN` pattern, but I thought this was a problem that I should create an issue for first, so I will create one.
