### ISSUE TITLE
from version not logged for pip package ecosystem

### ISSUE THREAD

**Issue by daveisfera** [dependabot/dependabot-core#10967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

7.4.1

### Language version

3.13

### Manifest location and content before the Dependabot update

requirements.txt

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
```

### Updated dependency

N/A

### What you expected to see, versus what you actually saw

```
+--------------------------------------------------+
|       Changes to Dependabot Pull Requests        |
+---------+----------------------------------------+
| created | django-cors-headers ( from  to 4.6.0 ) |
| created | newrelic ( from  to 10.3.0 )           |
| created | redis ( from  to 5.2.0 )               |
+---------+----------------------------------------+
```

### Native package manager behavior

N/A

### Images of the diff or a link to the PR, issue, or logs

Created PR was correct, but that log is missing the from version

### Smallest manifest that reproduces the issue

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
```
