### ISSUE TITLE
Dependabot creating next PR too soon after last PR auto-merges, resulting in next PR out-of-date with base branch 

### ISSUE THREAD

**Issue by devanubis** [dependabot/dependabot-core#10969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

poetry

### Language version

python 3.11

### dependabot.yml content
```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "scene-connect/dependabot-reviewers"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
  - package-ecosystem: "pip"
    allow:
      - dependency-type: all
    directory: "/"
    reviewers:
      - "scene-connect/dependabot-reviewers"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    insecure-external-code-execution: allow # apparently pip executes code see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#insecure-external-code-execution
```

### What you expected to see, versus what you actually saw

Similar to #4031 and #5234.

We have a github action which marks dependabot PRs to auto-merge, if they pass our CI workflow.

```
name: Dependabot auto-merge
on:
  workflow_call:
    inputs:
      merge_major_versions:
        default: false
        description: Auto merge on major version changes
        required: false
        type: boolean

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
      - name: Merge PR
        if: ${{ inputs.merge_major_versions || steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
```

When the first dependabot PR of the day successfully auto-merges, dependabot appears to create the second PR almost instantly, and that second PR gets based on HEAD^ missing the commit from the first dependabot PR, which just auto-merged.

That means we have to go around our multiple repos and `@ dependabot rebase` each of them to get them moving again, 

This all pretty much defeats the point of auto-merging our dependabot PRs in the first place, and also doubles up on CI workflow runs. (I've actually just added a job to fail and halt our CI if not up to date with the base branch, just to save us wasting the github actions minutes.

It also means that typically we only get 2 dependabot PRs per repository each day. We might be able to avoid that by changing our `schedule.time` and reacting quickly, but that also defeats the point of having dependabot do anything for us, we might as well have a daily task for someone to run `poetry lock` every morning and just test all our updates in one PR...

---

We deliberately set `open-pull-requests-limit: 1` to avoid having to have multiple PRs which we needed to repeatedly rebase and run our CI workflow. (Yes that could possibly also be avoided by not requiring PRs be up to date with the base branch, but we can't disable that requirement just for dependabot nor really do I want to, we do occasionally run into dependency clashes particularly with type-checking).

### Smallest manifest that reproduces the issue

I'll see if I can set up a bare public repo with some generic dependencies and make dependabot reproduce this behaviour.
