### ISSUE TITLE
Use private pypi registry without insecure-external-code-execution

### ISSUE THREAD

**Issue by mhaley-tignis** [dependabot/dependabot-core#10972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip >= 21.3

### Language version

Python 3.12

### Manifest location and content before the Dependabot update

/pyproject.toml
/requirements.txt

### dependabot.yml content

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  tignis-repo:
    type: python-index
    url: <redacted>
    username: <redacted>
    password: <redacted>
    replaces-base: true
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries: "*"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

I expect dependabot to be able to reference a private pypi repository, find version list for a package and compare it to the list found in the pyproject.toml file.

Instead, I encounter the following error in the dependabot logs:
```
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+--------------------------+
|          Errors          |
+--------------------------+
| unexpected_external_code |
+--------------------------+
```

And the following error in the Github UI:
```
 Dependabot refused to execute external code
Dependabot blocked external code required for this update. Please set insecure-external-code-execution: allow in the config if you trust all dependencies' supply chain.
```

The [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#insecure-external-code-execution) for setting `insecure-external-code-execution: allow` is not clear to me. The documents state
> Package managers with the package-ecosystem values ... pip may execute external code in the manifest as part of the version update process. This might allow a compromised package to steal credentials or gain access to configured registries.

Having credentials stolen is certainly something I do not want to happen, and I am confused what code in the manifest is being executed. I thought I would test removing the pyproject.toml file and see if I can just update requirements.txt, but I get the same error. A requirements.txt file is as simple as it can get, and definitely has no code in it. Is it possible to use private pypi registries without external code execution? If so, any tips on how to get started?
