### ISSUE TITLE
Dependabot is failing to authenticate against a private Hex Repisotiry

### ISSUE THREAD

**Issue by adamtharani** [dependabot/dependabot-core#11031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Hex

### Language version

Elixir

### Manifest location and content before the Dependabot update

/directory/mix.exs

### dependabot.yml content

```
version: 2

registries:
  fluxon-hex-repository:
    type: hex-repository
    repo: fluxon
    url: https://repo.fluxonui.com
    auth-key: "${{ secrets.FLUXON_HEX_REPO_AUTH_KEY }}"
    public-key-fingerprint: ${{ secrets.FLUXON_HEX_REPO_PUBLIC_KEY_FINGERPRINT }}
updates:
  - package-ecosystem: mix
    directory: "/"
    registries:
      - fluxon-hex-repository
    insecure-external-code-execution: allow
    schedule:
      interval: weekly
      day: thursday
    groups:
      production-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
```

### What you expected to see, versus what you actually saw

The package manager is failing to update due to `private_source_authentication_failure`
```
Handled error whilst updating ash: private_source_authentication_failure {:source=>"fluxon"}
```
