### ISSUE TITLE
NPM Install from a private registry

### ISSUE THREAD

**Issue by steve-gombos** [dependabot/dependabot-core#11038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

10.X

### Language version

20.X

### Manifest location and content before the Dependabot update

Engines in the `package.json`

```json
{
  "engines": {
    "node": ">=20.9.0",
    "npm": ">=10.1.0"
  }
}
```

The `.npmrc` file in the repository

```cmd
registry=https://private-repo-url
```

### dependabot.yml content

```yaml
version: 2

registries:
  private-npm:
    type: npm-registry
    url: https://private-repo-url
    token: ${{ secrets.PRIVATE_TOKEN }}
    replaces-base: true

updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - private-npm
    versioning-strategy: increase
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
```

### What you expected to see, versus what you actually saw

Unfortunately cannot provide links to logs or a working example since I do not have my own private registry (like my enterprise) but hopefully adding pertinent information here.

Expectation would be that when Dependabot attempts to install NPM that it sources it from either the NPMRC or Registries in the dependabot config.  

What actually happens is that it sources from the npmjs registry (which can be blocked by some enterprises), but then just hangs and consumes runners until the job is cancelled.

![image](https://github.com/user-attachments/assets/1206f444-d6c5-4868-b69b-e2f3b21121aa)

### Images of the diff or a link to the PR, issue, or logs

I am not familiar with dependabot enough, but not sure if these recent changes are correlated:
https://github.com/dependabot/dependabot-core/pull/10944
https://github.com/dependabot/dependabot-core/pull/10985

Here is what a previous job about 2 weeks ago looked like in the logs with the same package.json and dependabot.yml configs.
![image](https://github.com/user-attachments/assets/1f837b37-469e-4621-b899-10906144cc6f)
