### ISSUE TITLE
Gradle plugin version bumping

### ISSUE THREAD

**Issue by TobiasRoland** [dependabot/dependabot-core#1104]
Yesterday when running the [gradle versions plugin](https://github.com/ben-manes/gradle-versions-plugin) I noticed that dependabot does not bump my spring plugin version which was defined in the `build.gradle` plugin block 

```
plugins {
    // would expect the below to be bumped to 2.1.4.RELEASE
    id "org.springframework.boot" version "2.1.3.RELEASE"
}
```

Would be great if it dependabot could update this, too

**Comment by joshuatcasey** [comment]
This would be great for us too! We're using an `ext` block to set the Spring boot version for both the plugin and the BOM.

https://github.com/cloudfoundry/uaa/blob/develop/dependencies.gradle

**Comment by ColtonIdle** [comment]
@TobiasRoland how do you get the gradle versions plugin and dependabot working together?

**Comment by busches** [comment]
This is working for me today, appears to be added quite a while back https://github.com/dependabot/dependabot-core/commit/e571c5c6f3a812c0c51973ca063438d3cad71238

**Comment by zbynek** [comment]
@TobiasRoland is this still reproducable? If yes, could you share a link to the repo you're trying to update?

**Comment by koppor** [comment]
Does not work here.

Expected diff:

```diff
- id("org.openrewrite.rewrite") version("6.0.0")
+ id("org.openrewrite.rewrite") version("6.1.4")
```

Nothing happens.

All releases of the plugin are given there: https://github.com/openrewrite/rewrite-gradle-plugin/releases

Repository: https://github.com/jabref/jabref

**Comment by zbynek** [comment]
@koppor it seems the[ regex used to find plugin version declaration](https://github.com/dependabot/dependabot-core/blob/main/gradle/lib/dependabot/gradle/file_parser.rb#L227) is not generic enough. To allow dependabot to update that plugin you can just remove parentheses around plugin ID and version.

**Comment by koppor** [comment]
Interestingly, the plugin was not updated from 6.1.25 to 6.2.4 - even though that version is available: https://docs.openrewrite.org/reference/gradle-plugin-configuration

```groovy
id 'org.openrewrite.rewrite' version '6.1.25'
```

```yaml
version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    ignore:
      - dependency-name: com.microsoft.azure:applicationinsights-core
        versions:
          - ">= 2.5.a" # Blocked by https://github.com/microsoft/ApplicationInsights-Java/issues/1155
      - dependency-name: com.microsoft.azure:applicationinsights-logging-log4j2
        versions:
          - ">= 2.5.a" # Blocked by https://github.com/microsoft/ApplicationInsights-Java/issues/1155
```
