### ISSUE TITLE
Dependabot claims that it does  not support PNPM `v9.11.0`

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#11124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

v9.11.0

### Language version

18

### Manifest location and content before the Dependabot update

https://github.com/yeikel/kafka-ui/blob/dcb5d6edf6c3e1cf47a404f6f67be573de82b97f/frontend/package.json

### dependabot.yml content

```yml

- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Europe/London
  reviewers:
    - "kafbat/frontend"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  labels:
    - "type/dependencies"
    - "scope/frontend"

```

### What you expected to see, versus what you actually saw

Dependabot should be able to support within the minor versions of 9.x as per the code and the docs 

https://github.com/dependabot/dependabot-core/blob/d1608d6ecae730ea6acb957ced9cb8c67216f540/npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb#L155-L161

### Images of the diff or a link to the PR, issue, or logs

> > updater | 2024/12/13 04:03:05 INFO <job_932155108> Updating @testing-library/react from 14.3.1 to 16.1.0
>   proxy | 2024/12/13 04:03:06 [783] POST /update_jobs/932155108/record_update_job_error
> 2024/12/13 04:03:06 [783] 204 /update_jobs/932155108/record_update_job_error
> updater | 2024/12/13 04:03:06 INFO <job_932155108> Handled error whilst updating @testing-library/react: tool_version_not_supported {:"tool-name"=>"pnpm", :"detected-version"=>"v9.11.0", :"supported-versions"=>"9.15.0"}
>   proxy | 2024/12/13 04:03:06 [785] POST /update_jobs/932155108/record_ecosystem_meta

### Smallest manifest that reproduces the issue

```json

  "engines": {
    "node": "v18.17.1",
    "pnpm": "v9.11.0"
  }
```
