### ISSUE TITLE
Dependabot removing opencv-python dependency from poetry.lock file  

### ISSUE THREAD

**Issue by onuralpszr** [dependabot/dependabot-core#11136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip (poetry)

### Package manager version

1.8.5

### Language version

python 3.9,3.10,3.11,3.12,

### Manifest location and content before the Dependabot update

Before and After in PR because this issue happened when bot trigger update 

https://github.com/roboflow/supervision/pull/1740/files 

This update change "jupytext" but also removes opencv-python and  it is one my main requirement in repository shouldn't be delete it. I had to send commit to PR for prevent this and upgrade package(s) and run poetry locally to make it works. 

### dependabot.yml content

https://github.com/roboflow/supervision/blob/develop/.github/dependabot.yml

```
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆️
    target-branch: "develop"
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆️
    target-branch: "develop"
```

### What you expected to see, versus what you actually saw

Package upgrade should happen normally and it should NOT delete main deps from lock file in this case (opencv-python) 

### Native package manager behavior

Locally I tested with python 3.9,3.10.3.11,3.12 
- pip
- poetry

All works fine. Plus we have action in our repository do check for all of them with poetry
