### ISSUE TITLE
One specific GitHub Action is never updated

### ISSUE THREAD

**Issue by baynezy** [dependabot/dependabot-core#11149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

GitHub Actions

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  nuget-code-artifact:
    type: nuget-feed
    url: https://REDACTED.d.codeartifact.eu-west-2.amazonaws.com/nuget/team-packages/v3/index.json
    username: aws
    password: ${{secrets.CODE_ARTIFACT_TOKEN_PRIVATE_REPOS}}
  
  private-github-actions:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.PRIVATE_GITHUB_ACTIONS_TOKEN}}
  
  tf-cloud:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${{secrets.DEPENDABOT_TF_CLOUD}}
updates:
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    registries:
      - nuget-code-artifact
    schedule:
      interval: "daily"
    labels:
      - "flag:dependencies"
    open-pull-requests-limit: 10
      
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    registries:
      - private-github-actions
    schedule:
      interval: "daily"
    labels:
      - "flag:dependencies"
  
  - package-ecosystem: "terraform"
    directory: "/deploy/bucket" # Location of package manifests
    registries: "*"
    schedule:
      interval: "daily"
    labels:
      - "flag:dependencies"
  
  - package-ecosystem: "terraform"
    directory: "/deploy/lambda" # Location of package manifests
    registries: "*"
    schedule:
      interval: "daily"
    labels:
      - "flag:dependencies"
```

### What you expected to see, versus what you actually saw

I have a private repository in my organisation that I put my shared workflows in. These are used across many projects successfully.
I recently published a new tag version 1.0.0.8 of the repository.

Dependabot created a PR to update this. It updated every instance of each shared workflow except one. This has remained on the previous tag. This exact behaviour is replicated on every repository that uses these shared workflows.

I would expect that they all get updated at the same time.

### Successfully updated workflow (blocked-issue.yml):

```yaml
name: Blocked Issue Labeler

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  update:
    uses: My-Org/Shared.Workflows/.github/workflows/blocked-issue.yml@1.0.0.8
    secrets: inherit
```

### Unsuccessfully updated workflow (static-analysis.yml):

```yaml
name: Static Analysis
on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'test/**'
      - '**.sln'
      - '.github/workflows/static-analysis.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'test/**'
      - '**.sln'
      - '.github/workflows/static-analysis.yml'
jobs:
  scan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: My-Org/Shared.Workflows/.github/workflows/static-analysis.yml@0.0.2.3
    secrets: inherit
    with:
      project-name: 'Afterlife-Guide_AfterLife.Guide.Profile'
      test-filter: "Category!=LocalTest"
      has_integration_tests: true
```

If I run dependabot again it reports that this dependency is up to date.

```
updater | 2024/12/18 15:45:07 INFO <job_934922561> Checking if My-Org/Shared.Workflows 1.0.0.8 needs updating
  proxy | 2024/12/18 15:45:07 [078] GET [https://github.com:443/my-org/shared.workflows.git/info/refs?service=git-upload-pack](https://github.com/my-org/shared.workflows.git/info/refs?service=git-upload-pack)
  proxy | 2024/12/18 15:45:07 [078] 200 [https://github.com:443/my-org/shared.workflows.git/info/refs?service=git-upload-pack](https://github.com/my-org/shared.workflows.git/info/refs?service=git-upload-pack)
updater | 2024/12/18 15:45:07 INFO <job_934922561> Latest version is 1.0.0.8
updater | 2024/12/18 15:45:07 INFO <job_934922561> No update needed for My-Org/Shared.Workflows 1.0.0.8
```
