### ISSUE TITLE
NPM security update job doesn't pick minimal version when it's a transitive dependency

### ISSUE THREAD

**Issue by ryanbrandenburg** [dependabot/dependabot-core#11152]
[This line](https://github.com/dependabot/dependabot-core/blob/ba0bbf805a1b87c73b08f15447e0bea4a74e79e1/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb#L79) causes Dependabot-Core to choose the highest applicable version for transitive dependencies in NPM which can lead to weird behavior. Take [this example repo](https://github.com/ryanbrandenburg/crossspawn) and run it against this job:
```yaml
job:
   dependencies:
   - cross-spawn
   security-advisories:
   - dependency-name: cross-spawn
     affected-versions:
     - '>= 7.0.0, < 7.0.5'
     - '>= 0, < 6.0.6'
   existing-pull-requests:
   - - dependency-name: cross-spawn
       dependency-version: 7.0.5
   security-updates-only: true
   updating-a-pull-request: true
   commit-message-options:
     prefix: '[SECURITY] '
   experiments:
     lead_security_dependency: true
   source:
     directories:
     - /
     provider: github
     repo: ryanbrandenburg/crossspawn
     branch: main
   package-manager: npm_and_yarn
```
Which is modeled off a real scenario. The existing PR (with version 7.0.5) is not getting rebased because we try to create a new one instead (due to [this check failing](https://github.com/dependabot/dependabot-core/blob/ba0bbf805a1b87c73b08f15447e0bea4a74e79e1/updater/lib/dependabot/updater/operations/refresh_security_update_pull_request.rb#L284)). Of particular note to this scenerio is that cross-spawn 7.0.6 was published after the existing PR was created.
