### ISSUE TITLE
Dependabot not getting generated for react native app but working fine for other repo

### ISSUE THREAD

**Issue by mohamedfarees** [dependabot/dependabot-core#11180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 10.8.3

### Language version

Node 22.9.0

### dependabot.yml content

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# To manually trigger, add comment . make changes

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      # # Check for npm updates on Sundays
      # day: "monday"
      # # To run on Morning 9 AM IST
      # time: "09:00"
      # # Use Indian Standard Time (UTC +05:30)
      # timezone: "Asia/Calcutta"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    commit-message:
       prefix: "[NPM Dependencies] " 
       include: "scope" 
    labels: 
       - "dependencies"
    # Allow up to 10 open pull requests for pip dependencies. Default 5
    open-pull-requests-limit: 10

### What you expected to see, versus what you actually saw

Earlier every week we were getting dependabot PR. FOr past 3 weeks its not generating automatically, every week we manual make changes here and run it. we want to know why, we have another repo with NextJS and Python there its working fine

**Comment by a-schur** [comment]
@mohamedfarees please provide a repository with manifest files where the issue can be reproduced.

**Comment by mohamedfarees** [comment]
its private repo 
dependant.yaml
```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# To manually trigger, add comment . make changes

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "monday"
      # To run on Morning 9 AM IST
      time: "09:00"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Calcutta"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
    commit-message:
       prefix: "[NPM Dependencies] " 
       include: "scope" 
    labels: 
       - "dependencies"
    # Allow up to 10 open pull requests for pip dependencies. Default 5
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "monday"
      # To run on Morning 9 AM IST
      time: "09:00"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Calcutta"
    open-pull-requests-limit: 10
    commit-message: 
       prefix: "[GitHub Dependencies] " 
       include: "scope" 
    labels: 
       - "dependencies"

```
