### ISSUE TITLE
Problem with nested local modules in terraform

### ISSUE THREAD

**Issue by iGlasmacher-funnellab** [dependabot/dependabot-core#11203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

terraform

### Language version

1.10.0

### What you expected to see, versus what you actually saw

I have some local modules which are referenced in a chain, e.g. `modules/global/app.tf` calls a module at `../foo` with each module having its own providers. 

Now I want to upgrade the provider, but not the `provider.tf` files are updated.
They have the following form
``` tf
terraform {
  required_version = ">= 1.7.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.82.2"
    }
  }
}
```

Now on `terraform providers lock [...]` in the Dependabot workflow, there is the error
```
│ Error: Could not retrieve providers for locking
│ 
│ Terraform failed to fetch the requested providers for linux_amd64 in order to
│ calculate their checksums: some providers could not be installed:
│ - registry.terraform.io/hashicorp/aws: locked provider
│ registry.terraform.io/hashicorp/aws 5.75.1 does not match configured version
│ constraint >= 4.40.0, >= 5.46.0, 5.75.1, 5.82.2; must use terraform init
│ -upgrade to allow selection of new versions.
```

This is because the `5.75.1` constraint was not replaced by the `5.82.2` constraint in every modules `provider.tf`.

If the modules are not chained (a local module includes another local module), everything works just fine and all the providers of the top level included modules are updated correctly.

**Comment by flipcc** [comment]
Hello, could you please share your dependabot configuration? I encounter something similar and want to follow-up on my side.

**Comment by bodgit** [comment]
We're seeing the same issue, nested local modules are not being updated in the pull requests.

My `dependabot.yml` is as simple as:
```yaml
version: 2

updates:
  - package-ecosystem: terraform
    directory: /
    registries: '*'
    schedule:
      interval: daily
```
Setting `directories` to `**/*` or similar doesn't work as this just results in multiple pull requests being opened, which still produces the same erroring `terraform plan` run.

**Comment by austindrenski** [comment]
@bodgit wrote (https://github.com/dependabot/dependabot-core/issues/11203#issuecomment-2674254770):
> Setting `directories` to `**/*` or similar doesn't work as this just results in multiple pull requests being opened, which still produces the same erroring `terraform plan` run.

FWIW you should be able to use the `groups` config to bundle those pull requests, e.g.:

```yaml
- package-ecosystem: terraform
  directories:
  - .tf/*
  groups:
    aws:
      patterns:
      - hashicorp/aws
    datadog:
      patterns:
      - datadog/datadog
  schedule:
    interval: daily
```
