### ISSUE TITLE
Dependabot configured, but doesn't check for updates and shows "Dependabot version updates aren't configured yet"

### ISSUE THREAD

**Issue by YaLTeR** [dependabot/dependabot-core#11201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

cargo, github-actions

### Manifest location and content before the Dependabot update

https://github.com/YaLTeR/niri/blob/main/Cargo.toml

https://github.com/YaLTeR/niri/blob/main/.github/workflows/ci.yml

### dependabot.yml content

https://github.com/YaLTeR/niri/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I'm trying to configure Dependabot.

At first it checked for updates, but errored out for both Cargo and github_actions. The logs unfortunately got overwritten as I tried to re-run the workflows later, but for Cargo it errored because it failed to parse workspace from my subcrate Cargo.toml (seems some logic mismatch between dependabot and cargo itself), and for github_actions with some weird failed to resolve version error. It did successfully create PRs to update some Cargo packages though, which I later merged.

Since then, it stopped running any workflows or doing anything, even validating the dependabot.yml changes. The Insights panel shows "Dependabot version updates aren't configured yet".

Following #7357 and similar issues, I tried enabling/disabling security updates, and deleting and re-creating dependabot.yml from GitHub UI. Nothing helps, it keeps being stuck like this.

**Comment by YaLTeR** [comment]
Update: Dependabot seems to *work*, at least for Cargo dependencies: it opened two PRs today. Not sure about github_actions.

But the Dependabot panel in Insights still shows that it's not configured, and I can't check anything there.

**Comment by davidrunger** [comment]
I was having a similar issue, where Dependabot updates partially seemed to work (in my case, updating GitHub Actions but not updating Ruby/Bundler gems) and where the Dependabot panel in Insights showed that Dependabot was not enabled. Deleting and re-creating dependabot.yml from GitHub UI (as suggested [here](https://github.com/dependabot/dependabot-core/issues/7357#issuecomment-2468708560)) also did not help me. I didn't try enabling/disabling security updates, so I'm not sure if that would have helped.

What did seem to fix the issue was this: https://github.com/davidrunger/david_runger/pull/6806/files , i.e. switching from

```yml
    schedule:
      interval: cron
      cronjob: '4 4 * * *'
```

to

```yml
    schedule:
      interval: 'daily'
```

(Note: these are not equivalent. The cron schedule runs on weekends, but the 'daily' schedule does not.)

Maybe this is a bug with the relatively recently released cron scheduling for Dependabot? https://github.com/dependabot/dependabot-core/issues/6339

If so, I guess that this doesn't explain your issue, @YaLTeR , since you encountered this issue prior to the introduction of that cron scheduling feature. However, I mention it here in case it's helpful to anyone else. And maybe even for you, perhaps changing the `schedule` value temporarily to something else and then changing it back might resolve the issue?

**Comment by YaLTeR** [comment]
I always had mine using
```yml
    schedule:
      interval: "daily"
```
so I guess that's not the problem for me

**Comment by davidrunger** [comment]
@YaLTeR Yeah, probably so (as I mentioned in my comment), but I do still wonder if changing from `interval: "daily"` to e.g. `interval: "weekly"` and then back to `interval: "daily"` might possibly resolve your issue? It might be worth a shot. 🤷‍♂

**Comment by YaLTeR** [comment]
Didn't seem to help, oh well

**Comment by v-abhishekbhaskar** [comment]
@YaLTeR can you please let me know if this issue still persists and I'll have a further look? Thanks!

**Comment by YaLTeR** [comment]
Yes, in the niri repo Dependabot works for Cargo but still ignores GitHub Actions. The Dependabot panel in Insights still shows it's not configured.

**Comment by v-abhishekbhaskar** [comment]
@YaLTeR I have re-synced the aLTeR/niri repository. Hopefully, it fixes the issue now, but if not, please let me know and I'll debug further.

**Comment by YaLTeR** [comment]
Still says:

<img width="896" height="452" alt="Image" src="https://github.com/user-attachments/assets/0a1ae331-a0b4-4a98-b0d8-bedd65c8bbdc" />

We'll see in a few days if it opens any GitHub Actions update PR I guess

**Comment by nathan-gage** [comment]
Having the same issue -- using `uv` and `bun` in a monorepo.

**Comment by franziskahahn** [comment]
warning: Long text following.
TL;DR; For me "Dependabot version updates aren't configured yet" appears when I use "open-pull-requests-limit: 0" in the dependabot.yml.
**To only check for security updates, I wonder if I can use ignore or allow option. I hope one of the experts here can answer that!**


I ~am having~ had the same issue in a small, rarely-updated go repository. It never had dependabot running before - the config is brandnew. _(workaround working for me: see below)_

In this case the goal is to configure dependabot to only find CVEs ( open-pull-requests-limit: 0 ) and therefore will rarely find something. But the check should run anyways - configured by a cron schedule. It is a pretty big config with cron schedule, multiple ecosystems, commit-message prefix and so on. With that config I ran into same error as described in this issue here. 

```
#file: noinspection YAMLSchemaValidation
version: 2
registries:
  private-packagist:
    type: composer-repository
    url: https://repo.packagist.com/*****
    (...) 
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "35 9 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0 # this prevents "normal" updates but security updates will still be created!

  - package-ecosystem: "composer"
    directory: "/"
    registries:
      - private-packagist
    schedule:
      interval: "cron"
      cronjob: "35 9 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0 # this prevents "normal" updates but security updates will still be created!

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "35 9 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0 # this prevents "normal" updates but security updates will still be created!

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "35 9 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0 # this prevents "normal" updates but security updates will still be created!

```


Interesting for me was, that also the internal/auto-generated dependabot workflow is not listed in actions tab (see screenshot of a working repo below*). I am assuming that these workflows become visible (are created?) when they get executed the first time?! So here something was stuck.
<img width="664" height="673" alt="Image" src="https://github.com/user-attachments/assets/ac562d33-3e11-4365-a749-4cbdbd6c3a11" />
_(This is missing in my broken repo)_


**Soo.. What I tried and was NOT working:**
1. Committing minor (code comments) changes of dependabot.yml
2. Committing an actual change in dependabot,yml (change schedule time) 
3. since repo had no custom workflow yet, creating the workflows folder with a .gitkeep file
4. Disabling and re-enabling various dependabot setting
5. waiting until scheduled time 
6. delete dependabot.yml and re-add it. 


**What worked in the end:**
1. delete the dependabot.yml with the complex config (main)
2. create the dependabot default.yml (which contains an error since package-ecosystem is "") -> Syntax error message was shown in settings -> something changed at least, good sign
3. update the a basic small dependabot.yml to gomod daily:
     a.
```
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
```
4. Then finally dependabot run and the workflow action appeared - and also "Dependabot version updates aren't configured yet" finally disappeared and was replaced by the recent run list! Stuck status was gone 🥳 
5. Opened a pull request with complex config, not merged (but checks ran) and now again "Dependabot version updates aren't configured yet" appeared. 😢 So something in the complex config is causes the "Dependabot version updates aren't configured yet" error message even though syntax is valid. 
6. Reduced to only one ecosystem with schedule and wait until scheduled time - still "Dependabot version updates aren't configured yet" error message and no automated job. But github action Dependabot Updates still visible in action menu. 
```
#file: noinspection YAMLSchemaValidation
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "15 11 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0
``` 
8. Then I merged a new pull request with all ecosystems but removed "open-pull-requests-limit: 0",  and set it to schedule daily instead of cron. Now it's working again! 
So it is either about the open-pull-requests-limit or about the cron.
9. Re-Added "open-pull-requests-limit: 0" -> error message appears again. So it is about this setting!
10. removed  "open-pull-requests-limit: 0" and re-added schedule cron -> all good! "Dependabot version updates aren't configured yet" disappeared! 
11. But I only want security updates so I tried this, since in my opinion that's what [documentation](https://docs.github.com/de/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file) recommends:
```
#file: noinspection YAMLSchemaValidation
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "45 11 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "45 11 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "45 11 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "45 11 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "45 11 * * 1-5"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "chore: "
    open-pull-requests-limit: 0
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
```
-> error again 😢 
12. So open-pull-requests-limit: 0 consistently breaks Dependabot, even with groups. Let's try a different approach: use ignore rules to suppress all version updates instead. Security updates are explicitly documented to bypass ignore rules, so this should achieve the same goal without breaking Dependabot:
```
ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
        - "version-update:semver-patch"
```

And that seems to work. But so far there was no package vulnerable. **Since I couldn't find it explicitly said in documentation:
Will this ignore block still allow security updates?**

At least for allow [documentation states "update-types only affects version updates, not security updates."](https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#update-types-allow). For ignore I could not find that hint.
