### ISSUE TITLE
ignore github-actions hosted in our org is not working

### ISSUE THREAD

**Issue by zoezhangmattr** [dependabot/dependabot-core#11263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### dependabot.yml content

```yml
version: 2
updates:
  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    # Check for updates every month (weekdays)
    schedule:
      interval: "daily"
    # if set to 0 will disable dependabot version updates
    # open-pull-requests-limit: 0
    groups:
      all-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "myorg/reusable-action"
    ignore:
      - dependency-name: "myorg/reusable-action"
 ```

### What you expected to see, versus what you actually saw

dependabot update should ignore my private action
but still it tried to fetch it, and throw 401 (without auth)

**Comment by jim-weller** [comment]
I would also like `ignore:` to honor this. I have a composite action that I want to run on dependabot PRs, but the dependabot run always shows as failed because of the 401 trying to reach my Org's private repo hosting the composite aciton.

**Comment by jim-weller** [comment]
Nevermind. `ignore:` is working!

dependabot.yml
```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "MyOrg/my-action"
```

Log
```
updater | 2025/05/09 06:25:14 INFO <job_1013066009> All versions of MyOrg/my-action ignored, no update allowed
```
