### ISSUE TITLE
Dependabot is updating requirements.txt files in subfolders when only the `directory` option is set

### ISSUE THREAD

**Issue by nfelt14** [dependabot/dependabot-core#11360]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

poetry^=1.8

### Manifest location and content before the Dependabot update

- /pyproject.toml
- /docs/requirements.txt (shouldn't be updated)
- /tests/requirements.txt (shouldn't be updated)

### dependabot.yml content

```yaml
---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gh-actions-dependencies:
        patterns: ['*']
    labels: [gh-actions, dependencies]
    commit-message:
      prefix: gh-actions
      include: scope
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    groups:
      python-dependencies:
        patterns: ['*']
    labels: [python, dependencies]
    commit-message:
      prefix: python-deps
      include: scope
```

### What you expected to see, versus what you actually saw

I expect that only the `pyproject.toml` file is updated, but dependabot is updating the requirements files as well.

**Comment by v-abhishekbhaskar** [comment]
The [exclude-paths](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#exclude-paths-) feature of dependabot can be used to exclude specific files and sub-directories when scanning for dependabot updates.

This is a sample `dependabot.yml` configuration with exclude-paths-
```
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    # Exclude subdirectory requirements.txt files
    exclude-paths:
      - "docs/"
      - "tests/"
    groups:
      python-dependencies:
        patterns: ['*']
    labels: [python, dependencies]
    commit-message:
      prefix: python-deps
      include: scope
```
