### ISSUE TITLE
Invalid version in PR body when updating multiple versions of the same package

### ISSUE THREAD

**Issue by wraithgar** [dependabot/dependabot-core#11376]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm@11

### Language version

Node.js 22.13.0

### Manifest location and content before the Dependabot update

 - `/package.json`
 - `/package-lock.json`

### dependabot.yml content

```yaml
# This file is automatically added by @npmcli/template-oss. Do not edit.

version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    target-branch: "main"
    allow:
      - dependency-type: direct
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: deps
      prefix-development: chore
    labels:
      - "Dependencies"
    open-pull-requests-limit: 10
    groups:
      dependency-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
```

### Updated dependency

`undici` from 5.28.4 to 5.28.5

AND

`undici` from 6.21.0 to 6.21.1

### What you expected to see, versus what you actually saw

When a PR is made updating two different versions of the same package, the PR body states an incorrect version for one of the two updates.

In https://github.com/npm/documentation/pull/1450 you can see it says

> Updates `undici` from 5.28.4 to 6.21.1

and

> Updates `undici` from 6.21.0 to 6.21.1

The first one should read

> Updates undici from 5.28.4 to 5.28.5

The commit in the PR is correct, it is just the PR body that has this incorrect version.

### Native package manager behavior

N/A

### Images of the diff or a link to the PR, issue, or logs

 - https://github.com/npm/documentation/pull/1450
 - https://github.com/npm/statusboard/pull/935
