### ISSUE TITLE
Nuget: ignore and grouping don't work as expected

### ISSUE THREAD

**Issue by SeanFeldman** [dependabot/dependabot-core#11380]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

.NET 8

### dependabot.yml content

```yaml
version: 2

updates:
  - package-ecosystem: nuget
    target-branch: master
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1000
    groups:
      Stukent:
        patterns:
          - 'Stukent.*'
      Microsoft:
        patterns:
          - 'Microsoft.*'
          - 'Azure.*'
      TestLibraries:
        patterns:
          - 'Moq.*'
          - 'FluentAssertions.*'
          - 'xunit.*'
          - 'coverlet.*'
          - 'Verify.*'
          - 'Microsoft.NET.Test.Sdk.*'
      ThirdParty:
        patterns:
          - '.*'
    ignore:
      - dependency-name: 'FakeItEasy.*'
        versions: [ '8.*', '9.*' ]
        update-types: [ 'version-update:semver-major' ]
``` 

### Updated dependency

<img width="463" alt="Image" src="https://github.com/user-attachments/assets/60a4634d-572b-4553-bda8-c5c92d0b8db5" />

### What you expected to see, versus what you actually saw

<img width="463" alt="Image" src="https://github.com/user-attachments/assets/fde7a1de-7bdd-4c55-b19c-b330dc656d1c" />

### Images of the diff or a link to the PR, issue, or logs

[raw.log.txt](https://github.com/user-attachments/files/18512810/raw.log.txt)

### Smallest manifest that reproduces the issue

`test.csproj` project

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Core" Version="1.44.0" />
      <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.0" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
      <PackageReference Include="FakeItEasy" Version="7.4.0" />
      <PackageReference Include="xunit" Version="2.9.0" />
      <PackageReference Include="coverlet.msbuild" Version="6.0.0" />
    </ItemGroup>

</Project>
```

**Comment by rhyskoedijk** [comment]
@SeanFeldman I've run in to similar issues in the past; These tweaks might give the results you're expecting

```yaml
updates:
  - package-ecosystem: nuget
    groups:
      TestLibraries:
        patterns:
          - 'xunit*' # 'xunit.*' will not match against package name 'xunit', there is no trailing `.` in this case
    ignore:
      - dependency-name: 'FakeItEasy.*'
        versions: [ '>=8.0.0' ] # this contradicts the official documentation, but I've had more success using ">=8.0.0" over "8.*"
```

I also see that the groups `Stukent` and `ThirdParty` don't match any dependencies and could be removed unless you're expecting them to use in the future.
