### ISSUE TITLE
[NuGet] ignore semver-major doesn't appear to work

### ISSUE THREAD

**Issue by eerhardt** [dependabot/dependabot-core#11398]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Nuget

### Language version

.NET 9

### Manifest location and content before the Dependabot update

https://github.com/dotnet/aspire/blob/0ca981a95feccfc4cec15ebee6bd06bd7c792fe2/eng/Versions.props#L76-L104

### dependabot.yml content

https://github.com/dotnet/aspire/blob/0ca981a95feccfc4cec15ebee6bd06bd7c792fe2/.github/dependabot.yml#L1-L87

```
version: 2
registries:
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: nuget
    directory: "/"
    registries:
      - public-nuget
    schedule:
      day: monday
      interval: weekly
      time: "07:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 15
    ignore:
      # handled by Darc/Maestro flows
      - dependency-name: "Microsoft.DotNet.Arcade.Sdk"
      - dependency-name: "Microsoft.DotNet.Helix.Sdk"
      - dependency-name: "Microsoft.DotNet.SharedFramework.Sdk"
      - dependency-name: "Microsoft.Build.NoTargets"
      # Pinned versions that should not be updated
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
      # NetPlatform dependencies shouldn't update across major versions
      - dependency-name: "Microsoft.AspNetCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.EntityFrameworkCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Npgsql.*"
        update-types: ["version-update:semver-major"]
    groups:
      Azure:
        patterns:
          - "Azure.*"
          - "Microsoft.Azure.*"
          - "Microsoft.Extensions.Azure"
      AspNetCoreHealthChecks:
        patterns:
          - "AspNetCore.HealthChecks.*"
      FluentUi:
        patterns:
          - "Microsoft.FluentUI.*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"
      Orleans:
        patterns:
          - "Microsoft.Orleans*"
      NetPlatform:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.EntityFrameworkCore.*"
          - "Microsoft.Extensions.*"
          - "System.*"
        update-types:
          - 'minor'
          - 'patch'
      Npgsql:
        patterns:
          - "Npgsql.*"
        update-types:
          - 'minor'
          - 'patch'
      MicrosoftDotNet:
        patterns:
          - "Microsoft.DotNet.*"
      Grpc:
        patterns:
          - "Grpc.*"
      Polly:
        patterns:
          - "Polly.*"
    labels:
      - "area-codeflow"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - area-engineering-systems
```

### Updated dependency

dependabot made https://github.com/dotnet/aspire/pull/7226 with the first commit https://github.com/dotnet/aspire/pull/7226/commits/780a35802b5c63b0166e5b74feddf0d800417e2e

### What you expected to see, versus what you actually saw

Since I'm saying to ignore semver-major on on Microsoft.Extensions.* and System.* dependencies, I expect that those dependencies won't get lifted from v8.0 to v9.0

However, dependabot is updating these dependencies across major versions in this PR.

### Images of the diff or a link to the PR, issue, or logs

![Image](https://github.com/user-attachments/assets/b6c1b4ea-81b2-4c71-a5f7-cd0f74cccc37)

https://github.com/dotnet/aspire/actions/runs/12937683800/job/36086133337

**Comment by eerhardt** [comment]
@brettfo - am I doing something wrong in the dependabot yml config? Is this supposed to work:

```
    ignore:
      # NetPlatform dependencies shouldn't update across major versions
      - dependency-name: "Microsoft.AspNetCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.EntityFrameworkCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Npgsql.*"
        update-types: ["version-update:semver-major"]
```

**Comment by brettfo** [comment]
@eerhardt That scenario _should_ work because the common code handles the `ignore` section; that's not NuGet specific, but something is obviously going wrong.  I'll dig in a bit.

**Comment by brettfo** [comment]
@abdulapopoola and/or @jakecoffman Could I get some help routing this?  The `dependabot.yml` file was updated in [this PR](https://github.com/dotnet/aspire/pull/7125) and shortly after that [this update job](https://github.com/dotnet/aspire/actions/runs/12948230998/job/36116453468) was run, but examining the job JSON file shows an empty `ignore-conditions` property where I would have expected it to have several values.

**Comment by bricelam** [comment]
Possibly related to #4075 (same issue but for ignored `versions`)

**Comment by joaorosado** [comment]
I'm also having this issue recently on many of my repos.

It appears to be related to the groups feature. And in my case it's raising things that doesn't even appear on the PR description.

I cannot share a link since these are private repos/dependencies but here are some screenshots:

![Image](https://github.com/user-attachments/assets/697f87d5-62fb-46b0-b1fc-951b9502e572)

![Image](https://github.com/user-attachments/assets/f3da280c-06b9-4ff4-b430-ea522e4436ef)

![Image](https://github.com/user-attachments/assets/d380148f-ab74-47b1-b98f-b53ed4f10ce1)

There is no dependency from the one correctly being raised and the other one.
In fact the one being raised here to 12.* has a dependency to the one in the PR, but there is no reason for that raise at all all versions are compatible between themselves.

**Comment by maurofranchi** [comment]
@brettfo we are facing the same issue. 
Here is the depednabot.yml file:

```yaml
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Dublin"
    open-pull-requests-limit: 25
    commit-message:
      prefix: "chore(gh-actions): "
    groups:
      dotnet:
        patterns:
          - "*" # Prefer a single PR per solution update.
  # NuGet packages - only update Directory.Packages.props
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Dublin"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(nuget): "
    allow:
      # Only update dependencies defined in Directory.Packages.props
      - dependency-type: "direct"
    groups:
      awssdk:
        patterns:
          - "AWSSDK*"
          - "Amazon.*"
      masstransit:
        patterns:
          - "MassTransit*"
      hangfire:
        patterns:
          - "Hangfire*"
      npg:
        patterns:
          - "Npgsql*"
      otel:
        patterns:
          - "OpenTelemetry*"
      Nunit:
        patterns:
          - "NUnit*"
      Swagger:
        patterns:
          - "Swashbuckle*"
      Microsoft:
        patterns:
          - "Microsoft.*"
      GraphQL:
        patterns:
          - "GraphQL*"
      IdempotentAPI:
        patterns:
          - "IdempotentAPI.*"
    ignore:
      # Ignore major version updates for the following
      - dependency-name: "Microsoft.NETCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      # Ignore major version updates for dotnet tools
      - dependency-name: "dotnet-ef"
        update-types: ["version-update:semver-major"]
```

Here are a couple of screenshots from the PR it opened, showing that it updated several packages, including some we had explicitly instructed it to ignore for major version upgrades.

![Image](https://github.com/user-attachments/assets/cdcea0a8-dc27-40da-a089-f67bc64cb2e6)

![Image](https://github.com/user-attachments/assets/5ba3d914-f350-4335-acff-df6c58aac6b7)

The upgrade of the packages for AWSSDK and Amazon should have been part of a separate PR. Same for the  Swashbuckle ones.

Are we doing something wrong?
The log has 90k lines but I can't see any warning or error
