### ISSUE TITLE
Dependabot unexpectedly recreates manually-modified `groups` PRs

### ISSUE THREAD

**Issue by joshuagoran** [dependabot/dependabot-core#11402]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

```yaml
version: 2
updates:
    - package-ecosystem: npm
      directory: /frontend
      schedule:
          interval: weekly
          day: monday
          time: '08:00'
          timezone: America/New_York
      open-pull-requests-limit: 2
      labels:
          - dependencies
          - javascript
      registries: '*'
      groups:
          babel:
              patterns:
                  - '@babel/*'
          d3:
              patterns:
                  - 'd3-*'
          eslint:
              patterns:
                  - 'eslint*'
          mui:
              patterns:
                  - '@mui/*'
                  - '@emotion/*'
          storybook:
              patterns:
                  - '@storybook/*'
                  - 'storybook'
          tanstack:
              patterns:
                  - '@tanstack/*'
          testing-library:
              patterns:
                  - '@testing-library/*'
          turf:
              patterns:
                  - '@turf/*'

    - package-ecosystem: pip
      directory: /backend
      schedule:
          interval: weekly
          day: monday
          time: '08:00'
          timezone: America/New_York
      open-pull-requests-limit: 2
      labels:
          - dependencies
          - python
      registries: '*'

registries:
    [REDACTED]-git:
        type: git
        url: https://github.com
        username: [REDACTED]
        password: [REDACTED]
```

### What you expected to see, versus what you actually saw

We had an open, Dependabot-generated version update PR for our `mui` group. Due to breaking changes within that version update PR, we manually made some changes and started conversations about how to resolve the issue. Up to this point everything was as-expected.

#### Expected behavior

Dependabot would carry on with creating new PRs for other dependencies and groups, but that our open & _modified_ PR would not be recreated by Dependabot unless we manually ran the `@dependabot recreate` command. Manual commits and user conversations on the PR would be preserved.

#### Actual behavior

Once our next version update job ran (triggered manually, in case that matters), the PR was completely recreated, losing both our manual commits AND our conversations, generally creating a confusing experience. The manually-modified PR does not appear anywhere, including in our closed PRs.

---

#### Thoughts

Being unable to rely on Dependabot to not wipe out manual effort is very frustrating and unintuitive. If unavoidable, it would be far more useful to preserve the original PR if it had been edited, even if it is closed and replaced. Further, it seems to indicate an inconsistency in behavior when using `groups`, as we have not previously experienced this behavior for individual PRs that have been manually modified.
