### ISSUE TITLE
Dependabot fails to update gems when using Ruby 3.4 with tool_version_not_supported

### ISSUE THREAD

**Issue by nickjer** [dependabot/dependabot-core#11427]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

Bundler 2.6.2

### Language version

Ruby 3.4.1

### Manifest location and content before the Dependabot update

The `Gemfile` looks like...

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

source 'https://rubygems.pkg.github.com/<repo>' do
  gem '...'
end

ruby file: '.ruby-version'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.0.0'

...
```

and the `.ruby-version` file looks like...

```
3.4.1
```

### dependabot.yml content

```yaml
version: 2
registries:
  ruby-github:
    type: rubygems-server
    url: https://rubygems.pkg.github.com
    token: ${{ secrets.BP_GITHUB_TOKEN }}
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    insecure-external-code-execution: allow
    registries:
      - ruby-github
    allow:
      - dependency-type: "all"
```

### What you expected to see, versus what you actually saw

I do not expect to see the following errors...

```
updater | 2025/01/28 16:26:54 INFO <job_955018544> Checking if pg 1.5.9 needs updating
  proxy | 2025/01/28 16:26:54 [035] POST /update_jobs/955018544/record_update_job_error
  proxy | 2025/01/28 16:26:54 [035] 204 /update_jobs/955018544/record_update_job_error
updater | 2025/01/28 16:26:54 INFO <job_955018544> Handled error whilst updating pg: tool_version_not_supported {:"tool-name"=>"ruby", :"detected-version"=>">= 3.4", :"supported-versions"=>"1.8.7, 1.9.3, 2.0.0, 2.1.10, 2.2.10, 2.3.8, 2.4.10, 2.5.9, 2.6.9, 2.7.6, 3.0.6, 3.1.6, 3.2.4, 3.3.6"}

....

updater | 2025/01/28 16:33:21 INFO Results:
Dependabot encountered '340' error(s) during execution, please check the logs for more details.
+-------------------------------------------------------------------------------------+
|                            Dependencies failed to update                            |
+--------------------------------------------------------+----------------------------+
| pg                                                     | tool_version_not_supported |
| array_enum                                             | tool_version_not_supported |
| puma                                                   | tool_version_not_supported |
| sass-rails                                             | tool_version_not_supported |
| bootsnap                                               | tool_version_not_supported |
| kamal                                                  | tool_version_not_supported |
...
```

The odd thing is that other repos that are also running Ruby 3.4 do not see this error. So I am not entirely sure what is triggering it for this specific repo.
