### ISSUE TITLE
Dependabot closes PR if not merged before next interval triggers

### ISSUE THREAD

**Issue by sklakegg** [dependabot/dependabot-core#11439]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

maven

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:51"
      timezone: "Europe/Oslo"
    groups:
      patch-and-minor:
        update-types:
          - "patch"
          - "minor"
      major:
        update-types:
          - "major"
```

### What you expected to see, versus what you actually saw

With the current dependabot.yaml, we check the dependencies with a daily interval. If there is no current open dependabot PR in the repo, dependabot will create 2 PRs as specified in the groups config.

The next time the interval triggers again, we expect Dependabot to take no action (since dependencies has not changed in this case), or update the current PR if there is any changes.

But instead dependabot closes the PR with the following message: "Looks like these dependencies are no longer updatable, so this is no longer needed." This makes no sense to me, since nothing has changed.

Next interval again, since there is no existing PRs, dependabot creates 2 new PRs again. The cycle continues...

### Images of the diff or a link to the PR, issue, or logs

![Image](https://github.com/user-attachments/assets/e88f025e-f547-4060-902e-3481bc6c1343)

### Smallest manifest that reproduces the issue

Use the following yaml. Set the time firstly to a few minutes into the feature to trigger the PR creations. Then update the time again to a few mins into the future, and watch dependabot close the PRs. (Same approach used to show the issue in the image)

```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:51"
      timezone: "Europe/Oslo"
    groups:
      patch-and-minor:
        update-types:
          - "patch"
          - "minor"
      major:
        update-types:
          - "major"
```
