### ISSUE TITLE
Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly Microsoft.Build, Version=15.1.0.0

### ISSUE THREAD

**Issue by SeanFeldman** [dependabot/dependabot-core#11455]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

C#

### Manifest location and content before the Dependabot update

[dependabot.log.txt](https://github.com/user-attachments/files/18622452/dependabot.log.txt)

### Updated dependency

n/a

### What you expected to see, versus what you actually saw

Shoed not throw exceptions

### Images of the diff or a link to the PR, issue, or logs

[dependabot.log.txt](https://github.com/user-attachments/files/18622488/dependabot.log.txt)

### Smallest manifest that reproduces the issue

`.github\dependabot.yml`

```yml
version: 2

registries:
  # Azure DevOps private feed
  my-feed:
    type: nuget-feed
    key: "dotnet"
    url: "https://pkgs.dev.azure.com/My/_packaging/MyNuget/nuget/v3/index.json"
    token: PAT:${{ PAT }}

updates:
  - package-ecosystem: "nuget"
    target-branch: master
    directory: /
    registries: 
      - my-feed
    commit-message:
      prefix: "deps"
    schedule:
      interval: weekly
      day: sunday      
    open-pull-requests-limit: 1000
    groups:
      My:
        patterns:
          - 'My.*'
      Microsoft:
        patterns:
          - 'Microsoft.*'
          - 'Azure.*'
      TestLibraries:
        patterns:
          - 'Moq*'
          - 'FakeItEasy*'
          - 'FluentAssertions*'
          - 'xunit*'
          - 'coverlet*'
          - 'Verify*'
          - 'Microsoft.NET.Test.Sdk*'
      ThirdParty:
        patterns:
          - '.*'
    ignore:
      - dependency-name: 'FluentAssertions*'
        versions: [ '>=8.0.0' ]
        update-types: [ 'version-update:semver-major' ]
```

`AzDO pipeline yaml`

```yml
schedules:
  - cron: "0 0 */7 * *"
    displayName: 'Run Dependabot (once a week)'  
    always: true 
    branches:
      include:
        - master
    batch: true

trigger: none # Disable CI trigger

variables:
  - group: Dependabot

jobs:
  - job: Default
    timeoutInMinutes: 60
    
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
      - task: NuGetAuthenticate@1
        displayName: "Authenticate to NuGet feed"

      - task: dependabot@2
        displayName: 'Run Dependabot'
        inputs:
          useConfigFile: true
          useUpdateScriptvNext: true
          azureDevOpsAccessToken: $(System.AccessToken)
        env:
          PAT: $(System.AccessToken)
```

**Comment by SeanFeldman** [comment]
Closing as "resolved".
The workaround was to use an experiment:

```
      - task: dependabot@2
        displayName: 'Run Dependabot'
        inputs:
          useConfigFile: true
          useUpdateScriptvNext: true
          azureDevOpsAccessToken: $(System.AccessToken)
          experiments: nuget-install-dotnet-sdks=true
```
