### ISSUE TITLE
Dependabot does not update scoped package in pnpm catalog

### ISSUE THREAD

**Issue by mgred** [dependabot/dependabot-core#11491]
Hey,

the new pnpm catalog feature is nice and we got our first PR from the bot ❤  

In our case it was `vitest` updated from `3.0.2` to `3.0.5`. We also use `@vitest/coverage-v8` which aligns with the versioning of `vitest` but wan't updated. I expected dependabot to update this package, too:

<img width="326" alt="Image" src="https://github.com/user-attachments/assets/b23a483d-aa94-4f45-8e14-009f22d2725d" />

As far as I can say, we have to wrap the scoped package name because YAML wants it that way. May this be the reason why dependabot does not update the package accordingly?

Tnaks for any feedback and advice

**Comment by robaiken** [comment]
Hey @mgred! Looking at how people use named catalogs, I noticed not everyone groups their packages the same way, so updates now happen independently by default. If you want `vitest` and `@vitest/coverage-v8` to update together, check out the [group update feature](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--). Here's an example config:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
```

This will create a single PR for all vitest-related updates!
