### ISSUE TITLE
Resolving a dependabot alert on a repository using the Github NPM Package Registry looks for updates in the wrong registry

### ISSUE THREAD

**Issue by ImRodry** [dependabot/dependabot-core#11496]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

yarn v4.5.3

### Language version

Node.js v22.13.1

### dependabot.yml content

```yaml
version: 2
registries:
  private:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: npm
    directory: "/"
    registries:
      - private
```

### Updated dependency

undici from 6.19.8 to 6.21.1 or later

### What you expected to see, versus what you actually saw

When requesting dependabot to resolve a security alert and create a PR on a context that has a private repo configured with the Github Package Registry, dependabot will try to look for updates on the affected package on the Github Package Regitry despite the package being a public one. It should instead look in the yarn registry like it is written in the yarn.lock file.

### Native package manager behavior

The native package manager looks for updates for the package in the regitry specified in the lockfile

### Images of the diff or a link to the PR, issue, or logs

![Image](https://github.com/user-attachments/assets/1f5acddd-729b-4995-bd9d-218853219a52)

![Image](https://github.com/user-attachments/assets/4111bdaa-10ae-4157-aa48-368eccd40a57)

### Smallest manifest that reproduces the issue

```json
{
	"name": "test",
	"version": "1.0.0",
	"description": "Test app",
	"main": "dist/index.js",
	"license": "UNLICENSED",
	"private": true,
	"dependencies": {
		"discord.js": "^14.16.3",
	},
}
```

**Comment by cig-jaystevenson** [comment]
I hope to be corrected, but I believe you have to setup both the public and private registries in Dependabot for it to resolve both public and private packages. We had to setup our Dependabot this way to use both public and private registries for Nuget otherwise it was looking for public packages in our private registry, but I would imagine it is the same here. If not, then at least we've learnt something!

Using your file as an example:
```yaml
version: 2
registries:
  # setup your private registry
  private:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_TOKEN }}
    replaces-base: true
  # setup the public registry
  public:
    type: npm-registry
    url: https://registry.npmjs.org/
    replaces-base: true
updates:
  - package-ecosystem: npm
    directory: "/"
    # tell dependabot to use both registries when checking for updates
    registries:
      - private
      - public
```

While the [Depdenabot Nuget](https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/maintain-dependencies/removing-dependabot-access-to-public-registries#nuget) documentation has a reference on accessing both public and private registries (the mechanism I describe above), the Node section does not from what I can see so this a bit of a shot in the dark.

**Comment by ImRodry** [comment]
Hey @cig-jaystevenson I tested the exact same configuration you provided and tried to make the security update again and I got the same error, any other ideas?

**Comment by jamonkko** [comment]
@ImRodry did you get this resolved? I am checking similar issue where dependabot seemed to try to fetch public packages from private registry and it seemed to have caused by not having the default public registry listed also in the _.npmrc_

```.npmrc
# if this is missing dependabot seemed to use the @mycustom scoped one for public packages also
registry=https://registry.npmjs.org/
@mycustom:registry=https://npm.pkg.github.com
```

I did not find existing reported issues for this yet (at least quickly) and maybe this should be reported as a separate one. Imho dependabot should respect the "standard" way all package managers work and just use the  https://registry.npmjs.org/ as the base/default registry unless it has been explicitly replaced. But I could understand a counter argument that if all the registries it is allowed to use are already needed to be defined in the _dependabot.yaml_ then maybe the way they are used should be explicitly defined completely in _.npmrc_ as well.
Or just make it easy and use the `public` one from the yaml as base/default automatically even if it is missing from _.npmrc_

**Comment by randhircs** [comment]
@ImRodry You may like to share the config files or share the public repo with minimal setup that your project is having.

**Comment by ImRodry** [comment]
@randhircs I believe the files I shared are enough for a minimal reproducible example. I can no longer test this further as I no longer manage the repo this issue happened on, but I should also add that the mentioned dependency was not a direct dependency listed in the app, and rather a sub-dependency.
As for @jamonkko I didn't have a .npmrc set up in the repository. I believe dependabot should follow the URL listed in the project's lockfile, which I showed above to be the default one. To be clear, this works just fine with regular updates, it only failed with this security update of a sub-dep, so maybe the issue is somewhere there. I'm not sure what other information I can provide unfortunately

**Comment by v-thavaahariharangit** [comment]
@jamonkko and @ImRodry 

```
version: 2
registries:
  private:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_TOKEN }}
    replaces-base: true
```
Including `replaces-base: true` in this config tells Dependabot to treat `https://npm.pkg.github.com` as the base registry URL.

If your intention is to use the public registry as the default when package is not available in private, then this `replaces-base: true` should be removed from your `dependabot.yml` registry config.

<img width="948" height="129" alt="Image" src="https://github.com/user-attachments/assets/52021620-44d0-4169-a836-2de7e6be06f3" />


Ref: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#configuring-private-registries
