### ISSUE TITLE
dependency_file_not_found - No files found in /src

### ISSUE THREAD

**Issue by ChansiJames** [dependabot/dependabot-core#11520]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

.Net 9

### dependabot.yml content

```
version: 2
registries:
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  REDACTED:
    type: nuget-feed
    url: https://nuget.pkg.github.com/REDACTED/index.json
    username: REDACTED
    password: ${{ secrets.REDACTED }}
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    registries: "*"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Zulu"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 100
```

### What you expected to see, versus what you actually saw

When updating from .Net 8 to .Net 9, I expected some existing PRs to be closed, instead an error occurred. I have only made changes to csproj-files, specifically target framework and dependencies. Nothing related to the Dependabot-yaml itself or any directory structure. The solution file is located under `/src`. I can restore the projects just fine locally and in build pipelines.

```
2025/02/07 14:05:52 ERROR <job_...> Error during file fetching; aborting: No files found in /src
```
Followed by
```
+---------------------------+
|          Errors           |
+---------------------------+
| dependency_file_not_found |
+---------------------------+
```
and
```
Failure running container ...
```

It might be wroth mentioning that the `Discovery JSON content` looks pretty empty
```
{
  "Path": "src",
  "IsSuccess": true,
  "Projects": [],
  "GlobalJson": null,
  "DotNetToolsJson": null,
  "Error": null
}
```

**Comment by nicolas63** [comment]
i have the same issue

**Comment by ChansiJames** [comment]
It seems this is not related to the upgrade to .Net 9 I made. I manually ran the update job on another repository I have that doesn't include the .Net 9 updates with a similar result.

On the 1st of febuary the update job went fine, then a few days later on the 7th it failed saying again "dependency_file_not_found" but with the job error "Error during file fetching; aborting: Repo must contain .(cs|vb|fs)proj file.". It seems it found a "DotNetToolsJson"-package to announce updates for.

The /src contains a solution file with a bunch of nested folders with csprojs in them.

**Comment by alexey62soft** [comment]
I also receiving the same error on my Dependabot weekly job now. No upgrades to .NET 9 either.

**Comment by jsmith-kno2** [comment]
Same issue across all my private repos that depend on my GitHub private NuGet package feed. It was working February 3rd and failed with this error February 4th.

**Comment by alexey62soft** [comment]
@sachin-sandhu or @SeanFeldman can you take a look on that, please?

**Comment by fdahlen** [comment]
Experiencing the same issue

**Comment by dannystaple** [comment]
Observation - when I see this ticket, I also see https://github.com/dependabot/dependabot-core/issues/11525.
Both started at the same time, in the same jobs.

**Comment by KieranIrelandPD** [comment]
I'm also experiencing the same issue, no changes were made, but the jobs started failing

**Comment by chrisedebo** [comment]
Also seeing this

**Comment by dylanTesouro** [comment]
Having this issue as well. You can clearly see in the logs it isn't attempting to resolve using a second source. We have 2, the second source being github packages.

`No packages exist with this id in source(s): [nuget.org](http://nuget.org/)`

**Comment by alexey62soft** [comment]
@sachin-sandhu or @SeanFeldman or @brettfo any update on that?

**Comment by brettfo** [comment]
Is there a full log available?  This can happen if a required dependency, direct or transitive, isn't found on a package source, but the package name would help determine that.  This can also happen if MSBuild couldn't evaluate the project file, this is common if a CI or build step requires custom tooling or environment variables.

**Comment by alexey62soft** [comment]
@brettfo It seems to me this one is connected with #11525 , since it not trying to find Bop.Shared.Marc package in jfrog (custom NuGet feed).

Full log is attached.

[failure_log.txt](https://github.com/user-attachments/files/18812540/failure_log.txt)

**Comment by Taelyn** [comment]
same issue here, jobs just keep failing

[job-logs.txt](https://github.com/user-attachments/files/18812589/job-logs.txt)

**Comment by xiaodi17** [comment]
I am experiencing the same issue. No changes made in dependabot.yml

**Comment by jeroensmink98** [comment]
Also getting the same issues with a very basic setup

```yml
version: 2
registries:
  nugets:
    type: nuget-feed
    url: "https://pkgs.dev.azure.com/xxxxxx/xxxxx/_packaging/nugets/nuget/v3/index.json"
    token: "PAT:${{ ADO_PAT }}"
updates:
  # Backend
  - package-ecosystem: "nuget"
    directories: ["/"]
    target-branch: "main"
    open-pull-requests-limit: 5
    debug: true
    labels:
      - "dependencies"
      - "nuget"
    registries:
      - nugets
```

With a `NET8.0` project with a single package from a public registry

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>my_app</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" Version="2.0.0" />
  </ItemGroup>

</Project>
```

partial error log

```bash
updater | 2025/02/18 08:31:07 INFO <job_update_0_nuget_all> Discovery JSON content: {
updater |   "Path": "",
updater |   "IsSuccess": true,
updater |   "Projects": [],
updater |   "GlobalJson": null,
updater |   "DotNetToolsJson": null,
updater |   "Error": null
updater | }
updater | 2025/02/18 08:31:07 INFO <job_update_0_nuget_all> Discovery JSON path for workspace path [/] found in file [/home/dependabot/.dependabot/discovery_map.json] at location [/home/dependabot/.dependabot/discovery.1.json]
updater | 2025/02/18 08:31:07 INFO <job_update_0_nuget_all> Discovery JSON path for workspace path [/] found in file [/home/dependabot/.dependabot/discovery_map.json] at location [/home/dependabot/.dependabot/discovery.1.json]
updater | 2025/02/18 08:31:07 ERROR <job_update_0_nuget_all> Error during file fetching; aborting: No files found in /
##[debug]proxy | 2025/02/18 08:31:07 [007] POST http://host.docker.internal:42947/update_jobs/update_0_nuget_all/record_update_job_error
{"data":{"error-type":"dependency_file_not_found","error-details":{"file-path":null,"message":"No files found in /"}},"type":"record_update_job_error"}
##[debug]proxy | 2025/02/18 08:31:07 [007] 200 http://host.docker.internal:42947/update_jobs/update_0_nuget_all/record_update_job_error
##[debug]proxy | 2025/02/18 08:31:07 [008] PATCH http://host.docker.internal:42947/update_jobs/update_0_nuget_all/mark_as_processed
{"data":{"base-commit-sha":"c76228c75f2ff461a4b771b5c2503c5bf724d368"},"type":"mark_as_processed"}
##[debug]proxy | 2025/02/18 08:31:07 [008] 200 http://host.docker.internal:42947/update_jobs/update_0_nuget_all/mark_as_processed
updater | 2025/02/18 08:31:07 INFO <job_update_0_nuget_all> Finished job processing
updater | 2025/02/18 08:31:07 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------+
updater | |          Errors           |
updater | +---------------------------+
updater | | dependency_file_not_found |
updater | +---------------------------+
updater | 2025/02/18 08:31:07 DEBUG Killing session flusher
updater | 2025/02/18 08:31:07 DEBUG Shutting down background worker
cli | 2025/02/18 08:31:
```

Here is my full pipeline log

[pipeline-log.txt](https://github.com/user-attachments/files/18841650/pipeline-log.txt)
