### ISSUE TITLE
Dependabot conflicts due to indentation because of different whitespace settings

### ISSUE THREAD

**Issue by Sella-GH** [dependabot/dependabot-core#11531]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

GitHub Actions

### dependabot.yml content

```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github/workflows" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "Sella-GH"
    commit-message:
      prefix: "[Actions]"
      include: "scope"
    labels:
      - "area-ci"
      - "area-dependencies"
```

https://github.com/Sella-GH/AzzyBot/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

What happens:
I have my white space settings set to Spaces, 4 Spaces Width and enforce this through an .editorconfig file in the root.
When Dependabot starts updating and filling a PR it rewrites all the white spaces in the file to match Spaces, 2 Spaces Width. This behavior creates conflicts each time when I pull the repo through GitHub Desktop / Visual Studio 2022.

What I expect to happen:
Dependabot respects the existing white space on the files and does not modify it.
Maybe even with a configuration switch to let the user decide which indentation is wanted?

### Images of the diff or a link to the PR, issue, or logs

An example where it just rewrites the whole file:
https://github.com/Sella-GH/AzzyBot/pull/283
