### ISSUE TITLE
No PRs are created when specifying only update-types in groups

### ISSUE THREAD

**Issue by chika3742** [dependabot/dependabot-core#11606]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Pub

### Language version

Dart SDK 3.7.0

### Manifest location and content before the Dependabot update

pubspec.yaml

```YAML
dependencies:
  flutter:
    sdk: flutter

  lints: 4.0.0 # latest: 5.1.1
  animations: 2.0.10 # latest: 2.0.11
  pub_semver: 2.1.4 # latest: 2.1.5
```

### dependabot.yml content

```YAML
version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    groups:
      patch-updates:
        update-types:
          - patch
```

### What you expected to see, versus what you actually saw

Expected to be created 2 PRs:
- lints v4.0.0 -> 5.1.1
- group (animations v2.0.10 -> 2.0.11, pub_semver v2.1.4 -> 2.1.5)

but actually created:
- group (animations v2.0.10 -> 2.0.11, pub_semver v2.1.4 -> 2.1.5)

### Native package manager behavior

All updates are "Resolvable".

```zsh
% flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name              Current  Upgradable  Resolvable  Latest  

direct dependencies:     
animations                *2.0.10  *2.0.10     2.0.11      2.0.11  
lints                     *4.0.0   *4.0.0      5.1.1       5.1.1   
pub_semver                *2.1.4   *2.1.4      2.1.5       2.1.5  
```

### Images of the diff or a link to the PR, issue, or logs

Logs: https://github.com/chika3742/dependabot_test/actions/runs/13355684753/job/37298099035

<img width="839" alt="Image" src="https://github.com/user-attachments/assets/a45664ca-ec6d-43ff-94bd-388f0a4e66c4" />
