### ISSUE TITLE
Update not suggested for quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z

### ISSUE THREAD

**Issue by wjam** [dependabot/dependabot-core#11680]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

docker-compose

### Manifest location and content before the Dependabot update

```yaml
# https://docs.docker.com/compose/compose-file/

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: daily
```

### Updated dependency

According to https://quay.io/repository/minio/minio?tab=tags&tag=latest `RELEASE.2025-02-18T16-25-55Z` is the latest version

### What you expected to see, versus what you actually saw

Dependabot doesn't raise any PR with the only relevant lines in the log being

### Images of the diff or a link to the PR, issue, or logs

>  updater | 2025/02/26 08:36:26 INFO <job_970938993> Checking if minio/minio RELEASE.2025-01-20T14-49-07Z needs updating
> updater | 2025/02/26 08:36:26 INFO <job_970938993> Latest version is RELEASE.2025-01-20T14-49-07Z
> updater | 2025/02/26 08:36:26 INFO <job_970938993> No update needed for minio/minio RELEASE.2025-01-20T14-49-07Z

From https://github.com/wjam/dependabot-docker-compose-bug/actions/runs/13539714313/job/37837902590

### Smallest manifest that reproduces the issue

Minimal example repo is available at https://github.com/wjam/dependabot-docker-compose-bug.
