### ISSUE TITLE
Dependabot Error "error-type": "dependency_not_found" - .NET8, using private nuget repository.

### ISSUE THREAD

**Issue by wd0357097** [dependabot/dependabot-core#11690]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

nuget

### Manifest location and content before the Dependabot update

Our dependabot updates for our .NET8 repositories started to fail a few weeks ago with no changes on our end with  the following error...

-02-27T15:50:15.7259412Z 2025/02/27 15:50:06 INFO Discovering build files in workspace [/home/dependabot/dependabot-updater/repo/source].
2025-02-27T15:50:15.7260955Z 2025/02/27 15:50:06 INFO   No dotnet-tools.json file found.
2025-02-27T15:50:15.7261766Z 2025/02/27 15:50:06 INFO   No global.json file found.
2025-02-27T15:50:15.7262626Z 2025/02/27 15:50:06 INFO   Discovering projects beneath [source].
2025-02-27T15:50:15.7264011Z 2025/02/27 15:50:09 INFO   No packages.config file found.
2025-02-27T15:50:15.7264759Z 2025/02/27 15:50:09 INFO InstallDotnetSdks == true; retaining `global.json` contents.
2025-02-27T15:50:15.7265635Z 2025/02/27 15:50:10 INFO InstallDotnetSdks == true; retaining `global.json` contents.
2025-02-27T15:50:15.7271026Z updater | 2025/02/27 15:50:15 INFO <job_971688467> Discovery JSON content: {
2025-02-27T15:50:15.7273014Z   "Path": "/source",
2025-02-27T15:50:15.7273625Z   "IsSuccess": true,
2025-02-27T15:50:15.7274414Z   "Projects": [],
2025-02-27T15:50:15.7274958Z   "GlobalJson": null,
2025-02-27T15:50:15.7275323Z   "DotNetToolsJson": null,
2025-02-27T15:50:15.7275690Z   "Error": {
2025-02-27T15:50:15.7276035Z     "error-type": "dependency_not_found",
2025-02-27T15:50:15.7276476Z     "error-details": {
2025-02-27T15:50:15.7277166Z       "source": "Jha.Client.Interfaces"
2025-02-27T15:50:15.7277580Z     }
2025-02-27T15:50:15.7277845Z   }
2025-02-27T15:50:15.7278111Z }
2025-02-27T15:50:15.7279371Z updater | 2025/02/27 15:50:15 INFO <job_971688467> Discovery JSON path for workspace path [/source] found in file [/home/dependabot/.dependabot/discovery_map.json] at location [/home/dependabot/.dependabot/discovery.1.json]
2025-02-27T15:50:15.7293792Z updater | 2025/02/27 15:50:15 ERROR <job_971688467> Error during file fetching; aborting: The following dependency could not be found : Jha.Client.Interfaces
2025-02-27T15:50:15.9000437Z   proxy | 2025/02/27 15:50:15 [190] POST /update_jobs/971688467/record_update_job_error
2025-02-27T15:50:16.0659775Z   proxy | 2025/02/27 15:50:16 [190] 204 /update_jobs/971688467/record_update_job_error
2025-02-27T15:50:16.1115134Z   proxy | 2025/02/27 15:50:16 [192] PATCH /update_jobs/971688467/mark_as_processed
2025-02-27T15:50:16.2099162Z   proxy | 2025/02/27 15:50:16 [192] 204 /update_jobs/971688467/mark_as_processed
2025-02-27T15:50:16.2107097Z updater | 2025/02/27 15:50:16 INFO <job_971688467> Finished job processing
2025-02-27T15:50:16.2116262Z updater | 2025/02/27 15:50:16 INFO Results:
2025-02-27T15:50:16.2117292Z Dependabot encountered '1' error(s) during execution, please check the logs for more details.
2025-02-27T15:50:16.2118275Z +----------------------+
2025-02-27T15:50:16.2126635Z |        Errors        |
2025-02-27T15:50:16.2126997Z +----------------------+
2025-02-27T15:50:16.2127348Z | dependency_not_found |

It appears that it cannot find any project files even though all of the project files and .sln file is under the /source folder. 

### What you expected to see, versus what you actually saw

I expect an array of project files to be listed but its an empty array as shown below

2025-02-27T15:50:15.7273014Z   "Path": "/source",
2025-02-27T15:50:15.7273625Z   "IsSuccess": true,
2025-02-27T15:50:15.7274414Z   "Projects": [],
2025-02-27T15:50:15.7274958Z   "GlobalJson": null,
2025-02-27T15:50:15.7275323Z   "DotNetToolsJson": null,
2025-02-27T15:50:15.7275690Z   "Error": {
2025-02-27T15:50:15.7276035Z     "error-type": "dependency_not_found",
2025-02-27T15:50:15.7276476Z     "error-details": {
2025-02-27T15:50:15.7277166Z       "source": "Jha.Client.Interfaces"
2025-02-27T15:50:15.7277580Z     }
2025-02-27T15:50:15.7277845Z   }
2025-02-27T15:50:15.7278111Z }

**Comment by cig-jaystevenson** [comment]
Most likely related to this? https://github.com/dependabot/dependabot-core/issues/11525

**Comment by brettfo** [comment]
Anybody who sees this, can you post a full log, not just the snippet where the error is reported?

Similarly, if anybody reliably encounters this issue on a public repo, please let me know.

I'll be honest, I have no idea why this happens and the few Microsoft-internal logs I can see this happen, I can never make it happen during a local run so I can't even experiment with that.

**Comment by cig-jaystevenson** [comment]
@brettfo Entire raw log attached. `my-org` replaces our actual org name. 

[dependabot.txt](https://github.com/user-attachments/files/19031525/dependabot.txt)

In the interest of sharing as much as possible (without too much hopefully 😅) ...

Our (raw) dependabot config:
```yaml
version: 2

# Private package registries
registries:
  # The private GitHub Packages NuGet registry for My Org.
  nuget-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/my-org/index.json
    username: ${{ vars.GH_PKG_API_USER }}
    password: ${{ secrets.GH_PKG_API_KEY }}
  # When using a private nuget registry we also have to add the public registry!
  nuget-public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:

  # Maintain dependencies for Github Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 50
    schedule:
      interval: "monthly"
    groups:
      # Group all Actions updates together
      all-actions:
        patterns:
        - "*"

  # Maintain dependencies for Nuget
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 100
    registries:
      - nuget-github
      - nuget-public
    schedule:
      interval: "monthly"
    groups:
      # Group all EntityFrameworkCore updates together
      entityframeworkcore:
        patterns:
        - "*EntityFrameworkCore*"
      # Group all test package updates together
      tests:
        patterns:
          - "coverlet*"
          - "NUnit*"
          - "Moq"
          - "Microsoft.NET.Test*"
      # Group all Microsoft updates together
      microsoft:
        patterns:
        - "Microsoft*"
      # Group all Serilog updates together
      serilog:
        patterns:
        - "Serilog*"

  # Docker image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

```

The `csproj` for the main app (there is also a test project in the solution):
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>11</LangVersion>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <ThreadPoolMinThreads>20</ThreadPoolMinThreads>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MyOrg.Shared.Common" Version="8.3.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.10"/>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2"/>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3"/>
    <PackageReference Include="Serilog.Expressions" Version="5.0.0"/>
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0"/>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0"/>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.10"/>
  </ItemGroup>

</Project>
```

And finally the `global.json`:
```json
{
  "sdk": {
    "version": "8.0.0",
    "rollForward": "latestFeature"
  }
}
```

It was [this release](https://github.com/dependabot/dependabot-core/releases/tag/v0.296.0) the issue started occurring I believe, although there's no guarantee it was coincidental and something elsewhere is causing the problems.

Anything else you might need?
