### ISSUE TITLE
Updates for docker-compose ecosystem ignore labels configuration

### ISSUE THREAD

**Issue by vpavic** [dependabot/dependabot-core#11692]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

docker-compose

### dependabot.yml content

```yaml
version: 2
enable-beta-ecosystems: true

updates:
  # omitted other package ecosystems

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    labels: []
```

### Updated dependency

- `apachepulsar/pulsar:3.3.4` -> `apachepulsar/pulsar:4.0.3` 
- `localstack/localstack:4.1.0` -> `localstack/localstack:4.2.0`
- `prom/prometheus:v3.1.0` -> `prom/prometheus:v3.2.1`

### What you expected to see, versus what you actually saw

PRs for docker-compose ecosystem should respect `labels: []` from `dependabot.yml` and not have any labels, while they have `dependencies` and `docker_compose` labels.

Note that this affects 3 PRs that were opened at `2025-02-26T16:58:09Z`, `2025-02-27T16:27:37Z` and `2025-02-27T16:27:39Z`. Earlier PRs, latest one opened at `2025-02-25T16:37:49Z` respected configuration and did not contain any labels.

Also this does not affect recent PRs from other ecosystems (`github-actions`, `gradle`).
