### ISSUE TITLE
Dependabot can't resolve your JavaScript dependency files - @types/node

### ISSUE THREAD

**Issue by benebene84** [dependabot/dependabot-core#11697]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm@9.5.0

### Language version

node v20.15.1

### Manifest location and content before the Dependabot update

```yaml
{
"devDependencies": {
    "@biomejs/biome": "^1.8.3",
    "@storybook/addon-essentials": "^8.4.7",
    "@storybook/addon-interactions": "^8.4.7",
    "@storybook/addon-links": "^8.4.7",
    "@storybook/blocks": "^8.4.7",
    "@storybook/manager-api": "^8.4.7",
    "@storybook/react": "^8.4.7",
    "@storybook/react-vite": "^8.4.7",
    "@storybook/test": "^8.4.7",
    "@storybook/test-runner": "^0.20.1",
    "@storybook/theming": "^8.4.7",
    "@svgr/cli": "^8.1.0",
    "@types/node": "^22.10.1",
    "@types/react": "^19.0.1",
    "@types/react-dom": "^19.0.1",
    "@vitejs/plugin-react-swc": "^3.7.2",
    "@wolf-gmbh/aux-shared-config-js": "1.3.0",
    "chromatic": "^11.20.0",
    "glob": "^11.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "rollup-plugin-copy": "^3.5.0",
    "rollup-plugin-peer-deps-external": "^2.2.4",
    "rollup-preserve-directives": "^1.1.3",
    "sass": "^1.82.0",
    "storybook": "^8.4.7",
    "stylelint": "^16.11.0",
    "stylelint-config-standard-scss": "^14.0.0",
    "stylelint-value-no-unknown-custom-properties": "^6.0.1",
    "typescript": "^5.7.2",
    "vite": "^6.0.3",
    "vite-plugin-dts": "^4.3.0",
    "vite-tsconfig-paths": "^5.1.4"
  },
}
  "peerDependencies": {
    "react": "^18 || ^19",
    "react-dom": "^18 || ^19",
    "react-hook-form": "^7.54.0"
  },
  "dependencies": {
    "@ark-ui/react": "^4.4.4",
    "@radix-ui/react-accordion": "^1.2.1",
    "@radix-ui/react-checkbox": "^1.1.2",
    "@radix-ui/react-dropdown-menu": "^2.1.2",
    "@radix-ui/react-progress": "^1.1.0",
    "@radix-ui/react-radio-group": "^1.2.1",
    "@radix-ui/react-slider": "^1.2.1",
    "@radix-ui/react-switch": "^1.1.1",
    "@radix-ui/react-tabs": "^1.1.1",
    "@radix-ui/react-toast": "^1.2.2",
    "@radix-ui/react-toggle-group": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.4",
    "@tanstack/react-table": "^8.20.5",
    "@tanstack/react-virtual": "^3.11.0",
    "classnames": "^2.5.1"
  }
```

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file



version: 2

registries:
  github-private:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.WOLF_GITBOT_PAT }}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github-private
    schedule:
      interval: "daily"
    groups:
      radix:
        patterns:
          - "@radix-ui/*"
      tanstack:
        patterns:
          - "@tanstack/*"
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
```

### What you expected to see, versus what you actually saw

When trying to update versions via Dependabot, I always get an error regarding the `@types/node` package, see below.

Everything works as expected locally and in the pipeline when doing a pnpm install. Also the pnpm-lock only specifies one `@types/node` package.

However dependabot is still unable to fetch the correct version.

```
Dependabot can't resolve your JavaScript dependency files
Dependabot failed to update your dependencies because there was an error resolving your JavaScript dependency files.

Dependabot encountered the following error:

Error whilst updating sass in /pnpm-lock.yaml:
Progress: resolved 1, reused 0, downloaded 0, added 0
 WARN  GET https://registry.npmjs.org/sass error (undefined). Will retry in 10 seconds. 2 retries left.
undefined
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @types/node@22.10.1

This error happened while installing a direct dependency of /home/dependabot/dependabot-updater/repo

The latest release of @types/node is "17.0.18".

Other releases are:
  * newest8: 8.10.59
  * newest9: 9.6.55
  * ts2.0: 12.12.6
  * ts2.1: 12.12.6
  * ts2.2: 12.12.6
  * ts2.3: 12.12.6
  * ts2.4: 12.12.6
  * ts2.5: 12.12.6
  * ts2.6: 12.12.6
  * ts2.7: 12.12.6
  * ts2.8: 13.13.4
  * ts2.9: 14.0.1
  * ts3.0: 14.6.0
  * ts3.1: 14.10.1
  * ts3.2: 14.14.9
  * ts3.3: 14.14.20
  * ts3.4: 14.14.31
  * ts3.5: 15.6.1
  * ts3.6: 16.6.2
  * ts3.7: 16.11.7
  * ts3.8: 17.0.18
  * ts3.9: 17.0.18
  * ts4.0: 17.0.18
  * ts4.1: 17.0.18
  * ts4.2: 17.0.18
  * ts4.3: 17.0.18
  * ts4.4: 17.0.18
  * ts4.5: 17.0.18
  * ts4.6: 17.0.18
  * ts4.7: 17.0.18

If you need the full list of all 599 published versions run "$ pnpm view @types/node versions".
```

### Native package manager behavior

pnpm works just fine, also lock-file is correct

**Comment by v-thavaahariharangit** [comment]
@benebene84 

Here’s a working example: [dsp-testing/pnpm-private-registry-issue-11697
](https://github.com/dsp-testing/pnpm-private-registry-issue-11697)
The latest version of `@types/node` available in the private registry is `17.0.18`.

```
$ pnpm view @types/node versions
[
  ...
  '17.0.14',  '17.0.15',  '17.0.16',  '17.0.17',  '17.0.18'
]
```
This output was generated using a `.npmrc` file configured to point to the private registry: [`.npmrc` configuration](https://github.com/dsp-testing/pnpm-private-registry-issue-11697/blob/main/.npmrc)

If you require a newer version, please publish the latest release of your package to your private registry.

Dependabot is functioning as expected. With that, I’m closing this ticket.

**Comment by joao-dias-tma** [comment]
Can this be reopened? I have the same issue:
```
Dependabot failed to update your dependencies because there was an error resolving your JavaScript dependency files.

Dependabot encountered the following error:

Error whilst updating @nx/eslint-plugin in /pnpm-lock.yaml:
Scope: all 2 projects
Progress: resolved 1, reused 0, downloaded 0, added 0
undefined
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @types/compression@1.8.1 while fetching it from https://npm.pkg.github.com/

This error happened while installing a direct dependency of /home/dependabot/dependabot-updater/repo

The latest release of @types/compression is "1.7.2".

Other releases are:
  * ts2.0: 0.0.34
  * ts2.1: 0.0.34
  * ts2.2: 1.0.0
  * ts2.8: 1.7.0
  * ts2.9: 1.7.0
  * ts3.0: 1.7.0
  * ts3.1: 1.7.0
  * ts3.2: 1.7.0
  * ts3.3: 1.7.0
  * ts3.4: 1.7.0
  * ts3.5: 1.7.0
  * ts3.6: 1.7.1
  * ts3.7: 1.7.2
  * ts3.8: 1.7.2
  * ts3.9: 1.7.2
  * ts4.0: 1.7.2
  * ts4.1: 1.7.2
  * ts4.2: 1.7.2
  * ts4.3: 1.7.2
  * ts4.4: 1.7.2
  * ts4.5: 1.7.2
  * ts4.6: 1.7.2

If you need the full list of all 6 published versions run "$ pnpm view @types/compression versions".
 WARN  GET https://npm.pkg.github.com/@types%2Fcookie-parser error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://npm.pkg.github.com/@types%2Fexpress error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://npm.pkg.github.com/@types%2Faccept-language-parser error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://npm.pkg.github.com/@types%2Fnode error (undefined). Will retry in 10 seconds. 2 retries left.
```

There's nothing wrong with my lock file and there's nothing wrong with that dependency but somehow Dependabot trips on it, probably because it tries to get it from GitHub instead of npm for some reason?

**Comment by v-thavaahariharangit** [comment]
Here’s a working example setup that’s functioning correctly on my end:

`.npmrc` file
```
@types:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=${{ secrets.WOLF_GITBOT_PAT }}
```

package.json
```
{
    "packageManager": "pnpm@10.14.0",
    "dependencies": {
        "@types/node": "^17.0.0"
    }
}
```

pnpm-lock.yaml
```
lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      '@types/node':
        specifier: 17.0.0
        version: 17.0.0

packages:

  '@types/node@17.0.0':
    resolution: {integrity: sha512-eMhwJXc931Ihh4tkU+Y7GiLzT/y/DBNpNtr4yU9O2w3SYBsr9NaOPhQlLKRmoWtI54uNwuo0IOUFQjVOTZYRvw==}

snapshots:

  '@types/node@17.0.0': {}
```

`github/dependabot.yml` file

```
version: 2

registries:
  github-private:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.WOLF_GITBOT_PAT }}
    replaces-base: true

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github-private
    schedule:
      interval: "daily"
```

A pull request is being generated here: https://github.com/dsp-testing/pnpm-private-registry-issue-11697/pull/1

And it’s correctly updating the lock file.
<img width="1406" height="880" alt="Image" src="https://github.com/user-attachments/assets/5a13edcf-6844-4629-82f0-06d1825b5640" />

Note:Since I don’t have access to your source code, I can’t confirm your `.npmrc` setup. But based on the behavior, I suspect there might be a misconfiguration—especially regarding scoped packages.

For example : `@types/node@17.0.0`

<img width="1092" height="628" alt="Image" src="https://github.com/user-attachments/assets/8a1d765d-fb2e-41b6-9e12-a9bb2bcbe20d" />
