### ISSUE TITLE
Dependabot failed to create a pull request: 422 - Must supply a valid tree.mode

### ISSUE THREAD

**Issue by NGMarmaduke** [dependabot/dependabot-core#11715]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Bundler

### Language version

Ruby 3.4.1

### Manifest location and content before the Dependabot update

`/Gemfile`

```ruby
source "https://rubygems.org"

ruby file: ".ruby-version"

gem "bootsnap", require: false
gem "cssbundling-rails"
gem "google_sign_in"
gem "haml"
gem "jsbundling-rails"
gem "pg"
gem "propshaft"
gem "puma"
gem "rails", "~> 8.0"
gem "sentry-raven"
gem "slack-ruby-block-kit"
gem "slack-ruby-client"
gem "turbo-rails"

group :development, :test do
  gem "dotenv"
  gem "pry-byebug"
  gem "standard"
  gem "standard-rails"
end

group :test do
  gem "capybara"
  gem "factory_bot"
  gem "rspec-rails"
  gem "selenium-webdriver"
  gem "sinatra"
  gem "webmock"
end
```

### dependabot.yml content

```yaml
version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "06:00"
  open-pull-requests-limit: 7
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: direct
  groups:
    rails:
      patterns:
      - "rails"
      update-types:
      - "minor"
    minor-and-patch:
      update-types:
      - "patch"
      - "minor"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "06:00"
  open-pull-requests-limit: 7
  groups:
    minor-and-patch:
      update-types:
      - "patch"
      - "minor"
```

### What you expected to see, versus what you actually saw

I expected a PR to be raised for the 'minor' group however no pull request was created, output from depenabot logs:
```
+------------------------------------------------------------------------------------------------------------------------------------+
|                                                Changes to Dependabot Pull Requests                                                 |
+---------+--------------------------------------------------------------------------------------------------------------------------+
| created | cssbundling-rails ( from 1.4.1 to 1.4.2 ), slack-ruby-block-kit ( from 0.25.0 to 0.26.0 ), turbo-rails ( from 2.0.11 ... |
+---------+--------------------------------------------------------------------------------------------------------------------------+
```

Error message on the dependabot update detail screen:

```
Dependabot failed to create a pull request
Dependabot ran into an issue when attempting to create the pull request

Dependabot encountered the following error:

POST https://api.github.com/repos/korukids/response/git/trees: 422 - Must supply a valid tree.mode // See: https://docs.github.com/rest/git/trees#create-a-tree
[Troubleshoot Dependabot errors](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)
```
