### ISSUE TITLE
Dependabot ignore "ignore list"

### ISSUE THREAD

**Issue by biow0lf** [dependabot/dependabot-core#11721]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Docker-compose

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/alertmanager/"
      - "/blackbox-exporter/"
      - "/cadvisor/"
      - "/commafeed/"
      - "/diun/"
      - "/errbit-mongo/"
      - "/evemonk-caddy-mta-sts/"
      - "/evemonk-caddy-static/"
      - "/evemonk-imageproxy/"
      - "/evemonk-postgresql/"
      - "/evemonk-redis/"
      - "/fluentd/"
      - "/grafana/"
      - "/linkding/"
      - "/node-exporter/"
      - "/ntfy/"
      - "/postgres-exporter/"
      - "/prometheus/"
      - "/redis-exporter/"
      - "/traefik/"
      - "/watchtower/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
```

### What you expected to see, versus what you actually saw

I close PR and dependabot write: `OK, I won't notify you again about this release, but will get in touch when a new version is available.`

I trigger run dependabot and dependabot create new PR for this version.
