### ISSUE TITLE
Ability to name Dependabot update jobs

### ISSUE THREAD

**Issue by bbarry** [dependabot/dependabot-core#11736]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

It would be very useful to be able to differentiate the different dependabot update rules in a repo, Currently in the dependabot tab we see this:

![Image](https://github.com/user-attachments/assets/4ab28691-411d-43d5-b289-1259cc574ef0)

with a dependabot.yml file:

```yaml
version: 2
registries:
  ...
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      internal:
        patterns:
        - "ren*"
    ...
  - package-ecosystem: "nuget"
    target-branch: main
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      everything-else:
        exclude-patterns:
        - "ren*
    ...
```

There seems to be a 1-1 relationship between the `package-ecosystem` entries in the yml and the `Directory.Packages.props` entries in the table but it can be very difficult to identify which entry in the UI corresponds to which entry in the yml.

I would like to be able to provide a value to use in this screenshot instead of `Directory.Packages.props`. 

I'm not sure if this is the right place to report this or if it is already here as a duplicate that I'm unable to find...
