### ISSUE TITLE
`Gemfile` with `dependabot-omnibus` fails to install the `dependabot-uv` dep

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-core#11731]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

any

### Package manager version

any

### Language version

any

### Manifest location and content before the Dependabot update

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "dependabot-omnibus"
```

This is the `Gemfile` for the `dependabot` itself, not the one it is updating.
Here's how this file is installed:

```yml

.dependabot:
  image: ghcr.io/dependabot/dependabot-updater-$PACKAGE_MANAGER
  variables:
    PACKAGE_MANAGER: $CI_JOB_NAME
  retry: 1
  before_script:
    - bundle config set --local path 'vendor'
    - bundle install -j $(nproc)
  script: bundle exec ruby ./update.rb
  only:
    - schedules

pip:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bpip\b/
```

Link: https://github.com/wemake-services/kira-dependencies/blob/master/.gitlab-ci.yml

### What you expected to see, versus what you actually saw

```
Downloading dependabot-omnibus-0.299.1 revealed dependencies not in the API
(dependabot-uv (= 0.299.1)).
Running `bundle update dependabot-omnibus` should fix the problem.
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1
```

Looks like `dependabot-updater-pip` (and maybe others) don't have this dependency for some reason.

### Images of the diff or a link to the PR, issue, or logs

Related to https://github.com/dependabot/dependabot-core/pull/11687
