### ISSUE TITLE
Dependabot lies about which dependencies and versions it has updated

### ISSUE THREAD

**Issue by CorruptComputer** [dependabot/dependabot-core#11756]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

nuget

### Language version

.NET 9

### Manifest location and content before the Dependabot update

https://github.com/CorruptComputer/BlazorWasmOsmOauth/blob/main/BlazorWasmOsmOauth/BlazorWasmOsmOauth.csproj

(with unrelated parts removed)

```
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.11.5" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.11.5" />
```

### dependabot.yml content

https://github.com/CorruptComputer/BlazorWasmOsmOauth/blob/main/.github/dependabot.yml

```
---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

### Updated dependency

Microsoft.FluentUI.AspNetCore.Components
Microsoft.FluentUI.AspNetCore.Components.Icons

### What you expected to see, versus what you actually saw

I expected to see Microsoft.FluentUI.AspNetCore.Components changed from version 4.11.5 to 4.11.0, and 
Microsoft.FluentUI.AspNetCore.Components.Icons changed from version 4.11.5 to 4.11.6, based off what dependabot said in the PR description:

![Image](https://github.com/user-attachments/assets/31bc805f-9ef5-4f5b-9d78-34a26597dadf)

However, when looking at the diff I can see that Microsoft.FluentUI.AspNetCore.Components has not changed at all.

![Image](https://github.com/user-attachments/assets/b899ee48-45e7-4a21-b141-afb2321cc590)

### Native package manager behavior

Updates the package in VS Code just fine, no weird issues like these.

### Images of the diff or a link to the PR, issue, or logs

![Image](https://github.com/user-attachments/assets/3e4129d9-90d1-423e-af13-f75acd35b1a3)

### Smallest manifest that reproduces the issue

```
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
```
