### ISSUE TITLE
NuGet end-to-end updater needs to populate user-local `NuGet.Config` file

### ISSUE THREAD

**Issue by brettfo** [dependabot/dependabot-core#11781]
Also add support for the `replaces-base` parameter.

**Comment by AndrewBabbitt97** [comment]
Would this potentially be why credentials for a private registry don't seem to be working?

**Comment by brettfo** [comment]
No, the end-to-end updater isn't currently in use.

If you're getting auth failures you need to have a `NuGet.Config` file in the root of your repo that lists the custom package feeds and those feeds will have to be repeated in your `dependabot.yml` file with the appropriate token or username/password supplied via secrets.

Otherwise at the very top of the log should be some messages from the proxy indicating that it's pre-authenticating your custom feeds.

**Comment by AndrewBabbitt97** [comment]
In confused, because that was never needed back in December. We used to be able to specify our feeds in dependabot.yml a long with credentials and it would just work, now we just get errors.

Feels like a regression

**Comment by AndrewBabbitt97** [comment]
@brettfo Heres the yaml:

```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 30
    schedule:
      interval: "daily"
    commit-message:
      prefix: build
    registries:
      - nuget
      - github-nuget

registries:
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/recro/index.json
    username: USERNAME
    password: ${{ secrets.NUGET_PAT }}
```

The last time it worked was on Jan 16th with these logs:

[dependabot-01-16-2025.txt](https://github.com/user-attachments/files/19596096/dependabot-01-16-2025.txt)

It stopped working on Jan 17th with `private_source_authentication_failure` in these logs:

[dependabot-01-17-2025.txt](https://github.com/user-attachments/files/19596102/dependabot-01-17-2025.txt)

And for reference, here's a current log with the same configuration ran today:

[dependabot-04-03-2025.txt](https://github.com/user-attachments/files/19596110/dependabot-04-03-2025.txt)
