### ISSUE TITLE
Request for support to ignore minor/patch updates while allowing major upgrades for caret (^) version ranges.

### ISSUE THREAD

**Issue by dmcglynnpax8** [dependabot/dependabot-core#11787]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

I would like to request a feature enhancement for GitHub Dependabot to allow the ability to ignore minor and patch version upgrades for dependencies that use caret (^) version ranges, while still allowing major version upgrades.

## Current behavior:

Dependabot currently does not support ignoring minor and patch version updates for dependencies that are already defined with a caret (^) version in package.json. The only option is to ignore all updates, including major versions, which is not ideal.

## Desired behavior:

I would like the option to:

Automatically ignore minor and patch version updates for dependencies that use caret (^) version ranges.
Allow major version upgrades (e.g., ^1.0.0 → ^2.0.0).
This behavior would allow more control over dependency updates, ensuring that only major versions are considered for updates while maintaining the flexibility of minor and patch versions to be handled automatically at build time via the caret (^).

## Use case:

This feature would be useful in cases where:
We trust that the caret versioning is sufficient for minor and patch updates, as they won't break compatibility.
We only want to be alerted or automatically updated when a new major version of a dependency is released.
Example configuration (desired dependabot.yml format):

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        versions: ["^*"]  # Ignore all minor and patch updates for caret versions
        update-types: [ version-update:semver-patch, version-update:semver-minor ]
    commit-message:
      prefix: "fix"
```
