### ISSUE TITLE
Dependabot no longer runs if the project supports PHP 8.1 or below

### ISSUE THREAD

**Issue by Jean85** [dependabot/dependabot-core#11828]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Composer

### Package manager version

2.8.6 (latest)

### Language version

PHP 8.1 and below

### Manifest location and content before the Dependabot update

The manifest where I discovered the issue: https://github.com/facile-it/doctrine-mysql-come-back/blob/3.x/composer.json

Whenever I support any PHP version that is below 8.2 (which is what Dependabot runs on since #6527) does not work; Dependabot runs with this error:

![Image](https://github.com/user-attachments/assets/510fd477-bf87-4113-ba27-9bc254ec9f2e)

This is **unacceptable for libraries**, since the PHP package ecosystem still supports a wide range of EOLed versions, often because it's not needed to drop support for older versions so soon in libraries.
Data confirming this can be seen here: https://stitcher.io/blog/php-version-stats-january-2025#required-versions
The report shows that, up until last January, if you consider the **top 1000 most popular Composer packages, only 175 (17,5%) require 8.2 or more!**

I'm not asking to support EOLed versions of the language, but this makes it impossible to use Dependabot with a library, since I can't even (automatically) upgrade to newer dependencies, which in turn could block the advancement toward newer language versions!

So, why is Dependabot refusing to run on older PHP versions? Couldn't we run on newer version, and [rely on the `platform.php` option](https://getcomposer.org/doc/06-config.md#platform) (if needed) to simulate and older PHP version and correctly upgrade dependencies?

### dependabot.yml content
```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: weekly
```

### What you expected to see, versus what you actually saw

Having Dependabot run normally even if my `php` requierement is `^8.1`, or even `^7.4 || ^8.0`

### Smallest manifest that reproduces the issue

```json
{
    "name": "jean85/example",
    "require": {
        "php": "^8.1"
    }
}
```
