### ISSUE TITLE
`failed to find a workspace root` errors when multiple `cargo` workspaces exist in a single git repo

### ISSUE THREAD

**Issue by wmmc88** [dependabot/dependabot-core#11861]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

cargo

### Language version

Rust

### Manifest location and content before the Dependabot update

All `cargo.toml` and `cargo.lock` files in the repo (via `directories: ["**/*"]`)

### dependabot.yml content

https://github.com/microsoft/windows-drivers-rs/blob/93cf3c46559072d1bcf5b72cca63619d1b2060ae/.github/dependabot.yaml

```
version: 2
updates:
  - package-ecosystem: "cargo"
    directories: ["**/*"]
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "America/Los_Angeles"
      time: "06:00"
    commit-message:
      prefix: "chore"
    reviewers:
      - "microsoft/windows-drivers-rs"
    labels:
      - "type:dependabot"
      - "type:dependencies-cargo"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "America/Los_Angeles"
      time: "06:00"
    commit-message:
      prefix: "chore"
    reviewers:
      - "microsoft/windows-drivers-rs"
    labels:
      - "type:dependabot"
      - "type:dependencies-github-actions"
```

### What you expected to see, versus what you actually saw

I expect dependabot to execute successfully, but instead I get error logs with a lot of `dependency_file_not_resolvable`, `unknown error`, and `Dependabot can't resolve your Rust dependency files`

### Native package manager behavior

native package manager resolves packages sucessfully

### Images of the diff or a link to the PR, issue, or logs

https://github.com/microsoft/windows-drivers-rs/actions/runs/13978257220/job/39137329991

**Comment by JuroOravec** [comment]
I might have hit this error too.

**Repository layout** ([citry-dev/citry](https://github.com/citry-dev/citry/tree/a1bbcac0fb38a848e5dc5300f3a0c4b125b72d75))

```
citry/
├── Cargo.toml                    workspace A (the repository's own)
│                                   members     = crates/* (5, listed below)
│                                   [workspace.dependencies] holds 17
│                                   path deps pointing into workspace B
├── crates/
│   ├── citry_core_py/            ─┐
│   ├── citry_html_transform/      │ the 5 members of workspace A
│   ├── citry_template_formatter/  │ several depend on ruff_* crates
│   ├── citry_template_parser/     │ through [workspace.dependencies]
│   └── python_safe_eval/         ─┘
└── third_party/
    └── rust/
        └── ruff/                 GIT SUBMODULE, and workspace B
            │                       members = crates/*
            ├── Cargo.toml          (a second workspace root in the same repo)
            └── crates/
                ├── ruff_python_ast/
                ├── ruff_python_parser/
                └── ...            14 more, all targets of A's path deps
```


- Root `Cargo.toml` is a workspace with 5 members, all under `crates/`.
- `third_party/rust/ruff` is a **git submodule** holding [Ruff repo](https://github.com/astral-sh/ruff), and it
  is itself a workspace (`members = ["crates/*"]`).
- The root `Cargo.toml` has **17 path dependencies pointing into that
  submodule**, for example:

  ```toml
  [workspace.dependencies]
  ruff_python_ast = { path = "third_party/rust/ruff/crates/ruff_python_ast" }
  ```

**dependabot.yml**

```yaml
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "weekly"
```

**Without `exclude-paths`,** every run fails during file fetching:

```
Error during file fetching; aborting:
  /third_party/rust/ruff/crates/citry_core_py/Cargo.toml not found
```

The path is invalid `/third_party/rust/ruff/crates/citry_core_py/Cargo.toml`.

Crate `crates/citry_core_py/Cargo.toml` exists in the repo, but it is a member of the **root** workspace, not of the submodule's. Instead, Dependabot pickup up the `Cargo.toml` workspace defined in `third_party/rust/ruff` (git submodule), and tries to incorrectly resolve `crates/citry_core_py/Cargo.toml` relative to that.

**With `exclude-paths: ["third_party/**"]`,** file fetching gets past that point
and Cargo fails instead ([See failed job](https://github.com/citry-dev/citry/actions/runs/31171105522)):

```
failed to load manifest for workspace member `dependabot_tmp_dir/crates/citry_core_py`
referenced by workspace at `dependabot_tmp_dir/Cargo.toml`

Caused by:
  failed to load manifest for dependency `citry_template_formatter`
Caused by:
  failed to load manifest for dependency `citry_template_parser`
Caused by:
  failed to load manifest for dependency `python_safe_eval`
Caused by:
  failed to load manifest for dependency `ruff_python_ast`
Caused by:
  failed to read `dependabot_tmp_dir/third_party/rust/ruff/crates/ruff_python_ast/Cargo.toml`
Caused by:
  No such file or directory (os error 2)
```

These seem to fail because the submodule is a single gitlink:

```
160000 commit 45bbb4cb...    third_party/rust/ruff
```

so its files are not part of the tree the file fetcher reads. Excluding the
directory is therefore closer to the truth, but Cargo cannot resolve the
workspace without those manifests, so the run fails either way. Including it and
excluding it are both dead ends from where we sit.

**Effect.** The cargo ecosystem produces nothing for this repository: no version
updates and, more importantly, no security updates for any Rust dependency. Our
first-party crates' external dependencies are all declared in the root
`[workspace.dependencies]`, so none of them are reachable.

**What would help,** roughly in order of usefulness to us:

1. Resolving path dependencies that point into a submodule, by fetching the
   submodule's manifests alongside the parent's.
2. Failing that, an option to tell the cargo updater which manifest is the
   workspace root, so a nested workspace is not mistaken for one.
3. Failing that, a documented statement that a cargo workspace with path
   dependencies inside a submodule is unsupported. Knowing it will not work is
   more useful than a weekly red job, and would let us disable the ecosystem
   deliberately rather than leave a broken one running.

Happy to test a fix against this repository if that is useful; the layout above
is public and reproduces on every run.
