### ISSUE TITLE
Ignore major, minor, dependency commands and target-branch

### ISSUE THREAD

**Issue by slawekjaranowski** [dependabot/dependabot-core#11875]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Maven - probably others

### dependabot.yml content

like as:

```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "3.x"
```

### What you expected to see, versus what you actually saw

When we use target-branch we can have a project with multiple branches for multiple project major version.

When we use command like in comments: 

```
@dependabot ignore this major version
```

in PR  created for branch `3.x` - mentioned major version will be ignored in **all** project branches.

**expected**

Information about ignored version should be pinned to branch for which PR was created
