### ISSUE TITLE
Does not use set python index when upgrading the uv.lock

### ISSUE THREAD

**Issue by Lauszus** [dependabot/dependabot-core#11889]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

uv

### dependabot.yml content

```yaml
version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    insecure-external-code-execution: allow
    registries:
      - pypi-example

registries:
  pypi-example:
    type: python-index
    url: https://pypi.example.com
    username: ${{ secrets.EXAMPLE_PYPI_USERNAME }}
    password: ${{ secrets.EXAMPLE_PYPI_PASSWORD }}
    replaces-base: true
```

### What you expected to see, versus what you actually saw

I expected the private Python index to be given as an argument when upgrade the lock.

Instead it was running:

```bash
pyenv exec python -m uv lock --upgrade-package private-package
```

But this will fail if using a private package index. Instead it should do something like:

```bash
pyenv exec python -m uv lock --upgrade-package private-package --index https://"$USERNAME":"$PASSWORD"@pypi.example.com
```

Alternatively provide the username and password by setting the `UV_INDEX_PYPI_EXAMPLE_COM_USERNAME` and `UV_INDEX_PYPI_EXAMPLE_COM_PASSWORD` as environment variables.

**Comment by bogaertg** [comment]
same here

Dependabot retrieve new package version from private registry 

```
2025/04/09 09:02:14 INFO <job_995678105> Checking all dependencies for version updates...
updater | 2025/04/09 09:02:14 INFO <job_995678105> Checking if mongodbatlas-instance 0.1.0 needs updating
updater | 2025/04/09 09:02:14 INFO <job_995678105> Fetching release information from json registry at https://europe-west1-python.pkg.dev/purse-ops/python/pypi/ for mongodbatlas-instance
  proxy | 2025/04/09 09:02:14 [015] GET [https://europe-west1-python.pkg.dev:443/purse-ops/python/pypi/mongodbatlas-instance/json](https://europe-west1-python.pkg.dev/purse-ops/python/pypi/mongodbatlas-instance/json)
  proxy | 2025/04/09 09:02:14 [015] * authenticating python index request (host: europe-west1-python.pkg.dev)
  proxy | 2025/04/09 09:02:15 [015] 404 [https://europe-west1-python.pkg.dev:443/purse-ops/python/pypi/mongodbatlas-instance/json](https://europe-west1-python.pkg.dev/purse-ops/python/pypi/mongodbatlas-instance/json)
updater | 2025/04/09 09:02:15 WARN <job_995678105> No valid versions found via JSON API. Falling back to HTML.
updater | 2025/04/09 09:02:15 INFO <job_995678105> Fetching release information from html registry at https://europe-west1-python.pkg.dev/purse-ops/python/simple/ for mongodbatlas-instance
  proxy | 2025/04/09 09:02:15 [019] GET [https://europe-west1-python.pkg.dev:443/purse-ops/python/simple/mongodbatlas-instance/](https://europe-west1-python.pkg.dev/purse-ops/python/simple/mongodbatlas-instance/)
  proxy | 2025/04/09 09:02:15 [019] * authenticating python index request (host: europe-west1-python.pkg.dev)
  proxy | 2025/04/09 09:02:15 [019] 200 [https://europe-west1-python.pkg.dev:443/purse-ops/python/simple/mongodbatlas-instance/](https://europe-west1-python.pkg.dev/purse-ops/python/simple/mongodbatlas-instance/)
updater | 2025/04/09 09:02:15 INFO <job_995678105> Latest version is 1.0.0
```


but credential from dependabot.yaml was'nt propagated to uv lock upgrade 

```
updater | 2025/04/09 09:02:17 INFO <job_995678105> Process PID: 2308 completed with status: pid 2308 exit 0
updater | 2025/04/09 09:02:17 INFO <job_995678105> Total execution time: 0.04 seconds
2025/04/09 09:02:17 INFO <job_995678105> Using pre-installed uv package
2025/04/09 09:02:17 INFO <job_995678105> Running command: pyenv exec uv lock --upgrade-package mongodbatlas-instance
updater | 2025/04/09 09:02:17 INFO <job_995678105> Started process PID: 2334 with command: {} pyenv exec uv lock --upgrade-package mongodbatlas-instance {}
updater | 2025/04/09 09:02:17 INFO <job_995678105> Process PID: 2334 completed with status: pid 2334 exit 2
updater | 2025/04/09 09:02:17 INFO <job_995678105> Total execution time: 0.19 seconds
  proxy | 2025/04/09 09:02:17 [045] POST /update_jobs/995678105/record_update_job_unknown_error
  proxy | 2025/04/09 09:02:18 [045] 204 /update_jobs/995678105/record_update_job_unknown_error
  proxy | 2025/04/09 09:02:18 [047] POST /update_jobs/995678105/record_update_job_error
  proxy | 2025/04/09 09:02:18 [047] 204 /update_jobs/995678105/record_update_job_error
  proxy | 2025/04/09 09:02:18 [049] POST /update_jobs/995678105/increment_metric
  proxy | 2025/04/09 09:02:18 [049] 204 /update_jobs/995678105/increment_metric
  proxy | 2025/04/09 09:02:18 [051] POST /update_jobs/995678105/record_update_job_unknown_error
  proxy | 2025/04/09 09:02:18 [051] 204 /update_jobs/995678105/record_update_job_unknown_error
updater | 2025/04/09 09:02:18 ERROR <job_995678105> Error processing mongodbatlas-instance (Dependabot::SharedHelpers::HelperSubprocessFailed)
2025/04/09 09:02:18 ERROR <job_995678105> Using CPython 3.9.21 interpreter at: /usr/local/.pyenv/versions/3.9.21/bin/python3.9
error: Failed to fetch: `[https://europe-west1-python.pkg.dev/purse-ops/python/simple/mongodbatlas-instance/`](https://europe-west1-python.pkg.dev/purse-ops/python/simple/mongodbatlas-instance/%60)
  Caused by: Missing password for https://europe-west1-python.pkg.dev/purse-ops/python/simple/mongodbatlas-instance/
```

Here is my dependabot.yaml :

```yaml
version: 2
updates:
  # Mise à jour des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - purse
registries:
  purse:
    type: python-index
    url: https://europe-west1-python.pkg.dev/purse-ops/python/simple
    username: oauth2accesstoken
    password: ${{secrets.GAR_PYTHON_PASSWORD}}
    replaces-base: true
```

My pyproject.toml

```toml
[[tool.uv.index]]
name = "purse"
url = "https://oauth2accesstoken@europe-west1-python.pkg.dev/purse-ops/python/simple"
publish-url = "https://oauth2accesstoken@europe-west1-python.pkg.dev/purse-ops/python"
explicit = true
authenticate = "always"
```

**Comment by michael-booth** [comment]
I'm seeing the same issue as others have described above.
The company I work for currently runs our own instance of Dependabot while we are still on GHES.
We have a variety of artifacts which are published to private registries. Attempting to update these artifacts fails with the same error as provided above when using the `uv` package manager.

I've attempted to contribute a [PR](https://github.com/dependabot/dependabot-core/pull/12226) which i think addresses the issue. Would appreciate a review and any feedback on anything else that's required. 

Thanks again for all the work on Dependabot!

**Comment by Rasmus-S-Kristensen** [comment]
@michael-booth Can you confirm whether this is working for you at the moment?

I am looking into some problems we have with dependabot, which seems to stem from `uv lock` being called with `--index=<our index>` but it fails to authenticate. This in turn causes dependabot to error out. I am suspecting it is due to the credentials (username, password) not being "forwarded" to uv. 

Am still investigating, but was curious to hear if you (or others) had similar problems :)

**Comment by v-thavaahariharangit** [comment]
Scenario Tested in repo: https://github.com/dsp-testing/python-dependabot-private-registry-issue-11889 (intenal)

`pyproject.toml`
```
[project]
name = "dependabot-jfrog-test"
version = "0.1.0"
description = ""
authors = [{name = "Thavaa Hariharan", email = "thavaahariharan@github.com"}]
requires-python = ">=3.8"
dependencies = [
    "requests==2.32.2",
]

[[tool.uv.index]]
name = "jfrog"
url = "https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple"
default = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

`.github/dependabot.yml`
```
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    versioning-strategy: "increase"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    registries:
      - python-artifactory
      
registries:
  python-artifactory:
    type: "python-index"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.PYTHON_TOKEN }}"
    replaces-base: true
```

[PR successfully generated ](https://github.com/dsp-testing/python-dependabot-private-registry-issue-11889/pull/2)and both `pyproject.toml` and `uv.lock` files are updated as expected

<img width="1887" height="958" alt="Image" src="https://github.com/user-attachments/assets/63a92d9f-f2c8-4262-bf49-bfc5c218ed57" />

with this note closing this ticket.
