### ISSUE TITLE
Dependabot PRs are downgrading dependency versions for no discernable reason

### ISSUE THREAD

**Issue by jwodder** [dependabot/dependabot-core#11894]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

pip

### Manifest location and content before the Dependabot update

`/docs/requirements.txt`:

```
Sphinx~=8.0
sphinx-copybutton~=0.5.0
sphinx_rtd_theme~=3.0
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[python]"
    labels:
      - dependencies
      - d:python

  - package-ecosystem: pip
    directory: /docs
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
    commit-message:
      prefix: "[python+docs]"
    labels:
      - dependencies
      - d:python

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[gh-actions]"
      include: scope
    labels:
      - dependencies
      - d:github-actions
```

### Updated dependency

Sphinx: "updated" from 8.0 to 7.4

### What you expected to see, versus what you actually saw

I have multiple Python projects that specify a dependency of `Sphinx~=8.0` in `docs/requirements.txt`.  Today, Dependabot created PRs for all of them that "upgraded" this Sphinx dependency to 7.4, despite the fact that (a) this is a downgrade, (b) Sphinx 8.0 is a perfectly acceptable version, and (c) 7.4 was released almost a year ago.

### Images of the diff or a link to the PR, issue, or logs

- https://github.com/jwodder/javaproperties/pull/51
- https://github.com/jwodder/pyversion-info/pull/24
- https://github.com/jwodder/pypi-simple/pull/38
- https://github.com/jwodder/gitmatch/pull/22
- https://github.com/jwodder/versioningit/pull/108
- https://github.com/jwodder/apachelogs/pull/24
- https://github.com/jwodder/linesep/pull/22
- https://github.com/jwodder/permutation/pull/40
- https://github.com/wheelodex/headerparser/pull/67
