### ISSUE TITLE
Failing with github version in package.json

### ISSUE THREAD

**Issue by daveisfera** [dependabot/dependabot-core#11939]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

yarn 4.7

### Language version

node 22

### Manifest location and content before the Dependabot update

https://github.com/Apple-Actions/download-provisioning-profiles/blob/master/package.json

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
```

### Updated dependency

`github:orj/appstoreconnect#release/v0.3.0`

### What you expected to see, versus what you actually saw

Report that there's no update available and update all other dependencies

### Native package manager behavior

`yarn upgrade-interactive` reports that the latest version is `^0.2.1`

### Images of the diff or a link to the PR, issue, or logs

https://github.com/Apple-Actions/download-provisioning-profiles/actions/runs/14177070966/job/39714438623

### Smallest manifest that reproduces the issue

In `package.json`:
```
"dependencies": {
  "appstoreconnect": "github:orj/appstoreconnect#release/v0.3.0"
}
```
