### ISSUE TITLE
When updating go.mod, changes whitespace

### ISSUE THREAD

**Issue by emmjohnson** [dependabot/dependabot-core#11954]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Go

### Language version

1.24.0

### Manifest location and content before the Dependabot update

/go.mod

before update
```
module foo

go 1.24.0

require (
	cloud.google.com/go/appengine v1.9.3
	cloud.google.com/go/compute v1.34.0
...
)
```

### dependabot.yml content

dependabot.yml
```
version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "07:00" # UTC
    open-pull-requests-limit: 1
    commit-message:
      prefix: "📦 "
```

### Updated dependency

after update
```
module foo

go 1.24.0
require (
	cloud.google.com/go/appengine v1.9.3
	cloud.google.com/go/compute v1.34.0
...
)
```

### What you expected to see, versus what you actually saw

after update
```
module foo

go 1.24.0

require (
	cloud.google.com/go/appengine v1.9.3
	cloud.google.com/go/compute v1.34.0
...
)
```

no whitespace change

### Images of the diff or a link to the PR, issue, or logs

<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/60c55660-146e-4a96-a4fa-40b784d97a2f" />
