### ISSUE TITLE
dependabot does not update pnpm-workspace.yaml's catalog

### ISSUE THREAD

**Issue by azu** [dependabot/dependabot-core#11953]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm 9.15.9 and pnpm 10.7.1

dependabot support pnpm catalog according to release.

- https://github.com/orgs/community/discussions/150782

### Language version

Node.js v22.12.0

### Manifest location and content before the Dependabot update

- [pnpm-workspace.yaml](https://github.com/azu/pnpm-catalog-with-dependabot/blob/1d8d08132e18084a07b827731f3e58ba4baedced/pnpm-workspace.yaml)

```yaml
packages:
  - packages/*
catalog:
  lodash: 4.0.0
```

### dependabot.yml content

- https://github.com/azu/pnpm-catalog-with-dependabot/blob/1d8d08132e18084a07b827731f3e58ba4baedced/.github/dependabot.yml

```yaml
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
```

### Updated dependency

- lodash: 4.0.0 -> 4.17.21

PR: https://github.com/azu/pnpm-catalog-with-dependabot/pull/1

### Expected

dependabot should update pnpm-workspace.yaml and pnpm-lock.yaml.

- Update pnpm-workspace.yaml's catalog to 4.17.0
- Update pnpm-lock.yaml to 4.17.0

### Actual

dependabot only update pnpm-lock.yaml.

- pnpm-workspace.yaml's catalog is not updated
- pnpm-lock.yaml is updated to 4.17.0

It causes another issue:

- https://github.com/pnpm/pnpm/issues/9369

### Images of the diff or a link to the PR, issue, or logs

- pnpm 10 https://github.com/azu/pnpm-catalog-with-dependabot/pull/1
- pnpm 9 https://github.com/azu/pnpm9-catalog-with-dependabot/pull/1

both has same issue. the behavior is same.

### Smallest manifest that reproduces the issue

- https://github.com/azu/pnpm-catalog-with-dependabot

## Context

It seems that the dependabot update pnpm catalogs is not working as expected. The last successful run was on 2025-03-28T17:54:36+09:00 in my private repo, and since then, it has not been able to update the pnpm catalogs.
