### ISSUE TITLE
Dependabot rebase does not work on private repo

### ISSUE THREAD

**Issue by fallemand** [dependabot/dependabot-core#12013]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm 9

### Language version

Node 20.15

### dependabot.yml content
```yml
version: 2

registries:
  npm-codeartifact:
    type: npm-registry
    url: https://getyourguide-130607246975.d.codeartifact.eu-central-1.amazonaws.com/npm/private/
    username: "xxxx"
    password: "xxxx"

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Berlin
    registries:
      - npm-codeartifact
    labels: []
    open-pull-requests-limit: 10
   ``` 

### What you expected to see, versus what you actually saw

- PRs are correctly created 
- If I write `@dependabot rebase` I get the 👍 
- If I go to the update jobs, I see the failure
![Image](https://github.com/user-attachments/assets/d6dbf2e9-15f0-4e48-873e-deb30acfbe88)
- But there is no info inside
![Image](https://github.com/user-attachments/assets/d5cbfe9d-6368-4dfa-a403-00fa16e0aaad)
- When I try to see the logs:
![Image](https://github.com/user-attachments/assets/53d7fc9b-bb7a-4b01-a52f-f3ace66bbce8)

```
Dependabot
The self-hosted runner: gygci-dependabot-kjj97-0 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```
