### ISSUE TITLE
Version mentioned in uv upgrade message doesn't match the actual change in the lockfile

### ISSUE THREAD

**Issue by therefromhere** [dependabot/dependabot-core#12012]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

uv

### Language version

Python 3.13

### Manifest location and content before the Dependabot update

https://github.com/therefromhere/dependabot-uv-upgrade-bug/commit/a108d5bb3a9ac7d121ade75724f8f132d80a6ff2

```
[project]
name = "dependabot-uv-bug-11896"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
```

### dependabot.yml content

```
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

### Updated dependency

https://github.com/therefromhere/dependabot-uv-upgrade-bug/pull/1/files#diff-84321598744d84dbee2318e634c74c9aae39a1c253f1c4bd17ebf9ef2f807b11

### What you expected to see, versus what you actually saw

This PR is titled "Bump django from 5.0 to 5.1.8", but it's actually upgrading to django 5.2 (which was released 6 days ago).

https://github.com/therefromhere/dependabot-uv-upgrade-bug/pull/1

### Images of the diff or a link to the PR, issue, or logs

https://github.com/therefromhere/dependabot-uv-upgrade-bug/pull/1/files
