### ISSUE TITLE
Helm in combination with kustomization yaml

### ISSUE THREAD

**Issue by Aaron-Ritter** [dependabot/dependabot-core#12029]
@robaiken does the following scenario fit as well fall into helm support, or is this more related to k8s and the current docker implementation:

I install helm with kustomization.yaml which includes the chart repo and version:

```
helmCharts:
  - name: fusionauth
    repo: https://fusionauth.github.io/charts
    version: 1.0.12
    releaseName: fusionauth-app
    namespace: c1-sonderformatllc-identity
    valuesFile: values.fusionauth.yaml
    skipHooks: true
  - name: opensearch
    repo: https://opensearch-project.github.io/helm-charts
    version: 2.32.0
    releaseName: fusionauth-search
    namespace: c1-sonderformatllc-identity
    valuesFile: values.opensearch.yaml
```

And the related value files include the image repository and tag:

```
image:
  repository: "opensearchproject/opensearch"
  # override image tag, which is .Chart.AppVersion by default
  tag: "2.19.1"
  pullPolicy: "IfNotPresent"
```

```
image:
  # image.repository -- The name of the docker repository for fusionauth-app
  repository: fusionauth/fusionauth-app
  # image.repository -- The docker tag to pull for fusionauth-app
  tag: 1.56.0
  # image.pullPolicy -- Kubernetes image pullPolicy to use for fusionauth-app
  pullPolicy: IfNotPresent
```
