### ISSUE TITLE
Bump Helm chart version(s) for simple/single wrapper charts

### ISSUE THREAD

**Issue by kuhnroyal** [dependabot/dependabot-core#12046]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

It would be great if a dependabot could bump the `version` and `appVersion` in the `Chart.yaml` for cases where there is a single dependency and the fields match the current values.

```yaml
apiVersion: v2
name: minio-wrapper
description: My Bitnami MinIO wrapper
type: application
version: 15.0.0
appVersion: 2025.1.20
dependencies:
  - name: minio
    version: 15.0.0
    repository: https://charts.bitnami.com/bitnami
```

Currently the minio version gets bumped to 16.0.7 but it would be great to get a little bit more out of it. 

```yaml
apiVersion: v2
name: minio-wrapper
description: My Bitnami MinIO wrapper
type: application
version: 16.0.7
appVersion: 2025.4.8
dependencies:
  - name: minio
    version: 16.0.7
    repository: https://charts.bitnami.com/bitnami
```

This update should only be performed if the current values match.
