### ISSUE TITLE
Go mod tidy wasn't performed OR go version wasn't updated

### ISSUE THREAD

**Issue by theyoprst** [dependabot/dependabot-core#12078]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

gomod

### Language version

Go 1.24.1

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: "dev"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: "dev"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    target-branch: "dev"

  - package-ecosystem: gomod
    directory: /images/worker/gpubench
    schedule:
      interval: daily
    target-branch: "dev"
```

### What you expected to see, versus what you actually saw

Dependabot didn't execute `go mod tidy` for some reason, as a result golangci-lint is failing:

https://github.com/nebius/soperator/pull/718/commits/19df4dc0c5a8dda1219425b7c2f21d0cb395840f

As far as I understand, dependabot did run go mod tidy at least in 2020: https://github.blog/changelog/2020-10-19-dependabot-go-mod-tidy-and-vendor-support/

### Native package manager behavior

If I run `go mod tidy` manually, I've got:

```
 ➜ go mod tidy
go: github.com/mariadb-operator/mariadb-operator@v0.38.1 requires go >= 1.24.2; switching to go1.24.2
```
