### ISSUE TITLE
Dependabot Version Updates for GItHub Actions downgrades my action instead of upgrading it

### ISSUE THREAD

**Issue by mickeygousset** [dependabot/dependabot-core#12076]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

[GitHub Actions Workflow File](https://github.com/devopselvis/dependabot-version-updates-example/blob/main/.github/workflows/simple.yml)

Here are the contents of the workflow:

```
name: My Simple Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout using tag v2
-       
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        name: checkout using sha for v3

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        name: checkout using sha for v3.5.0
```

### dependabot.yml content

[Dependabot.yml file](https://github.com/devopselvis/dependabot-version-updates-example/blob/main/.github/dependabot.yml)

Contents of file:

```
version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```

### Updated dependency

I created a [workflow ](https://github.com/devopselvis/dependabot-version-updates-example/blob/main/.github/workflows/simple.yml)with three steps:

- `actions/checkout@v2`
- `actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744` - which is the SHA for v3
- `actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3` - which is the SHA for v3.5.0

### What you expected to see, versus what you actually saw

I expected to see:

- updated `actions/checkout@v2` to `actions/checkout@v4` 
- updated `actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744` to `actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683` 
- updated `actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3` to `actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683` 

Instead, I saw:

- updated `actions/checkout@v2` to `actions/checkout@v4` - that is correct
- updated `actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744` to `actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5` - this is wrong, as this SHA goes to v2. So it downgraded.
- updated `actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3` to `actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5` - This is wrong, as this SHA goes to v2. So it downgraded.

Then I tried a couple of other things:

- I created a [second repo](https://github.com/devopselvis/dependabot-version-updates-example2) where I only had one actions step in it, tied to a commit SHA, and it upgraded it correctly
- I created a [third repo](https://github.com/devopselvis/dependabot-version-updates-example3) where I had two action steps, the first tied to a commit SHA and the second tied to a tag. It upgraded correctly.
- I created a new repo this morning and [reproduced the behavior](https://github.com/devopselvis/dependabot-version-updates-example4/pull/1/files) from the first repo

So the problem I am having is reproducible

### Images of the diff or a link to the PR, issue, or logs

- [PR for the update that includes the downgrades - aka the bad update](https://github.com/devopselvis/dependabot-version-updates-example/pulls)
- [PR for my second repo where only having one action in the workflow worked.](https://github.com/devopselvis/dependabot-version-updates-example2/pull/1)
- [PR for the third repo where only having two actions in the workflows worked](https://github.com/devopselvis/dependabot-version-updates-example3)
- [PR for reproducing what happened in the first repo in an entirely new repo](https://github.com/devopselvis/dependabot-version-updates-example4)

And just for grins, the [YouTube video I was creating when this happened](https://www.youtube.com/watch?v=hY95AAKOVTw).

### Smallest manifest that reproduces the issue

```
name: My Simple Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        name: Checkout using tag v2

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        name: checkout using sha for v3

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        name: checkout using sha for v3.5.0
```
