### ISSUE TITLE
Helm - "dependency_file_not_found" issue

### ISSUE THREAD

**Issue by neilime** [dependabot/dependabot-core#12081]
Hi,
 
In my projects, some charts are located in a subfolder:
 
`charts/app-1/Chart.yaml`, `charts/app-2/Chart.yaml`

I can't make dependabot works with helm in this context, I always had this error: dependency_file_not_found`

I've tried with:

- ```
  directory: "/"
  ```
- ```
    directories: 
      - /charts/*
  ```
- ```
    directories: 
      - /charts/*/*
  ```
- ```
    directories: 
      - /charts/*/*.yaml
   ```

Example:

```
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+------------------------------------------------------------------------+
|                                 Errors                                 |
+---------------------------+--------------------------------------------+
| Type                      | Details                                    |
+---------------------------+--------------------------------------------+
| dependency_file_not_found | {                                          |
|                           |   "message": "/charts/*/*.yaml not found", |
|                           |   "file-path": "/charts/*/*.yaml"          |
|                           | }                                          |
+---------------------------+--------------------------------------------+
```

**Comment by joscha-alisch** [comment]
@neilime I have the same issue and needed to add `enable-beta-ecosystems: true` to make it work. This is contrary to what was described in https://github.com/dependabot/dependabot-core/issues/2237#issuecomment-2794085631 - so I've opened a new issue for this: https://github.com/dependabot/dependabot-core/issues/12121

**Comment by joscha-alisch** [comment]
That issue has been resolved now @neilime - you might want to try again now and see if that also resolves this issue :)

**Comment by robaiken** [comment]
I'm really sorry about the confusion with the feature flag not being removed correctly. It should have been fully removed when Helm support reached general availability, and I apologize for any frustration this has caused you both.

As @joscha-alisch mentioned, the issue requiring `enable-beta-ecosystems: true` (issue #12121) has now been fixed, so you shouldn't need that flag anymore.

**Comment by sbp-bvanb** [comment]
I want to group all helm updates, but dependabot does not support glob:

```
The property '#/updates/4/directory' must not include a glob pattern
```

Can this be resolved for helm as I want to group them to prevent the occurrence of a lot of PRs.

**Comment by yeikel** [comment]
> I want to group all helm updates, but dependabot does not support glob:
> 
> ```
> The property '#/updates/4/directory' must not include a glob pattern
> ```
> 
> Can this be resolved for helm as I want to group them to prevent the occurrence of a lot of PRs.

Can you share your `dependabot.yml` file?

**Comment by sbp-bvanb** [comment]
> > I want to group all helm updates, but dependabot does not support glob:
> > ```
> > The property '#/updates/4/directory' must not include a glob pattern
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can this be resolved for helm as I want to group them to prevent the occurrence of a lot of PRs.
> 
> Can you share your `dependabot.yml` file?

Attempt 1:

```
---
version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      helm-all:
        patterns:
          - "*"
```

Attempt 2:

```
---
version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/"
    directory: "/*/*/*/Chart.yaml"
    schedule:
      interval: "weekly"
    groups:
      helm-all:
        patterns:
          - "*"
```
