### ISSUE TITLE
pnpm fails to fetch npm package from private Github Packages repository when Dependabot attempts update

### ISSUE THREAD

**Issue by gthb** [dependabot/dependabot-core#12111]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm 9.15.5

### Language version

Node.js >=20

### Manifest location and content before the Dependabot update

```
./package.json
./pnpm-lock.yaml
```

### dependabot.yml content

```
version: 2
registries:
  github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - client-developers
  - package-ecosystem: github-actions
    directory: /
    registries:
      - github-packages
    schedule:
      interval: monthly
    reviewers:
      - client-developers
```

### Updated dependency

Noticed in each Dependabot alert in the repository https://github.com/GRID-is/GRID-headless, of which there are 5 so far, the latest being “canvg Prototype Pollution vulnerability” (referencing CVE-2025-25977)

### What you expected to see, versus what you actually saw

Expected to see Dependabot create a PR to apply a dependency update.

Instead, Dependabot tries to create an update and fails with “Dependabot can't authenticate to a private package registry”.

Salient excerpt from the log:
```
updater | 2025/04/22 11:39:56 INFO <job_1002735955> Process PID: 1455 completed with status: pid 1455 exit 1
2025/04/22 11:39:56 INFO <job_1002735955> Total execution time: 3.06 seconds
2025/04/22 11:39:56 WARN <job_1002735955> Error while accessing npm.pkg.github.com. Response (truncated) - Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 21, reused 0, downloaded 0, added 0
undefined
 ERR_PNPM_FETCH_401  GET https://npm.pkg.github.com/@grid-is%2Fmondrian: Unauthorized - 401

This error happened while installing a direct dependency of /home/dependabot/dependabot-updater/repo

No authorization header was set for the request.

These authorization settings were found:
@grid-is:registry=https://npm.pkg.github.com.../
  proxy | 2025/04/22 11:39:56 [103] POST /update_jobs/1002735955/record_update_job_error
  proxy | 2025/04/22 11:39:56 [103] 204 /update_jobs/1002735955/record_update_job_error
updater | 2025/04/22 11:39:56 INFO <job_1002735955> Handled error whilst updating canvg: private_source_authentication_failure {:source=>"npm.pkg.github.com"}
```

The repository secret referenced in `dependabot.yml` does exist and is not expired (we tried refreshing it too).

The `.npmrc` file contains:
```
engine-strict=true
@grid-is:registry=https://npm.pkg.github.com
```

Fetching these packages is working fine in Dependabot in another repository which uses npm, not pnpm.

### Native package manager behavior

```
$ pnpm i canvg@latest
 WARN  10 deprecated subdependencies found: are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, inflight@1.0.6, npmlog@5.0.1, resolve-url@0.2.1, rimraf@3.0.2, source-map-resolve@0.5.3, source-map-url@0.4.1, urix@0.1.0
Already up to date
Progress: resolved 937, reused 881, downloaded 0, added 0, done
Done in 904ms
```

after which we get:
```
$ git diff
diff --git a/package.json b/package.json
index 72e5056..8c226f3 100644
--- a/package.json
+++ b/package.json
@@ -41,7 +41,7 @@
     "@smithy/types": "^4.1.0",
     "@xmldom/xmldom": "~0.9.7",
     "accept-language": "~3.0.20",
-    "canvg": "~4.0.2",
+    "canvg": "~4.0.3",
     "hot-shots": "^10.2.1",
     "http-errors": "~2.0.0",
     "ioredis": "^5.5.0",
```
and corresponding changes in `pnpm-lock.yaml`.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/GRID-is/GRID-headless/security/dependabot/5

https://github.com/GRID-is/GRID-headless/network/updates/1002735955

https://github.com/GRID-is/GRID-headless/actions/runs/14593855434/job/40934994166
