### ISSUE TITLE
Helm "Registry type is not included in the list"

### ISSUE THREAD

**Issue by j-chao** [dependabot/dependabot-core#12115]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Helm

### dependabot.yml content

```
version: 2
registries:
  helm_registry:
    type: helm-registry
    url: https://raw.githubusercontent.com/some_private_repo/main
    username: my_username
    password: ${{ secrets.my_org_secret }}

updates:
  - package-ecosystem: "docker"
    directory: "/foobar"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/foobaz"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/boobaz"
    schedule:
      interval: "weekly"

  - package-ecosystem: "helm"
    directory: "/foobar"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/foobaz"
    registries: "*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/boobaz"
    registries: "*"
    schedule:
      interval: "weekly"
```

### What you expected to see, versus what you actually saw

Expecting to see Dependabot successfully:
1. recognizing the helm package-ecosystem.
2. authenticating to the private Helm registry .
3. checking if any updates for Helm chart dependencies need to be made.

Instead, we are seeing the following error thrown:

<img width="931" alt="Image" src="https://github.com/user-attachments/assets/4e824a3a-0c33-4f77-ba51-b4c5c6ec17b8" />

**Comment by abdulapopoola** [comment]
tagging @robaiken ;

**Comment by j-chao** [comment]
Thanks for the reply @robaiken ,
I have changed my dependabot.yml file to the following, but I am still getting the same error.

- I have referenced https://github.com/dependabot/dependabot-core/issues/12121 for setting `enable-beta-ecosystems` to true.
- Also, the [documentation here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#configuring-private-registries) may need to be updated if `registries: "*"` is no longer supported.

```
version: 2
enable-beta-ecosystems: true
registries:
  helm_registry:
    type: helm-registry
    url: https://raw.githubusercontent.com/some_private_repo/main
    username: my_username
    password: ${{ secrets.my_org_secret }}

updates:
  - package-ecosystem: "docker"
    directory: "/foobar"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/foobaz"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/boobaz"
    schedule:
      interval: "weekly"

  - package-ecosystem: "helm"
    directory: "/foobar"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/foobaz"
    registries: 
      - helm_registry
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/boobaz"
    registries: 
      - helm_registry
    schedule:
      interval: "weekly"
```
