### ISSUE TITLE
Dependabot does not update `Django` to version `5.2` with `uv`

### ISSUE THREAD

**Issue by gegoune** [dependabot/dependabot-core#12140]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

uv

### Package manager version

uv 0.6.16

### Language version

Python 3.13.3

### Manifest location and content before the Dependabot update

```toml
[project]
name = 'myproject'
version = "0.0.1"
requires-python = '>=3.13'
dependencies = [
  'django==5.1.8',
]
```

### dependabot.yml content

```yaml
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: 'uv'
    directory: '/'
    schedule:
      interval: 'daily'
```

### Updated dependency

`Django` from `5.1.8` to `5.2`

### What you expected to see, versus what you actually saw

Dependabot should update `Django` to version `5.2`, instead logs show:

```
updater | 2025/04/25 06:14:47 INFO <job_x> Checking if django 5.1.8 needs updating
updater | 2025/04/25 06:14:47 INFO <job_x> Fetching release information from json registry at https://pypi.org/pypi/ for django
  proxy | 2025/04/25 06:14:48 [101] GET https://pypi.org:443/pypi/django/json
  proxy | 2025/04/25 06:14:48 [101] 200 https://pypi.org:443/pypi/django/json
updater | 2025/04/25 06:14:48 INFO <job_x> Filtered out 2 yanked versions
updater | 2025/04/25 06:14:48 INFO <job_x> Filtered out 16 pre-release versions
updater | 2025/04/25 06:14:48 INFO <job_x> Latest version is 5.1.8
updater | 2025/04/25 06:14:48 INFO <job_x> No update needed for django 5.1.8
```

### Native package manager behavior

```sh
$ uv add django==5.2
Resolved XY packages in 766ms
Prepared 1 package in 962ms
Uninstalled 1 package in 389ms
Installed 1 package in 65ms
 - django==5.1.8
 + django==5.2
```

### Images of the diff or a link to the PR, issue, or logs

This has been briefly discussed in https://github.com/dependabot/dependabot-core/issues/10478#issuecomment-2794716978, https://github.com/dependabot/dependabot-core/issues/10478#issuecomment-2794754819.
