### ISSUE TITLE
Dependabot fails with nuget using multiple Directory.Packages.props files

### ISSUE THREAD

**Issue by Tsingis** [dependabot/dependabot-core#12149]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

nuget

### Manifest location and content before the Dependabot update

/App/Directory.Packages.props 

https://github.com/Tsingis/bitcoin-web-api/blob/master/App/Directory.Packages.props

```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="APIWeaver.OpenApi" Version="2.7.0" />
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
    <PackageVersion Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.4" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.2.0" />
    <PackageVersion Include="Serilog" Version="4.2.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.8.0.113526"/>
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="8.1.1" />
  </ItemGroup>
</Project>
```

/Tests/Directory.Packages.props

https://github.com/Tsingis/bitcoin-web-api/blob/master/Tests/Directory.Packages.props

```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.13.1" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.8.0.113526"/>
    <PackageVersion Include="xunit.v3" Version="2.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>
</Project>
```

### dependabot.yml content

```yml
 version: 2
 updates:
   - package-ecosystem: "nuget"
      directories:
        - "/App"
        - "/Tests"
      schedule:
        interval: "weekly"
        day: "wednesday"
        time: "21:00"
        timezone: "Europe/Helsinki"
      target-branch: "master"
      groups:
        asp:
          patterns:
            - "Asp.Versioning.*"
        microsoft:
          patterns:
            - "Microsoft.AspNetCore.*"
            - "Microsoft.Extensions.*"
        serilog:
          patterns:
            - "Serilog*"
```

https://github.com/Tsingis/bitcoin-web-api/blob/master/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Simple `directory: "/"` seems to ignore possible updates in `/Tests`

With

```yml
directories:
  - "/App"
  - "/Tests"
```

dependabot has error 

```
dependency_file_not_found {
	"message": "Repo must contain .(cs|vb|fs)proj file.",
	"file-path": null
}  
```

Even though those directories `/App` and `/Tests` do not directly have any files with the above mentioned extensions still they hold subdirectories with for example `.csproj` files.

Expecting to get updates to all `Directory.Packages.props` files (or `csproj` files) in each specified directory.

### Native package manager behavior

`dotnet list package --outdated` is able to find updates in projects within both directories `/App` and `/Tests`

```bash
The following sources were used:
   https://api.nuget.org/v3/index.json

Project `Api` has the following updates to its packages
   [net9.0]:
   Top-level Package        Requested   Resolved   Latest
   > Scalar.AspNetCore      2.2.0       2.2.0      2.2.1

The given project `Services` has no updates given the current sources.
Project `UnitTests` has the following updates to its packages
   [net9.0]:
   Top-level Package                                Requested   Resolved   Latest
   > Microsoft.Testing.Extensions.CodeCoverage      17.13.1     17.13.1    17.14.2

Project `IntegrationTests` has the following updates to its packages
   [net9.0]:
   Top-level Package                                Requested   Resolved   Latest
   > Microsoft.Testing.Extensions.CodeCoverage      17.13.1     17.13.1    17.14.2
```

https://github.com/Tsingis/bitcoin-web-api
