### ISSUE TITLE
Helm in combination with helmfile yaml

### ISSUE THREAD

**Issue by Llyth** [dependabot/dependabot-core#12141]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

I'll preface that this is simply recreating an issue similar to: https://github.com/dependabot/dependabot-core/issues/2126

With the GA of: https://github.com/dependabot/dependabot-core/issues/2237
and continuity of a similar issue for Kustomization: https://github.com/dependabot/dependabot-core/issues/12029

[helmfile](https://github.com/helmfile/helmfile) is a widely used and popular tool to "declaratively deploy your Kubernetes manifests, Kustomize configs, and Charts as Helm releases. Generate all-in-one manifests for use with ArgoCD." If I may quote its github repo desc.

In a helmfile.yaml file you could find:
```YAML
# https://helmfile.readthedocs.io/en/latest/#getting-started
repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false
```

Or with private helm charts and version locking:

```YAML
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: private-charts
    url: https://private-charts.organization.io
    username: user
    password: password

releases:
  - name: oauth2-proxy
    namespace: oauth2-proxy
    chart: bitnami/oauth2-proxy
    version: 1.2.3
    values:
      - templates/values.oauth2-proxy.yaml.gotmpl

  - name: project
    namespace: project
    chart: private-charts/chart
    version: 3.2.1
    values:
      - templates/values.project.yaml.gotmpl
```

Helmfile itself offers a .lock file in case you don't lock yourself to a specific version with `helmfile deps` it would then generate a `helmfile.lock`:
```YAML
version: 0.171.0
dependencies:
- name: chart
  repository: https://private-charts.organization.io
  version: 3.2.1
- name: oauth2-proxy
  repository: https://charts.bitnami.com/bitnami
  version: 1.2.3
digest: sha256:6ac45173d0595bd938347af1945cdc91bb189db0626ecb24a284bc2290e5316b
generated: "2025-04-25T13:55:17.722067634+02:00"
```

cc:
@robaiken as he was similarly tagged for Kustomization
@abatilo original poster of the helmfile issue
@mumoshu one of the main contributors of helmfile
