### ISSUE TITLE
Dependabot not creating PRs

### ISSUE THREAD

**Issue by gavintoddchurch** [dependabot/dependabot-core#12198]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

v10.9.2

### Language version

v22.14.0

### dependabot.yml content

```yaml
version: 2
registries:
  npm-artifactory:
    type: npm-registry
    url: https://<redacted>
    token: ${{secrets.<redacted>
    replaces-base: true

updates:
  - package-ecosystem: "npm"
    directories:
      - "/github-backup"
      - "/github-backup/github-repo-backup"
      - "/github-backup/github-repo-extractor"
    registries:
      - npm-artifactory
    schedule:
      interval: "weekly"
    groups:
      non-breaking-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
```

### Updated dependency

@churchofjesuschrist/festack-scripts:
current: 22.5.1
to: 23.0.0

react & react-dom
current: 18.x
to: 19.x

### What you expected to see, versus what you actually saw

Expected: Individual PR to update to new major version
Actual: no pr is created

### Native package manager behavior

using npx npm-check -u

<img width="477" alt="Image" src="https://github.com/user-attachments/assets/64ec5862-b33c-4ae7-9756-46284c1b70d9" />

### Smallest manifest that reproduces the issue

```json
{
  "name": "dependabot-repro",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }
}
```
