### ISSUE TITLE
uv: Looks for updates of `package[extra]`  instead of `package`

### ISSUE THREAD

**Issue by edgarrmondragon** [dependabot/dependabot-core#12196]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

uv

### Package manager version

uv 0.7.2

### Language version

Python 3.13

### Manifest location and content before the Dependabot update

```yaml
dependencies = [
    "psycopg2-binary==2.9.10",
    "sqlalchemy==2.0.40",
    "sshtunnel==0.4.0",
    "singer-sdk[faker]~=0.45.7",
]
```

in particular, `singer-sdk[faker]` is the offender here according to the dependabot logs:

```
updater | 2025/05/02 16:54:12 INFO <job_1009490109> Checking if singer-sdk[faker]  needs updating
updater | 2025/05/02 16:54:12 INFO <job_1009490109> Fetching release information from json registry at https://pypi.org/pypi/ for singer-sdk[faker]
updater | 2025/05/02 16:54:12 WARN <job_1009490109> Unexpected error in JSON fetch: bad URI(is not URI?): "https://pypi.org/pypi/singer-sdk[faker]/json". Falling back to HTML.
2025/05/02 16:54:12 INFO <job_1009490109> Fetching release information from html registry at https://pypi.org/simple/ for singer-sdk[faker]
  proxy | 2025/05/02 16:54:13 [043] GET [https://pypi.org:443/simple/singer-sdk/](https://pypi.org/simple/singer-sdk/)
2025/05/02 16:54:13 [043] 200 [https://pypi.org:443/simple/singer-sdk/](https://pypi.org/simple/singer-sdk/)
```

Full logs: https://github.com/MeltanoLabs/tap-postgres/actions/runs/14799613952/job/41555043888

### dependabot.yml content

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

```yaml
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: weekly
      timezone: "America/New_York"
      time: "07:23"
    versioning-strategy: increase-if-necessary
    groups:
      development-dependencies:
        dependency-type: development
      runtime-dependencies:
        dependency-type: production
        update-types:
          - "patch"
```

### What you expected to see, versus what you actually saw

Dependabot trying to update `singer-sdk` instead of `singer-sdk[faker]`.

**Comment by claudiadpp** [comment]
Hi, I have the same problem. Dependabot encounters URI parsing errors when attempting to update Python packages that include extras (e.g., `package[extra]`) and fails to create update pull requests, even when newer versions are available.

### Example Package
```python
# pyproject.toml
dependencies = [
    "pydantic-ai[a2a]>=1.0.0"
]
```
 ### Error logs 
```bash
updater | 2025/10/20 11:31:54 INFO <job_1129278651> Checking if pydantic-ai[a2a]  needs updating
updater | 2025/10/20 11:31:54 INFO <job_1129278651> Fetching release information from json registry at https://pypi.org/pypi/ for pydantic-ai[a2a]
updater | 2025/10/20 11:31:54 WARN <job_1129278651> Unexpected error in JSON fetch: bad URI (is not URI?): "https://pypi.org/pypi/pydantic-ai[a2a]/json". Falling back to HTML.
updater | 2025/10/20 11:31:54 INFO <job_1129278651> Fetching release information from html registry at https://pypi.org/simple/ for pydantic-ai[a2a]
  proxy | 2025/10/20 11:31:54 [015] GET https://pypi.org/simple/pydantic-ai/
  proxy | 2025/10/20 11:31:54 [015] 200 https://pypi.org/simple/pydantic-ai/
updater | 2025/10/20 11:31:55 INFO <job_1129278651> Fetching release information from json registry at [PRIVATE_REGISTRY] for pydantic-ai[a2a]
updater | 2025/10/20 11:31:55 WARN <job_1129278651> Unexpected error in JSON fetch: bad URI (is not URI?): "[PRIVATE_REGISTRY]/pydantic-ai[a2a]/json". Falling back to HTML.
updater | 2025/10/20 11:31:56 INFO <job_1129278651> Latest version is 1.1.0
updater | 2025/10/20 11:31:58 INFO <job_1129278651> Requirements update strategy bump_versions
updater | 2025/10/20 11:31:58 INFO <job_1129278651> No update possible for pydantic-ai[a2a] 
```
While Dependabot successfully falls back to HTML parsing and detects the latest version, it fails to generate update pull requests.

### dependabot.yml 
```yml
version: 2

registries:
  private-registry:
    type: python-index
    url: https://[PRIVATE_REGISTRY]
    username: ${{REGISTRY_USERNAME}}
    password: ${{REGISTRY_PASSWORD}}

updates:
  - package-ecosystem: "uv"
    directory: "/code"
    schedule:
      interval: "weekly"
    registries:
      - private-registry
```
### Environment
- **Package Manager**: uv 0.9.2
- **Ecosystem**: Python  
- **Repository**: Private repository with authentication
