### ISSUE TITLE
Helm in combination with ArgoCD Application yaml

### ISSUE THREAD

**Issue by jimmyjones2** [dependabot/dependabot-core#12202]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

With the GA of: https://github.com/dependabot/dependabot-core/issues/2237
and continuity of a similar issue for Kustomization: https://github.com/dependabot/dependabot-core/issues/12029 and Helmfile: https://github.com/dependabot/dependabot-core/issues/12141

[ArgoCD](https://github.com/argoproj/argo-cd) is a popular tool for pull based CD in Kubernetes.

The feature was requested in https://github.com/dependabot/dependabot-core/issues/2237#issuecomment-2701985976 but have created this ticket to track it. That also noted it's supported in [renovate](https://docs.renovatebot.com/modules/manager/argocd/)

Example ArgoCD Application, deploying a helm chart:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.23.0
    chart: cloudnative-pg
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
```

cc: original comment 👍 
@neilime
@mikejoh
@alexstojda
@JakobStadlhuber
@abkfenris
