### ISSUE TITLE
Dependencies checks not scheduled as configured in interval cron config

### ISSUE THREAD

**Issue by pawelryznar** [dependabot/dependabot-core#12209]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

maven, gradle, docker, github-actions

### Language version

Java 21

### dependabot.yml content

```
version: 2
registries:
  gradle-artifactory:
    type: maven-repository
    url: https://my-domain.io/artifactory/platform-mvn-all
    username: ${{ secrets.username }}
    password: ${{ secrets.token }}
  my-docker:
    type: docker-registry
    url: https://jfrog.io
    username: ${{ secrets.username }}
    password: ${{ secrets.token }}
  my-github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.github_token }}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - gradle-artifactory
    schedule:
      interval: "cron"
      cronjob: "0 5 1 * *"
      timezone: "Europe/Berlin"
    groups: # group dependencies to open just one PR
      gradle-all:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "docker"
    directory: "/deploy/docker"
    registries:
      - my-docker
    schedule:
      interval: "cron"
      cronjob: "0 5 7 * *"
      timezone: "Europe/Berlin"
    groups:
      docker-all:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "github-actions"
    directory: "/"
    registries:
      - my-github
    schedule:
      interval: "cron"
      cronjob: "0 5 15 * *"
      timezone: "Europe/Berlin"
    groups:
      github-all:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
```

### What you expected to see, versus what you actually saw

I was expecting only gradle updates on May 1st, but instead gradle (around 6am, gmt+2) and github actions (11:45pm, gmt+2) were updated.
