### ISSUE TITLE
poetry dependency groups don't play nicely with pep621 projects

### ISSUE THREAD

**Issue by david-gang** [dependabot/dependabot-core#12220]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

poetry

### Package manager version

2.12

### Language version

python >=3.12

### Manifest location and content before the Dependabot update

pyproject.toml
```
[project]
name = "test" 
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi==0.115.5",
    "pydantic==2.8.2"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
    groups:
      fastapi-dependencies:
        patterns:
          - "fastapi"
          - "pydantic*"
   ```

### Updated dependency

fastapi from 0.115.5 to 0.115.12
pydantic from 2.8.2 to 2.11.4

### What you expected to see, versus what you actually saw

Actually i would like to see the pr. Instead of this i get a message
```
updater | 2025/05/07 12:45:27 WARN <job_1011970686> Please check your configuration as there are groups where no dependencies match:
- fastapi-dependencies

This can happen if:
- the group's 'pattern' rules are misspelled
- your configuration's 'allow' rules do not permit any of the dependencies that match the group
- the dependencies that match the group rules have been removed from your project
```

if i switch to the more traditional pyproject.toml file 
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""


[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.115.5"
pydantic = "2.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

the pr is created

<img width="1420" alt="Image" src="https://github.com/user-attachments/assets/4e0a878d-4ed8-4dc8-a2f6-a9604b9b0ad0" />

here are the dependabot log files for before and after
[pep621.zip](https://github.com/user-attachments/files/20084618/pep621.zip)
[traditional.zip](https://github.com/user-attachments/files/20084643/traditional.zip)
