### ISSUE TITLE
Python `~3.12.10` unsupported

### ISSUE THREAD

**Issue by rblaine95** [dependabot/dependabot-core#12237]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Python

### Package manager version

Poetry 2.1

### Language version

Python `3.12`

### Manifest location and content before the Dependabot update

`/pyproject.toml`:

```toml
[project]
name = "acapy-cloud"
version = "5.0.0rc1"
description = "Main project configuration for acapy-cloud"
authors = [
  { name = "Mourits de Beer", email = "mourits.debeer@didx.co.za" },
  { name = "Cloete du Preez", email = "cloete.dupreez@didx.co.za" },
]
readme = "README.md"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "~3.12.10"

fastapi = "~0.115.10"
httpx = "~0.28.0"
loguru = "~0.7.2"
orjson = "~3.10.7"
pydantic = "~2.11.1"
PyYAML = "~6.0.2"
scalar-fastapi = "^1.0.3"
uvicorn = "~0.34.2"
uvloop = "^0.21.0"

[tool.poetry.group.app.dependencies]
aiohttp = "~3.11.7"
aiocache = "~0.12.0"
aries-cloudcontroller = "==1.3.0.post20250507"
base58 = "~2.1.1"
pyjwt = "~2.10.0"
uuid_utils = "^0.10.0"

[tool.poetry.group.endorser.dependencies]
aries-cloudcontroller = "==1.3.0.post20250507"
dependency-injector = "^4.46.0"
nats-py = { extras = ["nkeys"], version = "^2.10.0" }
tenacity = "^9.1.0"

[tool.poetry.group.trust-registry.dependencies]
alembic = "~1.15.0"
psycopg2-binary = "~2.9.6"
sqlalchemy = "~2.0.40"

[tool.poetry.group.waypoint.dependencies]
aiohttp = "~3.11.7"
dependency-injector = "^4.46.0"
nats-py = { extras = ["nkeys"], version = "^2.10.0" }
sse-starlette = "~2.3.3"
tenacity = "^9.1.0"
uuid_utils = "^0.10.0"

[tool.poetry.group.dev.dependencies]
anyio = "~4.9.0"
black = "~25.1.0"
isort = "~6.0.0"
pre-commit = "~4.2.0"
pylint = "~3.3.0"
pytest = "~8.3.2"
pytest-cov = "~6.1.0"
pytest-mock = "~3.14.0"
pytest-xdist = "^3.6.1"

[tool.coverage.run]
omit = ["*/tests/*"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--junitxml=junit.xml -p no:cacheprovider --cov-report=xml --cov-report=term:skip-covered"
junit_family = "xunit2"

[build-system]
requires = ["poetry-core>=2.1"]
build-backend = "poetry.core.masonry.api"
```

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/workflows/actions/deploy-eks
      - /.github/workflows/actions/test-eks
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  # Maintain dependencies for Python
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  # Maintain dependencies for Docker (Python)
  - package-ecosystem: docker
    directories:
      - /dockerfiles/agents
      - /dockerfiles/app
      - /dockerfiles/endorser
      - /dockerfiles/tests
      - /dockerfiles/trustregistry
      - /dockerfiles/waypoint
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
    groups:
      docker-python:
        patterns:
          - "python*"
    ignore:
      - dependency-name: python
        # Ignore Python updates like 3.12 -> 3.13
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  # Maintain dependencies for Docker (Golang)
  - package-ecosystem: docker
    directories:
      - /scripts/k6
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
    groups:
      docker-golang:
        patterns:
          - "golang*"
```

### What you expected to see, versus what you actually saw

Expected behavior:
Dependabot successfully detects outdated packages and opens Pull Requests to update affected packages.

What actually happens:
Dependabot fails and logs the following:
```
2025/05/10 07:51:47 INFO <job_1013502735> Total execution time: 0.0 seconds
updater | 2025/05/10 07:51:47 ERROR <job_1013502735> Error during file fetching; aborting: Dependabot detected the following Python requirement for your project: '~3.12.10'.

Currently, the following Python versions are supported in Dependabot: 3.9.*, 3.10.*, 3.11.*, 3.12.*, 3.13.*.
  proxy | 2025/05/10 07:51:47 [008] POST /update_jobs/1013502735/record_update_job_error
  proxy | 2025/05/10 07:51:47 [008] 204 /update_jobs/1013502735/record_update_job_error
  proxy | 2025/05/10 07:51:47 [010] PATCH /update_jobs/1013502735/mark_as_processed
  proxy | 2025/05/10 07:51:47 [010] 204 /update_jobs/1013502735/mark_as_processed
updater | 2025/05/10 07:51:47 INFO <job_1013502735> Finished job processing
updater | 2025/05/10 07:51:47 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+----------------------------------------------------------------------------------------------+
|                                            Errors                                            |
+----------------------------+-----------------------------------------------------------------+
| Type                       | Details                                                         |
+----------------------------+-----------------------------------------------------------------+
| tool_version_not_supported | {                                                               |
|                            |   "tool-name": "Python",                                        |
|                            |   "detected-version": "~3.12.10",                               |
|                            |   "supported-versions": "3.9.*, 3.10.*, 3.11.*, 3.12.*, 3.13.*" |
|                            | }                                                               |
+----------------------------+-----------------------------------------------------------------+
Failure running container 9527b9651eac4aae1fd75cac4bb99d86f06608027cdc57ee3bd0d58930b22d61
Cleaned up container 9527b9651eac4aae1fd75cac4bb99d86f06608027cdc57ee3bd0d58930b22d61
  proxy | 2025/05/10 07:51:48 0/5 calls cached (0%)
  proxy | 2025/05/10 07:51:48 Posting metrics to remote API endpoint
Error: Dependabot encountered an error performing the update

Error: The updater encountered one or more errors.

For more information see: https://github.com/didx-xyz/acapy-cloud/network/updates/1013502735 (write access to the repository is required to view the log)
🤖 ~ finished: error reported to Dependabot ~
```

**Comment by skokado** [comment]
Same issue in Python 3.12.10,

I use poetry.

`pyproject.toml`

```toml
[project]
requires-python = ">=3.12.10, <3.13"

# ...
```

Execution log:

```
...
updater | 2025/05/15 02:15:20 ERROR <job_1016112602> Error during file fetching; aborting: Dependabot detected the following Python requirement for your project: '>=3.12.10, <3.13'.

Currently, the following Python versions are supported in Dependabot: 3.9.*, 3.10.*, 3.11.*, 3.12.*, 3.13.*.
  proxy | 2025/05/15 02:15:20 [008] POST /update_jobs/1016112602/record_update_job_error
  proxy | 2025/05/15 02:15:20 [008] 204 /update_jobs/1016112602/record_update_job_error
  proxy | 2025/05/15 02:15:21 [010] PATCH /update_jobs/1016112602/mark_as_processed
  proxy | 2025/05/15 02:15:21 [010] 204 /update_jobs/1016112602/mark_as_processed
updater | 2025/05/15 02:15:21 INFO <job_1016112602> Finished job processing
updater | 2025/05/15 02:15:21 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+----------------------------------------------------------------------------------------------+
|                                            Errors                                            |
+----------------------------+-----------------------------------------------------------------+
| Type                       | Details                                                         |
+----------------------------+-----------------------------------------------------------------+
| tool_version_not_supported | {                                                               |
|                            |   "tool-name": "Python",                                        |
|                            |   "detected-version": ">=3.12.10, <3.13",                       |
|                            |   "supported-versions": "3.9.*, 3.10.*, 3.11.*, 3.12.*, 3.13.*" |
|                            | }                                                               |
+----------------------------+-----------------------------------------------------------------+
```
