### ISSUE TITLE
Dependabot unexpectedly recreating lockfiles for routine dependency updates

### ISSUE THREAD

**Issue by joshuagoran** [dependabot/dependabot-core#12245]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

pnpm `10.9.0`

### Language version

Node `22.14.0`

### Manifest location and content before the Dependabot update

`/package.json`

### dependabot.yml content

```yml
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Dependabot dependency management configuration

version: 2
updates:
    - package-ecosystem: npm
      directory: /
      reviewers:
        - [REDACTED]
      schedule:
          interval: weekly
          day: monday
          time: '08:00'
          timezone: America/New_York
      open-pull-requests-limit: 4
      labels:
          - dependencies
          - javascript
      registries: '*' # allows access to all credentials under top-level `registries` key
      groups:
          babel:
              patterns:
                  - '@babel/*'
          d3:
              patterns:
                  - 'd3-*'
          eslint:
              patterns:
                  - 'eslint*'
          mui:
              patterns:
                  - '@mui/*'
                  - '@emotion/*'
              exclude-patterns:
                - '@mui/x-data-grid'
          storybook:
              patterns:
                  - '@storybook/*'
                  - 'storybook'
          tanstack:
              patterns:
                  - '@tanstack/*'
          testing-library:
              patterns:
                  - '@testing-library/*'
          turf:
              patterns:
                  - '@turf/*'

    - package-ecosystem: pip
      directory: /gaia
      schedule:
          interval: weekly
          day: monday
          time: '08:00'
          timezone: America/New_York
      open-pull-requests-limit: 2
      labels:
          - dependencies
          - python
      registries: '*' # allows access to all credentials under top-level `registries` key

registries:
    private-git:
        type: git
        url: [REDACTED_URL]
        username: [REDACTED_USERNAME]
        password: ${{secrets.DEPENDABOT_GITHUB_TOKEN}}
```

### Expected:
Dependabot will update the lockfile entry only for the specific dependency (and subdependencies thereof) being updated in the PR

### Actual:
The entire lockfile is apparently being recreated, thereby updating _all_ dependencies at once with no explanation or warning about havingt done so

### Images of the diff or a link to the PR, issue, or logs

A small excerpt: this Dependabot PR is supposedly making a minor version update to ESLint, but is also updating every other dependency in our repo 👎 

<img width="1244" alt="Image" src="https://github.com/user-attachments/assets/0a2a3511-2833-4ed1-9541-6fadb95a2ee1" />
