### ISSUE TITLE
Enable Dependabot to Update `github-actions` Image Runner Versions

### ISSUE THREAD

**Issue by d33bs** [dependabot/dependabot-core#12250]
Thanks for the great work on this! I tried a quick search but did not see this turn up (please feel free to link and close if this is a duplicate). Would it be possible to update how `github-actions` ecosystem updates are applied to include GitHub Actions runner image version updates? For an example of these versions and their release updates, see the readme here: https://github.com/actions/runner-images .

Here's a quick demonstration:

If we had:

```yaml
name: do something

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
...
```

Dependabot would update this to (as of early 2025):

```yaml
name: do something

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
...
```
