### ISSUE TITLE
Bundler: `gemspec.required_ruby_version = '>= 2.7', '< 4'` does not work

### ISSUE THREAD

**Issue by ekohl** [dependabot/dependabot-core#12254]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

irrelevant

### Language version

irrelevant

### Manifest location and content before the Dependabot update

Write a gemspec with the following content:
```ruby
Gem::Specification.new do |gemspec|
  # ... all other required field ...
  gemspec.required_ruby_version = '>= 2.7', '< 4'
end
```

### dependabot.yml content

```yaml
version: 2
updates:
  # raise PRs for gem updates
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
```

### What you expected to see, versus what you actually saw

What actually happened:
```
updater | /home/dependabot/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:83:in `eval': (eval at 
                        /home/dependabot/bundler/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:83):1: syntax error, unexpected ',', expecting end-of-input (SyntaxError)
```

I expected it to understand the syntax. Normal Bundler does.

### Native package manager behavior

We have it here: https://github.com/voxpupuli/puppet_fixtures/blob/ec2d53fd3021ba243c06bb435a3a13cd95a4ff93/puppet_fixtures.gemspec#L15

And you can see on Rubygems that is recognized: https://rubygems.org/gems/puppet_fixtures/versions/0.1.1

### Images of the diff or a link to the PR, issue, or logs

https://github.com/OpenVoxProject/vanagon/pull/16
