### ISSUE TITLE
No changelog table

### ISSUE THREAD

**Issue by rafal-akiro** [dependabot/dependabot-core#12253]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

bun

### Package manager version

1.2.2

### dependabot.yml content

```
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      deps:
        dependency-type: "production"
        exclude-patterns:
          - "@nivo/*"
          - "*react-router*"
      dev-deps:
        dependency-type: "development"
        exclude-patterns:
          - "*storybook*"
          - "*react-router*"
      storybook:
        patterns:
          - "*storybook*"
      react-router:
        patterns:
          - "*react-router*"
      nivo:
        patterns:
          - "@nivo*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignoring amplify packages due to problems with login after any update. Handle it manually
      - dependency-name: "@aws-amplify/*"
      - dependency-name: "aws-amplify"
```

### What you expected to see, versus what you actually saw

Dependabot hasn't shown the table of updated dependencies for some time. The table should always be present.

# Before

<img width="629" alt="Image" src="https://github.com/user-attachments/assets/2a348c56-b9a4-4372-b79a-49e66db17d80" />

# Now

<img width="749" alt="Image" src="https://github.com/user-attachments/assets/011d4dff-d2a5-47c8-a17a-e9116c0fe41f" />
