### ISSUE TITLE
uv: Dependabot does not do version upgrades in uv.lock if pyproject.toml does not include any version constraints

### ISSUE THREAD

**Issue by sjakthol** [dependabot/dependabot-core#12273]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

uv

### Package manager version

uv 0.7.1

### Language version

python 3.13.2

### Manifest location and content before the Dependabot update

/pyproject.toml:

```toml
[project]
name = "dependabottest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3",
]
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
```

### Updated dependency

boto3 from version 1.38.17 to 1.38.18 (latest at time of writing)

### What you expected to see, versus what you actually saw

With pyproject.toml containing

```toml
dependencies = [
    "boto3",
]
```

dependabot does not create a pull request to update boto3 in uv.lock to newer version that is available (uv.lock has 1.38.17, latest version is 1.38.18 at the time of writing).

If I change pyproject.toml to

```toml
dependencies = [
    "boto3<2.0.0",
]
```

dependabot creates a pull request which updates boto3 in uv.lock to latest available version.

Expectation is that dependabot would create the same pull request to update boto3 in uv.lock even if the dependency is defined without a version constrain in pyproject.toml.

### Native package manager behavior

Package is updated to latest version in uv.lock

### Images of the diff or a link to the PR, issue, or logs

* Sample project used to reproduce the issue: https://github.com/sjakthol/dependabot-uv-test
* Link to dependabot job run when dependencies in pyproject.toml did not have any version constraints (just `boto3`): https://github.com/sjakthol/dependabot-uv-test/actions/runs/15082706127/job/42401409776
  * No updates were made and no pull request created even though newer version of boto3 would've been available (from boto3 1.38.17 to boto3 1.38.18 at the time of writing)
* Link to dependabot job run after a version constraint was added to pyproject.toml (`boto3` --> `boto3<2.0.0`): https://github.com/sjakthol/dependabot-uv-test/actions/runs/15082724531/job/42401448273
  * A pull request to update boto3 from 1.38.17 to 1.38.18 was created: https://github.com/sjakthol/dependabot-uv-test/pull/1
* Link to dependabot job run after version constraint for boto3 was removed from pyproject.toml (`boto3<2.0.0` --> `boto3`): https://github.com/sjakthol/dependabot-uv-test/actions/runs/15082739184/job/42401477314
  * The pull request created earlier got closed with reason `Looks like boto3 is no longer updatable, so this is no longer needed.`

### Smallest manifest that reproduces the issue

Sample project: https://github.com/sjakthol/dependabot-uv-test

Changes needed to get dependabot upgrade dependencies in lockfile: https://github.com/sjakthol/dependabot-uv-test/commit/00335b6f5c13f04b8ffc154698c7bdbcea38d6c1
