### ISSUE TITLE
Helm updates do not ignore pre-releases

### ISSUE THREAD

**Issue by gabriels17** [dependabot/dependabot-core#12271]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Helm

### Manifest location and content before the Dependabot update

PR was submitted to update cert-manager from 1.17.2 to 1.18.0. Upon checking the releases I noticed there is no 1.18.0 release, only an unstable 1.18.0-alpha.0 release.

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "helm"
    directories:
      - "..."
      - "/infra/cert-manager/chart/dev"
    groups:
      helm-dev:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
```

### What you expected to see, versus what you actually saw

Expected:
Dependabot should ignore pre-releases and not create a PR to bump the version of cert-manager.

Actual behaviour:
PR was created to update cert-manager to a version that has not yet been released.

### Smallest manifest that reproduces the issue

Chart.yaml

```
apiVersion: v2
appVersion: "1.0"
description: A Wrapper helm chart for cert-manager
name: cert-manager-wrapper
version: v1.0.0
dependencies:
- name: cert-manager
  version: 1.17.2
  repository: "https://charts.jetstack.io"
```
