### ISSUE TITLE
Dependabot declares a changed version constraint as a "bump"

### ISSUE THREAD

**Issue by austin-nl** [dependabot/dependabot-core#12286]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Docker

### dependabot.yml content

```yaml
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "release/patch"
    groups:
      dependabot-patch-and-minor-docker:
        update-types:
        - "minor"
        - "patch"
```

### Updated dependency

`bump elixir from 1.18.3-otp-27-alpine to 1.18-otp-27-alpine in the dependabot-patch-and-minor-docker group`

### What you expected to see, versus what you actually saw

We are using the `elixir` Docker image at `elixir:1.18.3-otp-27-alpine` for one of our images, but Docker keeps opening _incorrect_ upgrades which change the version constraint to be less specific than we have requested. (An example from one repo has been provided, but this is happening across multiple repos.)
