### ISSUE TITLE
Maven registry repo order issue.

### ISSUE THREAD

**Issue by whgibbo** [dependabot/dependabot-core#12298]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Maven

### Package manager version

N/A

### Language version

Java

### Manifest location and content before the Dependabot update

N/A see dependabot.yaml

### dependabot.yml content

```yaml
version: 2
registries:
  enterprise-support-mvn-remote:
    type: "maven-repository"
    url: "https://my.artifactory.com/artifactory/enterprise-mvn-remote"
    username: "${{secrets.ARTIFACTORY_USER_NAME}}"
    password: "${{secrets.ARTIFACTORY_USER_PASSWORD}}"
  maven-central-repo-remote:
    type: "maven-repository"
    url: "https://my.artifactory.com/artifactory/maven-remote"
    username: "${{secrets.ARTIFACTORY_USER_NAME}}"
    password: "${{secrets.ARTIFACTORY_USER_PASSWORD}}"

updates:
  - package-ecosystem: "maven"
    directory: "/maven"
    schedule:
      interval: "daily"
    registries:
      - enterprise-support-mvn-remote
      - maven-central-repo-remote

    target-branch: "main"
    open-pull-requests-limit: 100
```

### Updated dependency

It can be any dependency,  In this particular case we have a vendor providing extended support which in a remote repo **_enterprise-mvn-remote_**

Rather then have dependabot query maven central directly we have artifactory remote repo, for other packages.
However the older vendor versions are still in maven.

### What you expected to see, versus what you actually saw

Order of the maven repos does not appear to be honoured, in that it will not pick up new versions when use we include **_maven-central-repo-remote_** in the dependabot.yml.

Once we remove the **_maven-central-repo-remote_** from the dependabot.yml it is working as expected.

### Native package manager behavior

MVN settings.xml honours the priority order.

### Images of the diff or a link to the PR, issue, or logs

Unfortunately can't share this currently..  But what I can say is then when **_maven-central-repo-remote_** is in the dependabot there are no logs entries to **_enterprise-support-mvn-remote_**

### Smallest manifest that reproduces the issue

Again unfortunately I don't think it would help unless you had access to the vendors extended support repo.

Essentially, you would need a pom.xml that has a version that is available in maven central and a new version available in the enterprise support repo.

I.E.
- Maven Central: org.vendor:component:1.1.0
- Enterprise support: org.vender.component:1.5.0
