### ISSUE TITLE
Authentication failure when accessing private Maven repositories

### ISSUE THREAD

**Issue by piotrooo** [dependabot/dependabot-core#12293]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Gradle

### Language version

Java 21

### Manifest location and content before the Dependabot update

`/build.gradle`

### dependabot.yml content

```yaml
version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/thulium/packages
    username: piotrooo
    password: ${{secrets.PIOTROOO_PACKAGE_TOKEN}}
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - type/dependencies
  - package-ecosystem: gradle
    directory: /
    registries: '*'
    schedule:
      interval: daily
    labels:
      - type/dependencies
```

### What you expected to see, versus what you actually saw

When I try to access private packages, I see the following error:

```
updater | 2025/05/21 22:06:50 INFO <job_1019994700> Checking if com.thulium.sdk:sample-sdk 0.0.14 needs updating
  proxy | 2025/05/21 22:06:51 [012] GET [https://repo.maven.apache.org:443/maven2/com/thulium/sdk/sample-sdk/maven-metadata.xml](https://repo.maven.apache.org/maven2/com/thulium/sdk/sample-sdk/maven-metadata.xml)
  proxy | 2025/05/21 22:06:51 [012] 404 [https://repo.maven.apache.org:443/maven2/com/thulium/sdk/sample-sdk/maven-metadata.xml](https://repo.maven.apache.org/maven2/com/thulium/sdk/sample-sdk/maven-metadata.xml)
  proxy | 2025/05/21 22:06:51 [016] GET [https://maven.pkg.github.com:443/thulium/packages/com/thulium/sdk/sample-sdk/maven-metadata.xml](https://maven.pkg.github.com/thulium/packages/com/thulium/sdk/sample-sdk/maven-metadata.xml)
  proxy | 2025/05/21 22:06:51 [016] * authenticating maven repository request (host: maven.pkg.github.com)
  proxy | 2025/05/21 22:06:51 [016] 403 [https://maven.pkg.github.com:443/thulium/packages/com/thulium/sdk/sample-sdk/maven-metadata.xml](https://maven.pkg.github.com/thulium/packages/com/thulium/sdk/sample-sdk/maven-metadata.xml)
  proxy | 2025/05/21 22:06:51 [018] GET [https://repo.maven.apache.org:443/maven2/com/thulium/sdk/sample-sdk/](https://repo.maven.apache.org/maven2/com/thulium/sdk/sample-sdk/)
  proxy | 2025/05/21 22:06:51 [018] 404 [https://repo.maven.apache.org:443/maven2/com/thulium/sdk/sample-sdk/](https://repo.maven.apache.org/maven2/com/thulium/sdk/sample-sdk/)
  proxy | 2025/05/21 22:06:51 [020] POST /update_jobs/1019994700/record_update_job_error
  proxy | 2025/05/21 22:06:52 [020] 204 /update_jobs/1019994700/record_update_job_error
updater | 2025/05/21 22:06:52 INFO <job_1019994700> Handled error whilst updating com.thulium.sdk:sample-sdk: private_source_authentication_failure {:source=>"https://maven.pkg.github.com/thulium/packages"}
```

This line is especially interesting:

```
403 [https://maven.pkg.github.com:443/thulium/packages/com/thulium/sdk/sample-sdk/maven-metadata.xml]
```

Because when I try to call this package manually, like this:

```
http GET https://maven.pkg.github.com:443/thulium/packages/com/thulium/sdk/sample-sdk/maven-metadata.xml 'Authorization: bearer XXX'`
```

I get the following response:

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 250
Content-Security-Policy: default-src 'none';
Content-Type: application/xml
Date: Wed, 21 May 2025 22:13:22 GMT
Server: GitHub Registry
Strict-Transport-Security: max-age=31536000;
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-GitHub-Request-Id: BCEF:2B72D2:1345174:137EABF:682E5001
X-XSS-Protection: 1; mode=block
access-control-allow-methods: GET, HEAD, OPTIONS

<metadata>
  <groupId>com.thulium.sdk</groupId>
  <artifactId>sample-sdk</artifactId>
  <versioning>
    <latest>0.0.22</latest>
    <versions>
      <version>0.0.14</version>
      <version>0.0.22</version>
    </versions>
    <lastUpdated>20250521205744</lastUpdated>
  </versioning>
</metadata>
```

**Comment by v-thavaahariharangit** [comment]
Please update your registry configuration as below

```
version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    registries: "*"

registries: 
  maven-github:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/dsp-testing/maven-repo-to-publish"
    username: "x-access-token"
    password: "${{secrets.GIT_TOKEN}}"
```

Above config is tested and working as expected

Below are the manifest files used for testing
`build.gradle`
```
dependencies {
    implementation("com.dsp.testing:maven-repo-to-publish:1.0.1")
}
```
`settings.gradle`
```
dependencyResolutionManagement {
    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/dsp-testing/maven-repo-to-publish")
            credentials {
                username = "thavaahariharangit@github.com"
                password = "${{ secrets.GIT_TOKEN }}"
            }
        }
    }
}
```
Tested this in internal repo: gradle-dependabot-core-issue-12293

with this note I am closing this issue
