### ISSUE TITLE
Getting Build FAILED error in the Dependabot

### ISSUE THREAD

**Issue by vishnuprakash9845** [dependabot/dependabot-core#12307]
I have NuGet package configurations in Azure Artifacts and created the following dependabot.yml file. In the Azure pipeline, I was triggering Dependabot using this configuration:

**Configuration file**
```
version: 2
updates:
- package-ecosystem: "nuget"
  directories:
    - "/"
  target-branch: "master"
  commit-message:
      prefix: "Nuget Ops Update"
      include: "scope"
  groups:
    project-server-dependencies:
      applies-to: version-updates # Applies the group rule to version updates
      patterns:
        - "Ops.Lib.XXXXX"
        - "Ops.Server.XXXXXX"
  ignore:
    - dependency-name: 'LiteDB'
    - dependency-name: 'Microsoft.*' 
    - dependency-name: 'SpecFlow'
    - dependency-name: 'SpecFlow.*'
    - dependency-name: 'xunit'
    - dependency-name: 'xunit.*'
    - dependency-name: 'AutoFixture'
    - dependency-name: 'AutoFixture.*'
    - dependency-name: 'coverlet.*'
    - dependency-name: 'System.*'
    - dependency-name: 'Serilog'
    - dependency-name: 'Serilog.*'
    - dependency-name: 'PrimitiveItems'
    - dependency-name: 'SixLabors.ImageSharp'
    - dependency-name: 'SkiaSharp.Views.Blazor'
    - dependency-name: 'Moq'
  open-pull-requests-limit: 2
  registries:
      - azure_artifacts

registries:
  azure_artifacts:
    type: "nuget-feed"
    url: "https://pkgs.dev.azure.com/{org}/{proj}/_packaging/{feed-name}/nuget/v3/index.json"
    token: PAT:${{TOKEN}}
```

**Trigger file**
```
              - task: dependabot@2
                displayName: Run Dependabot on ${{repositoryName.name}}
                continueOnError: true
                inputs:
                  targetRepositoryName: ${{repositoryName.name}}
                  setAutoComplete: false
                  mergeStrategy: 'squash'
                  autoApprove: false 
                  autoApproveUserToken: $(DEPENDABOT_PAT)
                  azureDevOpsAccessToken: $(DEPENDABOT_PAT)
                timeoutInMinutes: 30
                env:
                  TOKEN: $(DEPENDABOT_PAT)
```

**Expected behavior**
It should create a pull request

**Actual behavior:**
Giving the error after 30 mins timeout

_STDERR:
updater |
updater |
updater | 2025/05/23 03:48:18 INFO     Package [System.Composition.AttributedModel] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/src/Presentation/GphsCli.PlatformAccess/GphsCli.PlatformAccess.csproj].
updater | 2025/05/23 03:48:18 INFO Updating project [/home/dependabot/dependabot-updater/repo/src/Presentation/GphsCli.WorkplaceAccess/GphsCli.WorkplaceAccess.csproj]
updater | 2025/05/23 03:48:18 INFO   Running 'PackageReference' project direct XML update
updater | 2025/05/23 03:48:18 INFO InstallDotnetSdks == true; retaining `global.json` contents.
updater | 2025/05/23 03:48:19 INFO InstallDotnetSdks == true; retaining `global.json` contents.
updater | 2025/05/23 03:48:21 WARN   Error determining dependencies from `/tmp/package-dependency-resolution_4Yx9dJ/Project.csproj`:
updater | STDOUT:
updater |   Determining projects to restore...
updater |   Restored /tmp/package-dependency-resolution_4Yx9dJ/Project.csproj (in 335 ms).
updater | /usr/local/dotnet/current/sdk/8.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error NETSDK1005: Assets file '/tmp/package-dependency-resolution_4Yx9dJ/obj/project.assets.json' doesn't have a target for 'net8.0'. Ensure that restore has run and that you have included 'net8.0' in the TargetFrameworks for your project. [/tmp/package-dependency-resolution_4Yx9dJ/Project.csproj]
updater |
updater | Build FAILED.
updater |
updater | /usr/local/dotnet/current/sdk/8.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): error NETSDK1005: Assets file '/tmp/package-dependency-resolution_4Yx9dJ/obj/project.assets.json' doesn't have a target for 'net8.0'. Ensure that restore has run and that you have included 'net8.0' in the TargetFrameworks for your project. [/tmp/package-dependency-resolution_4Yx9dJ/Project.csproj]
updater |     0 Warning(s)
updater |     1 Error(s)
updater |
updater | Time Elapsed 00:00:00.38
updater |
updater |
updater | STDERR:
updater |
updater |
updater | 2025/05/23 03:48:21 INFO     Package [System.Composition.AttributedModel] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/src/Presentation/GphsCli.WorkplaceAccess/GphsCli.WorkplaceAccess.csproj].
updater | 2025/05/23 03:48:21 INFO Updating project [/home/dependabot/dependabot-updater/repo/src/Presentation/Gphs.Client/GphsCli.csproj]
updater | 2025/05/23 03:48:21 INFO   Running 'PackageReference' project direct XML update
updater | 2025/05/23 03:48:21 INFO InstallDotnetSdks == true; retaining `global.json` contents.
updater | 2025/05/23 03:48:22 INFO InstallDotnetSdks == true; retaining `global.json` contents.
##[error]The task has timed out._

**Repo View:**

![Image](https://github.com/user-attachments/assets/c3ab7369-4fb0-498b-89b5-39f41b04eaef)
