### ISSUE TITLE
Dependabot not updating all required packages.lock.json files from referencing projects

### ISSUE THREAD

**Issue by Tsingis** [dependabot/dependabot-core#12318]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

nuget

### Language version

.NET 9

### Manifest location and content before the Dependabot update

https://github.com/Tsingis/bitcoin-web-api/pull/175/files

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "21:00"
      timezone: "Europe/Helsinki"
    target-branch: "master"
    groups:
      asp:
        patterns:
          - "Asp.Versioning.*"
      microsoft:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.Extensions.*"
      serilog:
        patterns:
          - "Serilog*"
```

### Updated dependency

Swashbuckle.AspNetCore.SwaggerUI from 8.1.1 to 8.1.2

### What you expected to see, versus what you actually saw

Expecting to update packages.lock.json from integration tests project aswell when it has project reference to api project due [WebApplicationFactory](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-9.0&pivots=xunit) usage

### Native package manager behavior

`dotnet build` and/or opening IDE generates the required missing packages.lock.json file for integration tests project.

See example required changes: https://github.com/Tsingis/bitcoin-web-api/pull/175/commits/701978473191e1f01b9c54580249e57a241dcfc9

### Images of the diff or a link to the PR, issue, or logs

https://github.com/Tsingis/bitcoin-web-api/pull/175
