### ISSUE TITLE
Adding a group for minor and patch versions breaks all of dependabot

### ISSUE THREAD

**Issue by ThomasShih** [dependabot/dependabot-core#12349]
We are having a lot of issues trying to group our minor and patch versions together, hoping someone might be able to assist in seeing if this is a bug.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: 'npm'
     groups:
      minor-and-patch:
        update-types:
          - 'patch'
          - 'minor'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 5
    reviewers:
      - <Our review Group>
    allow:
      - dependency-name: '*'
    ignore:
      - dependency-name: '@nx/*'
      - dependency-name: 'nx' # the base nx package is NOT under the @nx scope for some reason
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
      <... Some more patterns>
```

### What you expected to see, versus what you actually saw

The addition of the group block should group minor and patch version updates together, and leave major versions for individual PRs, however, the addition of the group block just stops dependabot from pushing up PRs alltogether. I feel like something is wrong with our config but we are adding the group just like how the [docs had examples...](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#example-4-grouped-pull-requests-for-minorpatch-updates-and-no-pull-requests-for-major-updates)

### Images of the diff or a link to the PR, issue, or logs

![Image](https://github.com/user-attachments/assets/452bf5c2-19ea-4392-a825-0ef2fbb9a729)
