### ISSUE TITLE
uv.lock change seems to be ignoring the "ignore" setting

### ISSUE THREAD

**Issue by therefromhere** [dependabot/dependabot-core#12354]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

uv

### Language version

Python

### Manifest location and content before the Dependabot update

https://github.com/therefromhere/dependabot-uv-bug-ignore/commit/8fe12552ed658fb22ec62b5427c1043190661003

https://github.com/therefromhere/dependabot-uv-bug-ignore/pull/2/files

### dependabot.yml content

```
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "django"
        # only allow x.y.* updates from dependabot for this package
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

### Updated dependency

Django 5.0 to 5.0.14 in the comments (which correctly aligns with the "ignore" directive
but 
5.0. to 5.2.1 in the uv.lock file

### What you expected to see, versus what you actually saw

I've specified an ignore:

```
    ignore:
      - dependency-name: "django"
        # only allow x.y.* updates from dependabot for this package
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
```

The description and comment of the PR aligns with that, but the actual change doesn't
https://github.com/therefromhere/dependabot-uv-bug-ignore/pull/2

If uv dependabot doesn't support the "ignore" directive, I think it should cause a validation error.

I think this is a quite a similar bug to https://github.com/dependabot/dependabot-core/issues/12012 - my assumption is that in both cases the issue is that the comment and the lockfile change aren't using the same source of truth.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/therefromhere/dependabot-uv-bug-ignore/pull/2
