### ISSUE TITLE
Incorrect packages picked for updates

### ISSUE THREAD

**Issue by jmstaley** [dependabot/dependabot-core#12363]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

python

### Package manager version

Poetry 2.1

### dependabot.yml content

```
  version: 2
  registries:
    basis-libraries:
      type: python-index
      url: <redeacted>
      username: <redeacted>
      password: <redeacted>
  updates:
    - package-ecosystem: "pip"
      directory: "/"
      insecure-external-code-execution: allow
      registries:
        - basis-libraries
      schedule:
        interval: "daily"
        time: "11:30"
      allow:
        - dependency-name: "*"
          dependency-type: "production"
      reviewers:
        - "team-blaze/python-reviewers"
      # Disable version update, only allow security update
      open-pull-requests-limit: 0
      groups:
        production-dependencies:
          dependency-type: "production"
          applies-to: security-updates
          update-types: ["patch", "minor"]
```

### Updated dependency

werkzeug 3.0.5 -> 3.0.6

### What you expected to see, versus what you actually saw

I had downgraded two packages to test the new groups I'd added to `dependabot.yml`. The group is for security updates only. 

What I expected to see was one single PR created with two package updates, werkzeug `3.0.5` -> `3.0.6` and jinja2 `3.1.5` -> `3.1.6`. What I got was a PR with only a single updated packages, werkzeug.

I've attempted to debug the issue and when looking at the job generated by dependabot it lists three dependencies `Jinja2`, `Werkzeug` and `werkzeug`. I've used the job json and created a yaml job and run this locally using `depdendabot-core` and the updater is working as I would expect but it seems like the list of dependencies in the job are incorrect. The dependency in `poetry.lock` is `jinja2`, lowercase j, so updater doesn't add it to the PR.

I've looked back an old run from April 17th, this was prior to adding the groups and it was able to create a PR with the listed dependency being `Jinja2`.
