### ISSUE TITLE
Cannot authenticate to OCI registry

### ISSUE THREAD

**Issue by jaredlueck** [dependabot/dependabot-core#12395]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Helm

### Package manager version

Helm

### Manifest location and content before the Dependabot update

/manifests/chart/reference-component-node

### dependabot.yml content

```yaml
version: 2
registries:
  ghcr-qlik:
    type: helm-registry
    url: "oci://ghcr.io"
    username: username
    password: password

updates:
  - package-ecosystem: helm
    directory: "/manifests/chart/reference-component-node"
    schedule:
      interval: daily
    registries:
      - ghcr-qlik
```

### What you expected to see, versus what you actually saw

I am getting errors when trying to authenticate to repositories on GHCR. 

`Error adding/updating Helm repository: Error: looks like "oci://ghcr.io/organization/helm" is not a valid chart repository or cannot be reached: ghcr.io/organization/helm/index.yaml@: not found`

I noticed this PR https://github.com/dependabot/dependabot-core/pull/12146. I not sure if that should fix this issue or if that has been released yet on GitHub runners.

also I am seeing in the logs 

`updater | 2025/06/05 13:03:34 INFO <job_1028601171> Checking if reference-component-node 0.0.0 needs updating`

I don't know why it would be trying to update the version of the chart itself? Or maybe I am misreading the logs

### Smallest manifest that reproduces the issue

```yaml
apiVersion: v2
description: Helm chart for reference-component-node
name: reference-component-node
version: 0.0.0
keywords:
  - reference-component-node
home: https://www.organization.com
sources:
  - https://github.com/organization/reference-component-node
dependencies:
  - name: qlikcommon
    version: 3.25.0
    repository: oci://ghcr.io/organization/helm
    condition: global.component-common-imports
```

**Comment by abn** [comment]
@jaredlueck try the following:

```yaml
registries:
  ghcr-qlik:
    type: docker-registry
    url: "oci://ghcr.io/organization/helm"
    username: username
    password: password
```
