### ISSUE TITLE
NuGet: Update PR is grouped despite no groups configured

### ISSUE THREAD

**Issue by kevinoid** [dependabot/dependabot-core#12401]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

C#

### Manifest location and content before the Dependabot update

https://github.com/kevinoid/NetCoreProject/blob/f545a889da89c63e58e3f6c6c8e08f82643461b3/NetCoreProject/NetCoreProject.csproj
https://github.com/kevinoid/NetCoreProject/blob/f545a889da89c63e58e3f6c6c8e08f82643461b3/NetCoreProject.UnitTests/NetCoreProject.UnitTests.csproj

### dependabot.yml content

```yaml
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
```

### Updated dependency

https://github.com/kevinoid/NetCoreProject/pull/250

- Updated Microsoft.NET.Test.Sdk from 17.13.0 to 17.14.1 in /Directory.Build.props, /NetCoreProject.UnitTests/NetCoreProject.UnitTests.csproj
- Updated SonarAnalyzer.CSharp from 10.10.0.116381 to 10.11.0.117924 in /Directory.Build.props, /NetCoreProject.UnitTests/NetCoreProject.UnitTests.csproj, /NetCoreProject/NetCoreProject.csproj
- Updated xunit.runner.visualstudio from 2.4.5 to 3.1.0 in /Directory.Build.props, /NetCoreProject.UnitTests/NetCoreProject.UnitTests.csproj

### What you expected to see, versus what you actually saw

I expected each update to be a separate PR, as they have been up until yesterday, since no groups are configured in `dependabot.yml`.  Instead, 3 updates are grouped into a single PR.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/kevinoid/NetCoreProject/pull/250

**Comment by kevinoid** [comment]
This issue was also mentioned in https://github.com/dependabot/dependabot-core/issues/12362#issuecomment-2948281964  However, that issue appears to be raising multiple issues (scheduling, ignored grouping rules, etc.) which is why I've opened this issue for the specific problem of grouped PRs when no groups are configured.

Note: I first observed the issue yesterday (2025-06-05).  It may have been introduced in [v0.316.0](https://github.com/dependabot/dependabot-core/releases/tag/v0.316.0).

**Comment by Tsingis** [comment]
As far as my observations go there have been some weird stuff happening with grouping in general even longer than that. All updates are always grouped and defined groups are not respected at all. In addition some updates are not found at all despite native tools clearly finding available updates.

**Comment by ericlamb** [comment]
I'm having a similar issue where all my updates are being put in the first group. E.g. with the grouping below everything ends up in the `aspnetcore` group.

```yaml
  groups:
    aspnetcore:
      patterns:
        - "Microsoft.AspNetCore*"
    efcore:
      patterns:
        - "Microsoft.EntityFrameworkCore*"
```
