### ISSUE TITLE
'Group' option does not include all expected dependencies ('*')

### ISSUE THREAD

**Issue by qfanee** [dependabot/dependabot-core#12421]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

maven

### Language version

Scala 2.13 / Java 17

### Manifest location and content before the Dependabot update

/pom.xml          (root)
/dir1/pom.xml  (module 1)
/dir2/pom.xml  (module 2)

### dependabot.yml content

```
  - package-ecosystem: maven
    open-pull-requests-limit: 10
    target-branch: master
    allow:
      - dependency-type: all
    directory: /
    groups:
      version-updates-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:                                                        # Update all dependencies with patch, minor versions
          - "patch"
          - "minor"
    ignore:                                                                       # Ignore springframework & netty from any upgrades
      - dependency-name: "org.springframework*"
      - dependency-name: "io.netty*"
      - dependency-name: "*"                                          # Ignore all other major version updates, for the other dependencies
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "[Dependabot]"
```

### Updated dependency

There were a lot of dependencies that were only minor-upgraded / patched, in a grouped manner. This behaviour was as expected.

### What you expected to see, versus what you actually saw

I am trying to update all of our project's dependencies by using Dependabot. Our CI/CD is within ADO. The logic that I tried to follow was:
-> Include as a grouped updates every dependency that has a minor/patch update
-> Every dependency, but not those starting with either "org.springframework" / "io.netty" should be updated
-> Disregard any "major-updates" PRs (disregard completely having individual PRs)

Considering the fact that I am using "patterns": "*", I expected to have, in the PR, all the dependencies that are not part of the "ignore" prefix list, but that is not the case. Somehow, that is not the case, as Dependabot is creating individual PRs for dependencies that should have been taken into account by the grouping..

![Image](https://github.com/user-attachments/assets/c2bbe003-ca0e-4adc-8144-eac14cef7b8a)
