### ISSUE TITLE
/pyproject.toml not parseable

### ISSUE THREAD

**Issue by kierun** [dependabot/dependabot-core#12422]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

poetry / Python

### Package manager version

Poetry (version 1.8.5)

### Language version

Python 3.13.3

### Manifest location and content before the Dependabot update

This is what I see:

![Image](https://github.com/user-attachments/assets/fa326ef6-965a-426f-8638-bb4f81323584)

My `pyproject.toml` works fine with poetry from the command line, and I could not find any reasons why it would not be parsable.

Here is the relevant [log from the latest action](https://github.com/kierun/pynpc/actions/runs/15554874794/job/43793092313)

```
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+-------------------------------------------------------------------------------+
|                                    Errors                                     |
+-------------------------------+-----------------------------------------------+
| Type                          | Details                                       |
+-------------------------------+-----------------------------------------------+
| dependency_file_not_parseable | {                                             |
|                               |   "message": "/pyproject.toml not parseable", |
|                               |   "file-path": "/pyproject.toml"              |
|                               | }                                             |
+-------------------------------+-----------------------------------------------+
Failure running container 3d95ad40670ec7d2dc28992e2b77adbbe2f92cb57f7ff5f6554f4e74dfd08a30
Cleaned up container 3d95ad40670ec7d2dc28992e2b77adbbe2f92cb57f7ff5f6554f4e74dfd08a30
  proxy | 2025/06/10 08:45:55 0/5 calls cached (0%)
2025/06/10 08:45:55 Posting metrics to remote API endpoint
```

### dependabot.yml content

You can view it [here](https://github.com/kierun/pynpc/blob/main/.github/dependabot.yml) or below:

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(GHA):"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(pip):"
    pull-request-branch-name:
      separator: "-"
```

### Updated dependency

N.A.

### What you expected to see, versus what you actually saw

What I see is an error, `"/pyproject.toml not parseable"`.

I expect 

1. The file to be parsable. I even checked with [validate-pyproject](https://pypi.org/project/validate-pyproject/) which reported neither error nor warnings.
2. The error message to tell me a little more than “not parseable”, like why not? Did you not find it? Was there an error in it? What?

### Native package manager behavior

Poetry works just fine to add, remove, and update dependencies.

### Images of the diff or a link to the PR, issue, or logs

N.A.

### Smallest manifest that reproduces the issue

[The source repo is here](https://github.com/kierun/pynpc/)
