### ISSUE TITLE
Unconfigured phantom duplicate group PRs that don't match configuration

### ISSUE THREAD

**Issue by OJFord** [dependabot/dependabot-core#12439]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm, pip

### dependabot.yml content

entries like:
```yml

  - package-ecosystem: npm
    directory: /apps/foo
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: ''
    labels: [] # this doesn't currently work any more either, cf. #12345
    groups:
      js-minor:
        update-types:
          - patch
          - minor

```

### What you expected to see, versus what you actually saw

I expect to get PRs:

- "Bump the js-minor group in /apps/foo with 2 updates"
- "Bump @unocss/nuxt from 65.5.0 to 66.2.0 in /apps/foo"

But I additionally get them like:

- "Bump the npm_and_yarn group in /apps/foo with 3 updates"
- "Bump ag-grid-community from 31.3.4 to 32.0.1 in /apps/foo in the npm_and_yarn group"

which will contain a mix of minor/patch and major version. I have no idea where the 'npm_and_yarn' group name is coming from or why that's a group.
