### ISSUE TITLE
uv: unable to update dependency with extras

### ISSUE THREAD

**Issue by mistydemeo** [dependabot/dependabot-core#12443]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

uv

### Package manager version

0.7.12

### Language version

Python 3.12.8

### Manifest location and content before the Dependabot update

Not working sample: https://github.com/mistydemeo/uvdeptest/blob/main/pyproject.toml

Working sample: https://github.com/mistydemeo/uvdeptest-noextras/blob/main/pyproject.toml

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: yt-dlp
```

### Updated dependency

yt-dlp, from 2024.7.25

### What you expected to see, versus what you actually saw

I have a project which uses `pyproject.toml`-based dependencies and a dependabot config to update one specific dependency. It looks like Dependabot is no longer able to update that dependency if I have any extras specified for it. For example, if I specify a dependency on `yt-dlp[default,curl-cffi]>=2024.7.25` Dependabot can't update it, and if I specify a dependency on `yt-dlp>=2024.7.25` it can.

The [dependabot logs](https://github.com/mistydemeo/uvdeptest/actions/runs/15620548955/job/44004055947) for the failed update show that it did *find* the new version, but concluded `Requirements to unlock update_not_possible`.

### Native package manager behavior

`uv sync --upgrade-package yt-dlp` correctly updates yt-dlp to version `2025.6.9`.

### Images of the diff or a link to the PR, issue, or logs

Repo with the dep specified using extras, where the upgrade didn't work: https://github.com/mistydemeo/uvdeptest

Repo with the dep specified without extras, where the upgrade worked: https://github.com/mistydemeo/uvdeptest-noextras

### Smallest manifest that reproduces the issue

```toml
[project]
requires-python = ">=3.9"
dependencies = [
  "yt-dlp[default,curl-cffi]>=2024.7.25"
]
```
