### ISSUE TITLE
NuGet needs to honor ignore condition update types

### ISSUE THREAD

**Issue by brettfo** [dependabot/dependabot-core#12468]
The NuGet updater currently does nothing with the `job.ignore-conditions[].update-types` property.

Ex:

``` yaml
job:
  ignore-conditions:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major # <- this is currently ignored
```
