### ISSUE TITLE
Helm image tag updates dropping `v` on tags

### ISSUE THREAD

**Issue by arsenetar** [dependabot/dependabot-core#12464]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

helm

### dependabot.yml content

``` yaml
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    groups:
      # group all minor/patch updates in one PR
      version-updates:
        dependency-type: production
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "helm"
    directories:
      - "/charts/**/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"
    groups:
      version-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
```

### Updated dependency

The dependencies that have had this issue are:
- https://github.com/vllm-project/vllm v0.8.5 -> v0.9.0.1 & v0.9.0.1 -> v0.9.1
- https://github.com/llm-d/llm-d-inference-sim/pkgs/container/llm-d-inference-sim v0.1.1 -> v0.1.2

### What you expected to see, versus what you actually saw

Versions are updated to the correct tag, not missing the leading `v`.  Some updates have correctly worked (first time llm-d-inference-sim was updated it was correctly updated), others result in the leading `v` in the tag being dropped.  It also seems to be removing the newline at the end of the file when this happens.

### Images of the diff or a link to the PR, issue, or logs

Example diff from PR:

<img width="1331" alt="Image" src="https://github.com/user-attachments/assets/9d86ebed-aef9-46af-b2e6-cc3abcb691f7" />

### Smallest manifest that reproduces the issue

This should reproduce the issue in a values.yaml file for a chart.
``` yaml
test:
    image:
      repository: ghcr.io/llm-d/llm-d-inference-sim
      tag: v0.1.1
```
