### ISSUE TITLE
Incorrect npm private registry URL for scoped packages

### ISSUE THREAD

**Issue by shashidhar087** [dependabot/dependabot-core#12469]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

```
version: 2
registries:
  npm-artifactory:
    type: npm-registry
    url: https://artifactory.xxxxxx.io/artifactory/api/npm/xxxxxx-global-npm-virtual/
    token: ${{secrets.Artifactory_token}}
    replaces-base: true
updates:
  - package-ecosystem: 'npm'
    registries:
      - npm-artifactory
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      patch:
        update-types:
          - 'patch'
```

### What you expected to see, versus what you actually saw

I expected Dependabot to successfully check for new versions of the scoped package and create a pull request if an update was available. 
The incorrect registry URL is - https://artifactory.xxxxxxxx.io/@test-scope%2Fdj-shared-functions

The expected registry URL is - https://artifactory.xxxxxxxx.io/artifactory/api/npm/dj-global-npm-virtual/@test-scope%2Fdj-shared-functions

### Images of the diff or a link to the PR, issue, or logs

> updater | 2025/06/17 15:27:10 INFO <job_1036075229> Checking if @test-scope/dj-shared-functions 3.7.0 needs updating
> updater | 2025/06/17 15:27:10 INFO <job_1036075229> Ignored versions:
> updater | 2025/06/17 15:27:10 INFO <job_1036075229>   > 3.7.0 - from @dependabot ignore command
>   proxy | 2025/06/17 15:27:10 [019] GET https://artifactory.xxxxxxx.io/@test-scope-ghfb%2Fdj-shared-functions
>   proxy | 2025/06/17 15:27:10 [019] * authenticating npm registry request (host: artifactory.xxxxxxxx.io, token auth)
>   proxy | 2025/06/17 15:27:10 [019] 404 https://artifactory.xxxxxxx.io/@test-scope-ghfb%2Fdj-shared-functions
> updater | 2025/06/17 15:27:10 INFO <job_1036075229> Adding dependencies as handled: (@test-scope-ghfb/dj-shared-functions).
>   proxy | 2025/06/17 15:27:10 [021] POST /update_jobs/1036075229/record_update_job_error
>   proxy | 2025/06/17 15:27:10 [021] 204 /update_jobs/1036075229/record_update_job_error
> updater | 2025/06/17 15:27:10 INFO <job_1036075229> Handled error whilst updating @test-scope-ghfb/dj-shared-functions: private_source_authentication_failure {source: "artifactory.xxxxxxxxx.io:443"}

```
> Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+------------------------------------------------------------------------------------------------------------------------+
|                                             Dependencies failed to update                                              |
+------------------------------------+---------------------------------------+-------------------------------------------+
| Dependency                         | Error Type                            | Error Details                             |
+------------------------------------+---------------------------------------+-------------------------------------------+
| @test-scope/dj-shared-functions | private_source_authentication_failure | {                                         |
|                                    |                                       |   "source": "artifactory.xxxxxxxx.io:443" |
|                                    |                                       | }                                         |
+------------------------------------+---------------------------------------+-------------------------------------------+
```
