### ISSUE TITLE
Dependabot fails to detect newer version of reusable workflows

### ISSUE THREAD

**Issue by jasonkarns** [dependabot/dependabot-core#12489]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

Calling workflow: https://github.com/jasonkarns/bats-mock/blob/9d0eecf7187f12e6c5604972e7a1f1fb264344c9/.github/workflows/release.yml

```yml
uses: nodenv/.github/.github/workflows/release.yml@4a6b0b802263fdeb2035c36ec813da4e468945b7 # v4.5.3
```

### dependabot.yml content

https://github.com/jasonkarns/bats-mock/blob/9d0eecf7187f12e6c5604972e7a1f1fb264344c9/.github/dependabot.yml

```yml
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: weekly }
```

### Updated dependency

There are 3/4 newer releases of the reusable workflows. Tags (each with a corresponding github release): `[v5.0.0](https://github.com/nodenv/.github/releases/tag/v5.0.0)`, `[v5.0.1](https://github.com/nodenv/.github/releases/tag/v5.0.1)`, `[v5.0.2](https://github.com/nodenv/.github/releases/tag/v5.0.2)` as well as a "vMajor" branch ref `[v5](https://github.com/nodenv/.github/tree/v5)`

https://github.com/nodenv/.github/releases

### What you expected to see, versus what you actually saw

I expected dependabot to open a PR to bump the release.yml workflow to v5* (at least one of the tags or branch). Instead, nothing was opened and dependabot reported no updates.

https://github.com/jasonkarns/bats-mock/actions/runs/15781575703/job/44488266989

### Images of the diff or a link to the PR, issue, or logs

[0_Dependabot.txt](https://github.com/user-attachments/files/20839026/0_Dependabot.txt)

[3_Run Dependabot.txt](https://github.com/user-attachments/files/20839038/3_Run.Dependabot.txt)
