### ISSUE TITLE
Dependabot ignores centrally pinned transitive version with `VersionOverride` and `CentralPackageTransitivePinningEnabled`

### ISSUE THREAD

**Issue by samtrion** [dependabot/dependabot-core#12493]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

latest

### Language version

C# 13

### Manifest location and content before the Dependabot update

[Directory.Packages.props](https://github.com/dailydevops/healthchecks/blob/main/Directory.Packages.props)
```xml
  <!-- part of / trimmed -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AWSSDK.SimpleNotificationService" Version="4.0.0.1" />
  </ItemGroup>
```

[Project file](https://github.com/dailydevops/healthchecks/blob/main/src/NetEvolve.HealthChecks.AWS.SNS/NetEvolve.HealthChecks.AWS.SNS.csproj)
```xml
    <!-- part of -->
    <PackageReference
      Include="AWSSDK.SimpleNotificationService"
      VersionOverride="[4.0.0, 5.0.0)"
      NoWarn="NU1901;NU1902;NU1903;NU1904"
    />
```

### dependabot.yml content

[dependabot.yml](https://github.com/dailydevops/healthchecks/blob/main/.github/dependabot.yml)
```yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependency:actions"
    open-pull-requests-limit: 20
    # Add assignees
    assignees:
      - samtrion

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependency:nuget"
    open-pull-requests-limit: 20
    # Add assignees
    assignees:
      - samtrion
    groups:
     coverlet:
       patterns:
         - "coverlet*"
     nunit:
       patterns:
         - "nunit"
         - "nunit*"
     testcontainers:
       patterns:
         - "testcontainers*"
     tunit:
       patterns:
         - "tunit"
         - "tunit*"
     verify:
       patterns:
         - "verify*"
     xunit:
       patterns:
         - "xunit"
         - "xunit*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(dev)"
    labels:
      - "dependency:devcontainers"
    open-pull-requests-limit: 20
    # Add assignees
    assignees:
      - samtrion
```

### Updated dependency

In addition to `AWSSDK.SimpleNotificationService`, other dependencies (approx. 10+) are affected. `AWSSDK.SimpleNotificationService` is only an example

`AWSSDK.SimpleNotificationService` - `4.0.0.1` -> `4.0.0.10`

### What you expected to see, versus what you actually saw

I would expect a PR that updates the following line as follows. Since this Dependency Transitive is used in [`Testproject`](https://github.com/dailydevops/healthchecks/blob/main/tests/NetEvolve.HealthChecks.Tests.Integration/NetEvolve.HealthChecks.Tests.Integration.csproj).

```xml
<PackageVersion Include="AWSSDK.SimpleNotificationService" Version="4.0.0.10" />
```

### Native package manager behavior

The native visual studio nuget manager updates the version inside the `Directory.Packages.props`

### Latest logs
[logs_40446324193.zip](https://github.com/user-attachments/files/20852591/logs_40446324193.zip)
