### ISSUE TITLE
Dependabot removes catalog/catalogs field with bun

### ISSUE THREAD

**Issue by Repomn** [dependabot/dependabot-core#12522]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

bun

### Package manager version

bun@1.2.14

### Language version

typescript@5.8.3

### dependabot.yml content

```yml
version: 2
updates:
   - package-ecosystem: "bun"
      directory: "/"
      schedule:
        interval: "daily"
        time: "08:00"
        timezone: "Asia/Tokyo"
      open-pull-requests-limit: 15
```

### What you expected to see, versus what you actually saw

Dependabot removes this fields of bun.lock on every Pull Request.
```
...
"catalog": {
    "zod": "^3.23.8",
  },
  "catalogs": {
    "ui": {
      "react": "^19.1.0",
      "react-dom": "^19.1.0"
    },
  },
...
```
