### ISSUE TITLE
Support missing author.email in Azure DevOps commits

### ISSUE THREAD

**Issue by acraven** [dependabot/dependabot-core#1252]
My dependabot script targeting an Azure DevOps repo is currently failing to create a PR due to a commit that does not contain the `author.email` field as below.

I don't have permissions to delete the branch containing the commit, but will continue my spike with a new repo.

This is a great product, but I've found very few resources on getting up to speed with Azure DevOps and Azure Artifacts. Keep up the good work.

```
- commitId: fc83...4452
  author:
    name: Project Collection Build Service (***)
    date: '2019-07-11T12:11:52Z'
  committer:
    name: Project Collection Build Service (***)
    date: '2019-07-11T12:11:52Z'
  comment: Bump ***.Core from 1.1.19144.1 to 1.1.19191.1
  commentTruncated: true
  changeCounts:
    Add: 0
    Edit: 1
    Delete: 0
  url: https://dev.azure.com/***/fd90...e97b/_apis/git/repositories/b125...b47d/commits/fc83...4452
  remoteUrl: https://dev.azure.com/***/***/_git/nugetspike/commit/fc83...4452
```
