### ISSUE TITLE
Dependabot has stopped providing the changelog of updated dependencies

### ISSUE THREAD

**Issue by patrickomeara** [dependabot/dependabot-core#12531]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

composer

### Package manager version

2.8.9

### Language version

8.4.8

### Manifest location and content before the Dependabot update

composer.json

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Australia/Melbourne"
    ignore:
      - dependency-name: "laravel/cashier-paddle"
        versions: [">=2"]
    groups:
      composer:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "07:00"
      timezone: "Australia/Melbourne"
    groups:
      actions:
        patterns:
          - "*"
```

### What you expected to see, versus what you actually saw

The last two times (weekly) dependabot runs, but does not provide any info about the packages it has updated.

![Image](https://github.com/user-attachments/assets/28204bc3-54b6-4633-a7cc-69f7be2f1f4e)

**Comment by reduckted** [comment]
I just encountered this on https://github.com/reduckted/GitWebLinks/pull/374

Package ecosystem was npm.

**Comment by matijs** [comment]
Maybe a duplicate of https://github.com/dependabot/dependabot-core/issues/12253?

This started happenening for one of my repos for the `npm` ecosystem. What that repo has in common with @patrickomeara's and @reduckted's repos and the one in the linked issue, is the presence of a `groups` and `ignore` block:

```yaml
groups:
  non-major-dependencies:
    applies-to: "version-updates"
    update-types:
      - "patch"
      - "minor"
ignore:
  - dependency-name: "react"
    update-types:
      - "version-update:semver-major"
  - dependency-name: "react-dom"
    update-types:
      - "version-update:semver-major"
```

Another repo that has no issues has a `groups` block but _no_ `ignore` block:

```yaml
groups:
  non-major-dependencies:
    applies-to: "version-updates"
    update-types:
      - "patch"
      - "minor"
```

**Update**
After merging the PR without changelogs I triggered Dependbot by hand and it created a tiny PR with just 2 updated dependencies that both had changelogs once again. 🤷

**Update 2025-07-14**
A PR with 11 updates did not have any changelogs. 😔

**Comment by 3raser95** [comment]
I have a private repo that has `groups` but no `ignore` and I'm experiencing this same issue there so I don't think the `ignore` is causing the issue.

**Comment by nicou** [comment]
Also experiencing this issue in our repos while using `groups` but no `ignore`.

**Comment by reduckted** [comment]
> I just encountered this on [reduckted/GitWebLinks#374](https://github.com/reduckted/GitWebLinks/pull/374)

In case it helps track down what's causing it, the pull request from seven days earlier did show the changelog.
https://github.com/reduckted/GitWebLinks/pull/373

**Comment by patrickomeara** [comment]
Yeah, this has only been an issue for me for the last two weeks. Nothing has changed on the dependabot settings side of things. I have other repos that use dependabot that still show the changelog

**Comment by 3raser95** [comment]
Just actually had dependabot create three different PRs today and none of them showed the changelog. After merging two of them the third one got recreated and the new PR suddenly had the correct changelogs appear. Really weird behaviour.

**Comment by ethanmdavidson** [comment]
Also happening for me, and I have very simple configs:

```yaml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```
