### ISSUE TITLE
Support for NuGet package lock files

### ISSUE THREAD

**Issue by xt0rted** [dependabot/dependabot-core#1303]
In NuGet 4.9 I think it is they added support for package lock files using the setting `RestorePackagesWithLockFile` which is part of your `.csproj` or `.props` file chain. This creates a file called `packages.lock.json` alongside your project file. The spec for this can be found at https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file

**Comment by greysteil** [comment]
Super keen to do this, but it's going to require some work - at the moment Dependabot does all of its .NET updating in Ruby, and we'll need to change that. We might want to continue this over at https://github.com/dependabot/dependabot-core/issues/541?

**Comment by gitfool** [comment]
@jerriep. given your great work with [dotnet-outdated](https://github.com/jerriep/dotnet-outdated), do you have any advice on how Dependabot can also update any associated [dependency lock](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#locking-dependencies) files in its PR?

Is the best way to run [`dotnet restore`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore), perhaps with [`--force-evaluate`](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#lock-file-extensibility), or are there other better ways?

**Comment by jerriep** [comment]
@gitfool No, I was not even aware of this new feature until you just pointed it out. You may have to resort to using some of the [NuGet Client libraries](https://github.com/NuGet/NuGet.Client) to achieve this.

Maybe look at [this PR](https://github.com/NuGet/NuGet.Client/pull/2342) and the linked specifications to see whether there are some hints to guide you.

**Comment by vmcbaptista** [comment]
is there any news regarding this topic?

**Comment by edumserrano** [comment]
Would also be interested in support for this feature. Any updates?

**Comment by majastrz** [comment]
Would also be interested in support for this.

**Comment by flcdrg** [comment]
I've written up a workaround for this at https://david.gardiner.net.au/2021/05/dependabot-nuget-lockfiles.html, but would much prefer it was handled natively given that dependabot stops maintaining the PR once a 'foreign' commit has been added.

**Comment by nogic1008** [comment]
As a workaround, I define a GitHub action in my repository that kicks `dotnet restore`.
*Note: You need to use [Personal Access Token](https://docs.github.com/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) to re-trigger another GitHub Actions (like unit testing)*
```yaml
  restore:
    name: Update NuGet Lock Files
    if: contains(github.head_ref, 'dependabot') && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x

      - run: dotnet restore --force-evaluate
      - id: diff
        continue-on-error: true
        run: |
          git add -N .
          git diff --name-only --exit-code
      - if: steps.diff.outcome == 'failure'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "chore(deps): update NuGet lock file"
          git push
```
