### ISSUE TITLE
Allow or improve wording around indentation in config.yml

### ISSUE THREAD

**Issue by MitchellCash** [dependabot/dependabot-core#1315]
I was having issues with my `config.yml` and couldn't figure out why it wasn't valid. I stumbled across this comment https://github.com/dependabot/dependabot-core/issues/956#issuecomment-456897223 which helped solve my problem.

I had incorrectly indented my config file as:

```yml
allowed_updates:
  - match:
    update_type: "all"
```

Instead of the allowed way:

```yml
allowed_updates:
  - match:
      update_type: "all"
```

The fix was simple, but difficult to figure out, because the errors I received were:

```
The property '#/update_configs/0/allowed_updates/0' contains additional properties ["update_type"] outside of the schema when none are allowed
The property '#/update_configs/0/allowed_updates/0/match' of type null did not match the following type: object
```

It would be good to get better error handling/messaging on this specific issue.
