### ISSUE TITLE
Unexpected behavior when using NPM private registry

### ISSUE THREAD

**Issue by kenchan0130** [dependabot/dependabot-core#1339]
## Expect behavior

Run updating dependences without exception.

## Actual behavior

```
Parsing dependencies information
  - Updating eslint-config-prettier (from 3.1.0)…/builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:320:in `handle_missing_package': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): registry.npmjs.org (Dependabot::PrivateSourceAuthenticationFailure)
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:181:in `handle_npm_updater_error'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:41:in `rescue in updated_lockfile_content'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:24:in `updated_lockfile_content'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:187:in `updated_package_lock_content'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:120:in `package_lock_changed?'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:149:in `block in updated_lockfiles'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `each'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `updated_lockfiles'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:39:in `updated_dependency_files'
...
/builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-common-0.112.5/lib/dependabot/shared_helpers.rb:112:in `run_helper_subprocess': 404 Not Found - GET https://registry.npmjs.org/@myPrivateRegistoryScope%2faws-util - Not found (Dependabot::SharedHelpers::HelperSubprocessFailed)
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:151:in `run_npm_top_level_updater'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:139:in `block in run_npm_updater'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-common-0.112.5/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:137:in `run_npm_updater'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:115:in `run_current_npm_update'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:35:in `block (2 levels) in updated_lockfile_content'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `chdir'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `block in updated_lockfile_content'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-common-0.112.5/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-common-0.112.5/lib/dependabot/shared_helpers.rb:37:in `chdir'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-common-0.112.5/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
	from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-common-0.112.5/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:30:in `updated_lockfile_content'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:187:in `updated_package_lock_content'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:120:in `package_lock_changed?'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:149:in `block in updated_lockfiles'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `each'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `updated_lockfiles'
	from /builds/SampleGroup/dependabot/vendor/bundle/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.112.5/lib/dependabot/npm_and_yarn/file_updater.rb:39:in `updated_dependency_files'
...
```

## Step to reproduce

At first, prepare `.npmrc` in the repository to be updated as follows.

```
registry=https://repo.example.com/npm-all/
```

And `https://repo.example.com/npm-all/` is configured on the registry side so that it can be accessed without a token.

Finally, run script.

**Comment by feelepxyz** [comment]
@kenchan0130 oh looks like it's still trying to fetch from `registry.npmjs.org`. How are you running dependabot-core? Could you put together a reproduction case/repository?

**Comment by kenchan0130** [comment]
@feelepxyz 
Since the repository is private, I will write specific methods here.

```ruby
# This file is Gemfile
source 'https://rubygems.org'

gem "dependabot-omnibus", "~> 0.112.5"
```

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true
# This file is bin/entrypoint.rb

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)

require "bundler/setup"

load File.expand_path("./generic-update-script.rb", __dir__)
```

```ruby
# Original is https://github.com/dependabot/dependabot-script/tree/371ba5e5929fb852b9130ddfba5c1fd5ddf36572
# This script is designed to loop through all dependencies in a GHE, GitLab or
# Azure DevOps project, creating PRs where necessary.

require "dependabot/file_fetchers"
require "dependabot/file_parsers"
require "dependabot/update_checkers"
require "dependabot/file_updaters"
require "dependabot/pull_request_creator"
require "dependabot/clients/gitlab_with_retries"
require "dependabot/omnibus"

credentials = [
  {
    "type" => "git_source",
    "host" => "github.com",
    "username" => "x-access-token",
    "password" => ENV["GITHUB_ACCESS_TOKEN"] # A GitHub access token with read access to public repos
  }
]

# Full name of the repo you want to create pull requests for.
repo_name = "Sample/node-project"

# Directory where the base dependency files are.
directory = "/"

package_manager = "npm_and_yarn"

# This is private hosting gitlab host name.
gitlab_hostname = "gitlab.example.com"

credentials << {
  "type" => "git_source",
  "host" => gitlab_hostname,
  "username" => "x-access-token",
  "password" => ENV["GITLAB_ACCESS_TOKEN"] # A GitLab access token with API permission
}

api_endpoint = "https://#{gitlab_hostname}/api/v4"

project_branch_name = "dependabot-test"

source = Dependabot::Source.new(
  provider: "gitlab",
  hostname: gitlab_hostname,
  api_endpoint: api_endpoint,
  repo: repo_name,
  directory: directory,
  branch: project_branch_name,
  )

##############################
# Fetch the dependency files #
##############################
puts "Fetching #{package_manager} dependency files for #{repo_name}"
fetcher = Dependabot::FileFetchers.for_package_manager(package_manager).new(
  source: source,
  credentials: credentials,
)

files = fetcher.files
commit = fetcher.commit

##############################
# Parse the dependency files #
##############################
puts "Parsing dependencies information"
parser = Dependabot::FileParsers.for_package_manager(package_manager).new(
  dependency_files: files,
  source: source,
  credentials: credentials,
)

dependencies = parser.parse

dependencies.select(&:top_level?).each do |dep|
  #########################################
  # Get update details for the dependency #
  #########################################
  checker = Dependabot::UpdateCheckers.for_package_manager(package_manager).new(
    dependency: dep,
    dependency_files: files,
    credentials: credentials,
  )

  next if checker.up_to_date?

  requirements_to_unlock =
    if !checker.requirements_unlocked_or_can_be?
      if checker.can_update?(requirements_to_unlock: :none) then :none
      else :update_not_possible
      end
    elsif checker.can_update?(requirements_to_unlock: :own) then :own
    elsif checker.can_update?(requirements_to_unlock: :all) then :all
    else :update_not_possible
    end

  next if requirements_to_unlock == :update_not_possible

  updated_deps = checker.updated_dependencies(
    requirements_to_unlock: requirements_to_unlock
  )

  #####################################
  # Generate updated dependency files #
  #####################################
  print "  - Updating #{dep.name} (from #{dep.version})…"
  updater = Dependabot::FileUpdaters.for_package_manager(package_manager).new(
    dependencies: updated_deps,
    dependency_files: files,
    credentials: credentials,
  )

  updated_files = updater.updated_dependency_files

  ########################################
  # Create a pull request for the update #
  ########################################
  pr_creator = Dependabot::PullRequestCreator.new(
    source: source,
    base_commit: commit,
    dependencies: updated_deps,
    files: updated_files,
    credentials: credentials,
    label_language: true,
    branch_name_separator: "-" # GitLab API does not support slash separator.
  )
  pull_request = pr_creator.create
  puts " submitted"

  next unless pull_request

  # Enable GitLab "merge when pipeline succeeds" feature.
  # Merge requests created and successfully tested will be merge automatically.
  if ENV["GITLAB_AUTO_MERGE"]
    g = Gitlab.client(
      endpoint: source.api_endpoint,
      private_token: ENV["GITLAB_ACCESS_TOKEN"]
    )
    g.accept_merge_request(
      source.repo,
      pull_request.iid,
      merge_when_pipeline_succeeds: true,
      should_remove_source_branch: true
    )
  end
end

puts "Done"
```

```yaml
# GitLab CI configuration for Dependabot
#
# Usage:
# * Set the required global variables used in `./generic-update-script.rb`
#   https://docs.gitlab.com/ee/ci/variables/#variables
#
# * Create a pipeline schedule for each managed repository
#   https://docs.gitlab.com/ee/user/project/pipelines/schedules.html
#
# * Set in the schedule required variables
#
#     PROJECT_PATH = group/repository
#     PACKAGE_MANAGER_SET = bundler,composer,npm_and_yarn
#
# https://github.com/dependabot/dependabot-script
# https://docs.gitlab.com/ee/ci/yaml/

.dependabot:
  stage: build
  image: dependabot/dependabot-core
  before_script:
    - gem update --system
    - gem install bundler -v 1.17.3
    - bundle install -j $(nproc) --path vendor/bundle
  variables:
    PACKAGE_MANAGER: $CI_JOB_NAME
  cache:
    untracked: true
    paths:
      - vendor/bundle
  script:
    - bundle exec ruby bin/dependabot.rb
  only:
    - schedules

bundler:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bbundler\b/

pip:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bpip\b/

npm_and_yarn:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /(\bnpm|yarn\b)/

maven:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bmaven\b/

gradle:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bgradle\b/

cargo:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bcargo\b/

hex:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bhex\b/

composer:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bcomposer\b/

nuget:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bnuget\b/

dep:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bdep\b/

go_modules:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bgo_modules\b/

elm:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\belm\b/

submodules:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bsubmodules\b/

docker:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bdocker\b/

terraform:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER_SET =~ /\bterraform\b/
```

---

We call core in much the same way https://github.com/dependabot/dependabot-script.
