### ISSUE TITLE
[JS] dependabot won't update private package's package.json

### ISSUE THREAD

**Issue by ptusch** [dependabot/dependabot-core#1356]
Hello there,

I'm currently checking if dependabot is good to use for some private repos I have. The issue is that dependabot only updates the `package-lock.json` but never `package.json`. This is not ideal as people who install the package in order to develop, would downgrade the version again.
The setup is as follows:
* Private registry 
* Private package, which is hosted on the private registry and github
* dependabot-preview to update packages

I read that the bot tries to make a distinction between application and libraries so I think that's the issue but no idea how I can counter it (the description in the package.json wil never be on npm and github isn't aware of the private repo)

Here's the dependabot config I use:
```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "./really_cool_name"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"

```
