### ISSUE TITLE
Deauthorized accounts break default_reviewers

### ISSUE THREAD

**Issue by larouxn** [dependabot/dependabot-core#1360]
👋 It seems that if you have `default_reviewers` set up with multiple GitHub users for a private organization level repository and one of those users is removed from the organization then on subsequent Dependabot PRs, nobody will be added as reviewers.

Is it possible that despite there being valid authorized users still present in the config because one of the `default_reviewers` no longer has access that Dependabot doesn't request review from anyone?

My specific experience was such that this repo had two `default_reviewers`, myself and one other developer. The other developer lost access to the repos last week. Then, this week, Dependabot created some gem bump PRs but didn't tag anyone for review. I have confirmed that prior PRs, before the deauthorization, both the other developer and myself were requested for review.

Configuration example:
```yml
version: 1
update_configs:
  # Update your Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - larouxn # me
      - other_developer # deauthorized user
    default_labels:
      - "Gem upgrades"

    version_requirement_updates: "auto"
```

Disclaimer, as I just discovered this, I haven't had time to explicitly try to reproduce it.
