### ISSUE TITLE
Limiting to security updates doesn't work when using multiple package managers

### ISSUE THREAD

**Issue by YPCrumble** [dependabot/dependabot-core#1441]
I have the following dependabot config in my repo:

```
version: 1

update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    allowed_updates:
      - match:
          update_type: "security"
    default_reviewers:
    - YPCrumble
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    target_branch: "develop"
    allowed_updates:
      - match:
          update_type: "security"
    default_reviewers:
    - YPCrumble
```

Normally (when only using one package manager for a repo) using `match: update_type: "security"` works fine. For this repo, however, the configuration to only create security updates doesn't work - PR's for all updates are being created by dependabot.

**Comment by feelepxyz** [comment]
@YPCrumble oh not sure what's gone wrong here but can look into it. Which repo are you seeing this issue on?

**Comment by YPCrumble** [comment]
@feelepxyz thanks for your help! It's a private repo - I don't know if it's helpful to give you the link to a private repo?

**Comment by feelepxyz** [comment]
@YPCrumble looks like your update config is invalid which is why the allowed updates are not applied, should look something like:

```yml
version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    allowed_updates:
      - match:
         update_type: "security"
    default_reviewers:
      - YPCrumble
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    target_branch: "develop"
    allowed_updates:
      - match:
         update_type: "security"
    default_reviewers:
      - YPCrumble
```

Looks like this is currently being fetched which has `allowed_updates` on the top level which isn't supported:

```yml
version: 1

update_configs:
  - allowed_updates:
    - match:
      update_type: "security"
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
    - YPCrumble
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
    - YPCrumble
```
