### ISSUE TITLE
Dependabot fails to authenticate to Artifactory Docker repository

### ISSUE THREAD

**Issue by steinwelberg** [dependabot/dependabot-core#1512]
We are using Artifactory as our Docker repository and I wanted to set it up so Dependabot can access it. After setting it up in the UI (as config variable), I receive an authentication error.

The repository URL is specified as `host:port`. (`release.onegini.com:443`). I have also tried it without the port (same result).

I'm 100% sure that the username & password are correct. I've re-entered them multiple times.

After googling around I couldn't find anything that could help me further, hence this ticket ;-).

**Comment by MuhannadVisma** [comment]
Have you ever managed to figure out an easy way to work around this? It seems that the Dependabot secrets are not made available during the "Initializing containers" step which means that it's practically impossible to use a private image such as:

```yml
phpunit:
  name: PHPUnit
  runs-on: ubuntu-latest
  container:
    image: eu.gcr.io/acme-corp/phpunit:latest
    credentials:
      username: _json_key
      password: ${{ secrets.GCR_JSON }}
  steps:
    - uses: actions/checkout@v6
    - run: composer install
    - run: vendor/bin/phpunit
```

but instead one would have to do something like this:

```yml
phpunit:
  name: PHPUnit
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v6
    - uses: docker/login-action@v4
      with:
        registry: eu.gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON }}
    - run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          eu.gcr.io/acme-corp/phpunit:latest \
          composer install
    - run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          eu.gcr.io/acme-corp/phpunit:latest \
          vendor/bin/phpunit
```
