### ISSUE TITLE
Dependabot couldn't find a Dockerfile for this project

### ISSUE THREAD

**Issue by ThibaultVlacich** [dependabot/dependabot-core#1540]
Dependabot just created this issue in my repository:

> Dependabot couldn't find a Dockerfile for this project.
> 
> Dependabot requires a Dockerfile to evaluate your project's current Docker dependencies. It had expected to find one at the path: /‎client/Dockerfile.
> 
> If this isn't a Docker project, or if it is a library, you may wish to disable updates for it in the .dependabot/config.yml file in this repo.

Of course, the file `/‎client/Dockerfile` do exists. I tried to manually rebump, but the error is present every time.

Here's my config:
```yaml
  - package_manager: "docker"
    directory: "/‎client"
    update_schedule: "daily"
    target_branch: "develop"
    # Apply default reviewer and label to created pull requests
    default_assignees:
      - "ThibaultVlacich"
    default_labels:
      - "dependencies"
      - "docker"
```
