### ISSUE TITLE
YAML aliases

### ISSUE THREAD

**Issue by prma85** [dependabot/dependabot-core#1582]
As an user, I would like to use YAML aliases to convert long code/configuration that repeats in simple one. Today, if you try to to it, you will get an error `YAML aliases are not supported`

I would like to convert
```yml
version: 1
update_configs:
    # Keep package.json up to date
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    allowed_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "semver:minor"

    # Also update the defaults
  - package_manager: "javascript"
    directory: "/__defaults"
    update_schedule: "live"
    version_requirement_updates: "auto"
    allowed_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "semver:minor"
`
``

into 
```yml
default: &DEFAULT
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    allowed_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "semver:minor"

version: 1
update_configs:
    <<: *DEFAULT

    # Also update the defaults
    <<: *DEFAULT
    directory: "/__defaults"
```

**Comment by feelepxyz** [comment]
@prma85 👋 thanks for the suggestion! We're holding off on supporting aliases until we know what will be supported in GitHub Actions workflow files. We're keen to keep these feature compatible so we can migrate towards actions in future.

**Comment by amthorn** [comment]
I'd like to request to reopen this one. yaml Aliases would be super useful for dependabot.

**Comment by tenpaiyomi** [comment]
Voicing my request for this as well.  A simple alias can help me clean up 44 duplicate lines of code down into just 4 (plus the original alias block)

**Comment by TArch64** [comment]
Same here. YAML aliases are super useful

**Comment by DominikGM** [comment]
Vote at https://github.com/orgs/community/discussions/37496  (warming up this old issue as this is the first search-result)

**Comment by jeffwidman** [comment]
Yeah, this should be re-opened, it got missed back when we had stalebot a long time ago.

I'm not sure we'll do it... as noted above, we have some interest in moving to be more compatible with actions workflow files, but in the meantime this should stay open.

**Comment by jeffwidman** [comment]
If do ever implement this, note [the warning](https://github.com/dependabot/dependabot-core/issues/2127#issuecomment-514981931) from @greysteil:
> it's surprisingly tricky to do in Ruby whilst avoiding the potential for DoS attacks from memory leaks.

**Comment by port19x** [comment]
![image](https://github.com/dependabot/dependabot-core/assets/82055622/601764e1-9a78-4e6e-a603-14745f2219e2)

**Comment by landongrindheim** [comment]
👋 Still [not sure we'll do this](https://github.com/dependabot/dependabot-core/issues/1582#issuecomment-1302386986), but this feature request deserves some context.

Dependabot has a backend service that parses the `dependabot.yml` config file and transforms it into a shape that can be used when Dependabot runs its update jobs. We've accrued quite a few ecosystems, which each have unique considerations. This parsing ends up being more complex than we'd like already, and introducing YAML aliases would make it more complex. Given that we have users with hundreds of configurations within a single file, the [previously shared warning](https://github.com/dependabot/dependabot-core/issues/1582#issuecomment-1398926186) is a factor as well.


**BUT** I can share that we're currently running [a public beta](https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/) which introduces multi-directory support. While it may not satisfy the needs for all usecases mentioned in this thread, it should address the case in this issues description. That might look something like 👇 today.


```yaml
version: 2
updates:
  - package-ecosystem: npm
    directories: 
      - "/"
      - "/__defaults"
    schedule:
      interval: daily
    allow:
      - dependency-type: all
```

**Comment by carlincherry** [comment]
Hi all 👋 , Dependabot PM here! Thank you for your suggestions and for contributing to the discussion. At this time, we won't be prioritizing this feature for the following reasons (thank you @landongrindheim for the summary above, to reiterate your comments):

- **Complexity**: Dependabot's backend service parses the dependabot.yml configuration file and transforms it for use in update jobs. Given the diverse ecosystems we support, each with unique considerations, the current parsing process is already quite complex. Introducing YAML aliases further complicates this already difficult process.

- **Security**: Implementing YAML aliases in Ruby presents significant challenges, particularly in avoiding potential DoS attacks due to memory leaks. 

However, for some potential solves for issues mentioned in this thread, check out our multi-directory [public beta](https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/)!

We appreciate your understanding and encourage you to provide feedback on the multi-directory support beta. Your input is valuable as we continue to improve Dependabot!

**Comment by lucasfcnunes** [comment]
@prma85

Shouldn't it be something like the following?

```yaml
# ...
update_configs:
  - <<: *DEFAULT
  # Also update the defaults
  - <<: *DEFAULT
    directory: "/__defaults"
```
