### ISSUE TITLE
Create 1 PR for the same update across update configs

### ISSUE THREAD

**Issue by hisuwh** [dependabot/dependabot-core#1595]
We have a monorepo for some microservices and have config something like this:
```yaml
version: 1
update_configs:
- package_manager: "javascript"
  directory: "/path/to/project1"
  update_schedule: "daily"

- package_manager: "javascript"
  directory: "/path/to/project2"
  update_schedule: "daily"

- package_manager: "dotnet:nuget"
  directory: "/path/to/project3"
  update_schedule: "daily"

- package_manager: "dotnet:nuget"
  directory: "/path/to/project4"
  update_schedule: "daily"
```

So if for example Typescript gets updated we end up with two PRs, 1 each for project1 and project2.

Its worse with dotnet because we have common assemblies between the two projects, so if a dependency in one of them changes, we end up with two PRs for the same project.  This obviously resolves and dependabot closes the second one when we merge the first one but it is still extra noise.

Perhaps you could support multiple folders per configuration so they can be easily grouped?
```yaml
version: 1
update_configs:
- package_manager: "javascript"
  directory:
  - "/path/to/project1"
  - "/path/to/project2"
  update_schedule: "daily"

- package_manager: "dotnet:nuget"
  directory: 
  - "/path/to/project3"
  - "/path/to/project4"
  update_schedule: "daily"
```
