### ISSUE TITLE
How to make dependabot use config.yml

### ISSUE THREAD

**Issue by Youssef1313** [dependabot/dependabot-core#1600]
From the "Add repos" page in <https://app.dependabot.com/accounts/{USERNAME}/add>.
I checked the repo, and made sure that the language is correct (.NET) and clicked the "Add selected" button. I'm getting "Repo must contain a .(cs|vb|fs)proj file or a packages.config.".

I understand that this error comes because the root of the repo doesn't have a project file. However, I can't set a specific directory. There are multiple project files in different directories. I've set them all in the config.yml file. How can I make dependabot uses the config.yml file and don't look at the repository root or any specific directory ?

**Comment by feelepxyz** [comment]
@Youssef1313 you should not need to "add repos" when using config files as long as the repository is visible to the Dependabot Preview app. If you've installed it under your personal account you can edit the visible repos from the installations settings page > Dependabot Preview: https://github.com/settings/installations

Once you add the config file with each directory listed as a separate entry under `update_configs` it should all work as expected. Example:

```yml
version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/dir1"
    update_schedule: "daily"
  - package_manager: "dotnet:nuget"
    directory: "/dir2"
    update_schedule: "daily"
```
