### ISSUE TITLE
Ability to inspect specific file?

### ISSUE THREAD

**Issue by babaMar** [dependabot/dependabot-core#1629]
Would be nice being able to configure a specific file to be inspected by dependabot. 

In my repository there's a `setup.py` and a `requirements-dev` folder (with additional dev dependencies only used locally). Even though my configuration looks like

```
version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
```

the bot is also inspecting files in `requirements-dev`, which I would expect to be inspected if my configuration looked rather like:

```version: 1
update_configs:
  - package_manager: "python"
    directory: "/requirements-dev"
    update_schedule: "daily"
```

At the same time, as I'm using `pip-tools`, I'd like dependabot to inspect only the `.ini` file as the `.txt` is automatically generated
