### ISSUE TITLE
npm - some dependencies are not updated

### ISSUE THREAD

**Issue by SuperITMan** [dependabot/dependabot-core#1633]
Probably linked to #1171

In my project, Dependabot is not updating some dependencies for an unknown reason.

Here are the deps without updates by dependabot in my root folder (list provided by `npm-check-updates`):
  - commitizen: ^4.0.0 → ^4.0.3
  - cz-customizable: ^6.0.0 → ^6.2.0
  - prettier: ^1.16.1 → ^1.19.1
  - ng-packagr: ^5.3.0 → ^5.7.1
  - release-it: ^12.2.2 → ^12.4.3 
  - stylelint-config-prettier: ^7.0.0 → ^8.0.1
  - tslint: ^5.11.0 → ^5.20.1
  - tslint-config-prettier: ^1.17.0 → ^1.18.0
  - tslint-sonarts: ^1.8.0 → ^1.9.0

My project is https://github.com/NationalBankBelgium/stark
My dependabot config is the following one:

```yml
---
update_configs:
- automerged_updates:
  - match:
      update_type: in_range
      dependency_type: all
  commit_message:
    :prefix: chore
    :include_scope: true
  directory: "/"
  ignored_updates:
  - match:
      dependency_name: "@angular/*"
      version_requirement: ">= 8"
  - match:
      dependency_name: "@angular-devkit/build-ng-packagr"
      version_requirement: ">= 0.800"
  - match:
      dependency_name: "@compodoc/compodoc"
      version_requirement: ">= 0"
  - match:
      dependency_name: typescript
      version_requirement: ">= 0"
  - match:
      dependency_name: "@types/node"
      version_requirement: ">= 11"
  package_manager: javascript
  update_schedule: live
```

I already clicked multiple times on the "bump" button but no PR is created those deps 😞 

Thanks for your help 😊
