### ISSUE TITLE
Notify Dependabot of a private dependency release takes up to 2h

### ISSUE THREAD

**Issue by miquelmasrieramrf** [dependabot/dependabot-core#1659]
Hi!

at our company, When a new version of a (private) package is published, it takes for Dependabot from 1 minute up to 2 hours to crearte the pull request in the repos using that dependency.

I would like to know if this is normal due to the way we are using Github and Dependabot, or there is something that we are missing.
We have **a lot** of repos in the organization, maybe it is the issue.

config.yml
```yml
version: 1
update_configs:  
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
    automerged_updates:
      - match:
          update_type: "in_range"
    version_requirement_updates: "off"
```

and the requests for updating are like this:
```
POST: https://api.dependabot.com/release_notifications/private
HEADERS:
Authorization Personal <github token>
Content-Type application/json
BODY:
{
  "name": "@<org>/<package_name>",
  "version": "1.0.0-alpha.22848",
  "package-manager": "npm_and_yarn"
}

which returns a 204 without content
```

thanks a lot
