### ISSUE TITLE
npm/yarn: do not update dev dependencies

### ISSUE THREAD

**Issue by lorvent** [dependabot/dependabot-core#1663]
Hello

is there any way to update only main dependencies but not dev dependencies?

often dev packages are being updated continously and i am afraid of bumping their versions as they may break things.

ex: gulp, webpack related packages in package.json

thanks.

**Comment by feelepxyz** [comment]
@lorvent you can configure allowed updates using the config file: https://dependabot.com/docs/config-file/#allowed_updates (only works if you're using [Dependabot Preview app](https://github.com/marketplace/dependabot-preview))

To update all production dependencies:

```
allowed_updates:
  - match:
       dependency_type: "production"
       update_type: "all"
```
