### ISSUE TITLE
Can allowed_updates include version number and wildcard?

### ISSUE THREAD

**Issue by aguibert** [dependabot/dependabot-core#1665]
I work on a project that is currently testing out usage of dependabot ([here is our current config](https://github.com/OpenLiberty/open-liberty/blob/integration/.dependabot/config.yml)).

We are a Java project and have many dependencies, so we need to specify `allowed_updates`. However, we want to be able to specify ranges for the versions we want to look for, such as:
```yml
      - match:
          dependency_name: "org.glassfish:javax.json:1.0.*"
      - match:
          dependency_name: "org.glassfish:javax.json:1.1.*"
```

Our project currently uses `org.glassfish:javax.json:1.0.*` in some places and `org.glassfish:javax.json:1.1.*` in other places, but we'd like to have dependabot scan for updates within these version ranges (e.g. bump from `org.glassfish:javax.json:1.0.1 --> org.glassfish:javax.json:1.0.2`). Would it be possible for dependabot to support this scenario?
