### ISSUE TITLE
Handling multiple dependency files

### ISSUE THREAD

**Issue by DhruvM1994** [dependabot/dependabot-core#1690]
I am trying to use dependabot for a repository consisting of several dependency files (pom.xml, package.json) that are not all located in the root of the repo. 
Is it possible to specify several directories?

**Comment by thepwagner** [comment]
@DhruvM1994 check out https://dependabot.com/docs/config-file/ ; you can provide a configuration file to specify files/paths to check:

```yaml
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
```
