### ISSUE TITLE
Cargo PR Closed Incorrectly

### ISSUE THREAD

**Issue by lucasbrendel** [dependabot/dependabot-core#1740]
2 PR's were opened in my project lucasbrendel/green-thumb-web#100 and lucasbrendel/green-thumb-web#102. There was a 3rd dependency that should also have had a PR but it did not get one. In the Cargo.toml the code was as such:

```toml
[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["handlebars_templates"]
```
Since Dependabot did not open a PR I updated the dep myself and then pushed to master. After the push dependabot did a rebase and then said that since those deps were up to date the PR's could be closed. Which is true in the branch that they were up to date but on master they were still on the old version.s
