### ISSUE TITLE
Major version update for caret version (^3.6.1 suggests 5.1.0)

### ISSUE THREAD

**Issue by theNailz** [dependabot/dependabot-core#1779]
We're using dependabot in a javascript project. Today we got a pull request from Dependabot to upgrade a lib to a new major version, while our `package.json` defines the version `^3.6.1`, which should mean [not to change the most left digit](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004).

`.dependabot/config.yml`:
```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/applications/webapp"
    update_schedule: "weekly"
    target_branch: develop
    default_labels:
      - "dependencies"
```
`package.json`:
```
// devDependencies:
"fuse.js": "^3.6.1",
```

Corresponding log from Dependabot:
```
updater | INFO <job_28821646> Checking if fuse.js 3.6.1 needs updating
  proxy | 2020/04/06 09:04:17 GET https://registry.npmjs.org:443/fuse.js
  proxy | 2020/04/06 09:04:17 200 https://registry.npmjs.org:443/fuse.js
  proxy | 2020/04/06 09:04:18 GET https://registry.npmjs.org:443/fuse.js/5.1.0
  proxy | 2020/04/06 09:04:18 200 https://registry.npmjs.org:443/fuse.js/5.1.0
updater | INFO <job_28821646> Latest version is 5.1.0
  proxy | 2020/04/06 09:04:19 GET https://registry.yarnpkg.com:443/fuse.js
  proxy | 2020/04/06 09:04:19 200 https://registry.yarnpkg.com:443/fuse.js
```

Is this a bug in Dependabot?
