### ISSUE TITLE
Add a `schedule` type of `security-updates-only` so Dependabot only creates PR's for security updates

### ISSUE THREAD

**Issue by v1sion** [dependabot/dependabot-core#1828]
Hey, kudos for the great work.
In the dependabot hosted version (https://app.dependabot.com) I'm able to select PR's on "Only security updates" it would be nice if we could have the same feature here.
Cheers

**Comment by feelepxyz** [comment]
@v1sion it tricky to make this a straight forward option in core as you have to provide all the security advisories yourself when self-hosting dependabot-core. You could achieve the same by checking that the updated versions are fixing a SecurityAdvisory.

**Comment by nikolas** [comment]
@v1sion, I haven't tried this myself yet, but you could try setting `allowed_updates`, and setting update_type to "security". Like this: 

```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
```

From https://dependabot.com/docs/config-file/#allowed_updates
