### ISSUE TITLE
Can't remove old config.yml

### ISSUE THREAD

**Issue by edumco** [dependabot/dependabot-core#1860]
# After updating a failing `config.yml` the old version can not be removed. 

**Package manage/ecosystem**: Docker

**What you expected to see, versus what you actually saw**

Expected behavior: 
- Old config is removed and new configs appear.

Actual behavior: 
- Old config keeps being exhibited

### config.yml

```yml
version: 1
update_configs:
  # Keep Dockerfile up to date, batching pull requests daily
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
```

### log:

```log
  proxy | time="2020-05-14T08:56:59Z" level=info msg="proxy starting" commit=1d28f333720c25e3a515b8fcab112ffba5a05e54
  proxy | 2020/05/14 08:56:59 Listening (:1080)
fetcher | yarn config v1.22.4
fetcher | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
fetcher | Done in 0.03s.
fetcher | warning: parser/current is loading parser/ruby26, which recognizes
fetcher | warning: 2.6.6-compliant syntax, but you are running 2.6.5.
fetcher | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
fetcher | INFO <job_33132771> Starting job processing
  proxy | 2020/05/14 08:57:03 GET https://api.github.com:443/repos/edumco/docker-selenium
  proxy | 2020/05/14 08:57:03 * authenticating github api request
  proxy | 2020/05/14 08:57:04 200 https://api.github.com:443/repos/edumco/docker-selenium
  proxy | 2020/05/14 08:57:04 GET https://api.github.com:443/repos/edumco/docker-selenium/git/refs/heads/master
  proxy | 2020/05/14 08:57:04 * authenticating github api request
  proxy | 2020/05/14 08:57:04 200 https://api.github.com:443/repos/edumco/docker-selenium/git/refs/heads/master
  proxy | 2020/05/14 08:57:04 GET https://api.github.com:443/repos/edumco/docker-selenium/contents/?ref=797cadb0320e43726846a61f79e5f8da1f51f585
  proxy | 2020/05/14 08:57:04 * authenticating github api request
  proxy | 2020/05/14 08:57:04 200 https://api.github.com:443/repos/edumco/docker-selenium/contents/?ref=797cadb0320e43726846a61f79e5f8da1f51f585
fetcher | ERROR <job_33132771> Error during file fetching; aborting
fetcher | INFO <job_33132771> Finished job processing
```
> <https://github.com/edumco/docker-selenium/blob/797cadb0320e43726846a61f79e5f8da1f51f585/.dependabot/config.yml>

### `config.yml`

```yml
version: 1

update_configs:
  - package_manager: "docker"
    directory: "/Hub"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/NodeBase"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/NodeChrome"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/NodeChromeDebug"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/NodeFirefox"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/NodeFirefoxDebug"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/NodeOpera"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/NodeOperaDebug"
    update_schedule: "daily"
```

> <https://github.com/edumco/docker-selenium/blob/master/.dependabot/config.yml>

![Captura de tela de 2020-05-14 18-57-20](https://user-images.githubusercontent.com/21086024/81990081-d0834e80-9614-11ea-83f3-afd1a9001d3b.png)
