### ISSUE TITLE
Feature request: per-package update schedule

### ISSUE THREAD

**Issue by j3parker** [dependabot/dependabot-core#1865]
First - thank you for dependabot! It's been fantastic! I know you're hard at work integrating into GitHub... I'm excited to see what that means! 

Something we've noticed is that it isn't possible to have different update frequencies for different packages in the same package manager.

## Motivation

The C# AWSDK packages update themselves multiple times per day, and are quite granular. It's not uncommon for us to have 10+ of these packages used in a repo. The volume of pull requests that this creates is really annoying.

We'd be happy receiving automatic updates for these packages less frequently. We'd also like to batch them (a feature that's been requested [here](https://github.com/dependabot/dependabot-core/issues/317), [here](https://github.com/dependabot/dependabot-core/issues/1296), and [here](https://github.com/dependabot/dependabot-core/issues/1190).) If that feature existed I think we'd still appreciate finer-grained control over update schedules, though.

## An attempted workaround

Consider this config which attempts to do that with multiple `update_configs`:

```yaml
version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    allowed_updates:
      - match:
          dependency_name: "AWSSDK.*"
    directory: "/"
    update_schedule: weekly
  - package_manager: "dotnet:nuget"
    ignored_updates:
      - match:
          dependency_name: "AWSSDK.*"
    directory: "/"
    update_schedule: live
```

The validator gives this error:

```
The property '#/update_configs/1' is a duplicate. Update configs must have a unique combination of 'package_manager', 'directory', and 'target_branch'
```

This makes some sense; although these `update_config`s appear to be mutually exclusive in general that wouldn't be true, and that's weird.
