### ISSUE TITLE
Version 2 yaml validator doesn't catch duplicated `ignore:` sections.

### ISSUE THREAD

**Issue by georgedorn** [dependabot/dependabot-core#1919]
This validates:
```
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '13:00'
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chromedriver-binary
  ignore:
  - dependency-name: celery
  commit-message:
    prefix: chore
```
But then dependabot happily opens PRs to update chromedriver-binary, as the second `ignore:` clobbers the first.

(I'm now aware of the correct format; this bug report is because the validator didn't catch this.  Also, maybe somebody else searching for why dependabot isn't respecting their 'ignore' statements will find this, too.)
