### ISSUE TITLE
"Dependabot couldn't find a build.gradle for this project" when using a monorepo with no build.gradle in root of repo

### ISSUE THREAD

**Issue by badgerwithagun** [dependabot/dependabot-core#1939]
### Package manage/ecosystem
Gradle
### Manifest contents prior to update
N/A
### Updated dependency
N/A
### What you expected to see, versus what you actually saw
We have a monorepo with just directories at the root, each containing an application. Config file looks like this:
```
version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/common"
    update_schedule: "daily"

  - package_manager: "java:gradle"
    directory: "/app1"
    update_schedule: "daily"

  - package_manager: "java:gradle"
    directory: "/app2"
    update_schedule: "daily"

  - package_manager: "java:gradle"
    directory: "/app3"
    update_schedule: "daily"
```
I would expect this to check and manage dependencies in the four specified directories. However instead Dependabot creates an issue like this:

![Screenshot 2020-06-24 at 16 59 59](https://user-images.githubusercontent.com/6483013/85590242-2566ab80-b63c-11ea-92ac-506432ec6cb8.png)

We **used** to have a build.gradle at the root, and it all worked fine. It just stopped working when that was removed.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid issue?

**Comment by badgerwithagun** [comment]
I'm not sure. We ended up creating a root build.gradle for the monorepo which does nothing other than exist so Dependabot would work, and then got on with other things.

**Comment by jeffwidman** [comment]
Can you try removing it and see if still works or not? It definitely shouldn't need to be there.

**Comment by sconvent** [comment]
I just tried it out and it seems to work.

See for reference: https://github.com/sconvent/dependabot-issue-demonstrator/tree/4805be421d5b173add512c8ef57e19d0f5c16737

There are two Gradle modules and no `build.gradle` at the root folder.
Dependabot config:
```yaml
version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/module1"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/module2"
    schedule:
      interval: "daily"
```
Using `version: 2`, because `version: 1` doesn't work anymore on Github.
Both dependabot logs look good and it also created PRs.

So from my point of view this issue can be closed.
