### ISSUE TITLE
Broken links in PR description for Submodules with periods (eg, `.github.io`)

### ISSUE THREAD

**Issue by Nagarian** [dependabot/dependabot-core#1965]
**Package manage/ecosystem**
Git Submodule
**Updated dependency**

**What you expected to see, versus what you actually saw**
Hi guys, I'm encountering an issue with Dependabot and **Git-submodule**, this submodule have dots in its url and when dependabot create Pull request, links in the description are not generated properfully.

IE: `https://github.com/optc-db/optc-db/compare/74a20cd0c1b8ca8c8a6934fc9bab9ac9ad24c21d...3208aa36af5ff683640b53af2439a0f81adeb019` instead of `https://github.com/optc-db/optc-db.github.io/compare/74a20cd0c1b8ca8c8a6934fc9bab9ac9ad24c21d...3208aa36af5ff683640b53af2439a0f81adeb019`

Thanks for your help !

**Images of the diff or a link to the PR, issue or logs**
<https://github.com/Nagarian/optc-box-manager/pull/18>

`.gitmodules`
```
[submodule "src/optcdb"]
	path = src/optcdb
	url = https://github.com/optc-db/optc-db.github.io.git
```

`.github\dependabot.yml`
```yaml
version: 2
updates:
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "08:00"
      timezone: "Europe/Paris"
```
