### ISSUE TITLE
Make semicolon in commit message prefix optional

### ISSUE THREAD

**Issue by markcellus** [dependabot/dependabot-core#1975]
Our current setup requires that there be no semicolon after the prefix specified in `update_configs.commit_message.prefix` config option. Is it possible to make the semicolon optional? Thanks!

**Comment by avaly** [comment]
I would also like to be able to customize this in the commit message prefix. Our team is using a format like `[SECTION][type] Commit title`. And all Dependabot commits look like `[SECTION][type]: Commit title`.

**Comment by flovogt** [comment]
I just came across this one. @avaly You can achieve this scenario by adding a whitespace after the `[SECTION][type]`.

```yaml
  versioning-strategy: increase
  commit-message:
    prefix: "[SECTION][type] "
```
