### ISSUE TITLE
ignored_updates with Go modules either not ignoring or needs more documentation

### ISSUE THREAD

**Issue by stone-z** [dependabot/dependabot-core#1992]
This could either be a bug report or just a request for more docs depending on the outcome.

In [this repo](https://github.com/giantswarm/kvm-operator) I am trying to ignore all dependencies from `k8s.io/` which are above a certain version `>= 0.17.0` as I only want patch updates within the 0.16 minor version.

I think it isn't properly matching due to the special characters in the name. I'm not sure what exactly to expect from the `dependency_name` and `version_requirement` fields -- are these proper regular expressions, or is there some limited syntax which dependabot supports?

I've tried this two ways with no success:
```
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "master"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: "k8s.io/*"
          version_requirement: ">=0.17.0"
```

and 

```
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "master"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: |
            k8s\.io\/*
          version_requirement: ">=0.17.0"
```

Can you shed some light here?

**Comment by stone-z** [comment]
Matching with a single wildcard character seems to be working as expected these days, so I will close this

**Comment by stone-z** [comment]
Re-opening this because we're still having difficulties with `ignore` behavior using Go modules.

As before, we're trying to ignore certain version ranges of `k8s.io` dependencies. We are using the config below, which should restrict the dependency ranges on two target branches: `master` and `release-v1.19.x`. The behavior works as expected on the `master` branch, but we receive no updates for the `1.19` branch.

Here is the configuration we're using in [this repository](https://github.com/giantswarm/hyperkube):
```
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: release-v1.19.x
  ignore:
  - dependency-name: k8s.io/*
    versions:
    - ">=0.20.0"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: k8s.io/*
    versions:
    - ">=0.21.0"
```

We see this in the logs for a run on the `1.19` branch:
```
updater | INFO <job_80302903> Updating k8s.io/kubectl from 0.19.4 to 0.20.1
```

No PR is opened for this update to 0.20.1 (which is the desired behavior because this version is ignored).

However we _also_ do not receive PRs for versions 0.19.5 or 0.19.6, which we should receive.

We would appreciate any guidance on the correct syntax in this situation.
