### ISSUE TITLE
Support "*" parameter in folder paths

### ISSUE THREAD

**Issue by petergrau** [dependabot/dependabot-core#1994]
We have several plugins in one repo that all have their own `package.json`. We would like to define one directory path that catches all of them - something like: 
``` /libs/*/ ```
That should include then all `package.json` of the libs without having to define an entry for each of them following all the same ruleset.

**Comment by maneetgoyal** [comment]
Will be great to have.

Using `lerna` with `yarn workspaces`. Here's my `dependabot.yml`:

```
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
```

When dependabot creates a PR for updating the dependencies that present in only the child packages `root/packages/**/abc`, `root/packages/**/def`, etc., it only updates the `yarn.lock`. Would be great if it updates the `package.json` of the child packages as well (not just the root level `package.json`).
