### ISSUE TITLE
Post upgrade script

### ISSUE THREAD

**Issue by mockdeep** [dependabot/dependabot-core#2004]
I'd love for it to be possible to run some command after an upgrade. For example, running `yarn deduplicate` or `rubocop --auto-gen-config`. Right now our CI fails on these, so I end up pulling down the branch, running the commands manually, and force pushing back up.

**Comment by piotrd** [comment]
> Interesting idea, could you perhaps leverage an Action to automate this instead of building it into dependabot?

@jurre can you please elaborate how can I trigger an action on dependabot commits?

**Comment by jurre** [comment]
Something like this should work:

```yaml
jobs:
  some-job:
    name: Running something on Dependabot breanches
    runs-on: ubuntu-latest
    if: startsWith(github.ref, dependabot/bundler)
    steps:
      # ...
```

A caveat of this approach currently is that dependabot will no longer automatically rebase those branches, because they have been changed.

**Comment by devinmatte** [comment]
This feature would be great. The actions job is an okay workaround but a form of this that supports dependabot rebases would be fantastic

**Comment by StevenACoffman** [comment]
I found [this example](https://github.com/crazy-max/artifactory-cleanup/commit/a88eb5eb5c13235c92be4c9b344410ea381f54ec#diff-9c93e82f4489fa464e962839fc18bb3849015882259535094345145238f90610):
```
name: vendor

on:
  pull_request_target:
    paths:
      - '.github/workflows/vendor.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      -
        name: Set up Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Vendor update
        uses: docker/bake-action@v1
        with:
          targets: vendor-update
      -
        name: Commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit --message "Fix go modules"
            git push
          fi
```
