### ISSUE TITLE
dependabot doesn't check other branches

### ISSUE THREAD

**Issue by thasmo** [dependabot/dependabot-core#2012]
I've added a dependabot config to another branch:

```yml
version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    version_requirement_updates: 'widen_ranges'
    target_branch: 'version/1'
    allowed_updates:
      - match:
          update_type: 'all'
          dependency_type: 'direct'
```

I'm not getting any PRs for the branch `version/1`, only for master.

How do I get PRs for other branches?
