### ISSUE TITLE
Bundler Using Incorrect Version

### ISSUE THREAD

**Issue by nbibler** [dependabot/dependabot-core#2018]
I have a repository with a Gemfile and Gemfile.lock in it. The Gemfile.lock is generated by Bundler and contains the `BUNDLED WITH` information at the bottom:

```
BUNDLED WITH
   2.1.4
```

However, when Dependabot checks the repository, I'm getting `Dependabot can't resolve your Ruby dependency files` issues with:

```
Bundler::VersionConflict with message: Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    license_finder (~> 6.0) was resolved to 6.1.0, which depends on
      bundler (~> 2.1.0)

    rails (~> 6.0.0) was resolved to 6.0.2.1, which depends on
      bundler (>= 1.3.0)

  Current Bundler version:
    bundler (1.17.3)
```

Seemingly, the Dependabot runner is executing Bundler at version `1.17.3`, even though the Gemfile.lock identifies `2.1.4` as the version used to create the lock. That `BUNDLED WITH` [should be enough](https://bundler.io/guides/bundler_2_upgrade.html) for Bundler to know to use a 2.x version when executing, but seemingly it's not?

Is there a way to have Dependabot run using Bundler 2.x instead of 1.x that isn't documented somewhere?

**Comment by dpep** [comment]
any update or ways we can contribute to the Bundler 2 upgrade effort?

**Comment by feelepxyz** [comment]
👋  we've just launched support for bundler v2 in Dependabot Version and Security Updates. This should just work if your lockfile has been `BUNDLED WITH 2.x`. Let us know if this is working for you.

Dependabot Preview support is coming next week.

**Comment by jurre** [comment]
This should be resolved now 🎉 please let us know if you run into things

**Comment by dpep** [comment]
it's looking good on my end.  thanks for pushing the upgrade through!  🎉  🚀

**Comment by csalvato** [comment]
Hm I am seeing an issue using Bundler 2.1.4:

<img width="932" alt="Screen Shot 2021-04-22 at 4 51 18 PM" src="https://user-images.githubusercontent.com/1158152/115794283-f79ce100-a38a-11eb-859e-67e008fe5ad6.png">

It looks like Dependabot is using Bunder 2.2.15, but our lockfile was bundled with 2.1.4.

Upgrading to 2.2.15 will require a lift from our team.

Is there a way to  get this to work with Bundler 2.1.4?

Here's our `dependabot.yml`:

```yml
version: 2
registries:
  contribsys: # Define access for contribsys registry
    type: rubygems-server
    url: https://enterprise.contribsys.com/
    username: ${{secrets.SIDEKIQ_USERNAME}}
    password: ${{secrets.SIDEKIQ_PASSWORD}}
updates:
  - package-ecosystem: 'bundler'
    insecure-external-code-execution: allow
    registries:
      - contribsys
    open-pull-requests-limit: 100
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'dependabot'
      - 'ruby'

```
