### ISSUE TITLE
ignored_updates is not working when update is avaialble for multiple modules

### ISSUE THREAD

**Issue by alexey-anufriev** [dependabot/dependabot-core#2029]
In my project have two modules:
- hibernate-proxy-support
- hibernate-proxy-support-test

In both of them I have a dependency `hibernate-core`.
In the first module the version is 5.0.0 as I need to support the earliest version.
But in the second one I have 5.4.12 (for some time it was the latest), it is ok for testing.

As soon as I pluggen dependabot it suggested me to upgrade 5.0.0 to the latest.
Latest was at that time - 5.4.12. But I wanted to keep this version frozen.
So I have added the following config:
```
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "java:maven"
    directory: "/hibernate-proxy-support"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "*hibernate-core*"
```
And it was fine, PR was automatically closed.

But a couple of days ago the newer `hibernate-core` was release - 5.4.14.
And now I have a PR that contains an update for my dependency in both modules.

So `ignored_updates` does not work.
