### ISSUE TITLE
Dependabot should automerge if all *mandatory* pull-request checks are passing

### ISSUE THREAD

**Issue by oscard0m** [dependabot/dependabot-core#2036]
When using `automerged_updates` option, dependabot is not able to merge if a *non-mandatory* check does not pass. I suggest dependabot should be able to merge if all mandatory checks have passed (or at least have the option at `config.yml` level)

Example Pull Request:

![image](https://user-images.githubusercontent.com/2574275/74024614-8bf76f80-49a2-11ea-9976-08fe46ab2cc6.png)

Lint check is a *non-mandatory* check on that repository

This is the `config.yml` file being used if it adds more info:
```
version: 1
update_configs:  
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
    automerged_updates:
      - match:
          update_type: "in_range"
    version_requirement_updates: "off"
    commit_message:
      prefix: "chore"
```
