### ISSUE TITLE
[feature] Support monitoring of several branches

### ISSUE THREAD

**Issue by davidkarlsen** [dependabot/dependabot-core#2159]
It would be good if dependabot could support several branches - today it only monitors the default branch.
It's quite common to have a branch per tag for docker images - for instance `java8`, `java11`, `java12`, or several `release/*` branches.

To avoid scanning all kinds of short-lived branches, you could require a branch regex / set a limit or the likes.

**Comment by infin8x** [comment]
Unfortunately we don't expect to change Dependabot to support configuration files on multiple branches.

**Comment by skjnldsv** [comment]
@infin8x what about `target-branch` supporting arrays instead of just string?
So we can avoid duplicate code?

```yml
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  # Only allow updates to the lockfile
  versioning-strategy: lockfile-only
  target-branch:
  - stable19
  - stable18
  - stable17
  labels:
  - 3. to review
  - "feature: dependencies"
```

**Comment by AraHaan** [comment]
Is this supported on the github native dependabot where I have the following:
- main (long living branch which is the default that is for a specific bleeding edge version)
- releases/X.Y (long living branch for a specific release for servicing updates, which includes dependency security updates) (can have multiple branches of these and each for specific major and minor releases)

As such I would need such a thing to benefit from being able to have the bleeding edge support the next major version of those dependencies, but each release updating to the latest patch version of the major one they are currently using.

**Comment by AraHaan** [comment]
I managed to do something manually (and that is duplicating the config values in the dependabot yml file on the default branch and then setting the duplicate configs to monitor a specific branch). It however, does feel like a hack though.

**Comment by sebnitu** [comment]
Has anyone gotten this to work? I'm still struggling to get dependabot to open PR dep bumps on multiple branches. Here's what my config looks like, but it's only opening PRs for main:

```
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    target-branch: "main"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    target-branch: "next"
```
