### ISSUE TITLE
Per dependency bump schedule

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/dependabot-core#2165]
I'm not sure if there is already an open issue/backlog item for this, but it would be nice to be able to set bump schedules on a per-dependency basis.

For example, I typically want daily updates to my repositories so I can get the latest packages asap, except there are a few dependencies that release daily that I don't want to have to review and merge every day. For these few dependencies (usually AWS packages), I would want them to be bumped weekly or even monthly.

Right now I have this repository set to bump weekly because of those frequently updated packages, so I get a big dump of everything on Mondays. It would be nice to change it to daily for all packages except the frequently updated ones.

Thanks for all your work on dependabot!

**Comment by RevolutionTech** [comment]
> ...we publish a public npm package that is then consumed by the various app repos that make up our web presence. Ideally we want our consumers to be notified of our releases ASAP as we want people to keep up to date...
> 
> At the same time we appreciate our developer buddies would prefer a weekly cadence for other updates so they're not overwhelmed.

We have a very similar use case, although just wanted to add that we use Dependabot to update dependencies in the package that we publish and then use Dependabot in the projects that use this package.

Since we update dependencies monthly, the updates for the package and the updates for the projects come at the same time. This really means that unless we manually re-execute Dependabot on all of the projects after updating the package, all of the projects' dependencies from the package will be consistently one month old.

Having the ability to mark our package to be updated as live would be great because then we could update the package first, push out a new version, and then the latest version of the package could be merged in along with the remaining Dependabot PRs for that month without manually running Dependabot on every project.

**Comment by tsauvajon** [comment]
This is also a blocker for us. We want most dependencies to be as fresh as possible, but we have dependencies that are deployed daily, making Dependabot create an insane amount of PRs.

I tried a similar approach as others in this issue or one of the duplicates:
```yml
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "github.com/something/[...]"
      - match:
          dependency_name: "github.com/aws/aws-sdk-go"
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "weekly"
```
