### ISSUE TITLE
Monorepo ignore local dependency not working

### ISSUE THREAD

**Issue by yss14** [dependabot/dependabot-core#2167]
I'm currently running dependabot on a lerne-managed monorepo. This week, I added a new package `cassandra-schema-builder` to the monorepo which is required by the `projects/backend` package. Since none of the packages are released to npm yet, I received a message from dependabot 

```
Error whilst updating type-graphql in /projects/backend/package-lock.json:
404 Not Found - GET https://registry.npmjs.org/cassandra-schema-builder - Not found
```

Now, I'm trying to tell dependabot to ignore this package, since lerna is managing the linking and later the updating of this dependency. However, with the following config I still get the error message above.

```
version: 1

update_configs:
  - package_manager: "javascript"
    directory: "./"
    update_schedule: "live"
    
    ignored_updates:
      - match:
          dependency_name: "cassandra-schema-builder"

    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
```

The repo is public and can be found [here](https://github.com/yss14/musicshare).
