### ISSUE TITLE
Support for bumping docker containers inside azure-pipelines.yml?

### ISSUE THREAD

**Issue by njsmith** [dependabot/dependabot-core#2194]
Azure Pipelines has an interesting feature where the azure-pipelines.yml file can name a container to use for running tests: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azdevops&tabs=yaml

It would be neat if dependabot could bump these container tags, like it can `FROM` lines.

From the doc above, there seem to be a few different variants:

```yaml
container: <container tag>

containerImage: <container tag>

container: <arbitrary string>
  image: <container tag>
  endpoint: <registry url>
```
