### ISSUE TITLE
[Feature request] Opt out minor and patch versions

### ISSUE THREAD

**Issue by bustikiller** [dependabot/dependabot-core#2219]
For organizations with many projects sometimes it is hard to keep track of all the dependency updates. I would like to get only updates for major & security releases (opt-out from minor and patch versions), configurable per project.

**Comment by czerwinskilukasz1** [comment]
I would love to opt out from patch versions too.
What's the priority of this issue?

**Comment by stephenhebert** [comment]
Please 🙏

**Comment by pimjansen** [comment]
This would be a real great way to keep track on our dependencies. At this point there is no way to auto update patches as far as im concerned? I can only update security issues there:

```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "security"

  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "security"
```

I agree that the `semver:<type>` pattern would be good improvement. This way people can still opt-in for their security updates and decide if they want to bump patches / minors or majors on their own liking.

**Comment by simkimsia** [comment]
This is my dependabot yml

```yml
version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "django"
        # For Django
        versions: ["3.x"]
```

I have followed the convention here https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#ignore

but it's not working.

![image](https://user-images.githubusercontent.com/245021/93429131-3cdbca80-f8f3-11ea-8ea2-ace894f58d00.png)

What did I do wrong?

**Comment by PippoRaimondi** [comment]
Is anyone working on this? having PRs for minor versions creates a lot of noise, there should be an option configure this..

**Comment by PippoRaimondi** [comment]
Doesn't seem like anyone is working on it... I will have a look and see how far I can get adding this feature...

**Comment by Nokel81** [comment]
@PippoRaimondi How i it going? Do you need any help? (Though TBH I would like the opposite, namely ignore major version changes)

**Comment by raisonon** [comment]
This GitHub Action has automerge options for patch, minor and major -- is this the answer everyone on this thread has been waiting for or am I missing something?

https://github.com/marketplace/actions/dependabot-auto-merge

**Comment by Nokel81** [comment]
No not auto merge, I don't want the PRs made for `major` versions at all.

**Comment by srgustafson8** [comment]
Just adding my voice to this - aws-sdk-go (in my case) gets a new patch version every day, which is annoying and unnescessary. Ideally I would be able to say something like `ignore_version: ["semver:patch"]` or any other combination and dependabot would only raise a PR when there's a minor version bump. Saving me commenting _ignore this_ every time

**Comment by brcarp** [comment]
#2016 was closed as a duplicate of this one, which is all well and good, but then I want to voice my support here for this issue, just to add some numbers to the board (and also to qualify as a participant so that I can receive updates if and when any progress is made on this feature request).

FWIW I'm both interested in tuning down path level but also tuning up minor versions, separately from major versions which are also useful to isolate from a knob-turning perspective. There are different use cases for each, and no particular one outshines the others in its usefulness. user configurability across all combinations is the way to go here.

**Comment by asciimike** [comment]
I've been consolidating issues because this feature is getting prioritized and we'll be working on it this quarter 😄 

I'll be popping back in here to get some additional feedback as we're thinking through how this should work (I do expect that we'll allow for opting out of any/all of major/minor/patch, but there are some fun sticky wickets around "what about ecosystems that don't use semver," "what about all the people who are appending `-alpha` to their versions," or "should this be per-package or apply to all packages in an ecosystem").

**Comment by pimjansen** [comment]
> I've been consolidating issues because this feature is getting prioritized and we'll be working on it this quarter 😄 
> 
> 
> 
> I'll be popping back in here to get some additional feedback as we're thinking through how this should work (I do expect that we'll allow for opting out of any/all of major/minor/patch, but there are some fun sticky wickets around "what about ecosystems that don't use semver," "what about all the people who are appending `-alpha` to their versions," or "should this be per-package or apply to all packages in an ecosystem").

Well i think a statement should be made to allow types A or B. Supporting all options wont really work i guess. But without semver it would be pretty difficult to guarantee compatibility right?

Your statement, what about alpha and rcs, should these be handled just like the patch?

So 1.0.0-alpha1 could patch to 1.0.0-alpha2 or maybe even to a stable at that point?

**Comment by asciimike** [comment]
`-alpha` and the like are probably the worst examples--today I encountered a customer issue with a version that looked like `major.minor.patch+zstd.major.minor.patch`. Ecosystems (and even big packages within an ecosystem) have different standards. The most annoying to deal with here is probably going to be dates/timestamps as versions (what does it mean to ignore "patch" updates on a date?), but I'm confident we'll all be able to come up with something good.

We'll definitely be reaching out here to gather more feedback on what people expect, and we'll make sure to let folks know what the plan is when it's ready for consumption to ensure needs are being met.

**Comment by pimjansen** [comment]
Your are right but i think the spec of semver is pretty clear right? Would it be a way to generate seperate parsers for example?

Like add a config as semver:patch would match it only for a semver structure. This way there are a dozen of options and you dont bind the solution strictly to a single implementation

**Comment by asciimike** [comment]
Grabbed some data on the SEMVER question that I figured folks might find interesting.

Common SEMVER-adjacent (allowed in SEMVER, though more than just `major.minor.patch`) categories include:
 - `major.minor.patch.Final|RELEASE|other_number` (`1.2.3-alpha.4` is also common-ish)
 - `major.minor-jre` (or just `major.minor`, or just `major`)

Non-SEMVER looks like:
 - `YYYY.version` (e.g. `2019.5`)
 - Commit hashes (e.g. `7e64906`)
 - `release_name-datestamp` (e.g. `buster-20210208`, mostly for what look like docker images)
 - Words like `RELEASE` or `LATEST`

Overall 96%+ match some SEMVER-like construct, while the remaining < 4% don't (note that the latter is being overcounted, since my query counted `major.minor` and `major` in the latter category--I was a bit lazy with my regex writing).

I think we'll be pretty safe sticking to SEMVER, with `docker` being the main exception.

**Comment by asciimike** [comment]
First round of config file options that we'd like feedback on. I've provided emoji for you to "vote" with, though feel free to comment back with other proposed syntaxes or desired clarifications. Our goal here is to separate version updates and security updates to allow for opting out of them individually, vs trying to do both with the same SEMVER\ syntax (e.g. you may want to ignore patches, but not for security updates).

_Note: we're probably not going to immediately implement opting out of security updates, but it is something we'd like to consider in the design of the config._

## The options

### Option 1: re-use `versions` (vote by reacting with the 🎉  emoji)

Example: ignoring patch updates on `lodash`:

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    - dependency-name: "lodash"
      versions: ["version-update:semver-patch"]
```

Example: ignoring low severity security warnings on `lodash`:

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    - dependency-name: "lodash"
      versions: ["security-update:severity-low"]
```

Example: combining updates, e.g. only give me critical severity alerts and minor updates for `lodash`:

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    - dependency-name: "lodash"
      versions: ["security-update:severity-low", "security-update:severity-moderate", "security-update:severity-high", "version-update:semver-patch", "version-update:semver-major"]
```

Personally I think that it's potentially a little weird that `versions` contains things that aren't versions or can't really "be" versions (e.g. `severity-low`), but the array syntax works well for large groups

### Option 2: add `update-type` to `ignore` (vote by reacting with the 🚀  emoji)

Example: ignoring patch updates on `lodash`:

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    - dependency-name: "lodash"
      update-type: "version-update:semver-patch"
```

Example: ignoring low severity security warnings on `lodash`:

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    - dependency-name: "lodash"
      update-type: "security-update:severity-low"
```

Example: combining updates, e.g. only give me critical severity alerts and minor updates for `lodash`:

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    - dependency-name: "lodash"
      update-type: "security-update:severity-low"
    - dependency-name: "lodash"
      update-type: "security-update:severity-moderate"
    - dependency-name: "lodash"
      update-type: "security-update:severity-high"
    - dependency-name: "lodash"
      update-type: "version-update:semver-patch"
    - dependency-name: "lodash"
      update-type: "version-update:semver-major"
```

I think that the single `update-type` string makes opting out of multiple types painful. We could potentially make it accept an array (or implement it as an array named `update-types`). The question here would be, what happens if you specify an ignore `version` and an `update-type`?

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    - dependency-name: "lodash"
      versions: ["4.x.x"]
      update-type: "version-update:semver-patch"
```

Should this be allowed? Would it be the same with `update-type: "security-update:severity-low"`? What about `update-type: "version-update:semver-major"`?

## Additional notes

As of right now we're not planning on adding this functionality to `allow` (though it is tracked in #3479), since I think it would be weird to say things like `allow: ... semver-patch` because those are already allowed by default, so `ignore` feels like the right place for them. Potentially `allow`ing something means that everything else gets ignored (which is effectively how it is today: an explicit `allow` is an implicit `ignore`).

I think there is also a meta question around, "do we need to include `security-update:...` and `version-update:...` or is it obvious to you all that `semver:major` would only apply to version updates and `severity:low` would only apply to security updates?

**Comment by Nokel81** [comment]
@asciimike Would I be able to propose a middle ground. An array like syntax (similar to option 1) but with a new field, say `"update-types"`. I see this as the best of both worlds since I agree with you that the concept "ignore security-update:severity-low" isn't really a "version".

**Comment by asciimike** [comment]
@Nokel81 that's discussed at the bottom of option 2, and it's totally possible.

**Comment by mairaw** [comment]
I'd like to see a config option where I opt out of patches for any package.

**Comment by Nokel81** [comment]
Ah sorry, I missed that. I think it would be simpler if ignoring both `versions` and `update-type` were mutually exclusive since if you update to version 5 manually that option is now ignored and you are back to allowing `major` updates (or something like that).

**Comment by mairaw** [comment]
Gotcha! Yeah, using `*` for dependency-name works for me.

**Comment by pimjansen** [comment]
Yeah looks solid. Strictly with semver i could set this up as daily job to update my full application to allow all except majors which according to semver are not backwards compatible.

Though its always tricky where not everyone does this strictly, spec wise is fine.

**Comment by asciimike** [comment]
Thanks everyone for the feedback, it's much appreciated and been incorporated! Here's where we've landed:

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    # ignore all patch versions
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
    # ignore major version updates to express, will also ignore patch updates since express is in "*" above
    - dependency-name: "express"
      update-types: ["version-update:semver-major"]
```

Basically, ignore conditions are additive and may apply to multiple dependencies in an ecosystem.

Another good example showing how `versions` plays with `update-types`:

```yaml
version: 2
updates:
 - package-ecosystem: npm
   directory: "/"
   ignore:
    # ignore all 4.x updates as well as all patch updates, so only get minor updates for 3.x
    - dependency-name: "lodash"
      versions: ["4.x"]
      update-types: ["version-update:semver-patch"]
```

We're not planning on adding `security-update:severity-*` at this time, but I'll open another issue to track it when we're closer.

Please keep the feedback coming!

**Comment by asciimike** [comment]
Even though we won't be including `security-update:severity-*` I wanted to test the naming of `version-update:semver-*` with this group.

We wanted to have these strings convey:
 - what type of update the ignore condition applies to (version or security)
 - within the update type, what field(s) were we looking at (e.g. `semver`, `severity`)
 - the value of the chosen field to ignore (e.g. `major`, `critical`)

I think the potential confusion with just using `semver:patch` is that (potentially, but likely) we'd still allow security updates with patch version bumps, which might be confusing to folks who thought they had fully opted out of patch updates.

Would `semver:patch` be clear enough to folks on this thread that they ONLY apply to version updates (similarly, would `severity:low` do the same for security updates)?

**Comment by mairaw** [comment]
If I'm understanding your question correctly @asciimike, you're saying that if I say I want to exclude patches but then I still allow all security update levels, that I'd be getting that patch update? That would be the behavior I'd want.

**Comment by asciimike** [comment]
@mairaw, yes, if all you did was exclude `semver:patch` we'd still send security updates, including `patch` updates. The potential confusion is that by default all security update severities will be allowed and can't be ignored, until we add that functionality.

**Comment by revolter** [comment]
I personally prefer the longer, more verbose versions, as I think that they're clearer for anyone. Meaning, `version-update:semver-patch` instead of only `semver:patch`. Also, if a different versioning system will be supported in the future, they're all be under the same `version-update` prefix.

**Comment by brcarp** [comment]
@asciimike Would the new format allow for different `semver` filters to be applied to the same package ecosystem on different schedules? One of the things we were hoping for was to check for major/minor version releases and patch releases on different schedules, where one could be `monthly` and the other `weekly`. That way different groups of updates could be given different priority/frequency depending on what kind of maintainer resources were available and how frequently they would want to engage with updates.

**Comment by asciimike** [comment]
@brcarp it's something we've talked about internally (especially setting `dependency_type: production | development` to different schedules). We've decided to not release that in the first version of this feature, and instead consider it as a follow up pending feedback (e.g. if the majority of folks just want to shut up one dependency, they wouldn't need this, but if folks are doing the dev/prod split, they probably would). Your vote has been counted for it though!

**Comment by mjgallag** [comment]
@asciimike how do we tell when it's [generally available](https://github.com/mjgallag/runhub-app-template/runs/2469168069)?

**Comment by asciimike** [comment]
@mjgallag (and other interested folks): please [sign up here](https://forms.gle/7GRPVW9HAgqwjyjBA) for the beta of this feature. I'll email folks who sign up with some beta docs when it's ready to go (should be fairly soon).

GA releases are typically published to the [GitHub Changelog](https://github.blog/changelog/) and are tweeted by [GHchangelog](https://twitter.com/GHchangelog). I'll also post the changelog post here, so folks are aware :)

**Comment by asciimike** [comment]
Hey folks, we've shipped this feature into public beta 🚀 

You can [follow the docs](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#ignore) to enable it.

Thanks to all the beta testers who gave us valuable feedback!

**Comment by brcarp** [comment]
> Thanks everyone for the feedback, it's much appreciated and been incorporated! Here's where we've landed

@asciimike In looking at the doc, does this mean that for combining `update-types` you landed on this syntax?
```
   ignore:
    - dependency-name: "lodash"
      update-types: ["version-update:semver-patch", "version-update:semver-major"]
```

**Comment by asciimike** [comment]
@brcarp yes, that's correct

**Comment by limonte** [comment]
@asciimike I can't fugure out from the docs, how do I "For all packages, exclude everything except major releases". Could you advice me on that?

**Comment by brcarp** [comment]
> @asciimike I can't fugure out from the docs, how do I "For all packages, exclude everything except major releases". Could you advice me on that?

I think you would list patch and minor as ignored like this:
```
["version-update:semver-patch", "version-update:semver-minor"]
```

I think security updates are still included however?

**Comment by asciimike** [comment]
@limonte @brcarp is correct in the above

**Comment by pimjansen** [comment]
Will try this out for Azure Devops. Had a difficult implementation before though so curious how it will go

**Comment by limonte** [comment]
Might be a stupid question, but what does "ignored" mean? In good old days when Greenkeeper was alive, it was working this way:

- create a PR for every major release
- create and build branch for every release
- create a PR for patch/minor release only if build from the previous step failed

This behavior is perfect in my opinion. Is it possible to achieve the same with dependabot?

**Comment by Nokel81** [comment]
@limonte From my understanding it means that dependabot will not create the PRs for those minor/patch versions (if you ignore them).

**Comment by asciimike** [comment]
We don't currently have away to conditionally unignore based on a build result, this is currently all or nothing. If you only want to receive major, you can ignore minor and patch, and then manually unignore if major fails (or build an action to commit removing minor).

**Comment by brcarp** [comment]
> This behavior is perfect in my opinion, because it's based on two assumptions:
> * there are always breaking changes in major releases, so developers' attention to new major releases is always needed
> * there should be no breaking changes in patch/minor releases and developers' attention is needed only if CI build is failing (e.g. there might be accidental breaking changes in patch/minor releases)

I have similar feelings about the differences between major and minor/patch releases, but my preference is a bit let complicated than that from a workflow perspective: I'd like to have two different schedules for the same `package-ecosystem` with different `update-types` so that I can have one update-type run on the `weekly` schedule and the other run on the `monthly` schedule, which better optimizes the opportunities to review major and minor updates on a periodic basis. My understanding is that this isn't possible at the moment because you can only have one update rule for a given `package-ecosystem`. (I haven't tested that specifically but it's the assumption I'm making based on the docs.)

**Comment by asciimike** [comment]
#1778 is the feature request you're seeking, and it's something we've thought about in the course of this, but haven't scheduled yet.

**Comment by asciimike** [comment]
https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/ is the official release of this feature (though you all have been using it all week ;)

I'm going to close this issue--if you've got additional issues or feature requests, please file the appropriate issue on this repo and we'll get to it soon!

**Comment by skjnldsv** [comment]
Now this: https://github.com/dependabot/dependabot-core/issues/2511
So we can all have proper configs on big github projects with multiple stable branches and get updates for patch dependencies :pray:

**Comment by pimjansen** [comment]
Im using this feature now but im getting "weird" responses. I have a very basic configuration overall to only allow patches on semver:

```yml
version: 2
updates:
  - package-ecosystem: composer
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
```

The thing is that im receiving these PRs:
- Bump laminas/laminas-soap from 2.8.0 to 2.9.0
- Bump sensio/framework-extra-bundle from 5.6.1 to 6.1.4
- etc

Below is the log output.
```
Targeting 'develop' branch under '/' directory
Using 'bump_versions_if_necessary' versioning strategy
Parsing dependencies information
Checking if doctrine/migrations 2.2.1 needs updating
Requirements to unlock own
Updating doctrine/migrations from 2.2.1 to 3.1.2
Submitting doctrine/migrations pull request for creation. Done (PR #5585).
Checking if laminas/laminas-soap 2.8.0 needs updating
Requirements to unlock own
Updating laminas/laminas-soap from 2.8.0 to 2.9.0
Submitting laminas/laminas-soap pull request for creation. Done (PR #5586).
Checking if sensio/framework-extra-bundle 5.6.1 needs updating
Requirements to unlock own
Updating sensio/framework-extra-bundle from 5.6.1 to 6.1.4
Submitting sensio/framework-extra-bundle pull request for creation. Done (PR #5587).
Checking if symfony/apache-pack 1.0.1 needs updating
No update needed for symfony/apache-pack 1.0.1
Checking if symfony/asset 5.1.7 needs updating
```

Is there anything that im missing here or?

Maybe @asciimike knows? Is this due the fact im using both major and minor?
