### ISSUE TITLE
Add support for updating gradle wrapper

### ISSUE THREAD

**Issue by rahulsom** [dependabot/dependabot-core#2223]
Hi!

This is an amazing way to manage dependencies.

It would be awesome if it could also send PRs for gradle wrapper updates. 
Typically this involves 

1. Find the latest version of gradle published at 

```
https://api.github.com/repos/gradle/gradle/releases/latest
```

2. Run 

```
./gradlew wrapper --gradle-version ${VERSION} --distribution-type all
```

3. Send a PR.

Some projects using maven also use a wrapper - https://github.com/takari/maven-wrapper but that can be a separate issue.

**Comment by FireMasterK** [comment]
Any progress on this?

**Comment by robstoll** [comment]
@infin8x do you have some pointers where this needs to be implemented, I would still take a look

**Comment by infin8x** [comment]
@robstoll I don't at the moment, sorry. We're a bit swamped at the moment and can't commit to giving your PR the requisite attention.

**Comment by robstoll** [comment]
@infin8x I don't need a commitment, just a pointer where I should start looking. There is a lot of code and I don't have time either, so if I spend time helping you out then I want to do it as efficiently as possible. I think it would be enough, if you can point me to the file where the analysis for updates takes place. Thanks in advance

**Comment by JavierSegoviaCordoba** [comment]
Poke, should be great someone who knows the project can help @robstoll to get this working.

**Comment by sehenst** [comment]
> Poke, should be great someone who knows the project can help @robstoll to get this working.

@asciimike ?

**Comment by jameswald** [comment]
I have been using https://github.com/marketplace/actions/update-gradle-wrapper-action to implement this feature. Gets the job done for now although it would be better if this were supported by dependabot.

**Comment by asciimike** [comment]
https://github.com/dependabot/dependabot-core#dependabot-package-manager is a good place to start, as it has a good explanation of how the various pieces fit together, and links to READMEs on how to implement the required methods.

https://github.com/dependabot/dependabot-core/tree/main/gradle/lib/dependabot/gradle is probably where most of the additions will happen. I'd expect you'd have to modify the update checker as well as the file updater.

**Comment by robstoll** [comment]
I am afraid,but I don't have the time any more to look at it but it hopefully helps someone else

**Comment by IdiosApps** [comment]
I've been reading about this and have opened https://github.com/IdiosApps/dependabot-gradlewrapper-test. It gives some context/summary of the problem, and a few gradle dependencies so we can test any changes to dependabot-core with a dry run on it.

I'll try to find time to look into this repo later, thanks for the links @asciimike

**Comment by mustafaozhan** [comment]
Really looking forward to seeing this too!

**Comment by eirnym** [comment]
I'm looking forward to support Gradle Wrapper updates. Update-gradle-wrapper-action mentioned above has too many problems. I'm going to replace it using https://services.gradle.org/ at least till the dependabot will support it

**Comment by eirnym** [comment]
https://github.com/marketplace/actions/upgrade-gradle is the closest implementation to what I have locally

**Comment by xtermi2** [comment]
Really disappointing, no progress here. I'm waiting for years for this feature.

**Comment by GregJohnStewart** [comment]
Bump!

Sad to see it's not supported already :(

**Comment by FunkyMuse** [comment]
any hope on this?

**Comment by deivid-rodriguez** [comment]
Hello! We'll make sure to update this issue once there's movement. In the meantime, please use reactions instead of [+1 comments](https://github.com/dependabot/dependabot-core#no-1-comments) to show support for the request. Thanks!

**Comment by DPUkyle** [comment]
https://services.gradle.org/versions/current is a great endpoint with easy-to-consume json.

**Comment by britter** [comment]
@DPUkyle I think the main problem here is that in order to upgrade the wrapper jar and shell scripts completely one needs to run the Gradle build. I'm not sure that is supported by dependabot.

**Comment by Thunderforge** [comment]
Aren't the wrapper jar and shell scripts known quantities for each release, used the same by everyone? Is it possible to have Dependabot just supply pre-built for the requested version instead of running `gradlew wrapper` to generate them?

**Comment by gmazzo** [comment]
This has been open for several years now, and since I'm tired of using 3rd party stuff for this kind of bump, I took some time to implement it #12891

I just hope that maintainers will show some ❤️ to it, since this is my first time with a big-scale Ruby project

**Comment by huehnerlady** [comment]
@rahulsom thank you so much for implementing this. is there anything special I need to do for it to be enabled? My file looks like this:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      spring: # always update spring dependencies together
        patterns:
          - "org.springframework*"
      other: # group all non-spring minor/patch updates
        patterns:
          - "*"
        exclude-patterns:
          - "org.springframework*"
        update-types:
          - minor
          - patch
```

**Comment by yeikel** [comment]
@huehnerlady Your configuration is correct, however, there is still work in progress for this. There is a chance that we closed this issue a bit prematurely/optimistically. 

See https://github.com/dependabot/dependabot-core/pull/12891 for updates

**Comment by huehnerlady** [comment]
@yeikel ok thank you. 

Maybe it makes sense to reopen it again to have transparency on this? :)

**Comment by yeikel** [comment]
@kbukum1 Could you please re-open this issue. We should close this after we fix all the open issues and promote it from experiment to stable

Otherwise, it causes confusion like what @huehnerlady observed

**Comment by v-kbukum1** [comment]
> [@kbukum1](https://github.com/kbukum1) Could you please re-open this issue. We should close this after we fix all the open issues and promote it from experiment to stable
> 
> Otherwise, it causes confusion like what [@huehnerlady](https://github.com/huehnerlady) observed

Since there are a few issues @gmazzo and @yeikel are working on, we are going to keep this issue until we roll out the feature flag for gradle wrapper update.

**Comment by gregjotau** [comment]
Are there any docs for how to enable this? Our current dependabot.yml:
```
version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/*"        # all immediate subfolders
    schedule:
      interval: "cron"
      cronjob: "0 0 1 * *"   # 1st of every month 00:00 UTC
    groups:
      all-gradle-updates:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/cloudflare-worker"
    schedule:
      interval: "cron"
      cronjob: "0 0 1 * *"   # 1st of every month 00:00 UTC
    groups:
      all-npm-updates:
        patterns: ["*"]
```
