### ISSUE TITLE
Support Kotlin when updating Gradle files

### ISSUE THREAD

**Issue by JLLeitschuh** [dependabot/dependabot-core#2238]
Trying to add a project like this one: https://github.com/JLLeitschuh/ktlint-gradle

Gives the following error:
> Repo must contain a build.gradle.

The bot should support `build.gradle.kts` files, or even better, supporting `*.gradle.kts` files and `*.gradle` files.

---

More in depth information about this issue can be found here:
 - https://github.com/dependabot/dependabot-core/issues/1164
 - https://github.com/dependabot/feedback/issues/172#issuecomment-637591057

**Comment by Jerbell** [comment]
Until Kotlin DSL is supported I have a bit of a hack:
Add this to your parent build.gradle.kts (subprojects section for multi-module)
```kotlin
    tasks.register("createDependabotFile") {
        doLast {
            mkdir("$projectDir/dependabot")
            val file = File("$projectDir/dependabot/build.gradle")
            file.writeText( "// Do not edit manually! This file was created by the 'createDependabotFile' task defined in the root build.gradle.kts file.\n")
            file.appendText("dependencies {\n")
            project.configurations.getByName("runtimeClasspath").allDependencies
                    .filter { it.group != rootProject.name && it.version != null }
                    .forEach { file.appendText("    compile '${it.group}:${it.name}:${it.version}'\n") }
            project.configurations.getByName("testRuntimeClasspath").allDependencies
                    .filter { it.group != rootProject.name && it.version != null }
                    .forEach { file.appendText("    testCompile '${it.group}:${it.name}:${it.version}'\n") }
            file.appendText("}\n")
        }
    }
```
It will create a dummy build.gradle file in a dependabot directory.  Have dependabot analyse that build.gradle & make suggestions.  When you update your relevant kts file, then pull requests get closed automatically.
You might want to switch runtimeClasspath & testRuntimeClasspath to be runtimeClasspath & testRuntimeClasspath respectively.
I have this task run after Gradle sync in IntelliJ.
Feel free to improve!

**Comment by Hakky54** [comment]
Thank you @Jerbell and @teolemon for sharing your hacks, I used it with a multi module project and it worked. Just sharing here the github action for others who are seeking for a temp solution till the actual feature is available.

**dependabot.yml**
```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "module-a/dependabot"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "module-b/dependabot"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "module-c/dependabot"
    schedule:
      interval: "daily"
```
