### ISSUE TITLE
Support for `automerge` in GitHub Native Dependabot

### ISSUE THREAD

**Issue by UziTech** [dependabot/dependabot-core#2268]
The `automerged_updates` options seems to have been removed in v2 according to the [docs](https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates). Is there a way to automerge v2?

**Comment by feelepxyz** [comment]
@UziTech sadly yes, we've got this issue tracking automerging support with a few community-suggested alternatives: https://github.com/dependabot/dependabot-core/issues/1973

Will close this out as duplicate.

**Comment by UziTech** [comment]
@feelepxyz I saw that issue but it is about v1. I am asking about v2

**Comment by feelepxyz** [comment]
@UziTech ah yes sorry that issue is confusing. Here's the comment reffering to v2 support: https://github.com/dependabot/dependabot-core/issues/1823#issuecomment-641594279

**Comment by UziTech** [comment]
@feelepxyz It seems like the comments about automerging in v2 are spread into issues about other things. I still feel like this isn't a duplicate of any of those since none of those issues are specifically about auto-merge in v2. Some of them are also closed making it harder for a person to find them. I think it would be easier for people to find the reasoning behind the removal if this issue remained open until it is resolved.

Though I feel like a link to this https://github.com/dependabot/dependabot-core/issues/1823#issuecomment-641594279 is good enough for an answer.

**Comment by UziTech** [comment]
In case anyone wants the ability to auto merge you can accomplish this with github actions:

The token used to comment must have `public_repo` or push permission to the repo so the default `secrets.GITHUB_TOKEN` won't work.

```yml
  ...
  Automerge:
    needs: [Test, Lint]
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event_name == 'pull_request' &&
      startsWith(github.event.pull_request.title, 'chore(deps-dev):')
    steps:
      - name: '@dependabot merge'
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            await github.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body: '@dependabot merge'
            })
```

**Comment by Clumsy-Coder** [comment]
@UziTech I'm having trouble with which Personal Access Token scope to use. You said you need either **public_repo** or **push permission**. Which scope permission is that (the push permission)?

**Comment by UziTech** [comment]
@Clumsy-Coder If it is a public repo this is all you should need:

![image](https://user-images.githubusercontent.com/97994/87958243-e8dd7280-ca76-11ea-8e26-c17b7d639d34.png)

There isn't a permission called "push" but any token that is able to push commits should work.

**Comment by Clumsy-Coder** [comment]
@UziTech I'm using a private repo. Do I need **repo** permission (and all it's sub permissions)?

**Comment by UziTech** [comment]
Yes I believe `repo` is permission is needed to push to private repos.

**Comment by Clumsy-Coder** [comment]
@UziTech Thanks. That worked.

**Comment by ZebraFlesh** [comment]
It seems like this solution fails with protected branches? (The `dependabot` user can't be granted access to push to a protected branch.)

**Comment by UziTech** [comment]
@ZebraFlesh you can try using the [pascalgn/automerge-action](https://github.com/pascalgn/automerge-action) to merge with a user other than dependabot.

**Comment by ZebraFlesh** [comment]
@UziTech Thanks, that's an interesting work around. However, I'm not thrilled about consuming yet more Actions minutes because dependabot broke the `merge` command in v2. I'm going to stick with v1 until this is fixed.

**Comment by peaceiris** [comment]
We got the alternative here: https://twitter.com/github/status/1336360682221133827?s=20

> Check out auto-merge! Now, when your branch protection rules are met, your changes approved, and your checks are green, GitHub can automatically merge your pull request for you.

**Comment by UziTech** [comment]
@peaceiris Is that a button that you have to push on every pull request? This issue is more about not even having to look at the pull request or need any human interaction for merging dependency updates.

**Comment by peaceiris** [comment]
We do not know the details yet. [It will start rolling out next week.](https://twitter.com/willsmythe/status/1336383054676455425?s=20) I hope we can set the auto-merge for a whole repository/account.

**Comment by UziTech** [comment]
According to the roadmap it will be a button that can be pressed when a PR is submitted by a person with push access. I don't think this will do anything for dependabot ☹.

https://github.com/github/roadmap/issues/107

**Comment by UziTech** [comment]
It seems like all of these automerge work arounds are failing now since dependabot does not have access to any secrets in the repository.

https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

**Comment by mercuriete** [comment]
as @UziTech said, we can't use personal access tokens on Github actions triggered from dependabot.
So we cant use any plugin or implement a custom solution because of that.

I think it's time to raise the priority of this bug.

Thanks for your awesome work.

**Comment by dentarg** [comment]
Looks like it could be possible to still workaround it, with the `on:  workflow_run: ...` technique shown in https://securitylab.github.com/research/github-actions-preventing-pwn-requests?

**Comment by feelepxyz** [comment]
👋  Sorry for the inconvenience this change has caused. We know it's a pain to rejig workflows around this new limitation but we felt it was necessary considering the potential risk.

We've put together a sample workflow for updating a dependabot pr that might be a useful reference for automerging using actions: https://github.com/dependabot/dependabot-actions-workflow/tree/main/.github/workflows

**Comment by UziTech** [comment]
> We've put together a sample workflow for updating a dependabot pr that might be a useful reference for automerging using actions: https://github.com/dependabot/dependabot-actions-workflow/tree/main/.github/workflows

That is a lot of boiler plate code that could be handled by `automerge: true`. Every other dependency management software that I have used has it (including dependabot v1) and I have never, not once, had any security related issues.

I also don't see how the method in that reference is any safer than having a configuration option.

**Comment by asciimike** [comment]
As noted above, _infin8x provided some good context on why this isn't likely to be added to v2 here: https://github.com/dependabot/dependabot-core/issues/1823#issuecomment-641594279 (and if you need more incentive, the [eslint-scope](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes) postmortem explicitly said that people shouldn't use automergers to prevent propagation of the issue).

We need to ensure that when we build a product, it's safe for the millions of developers on GitHub, not just usable by the folks on this thread. We also recognize that folks need escape hatches that let developers act unsafely *if they understand and are willing to assume that risk.*

An average developer that uses `automerge: true` isn't likely to understand the potential dangers inherent in a "harmless" one liner, while one who reads a blog post called "preventing pwn requests" and sees examples of why what they're trying to do can result in their credentials being stolen is much more likely to understand that risk.

Security is a spectrum from "reasonably secure" to "hilariously insecure", which unfortunately often conflicts with developer experience (it's easier to hardcode your API keys, but you really should be using Vault and rotating the keys with some frequency). I want to push defaults closer to "reasonably secure" over time, ideally without major regressions in experience. Sometimes, it's not possible to do that, and I want to make it clear that we don't take these tradeoffs lightly. I know it's not the easiest thing accept when you feel like something useful has been taken away, and I apologize if folks that feel that way. We're constantly working behind the scenes to make Dependabot more secure AND more usable, and sometimes that progress isn't always linear.

**Comment by UziTech** [comment]
> Security is a spectrum from "reasonably secure" to "hilariously insecure"

I think this is the main debate here. Where that line should be drawn is often unclear. The problem I have with dependabot is that literally every other dependency management software that I know of draws the line on the other side of `automerge: true`.

**Comment by UziTech** [comment]
Maybe a good compromise would be something like react uses with `dangerouslySetInnerHTML`. The setting could be `dangerouslyAutomergeAndPossiblyGetPwnd: true`

**Comment by asciimike** [comment]
I considered writing this (my options were a bit snarkier, ranging from `i-acknowledge-automerge-is-unsafe: true` to `i-will-not-post-nasty-things-to-hacker-news-when-my-automerged-dependency-mines-bitcoin: true`?), but I worry that this is still going to result in people getting pwned and then asking why GitHub provided a thing that we acknowledged is unsafe in the first place.

**Comment by asciimike** [comment]
> The problem I have with dependabot is that literally every other dependency management software that I know of draws the line on the other side of automerge: true

They will also be on the other side of propagating vulnerable/malicious dependencies. They have a different set of constraints, therefore they make this choice. I am unconvinced that GitHub can given the total size and breadth of experience of customers on the platform.

**Comment by UziTech** [comment]
> I am unconvinced that GitHub can given the total size and breadth of experience of customers on the platform.

A couple things wrong with this statement:

1. The other dependency management software works with GitHub so the size and breadth of experience of customers is at least as big as GitHub users.
2. Dependabot is not GitHub.

I don't think GitHub should make a one click "Automerge PRs" button (for exactly the reason you illustrate). Dependabot adding a setting (no matter how long) is very different than giving every GitHub user the ability to automerge dependencies.

> They will also be on the other side of propagating vulnerable/malicious dependencies.

Possibly, but at this point, I believe, they understand that risk and have still found the line between convenience and security to be on the other side.

> They have a different set of constraints, therefore they make this choice.

Do they? It is possible they need to move the line towards convenience to attract customers whereas Dependabot is just a free addon, hence no need to attract customers.

In any case, I still think it would be beneficial for Dependabot to add back the setting instead of requiring customers to jump through hoops. Luckily there is other software that accomplishes the same thing.

**Comment by asciimike** [comment]
Dependabot as it exists (not the legacy Dependabot Preview) is built in to GitHub, no app install necessary (unlike all the other options). Security Updates are enabled by default on public repos where it makes sense ([docs](https://docs.github.com/en/code-security/supply-chain-security/configuring-dependabot-security-updates#supported-repositories)). So yes, it could end up as "letting every GitHub user automerge their dependencies."

**Comment by UziTech** [comment]
The setting would require users to create a dependabot config file. So no, it could not end up as "letting every GitHub user automerge their dependencies" any easier than any other software.

**Comment by honzajavorek** [comment]
Earlier today I posted a comment to an issue which is possibly less relevant than this one. I'm cross-posting it for visibility and to add myself to the discussion here: https://github.com/dependabot/dependabot-core/issues/1973#issuecomment-829083554

As of writing this, I got PRs notifying me about the migration on 14 projects. Most of them are using auto-merging. Just one is something I'm paid to maintain.

I feel like I'm getting punished for loving the technology in the past and heavily using it on most of my hobby and community projects.

**Comment by mercuriete** [comment]
@honzajavorek 
I had the same problem as you had.
I just drop dependabot and started use renovatebot.

just install this: https://github.com/marketplace/renovate

and drop a file similar to this one:

renovate.json
```json
{
  "extends": [
    "config:base"
  ],
  "schedule": ["after 7pm and before 7am"],
  "prConcurrentLimit": 2,
  "packageRules": [
    {
      "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    },
    {
      "matchDepTypes": ["devDependencies"],
      "automerge": true
    }
  ]
}
```

I hope you can evaluate if that tool is better for your use case.

**Comment by JustArchi** [comment]
I've also replaced dependabot with renovate bot, and I can recommend everybody interested doing the same. I don't know what was so difficult in renaming `automerge: true` to `i-know-what-im-doing-and-understand-the-risks-so-automerge-please: true` and keeping perfectly valid feature, but it's no longer any concern of mine.

The fact that you've decided to announce the shutdown of native Dependabot before resurrecting this feature as part of your "investigation" in https://github.com/dependabot/dependabot-core/issues/1823#issuecomment-641594279 was the final nail in the coffin for me. And the fact that you defend your decision with that argument yet recommend people to use third-party solutions to re-enable automerge is a total hypocrisy to me.

So long dependabot, yet another great product that went downhill after acquisition.

**Comment by UziTech** [comment]
For anyone looking for a work-around here is a script that uses `workflow_run` to merge dependabot PRs:

```yml
name: "Automerge"
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  Automerge:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Merge PR'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
            });
            if (pr.data.title.startsWith('chore(deps-dev):') && pr.data.user.login === 'dependabot[bot]') {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.workflow_run.pull_requests[0].number,
              });
              console.log('Merged 🎉');
            } else {
              console.log('Not Merged 🚫');
            }

```

You can see it in action [here](https://github.com/UziTech/marked-linkify-it/tree/main/.github/workflows).

**Comment by asciimike** [comment]
And for folks who need metadata (e.g. name of the dependency, semver, dev/prod, etc.) we have published an action that provides this and have some info on how it can be used to enable GitHub's auto-merge: https://github.com/marketplace/actions/fetch-metadata-from-dependabot-prs#enabling-auto-merge

**Comment by Kocal** [comment]
Nice! That's really a great news. Thanks @asciimike!

**Comment by gitfool** [comment]
@asciimike good stuff! If I understand correctly, it follows that the _simplest_ workflow I can have to just auto approve and auto merge all dependabot PRs would be:
```yaml
name: Dependabot auto-approve and auto-merge
on: pull_request_target
permissions:
  pull-requests: write
  content: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Auto merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
This would still leverage the `dependabot/fetch-metadata` action to validate the author and all commits are from Dependabot.
