### ISSUE TITLE
Add label by package name and update_type

### ISSUE THREAD

**Issue by jrjohnson** [dependabot/dependabot-core#2294]
With the removal of automerge a configuration like:

```
automerged_updates:
    - match:
        dependency_name: "eslint"
    - match:
        update_type: "semver:minor"
        dependency_name: "@fortawesome/free-brands-svg-icons"
```
Is no longer possible. In order to effectively automate a replacement using a merge action we need to be able to apply labels to the PR based on the package/semver release/risk.

Something like 
```
labels:
    my_automerge_label:
      - match:
         dependency_name: eslint
         new_maintainer: false
      - match:
         update_type: semver:minor
         dependency_name: "@fortawesome/free-brands-svg-icons"
```

Criteria like `new_maintainer` is particularly important and something dependabot prevented auto-merging on in the past, but would be very difficult to suss out in a bot without parsing the content of the PR.

Refs #2268 #1973
