### ISSUE TITLE
Private Module Golang

### ISSUE THREAD

**Issue by renanbastos93** [dependabot/dependabot-core#2297]
I have module private on Golang inside my organization so `dependabot` not found it to validate.

![image](https://user-images.githubusercontent.com/8202898/86849666-69b76a00-c086-11ea-8000-52b12ef571f8.png)

my file:

```yml
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates managed by Composer once a week
      interval: "weekly"

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates managed by Composer once a week
      interval: "weekly"
```
