### ISSUE TITLE
Dependabot not creating PRs when it should be

### ISSUE THREAD

**Issue by kbrashears5** [dependabot/dependabot-core#2320]
**Package manage/ecosystem**
npm

**Manifest contents prior to update**
https://github.com/kbrashears5/typescript-aws-apigateway-helper/blob/master/package.json

**Updated dependency**
@types/node 14.0.22 -> 14.0.23
ts-jest 26.1.1 -> 26.1.2
typescript-helper-functions 1.0.9 -> 1.0.10

**What you expected to see, versus what you actually saw**
Expect to see a PR created as 3 dependencies are out of date

**Images of the diff or a link to the PR, issue or logs**
[dependabot_logs.txt](https://github.com/dependabot/dependabot-core/files/4922481/dependabot_logs.txt)
yaml setup:
```yaml
version: 2
updates:
  # package.json in root directory
  - package-ecosystem: "npm"
    directory: "/"
    # daily at 5am UTC
    schedule:
      interval: "daily"
```
