### ISSUE TITLE
[npm] Update both dependencies and devDependencies

### ISSUE THREAD

**Issue by Clumsy-Coder** [dependabot/dependabot-core#2351]
Allow the ability to check and update both npm dependencies **and** devDependencies.

Currently I see the option to only update either npm dependencies or devDependencies, but not both.

Current dependabot config.
```yaml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'direct'
    open-pull-requests-limit: 15

```

Using [link](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#allow) as reference
