### ISSUE TITLE
Dependabot does not seems to run since migrating to Github / 2.0 config.

### ISSUE THREAD

**Issue by louim** [dependabot/dependabot-core#2370]
**Package manager/ecosystem**
NPM and Bundler

**What you expected to see, versus what you actually saw**
Since we migrated our projects to the integrated version with Github, Dependabot hasn't bumped our dependencies automatically. We followed the configuration instructions from the migration PR and on Github, but so far I had to run the check manually. This is what our config looks like:
```yml
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "05:00"
    timezone: "America/Montreal"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "05:00"
    timezone: "America/Montreal"
  open-pull-requests-limit: 10
```

Based on that, I would assume the weekly scan would occur at 5:00 in the Timezone America/Montreal on monday. So far it hasn't 😢, and we had to trigger the update manually. Is there something wrong in that config?

We have that config on `https://github.com/hooktstudios/didacte-site` (private repo). We also run the same config for most of our projects, and the result was the same (no bump).
