### ISSUE TITLE
Dependabot Hang in "Checking now" with unfound package

### ISSUE THREAD

**Issue by erwan-joly** [dependabot/dependabot-core#2382]
I'm trying to turn on dependabot in a private C# project repo.
Dependabot hang in "Checking now" stage.
I suspect the reason for this is because one of the nuget package is not on nuget but on a private source.
I was expecting to have the system working with an exclude on those package but it seems to hang even with exclusion.

```

version: 2
updates:
  - directory: "/services/FirstService"
    package-ecosystem: nuget
    schedule:
      interval: daily
    labels:
      - "a label"
      - "ready for review"
    ignore:
      - dependency-name: "MyDependencyPrefix.*"

  - directory: "/services/SecondService"
    package-ecosystem: nuget
    schedule:
      interval: daily
    labels:
      - "a label"
      - "ready for review"
    ignore:
      - dependency-name: "MyDependencyPrefix.*"


```
that is pretty much the code i'm using. I obviously don't expect to get updates on MyDependencyPrefix.* packages as those are not accessible but i would still expect the system not to hang.

is it a bug or my configuration is bad ?
