### ISSUE TITLE
Ability to have duplicate updates - but different allow types

### ISSUE THREAD

**Issue by kbrashears5** [dependabot/dependabot-core#2390]
Ability to have duplicate updates in the same dependabot

Would like the ability to do something like this:
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-type: "production"
        
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    allow:
      - dependency-type: "development"
```

This lets me define that daily, look for dependencies, and weekly look for dev dependencies.

How I have this setup now, I get an error saying 
> The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
