### ISSUE TITLE
[BUG][pip-tools] Double PRs for nested subdirs

### ISSUE THREAD

**Issue by webknjaz** [dependabot/dependabot-core#2489]
When there's several entries for the repository root and the subfolder (`/docs` and `/`), updates for the same deps in the subfolder are sent twice.

_I think_ dependabot should exclude explicitly declared subfolders when processing the higher level dirs with the same package manager.

**Package manager/ecosystem**

pip-compile

**What you expected to see, versus what you actually saw**

Expected one PR, got two:
https://github.com/ansible/ansible-lint/pull/1015 / https://github.com/ansible/ansible-lint/pull/1016

```yaml
# .github/dependabot.yml
version: 2
updates:
- package-ecosystem: pip
  directory: /docs
  schedule:
    day: sunday
    interval: weekly
  labels:
  - dependabot-deps-updates
  - skip-changelog
  versioning-strategy: lockfile-only
  open-pull-requests-limit: 3
- package-ecosystem: pip
  directory: /
  schedule:
    day: sunday
    interval: weekly
  labels:
  - dependabot-deps-updates
  - skip-changelog
  versioning-strategy: lockfile-only
  open-pull-requests-limit: 3
```
