### ISSUE TITLE
Allow array in `target-branch`

### ISSUE THREAD

**Issue by skjnldsv** [dependabot/dependabot-core#2511]
That would prevent us to have lots of duplicate configs 

```yml
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch:
  - stable19
  - stable18
  - stable17
  labels:
  - 3. to review
  - "feature: dependencies"
```
