### ISSUE TITLE
Support configuring allowed updates for security updates using config file

### ISSUE THREAD

**Issue by kyeotic** [dependabot/dependabot-core#2521]
I have configured a [`dependabot.yml`](https://github.com/kyeotic/raviger/blob/master/.github/dependabot.yml) that should ignore devDependencies

```yaml

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    ignore:
      - dependency-name: "*"
        dependency-type: "development"
```

Despite this I am still getting [PR's for devDependency warnings](https://github.com/kyeotic/raviger/pull/68)

What do I need to do to stop these from happening?

**Comment by jurre** [comment]
Hi, that config file looks to be invalid: https://github.com/kyeotic/raviger/runs/1097204025

You cannot specify `dependency-type` in the `ignore` condition, but since you already have an `allow` rule set up to match only `production` dependency types, I think you can get rid of that `ignore` field entirely and it should work.

Lmk if that works 👍

**Comment by kyeotic** [comment]
I added the ignore field after the `allow` failed to stop a PR yesterday. I will remove ignore again and give it another day I guess.

**Comment by kyeotic** [comment]
It's happening [again](https://github.com/kyeotic/raviger/pull/76)

with this config

```yaml
version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
        dependency-type: "production"

```

**Comment by kyeotic** [comment]
@jurre I realized you probably wouldn't get notified from an issue re-opening... so :bump:

**Comment by jurre** [comment]
@feelepxyz do you have an idea what's going on here?

**Comment by feelepxyz** [comment]
@kyeotic pretty sure that's because it's a security update fixing a vulnerability in lodash: https://github.com/advisories/GHSA-p6mc-m468-83gw

You currently can't configure `allow`ed updates for security updates using the config file. Currently only the following config file options are used for security updates:
- `assignees`
- `commit-message`
- `ignore`
- `labels`
- `milestone`
- `pull-request-branch-name.separator`
- `rebase-strategy`
- `reviewers`
- `vendor`
- `versioning-strategy`

You'd have to ignore the dependencies specifically as we don't support ignoring `dependency-type` yet.

**Comment by kyeotic** [comment]
@feelepxyz That's surprising. Is this explained in the docs anywhere?

I think wanting to ignore dependabot warnings for devDependencies is a pretty common request. I don't see why this separate and additional category of "security updates" is even in the equation. If I say I don't want devDependency warnings I mean I don't want _any warnings for any devDependencies_. Frankly, this behavior is _wrong_.

**Comment by kyeotic** [comment]
I guess I'm just going to have to disable dependabot entirely.

**Comment by feelepxyz** [comment]
Good feedback and legitimate use-case! Will add this to our backlog to fix, we haven't done much to make both products configurable using the same config file but are looking at changing this.

> I guess I'm just going to have to disable dependabot entirely.

You can also only disable security updates from the GitHub UI: 

<img width="1096" alt="Screenshot 2020-11-20 at 17 46 11" src="https://user-images.githubusercontent.com/20165/99832345-4c2bfe00-2b58-11eb-8825-ccc96237ede5.png">

**Comment by ronjouch** [comment]
@kyeotic for findability, can you pls rename this issue to something like `Dependabot *security* updates should accept a "production dependencies only" mode` ? Hope this lands someday.

**Comment by ronjouch** [comment]
Also, @feelepxyz @jurre reading [dependabot-security docs](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-dependabot-security-updates), it's not clear to me how yml-configurable this "security" product is. Before this issue I hadn't understood it was configurable, at all. Does dependabot-security read dependabot.yml? Will both dependabot and dependabot-security run? Since having a dependabot.yml is how you enable dependabot, how do I for example configure `reviewers` for my security alerts, but without enabling the full dependabot? Am I missing documentation?

**Comment by feelepxyz** [comment]
> Also, @feelepxyz @jurre reading [dependabot-security docs](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-dependabot-security-updates), it's not clear to me how yml-configurable this "security" product is. Before this issue I hadn't understood it was configurable, at all. Does dependabot-security read dependabot.yml? Will both dependabot and dependabot-security run? Since having a dependabot.yml is how you enable dependabot, how do I for example configure `reviewers` for my security alerts, but without enabling the full dependabot? Am I missing documentation?

Yeah it's currently very patchy but we have a plan to fix it! You currently can't configure security updates using the config file without also enabling version updates, if you do want to enable version updates the following config file options will also apply to security updates: https://github.com/dependabot/dependabot-core/issues/2521#issuecomment-731305885

**Comment by kyeotic** [comment]
@feelepxyz Sounds good, I will disable dependabot-security until thats fixed.

As a user, I have to say that this distinction is surprising and frustrating. I understand that they are internally considered two independent products, possibly developed by different teams, but they serve similar functions, have similar names, with similar operation and similar configuration so as a user I don't see them as independent, but as parts of a whole. I expect the difference in security and regular (?) to be a kind of alert, not a completely separate application with separate configuration. I would like to see them use a single configuration, possibly with a `threshold` or `minimumAlertLevel` for each kind.

**Comment by ronjouch** [comment]
@feelepxyz @jurre any news on making `Dependabot security updates` configurable (either through a `dependabot.yml`, or through checkboxes in `https://github.com/<org>/<project>/settings/security_analysis` ?

For my desired use case (1. security vulns only, 2. npm prod deps only, 3. automatic assignment to a list of reviewers) I'm still torn between two unsatisfying options:

1. Use a `dependabot.yml` to get above points [2, 3], but miss point [1] and be overwhelmed with non-security upgrades.
2. Use the barebones `Dependabot security updates` feature integrated into GitHub and get above point [1], but miss points [2, 3] and have PRs for all deps (as opposed to only prod deps) and lacking assignment to reviewers.
    - Note: point 2. "prod deps only" isn't the biggest deal for me. What matters most is to point 3. "automatically assignment to a list of reviewers", else these PRs are just floating here and nobody looks at them.

---

<sub>(And sorry for the lame "bump" comment, I never write those in open source projects because I hate causing noise to issue subscribers, but I'm paying for dependabot/GitHub and it's been six months, so here's me doing an exception to this rule :shrug:)</sub>

**Comment by feelepxyz** [comment]
@ronjouch yeah it's kinda possible to configure security updates through `dependabot.yml`, this is a bit of a hack atm but should work:

```yaml
version: 2
updates:
  - package-ecosystem: npm
     directory: "/"
     schedule:
       interval: "daily"
     open-pull-requests-limit: 0 # in case you don't want to enable version updates
     allow:
      - dependency-type: "production"
     reviewers:
       - username
```

Security update PR should inherit this config as the config object is shared between version and security updates as long as the ecosystem, directory matches on the default branch.

We're planning to make this a lot nicer.
