### ISSUE TITLE
Nuget does not work with the "Ignore" option of dependabot.yml

### ISSUE THREAD

**Issue by Jacob-Roberts** [dependabot/dependabot-core#2531]
**Package manager/ecosystem**
nuget
**Manifest contents prior to update**
N/A
**Updated dependency**
N/A
**What you expected to see, versus what you actually saw**
In my project we have a dependency on IdentityServer4
`<PackageReference Include="IdentityServer4" Version="3.1.4" />`
My Dependabot.yml file is as follows
```yaml
version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "develop"
    # For IS4, ignore all updates for version 4 and 5
    ignore:
      - dependency-name: "IdentityServer4"
        versions: ["4.x"]
```
However, dependabot keeps creating pull requests for IdentityServer4 versions 4 and above.

**Images of the diff or a link to the PR, issue or logs**
![IS4Update](https://user-images.githubusercontent.com/1888257/93531379-5f261600-f8fc-11ea-84b2-3d7838226d32.PNG)
