### ISSUE TITLE
Improvements to submodules and lockfile interaction

### ISSUE THREAD

**Issue by cbeck88** [dependabot/dependabot-core#2534]
We have recently started using dependabot in a rust project, it is awesome! Thank you!

One way that it could be better is the following:

The submodules language supports detecting changed submodules and opening PRs to uprev them, but in rust cargo, usually submodule uprevs will trigger changes to the Cargo.lock files, because the cargo manifests and versions of the crates in the submodule may change.

The guidance from Cargo team is that for libraries, `Cargo.lock` should not be committed, but for applications, the `Cargo.lock` usually should be committed to support repeatable builds: https://github.com/rust-lang/cargo/issues/315

Consequently, we commit our `Cargo.lock` files and check in CI that building does not change the `Cargo.lock`. This is like a dirty-git check.

Consequently, when dependabot submodules bot opens the uprev PR, the PR is usually almost perfect but needs a lockfile update. Then a human needs to pull the branch, do `cargo build`, commit the changed lockfiles, and push to the dependabot branch.

It would be great if dependabot could also handle the lockfiles somehow so that the PR it creates is usually perfect and can just be merged. i'm not sure how hard this is. There are also some other cargo commands like `cargo generate-lockfile` that are supposed to generate the lockfile without building, but I don't know much about these.

It seems likely that other language with package managers with lockfiles might have the same issue when dealing with submodules, but I'm not sure. I didn't find any existing tickets. Thanks!

**Comment by fregante** [comment]
This isn't necessarily a rust issue, but a git submodule issue. I have the same problem with npm with the configuration described in https://github.com/dependabot/dependabot-core/issues/5977

My current solution is a workflow + a manual commit to trigger CI:

```yml
name: dependabot

on:
  pull_request_target:
    # Do not use, it doesn't work. It seems that the workflow is run from the `main` branch instead
    # branches: ["dependabot/submodules/**"]

permissions:
  pull-requests: write
  contents: write

jobs:
  lockfile-update:
    if: github.actor == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/submodules/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # https://stackoverflow.com/a/65027014/288906
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - run: npm install
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lockfile
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            CI does not start automatically, so:

            1. Create a commit
            2. Fix any new CI issues
            3. Merge

            To create a commit, either:

            - Click on "Update branch" button if available
            - Check out this branch and run this command locally:

            ```sh
            git commit --allow-empty -m "trigger ci" && git push
            ```
```
