### ISSUE TITLE
How to trigger updates again once dependencies were ignored and pull requests closed in the past? 

### ISSUE THREAD

**Issue by xh3b4sd** [dependabot/dependabot-core#2549]
Coming from the Kubernetes ecosystem we have to ignore certain dependencies for a little while until we can catch up with everything. So we have a directive like the one below. 

```
  ignore:
  - dependency-name: k8s.io/*
    versions:
    - ">=0.17.0"
```

After some time we want to move on and modify the ignore directive as follows. Note minor `17` became minor `19`. 

```
  ignore:
  - dependency-name: k8s.io/*
    versions:
    - ">=0.19.0"
```

Now there are still no pull requests coming from dependabot and I presume this is due to certain pull requests being closed which tried to update these dependencies before we had the ignore directive in place. I would like to get updates again once the ignore directive changed. How does this work right now?
