### ISSUE TITLE
yarn.lock updates are not using private registry

### ISSUE THREAD

**Issue by timofloettmann** [dependabot/dependabot-core#2698]
**Package manager/ecosystem**

javascript

**Updated dependency**

Happens with any dependency that isn't listed in the package.json. I have not observed this issue with dependencies that are listed in the package.json yet.

**What you expected to see, versus what you actually saw**

Expected version, hash and integrity values to change, but registry endpoint should have remained the same. Instead, this is what the Pull Request changeset looks like:

before:
```
bl@^1.0.0:	
  version "1.2.2"	 
  resolved "https://company.jfrog.io/artifactory/api/npm/npm/bl/-/bl-1.2.2.tgz#a160911717103c07410cef63ef51b397c025af9c"	  
  integrity sha1-oWCRFxcQPAdBDO9j71Gzl8Alr5w=	 
```

after:
```
bl@^1.0.0:
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/bl/-/bl-1.2.3.tgz#1e8dd80142eac80d7158c9dccc047fb620e035e7"
  integrity sha512-pvcNpa0UU69UT341rO6AYy4FVAIkUHuZXRIWbq+zHnsVcRzDDjIAhGuuYoi0d//cwIwtt4pkpKycWEfjdV+vww==
```

Note the `registry.yarnpkg.com` in the updated entry.

**Additional information**

- The registry is configured in an `.npmrc` that is checked into the repository:

```
registry=https://company.jfrog.io/artifactory/api/npm/npm/
```

- Authentication is configured in Config variables, the dependabot logs show that those work:

> updater | INFO <job_52737199> Checking if bl 1.2.2 needs updating
>   proxy | 2020/10/29 12:55:51 [012] GET https://company.jfrog.io:443/artifactory/api/npm/npm/bl
>   proxy | 2020/10/29 12:55:51 * authenticating npm registry request (host: company.jfrog.io, basic auth)
>   proxy | 2020/10/29 12:55:52 [012] 200 https://company.jfrog.io:443/artifactory/api/npm/npm/bl
>   proxy | 2020/10/29 12:55:52 [014] GET https://company.jfrog.io:443/artifactory/api/npm/npm/bl
>   proxy | 2020/10/29 12:55:52 * authenticating npm registry request (host: company.jfrog.io, basic auth)
>   proxy | 2020/10/29 12:55:52 [014] 200 https://company.jfrog.io:443/artifactory/api/npm/npm/bl
>   proxy | 2020/10/29 12:55:52 [016] GET https://company.jfrog.io:443/artifactory/api/npm/npm/bl/4.0.3
>   proxy | 2020/10/29 12:55:52 * authenticating npm registry request (host: company.jfrog.io, basic auth)
>   proxy | 2020/10/29 12:55:52 [016] 200 https://company.jfrog.io:443/artifactory/api/npm/npm/bl/4.0.3
> updater | INFO <job_52737199> Latest version is 4.0.3
>   proxy | 2020/10/29 12:55:57 [018] GET https://company.jfrog.io:443/artifactory/api/npm/npm/bl
>   proxy | 2020/10/29 12:55:57 * authenticating npm registry request (host: company.jfrog.io, basic auth)
>   proxy | 2020/10/29 12:55:57 [018] 200 https://company.jfrog.io:443/artifactory/api/npm/npm/bl

**Comment by jurre** [comment]
Are you using dependabot.com, or the github native version of dependabot? Because we do not currently support private registries in the gh-native version (although we are working on it).

If you are using dependabot.com (dependabot-preview), how have you configured the credentials for this registry?

**Comment by timofloettmann** [comment]
Yes, we're using dependabot-preview.

The credentials have been configured through the Dashboard only (nothing in npmrc or yarnrc): Top right corner -> Config variables -> `Javascript` with `company.jfrog.io/artifactory/api/npm/npm/` as registry and `user:password` for credentials.

**Comment by asciimike** [comment]
We [just launched support for private registries](https://github.blog/2021-03-15-dependabot-private-dependencies/) in beta for GitHub's native dependabot, would you mind trying it there (you can migrate from Preview to Native on app.dependabot.com > "Create config file") and letting us know if it's fixed?

**Comment by gclair** [comment]
@asciimike  I thought we had configured our `dependabot.yml` correctly, however it seems not, and its along the same lines (using jfrog articfactory). Do we need an .npmrc at all or is the yaml enough?

```
version: 2
registries:
  npm-priv:
    type: npm-registry
    url: "https://<compname>.com/artifactory/api/npm/npm/"
    username: xxxxxxxxxxxxxxxxxxx
    password: ${{secrets.XXXXXXXXXXXXXXXXX}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-priv
    schedule:
      interval: "daily"
```
The checks complain about the URL.

```JavaScript registries must specify a url in a format like `https://registry.npmjs.org` or `https://npm.pkg.github.com`. Please don't include a path.```

However we seem to need the path.. is there a workaround for our setup?

**Comment by markcellus** [comment]
@gclair we seem to be having this same issue with our private npm registry artifactory. I opened https://github.com/dependabot/dependabot-core/issues/3281.

**Comment by JaredAAT** [comment]
> We [just launched support for private registries](https://github.blog/2021-03-15-dependabot-private-dependencies/) in beta for GitHub's native dependabot, would you mind trying it there (you can migrate from Preview to Native on app.dependabot.com > "Create config file") and letting us know if it's fixed?

@asciimike This is only for native Github?  If I'm using BitBucket or Gitlab (with dependabot-script) I can't yet setup access for private dependencies in npm?

**Comment by asciimike** [comment]
It is, though I assume that there's a reasonable chunk of the code in core that's shared (you'll mostly be responsible for your own secret management).

**Comment by timofloettmann** [comment]
@asciimike Sorry for the very delayed response. We've put this on hold for a while and I just got back to trying it again.

Using the native Github dependabot, this configuration works as expected:

```
version: 2
registries:
  jfrog:
    type: npm-registry
    url: https://<company>.jfrog.io/artifactory/api/npm/npm/
    username: ${{secrets.JFROG_USERNAME}}
    password: ${{secrets.JFROG_PASSWORD}}
updates:
  - package-ecosystem: 'npm'
    registries:
      - jfrog
    directory: '/'
    schedule:
      interval: 'daily'
```

There is no other configuration file necessary, no .npmrc, no .yarnrc
package.json and yarn.lock are both updated as expected in the PR.

From my side, this issue can be considered resolved.
