### ISSUE TITLE
GitHub Actions versions are bumped to pre-release versions

### ISSUE THREAD

**Issue by nihalgonsalves** [dependabot/dependabot-core#2718]
Dependabot seems to bump some GitHub Actions to their pre-release versions, notably `setup-node`.

**Package manager/ecosystem**

`github_actions`

**Manifest contents prior to update**

[Workflow file](https://github.com/nihalgonsalves/node-typescript-eslint-template/blob/main/.github/workflows/build.yml#L8-L11)

Relevant YAML:

```yaml
- name: Use Node.js 14.x
  uses: actions/setup-node@v1
  with:
    node-version: '14.x'
```

**Updated dependency**

> Bumps [actions/setup-node](https://github.com/actions/setup-node) from v1 to v2.1.2.

https://github.com/nihalgonsalves/node-typescript-eslint-template/pull/181

**What you expected to see, versus what you actually saw**

- Expected: `v1.4.4`, the latest release [here](https://github.com/actions/setup-node/releases)
- Actual: `v2.1.2 (beta)`, the pre-release [here](https://github.com/actions/setup-node/releases)

**Images of the diff or a link to the PR, issue or logs**

- [Dependabot config](https://github.com/nihalgonsalves/node-typescript-eslint-template/blob/main/.github/dependabot.yml#L7-L10)

    ```yaml
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
        interval: daily
    ```

- PR by Dependabot: https://github.com/nihalgonsalves/node-typescript-eslint-template/pull/181

**Other info**

Additionally, the addition of the version numbers (other than the major version) is a bit unexpected, since GitHub's own docs always use `@v1` / `@v2` / etc - thus staying on an automatic update of minor/patch versions. This would be my preferred behaviour too. Here's an issue that reports it: https://github.com/dependabot/dependabot-core/issues/2304

**Comment by peaceiris** [comment]
This is a duplicate of #2303 and #2304

**Comment by henryiii** [comment]
As a workaround, I've been using 

```yml
ignore:
  # Official actions have moving tags like v1
  # that are used, so they don't need updates here
  - dependency-name: "actions/*"
```

but for some reason that seems to be ignoring `jwlawson/actions-setup-cmake@v1.3`.
