### ISSUE TITLE
Select where to create branch from

### ISSUE THREAD

**Issue by jrock2004** [dependabot/dependabot-core#2721]
So what I am looking to see is the the following:

- Dependabot monitors my master package.json
- When an update is discovered, it creates a branch from master. Make the changes.
- Creates a PR to another branch that is different from master

Here is a thought config file

```
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  source-branch: Master
  target-branch: Develop
```

Thoughts?
