### ISSUE TITLE
Nested team as reviewer not tagged

### ISSUE THREAD

**Issue by frankkoornstra** [dependabot/dependabot-core#2758]
Looking at the documentation it seems possible to tag [teams as reviewers](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#reviewers) in PRs. That feature does, however, not seem to work for [_nested_ teams](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/about-teams#nested-teams).

For example: 
Our team is organized as follows `GetFeedback > platform > platform-java`

My configuration file is as follows:
```yaml
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Dependencies"
    reviewers:
      - "GetFeedback/platform-java"
...
```
But whenever a PR is opened by Dependabot, this team is not tagged (but labels are added, everything else seems to work). `GetFeedback/platform-java` is the value that is displayed at the team page and also works in manually tagging that team.

Let me end by saying your tool is an amazing asset to the development community, thank you for all the efforts!

**Package manager/ecosystem**
All
**Manifest contents prior to update**
Irrelevant
**Updated dependency**
Irrelevant
**What you expected to see, versus what you actually saw**
Nested team should be tagged while it is not
**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/4497278/99057618-566c5c00-259c-11eb-905d-e87ece4b4b41.png)
