### ISSUE TITLE
Ignoring target-branch

### ISSUE THREAD

**Issue by pepperrone** [dependabot/dependabot-core#2767]
With the following `dependabot.yml`:
```
version: 2
updates:
  # Updates for JS
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/deployment"
    schedule:
      interval: "daily"
    target-branch: "develop"

  # Updates for Java
  - package-ecosystem: "gradle"
    directory: "/api"
    schedule:
      interval: "daily"
    target-branch: "develop"
```

Dependabot is creating PRs against `master` instead of `develop` as seen here:
![image](https://user-images.githubusercontent.com/57622772/99239485-0804ca80-27f3-11eb-9610-784863e9e2b0.png)
