### ISSUE TITLE
[FR] Be able to configure `version_requirement_updates` differently for `production` and `development` dependencies

### ISSUE THREAD

**Issue by carusogabriel** [dependabot/dependabot-core#2779]
Hello there 👋 

First of all thanks for this amazing tool, we've been using it on https://github.com/usabilla, inside our private repositories, for a while now, since #1230 👌 

There's one feature that I'd like to share an idea with you about it: give the users the ability to configure the `version_requirement_updates` option differently for the two kinds of dependencies: `production` and `development`.

Something like this:

```yml
version: 1 # We are using `dependabot-preview` because of Private Repositories needs (see #2778 and https://github.com/dependabot/dependabot-core/issues/2297#issuecomment-655380840)
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "Dependencies"
    # version_requirement_updates: "auto" // This is how it's today
    version_requirement_updates:
      - match:
          dependency_type: "development"
          requirement_type: "increase_versions"
      - match:
          dependency_type: "production"
          requirement_type: "widen_ranges"
```

What do you think? And, can you point me to the code where I should do the change to propose a PR? :)
