### ISSUE TITLE
Add commit on dependabot pull request with github action

### ISSUE THREAD

**Issue by derTobsch** [dependabot/dependabot-core#2798]
Hey,
first of all thank you for the great work! I really like to use dependabot. Great piece of software.

We, at the https://github.com/synyx/urlaubsverwaltung, have a mechanism that adds an hash to different bundles to improve caching. These hashes will be updated e.g. if a dependency will be updated and used in a bundle. Now we want to directly change this hashes on the dependabot opened pull request with a github action. The steps that does this is first a `npm run build` and then we commit the possible changes with:

```yaml
      - name: Assets-Manifest commit
        if: contains(github.event.pull_request.labels.*.name, 'javascript')
        run: |
          git config --local user.name $someName
          git config --local user.email $someMail
          git diff --quiet --name-only src/main/webapp/WEB-INF/assets-manifest.json || (git add src/main/webapp/WEB-INF/assets-manifest.json; git commit -m  "Adapt assets-manifest")
      - name: Assets-Manifest push
        if: contains(github.event.pull_request.labels.*.name, 'javascript')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AM_PAT }}
          branch: ${{ github.head_ref }}
          repository: synyx/urlaubsverwaltung
```
see https://github.com/synyx/urlaubsverwaltung/blob/master/.github/workflows/maven.yml#L44  

If we do this a commit with the changes of the hash with be added and it seems to work, but it only seems to work. Because dependabot will everytime add a merge commit no matter if there is something to add or not see
https://github.com/synyx/urlaubsverwaltung/pull/1571/commits and the builds will stop.

So my question is, is there any other way to add a commit to a dependabot pull request without destrying it? :-)

Any hints are welcome!

**Comment by feelepxyz** [comment]
> So my question is, is there any other way to add a commit to a dependabot pull request without destrying it? :-)

If you prefix the new commit message with `[dependabot skip] ` dependabot rebases etc will still work, you'll need to re-run the action every time the PR changes so you apply your changes on top of the rebased PR.

We've got something like this setup internally as a trigger:

```yaml
name: Dependabot
on:
  push:
    branches:
      - "dependabot/bundler/**"
```
