### ISSUE TITLE
How to disable for a fork?

### ISSUE THREAD

**Issue by hugovk** [dependabot/dependabot-core#2804]
I enabled Dependabot for a fork (https://github.com/hugovk/pytest), to make sure it was working smoothly before creating a PR to add it upstream (https://github.com/pytest-dev/pytest). Upstream is now using it, it's working well, thanks!

However, I now want to disable Dependabot for my fork but cannot find a way.

https://app.dependabot.com/accounts/hugovk says:

> You've successfully migrated pytest to GitHub 🎉

![image](https://user-images.githubusercontent.com/1324225/100579683-4a4b0300-32ed-11eb-957e-994a6f53e948.png)

At https://github.com/settings/installations/8631454, Dependabot Preview only has access to other repos:

![image](https://user-images.githubusercontent.com/1324225/100579731-63ec4a80-32ed-11eb-954c-e26ad5ff271d.png)

At https://github.com/hugovk/pytest/settings/security_analysis I have everything disabled:

![image](https://user-images.githubusercontent.com/1324225/100579832-939b5280-32ed-11eb-82c7-d35eb75f5635.png)

Deleting https://github.com/hugovk/pytest/blob/master/.github/dependabot.yml is not an option, because this is a fork, and it needs to be kept in sync with upstream.

How can I disable Dependabot for my fork?

**Package manager/ecosystem**

Python

**Manifest contents prior to update**

```yml
version: 2
updates:
- package-ecosystem: pip
  directory: "/testing/plugins_integration"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
```
https://github.com/hugovk/pytest/blob/master/.github/dependabot.yml
https://github.com/hugovk/pytest/blob/master/testing/plugins_integration/requirements.txt
