### ISSUE TITLE
Ignore/Allow GitHub Actions workflow files by filename prefix

### ISSUE THREAD

**Issue by stone-z** [dependabot/dependabot-core#2857]
Similar to [this Community thread](https://github.community/t/dependabot-ignore-some-workflow/141986), we have particular GitHub Actions workflows which we manage centrally and would like to `ignore` in our dependabot config. Since we have several hundred repositories on which we're running Dependabot, each time a dependency in one of these workflows is updated, a whole bunch of PRs are opened. We then update the dependency centrally (we have some automation in place to re-generate the workflows) and the dependabot PRs auto-close, but it would be nice for us and the planet if we could save the compute time and just skip those dependencies.

There is no single central manifest for GitHub Actions, but in our case, the workflow files all have similar prefixes which [could be easily matched](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-file-paths). We'd like to be able to do something like the below, to ignore any workflow file which starts with `zz_generated`:

```
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    ignore:
      - file-name: "**/zz_generated*"
```
