### ISSUE TITLE
Dependabot updating dependencies from wrong package manager

### ISSUE THREAD

**Issue by amogkam** [dependabot/dependabot-core#2965]
We have recently added Dependabot for our [repo](https://github.com/ray-project/ray) and want to do pip updates only, but Dependabot is updating Java dependencies as well even though this is not configured.

Our [dependabot.yml](https://github.com/ray-project/ray/blob/master/.github/dependabot.yml) file looks like this:
```
version: 2
updates:
  # Tune/SGD/Doc requirements
  - package-ecosystem: "pip"
    # The requirements base directory currently only contains tune requirements.
    # If we want to add more requirements here (Core, RLlib, etc.), then we should make subdirectories for each one.
    directory: "/python/requirements"
    schedule:
      # TODO(amogkam) change this to weekly after some initial validation.
      interval: "daily"
      # 8 PM
      time: "20:00"
      # Use Pacific Standard Time
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "[tune]"
      include: "scope"
    # Only 3 upgrade PRs at a time.
    open-pull-requests-limit: 3
    reviewers:
      - "ray-project/ray-tune"
```
Only pip updates should be setup, but Dependabot has been creating PRs for Java updates and in a different directory than what's specified here.
https://github.com/ray-project/ray/pull/13316
https://github.com/ray-project/ray/pull/13317

Is there anything that's wrong with our yaml file? If Java package manager is not configured I would expect Dependabot not to make any PRs to update the Java dependencies.
