### ISSUE TITLE
dependabot adds in the PR only the first reviewer from reviewers list

### ISSUE THREAD

**Issue by van-mronov** [dependabot/dependabot-core#3115]
**Package manager/ecosystem**
mix

**What you expected to see, versus what you actually saw**
We noticed that dependabot adds only the first reviewer in the PR.
We would like to see all listed reviewers in PRs.

**Images of the diff or a link to the PR, issue or logs**

Here is the config we use:
```
version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "danbaranov"
      - "van-mronov"
```

And this is the example of PR created by dependabot.

<img width="1336" alt="Screenshot 2021-02-10 at 14 49 59" src="https://user-images.githubusercontent.com/550254/107518424-4241f600-6baf-11eb-81d6-f40330ef7520.png">
