### ISSUE TITLE
Invalid function npm:update error when updating javascript dependency

### ISSUE THREAD

**Issue by vviotto** [dependabot/dependabot-core#3158]
**Package manager/ecosystem**
javascript:npm

Hello, I'm trying to setup a pipeline in Azure Devops to run dependabot but the FileUpdater is throwing an error.
I'm running the pipeline inside a container job using the dependabot/dependabot-core docker image, and the dependabot-script to update the repo dependencies.
Is it possible that I might be missing the javascript native helper? Its weird because that shouldn't be the case when using the dependabot docker image.

This is the error:
```
Parsing dependencies information
  - Updating react-query (from 3.9.6)…/__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:111:in `run_helper_subprocess': Invalid function npm:update (Dependabot::SharedHelpers::HelperSubprocessFailed)
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:151:in `run_npm_top_level_updater'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:139:in `block in run_npm_updater'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:137:in `run_npm_updater'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:115:in `run_current_npm_update'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:35:in `block (2 levels) in updated_lockfile_content'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `chdir'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `block in updated_lockfile_content'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `chdir'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
	from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:30:in `updated_lockfile_content'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater.rb:187:in `updated_package_lock_content'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater.rb:120:in `package_lock_changed?'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater.rb:149:in `block in updated_lockfiles'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `each'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `updated_lockfiles'
	from /__w/1/s/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.118.8/lib/dependabot/npm_and_yarn/file_updater.rb:39:in `updated_dependency_files'
	from ./generic-update-script.rb:168:in `block in <main>'
	from ./generic-update-script.rb:130:in `each'
	from ./generic-update-script.rb:130:in `<main>'
```

For reference, this is my pipeline: (I'm cloning the dependabot-script repo for now, for testing purposes)
```yaml
trigger: none

variables:
  MAPPED_ACCESS_TOKEN: $(ACCESS_TOKEN) // secret variables need to be mapped first

jobs:
  - job: update_dependencies
    displayName: Update dependencies
    pool:
      vmImage: 'ubuntu-20.04'
    container: 
      image: dependabot/dependabot-core:latest
      env:
        AZURE_ACCESS_TOKEN: $(MAPPED_ACCESS_TOKEN)


    steps:
      - script: git clone https://github.com/dependabot/dependabot-script.git
        displayName: Cloning dependabot-script repo

      - script: bundle install -j 3 --path vendor
        displayName: Installing dependabot dependencies
        workingDirectory: dependabot-script/

      - script: bundle exec ruby ./generic-update-script.rb
        displayName: Updating dependencies
        workingDirectory: dependabot-script/
```

Thanks for the help =)
