### ISSUE TITLE
Nested dependencies .NET

### ISSUE THREAD

**Issue by liciniomendes** [dependabot/dependabot-core#3174]
I creating a library that has some sample projects and a test project. All of this is side by side with my library code. I find this a very common project structure for .NET. My library will be using `NET Standard 1.3` because we aim to use it in multiple `.NET` versions.

```text
my-project
├─ src/
│  ├─ my-lib/
├─ samples/
│  ├─ net5/
│  ├─ net452/
│  ├─ net472/
├─ tests/
│  ├─ net5/
```

Now I want to use `dependabot`,  and created a `dependabot.yaml`:
```yaml
version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/my-lib/
    schedule:
      interval: weekly
    ignore:
      - dependency-name: Microsoft.Extensions.*
        versions:
          - 2.*
          - 3.*
          - 5.*
```
Let's pick a simple example, my library uses `Microsoft.Extensions.Configuration` and the version that can be used with `NET Standard 1.3` is `1.1.1`. I can `ignore` the other versions in the configuration and that is nice. This will create a pull request to update  `Microsoft.Extensions.Configuration` to `1.1.2` because is the latest version. Works like a charm.

Now I need to find a way to do the same for test and sample projects, the obvious solution for me was:
```yaml
version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/my-lib/
    schedule:
      interval: weekly
    ignore:
      - dependency-name: Microsoft.Extensions.*
        versions:
          - 2.*
          - 3.*
          - 5.*
  - package-ecosystem: nuget
    # this app is running in .NET 5
    directory: /samples/sample-app
    schedule:
      interval: weekly
```
This will create pull requests for the needed dependencies in the `sample-app` and also in `my-lib`. Now I will have a pull request trying to update `my-lib` dependency  `Microsoft.Extensions.Configuration` to `5.0.0`  and this is wrong.

Tried to add an `ignore` to `my-lib` in the config file but it still checks the project.

Is there something that I am missing that allows ignoring nested projects/dependencies?
