### ISSUE TITLE
[Feature] Update Docker images in docker-compose.yml

### ISSUE THREAD

**Issue by Divlo** [dependabot/dependabot-core#3189]
Hey 👋,

Thanks for this awesome `dependabot`, I use it in nearly every GitHub repo. :+1: 

As it is in this page : https://dependabot.com/docker/
It seems like `dependabot` only update `Dockerfile` but it doesn't update `docker-compose.yml`, it is also something I noticed.

For example, I have a repo with this kind of config in the `docker-compose.yml` file :
```yaml
version: '3.0'
services:
  database:
    image: 'mysql:8.0.23' # It could be cool if `dependabot` could look for updates
    # there are other configs here, but to stay simple, I only set the `image` property
```

Currently, I must myself update the `mysql` image, also I could miss important security updates etc.
