### ISSUE TITLE
Dependabot unnecessary PRs for GitHub created actions

### ISSUE THREAD

**Issue by aleks-ivanov** [dependabot/dependabot-core#3194]
**Package manager/ecosystem**
github-actions

**Updated dependency**
Any action created by GitHub

**What you expected to see, versus what you actually saw**
In the actions created by GitHub, the developers have implemented a feature that when an action of theirs is used by referring only the major version i.e. **actions/checkout@v2**, the "@v2" refers to the latest version with that major number i.e. "v2" refers to "v2.3.4".

Now Dependabot creates PRs bumping the version of these actions from major version to latest version i.e. "v2" to "v2.3.4", which doesn't do anything for actions created by GitHub.

Dependabot should create PRs for those actions, ONLY when a new major version is available i.e. if the pipeline uses **actions/checkout@v1** and the latest version is "v2.3.4", Dependabot should create a PR with **actions/checkout@v2**.

**Images of the diff or a link to the PR, issue or logs**
https://github.com/aleks-ivanov/RestSharp/pull/2

**Comment by AraHaan** [comment]
I agree it is annoying as fuck.

**Comment by lucacome** [comment]
This happens for other dependencies too, for example, dependabot wants to update `go` from `1.15` to `1.16.0`.
I'd love to see this fixed.

**Comment by asciimike** [comment]
As I understand it, the request here is, "only upgrade major versions" as opposed to a bug, "Dependabot is updating the wrong thing" (because it's not--it's supposed to update to the latest version; major, minor, or patch that it sees when it runs the update).

If you'd like to change the behavior, you can add an [`ignore`](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#ignore) to your `update`:

```yaml
updates:
  package-ecosystem: "github-actions"
  directory: "/.github/workflows"
  schedule:
    interval: "weekly"
  ignore:
    dependency-name: "actions/checkout"
    versions: ["v1", "v2"]
```

Though, to be fair, I don't entirely remember how Actions versioning works (I think they're just tagged releases, so I'm not sure how we treat versions).

**Comment by AraHaan** [comment]
they are tagging releases tbh.

**Comment by asciimike** [comment]
I think it makes sense for Actions developers to tag all releases, so that folks who want granular updates can get them. Dependabot should provide an opt-out mechanism like we have with `ignore` to allow folks to pick and choose. If the above isn't working correctly, that sounds like an issue for us to fix.

**Comment by lucacome** [comment]
Sorry, maybe I hijacked the wrong issue but what I was saying about other dependencies is if I have for example in docker `FROM alpine:3.9` it means that I don't care about patch releases, so I wouldn't want dependabot to update to `FROM alpine:3.10.0` and have it triggered for every `3.10.x` version.

**Comment by asciimike** [comment]
Is that not the same general solution?

```yaml
updates:
  package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    dependency-name: "alpine"
    versions: ["3.x"]
```

Again, version syntax may differ slightly.

This would allow a bump to `FROM alpine:4.0` but not to `FROM alpine:3.0` which seems to be the behavior described?
