### ISSUE TITLE
"interval: daily" checks are not run.

### ISSUE THREAD

**Issue by oittaa** [dependabot/dependabot-core#3206]
**Package manager/ecosystem**

pip, docker, github-actions
**Manifest contents prior to update**

**Updated dependency**

**What you expected to see, versus what you actually saw**

The checks are configured to be run daily, but it has been over 3 days since they were run the last time.
**Images of the diff or a link to the PR, issue or logs**

```yaml
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
```
https://github.com/oittaa/gcp-storage-emulator/
https://github.com/oittaa/gcp-storage-emulator/blob/97ccaa6953f4d6f4e855bb8c88597959447e8a7c/.github/dependabot.yml

<img width="1397" alt="Screenshot 2021-02-28 at 20 05 11" src="https://user-images.githubusercontent.com/8972248/109430228-8c750500-7a00-11eb-8753-e73b34ffb92c.png">
