### ISSUE TITLE
Scheduling for specific dependencies?

### ISSUE THREAD

**Issue by saschanaz** [dependabot/dependabot-core#3240]
Some dependencies may directly impact the feature of the package and while others not. I want to be notified ASAP when updates happen for those important dependencies while just monthly for others.

**Comment by xlgmokha** [comment]
@saschanaz Are you saying that you would like to schedule dependency intervals differently for different groups of dependencies. 

E.g. monthly for development dependencies and daily for production dependencies?

**Comment by saschanaz** [comment]
Yup, exactly. Not necessarily a production dependency, though.

**Comment by asciimike** [comment]
@saschanaz I think the right answer is [`allow`](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#allow) and have multiple updates:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "production"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "development"
    schedule:
      interval: "weekly"
```

You can also select individual dependencies to set different update frequencies on.

Closing this, but feel free to re-open if it's doesn't work in this case.
