### ISSUE TITLE
Feature request: notify when/before the dependency EOL

### ISSUE THREAD

**Issue by missedone** [dependabot/dependabot-core#3242]
We have a lot of Java projects and most of them use Spring Framework or Spring Boot.
For example, we're using Spring Boot 2.3.8, and configured dependabot to report new version of 2.3.x only:
```
version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  - dependency-name: "org.springframework.boot:*"
    versions: [">=2.4"]
```
however, 2.3.x is going to EOL at May 2021, we didn't know until checked the doc https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#released-versions
with the above dependabot config, we won't receive any notification of new version even current version is EOL in future.

so can dependabot notify when (or even better, before) the dependency gets EOL?
i know it maybe a little bit hard to implement, since you have to build database (or at least grab the data) of EOL info of the components.

the above is just an example of Spring Boot of the Java projects, the same concept can be applied to other frameworks, language, etc.
