### ISSUE TITLE
Gradle subprojects

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [dependabot/dependabot-core#3254]
I am only getting updates for the root `build.gradle.kts` file, but I am seeing other projects that can get updates for all subprojects `build.gradle.kts`

Is dependabot searching in `settings.gradle.kts` file where are the subprojects? This is a problem because I can have a plugin/algorithm that auto-include all subprojects without indicating them manually with `include(":some-subproject")`.

Should be great that I can just use a wildcard pattern but it doesn't work for me:

```
version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/**/*/"
    schedule:
      interval: "daily"
```
