### ISSUE TITLE
Improve what version should be picked

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [dependabot/dependabot-core#3255]
Currently, I am seeing multiple issues:

1.
```
- val coroutines = "1.4.3"
+ val coroutines = "1.4.3-native-mt"
```

2.
```
val dokka = "1.4.20"
val dokka = "1.4.20-dev-65"
```

The first one really is mixing a version from "different libs" caused by how coroutines library is releasing the artifact.

The second one is using a dev version that can't be even used in the project because it hasn't the necessary repository.

I can understand that here we can have a real problem about how to solve this issue in a generic way because some libs can use semantic versioning, but, as a workaround, why just don't let the user specify a regex?

It allows filtering unnecessary versions and it can be modified to allow a custom approach for those versions that don't follow semantic versioning.

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
	version-regex: "..."
    schedule:
      interval: "daily"
```
