### ISSUE TITLE
Unquoted time of day treated as integer when parsing configuration

### ISSUE THREAD

**Issue by l0b0** [dependabot/dependabot-core#3263]
To reproduce:

1. Commit the following dependabot configuration ([original](https://github.com/linz/geospatial-data-lake/blob/4c2f2eae09eb5abe468016491742662bd156dc82/.github/dependabot.yml)), formatted by [`pretty-format-yaml`](https://github.com/macisamuele/language-formatters-pre-commit-hooks):
   ```
   version: 2
   updates:
   - package-ecosystem: pip
     directory: /
     schedule:
       interval: weekly
       day: friday
       time: 15:00
       timezone: Pacific/Auckland
   ```
2. Run dependabot

[Result](https://github.com/linz/geospatial-data-lake/pull/387/checks?check_run_id=2090992426):

> The property '#/updates/4/schedule/time' of type integer did not match the following type: string

I thought this might be a bug in `pretty-format-yaml`, but then again I wouldn't expect `15:00` to be treated like an integer.
