### ISSUE TITLE
Error when specifying private JavaScript registry URL 

### ISSUE THREAD

**Issue by markcellus** [dependabot/dependabot-core#3281]
**Package manager/ecosystem**
private npm/artifactory

Getting the following error when trying to use our private npm registry artifactory.

```bash
JavaScript registries must specify a url in a format like `https://registry.npmjs.org` or `https://npm.pkg.github.com`. Please don't include a path.
```

Here is our `.github/dependabot.yml` config using Github-native dependabot:

```yml
version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://artifacts.<xxxx>/artifactory/api/npm/npm
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_PASSWORD}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```

**Comment by jurre** [comment]
I think this should work if you remove the `artifactory/api/npm/npm` part from the URL. The full URL is specified in the package.json and it should be what is used to resolve the dependency, this config is just used to pull in the right credentials.

Have you tried this and ran into something?

**Comment by gclair** [comment]
The path is necessary when using jfrog artifactory. Not everyone is going to have a straight url with no path to use. 

https://www.jfrog.com/confluence/display/JFROG/npm+Registry

```
Npm repositories must be prefixed with api/npm in the path

When accessing an npm repository through Artifactory, the repository URL must be prefixed with api/npm in the path. This applies to all npm commands including npm install and npm publish.

For example, if you are using Artifactory standalone or as a local service, you would access your npm repositories using the following URL:

    http://localhost:8081/artifactory/api/npm/<repository key>

Or, if you are using Artifactory Cloud, the URL would be:

    https://<server name>.jfrog.io/artifactory/api/npm/<repository key>
```

**Comment by jurre** [comment]
Yes, but the full artifactory path should already be specified in the `.npmrc` / `package{-lock}.json`, for the dependency resolution it is not configured from the dependabot.yml. The dependabot config is just a mapping to grab the secrets from, please give it a go with removing this from the dependabot config.

**Comment by markcellus** [comment]
Oh I see @jurre. So you're saying as long as the full path is specified in npmrc file, we can remove the trailing path at the end of `registries.npm-npmjs.url`?

**Comment by jurre** [comment]
> Oh I see @jurre. So you're saying as long as the full path is specified in npmrc file, we can remove the trailing path at the end of `registries.npm-npmjs.url`?

Yep! We may need to improve the docs here if this is not intuitively clear, especially in the case of Artifactory I get that this seems to contradict their docs

**Comment by jeffhubLR** [comment]
Also using Artifactory.
I removed the path from the registry definition in the dependabot.yml but still received this error from the Dependabot check:

Dependabot can't authenticate to a private package registry
The following private package registry was used and caused the update to fail: redacted.jfrog.io/full/path/redacted.

Can you explain exactly what is necessary to get this to work? All frontend code is in a subfolder. Our dependabot.yml is as follows:
```
version: 2
registries:
  npm-REDACTED-artifactory:
    type: npm-registry
    url: https://REDACTED.jfrog.io
    token: ${{secrets.ARTIFACTORY_NPM_TOKEN}}

updates:
  - package-ecosystem: "npm"
    directory: "/front-end" # Location of package manifests
    registries:
      - "npm-REDACTED-artifactory"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
```

The yarn.lock _does_ have the full path of all dependencies.

We have an `.npmrc` file in the front-end directory which I'm thinking _may_ be the culprit, but an understanding of what this should look like for Dependabot to appropriately be able to access the private NPM repo would be appreciated. This file is currently targeted at allowing frontend developers to just configure some environment variables to get things to work.
```
_auth=${ARTIFACTORY_NPM_AUTH}
always-auth=true
email=${ARTIFACTORY_USERNAME}
registry=https://REDACTED.jfrog.io/full/path/redacted/
@REDACTED:registry=https://REDACTED.jfrog.io/full/path/redacted/
```

Any clarification or help would be MUCH appreciated. We are really excited to have private registry support available, and just need some pointers to get it working for us. Thanks!

**Comment by ericmatthys** [comment]
I'm seeing a similar issue with an artifactory registry. Currently we are successfully using dependabot.com with its config variables. I'm trying to switch to github native dependabot now that there is private registry support, but running into an issue.

```yml
version: 2
registries:
  artifactory:
    type: npm-registry
    url: https://artifactory.example.bz
    token: ${{secrets.ARTIFACTORY_TOKEN}}
updates:
  - package-ecosystem: "npm"
    registries:
      - artifactory
    directory: "/"
    schedule:
      interval: "daily
```

In the dependabot logs, I can see that if a dependency is on the latest version, everything looks healthy. If a dependency is out of date, there are 404s.

```
updater | INFO <job_96642593> Checking if html-webpack-plugin 5.3.1 needs updating
  proxy | 2021/03/16 22:58:33 [228] GET https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/html-webpack-plugin
  proxy | 2021/03/16 22:58:33 [228] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/16 22:58:34 [228] 200 https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/html-webpack-plugin
  proxy | 2021/03/16 22:58:34 [230] GET https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/html-webpack-plugin/5.3.1
  proxy | 2021/03/16 22:58:34 [230] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/16 22:58:34 [230] 200 https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/html-webpack-plugin/5.3.1
updater | INFO <job_96642593> Latest version is 5.3.1
updater | INFO <job_96642593> No update needed for html-webpack-plugin 5.3.1

updater | INFO <job_96642593> Checking if @types/react-redux 7.1.5 needs updating
  proxy | 2021/03/16 22:58:07 [214] GET https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/@types%2Freact-redux
  proxy | 2021/03/16 22:58:07 [214] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/16 22:58:07 [214] 200 https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/@types%2Freact-redux
  proxy | 2021/03/16 22:58:07 [216] GET https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/@types%2Freact-redux/7.1.16
  proxy | 2021/03/16 22:58:07 [216] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/16 22:58:07 [216] 200 https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/@types%2Freact-redux/7.1.16
updater | INFO <job_96642593> Latest version is 7.1.16
  proxy | 2021/03/16 22:58:09 [218] GET https://artifactory.example.bz:443/@types%2freact-redux
  proxy | 2021/03/16 22:58:09 [218] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/16 22:58:09 [218] 404 https://artifactory.example.bz:443/@types%2freact-redux
updater | INFO <job_96642593> Requirements to unlock own
updater | INFO <job_96642593> Requirements update strategy bump_versions
updater | INFO <job_96642593> Updating @types/react-redux from 7.1.5 to 7.1.16
  proxy | 2021/03/16 22:58:10 [220] GET https://artifactory.example.bz:443/@types%2freact-redux
  proxy | 2021/03/16 22:58:10 [220] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/16 22:58:10 [220] 404 https://artifactory.example.bz:443/@types%2freact-redux
  proxy | 2021/03/16 22:58:22 [222] GET https://artifactory.example.bz:443/@types%2freact-redux
  proxy | 2021/03/16 22:58:22 [222] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/16 22:58:22 [222] 404 https://artifactory.example.bz:443/@types%2freact-redux
  proxy | 2021/03/16 22:58:28 [224] GET https://artifactory.example.bz:443/@types%2freact-redux
  proxy | 2021/03/16 22:58:28 [224] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/16 22:58:28 [224] 404 https://artifactory.example.bz:443/@types%2freact-redux
updater | INFO <job_96642593> Handled error whilst updating @types/react-redux: private_source_authentication_failure {:source=>"artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache"}
```

The entry in `yarn.lock` looks like:

```
"@types/react-redux@7.1.5":
  version "7.1.5"
  resolved "https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/@types/react-redux/-/react-redux-7.1.5.tgz#c7a528d538969250347aa53c52241051cf886bd3"
  integrity sha1-x6Uo1TiWklA0eqU8UiQQUc+Ia9M=
  dependencies:
    "@types/hoist-non-react-statics" "^3.3.0"
    "@types/react" "*"
    hoist-non-react-statics "^3.3.0"
    redux "^4.0.0
```

**Comment by Lykathia** [comment]
Seeing the same as @ericmatthys

#3292 was closed pointing to here as a resolution, but, it appears to me to be more than just clarification required. It seems like a defect?

**Comment by markcellus** [comment]
Getting this error too. Never got it to work. 

@jurre it doesn't even seem like it's picking up the credentials in the `dependabot.yml` file. Is it possible that putting your dependabot secrets under "Dependabot" section is what's causing it? We have our `registries.npm-npmjs` fields set to:

```yml
username: ${{secrets.ARTIFACTORY_USERNAME}}
password: ${{secrets.ARTIFACTORY_PASSWORD}}
```

But our dependabot secrets are stored in Github settings under "Secrets -> Dependabot" instead of just "Secrets". So shouldn't these values be something similar to the following?

```yml
username: ${{secrets.dependabot.ARTIFACTORY_USERNAME}}
password: ${{secrets.dependabot.ARTIFACTORY_API_KEY}}
```

**Comment by pstepniewskiconfigit** [comment]
@jurre but not every registry have `package-lock.json` or `yarn.lock`

**Comment by jurre** [comment]
> @jurre but not every repository have package-lock.json or yarn.lock commited in their source code or .npmrc with defined scoped registry there.

How would other developers or your CI know which registry to use in that case? The information needs to be encoded somewhere, and it's not a dependabot specific thing, right?

**Comment by drochow** [comment]
Hey, 

not sure if we should open a new issue,  we got this error here: 

`The property '#/registries/fast' of type object did not match one or more of the required shemas'`

Using the following config: 

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - "fast"
    schedule:
      interval: "daily"
      time: "11:30"
    target-branch: "prototype.base"
    commit-message:
      prefix: "proto.base"
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - "fast"
    schedule:
      interval: "daily"
      time: "11:30"
    target-branch: "prototype.api-gateway.base"
    commit-message:
      prefix: "proto.api-gw"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:30"
    registries:
      - "fast"
    target-branch: "api-gateway"
    commit-message:
      prefix: "api-gw"
registries:
  fast:
    type: npm-registry
    url: 'https://fast.xxx.xxx.com'
    username: dependabot
    token: ${{secrets.DEPENDABOT_FAST_PASS}}
```

Best

**Comment by pstepniewskiconfigit** [comment]
> > @jurre but not every repository have package-lock.json or yarn.lock commited in their source code or .npmrc with defined scoped registry there.
> 
> How would other developers or your CI know which registry to use in that case? The information needs to be encoded somewhere, and it's not a dependabot specific thing, right?

This information is stored in global `.npmrc` which is located in user home directory, and it uses scopes to determine which packages should be installed from which registry.

**Comment by pstepniewskiconfigit** [comment]
@drochow Because you should use just token or combination username with password

Please look [here](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#npm-registry) at docs.

**Comment by jurre** [comment]
> This information is stored in global .npmrc which is located in user home directory, and it uses scopes to determine which packages should be installed from which registry.

You'll need to add the npmrc with that config to the repo as well. Npm needs to be configured in a way to pull these dependencies from the registry, and the dependabot config is only there to wire up the secrets. We'll make sure to clarify this further in our docs

**Comment by pstepniewskiconfigit** [comment]
@jurre but still this sounds like a hack to me. Why you can't expose schema like the one below? Also allowing for path in url. We don't request it immediately but as iteration of this feature.

```yaml
version: 2

registries:
  npm:
    type: npm-registry
    url: https://packages.example.com/npm/npm/
    scopes:
      - @org-name
      - @other-org-name
    token: ${{ secrets.NPM_AUTH_TOKEN }}
```

**Comment by jurre** [comment]
> @jurre but still this sounds like a hack to me. 

I don't see how this is a hack? It us how you configure npm to reach private registries. Dependabot pulls this file in and uses it to run npm.

> Why you can't expose schema like the one below?

It's technically possible but it's non-standard, dependabot specific and we would need to have a different configuration syntax for every ecosystem. Npm already has a solution for this, reusing this seems like the right thing to do.

**Comment by pstepniewskiconfigit** [comment]
@jurre yes it have solution for that, and it's the one that I'm speaking of. Please read this document https://docs.npmjs.com/cli/v7/using-npm/scope#associating-a-scope-with-a-registry

**Comment by markcellus** [comment]
This works for me after removing the path as suggested in https://github.com/dependabot/dependabot-core/issues/3281#issuecomment-800370402, so closing. 

FWIW, @pstepniewskiconfigit the schema you are proposing seems a lot simpler and how I would expect it to work. If you should ever create a new issue for your proposal, I would upvote it 🙂

**Comment by markcellus** [comment]
@jurre @jasonrudolph 

I must reopen this because I thought it was working but it appears that it's 404'ing the packages now because the path in the .npmrc file isn't being used. @jurre explained in above in https://github.com/dependabot/dependabot-core/issues/3281#issuecomment-800323539 that we must remove the path from the `registries.npm.url` and that it would pick up the path from the .npmrc file. But doesn't look like its working.

Here are contents of `.npmrc` file in the repository:

```bash
registry=https://<artifactory_url>/artifactory/api/npm/npm
```

Here is dependabot.yml config:

```yml
version: 2
registries:
  npm:
    type: npm-registry
    url: <artifactory_url>
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_PASSWORD}}
updates:
  - package-ecosystem: 'npm'
    registries: 
      - 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```
