### ISSUE TITLE
Add a way to add the child workspace name in the commit message scope

### ISSUE THREAD

**Issue by felipecrs** [dependabot/dependabot-core#3282]
I use dependabot with semantic-release, so it pushes PRs following Conventional Commits. However, in my repo, I'm using NPM v7 with workspaces, with the following structure:

```
| package.json
| package-lock.json
| website/
    | package.json 
```

I configured my semantic-release to create new patch releases every time a PR with `build(deps)` but not `build(deps-dev)` is pushed. However, currently, the commit message does not point which workspace the dependency is being updated, and I would not like to release new patch versions for dependencies upgraded in the `website` workspace.

So, it would be very useful to have a feature like:

```yaml
commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope-and-child-workspace"
```

Which would generate commit messages like:

For root's project:

```
build(deps): bump [...]
build(deps-dev): bump [...]
```

For the child website project:

```
build(website-deps): bump [...]
build(website-deps-dev): bump [...]
```

My repo can be found at https://github.com/felipecrs/megatar.
