### ISSUE TITLE
Multiple PRs being opened for the same project and dependency for wrong path

### ISSUE THREAD

**Issue by mairaw** [dependabot/dependabot-core#3287]
**Package manager/ecosystem**
NuGet
**What you expected to see, versus what you actually saw**
Here's my yml file
```
version: 2
updates:
- package-ecosystem: npm
  directory: "/src/netlandingpage"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/netlandingpage"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/netlive/Client"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/netlive/Shared"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
```

Dependabot opened a PR for each path I have enabled on my yml file, even though that dependency was only present in src/Common
![image](https://user-images.githubusercontent.com/12971179/111400919-8714ed00-8685-11eb-8645-78dfb8a7da77.png)

The contents of each PR was exactly the same.
![image](https://user-images.githubusercontent.com/12971179/111401050-c3484d80-8685-11eb-8094-dc0f4cb4d07e.png)
