### ISSUE TITLE
Getting 401 errors when using secrets

### ISSUE THREAD

**Issue by markcellus** [dependabot/dependabot-core#3293]
**Package manager/ecosystem**
private npm/artifactory

Getting a lot of 401 errors when using secrets in `dependabot.yml` file. Here's [log](https://github.com/AudaxHealthInc/chatterbox-ui/network/updates/96791357).

Here is our `.github/dependabot.yml` config using Github-native dependabot:

```yml
version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: <artifactory_url>
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_PASSWORD}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```

I verified the credentials work in a `curl` but it doesn't even seem like it's picking up the credentials in the `dependabot.yml` file.

**Comment by markcellus** [comment]
Is it possible that putting your dependabot secrets under "Dependabot" section is what's causing it? We have our `registries.npm-npmjs` fields set to:

```yml
username: ${{secrets.ARTIFACTORY_USERNAME}}
password: ${{secrets.ARTIFACTORY_PASSWORD}}
```

But our dependabot secrets are stored in Github settings under "Secrets -> Dependabot" instead of just "Secrets". So shouldn't these values be something similar to the following?

```yml
username: ${{secrets.dependabot.ARTIFACTORY_USERNAME}}
password: ${{secrets.dependabot.ARTIFACTORY_PASSWORD}}
``` 
I don't know if that would fix the issue but just wondering...

**Comment by jasonrudolph** [comment]
👋 @markcellus: It looks like the `updates` section is missing a [`registries` entry](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#configuration-options-for-private-registries). I'll try to explain. 😅

At the top level, you've got the list of available registries defined. (Great!)

```yaml
registries:
  npm-npmjs:
    type: npm-registry
    url: <artifactory_url>
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_PASSWORD}}
```

Then, for each entry in the `updates` array, you'll need to specify which registries are available to that entry.

In your case, you could list the registry by name like so:

```yaml
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    registries: # <=====
    - npm-npmjs # <=====
```

Or, you can give access to all registries like so (which will automatically include any registries you add to the top-level `registries` section in the future):

```yaml
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    registries: "*" # <=====
```

Can you give that a try? 

I think that will resolve the issue for you, so I'm going to close this out. If it doesn't resolve the issue, please reply to let us know, and we'll reopen this issue.
