### ISSUE TITLE
API for setting dependabot secrets

### ISSUE THREAD

**Issue by j3parker** [dependabot/dependabot-core#3297]
Follow up to #2311
(Sorry -- I guess this is more of a GitHub feature but this repo seemed kind of appropriate? LMK if it should go somewhere else.)

We are using [AWS CodeArtifact](https://aws.amazon.com/codeartifact/) for our packages (NPM, NuGet, etc.) The tokens used to access codeartifact are [limited to a maximum 12 hour lifetime](https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_GetAuthorizationToken.html) (which is cool).

To deal with this we'd like to update the secret periodically (e.g. every 6 hours). Unfortunately, I can't find any documented API to set these secrets, just the UI. I checked the [org actions secrets](https://docs.github.com/en/rest/reference/actions#list-organization-secrets) API and as expected the Dependabot secrets do not show up there.

Are there plans to launch an API for this? Would it be possible to get access to a beta/alpha for them? We are willing to deal with unannounced breaking changes during an alpha 😃 

Really excited for this feature! Dependabot has been great.

**Comment by asciimike** [comment]
@j3parker I've got an internal issue tracking adding this, so it's on the roadmap, don't worry!

**Comment by asciimike** [comment]
As a quick update, there are something like 19 different endpoints that need to be copied, and we're still working on where exactly to put them (you may have already noticed that there's no "dependabot" API, things are scattered around a bit). It's not likely this is going to make it into GA, but I promise that I'm working on it and hope to have a solution for folks soon!

**Comment by asciimike** [comment]
@GaboFDC nothing yet, unfortunately. For my curiosity: what secrets are you setting that need to be dynamic?

**Comment by tiltier** [comment]
I'm not @GaboFDC , but in a similar situation as the one mentioned in the original issue description: We use AWS CodeArtifact, tokens only live for 12 hours. It's impractical to keep this updated manually.

**Comment by jeffgran** [comment]
We are using dependabot secrets to provide credentials to our private rubygems/npm/etc registry. We regularly rotate these secret credentials and would have to update these secrets manually without an API.

**Comment by GaryGSC** [comment]
In our case, we have AWS account credentials as organization secrets that we share with individual repos [via API](https://docs.github.com/en/rest/reference/actions#add-selected-repository-to-an-organization-secret). We rotate those credentials. Right now, there's no way to programmatically give Dependabot access to those secrets, which makes it difficult to interact with AWS in CI on Dependabot PRs. This'll become increasingly important as we try to adopt Dependabot for Terraform. ([roadmap](https://github.com/github/roadmap/issues/191)/[related issue](https://github.com/dependabot/dependabot-core/issues/1176))

**Comment by alexef** [comment]
@asciimike any update here 🙏 ? this blocks our migration from Nexus to AWS CodeArtifact, and having an idea if this is going to be fixed sooner rather than later can help us to make a decision.

**Comment by asciimike** [comment]
@alexef unfortunately no updates, as the team currently has some other priorities. I'm chatting with some other teams at GitHub to see if they can help us out, and I'll update this issue as soon as there's movement.

**Comment by daniel-ciaglia** [comment]
2 months gone - anything we can do to update the token ourself?

**Comment by joshgubler** [comment]
With [the change to GitHub Actions and Dependabot Secrets](https://github.blog/changelog/2021-11-30-github-actions-workflows-triggered-by-dependabot-receive-dependabot-secrets/) today, did this issue see any progress?

**Comment by jurre** [comment]
I don't have anything to share in terms of roadmap, but this a still feature we are interested in shipping. That change to Actions secrets is mostly unrelated.

**Comment by JeffAshton** [comment]
Of the 19 different endpoints, could just the ones required to update a secret be prioritized?  Adding and removing are nice to have but likely not as impacting for everyone.

**Comment by dcrdev** [comment]
Also using CodeArtifact - set up a nice little scheduled Github action to set the token and then realised Dependabot secrets != Github secrets.

Like @JeffAshton said can you please prioritise this endpoint? I imagine that there are a lot of enterprise registries that have short lived tokens and this is a real blocker.

**Comment by jurre** [comment]
This API is now available: https://docs.github.com/en/rest/reference/dependabot

**Comment by EwiththeBowtie** [comment]
NOTE: Dependabot users attempting to use dynamic secrets with AWS CodeArtifact and poetry.

Despite AWS referring to the CodeArtifact token as a token in their documentation, it behaves as a password for the 'aws' username. Twine has similar behavior.

```
version: 2
registries:
  python-codeartifact:
    type: python-index
    url: <YOUR_CODEARTIFACT_PIPY_URL>
    username: aws
    password: ${{secrets.<YOUR_DYNAMICALLY_UPDATED_TOKEN>}}
```
How do we get this added to the Dependabot documentation?

**Comment by JeffAshton** [comment]
> NOTE: Dependabot users attempting to use dynamic secrets with AWS CodeArtifact and poetry.
> 
> Despite AWS referring to the CodeArtifact token as a token in their documentation, it behaves as a password for the 'aws' username. Twine has similar behavior.
> 
> ```
> version: 2
> registries:
>   python-codeartifact:
>     type: python-index
>     url: <YOUR_CODEARTIFACT_PIPY_URL>
>     username: aws
>     password: ${{secrets.<YOUR_DYNAMICALLY_UPDATED_TOKEN>}}
> ```
> 
> How do we get this added to the Dependabot documentation?

This really feels like a specific CodeArtifact detail.  One thing we learned though, was that in order to pull changes from both our private repository and the public one, we also needed to define the public one explicitly.

**Comment by jurre** [comment]
@EwiththeBowtie that seems like something that should be covered in the CodeArtifact docs instead of the Dependabot docs? Dependabot will dutifully use whatever credentials are provided to it

**Comment by armandobelardo** [comment]
Sorry to for the ping on a closed issue, but @jurre can we pass in a secret to the registry URL?
The config as 
```
version: 2
registries:
  private-npm:
    type: npm-registry
    url: ${{secrets.CODE_ARTIFACT_NPM_URL}}
    username: aws
    password: ${{secrets.CODE_ARTIFACT_TOKEN}}
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    registries:
      - private-npm
```
gets this error ```JavaScript registries must specify a url in a format like `https://registry.npmjs.org` or `https://npm.pkg.github.com`.``` almost as if it's reading the secret config as a string and not injecting in the actual secret. Taking the secret value and plugging it directly into config works as expected.

For context, we're looking to use a secret so we can dynamically set our registries from some central IaC so we're not referencing the account number and repo names in a bunch of different places out right.

**Comment by aphexlog** [comment]
I am also having this problem, with the token url combo:
```
version: 2
registries:
  npm-codeartifact:
    type: npm-registry
    url: https://BLAHHH.d.codeartifact.us-west-2.amazonaws.com
    token: ${{secrets.CODE_ARTIFACT_TOKEN}}
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    registries:
      - npm-codeartifact
      ```
      
  when dependabot runs I just see a bunch of calls to npmjs site:
  
  ` proxy | 2022/06/30 16:48:20 [194] 200 https://registry.npmjs.org:443/strip-bom`

**Comment by aphexlog** [comment]
> I too am having seeing this issue with the token / url combo:
> 
> ```
> version: 2
> registries:
>   npm-codeartifact:
>     type: npm-registry
>     url: https://BLAHHH.d.codeartifact.us-west-2.amazonaws.com
>     token: ${{secrets.CODE_ARTIFACT_TOKEN}}
> updates:
>   # Keep npm dependencies up to date
>   - package-ecosystem: 'npm'
>     directory: '/'
>     schedule:
>       interval: 'daily'
>     registries:
>       - npm-codeartifact
> ```
> 
> when dependabot runs I just see a bunch of calls to the public npm registry:
> 
> ` proxy | 2022/06/30 16:48:20 [194] 200 https://registry.npmjs.org:443/strip-bom`

nvm.. I forgot to merge my changes to my lock.json file which had the new mappings to the codecommit registry. Verified the above works. (P.S. I did actually start out with the exact same issue as the OP)

**Comment by caevv** [comment]
I must be so stupid, I tried with token and all sort of tokens in every shape and won't just work :
```
  npm-codeartifact:
    type: npm-registry
    url: https://##-##.d.codeartifact.eu-west-2.amazonaws.com (also tried adding "/npm/private-npm-store/")
    token: ${{secrets.CODEARTIFACT_TOKEN}}
```

**Comment by aphexlog** [comment]
@caevv you do not need the `/npm/private-npm-store/` .. fyi, code artifact tokens expire in 12 hours by default. try getting a new token. The fallowing version of what you have will work if the correct token is provided:
```
  npm-codeartifact:
    type: npm-registry
    url: https://##-##.d.codeartifact.eu-west-2.amazonaws.com
    token: ${{secrets.CODEARTIFACT_TOKEN}}
```

**Comment by caevv** [comment]
I do exactly this:

```yml
registries:
  npm-codeartifact:
    type: npm-registry
    url: https://##-##.d.codeartifact.eu-west-2.amazonaws.com
    token: ${{secrets.CODEARTIFACT_TOKEN}}

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - npm-codeartifact
```

Then I go to the repo on dependabot secrets and update the variable `CODEARTIFACT_TOKEN ` with the result of this:

```
aws codeartifact get-authorization-token --domain ## --domain-owner ## --query authorizationToken --output text --profile ##
```

I still get:

```
proxy | 2022/06/29 16:52:06 [024] 401 https://###-###.d.codeartifact.###.amazonaws.com:443/npm/private/hermes-engine
updater | INFO <job_408163671> Handled error whilst updating hermes-engine: private_source_authentication_failure {:source=>"###-###.d.codeartifact.###.amazonaws.com/npm/private"}
```

**Comment by nindzyago** [comment]
> I do exactly this:
> 
> ```yaml
> registries:
>   npm-codeartifact:
>     type: npm-registry
>     url: https://##-##.d.codeartifact.eu-west-2.amazonaws.com
>     token: ${{secrets.CODEARTIFACT_TOKEN}}
> 
>   - package-ecosystem: "npm"
>     directory: "/"
>     schedule:
>       interval: "daily"
>     registries:
>       - npm-codeartifact
> ```
> 
> Then I go to the repo on dependabot secrets and update the variable `CODEARTIFACT_TOKEN ` with the result of this:
> 
> ```
> aws codeartifact get-authorization-token --domain ## --domain-owner ## --query authorizationToken --output text --profile ##
> ```
> 
> I still get:
> 
> ```
> proxy | 2022/06/29 16:52:06 [024] 401 https://###-###.d.codeartifact.###.amazonaws.com:443/npm/private/hermes-engine
> updater | INFO <job_408163671> Handled error whilst updating hermes-engine: private_source_authentication_failure {:source=>"###-###.d.codeartifact.###.amazonaws.com/npm/private"}
> ```

have you found a solution? got same error with same config

**Comment by yaboi** [comment]
I was able to get this to work by creating an action/workflow in my repository that 

1. Runs every 10 hours
2. Generates a code artifact auth token _(this could be a token for any registry, just adjust the generation step(s))_
3. Sets the newly generated token as a Dependabot secret _(could also set a repo secret if any non-Dependabot actions require this token)

**Workflow file:** (`/.github/workflows/refresh-private-registry-credentials.yml`)
```yml
name: Refresh Private Registry Credentials

on:
  schedule:
    - cron: '0 */10 * * *'

jobs:
  refresh-private-registry-credentials:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Configure env
      - name: Configure AWS Repo credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.*** }}
          aws-secret-access-key: ${{ secrets.*** }}
          aws-region: ${{ secrets.*** }}

      # Get code artifact token
      - name: Get Token
        run: echo CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.*** }} --domain-owner ${{ secrets.*** }} --query authorizationToken --output text --region ${{ secrets.*** }} ) >> $GITHUB_ENV

      # Set token as Dependabot secret
      - name: Set Dependabot token
        uses: merchstack/set-action-dependabot-secret@v/2.1.3
        with:
          dependabot: true
          name: 'CODEARTIFACT_AUTH_TOKEN'
          value: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
          token: ${{ secrets.*** }}
```

**Dependabot file:** (`/.github/dependabot.yml`)
```yml
version: 2

registries:
  npm-codeartifact:
    type: npm-registry
    url: ${{ secrets.*** }}
    token: ${{ secrets.CODEARTIFACT_AUTH_TOKEN }}

updates:
  ...
```
