### ISSUE TITLE
Requests with bad paths for out-of-date dependencies using private npm registry and github native dependabot

### ISSUE THREAD

**Issue by ericmatthys** [dependabot/dependabot-core#3298]
**Package manager/ecosystem**
javascript / npm

**Manifest contents prior to update**

`.npmrc`
```
save-prefix=""
package-lock=false
# `npm-stable-and-cache`
registry=https://artifactory.example.bz/artifactory/api/npm/npm-stable-and-cache/
//artifactory.example.bz/artifactory/api/npm/npm-stable-and-cache/:_authToken=REDACTED
//artifactory.example.bz/artifactory/api/npm/npm-stable-and-cache/:always-auth=true
# `npm-stable`
@example:registry=https://artifactory.example.bz/artifactory/api/npm/npm-stable/
//artifactory.example.bz/artifactory/api/npm/npm-stable/:_authToken=REDACTED
//artifactory.example.bz/artifactory/api/npm/npm-stable/:always-auth=true
```

`dependabot.yml`
```yml
version: 2
registries:
  artifactory:
    type: npm-registry
    url: https://artifactory.example.bz
    token: ${{secrets.ARTIFACTORY_TOKEN}}
updates:
  - package-ecosystem: "npm"
    registries:
      - artifactory
    directory: "/"
    schedule:
      interval: "daily
```

**What you expected to see, versus what you actually saw**

Currently we are successfully using dependabot.com with its config variables. We have two config variables, one for `artifactory.example.bz/artifactory/api/npm/npm-stable/` and another for `artifactory.example.bz/artifactory/api/npm/npm-stable-and-cache/`. I'm trying to switch to github native dependabot now that there is private registry support, but running into an error.

```
Dependabot can't authenticate to a private package registry
The following private package registry was used and caused the update to fail: artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache.
```

**Images of the diff or a link to the PR, issue or logs**

Up-to-date dependency with 200 responses:

```
updater | INFO <job_96913755> Checking if imports-loader 2.0.0 needs updating
  proxy | 2021/03/18 07:46:05 [018] GET https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/imports-loader
  proxy | 2021/03/18 07:46:05 [018] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/18 07:46:05 [018] 200 https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/imports-loader
  proxy | 2021/03/18 07:46:05 [020] GET https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/imports-loader/2.0.0
  proxy | 2021/03/18 07:46:05 [020] * authenticating npm registry request (host: artifactory.example.bz, token auth)
updater | INFO <job_96913755> Latest version is 2.0.0
updater | INFO <job_96913755> No update needed for imports-loader 2.0.0
```

Out-of-date dependency with bad requests to `https://artifactory.example.bz:443/esbuild`:

```
updater | INFO <job_96913755> Checking if esbuild 0.9.2 needs updating
  proxy | 2021/03/18 07:46:08 [042] GET https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/esbuild
  proxy | 2021/03/18 07:46:08 [042] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/18 07:46:08 [042] 200 https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/esbuild
  proxy | 2021/03/18 07:46:08 [044] GET https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/esbuild/0.9.3
  proxy | 2021/03/18 07:46:08 [044] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/18 07:46:08 [044] 200 https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/esbuild/0.9.3
updater | INFO <job_96913755> Latest version is 0.9.3
  proxy | 2021/03/18 07:46:16 [046] GET https://artifactory.example.bz:443/esbuild
  proxy | 2021/03/18 07:46:16 [046] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/18 07:46:16 [046] 404 https://artifactory.example.bz:443/esbuild
updater | INFO <job_96913755> Requirements to unlock own
updater | INFO <job_96913755> Requirements update strategy bump_versions
updater | INFO <job_96913755> Updating esbuild from 0.9.2 to 0.9.3
  proxy | 2021/03/18 07:46:23 [048] GET https://artifactory.example.bz:443/esbuild
  proxy | 2021/03/18 07:46:23 [048] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/18 07:46:23 [048] 404 https://artifactory.example.bz:443/esbuild
  proxy | 2021/03/18 07:46:32 [050] GET https://artifactory.example.bz:443/esbuild
  proxy | 2021/03/18 07:46:32 [050] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/18 07:46:32 [050] 404 https://artifactory.example.bz:443/esbuild
  proxy | 2021/03/18 07:46:42 [052] GET https://artifactory.example.bz:443/esbuild
  proxy | 2021/03/18 07:46:42 [052] * authenticating npm registry request (host: artifactory.example.bz, token auth)
  proxy | 2021/03/18 07:46:42 [052] 404 https://artifactory.example.bz:443/esbuild
updater | INFO <job_96913755> Handled error whilst updating esbuild: private_source_authentication_failure {:source=>"artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache"}
```

The entry in `yarn.lock` looks like:

```
esbuild@0.9.2, esbuild@^0.9.2:
  version "0.9.2"
  resolved "https://artifactory.example.bz:443/artifactory/api/npm/npm-stable-and-cache/esbuild/-/esbuild-0.9.2.tgz#7e9fde247c913ed8ee059e2648b0c53f7d00abe5"
  integrity sha1-fp/eJHyRPtjuBZ4mSLDFP30Aq+U=
```

**Comment by pstepniewskiconfigit** [comment]
Some valid comments are located also here #3281

**Comment by thepwagner** [comment]
👋 Thank you for the awesome bug report - the included details made reproducing this a breeze!

This issue was caused by Dependabot rejecting NPM registries with a path in the URL. Since dependabot will [generate .npmrc](https://github.com/dependabot/dependabot-core/blob/f5593cbaf7e333a8d0b445a280a73876ad494f3c/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb) during the update,  the generated `.npmrc` would look like:

```
save-prefix=""
package-lock=false
# `npm-stable-and-cache`
registry=https://artifactory.example.bz
//artifactory.example.bz/:_authToken=REDACTED
//artifactory.example.bz/:always-auth=true
```

We've changed Dependabot to accept NPM registries with a path, so the configuration in the issue description can be represented as:
```yaml
registries:
  artifactory-stable:
    type: npm-registry
    url: https://artifactory.example.bz/artifactory/api/npm/npm-stable
    token: ${{secrets.ARTIFACTORY_TOKEN}}
  artifactory-cache:
    type: npm-registry
    url: https://artifactory.example.bz/artifactory/api/npm/npm-cache
    token: ${{secrets.ARTIFACTORY_TOKEN}}
updates:
  - package-ecosystem: "npm"
    registries:
      - artifactory-stable
      - artifactory-cache
    directory: "/"
    schedule:
      interval: "daily
```
