### ISSUE TITLE
GitHub dependabot ignores patch updates

### ISSUE THREAD

**Issue by vsmelov** [dependabot/dependabot-core#3302]
Action:
- update the package hello_world_vsmelov from 0.2.1 to 0.2.2,
- restart dependabot check

Expected:
- PR to update from  0.2.1 to 0.2.2 created

Actual:
- no PR created
- I see in dependabot log that it see that the new version appeared, but ignores it, it does not create the PR.

When I update the package from 0.2.1 to 0.3.1 it works fine, PR is created.

Should I use some setting to increase "sensitivity" of dependabot to create PR on patch updates?

.github/dependabot.yml
```
version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: live
  open-pull-requests-limit: 10
  allow:
  - dependency-type: all
```

Cargo.toml
```
[package]
name = "dependabot-test"
version = "0.0.1"
authors = ["Vladimir Smelov"]
autobins = false

[dependencies]
hello_world_vsmelov = "^0.2.1"
```
