### ISSUE TITLE
Multiple package-ecosystem of same type in monorepo doesnt seem to work

### ISSUE THREAD

**Issue by phlax** [dependabot/dependabot-core#3324]
I have a monorepo (for testing) which has several python/pip requirements.txt files

I created the following `dependabot.yaml` hoping to trigger dep updates on all of the "projects"

```
version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/abc"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/jkl/sub/sub"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/xyz/sub/sub/sub"
    schedule:
      interval: "daily"

```

i tried validating the config and that passes - but i only ever get alerts/pr for one of the requirements.txt files

testing repo is here:

https://github.com/phlax/dependabot-testing
