### ISSUE TITLE
dependabot config (commit prefix) not working

### ISSUE THREAD

**Issue by oprogramador** [dependabot/dependabot-core#3419]
**Package ecosystem**
npm
**What you expected to see, versus what you actually saw**
The commit message is `Bump y18n from 4.0.0 to 4.0.1` though I have the following in my newly created `.dependabot/config.yml` file:
```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
```

I expect a `fix` or `chore` prefix in the commit message - I don't know whether `y18n` is a prod or dev dependency as it doesn't exist in my `package.json` file but only in `yarn.lock`.

Neither `@dependabot recreate` nor `@dependabot reopen` nor `@dependabot rebase` fixes the commit message.

A link to the dependabot PR: https://github.com/oprogramador/sort-any/pull/37
