### ISSUE TITLE
python 3.8.9 is not found

### ISSUE THREAD

**Issue by sobolevn** [dependabot/dependabot-core#3439]
**Package ecosystem**

- All python: `pip`, `poetry`, etc

**🕹 Bonus points: Smallest manifest that reproduces the issue**

```toml
# pyproject.toml

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "a"
description = "b"
version = "0.1.0"
authors = []

license = "MIT"


[tool.poetry.dependencies]
python = "3.8.9"

[tool.poetry.dev-dependencies]

```

It is failing:

```
Dependabot detected the following Python requirements for your project: '[[#<Dependabot::Python::Requirement:0x000055568ad26c08 @requirements=[["=", #<Dependabot::Python::Version 3.8.9>]]>]]'.

Currently, the following Python versions are supported in Dependabot: 3.9.2, 3.9.1, 3.9.0, 3.8.8, 3.8.7, 3.8.6, 3.8.5, 3.8.4, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.10, 3.7.9, 3.7.8, 3.7.7, 3.7.6, 3.7.5, 3.7.4, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.13, 3.6.12, 3.6.11, 3.6.10, 3.6.9, 3.6.8, 3.6.7, 3.6.6, 3.6.5, 3.6.4, 3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.10, 3.5.8, 3.5.7, 3.5.6, 3.5.5, 3.5.4, 3.5.3, 2.7.18, 2.7.17, 2.7.16, 2.7.15, 2.7.14, 2.7.13.

```
Link: https://github.com/wemake-services/wemake-django-template/issues/1529

But, `python3.8.9` is released: https://www.python.org/downloads/release/python-389/
