### ISSUE TITLE
Unable to log into AWS ECR

### ISSUE THREAD

**Issue by dexterlakin** [dependabot/dependabot-core#3457]
https://github.com/dependabot/dependabot-core/blob/ac276c959e8fa193061e47420152b7e4fa178b0a/docker/lib/dependabot/docker/utils/credentials_finder.rb#L47

Shouldn't this be:
`registry_details["url"]?
`
When I set "registry" i get this error:
```
The property '#/registries/ecr/' did not contain a required property of 'url'
The property '#/registries/ecr/' contains additional properties ["registry"] outside of the schema when none are allowed

```
When I set "url" dependabot always returns this error:
`Handled error whilst updating XXX: private_source_authentication_failure`

Does anyone have an example of a working configuration for AWS ECR?

**Comment by thepwagner** [comment]
@dexterlakin `url` is correct value [in the dependabot.yaml](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#docker-registry) configuration file. There's a mapping+normalization step that will map to the `"registry"` value this library expects, if necessary.

ECR should be working, we'll update with a sample configuration...

**Comment by thepwagner** [comment]
@dexterlakin here's a sample configuration using ECR:

```yaml
version: 2
registries:
  ecr-docker:
    type: docker-registry
    url: 1234567890.dkr.ecr.us-east-1.amazonaws.com
    username: ${{secrets.ECR_AWS_ACCESS_KEY_ID}}
    password: ${{secrets.ECR_AWS_SECRET_ACCESS_KEY}}
registries:
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - ecr-docker
    schedule:
      interval: "daily"
```

Only static credentials are supported.

For reference, my test user had the following IAM policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:ListTagsForResource"
            ],
            "Resource": "arn:aws:ecr:us-east-1:1234567890:repository/my-repository"
        }
    ]
}
```

It'd admittedly not "least privilege", but is a little better than https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html#AmazonEC2ContainerRegistryReadOnly
