### ISSUE TITLE
Opt-out of default `major/minor/patch` labels

### ISSUE THREAD

**Issue by shadycuz** [dependabot/dependabot-core#3465]
I want all my dependencies updates from dependabot to have label "patch". I have added that to my config file.

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "chore"
      - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "chore"
      - "patch"
```

If a dependency does a major or minor version change then I endup with duplicate labels. I use these labels to set the version of my releases so they must always be patch when coming from dependabot. 

Example PR's https://github.com/DontShaveTheYak/cloud-radar/pull/12 https://github.com/DontShaveTheYak/cloud-radar/pull/14

**Comment by asciimike** [comment]
Looks like major/minor/patch logic was discussed here: https://github.com/dependabot/feedback/issues/134

It also looks like we don't have a way to turn it off, which seems... less than ideal. I'm going to quickly re-classify this as a feature request to do so, which would respect your desire to label it as desired.

**Comment by asciimike** [comment]
Potential options include:

### Add a special `dependabot-ignore:` label prefix

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      # these labels get ignored
      - "dependabot-ignore:major"
      - "dependabot-ignore:minor"
      - "dependabot-ignore:patch"
      # these labels get added
      - "chore"
      - "patch"
```

Pros:
 - No additional top level config options required
 
Cons:
 - Nobody could add a literal `"dependabot-ignore:*"` label (turns out nobody seems to use this, but it would have to be documented)

### Add a new section for default opt-outs

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "chore"
      - "patch"
    default-opt-outs:
      - "automatically-adding-semver-labels"
```

Pros:
 - Extensible to the other features Dependabot users may want to opt out of
 - No restrictions on label names
 
Cons:
 - It's a giant grab bag of functionality that will only grow over time (it's not aesthetically pleasing)

Any thoughts?
