### ISSUE TITLE
Make `allow` and `ignore` symmetric

### ISSUE THREAD

**Issue by asciimike** [dependabot/dependabot-core#3479]
Currently, Dependabot offers two ways of opting dependencies in or out of updates: [`allow`](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#allow) and [`ignore`](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#ignore). The main differences (from a config file functionality standpoint) are:
 - `allow` has the ability to specify `dependency-type`'s (e.g. `development`, `production`) to allow a certain number of dependencies 
 - `ignore` has the ability to opt out of certain `versions`, while `allow` can't opt you in to certain versions (e.g. only `allow` updates on `x.y.z` not `x+1.y.z`).

It certainly feels useful to be able to write something like:

```yaml
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-type: "development"
```

Which would fulfill issues like https://github.com/dependabot/dependabot-core/issues/3475

We also offer a `@dependabot ignore` command without a corresponding `@dependabot allow` command, though dependabot updates everything by default, so allow might be redundant, unless you're trying to opt back in after you've opted out.

As an internal implementation note, I believe `allow` and `ignore` run at different times, so potentially we might want to unify this, or further clarify this behavior.

**Comment by feelepxyz** [comment]
Thoughts on doing this in stages? Adding `dependency-type` to `ignore` would be a pretty straight forward change compared to adding `versions` to `allow`.

**Comment by asciimike** [comment]
Fine with doing it in stages, just wanted to create an issue that covers the majority of these feature requests.

**Comment by siddharthvp** [comment]
For npm at the moment would setting `allow: - dependency-type: production` disable the updates for devDependencies? I missed that option while going through the docs earlier.

**Comment by feelepxyz** [comment]
> would setting `allow: - dependency-type: production` disable the updates for devDependencies

@siddharthvp yep 👍

**Comment by siddharthvp** [comment]
Sorry if this appears unrelated – but would a combo like the following also work as of now?
```
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: production

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
    allow: 
      - dependency-type: development
```

(The intent is to get regular dependency updates daily and devDependency updates monthly.)

**Comment by asciimike** [comment]
@siddharthvp your head is in the right place, but unfortunately we don't currently support multiple schedules for the same ecosystem/directory pair. It's something we've considered, but it'll probably be a little further out (we're working on #2219 now).

**Comment by humphrey** [comment]
+1 for adding `dependency-type` to `ignore` if it's a straightforward change.

I believe that it is currently possible to only produce pull requests for `dependency-type: "production"` but it would be nice for them to be completely removed on the dependabot list.

Use case: I don't care about all of the security updates to "express" if it's only used in my web-based project to power hot-reloading during development.

**Comment by msudgh** [comment]
Is this feature discontinued?
I have the same problem with dev dependencies and they're not important for production stream as there's no direct usage on the dependency. I think the mentioned solution by @humphrey is valid.

**Comment by cedric-anne** [comment]
Adding either support of `update-types` in `allow` or support of `dependency-type` in `ignore` would help a lot to be able to use a different policy for development and production dependencies.

With support of `update-types` in `allow`:
```yaml
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "development"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
      - dependency-type: "production"
        update-types:
          - "version-update:semver-patch"
```


With support of `dependency-types` in `ignore`:
```yaml
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-type: "development"
        update-types:
          - "version-update:semver-major"
      - dependency-type: "production"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
```
