### ISSUE TITLE
Permissions issue since Docker image version 0.141.0

### ISSUE THREAD

**Issue by sussexrick** [dependabot/dependabot-core#3499]
Dependabot Docker images fail to run `bundle install` on Azure pipelines since version 0.141.0.

**Package ecosystem**

n/a - it's before I get to that stage

**What you expected to see, versus what you actually saw**

Expected (output from 0.140.3):

```
Installing aws-sdk-ecr 1.41.0
Fetching commonmarker 0.21.2
Fetching gitlab 4.17.0
Installing commonmarker 0.21.2 with native extensions
Installing gitlab 4.17.0
Fetching http-cookie 1.0.3
Installing http-cookie 1.0.3
Fetching octokit 4.20.0
Installing octokit 4.20.0
Fetching rest-client 2.1.0
Installing rest-client 2.1.0
Fetching docker_registry2 1.10.0
Installing docker_registry2 1.10.0
Fetching dependabot-common 0.133.6
Installing dependabot-common 0.133.6
Fetching dependabot-bundler 0.133.6
Fetching dependabot-cargo 0.133.6
Installing dependabot-cargo 0.133.6
Installing dependabot-bundler 0.133.6
Fetching dependabot-composer 0.133.6
Fetching dependabot-dep 0.133.6
Installing dependabot-composer 0.133.6
Installing dependabot-dep 0.133.6
Fetching dependabot-docker 0.133.6
Fetching dependabot-elm 0.133.6
Installing dependabot-docker 0.133.6
Installing dependabot-elm 0.133.6
Fetching dependabot-git_submodules 0.133.6
Fetching dependabot-github_actions 0.133.6
Installing dependabot-git_submodules 0.133.6
Installing dependabot-github_actions 0.133.6
Fetching dependabot-go_modules 0.133.6
Fetching dependabot-gradle 0.133.6
Installing dependabot-go_modules 0.133.6
Installing dependabot-gradle 0.133.6
Fetching dependabot-hex 0.133.6
Fetching dependabot-maven 0.133.6
Installing dependabot-hex 0.133.6
Installing dependabot-maven 0.133.6
Fetching dependabot-npm_and_yarn 0.133.6
Fetching dependabot-nuget 0.133.6
Installing dependabot-nuget 0.133.6
Fetching dependabot-python 0.133.6
Installing dependabot-npm_and_yarn 0.133.6
Installing dependabot-python 0.133.6
Fetching dependabot-terraform 0.133.6
Installing dependabot-terraform 0.133.6
Fetching dependabot-omnibus 0.133.6
Installing dependabot-omnibus 0.133.6
Bundle complete! 2 Gemfile dependencies, 65 gems now installed.
Bundled gems are installed into `./vendor`
Post-install message from httparty:
When you HTTParty, you must party hard!
Finishing: Install dependencies
```
Actual (output from 0.141.0 onwards):

```
Starting: Install dependencies
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/39d47893-114c-4225-9ee3-b83b68db1749.sh
There was an error while trying to write to
`/home/dependabot/dependabot-script/.bundle/config`. It is likely that you need
to grant write permissions for that path.
##[error]Bash exited with code '23'.
Finishing: Install dependencies
```

**🕹 Bonus points: Smallest manifest that reproduces the issue**

Run this pipeline on Azure DevOps:

```yml
jobs:
- job: Dependabot 
  pool:
    vmImage: "ubuntu-20.04"

  variables:
  - name: DockerImageTag
    value: '0.141.0' # '0.140.3' is fine
  
  steps:
  - script: git clone https://github.com/thepensionsregulator/dependabot-script.git
    displayName: Clone dependabot repo

  - script: docker pull dependabot/dependabot-core:$(DockerImageTag)
    displayName: Pull dependabot-core Docker image

  # -j 3 = allow 3 parallel downloads during bundle install
  # --path vendor = install into the /home/dependabot/dependabot-script/vendor folder inside the container
  - script: |
      cd dependabot-script
      docker run -v "$(pwd):/home/dependabot/dependabot-script" \
                 -w /home/dependabot/dependabot-script dependabot/dependabot-core:$(DockerImageTag) bundle install \
                 -j 3 \
                 --path vendor
    displayName: Install dependencies
```

**Comment by nachogarcia** [comment]
Since 2 days I also have started having issues with permission, in my case installing a self-signed certificate

```yaml
.dependabot:
  image: dependabot/dependabot-core
  variables:
    PACKAGE_MANAGER: $CI_JOB_NAME
  before_script:
    - cp $CA_CRT /usr/local/share/ca-certificates/cert.crt
    - chmod 644 /usr/local/share/ca-certificates/cert.crt
    - update-ca-certificates
```

`cp: cannot create regular file '/usr/local/share/ca-certificates/cert.crt': Permission denied`

In case it helps
