### ISSUE TITLE
Notification on error

### ISSUE THREAD

**Issue by sbrunner** [dependabot/dependabot-core#3509]
Is it possible to be notified when Dependabot has an error when he tries to do the update (e.g. "Dependabot can't resolve your Python dependency files"), Or having an API to be able to get them.

I need it because I survey many repositories...

Dependabot version 1 was opening an issue, this was enough for me :-)

**Comment by brrygrdn** [comment]
👋🏻  @sbrunner Thanks for opening an issue, this is definitely something we want to get to. I don't have an ETA right now that I can share but we definitely want to improve the visibility of job outcomes when a PR isn't created.

**Comment by cfryanr** [comment]
+1. @brrygrdn, this would be especially valuable for a Go project.

For one of the projects that I work on, the Dependabot scanning quietly stopped working because we accidentally inherited an indirect dependency on a library that had at some point in the past violated the Go rule that a released package should not change its checksum. This would have been fixable with a replace directive in our project's go.mod if we were aware of Dependabot's failures, but we had no idea that Dependabot had stopped working for a long time. If something had emailed us or otherwise notified us to say that Dependabot got an error during dependency scanning, then we could have benefited from knowing much earlier. Unfortunately, this resulted in a long period of time where everything was working in our project's code and tests so we assumed that Dependabot was scanning our dependencies, but actually it was not scanning at all.

**Comment by mwaddell** [comment]
Currently, the only way to see that the last dependabot run did not fail is to manually go to the `/network/updates` page for each repository individually and make sure that none of them show an error of any kind.

Would it be possible to have dependabot create a new Issue (instead of a PR) whenever a run fails?  

This issue would link to the `/network/updates` page itself in the case of a parsing error, such as:
> ![image](https://user-images.githubusercontent.com/750244/151592250-fdbb1c48-6f83-497b-8eaa-5089cc0c0c5d.png)

This issue would link to the `/network/update/<ID>` page in the case of a failure of a particular ecosystem, such as:
> ![image](https://user-images.githubusercontent.com/750244/151592806-ea59c8ac-c6fd-4479-8d94-6be724cff256.png)

**Comment by mwaddell** [comment]
The issue of dependabot failing silently could also be resolved by reenabling the badges (see task #1912 and #1960), but using issues instead might be a simpler approach than creating a whole new set of endpoints to serve up badges...

**Comment by mwaddell** [comment]
Probably the simplest solution would be to add an "Email each time a dependabot run fails" to the notification settings since there already exists logic to send out an email at the end of any run that has a security vulnerability.  I don't believe that code exists in dependabot-core, that's probably in github's code itself, so I'm not sure if this is the appropriate place to log the issue.  Is there a better repo for this request?

![image](https://user-images.githubusercontent.com/750244/151666695-c0d36eef-2c30-47ff-9896-b37dd39b8222.png)

**Comment by mwaddell** [comment]
Could also be addressed by #4680 using a custom workflow

**Comment by jeffwidman** [comment]
This was one of my biggest annoyances when I used Dependabot at a previous employer. 

Not only is it not obvious it's broken, it's also not obvious when it's "working for most of the deps, but broken for a subset of deps". Typically this happens when bumping a particular dep requires bumping another dep and Dependabot isn't smart enough (yet) to unlock them both simultaneously to get past the constraint conflict.

Thankfully, now that I'm on the inside I can say that this is something that folks are aware of and there's already an internal project in-flight to improve the UI surfacing of errors, although it's a fairly large project so may take a while to land yet.

**Comment by darokel** [comment]
@jeffwidman Just checking in to see if there has been any progress with this request?

**Comment by glastrac** [comment]
Hey guys, what the heck? We need to be notified. Please follow up this issue.

**Comment by jtherrmann** [comment]
+1 for this. We manage dozens of repos and recently encountered an issue in which dependabot was failing due to a syntax error in our `pyproject.toml` files and only noticed the problem by accident.

**Comment by ssbarnea** [comment]
I looking seriously about switching to an alternative like renovate because development and maintenance stalled since the sale.

**Comment by fszymanski-blvd** [comment]
We just ran into an issue where dependabot always uses the latest Terraform, but we have Terraform version pinned (e.g. ~> 1.11.3). This caused all the dependabot terraform runs to fail without notification. 

Combined with the fact that Dependabot can't upgrade Terraform versions, we have hit a difficult position where we might need to stop pinning Terraform version to allow dependabot to work without errors. New Terraform minor versions seem to be coming out every 3-4 months which is too much work to keep them updated manually.

**Comment by case** [comment]
This issue has been open since 2021, which (sadly) means it still doesn't appear to be a priority for the GitHub folks.

It occurred to me a few days ago, that since [Dependabot jobs simply run as standard GitHub Actions](https://github.blog/news-insights/product-news/dependabot-on-github-actions-and-self-hosted-runners-is-now-generally-available/) nowadays, their run metadata might be available via the GH API, CLI, etc. It turns out that's true, so I made a little Actions job that you can run on a schedule, to "look back" over a specified time interval (e.g. a week, etc.) for failed Dependabot runs. Then configure it to alert accordingly.

Try it out here: https://github.com/marketplace/actions/dependabot-error-alerts

(I also added a `gh` CLI-only prototype at the bottom of the Readme, for folks who'd rather just DIY it without a third-party Action)

**Comment by yeikel** [comment]
Since Dependabot functions like any other workflow run, you can listen to the GitHub events and act as needed. For example: 

File: `.github/workflows/dependabot-watcher.yml` 

Content: 

```yml
name: Dependabot Watcher
on:
  workflow_run:
    workflows:
         # The Dependabot workflow is always called "Dependabot Updates"
      - Dependabot Updates
    types:
       # Options: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_run
      - completed
jobs:
  trigger-on-failure-dependabot-update:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send alert
        run: |
          # TODO: Integrate with your alert notification system here
          
  # Optional, this is just an example of what you can do for other situations if needed
  trigger-on-success-dependabot-update:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send alert
        run: |
          # TODO: Integrate with your alert notification system here
```

If we need more advanced mechanisms such as creating an issue (and close it when fixed), that's something we can build as a community as needed starting from this template
