### ISSUE TITLE
Dependabot fails to find latest versions using private Artifactory

### ISSUE THREAD

**Issue by alexrosenfeld10** [dependabot/dependabot-core#3547]
I'm getting the following issue when using a private Artifactory nuget feed:

```
updater | INFO <job_113476641> Checking if My.Company.Dependency 1.5.3 needs updating
  proxy | 2021/04/22 21:31:19 [086] GET https://mycompany.jfrog.io:443/artifactory/nuget/
  proxy | 2021/04/22 21:31:19 [086] * authenticating nuget feed request (host: mycompany.jfrog.io, basic auth)
  proxy | 2021/04/22 21:31:19 [086] 200 https://mycompany.jfrog.io:443/artifactory/nuget/
  proxy | 2021/04/22 21:31:19 [088] GET https://mycompany.jfrog.io:443/artifactory/nuget/FindPackagesById()?id=%27My.Company.Dependency%27
  proxy | 2021/04/22 21:31:19 [088] * authenticating nuget feed request (host: mycompany.jfrog.io, basic auth)
  proxy | 2021/04/22 21:31:20 [088] 200 https://mycompany.jfrog.io:443/artifactory/nuget/FindPackagesById()?id=%27My.Company.Dependency%27
updater | INFO <job_113476641> Latest version is 
updater | INFO <job_113476641> Requirements to unlock update_not_possible
updater | INFO <job_113476641> Requirements update strategy 
updater | INFO <job_113476641> No update possible for My.Company.Dependency 1.5.3
```

There is a version 1.6.4 of `My.Company.Dependency` available, so it seems like something is going wrong with Dependabot here. Also, I checked this with a dependency that _isn't_ made by MyCompany but does need an upgrade. It still doesn't work and the output is similar, which points to either something wrong with the configuration I have or with dependabot pulling from private artifact stores.

It's possible I have something misconfigured, but it seems to be OK to me. 

**Package ecosystem**
nuget-feed

**Package manager version**
.net core

**Language version**
n/a

**Manifest location and content prior to update**
n/a

**dependabot.yml content**
```yaml
version: 2

registries:
  nuget-jfrog:
    type: nuget-feed
    url: https://mycompany.jfrog.io/artifactory/nuget/
    username: my-username
    password: ${{secrets.DEPENDABOT_JFROG_SECRET}}
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "3.x"
    registries:
      - nuget-jfrog
```

**Updated dependency**
n/a

**What you expected to see, versus what you actually saw**
Dependabot should open PRs for the dependencies that have updates available

**Native package manager behavior**
n/a

**Images of the diff or a link to the PR, issue or logs**
n/a

**🕹 Bonus points: Smallest manifest that reproduces the issue**
n/a

**Comment by alexrosenfeld10** [comment]
```
registries:
  nuget-jfrog:
    type: nuget-feed
    url: https://my-org.jfrog.io/artifactory/api/nuget/nuget
    username: ${{ secrets.ORG_JFROG_USERNAME }}
    password: ${{ secrets.ORG_JFROG_ACCESS_TOKEN }}
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "3.x"
    open-pull-requests-limit: 10
    registries:
      - nuget-jfrog
```

all of a sudden, this seems to work. 🤷
