### ISSUE TITLE
dependabot doesn't seem to init submodules before resolving dependencies

### ISSUE THREAD

**Issue by macklin-10x** [dependabot/dependabot-core#3554]
**Package ecosystem**
gomod

**Manifest location and content prior to update**
/go.mod
/some_submodule/go.mod
**dependabot.yml content**
```
version: 2

updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
 ```
**What you expected to see, versus what you actually saw**
I expected Dependabot to resolve my dependencies inside a submodule.  Instead, it appears to have not initialized the submodule, as when it attempts to find go.mod in the submodule via go mod replace directive, it fails to find it:
```
updater | ERROR <job_113688959> Error processing github.com/getsentry/sentry-go (Dependabot::DependabotError)
updater | ERROR <job_113688959> go: github.com/OurOrg/some_submodule@v0.0.0-20200619054206-2eba306b06f4 (replaced by ./some_submodule): reading some_submodule/go.mod: open /some_submodule/go.mod: no such file or directory
```

To be clear, I am not trying to have Dependabot manage/update the version of the submodule.  I just want Dependabot to manage the dependencies in the root go.mod file, but it is failing to resolve due to errors like the one shown above.
