### ISSUE TITLE
Dependabot can't update bundler dependency files that reference private git repositories

### ISSUE THREAD

**Issue by kcarmonamurphy** [dependabot/dependabot-core#3587]
I'm having trouble getting dependabot to work with private git repos that are included as gems in a private project, under an organization.

![Screen Shot 2021-04-28 at 16 57 02](https://user-images.githubusercontent.com/1145018/116473060-b8680780-a844-11eb-8945-787e297fe96d.png)

Here's the Github structure:

```
- organization with both public and private repos
  - private_repo_one (example: https://github.com/my-organization/private_repo_one)
  - private_repo_two (example: https://github.com/my-organization/private_repo_two)
```

The `Gemfile` for `private_repo_one` contains the following line:

```
gem 'private_repo_two', git: "git@github.com:my-organization/private_repo_two"
```

This is what my `dependabot.yml` file looks like in `private_repo_one`:

```
version: 2

registries:
  ruby-github:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/octocat/github_api
    token: ${{secrets.DEPENDABOT_PRIVATE_KEY}} <-- this is set as a personal access token generated from https://github.com/settings/tokens

updates:
  - package-ecosystem: bundler
    directory: "/"
    insecure-external-code-execution: allow
    registries: "*"
```

I've given my personal access token ALL of the permissions, and the `DEPENDABOT_PRIVATE_KEY` is an organization dependabot secret defined here https://github.com/organizations/my-organization/settings/secrets/dependabot

Why isn't this working? Does dependabot v2 simply not support private bundler repos?

**Comment by feelepxyz** [comment]
@kcarmonamurphy it looks like you still need to grant access to the private git repository, the above token will only be applied when the package is hosted on `https://rubygems.pkg.github.com/octocat`. We're looking at ways of making the integration with GitHub packages smoother.

You'll also want to grant dependabot access to these repos, you can use this UI to  grant it access if they exist under the same organization: https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-dependencies

If it's under another org, you'll need to add a `git` `registries` entry: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#git

**Comment by mvz** [comment]
If I understand correctly from https://github.blog/changelog/2020-12-02-dependabot-version-updates-from-private-github-repositories/, for dependencies in the bundler ecosystem you always need a `registries` entry.

**Comment by kcarmonamurphy** [comment]
Hi @feelepxyz and @mvz, thank you for your input. We were able to get it to work after all!

Turns out that we were using the wrong registry. Because we're sourcing our packages directly from github, we needed to use the github registry instead of the rubygems one:

```
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT_PRIVATE_KEY}}
```
