### ISSUE TITLE
Option rebase-strategy set to disabled doesn't prevent rebasing

### ISSUE THREAD

**Issue by electrofelix** [dependabot/dependabot-core#3594]
**Package ecosystem**
gomod (but presumably could be any)
**dependabot.yml content**
We have some private registries so I've pruned some blocks out of this, but the gomod and github action blocks are exactly as in the config file:
```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
```
**What you expected to see, versus what you actually saw**
Expected that dependabot would not attempt to perform rebasing on target branch being updated due to setting `rebase-strategy: disabled`, yet it continues to do so and the subsequent force push removes review approvals. We already have a workflow that will merge the target branch in to the dependabot PR automatically when the target branch is updated. This allows our CI to check that the PR with the latest target branch contents will also pass, and ideally automatically merge in the background without requiring further checking.
**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/912324/116572670-17408600-a904-11eb-840a-4e6dcc6358db.png)
I have tried to reproduce this on a public repo and it works as documented rather than as described above. However I noticed one slightly peculiarity https://github.com/electrofelix/dependabot-rebase-bug/pull/3 does not include a `go` label, where in the private repo belonging to the org I'm in does. So I'm wondering if there is a chance there is either a per-org setting here that is causing the above behaviour or if there is stale configuration from dependabot-preview that could be messing things up. Added the `rebase-strategy` to the config file in the affected repo on the 16th April, so I figure it should be long enough for it to be picked up.

**Comment by electrofelix** [comment]
This seems to have cleared itself, I'm not sure why it was misbehaving with the gomod update before as there was over a week between when the dependabot.yml was updated to disable rebasing and the PR above reference getting opened. It is respecting the setting now.

**Comment by electrofelix** [comment]
This is happening again on a project created after my last comment.

It appears that even when `rebase-strategy: disabled` is set on a project, once the comment `@dependabot squash and merge` is added, if there is subsequently an update to the PR (e.g. the default branch is merged into the PR to ensure it is only merged if what is the final result of the merge of the PR passes CI), it switches to trying to rebase the PR and that breaks the approval process because a force push will remove any existing approvals.

**Comment by hemberger** [comment]
This is happening to me without even touching the PR. After the file being updated is changed on the target branch, dependabot force-pushes to the PR. For example, see https://github.com/smrealms/smr/pull/1555.

The following config has been set since Dec 2022:
```
- package-ecosystem: composer
  directory: "/" 
  schedule:
    interval: daily
  rebase-strategy: disabled
```
Please let me know if I can provide any further info. Thanks!
