### ISSUE TITLE
Non-private registries cause schema issue

### ISSUE THREAD

**Issue by rjmholt** [dependabot/dependabot-core#3600]
**Package ecosystem**

NuGet

**Language version**

**Manifest location and content prior to update**

**dependabot.yml content**

**Updated dependency**

**What you expected to see, versus what you actually saw**

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

From https://github.com/PowerShell/PSScriptAnalyzer/pull/1664.

Config file:

```yaml
version: 2
registries:
  powershell-gallery:
    type: nuget-feed
    url: https://www.powershellgallery.com/api/v2/
  nuget-org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  registries:
  - powershell-gallery
  - nuget-org
```

You can find the current file [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/.github/dependabot.yml).

The configuration file is reporting a schema issue:

![image](https://user-images.githubusercontent.com/7009879/116599655-3aa40a80-a8dd-11eb-96b1-0da845bd5c36.png)

The configuration file I wrote is based on dependabot's own generated configuration in https://github.com/PowerShell/PSScriptAnalyzer/pull/1668 (which we rewrote because we thought GitHub might have special logic to detect dependabot commits to perform a configuration hook).

I can't find any further information on the schema or what it expects and the documentation doesn't really cover this case (it only talks about private registries that have tokens or passwords).

I also saw the same error message with this config [here](https://dependabot.com/docs/config-file/validator/).

1. Are non-authenticated registry entries supported?
2. Is there a schema I can refer to to help understand what's going on here (the current error message didn't help)
