### ISSUE TITLE
Dependabot proposes bad Go module updates in monorepos

### ISSUE THREAD

**Issue by jawnsy** [dependabot/dependabot-core#3617]
This seems to be an issue as our project is in a monorepo, so we have Node.js modules that include Go source files nested underneath, and generated code that requires Go modules.

When dependabot does a `go mod tidy`, it hasn't installed those other modules, and so removes those dependencies.

A workaround for this might be to manually ensure that those dependencies are required by adding a Go file that imports those. 

**Package ecosystem**
Go

**Package manager version**
go1.16.3 linux/amd64

**Language version**

go1.16.3

**Manifest location and content prior to update**

/go.mod
/go.sum

**dependabot.yml content**

```yaml
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"
    ignore:
      # GitHub always delivers the latest versions for each major
      # release tag, so handle updates manually
      - dependency-name: "actions/*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"
```

**Updated dependency**

chore: bump github.com/google/go-containerregistry from 0.4.0 to 0.5.0 

**What you expected to see, versus what you actually saw**

I expected an update to the single proposed library, instead several other dependencies were removed and other unrelated dependencies were updated.

![image](https://user-images.githubusercontent.com/52710/116761170-c4ca9c80-a9cb-11eb-9942-16c4c0ce3411.png)

Here's a diff from a different PR, note that many of the same dependencies are being removed here too:

![image](https://user-images.githubusercontent.com/52710/116785608-60512100-aa4f-11eb-823c-8fb3625e37ae.png)

**Native package manager behavior**

I made the change manually just by updating the containerregistry dependency, and this is the result:

![image](https://user-images.githubusercontent.com/52710/116788487-b2e60980-aa5e-11eb-846d-c27bdb3bdb1e.png)

**Images of the diff or a link to the PR, issue or logs**

The Dependabot logs do not show anything meaningful:

```
  proxy | 2021/04/30 23:58:04 [099] 200 https://github.com:443/influxdata/go-syslog/git-upload-pack
  proxy | 2021/04/30 23:58:04 [101] POST https://github.com:443/influxdata/go-syslog/git-upload-pack
  proxy | 2021/04/30 23:58:04 [101] * authenticating git server request (host: github.com)
  proxy | 2021/04/30 23:58:04 [101] 200 https://github.com:443/influxdata/go-syslog/git-upload-pack
  proxy | 2021/04/30 23:58:04 [104] GET https://gopkg.in:443/yaml.v3/info/refs?service=git-upload-pack
  proxy | 2021/04/30 23:58:04 [108] GET https://github.com:443/google/go-containerregistry/info/refs?service=git-upload-pack
  proxy | 2021/04/30 23:58:04 [108] * authenticating git server request (host: github.com)
  proxy | 2021/04/30 23:58:04 [109] POST https://github.com:443/robfig/cron/git-upload-pack
  proxy | 2021/04/30 23:58:04 [109] * authenticating git server request (host: github.com)
  proxy | 2021/04/30 23:58:04 [104] 200 https://gopkg.in:443/yaml.v3/info/refs?service=git-upload-pack
  proxy | 2021/04/30 23:58:04 [109] 200 https://github.com:443/robfig/cron/git-upload-pack
  proxy | 2021/04/30 23:58:04 [111] POST https://github.com:443/robfig/cron/git-upload-pack
  proxy | 2021/04/30 23:58:04 [111] * authenticating git server request (host: github.com)
  proxy | 2021/04/30 23:58:04 [108] 200 https://github.com:443/google/go-containerregistry/info/refs?service=git-upload-pack
  proxy | 2021/04/30 23:58:04 [111] 200 https://github.com:443/robfig/cron/git-upload-pack
  proxy | 2021/04/30 23:58:04 [113] POST https://github.com:443/cdr/retry/git-upload-pack
  proxy | 2021/04/30 23:58:04 [113] * authenticating git server request (host: github.com)
  proxy | 2021/04/30 23:58:04 [115] POST https://github.com:443/google/go-github/git-upload-pack
  proxy | 2021/04/30 23:58:04 [115] * authenticating git server request (host: github.com)
  proxy | 2021/04/30 23:58:04 [113] 200 https://github.com:443/cdr/retry/git-upload-pack
  proxy | 2021/04/30 23:58:04 [117] POST https://github.com:443/cdr/retry/git-upload-pack
  proxy | 2021/04/30 23:58:04 [117] * authenticating git server request (host: github.com)
  proxy | 2021/04/30 23:58:05 [119] POST https://github.com:443/go-chi/chi/git-upload-pack
  proxy | 2021/04/30 23:58:05 [119] * authenticating git server request (host: github.com)
```
**🕹 Bonus points: Smallest manifest that reproduces the issue**
