### ISSUE TITLE
Release notes link is wrong for keptn/keptn check-spelling/check-spelling@v0.0.18

### ISSUE THREAD

**Issue by jsoref** [dependabot/dependabot-core#3629]
**Package ecosystem**
GitHub Actions

**Package manager version**

**Language version**

**Manifest location and content prior to update**
https://github.com/keptn/keptn/blob/f01ee895f71e9055e9acc4df755d608d50e5b854~/.github/workflows/spelling.yml

```yaml
name: Spell checking
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
    branches:
      - "**"
    tags-ignore:
      - "**"
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-20.04
    steps:
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2.0.0
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
        fetch-depth: 5
    - name: checkout
      if: "!contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 5
    - uses: check-spelling/check-spelling@0.0.17-alpha
```

https://github.com/keptn/keptn/blob/7a109e76f3fda63cede48cceda6eea65942b2a02/.github/dependabot.yml
```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
```

**Updated dependency**

    Bumps [check-spelling/check-spelling](https://github.com/check-spelling/check-spelling) from 0.0.17-alpha to v0.0.18.

**What you expected to see, versus what you actually saw**

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**
