### ISSUE TITLE
Support public GitHub Packages without manual token

### ISSUE THREAD

**Issue by hfhbd** [dependabot/dependabot-core#3646]
If you publish a `java` maven artifact on GitHub Packages with public access, to download and fetch everybody still needs authentication, see https://github.community/t/download-from-github-package-registry-without-authentication.

Until this is fixed, it would be nice, if Dependabot could authenticate (read-only) to GitHub Packages to fetch publics artifacts. 
Dependabot would have its own token and use it to authenticate to Packages.

Currently, you have to provide a custom GitHub token with `read:packages` scope (https://github.community/t/download-from-github-package-registry-without-authentication/14407/106).

```
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/hfhbd
    username: dependabot
    password: ${{secrets.GHP_TOKEN}}

- package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - maven-github
```

For private repos/packages, a manual created token would be still required, only public artifacts on GitHub Packages would be fetched without a manual token.
