### ISSUE TITLE
Workflow don't have access to secrets on first run

### ISSUE THREAD

**Issue by clmntgr** [dependabot/dependabot-core#3657]
## Basic info:

**Package ecosystem**
composer or yarn
**Package manager version**
Any
**Language version**
Not related
**Manifest location and content prior to update**
Not related
**Updated dependency**
Any
**Native package manager behavior**
Not related
**Images of the diff or a link to the PR, issue or logs**
Not related

## Previous behavior in Dependabot Preview:

```
version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    default_labels:
      - "Dependabot"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    default_labels:
      - "Dependabot"
```

```
composer config http-basic.nova.laravel.com *** ${NOVA_PASSWORD}
  composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader
  shell: /usr/bin/bash -e {0}
  env:
    NOVA_PASSWORD: ***
```

## Current behavior in GitHub-native Dependabot:

```
version: 2
registries:
  composer-repository-nova:
    type: composer-repository
    url: https://nova.laravel.com
    username: ***
    password: "${{secrets.NOVA_PASSWORD}}"

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
    registries:
      - composer-repository-nova
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
```

```
composer config http-basic.nova.laravel.com *** ${NOVA_PASSWORD}
  composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader
  shell: /usr/bin/bash -e {0}
  env:
    NOVA_PASSWORD:
```

So the problem is that my main action (which run lint and test) fail on the first run for dependabot PR, if I restart the action it will work correctly.
It looks like that the action don't have access to the secrets for dependabot PR so the private repositories login fail.

The `NOVA_PASSWORD` secret is set on actions AND dependabot secrets sections.
For now I just re run all actions.

Thanks for your work on dependabot, it was the main reason I switch to github!
