### ISSUE TITLE
open-pull-requests-limit configuration is ignored

### ISSUE THREAD

**Issue by fabiendem** [dependabot/dependabot-core#3705]
**Package ecosystem**

`yarn` so configured `npm`.  
https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#package-ecosystem

**Package manager version**

`yarn 1.22.10`

**Language version**

N/A

**Manifest location and content prior to update**

**dependabot.yml content**

```
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    reviewers:
      - "foo"
    labels:
      - ":robot: dependabot"
      - ":sunglasses: needs review"
      - ":stop_sign: do not merge"
    commit-message:
      prefix: "[Needs ticket]"
```

**Updated dependency**

N/A

**What you expected to see, versus what you actually saw**

We have set the `open-pull-requests-limit` to `1`.
We would expect no more than one dependabot PR being open at the same time.  
But we keep receiving new PRs from dependabot above the limit of `1`.  Those are not security updates.

Note that this is a project migrated from dependabot.com to github.

**Native package manager behavior**

N/A

**Images of the diff or a link to the PR, issue or logs**

Weirdly the Github dashboard properly displays the limit of 1.

![Screenshot 2021-05-12 at 11 41 45](https://user-images.githubusercontent.com/1186282/117962652-5fee3b00-b317-11eb-9cbd-c8a72422bf41.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**

```
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
```
