### ISSUE TITLE
Only security updates feature is not working now 

### ISSUE THREAD

**Issue by calix2** [dependabot/dependabot-core#3711]
I have a very simple question, I did a lot of Google but could not find the answer anywhere. Sorry I have to seek for this answer here. 

Earlier, there was an option in https://app.dependabot.com for "Only security updates" which were creating the PRs with the label `security` and [Security] in the commit message. 

![image](https://user-images.githubusercontent.com/60227300/118038822-e2a2e480-b36f-11eb-8382-13975df375fa.png)

I see no option to achieve this now. I am sure there is a filter something like this `only-security-updates: true` which can be defined in `dependabot.yml` file i.e.:

```
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  only-security-updates: true
```

Either it does not exist or I am unable to locate it. Kindly help.
