### ISSUE TITLE
Adding private registries stops checking default public nuget feed.

### ISSUE THREAD

**Issue by SwiftMJ** [dependabot/dependabot-core#3724]
**Package ecosystem**
Nuget

**dependabot.yml content**
```yaml
version: 2
registries:
  telerik:
    type: nuget-feed
    url: https://nuget.telerik.com/nuget
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
updates:
- package-ecosystem: nuget
  directory: "/WebApplication.Server"
  registries: 
   - telerik
  schedule:
    interval: daily
  open-pull-requests-limit: 40
```

**What you expected to see, versus what you actually saw**
My project uses both public and private nuget packages. The private packages are accessible at https://nuget.telerik.com/nuget and the public packages at https://api.nuget.org/v3/index.json the default public feed. 

When I added the new [private registries](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#configuration-options-for-private-registries) section it stopped checking the public nuget feed. So how do I configure dependabot to check both public and private feeds?

What I have tried:

1. When I include the **private feed** in the registries section (as shown above) it will only check that feed and the public feed will not be checked. Also tried `registries: "*"` but that made no difference.
2. When I include both the **public and private feed** in the registries it throws an error as mentioned in issue #3600 because a token or username/password is required.
3. I then tried creating two update sections as show below, one with the registries specified and one without:
```yaml
updates:
- package-ecosystem: nuget
  directory: "/WebApplication.Server"
  registries: 
   - telerik
  schedule:
    interval: daily
  open-pull-requests-limit: 40
- package-ecosystem: nuget
  directory: "/WebApplication.Server"
  schedule:
    interval: daily
  open-pull-requests-limit: 40
```
but that does not work because it gives this error:
`The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'`

I expect option 1 should work or am I not configuring my dependabot.yml file correctly?

Related post: https://github.community/t/dependabot-private-registries/173313

**Comment by feelepxyz** [comment]
@SwiftMJ you might be able to tell dependabot to also use the public registry if you add a `nuget.config` file with the following package source, something like (not sure if there are other required options that need to be included):

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
</configuration>
```

**Comment by SwiftMJ** [comment]
@feelepxyz I created a small example repo: https://github.com/SwiftMJ/DependabotTest

It has one public and one private dependency, both out of date. Dependabot creates a pull request for telerik but not Newtonsoft.Json.

I also tried added the `nuget.config` file but it still does not create a pull request for Newtonsoft.Json. The update log only mentions  nuget.telerik.com and does not mention api.nuget.org.

**Comment by jasonycw** [comment]
> Dependabot Preview will be shut down on August 3rd, 2021.

Any update on whether or not it will be fixed before the deadline?

**Comment by jasonycw** [comment]
Hi @lfdebrux and @asciimike, any update on this bug?

It's less than a week before Dependabot Preview shut down on August 3rd, 2021

Are we going to be stuck with the bugged native dependabot or no dependabot after a week?

**Comment by lfdebrux** [comment]
@jasonycw not sure why I've been tagged in your comment? I am not a maintainer of Dependabot or part of GitHub.

**Comment by jurre** [comment]
This seems like a bug on our end, we raise an error when the package cannot be found on the private feed [here](https://github.com/dependabot/dependabot-core/blob/f3c39032a15080ced654b59d9d3c0d53c216ec13/nuget/lib/dependabot/nuget/update_checker/repository_finder.rb#L119) and so we end up never checking the public feed.

It's a little tricky because we definitely want to check the private feed first, but we should probably hold out raising that `PrivateSourceAuthenticationFailure` until we've also checked the public feed.

I really wish there was a way to know which package should be downloaded from where, because the current approach leaves you vulnerable to a dependency confusion attack.

FWIW the `nuget.config` is pulled in correctly, and we configure the feeds correctly, we just never get to checking it, from what I could tell from a quick glance.

**Comment by jasonycw** [comment]
Sorry @lfdebrux, just me mis-clicked on the tagging suggestion list :(

@jurre is it the same behavior as dependabot preview? 
From the log in dependabot preview, https://github.com/dependabot/dependabot-core/issues/3762#issuecomment-846868094,  seems like it may be pulling from the public feed first?

**Comment by jurre** [comment]
> seems like it may be pulling from the public feed first?

Yeah, so, I think the behavior in core was roughly the same, but in preview we'd let folks specify the public feed as a private registry, which would then end up being checked first.

I think checking the public registry first is probably not desired, folks often fork or mirror public packages in their private registry, so I think we should always check there first?

**Comment by jasonycw** [comment]
> I think we should always check there first?

This I am not sure. 
Since in our case, our private feed only contain in house packages, we don't fork public one into ours.

But if some folks fork packages into their private registry and the versioning is not up to date with the public feed, like
- Private feed has `Newtonsoft.Json 12.0.3`
- Public feed has `Newtonsoft.Json 13.0.1`

Maybe it's not an issue about which registry being checked first, but need to query both feeds for every package, and then prioritize the latest private one?

**Comment by jurre** [comment]
> Maybe it's not an issue about which registry being checked first, but need to query both feeds for every package, and then prioritize the latest private one?

I'm not sure if that's a good idea, a malicious actor could figure out or guess which private packages are used in an organization and register those on the public feed, that way they could get their malicious code to run in CI environments, or even production if someone merges the PR by mistake.

That might sound like a fringe edge-case, but it happens surprisingly often :(

**Comment by brrygrdn** [comment]
@SwiftMJ thanks for providing a test repo, I've traced through the code that configures the sources for Nuget packages and @feelepxyz's comment about using a `nuget.config` should work from [looking at this code](https://github.com/dependabot/dependabot-core/blob/49b849af53d72f4e6641b0779372c6bda76df375/nuget/lib/dependabot/nuget/update_checker/repository_finder.rb#L154-L189).

I think Dependabot expects the `nuget.config` to live in the same path as configured in `dependabot.yml` as the `directory` for the nuget updates. It seems the file isn't being retrieved currently when I try dry running that test repo, but moving it should work as intended.

**Comment by SwiftMJ** [comment]
@brrygrdn I just tested and that appears to have worked! 

Although for visual studio or a multi project solution I think the `nuget.config` should be located in the root directory.

I was able to [change the dependabot directory config](https://github.com/SwiftMJ/DependabotTest/commit/1e833022f0967222bc5fc5b1cf17bbb9f080971a) so that it uses `DependabotTest.sln` rather than `DependabotTest/DependabotTest.csproj` which then meant I could move my `nuget.config` file back to the root directory. I then checked the logs and it was able to see updates where available for both nuget packages, so this looks to be working perfectly now.

Thanks for all your help.

**Comment by brrygrdn** [comment]
:wave: @SwiftMJ just as an FYI, after some further discussion on https://github.com/dependabot/dependabot-core/issues/3762, we've deployed a change that permits you to add a public nuget feed without credentials to your config file as an alternative to the `nuget.config`, e.g.

```yaml
version: 2
registries:
  telerik:
    type: nuget-feed
    url: https://nuget.telerik.com/nuget
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
  public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: nuget
    directory: "/"
    registries: "*"
    schedule:
      interval: daily
    open-pull-requests-limit: 40
```
