### ISSUE TITLE
Vendor update for bundler does not use directory config

### ISSUE THREAD

**Issue by jamiehodge** [dependabot/dependabot-core#3736]
**Package ecosystem**
bundler
**Package manager version**
n/a
**Language version**
n/a
**Manifest location and content prior to update**
n/a
**dependabot.yml content**
```yaml
updates:
  - package-ecosystem: "bundler"
    vendor: true
    directory: "/"
...
  - package-ecosystem: "bundler"
    vendor: true
    directory: "/acceptance"
```
**Updated dependency**
n/a
**What you expected to see, versus what you actually saw**
I would expect, given two directories with vendor enabled, that cache paths in both directories would be updated.

The issue is that the cache directory is resolved/updated without the directory property: https://github.com/dependabot/dependabot-core/blob/main/bundler/lib/dependabot/bundler/file_updater.rb#L83

Updates to separate directories will only result in the updating of the top-level vendor cache.

**Native package manager behavior**
n/a
**Images of the diff or a link to the PR, issue or logs**
n/a
**🕹 Bonus points: Smallest manifest that reproduces the issue**
n/a
