### ISSUE TITLE
Private gem's "public" dependencies are not found...

### ISSUE THREAD

**Issue by gencer** [dependabot/dependabot-core#3742]
I have very same issue as #3461. I have a private gem which depends on some other "public" gems and Dependabot Native seems trying to find it on GitHub Packages (private registry) rather than Rubygems.org... Therefore, I do not get any PRs from Dependabot native.

**Package ecosystem**
bundler

**Package manager version**
bundler-2.1.17

**Language version**
Ruby 3.0.1

**Manifest location and content prior to update**
/Gemfile

**dependabot.yml content**
```
version: 2
registries:
  rubygems-server-rubygems-pkg-github-com:
    type: rubygems-server
    url: https://rubygems.pkg.github.com
    token: '${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_TOKEN}}'

updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    insecure-external-code-execution: allow
    versioning-strategy: increase
    commit-message:
      prefix: chore
      include: scope
    registries:
      - rubygems-server-rubygems-pkg-github-com
```

**Updated dependency**
All dependencies causes `dkim` gem not found error

**What you expected to see, versus what you actually saw**
PRs... Got nothing except error in Dependency page

**Native package manager behavior**
See below...

**Images of the diff or a link to the PR, issue or logs**
See below...

**🕹 Bonus points: Smallest manifest that reproduces the issue**
Private repo :(

```
PLATFORMS
  ruby

RUBY VERSION
   ruby 3.0.1p64

BUNDLED WITH
   2.2.17
```

However, I am able to install all gems locally (`bundle install`) and in CI/CD side.

Dependabot shows this error for every gem it checks:

```
updater | INFO <job_135224420> Handled error whilst updating puma: dependency_file_not_resolvable {:message=>"Bundler::GemNotFound with message: Your bundle is locked to dkim (1.0.1), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of dkim (1.0.1) has removed it. You'll need to update your bundle to a version other than dkim (1.0.1) that hasn't been removed in order to install."}
```

Yes, `dkim` is a public gem and my private gem depends on it. And, These are the logs where dependabot checks `dkim`:

```
proxy | 2021/05/18 18:39:21 [206] 200 https://rubygems.pkg.github.com:443/my-org/api/v1/dependencies?gems=celluloid-gems%2Cchilkat%2Cfugit%2Crack%2Crest-client%2Csequel-bulk-audit%2Csequel-redis-cache
  proxy | 2021/05/18 18:39:21 [208] GET https://rubygems.pkg.github.com:443/my-org/api/v1/dependencies?gems=dkim%2Cmail%2Cpg%2Csequel
  proxy | 2021/05/18 18:39:21 [208] * authenticating rubygems server request (host: rubygems.pkg.github.com)
  proxy | 2021/05/18 18:39:21 [208] 200 https://rubygems.pkg.github.com:443/my-org/api/v1/dependencies?gems=dkim%2Cmail%2Cpg%2Csequel%2Cwork_queue
  proxy | 2021/05/18 18:39:21 [210] GET https://index.rubygems.org:443/versions
  proxy | 2021/05/18 18:39:21 [210] 304 https://index.rubygems.org:443/versions
  proxy | 2021/05/18 18:39:22 [214] GET https://index.rubygems.org:443/info/work_queue
  proxy | 2021/05/18 18:39:22 [214] 200 https://index.rubygems.org:443/info/work_queue
  proxy | 2021/05/18 18:39:22 [216] GET https://index.rubygems.org:443/info/dkim
  proxy | 2021/05/18 18:39:22 [216] 200 https://index.rubygems.org:443/info/dkim
  proxy | 2021/05/18 18:39:23 [218] GET 
```

_Originally posted by @gencer in https://github.com/dependabot/dependabot-core/issues/3461#issuecomment-843454592_

**Comment by jurre** [comment]
I _think_ your `Gemfile.lock` might still be using an older format. Could you check if you see separate `GEM` blocks with their own remote, so:

```
GEM
  remote: https://rubygems.pkg.github.com
  specs:
    # .. the specs
 
GEM
  remote: https://rubygems.org/
  specs:
```

or a single block, like:

```
GEM
  remote: https://rubygems.pkg.github.com
  remote: https://rubygems.org/
```

If the latter, try re-generating the lockfile so that Bundler can tell which gem is supposed to be pulled from where, and I _think_ it'll resolve things 🤞
