### ISSUE TITLE
Is dependabot.yml mandatory for GitHub Dependabot?

### ISSUE THREAD

**Issue by aravindvnair99** [dependabot/dependabot-core#3743]
I don't have an issue per se, but just a question as the title suggests. I was wondering what's the difference between enabling it in the repository settings vs adding the config file as both seemed the same to me except for the ability to configure and the docs didn't seem to be very clear on this part.

So, my question is if it is okay to just enable only this as shown here:

![](https://user-images.githubusercontent.com/8466666/118683436-66752a80-b7cf-11eb-8b1f-13a4555d9265.png)

Or is it necessary to include the config below in `.github/dependabot.yml` file in addition to enabling the two options as shown above:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
```
