### ISSUE TITLE
Ignoring wildcard version

### ISSUE THREAD

**Issue by blommish** [dependabot/dependabot-core#3746]
When there is a new update for kotlinx-coroutines-core we always get a update for the `*-native-mt` version but we want the "normal" version, ex `1.5.0` instead of `1.5.0-native-mt`. How would that be possible? 

```
version: 2

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "*-native-mt"
```
