### ISSUE TITLE
`ignore` by `label`

### ISSUE THREAD

**Issue by Tyflomate** [dependabot/dependabot-core#3747]
Hello, 

I have an api only project and dependabot created several pr to upgrade javascript dependencies and since I don't have the front in it, I don't really care about those. I saw that we can use `ignore: dependency-name` but since every pr has the label `javascript` i would like to be able to do `ignore: javascript`. Like this i wont need toignore each dependency one by one.

Here is my dependabot.yml:
```
version: 2
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```

Thanks a lot !
