### ISSUE TITLE
GitHub Actions aren't bumped if two files have different versions of an action

### ISSUE THREAD

**Issue by mueller-ma** [dependabot/dependabot-core#3750]
**Package ecosystem**
GitHub Actions
**Package manager version**
Latest on github.com
**Language version**
Latest on github.com
**Manifest location and content prior to update**

`.github/workflows/plantuml.yml`
````
[...]
    - name: checkout
      uses: actions/checkout@v1
[...]
````
`.github/workflows/build.yml`
````
[...]
    - name: checkout
      uses: actions/checkout@v2
[...]
````
**dependabot.yml content**
````yaml
version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

````
**Updated dependency**
None
**What you expected to see, versus what you actually saw**
I expect to see a PR that bumps the checkout action to version 2 in `.github/workflows/plantuml.yml`, but there isn't one.
**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**
The only occurence of `checkout` in the log: 
````
updater | INFO <job_135451773> Checking if actions/checkout 2 needs updating
  proxy | 2021/05/19 07:01:27 [014] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2021/05/19 07:01:27 [014] * authenticating git server request (host: github.com)
  proxy | 2021/05/19 07:01:27 [014] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
updater | INFO <job_135451773> Latest version is 2
updater | INFO <job_135451773> No update needed for actions/checkout 2
````

However both files are monitored:
![grafik](https://user-images.githubusercontent.com/22525368/118798335-cfc36f00-b89d-11eb-8439-d3a533b7aa8b.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**

When sorted lexically `build.yml` comes bofore `plantuml.yml`. Since this repo is private, I cannot link to it.
