### ISSUE TITLE
Migration PR not align with original dependabot config variables

### ISSUE THREAD

**Issue by jasonycw** [dependabot/dependabot-core#3762]
## Basic info:

**Package ecosystem**
nuget
**Language version**
C#
**Manifest location and content prior to update** 
n/a
**Updated dependency** 
n/a
**Native package manager behavior** 
n/a

In our dependabot setup, we have multiple nuget feeds setup so that we can update both the public nuget packages from https://api.nuget.org/v3/index.json and the private nuget packages hosted on github package.

However, I tried update a few of our repo to native dependabot with the migration PR and seems like the migration PR doesn't account for multiple nuget feeds. The result `.github/dependabot.yml` only contain the the github package link which breaks the package update process. 

This migration PR is not ready for one click migration like https://github.com/dependabot/dependabot-core/issues/3591#issuecomment-829325836 said

## Previous behavior in Dependabot Preview:

![image](https://user-images.githubusercontent.com/4518597/119116160-8bc99900-ba5a-11eb-8938-77926367f409.png)

Update logs on app.dependabot.com
```
  proxy | 2021/05/21 01:14:07 * authenticating nuget feed request (host: api.nuget.org, bearer auth)
  proxy | 2021/05/21 01:14:07 * authenticating nuget feed request (host: nuget.organization.net, bearer auth)
  proxy | 2021/05/21 01:14:08 * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2021/05/21 01:14:08 Listening (:1080)
```

## Current behavior in GitHub-native Dependabot:

![image](https://user-images.githubusercontent.com/4518597/119116721-1c07de00-ba5b-11eb-9fe6-f84dbac95698.png)

Update logs in repo's `Dependency graph` > `Dependabot`
```
  proxy | time="2021-05-21T01:08:21Z" level=info msg="proxy starting" commit=asdfdsf20f0c7297a2340dd3181976c0c2b20872cd
  proxy | 2021/05/21 01:08:21 * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2021/05/21 01:08:21 Listening (:1080)
```

``` yml
version: 2
registries:
  nuget-feed-nuget-pkg-github-com-organizationname-index-json:
    type: nuget-feed
    url: https://nuget.pkg.github.com/organizationname/index.json
    token: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_ORGANIZATIONNAME_INDEX_JSON_TOKEN}}"

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Hongkong
  open-pull-requests-limit: 99
  reviewers:
  - someone
  - jasonycw
  assignees:
  - someone
  registries:
  - nuget-feed-nuget-pkg-github-com-organizationname-index-json
```

**Comment by jurre** [comment]
> In our dependabot setup, we have multiple nuget feeds setup so that we can update both the public nuget packages from https://api.nuget.org/v3/index.json and the private nuget packages hosted on github package.

You do not need to configure the public registry, it was a noop in preview and it is stripped out for the native version.

> breaks the package update process

Have you configured the secrets as mentioned [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-encrypted-secrets-for-dependabot)

**Comment by jasonycw** [comment]
> Have you configured the secrets as mentioned here?

Yes, I have followed the PR and added the secret to the repo(some private repo not in organization) and organization level.

But in the update log, there is nothing related to api.nuget.org is shown, only the github package feed

**Comment by jasonycw** [comment]
Here are more update logs from the GitHub native dependabot showing package not being checked from public nuget feed
```
updater | INFO <job_137293849> Checking if AWSSDK.S3 3.7.0.25 needs updating
updater | INFO <job_137293849> Ignored versions:
updater | INFO <job_137293849>   3.5.7.11 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.5.7.12 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.5.8 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.5.8.3 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.5.8.6 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.5.8.8 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.5.9 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.5.9.2 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.5.9.5 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.7.0.10 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.7.0.12 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.7.0.16 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.7.0.2 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.7.0.3 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.7.0.4 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.7.0.7 - from .github/dependabot.yml
updater | INFO <job_137293849>   3.7.0.9 - from .github/dependabot.yml
  proxy | 2021/05/24 01:08:23 [078] GET https://nuget.pkg.github.com:443/organizationname/index.json
  proxy | 2021/05/24 01:08:23 [078] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2021/05/24 01:08:23 [078] 200 https://nuget.pkg.github.com:443/organizationname/index.json
  proxy | 2021/05/24 01:08:23 [080] GET https://nuget.pkg.github.com:443/organizationname/query?q=awssdk.s3&prerelease=true
  proxy | 2021/05/24 01:08:23 [080] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2021/05/24 01:08:24 [080] 200 https://nuget.pkg.github.com:443/organizationname/query?q=awssdk.s3&prerelease=true
updater | INFO <job_137293849> Latest version is 
updater | INFO <job_137293849> Requirements to unlock update_not_possible
updater | INFO <job_137293849> Requirements update strategy 
updater | INFO <job_137293849> No update possible for AWSSDK.S3 3.7.0.25
```
Where `AWSSDK.S3` should be updated to **3.7.0.27** 3 days ago according to
https://www.nuget.org/packages/AWSSDK.S3/ and https://api-v2v3search-0.nuget.org/query?q=AWSSDK.S3&prerelease=true

And other repo which is not migrated to native dependabot yet, @dependabot-preview can still create PR correctly
Here is part of the logs from https://app.dependabot.com/
```
updater | INFO <job_80911760> Checking if AWSSDK.S3 3.7.0.25 needs updating
  proxy | 2021/05/24 01:15:22 [011] GET http://nuget.organization.net/index.json
  proxy | 2021/05/24 01:15:22 [011] 200 http://nuget.organization.net/index.json
  proxy | 2021/05/24 01:15:22 [013] GET https://nuget.pkg.github.com:443/organizationname/index.json
  proxy | 2021/05/24 01:15:22 [013] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2021/05/24 01:15:22 [013] 200 https://nuget.pkg.github.com:443/organizationname/index.json
  proxy | 2021/05/24 01:15:22 [014] GET http://nuget.organization.net/flatcontainer/awssdk.s3/index.json
  proxy | 2021/05/24 01:15:22 [014] 404 http://nuget.organization.net/flatcontainer/awssdk.s3/index.json
  proxy | 2021/05/24 01:15:22 [016] GET https://api-v2v3search-0.nuget.org:443/query?q=awssdk.s3&prerelease=true
  proxy | 2021/05/24 01:15:23 [016] 200 https://api-v2v3search-0.nuget.org:443/query?q=awssdk.s3&prerelease=true
  proxy | 2021/05/24 01:15:23 [018] GET https://nuget.pkg.github.com:443/organizationname/query?q=awssdk.s3&prerelease=true
  proxy | 2021/05/24 01:15:23 [018] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2021/05/24 01:15:23 [018] 200 https://nuget.pkg.github.com:443/organizationname/query?q=awssdk.s3&prerelease=true
updater | INFO <job_80911760> Latest version is 3.7.0.27
updater | INFO <job_80911760> Requirements to unlock own
updater | INFO <job_80911760> Requirements update strategy 
updater | INFO <job_80911760> Updating AWSSDK.S3 from 3.7.0.25 to 3.7.0.27
updater | INFO <job_80911760> Submitting AWSSDK.S3 pull request for creation
```

**Comment by jasonycw** [comment]
This maybe the same issue as https://github.com/dependabot/dependabot-core/issues/3724

If default public nuget feed should always be check at the first place, it's the same bug.
Or if there is a need to support multiple nuget feeds inside `dependabot.yml`?

**Comment by jasonycw** [comment]
Hi @jurre and @brrygrdn, any update on this bug?

> Dependabot Preview will be shut down on August 3rd, 2021.

It's only a week left before dependabot preview shut down but the native dependabot still not pulling public nuget feed properly when there are 3rd party nuget feed.

Are we going to be stuck with the bugged native dependabot after August 3rd?

**Comment by brrygrdn** [comment]
Sorry for the delay in replying @jasonycw - to elaborate on my comment in #3724, I believe the correct way to configure this is to add a `nuget.config` file to your project root directory as @feelepxyz mentioned:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
</configuration>
```

Dependabot builds a list of repositories to look up packages in the [RepositoryFinder class](https://github.com/dependabot/dependabot-core/blob/49b849af53d72f4e6641b0779372c6bda76df375/nuget/lib/dependabot/nuget/update_checker/repository_finder.rb) which inserts `https://api.nuget.org/v3/index.json` if no other source is configured [here](https://github.com/dependabot/dependabot-core/blob/49b849af53d72f4e6641b0779372c6bda76df375/nuget/lib/dependabot/nuget/update_checker/repository_finder.rb#L135). 

In Dependabot Preview this is not a problem as looking at your existing configuration, you have a config variable that provides this URI:

![image](https://user-images.githubusercontent.com/4518597/119116160-8bc99900-ba5a-11eb-8938-77926367f409.png)

I believe this workflow existed historically so that using a mix of public and private sources had to be explicitly configured, which core 'opting out' of the public repo once any other source was provided. By explicitly indicating the official public source in your `nuget.config` you will be providing Native Dependabot with instruction to use it.

Let me know if this helps or if you have any further issues.

**Comment by jasonycw** [comment]
What about if `dependabot.yml` can support multiple feed?
``` YAML
version: 2
registries:
  nuget-feed-nuget-pkg-github-com-organizationname-index-json:
    type: nuget-feed
    url: https://nuget.pkg.github.com/organizationname/index.json
    token: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_ORGANIZATIONNAME_INDEX_JSON_TOKEN}}"
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Hongkong
  open-pull-requests-limit: 99
  reviewers:
  - someone
  - jasonycw
  assignees:
  - someone
  registries:
  - nuget-feed-nuget-pkg-github-com-organizationname-index-json
  - public-nuget
```

Currently, native dependabot doesn't support this, it will say 
![image](https://user-images.githubusercontent.com/4518597/127254546-e0242794-7360-4c61-bbf7-4a43ddb427fd.png)

**Comment by brrygrdn** [comment]
Thanks for the feedback @jasonycw, we're taking a look at this change internally to see what is practical.

**Comment by michakinchen1988** [comment]
Hey I've had this dependable done for years I really don't know what I'm doing im teaching my selfbi did not mean to such ya up like that but it been running for years for me can u help me out on few pointer ideasOn Jul 28, 2021 11:45 AM, Barry Gordon ***@***.***> wrote:
Thanks for the feedback @jasonycw, we're taking a look at this change internally to see what is practical.

**Comment by brrygrdn** [comment]
👋🏻  @jasonycw I've deployed a change that permits you to add the public feed explicitly to the config file, e.g.

```yaml
version: 2
registries:
  nuget-feed-nuget-pkg-github-com-organizationname-index-json:
    type: nuget-feed
    url: https://nuget.pkg.github.com/organizationname/index.json
    token: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_ORGANIZATIONNAME_INDEX_JSON_TOKEN}}"
  public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Hongkong
  open-pull-requests-limit: 99
  reviewers:
  - someone
  - jasonycw
  assignees:
  - someone
  registries:
  - nuget-feed-nuget-pkg-github-com-organizationname-index-json
  - public
```

Hopefully that helps resolve your issue.
