### ISSUE TITLE
Dependabot can't fetch secrets from GitHub?

### ISSUE THREAD

**Issue by ryanzidago** [dependabot/dependabot-core#3764]
**dependabot.yml content**

```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "mix" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/assets/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```

**What you expected to see, versus what you actually saw?**

**I expected that, once Dependabot's open up a PR for updating a package, Dependabot has access to GitHub Secrets.** 
Here's the problem however:
I'm using this [action](https://github.com/shaunco/ssh-agent/tree/git-repo-mapping) to fetch private repositories from GitHub that will then be used as private dependencies in my projects. In this action, [each dependencies is fetched in order, based on a secret](https://github.com/shaunco/ssh-agent/tree/git-repo-mapping#using-multiple-keys).

The problem is that, once **Dependabot opens up a PR to update a dependency, the CI stops and returns the following error**: 

```
The ssh-private-key argument is empty. Maybe the secret has not been configured, or you are using a wrong secret name in your workflow file.
```

Which is false because I configured all the keys in my organisation's settings for Dependabot under https://github.com/organizations/MY-ORGANIZATION/settings/secrets/dependabot. I know that the keys are correct. I also explicitely gave Dependabot access to all of the private repositories that I which to be updated by Dependabot. Basically, I did what's mentioned in this blog [post](https://github.blog/2021-03-15-dependabot-private-dependencies/).

**What did I tried to solve this issue?**

+ I told Dependabot to recreate the PR with `@dependabot recreate` => Didn't work
+ I tried to overwrite the Organization's secrets with secrets configured at the repository level. => Didn't work either
+ I manually restarted the failed workflow triggered by Dependabot's PR => It works, but is cumbersome.

**Could it be that Dependabot has a problem with fetching secrets?**

**Comment by jurre** [comment]
You'll still need to add configuration for those secrets to the config file, I think this should solve your problem: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#configuration-options-for-private-registries

**Comment by ryanzidago** [comment]
> You'll still need to add configuration for those secrets to the config file, I think this should solve your problem: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#configuration-options-for-private-registries

I added the following lines to the `dependabot.yml` file:
```yml
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_ACCESS_TOKEN }}
```

I also created a GitHub Access Token from my profile and put it in my repo, under https://github.com/MYORGANIZATION/myrepo/settings/secrets/dependabot

However, I still get the same error :thinking:
