### ISSUE TITLE
Cannot provide empty password

### ISSUE THREAD

**Issue by mike-carey** [dependabot/dependabot-core#3783]
**Package ecosystem**

composer

**Package manager version**

v2

**Language version**

PHP 7

**Manifest location and content prior to update**

composer.json
```json
{
  "name": "mikecarey/wpmudev-dependabot-test",
  "type": "project",
  "authors": [],
  "repositories": [
    {
      "type": "composer",
      "url": "https://wpmudev.com"
    }
  ],
  "extra": {
    "wordpress-install-dir": "html",
    "installer-paths": {
      "html/wp-content/plugins/{$name}/": [
        "type:wordpress-plugin"
      ]
    }
  },
  "require": {
    "php": ">=7.3.0",
    "johnpbloch/wordpress": "^5.7",
    "wpmudev/wp-smush-pro": "^3.8"
  },
  "require-dev": {
    "wp-cli/wp-cli": "^2.3"
  }
}

```

**dependabot.yml content**

```yaml
version: 2
registries:
  wpmudev:
    type: composer-repository
    url: https://wpmudev.com/
    username: ${{secrets.WPMUDEV_API_KEY}}
    password: ''
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: all
    labels:
      - maintenance
      - dependencies
    registries:
      - wpmudev
```

**Updated dependency**

Not necessarily this specific dependency, but this is an example of a dependency behind auth with no password that was having trouble getting updates.

wpmudev/wp-smush-pro 3.8.4 to 3.8.5

**What you expected to see, versus what you actually saw**

Dependabot is **requiring** a password to be provided through Github Secrets.  Dependabot made use of previously acceptable version of config for security updates; however, that was a red herring since I assumed it was accepting my config when it was not.

When providing an empty string for the password, heading to the dependency graph insights via dependabot tab gives error:
```
Tokens should be stored as a GitHub secret.
```
This is under `https://github.com/<owner>/<repository>/network/updates`

I expected it to accept an empty password.  WPMU Dev uses basic auth with the api key as the username and no password.  
WPMU Dev specifically uses no password: https://wpmudev.com/blog/composer-repository/

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

I have been debugging this on a private repository, but have created a small test repository with minimal dependencies that I have been playing with; however, it makes use of one of WPMU Dev's pay-for products, so you will need an API key.

https://github.com/mike-carey/wpmudev-dependabot-test

There is a Github community discussion where someone is attempting to make use of no auth as well: https://github.community/t/dependabot-private-composer-repositories-formatting/173619
