### ISSUE TITLE
weekly schedule not working

### ISSUE THREAD

**Issue by TheRealAstoo** [dependabot/dependabot-core#3785]
**Package ecosystem**
  `npm`
 
**Package manager version**
  `yarn 1.22.5`
 
**Language version**
  `nodejs 14.15.4`
 
**Manifest location and content prior to update**
  `/services/api/package.json`
  `/services/front/package.json`
  `/services/slidedeck/package.json`
 
**dependabot.yml content**
  ```yaml
    version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/services/api"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    reviewers:
    - "TheRealAstoo"

  - package-ecosystem: "npm"
    directory: "/services/front"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    reviewers:
    - "TheRealAstoo"

  - package-ecosystem: "npm"
    directory: "/services/slidedeck"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    reviewers:
    - "TheRealAstoo"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    reviewers:
    - "TheRealAstoo"
````

**What you expected to see, versus what you actually saw**
I expected to see some PRs the friday at 10am, but I have live PRs .
