### ISSUE TITLE
Dependabot keeps opening PR:s when merging one, even though schedule is set to once a week.

### ISSUE THREAD

**Issue by samirergaibi** [dependabot/dependabot-core#3824]
As soon as a dependabot PR is merged in the repo dependabot starts checking for new updates and opens another one, even though the schedule is set to only check once a week.

is this expected behaviour? I could not find anything about that being the case in the documentation.

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      day: 'thursday'
      interval: 'weekly'
      time: '02:00'
      timezone: 'Europe/Stockholm'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '@material-ui/core'
        versions:
          - '> 4.11.4, < 4.12'
      - dependency-name: '@material-ui/core'
        versions:
          - 4.11.4
      - dependency-name: styled-components
        versions:
          - 5.2.2
      - dependency-name: eslint-plugin-react
        versions:
          - 7.23.0
        # Broke linting jobs
      - dependency-name: eslint-plugin-import
        versions:
          - '2.23.x'

```
