### ISSUE TITLE
pip package resolved to non-canonical version in dependency graph

### ISSUE THREAD

**Issue by ntravis** [dependabot/dependabot-core#3828]
**Package ecosystem**
pip
**Package manager version**
n/a (whatever dependabot is using)
**Language version**
Python 3.7 in our deployment but that's not relevant for dependabot
**Manifest location and content prior to update**
/requirements/default.txt
**dependabot.yml content**

```yaml
version: 2
registries:
  python-index-nexus-fool-com-repository-fool-pypi-simple:
    type: python-index
    url: https://nexus.fool.com/repository/fool-pypi/simple/
    replaces-base: true
    username: "${{secrets.PYTHON_INDEX_NEXUS_FOOL_COM_REPOSITORY_FOOL_PYPI_SIMPLE_USERNAME}}"
    password: "${{secrets.PYTHON_INDEX_NEXUS_FOOL_COM_REPOSITORY_FOOL_PYPI_SIMPLE_PASSWORD}}"

updates:
- package-ecosystem: pip
  insecure-external-code-execution: allow
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  registries:
  - python-index-nexus-fool-com-repository-fool-pypi-simple
```

**Updated dependency**
ddtrace
**What you expected to see, versus what you actually saw**
In the dependency graph view, I would expect that ddtrace is resolved to the canonical version from [datadog's repo](https://github.com/Datadog/dd-trace-py) rather than peloton's [outdated fork](https://github.com/pelotoncycle/dd-trace-py). The underlying version that is actually installed is correctly coming from Datadog via pypi. This is only one example from this particular repository. django-redis appears to be doing the same thing (linking to this [dead fork](https://github.com/jianglb-alibaba/django-redis) instead of the canonical [jazzband repo](https://github.com/jazzband/django-redis).
 
**Native package manager behavior**
n/a
**Images of the diff or a link to the PR, issue or logs**
non-public repo but here is a screenshot of the dep graph:
![image](https://user-images.githubusercontent.com/8976020/120387833-60676980-c2f8-11eb-9dc0-0817585ea38c.png)

All links are above

**🕹 Bonus points: Smallest manifest that reproduces the issue**
