### ISSUE TITLE
Create way for external CI systems to know if commit came from Dependabot

### ISSUE THREAD

**Issue by gdams** [dependabot/dependabot-core#3849]
### Background

At the Eclipse Foundation (and several other software foundations), contributors must sign a contributing agreement before creating pull requests. For this reason, whenever dependabot creates a pull request in my projects, one of the status checks fails and blocks the auto-merge. We had considered whitelisting the user but `support@github.com` is used by several GitHub services so this was deemed to not be secure.

### Proposal
Allow users to specify a GitHub token in the `dependabot.yml` which comes from the repo secrets.

e.g
```yaml
version: 2
github-token: ${{ secrets.GITHUB_TOKEN }}
updates:
- package-ecosystem: npm
  schedule:
    interval: daily
```
