### ISSUE TITLE
Dependabot does not have issue commenting/github API rights during CI

### ISSUE THREAD

**Issue by Pomax** [dependabot/dependabot-core#3860]
**Package ecosystem**

github actions

**What you expected to see, versus what you actually saw**

We have a CI file that includes this snippet:

```yaml
- uses: actions/github-script@v3
      if: ${{ failure() }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'This PR introduces visual differences. Click [here](https://example.org/someurl) to inspect the diffs.'
          })
```

And this ran fine for PRs opened by the `dependabot-preview` account, but throws the following error for PRs filed by the new `dependabot` account:

```
RequestError [HttpError]: Resource not accessible by integration
Error: Unhandled error: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v3/dist/index.js:2342:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 07 Jun 2021 16:35:40 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3',
    'x-github-request-id': '0402:3080:20B9D70:61EDECC:60BE4ADC',
    'x-ratelimit-limit': '15000',
    'x-ratelimit-remaining': '14943',
    'x-ratelimit-reset': '1623086793',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '57',
    'x-xss-protection': '0'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/mozilla/foundation.mozilla.org/issues/6826/comments',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.2.1 Node.js/12.13.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"This PR introduces visual differences. Click [here](https://foundation-mozilla-org-visual-ci.s3.us-east-1.amazonaws.com/pull/6826/merge/index.html?reference=main&compare=compare) to inspect the diffs."}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/issues#create-an-issue-comment'
}
```

For example https://github.com/mozilla/foundation.mozilla.org/pull/6826/checks?check_run_id=2766120004
