### ISSUE TITLE
Dependabot Only Updated Lockfile

### ISSUE THREAD

**Issue by R4356th** [dependabot/dependabot-core#3891]
**Package ecosystem**
npm
**Package manager version**
Whatever version GitHub uses
**Language version**
Whatever version GitHub uses
**Manifest location and content prior to update**
https://github.com/R4356th/minhtml/blob/main/package.json
**dependabot.yml content**
https://github.com/R4356th/minhtml/blob/main/.github/dependabot.yml
**Updated dependency**
``eslint``, ``webpack`` etc.
**What you expected to see, versus what you actually saw**
I expected Dependabot to update ``package.json`` alongside ``package-lock.json`` but that is not what happened; only the lockfile was updated.
**Native package manager behavior**
Both get updated
**Images of the diff or a link to the PR, issue or logs**
R4356th/minhtml#31

Note that even though I only linked a personal repo above, I have also noticed this in many others and had to manually update the lockfile.

**Comment by feelepxyz** [comment]
@R4356th your project is being identified as a library so dependabot will try to widen the `package.json` requirements, meaning it won't update it if it matches the new version. It's currently a known issue that we only update the lockfile in this case.

You can change the default versioning strategy dependabot uses to always keep the `package.json` requirement up to date with the latest version: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#versioning-strategy

```yml
version: 2
updates:
  - package-ecosystem: npm
    directory: "/" 
    schedule:
      interval: "daily"
      time: "11:00"
    open-pull-requests-limit: 15
    reviewers:
    - r4356th
    # Always increase the version requirement to match the new version.
    versioning-strategy: increase
```
