### ISSUE TITLE
IP Allow List prevents updating private images

### ISSUE THREAD

**Issue by bittelc** [dependabot/dependabot-core#3903]
**Package ecosystem**

<details>
<summary>dependabot.yml content</summary>

```

version: 2
registries:
  pleo-gradle-github-registry:
    type: maven-repository
    url: 'https://maven.pkg.github.com/pleo-io'
    username: ""
    password: ${{ secrets._redacted_  }}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"  # Weekdays only
    pull-request-branch-name:
      separator: "-"
    registries: "*"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"

```

</details>

**What you expected to see, versus what you actually saw**

I expect to see have the same experience with Dependabot before turning on the IP Allow List (GitHub Enterprise feature) as I have after turn on the IP Allow List. I also expect that I may need to add some Dependabot-specific IPs to the IP Allow List in order to accomplish this continued functionality, however there is no place (easily findable) to find these IPs so that I can add them to the IP Allow List.

The actual functionality is that I have a very happy, successful Dependabot setup before turning on the IP Allow List. After flipping the switch to turn on the IP Allow List, I receive 4xx errors when Dependabot attempts to retrieve packages from private GitHub registries (owned by the org that Dependabot is running against (in this case `pleo-io`)).

**Dependabot log output**
This is the log from:
![image](https://user-images.githubusercontent.com/6162362/122047290-40e43c80-cde0-11eb-83aa-75a1d22d74b3.png)
––––
Resulting in:
––––
![image](https://user-images.githubusercontent.com/6162362/122047389-62ddbf00-cde0-11eb-802a-8d7d01eccf20.png)

<details>
<summary>Log sample output of failed update: content</summary>

```


  proxy | 2021/06/15 11:44:13 [022] 200 https://plugins.gradle.org:443/m2/org/barfuin/gradle/jacocolog/org.barfuin.gradle.jacocolog.gradle.plugin/maven-metadata.xml
  proxy | 2021/06/15 11:44:13 [024] GET https://repo.maven.apache.org:443/maven2/org/barfuin/gradle/jacocolog/org.barfuin.gradle.jacocolog.gradle.plugin/maven-metadata.xml
  proxy | 2021/06/15 11:44:13 [024] 404 https://repo.maven.apache.org:443/maven2/org/barfuin/gradle/jacocolog/org.barfuin.gradle.jacocolog.gradle.plugin/maven-metadata.xml
  proxy | 2021/06/15 11:44:13 [026] GET https://maven.pkg.github.com:443/pleo-io/org/barfuin/gradle/jacocolog/org.barfuin.gradle.jacocolog.gradle.plugin/maven-metadata.xml
  proxy | 2021/06/15 11:44:13 [026] * authenticating maven repository request (host: maven.pkg.github.com)
  proxy | 2021/06/15 11:44:13 [026] 401 https://maven.pkg.github.com:443/pleo-io/org/barfuin/gradle/jacocolog/org.barfuin.gradle.jacocolog.gradle.plugin/maven-metadata.xml
updater | INFO <job_161521922> Latest version is 1.2.4
updater | INFO <job_161521922> No update needed for org.barfuin.gradle.jacocolog 1.2.4
updater | INFO <job_161521922> Checking if io.dropwizard.metrics:metrics-healthchecks 4.2.0 needs updating
  proxy | 2021/06/15 11:44:13 [028] GET https://repo.maven.apache.org:443/maven2/io/dropwizard/metrics/metrics-healthchecks/maven-metadata.xml
  proxy | 2021/06/15 11:44:13 [028] 200 https://repo.maven.apache.org:443/maven2/io/dropwizard/metrics/metrics-healthchecks/maven-metadata.xml
  proxy | 2021/06/15 11:44:13 [030] GET https://maven.pkg.github.com:443/pleo-io/io/dropwizard/metrics/metrics-healthchecks/maven-metadata.xml
  proxy | 2021/06/15 11:44:13 [030] * authenticating maven repository request (host: maven.pkg.github.com)
  proxy | 2021/06/15 11:44:13 [030] 401 https://maven.pkg.github.com:443/pleo-io/io/dropwizard/metrics/metrics-healthchecks/maven-metadata.xml


```

</details>
