### ISSUE TITLE
bug: Cannot use secrets for private registry username + password (python, Gemfury)

### ISSUE THREAD

**Issue by iamnoah** [dependabot/dependabot-core#3924]
I've setup a private python registry hosted on Gemfury per these instructions: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-encrypted-secrets-for-dependabot

I have two organization level secrets (but adding secrets at the repository level has the same result) with this Dependabot config:

```yaml
version: 2
registries:
  fury:
    type: python-index
    url: <private>
    username: ${{ secrets.FURY_DEPLOY_TOKEN }}
    password: ${{ secrets.FURY_DEPLOY_PASS }}
updates:
  - package-ecosystem: pip
    directory: /
    insecure-external-code-execution: allow
    target-branch: develop
    registries:
      - fury
    schedule:
      interval: daily
```

The result is this:

<img width="916" alt="Screen Shot 2021-06-17 at 1 28 13 PM" src="https://user-images.githubusercontent.com/139201/122316384-e2e65f00-cf6f-11eb-89ce-d385b7b5a937.png">

For Gemfury, the username is the secret access token. The FURY_DEPLOY_PASS secret is just the string "NOPASS" as a [workaround](https://github.com/dependabot/dependabot-core/issues/3783).
