### ISSUE TITLE
Dependabot doesn't recognize updated Docker images.

### ISSUE THREAD

**Issue by oittaa** [dependabot/dependabot-core#3929]
dependabot.yml

```
version: 2
updates:
- package-ecosystem: pip
  directory: "/app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/app"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  
```

https://github.com/oittaa/avif-converter/network/updates/163792800

important part from the log:
```
updater | INFO <job_163792800> Checking if oittaa/imagemagick 7.0.11-14 needs updating
...
updater | INFO <job_163792800> Latest version is 7.0.11-14
updater | INFO <job_163792800> No update needed for oittaa/imagemagick 7.0.11-14
updater | INFO <job_163792800> Finished job processing
```

Even though there's version 7.1.0-0 which should be used: 
https://hub.docker.com/r/oittaa/imagemagick/tags?page=1&ordering=name
