### ISSUE TITLE
Dependabot creates invalid Yarn 2 lock file

### ISSUE THREAD

**Issue by FizzBuzz791** [dependabot/dependabot-core#3939]
**Package ecosystem**
npm
**Package manager version**
Yarn 2.4.2
**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```
**What you expected to see, versus what you actually saw**
I expect a valid yarn.lock file.

It is using the format;
...
version "x.y.z"
resolved "https://registry.yarnpkg.com/..."
...

Note that there is no ":" between the key value pair.

I expect to see;
...
version: x.y.z
resolution: "package"
...
**Native package manager behavior**
If I checkout a dependabot branch, delete the lock file and then run `yarn install`, it generates the file with the above expected format.
**Images of the diff or a link to the PR, issue or logs**
The red is what dependabot produces, the green is what you get when you delete the lock file and run `yarn install`
![image](https://user-images.githubusercontent.com/2747764/122629249-3c749800-d0ee-11eb-830d-a12ad5122e55.png)
**🕹 Bonus points: Smallest manifest that reproduces the issue**
Easily reproducible with a vanilla Create React App.
