### ISSUE TITLE
Spec multiple directories for one package-ecosystem

### ISSUE THREAD

**Issue by tobiasehlert** [dependabot/dependabot-core#3951]
Hello,

I've a repo with around 50 directories where 25~ have a Terraform provider file specifying a provider version.
As it looks to me, I need to create a separate entry for every modules directory in dependabot.yaml, which results in a very long file. Or maybe that I would add /modules instead and that depedabot would go through all .tf files inside the directories recursively..

E.g. of 3 helm provider modules
```yaml
  - package-ecosystem: "terraform"
    directory: "/modules/helm_cert_manager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/modules/helm_external_dns"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/modules/helm_ingress_nginx"
    schedule:
      interval: "weekly"
```

This should be much more nice to do this with the 3 helm repos
```yaml
  - package-ecosystem: "terraform"
    directory:
      - "/modules/helm_cert_manager"
      - "/modules/helm_external_dns"
      - "/modules/helm_ingress_nginx"
    schedule:
      interval: "weekly"
```

Or maybe even better to be able to use it recursively like this..
```yaml
  - package-ecosystem: "terraform"
    directory: "/modules"
    schedule:
      interval: "weekly"
```

And if one provider gets updated, the bump currently is done for every `-package-ecosystem` so with the combine of directories, it's maybe possible to get one PR for one provider bump and not multiple PRs for the same provider-bump?
