### ISSUE TITLE
PR created for update when PackageReference uses fixed version

### ISSUE THREAD

**Issue by flcdrg** [dependabot/dependabot-core#3982]
**Package ecosystem**
NuGet / PackageReference
**Package manager version**
.NET SDK 5.0.301

```yaml
version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
```

**Updated dependency**

```xml
-    <PackageReference Include="Microsoft.Extensions.Http" Version="[3.1.13]" />
+    <PackageReference Include="Microsoft.Extensions.Http" Version="[5.0.0]" />
```

**What you expected to see, versus what you actually saw**
This package reference has a fixed version number, so I would not expect Dependabot to try and update it.

**Native package manager behavior**
NuGet / Visual Studio does not offer to upgrade this package.

**Images of the diff or a link to the PR, issue or logs**

![image](https://user-images.githubusercontent.com/384747/123189995-f0569880-d4dd-11eb-9c3e-cf897466d4d3.png)
