### ISSUE TITLE
More than one yarn dep updated in a PR

### ISSUE THREAD

**Issue by Forfold** [dependabot/dependabot-core#3985]
Recently we have noticed Dependabot attempt to update more than one dependency for a PR, though the title and description for the PR still describe updating a single dependency. Details outlined below:

**Package ecosystem**
yarn

**Package manager version**
yarn 1.22.10

**Language version**
node 15.13.0

**Manifest location and content prior to update**
https://github.com/target/goalert/blob/master/package.json
https://github.com/target/goalert/blob/master/web/src/package.json

**dependabot.yml content**
https://github.com/target/goalert/blob/master/.github/dependabot.yml
```
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '09:00'
      timezone: 'America/Chicago'
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: '@date-io/luxon'
        versions:
          - '<=3.0.0'
      - dependency-name: '@date-io/core'
        versions:
          - 2.10.7
```

**Updated dependency**
`cssnano`, though I have other examples

**What you expected to see, versus what you actually saw**
Expect only `cssnano` to update, however `@types/luxon` is also updated

**Images of the diff or a link to the PR, issue or logs**
https://github.com/target/goalert/pull/1642/files
