### ISSUE TITLE
Private git submodules still inaccessible from workflows

### ISSUE THREAD

**Issue by srittau** [dependabot/dependabot-core#3999]
Please consider the following workflow, where the submodules are private GitHub repositories:

```yaml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.WHATEVER }}
```

I haven't found a way to make this work. The private submodule has been added to https://github.com/organizations/orgname/settings/security_analysis, github has been added as a private registry to `.github/dependabot.yml`. If the token is provided, it fails due to an empty token due to #3253. Removing the token has no effect either, but isn't an option anyway, since it will break pushes by regular users. Splitting the workflow is also not possible, since naturally the checkout action is required in any case. Neither the documentation nor the FAQ in #3253 has been helpful.
