### ISSUE TITLE
Dependabot refused to execute external code

### ISSUE THREAD

**Issue by natematykiewicz** [dependabot/dependabot-core#4002]
## Basic info:

**Package ecosystem**
Bundler
**Package manager version**
1.17.3
**Language version**
Ruby 2.5.1
**Manifest location and content prior to update**
Gemfile
**Updated dependency**

**Native package manager behavior**
It installs normally

**Images of the diff or a link to the PR, issue or logs**
```yaml
version: 2
registries:
  rubygems-server-rubygems-pkg-github-com-auctionedge:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/auctionedge
    username: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_AUCTIONEDGE_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_AUCTIONEDGE_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rack-cors
    versions:
    - 1.1.1
  registries:
  - rubygems-server-rubygems-pkg-github-com-auctionedge
 ```

## Previous behavior in Dependabot Preview:
It found updates and submitted PRs, which had passing CI.

## Current behavior in GitHub-native Dependabot:
Fails to check for updates

> Dependabot refused to execute external code
Dependabot blocked external code required for this update. Please set insecure-external-code-execution: allow in the config if you trust all dependencies' supply chain.

```
proxy | time="2021-06-29T05:42:19Z" level=info msg="proxy starting" commit=97f78db7d4c42ec4f30c03ac9a981efd790f852d
  proxy | 2021/06/29 05:42:19 Listening (:1080)
updater | 2021-06-29T05:42:19.893917166 [166573220:main:WARN:src/devices/src/legacy/serial.rs:434] Detached the serial input due to peer close/error.
updater | time="2021-06-29T05:42:21Z" level=info msg="guest starting" commit=524810a0a39a9005af53185e9bb7817463751bc4
updater | time="2021-06-29T05:42:21Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=166573220 updater_timeout=45m0s updater_version=0.156.2-036ce87c7e75042bfd46a4211778704047bf3e40
updater | I, [2021-06-29T05:42:23.011534 #9]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.3-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_166573220> Starting job processing
  proxy | 2021/06/29 05:42:25 [002] GET https://api.github.com:443/repos/auctionedge/the-collector
  proxy | 2021/06/29 05:42:25 [002] * authenticating github api request
  proxy | 2021/06/29 05:42:25 [002] 200 https://api.github.com:443/repos/auctionedge/the-collector
  proxy | 2021/06/29 05:42:25 [004] GET https://api.github.com:443/repos/auctionedge/the-collector/git/refs/heads/master
  proxy | 2021/06/29 05:42:25 [004] * authenticating github api request
  proxy | 2021/06/29 05:42:25 [004] 200 https://api.github.com:443/repos/auctionedge/the-collector/git/refs/heads/master
  proxy | 2021/06/29 05:42:25 [006] GET https://api.github.com:443/repos/auctionedge/the-collector/contents/?ref=6e6c30bc90616c6227a38c419cab01084822a763
  proxy | 2021/06/29 05:42:25 [006] * authenticating github api request
  proxy | 2021/06/29 05:42:25 [006] 200 https://api.github.com:443/repos/auctionedge/the-collector/contents/?ref=6e6c30bc90616c6227a38c419cab01084822a763
  proxy | 2021/06/29 05:42:25 [008] GET https://api.github.com:443/repos/auctionedge/the-collector/contents/Gemfile?ref=6e6c30bc90616c6227a38c419cab01084822a763
  proxy | 2021/06/29 05:42:25 [008] * authenticating github api request
  proxy | 2021/06/29 05:42:26 [008] 200 https://api.github.com:443/repos/auctionedge/the-collector/contents/Gemfile?ref=6e6c30bc90616c6227a38c419cab01084822a763
  proxy | 2021/06/29 05:42:26 [010] GET https://api.github.com:443/repos/auctionedge/the-collector/contents/Gemfile.lock?ref=6e6c30bc90616c6227a38c419cab01084822a763
  proxy | 2021/06/29 05:42:26 [010] * authenticating github api request
  proxy | 2021/06/29 05:42:26 [010] 200 https://api.github.com:443/repos/auctionedge/the-collector/contents/Gemfile.lock?ref=6e6c30bc90616c6227a38c419cab01084822a763
updater | INFO <job_166573220> Finished job processing
updater | time="2021-06-29T05:42:26Z" level=info msg="task complete" container_id=job-166573220-file-fetcher exit_code=0 job_id=166573220 step=fetcher
updater | I, [2021-06-29T05:42:27.251897 #9]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.3-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_166573220> Starting job processing
updater | INFO <job_166573220> Starting update job for auctionedge/the-collector
updater | INFO <job_166573220> Finished job processing
updater | time="2021-06-29T05:42:31Z" level=info msg="task complete" container_id=job-166573220-updater exit_code=0 job_id=166573220 step=updater
```

## Notes

I have no idea what external code it's attempting to run. I do have 1 gem installed via git. Could this be the problem? Is there a way to know exactly what external code it's trying to run?
