### ISSUE TITLE
Error during run: Dependabot::Clients::Azure::NotFound

### ISSUE THREAD

**Issue by pimjansen** [dependabot/dependabot-core#4010]
Im trying to run Dependabot inside Azure Pipelines. For my own organisation all runs fine however the exact same content seems to fail at a different organisation. The `dependabot.yml` file is actually a 1 on 1 copy and also the error is something i can not put my finger on.

The actual exception: `Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)`

**Package ecosystem**
composer

**Package manager version**
2

**Language version**
php 7.4

**Manifest location and content prior to update**
composer.json

**dependabot.yml content**
```yml
version: 2
updates:
  - package-ecosystem: composer
    directory: /
    target-branch: main
    schedule:
      interval: daily
    versioning-strategy: increase
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
```
**Updated dependency**
n/a
**What you expected to see, versus what you actually saw**
```shell
5d539f19867e: Pull complete
Digest: sha256:424a2968ee6d4382cba78642c75e2c376871b78f413fd49a3ec2e690119759ae
Status: Downloaded newer image for tingle/dependabot-azure-devops:latest
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.3-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.2/lib/dependabot/clients/azure.rb:231:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.2/lib/dependabot/clients/azure.rb:89:in `fetch_repo_contents_treeroot'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.2/lib/dependabot/clients/azure.rb:65:in `fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.2/lib/dependabot/file_fetchers/base.rb:283:in `_azure_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.2/lib/dependabot/file_fetchers/base.rb:207:in `_fetch_repo_contents_fully_specified'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.2/lib/dependabot/file_fetchers/base.rb:178:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.2/lib/dependabot/file_fetchers/base.rb:160:in `repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-composer-0.156.2/lib/dependabot/composer/file_fetcher.rb:106:in `expand_path'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-composer-0.156.2/lib/dependabot/composer/file_fetcher.rb:55:in `block in path_dependencies'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-composer-0.156.2/lib/dependabot/composer/file_fetcher.rb:54:in `each'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-composer-0.156.2/lib/dependabot/composer/file_fetcher.rb:54:in `path_dependencies'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-composer-0.156.2/lib/dependabot/composer/file_fetcher.rb:27:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.156.2/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using 'https://dev.azure.com:443/' as API endpoint
Fetching composer dependency files for mg/Webshop_sw6/_git/webshop-sw6-poc
Targeting 'main' branch under '/' directory
Using 'bump_versions' requirements update strategy
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Dependabot
```
**Native package manager behavior**
n/a
**Images of the diff or a link to the PR, issue or logs**
n/a
**🕹 Bonus points: Smallest manifest that reproduces the issue**
```yml
# Azure Pipeline
pool:
  vmImage: ubuntu-latest

trigger: none

schedules:
  - cron: "30 2 * * 0,1,2,3,4"
    branches:
      include:
        - main
    always: 'true'
    displayName: Dependabot

steps:
  - task: dependabot@1
    displayName: Dependabot
    inputs:
      useConfigFile: true
      dockerImageTag: latest
```
