### ISSUE TITLE
Dependabot respects requirements file more than its configuration file

### ISSUE THREAD

**Issue by dmytrostriletskyi** [dependabot/dependabot-core#4017]
Hi, 

first, thank you for supporting this great project. Second, unfortunately, I have some problems with Dependabot behavior.
I use the second version with GitHub. 

My configuration file looks like:

```yaml
version: 2
registries: 
  nexus:
    type: python-index
    url: https://nexus.external.project.com/repository/pypi-all/simple
    username: ${{secrets.NEXUS_USERNAME}}
    password: ${{secrets.NEXUS_PASSWORD}}
updates:
  - package-ecosystem: "pip"
    insecure-external-code-execution: allow
    registries:
      - nexus
    ...
```

And my requirements file looks like:

```
--index-url https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@nexus.internal.project.com/repository/pypi-all/simple
some-private-package==0.0.7
...
```

You can see that private registers' domains are different. I download packages from private register (nexus.internal.project.com), which is in my private network. But for Dependabot, I've created the different domain (nexus.external.project.com), which is public (but only for Dependabot IPs).

The problem I've faced, that Dependabot ignore what is specified in the configurations file and instead of looking for updates by external domain from the configurations file, it does it by the internal domain from the requirements file. And logs says the following:

![Screenshot 2021-07-01 at 18 04 10 (2)](https://user-images.githubusercontent.com/22666467/124261538-938c5b00-db39-11eb-8e66-db89ee657623.png)

As for me, it's not logical at all. Can you clarify this behavior for me, please? Is there an option to strictly looking for updates from the configuration's private register?

Thank you in advance,
Dmytro

**Comment by xlgmokha** [comment]
Thanks for the detailed write up.  

> Can you clarify this behavior for me, please?

Dependabot tries to default to using the package manager to perform the update where it can. We set up a transparent proxy that has limited access to credentials so that when the package manager makes an outbound network request to fetch the desired resource the proxy matches the host for the outbound request with one of the entries in the `registries` configuration section. The registries section doesn't control which host to connect to. It provides access to credentials so that the outbound network request can be made by the package manager etc.

> Is there an option to strictly looking for updates from the configuration's private register?

At the moment, you'll need to configure the package manager to connect to the same host that is defined in the `registries section`. i.e. add `--index-url` to `pip.conf` to control which host to connect to.

I hope this clears up some confusion. If the scenario that you described in the description is something that you would like us to support we could convert this issue into a feature request. WDYT?

**Comment by dmytrostriletskyi** [comment]
Hi, @xlgmokha,

I've done a workaround for my case.  

I've removed any mention of a host in the requirements file:

```
some-private-package==0.0.7
...
```

And exported environment variable `PIP_INDEX_URL` (basically, I do the following commands in Dockerfile):

```bash
$ export PIP_INDEX_URL=https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@nexus.internal.project.com/repository/pypi-all/simple
$ pip3 install -r /cooking-time-service/requirements.txt
```

With that, Dependabot cannot find a host from the requirement file and seems goes to the configuration's file and use the private register as a host.

Honestly, it would be great if I had a configuration in the configuration file where I just set `strictly use host from register` (or whatever it's called). 

Thank you for you fast response! <3

**Comment by xlgmokha** [comment]
Thanks for your patience. I'll bring this issue up for discussion at the next team meeting.

Happy hacking!

**Comment by xlgmokha** [comment]
Similar to: https://github.com/dependabot/dependabot-core/issues/3478.

**Comment by mpailloncy** [comment]
I'm facing a very similar issue but for NPM registry configuration. I'd like to use a different registry for Dependabot usage than the one specified in the _package-lock.json_ (or _yarn.lock_): having Dependabot using an external/public facing (with auth) registry, while keeping _package-lock.json_ using the internal registry (not public) by default.

AFAIK there is no way to workaround that at the moment for an NPM registry.

The _.npmrc_ file at repo level looks like that:

````
registry = https://nexus.internal.project.com/repository/npm
always-auth = true
_auth = ${AUTH_TOKEN}
````

With the _.github/dependabot.yaml_ looking like:

````
version: 2
registries:
  npm-registry-external:
    type: npm-registry
    url: https://nexus.external.project.com/repository/npm
    username: "${{secrets.EXT_REGISTRY_USERNAME}}"
    password: "${{secrets.EXT_REGISTRY_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
   ...
  registries:
  - npm-registry-external
````

However, the URL of each dependency in the _package-lock.json_ is taken instead of the registry specified in the _.github/dependabot.yaml_ file, causing Dependabot to fail as it can't access the internal registry. 

Any thoughts? Let me know if that's worth creating another issue or not - happy to raise it if needed - but the need seems to be close to this feature request
