### ISSUE TITLE
PRs not created for one private package but created for others

### ISSUE THREAD

**Issue by jdforsythe** [dependabot/dependabot-core#4038]
**Package ecosystem**

npm

**Package manager version**

**Language version**

**Manifest location and content prior to update**

**dependabot.yml content**

```yml
version: 2

registries:
  npm-private:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN }}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    registries:
      - npm-private
    allow:
      ## only allow dependabot to create PRs for third party production dependencies
      - dependency-type: production
      ## allow any @sensource dependency
      - dependency-type: all
        dependency-name: "@sensource/*"
    labels:
      - "🧰 type:chore"
      - "🤖 bot"
    commit-message:
      prefix: "🤖 📦 "
      prefix-development: "🤖 📦 [dev]"

  ## Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

**Updated dependency**

Private repo / npm package

**What you expected to see, versus what you actually saw**

We released two private npm modules 4 days ago. PRs came in for package 1 over the last 4 days (not all the next day, as we would expect with the "daily" configuration).

Package 2 never got any PRs in any of its dependent repos. Both packages are `@sensource/package-name`, all configuration is identical.

Some of the dependent repos had not checked for updates in several days:

![Screen Shot 2021-07-12 at 8 43 40 AM](https://user-images.githubusercontent.com/286972/125291696-ad732e00-e2ef-11eb-891f-d763cb5912f2.png)

but even the repos that had checked this morning still did not have PRs created.

I manually triggered an update check on the repos and still no PRs have been created. The logs seem to detect that there's a new version.

```txt
updater | INFO <job_170657191> Checking if @sensource/PACKAGE-TWO 0.3.1 needs updating
  proxy | 2021/07/12 12:44:16 [022] GET https://registry.yarnpkg.com:443/@sensource%2FPACKAGE-TWO
  proxy | 2021/07/12 12:44:16 [022] * authenticating npm registry request (host: registry.yarnpkg.com, token auth)
  proxy | 2021/07/12 12:44:16 [022] 200 https://registry.yarnpkg.com:443/@sensource%2FPACKAGE-TWO
  proxy | 2021/07/12 12:44:17 [024] GET https://registry.yarnpkg.com:443/@sensource%2FPACKAGE-TWO/0.3.3
  proxy | 2021/07/12 12:44:17 [024] * authenticating npm registry request (host: registry.yarnpkg.com, token auth)
  proxy | 2021/07/12 12:44:17 [024] 200 https://registry.yarnpkg.com:443/@sensource%2FPACKAGE-TWO/0.3.3
updater | INFO <job_170657191> Latest version is 0.3.3
  proxy | 2021/07/12 12:44:18 [026] GET https://registry.yarnpkg.com:443/@sensource%2fPACKAGE-TWO
  proxy | 2021/07/12 12:44:18 [026] * authenticating npm registry request (host: registry.yarnpkg.com, token auth)
  proxy | 2021/07/12 12:44:18 [026] 200 https://registry.yarnpkg.com:443/@sensource%2fPACKAGE-TWO
  proxy | 2021/07/12 12:44:18 [034] GET https://registry.yarnpkg.com:443/debug/-/debug-4.3.1.tgz
```
So it seems to determine that it needs an update from 0.3.1 to 0.3.3 but doesn't create the PR to do so. Again, we have this same configuration across all our repositories and this has worked mostly flawlessly, creating PRs for any new releases the next day in all dependent repositories. For some reason, this particular package release has not caused any PRs to be opened to update it on any of its 33 dependent repositories.

**Native package manager behavior**

Updating the package manually in one of the dependent repos works without any issues.

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**
