### ISSUE TITLE
Dependabot produces multiple PRs even though latest major version was ignored 

### ISSUE THREAD

**Issue by mcmxcdev** [dependabot/dependabot-core#4040]
**Package ecosystem**
npm
**Package manager version**
yarn v1
**Language version**
Node 14
**dependabot.yml content**
```yml version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: 'weekly'
    day: "monday"
    time: '08:00'
    timezone: 'Europe/Berlin'
  open-pull-requests-limit: 10
  target-branch: develop
  labels:
  - dependencies
  ignore:
  - dependency-name: '*'
    update-types: ['version-update:semver-minor', 'version-update:semver-patch']
  commit-message:
    prefix: chore
    include: scope
```

**Updated dependency**
`compression-webpack-plugin`

**What you expected to see, versus what you actually saw**

We received a dependabot PR `chore(deps-dev): bump compression-webpack-plugin from 3.1.0 to 6.1.1` which we closed manually since webpack upgrades are done by hand. 

Now after a while, we received a new dependabot PR `chore(deps-dev): bump compression-webpack-plugin from 3.1.0 to 5.0.2`

I am quite sure that there would be even another one coming to upgrade from v3 to v4, since that seems to be the faulty behavior.

In my opinion, the expected behavior should be that dependabot doesn't notify for of any major version OR lower that a PR was closed for, so the only time we should get a new PR would be `compression-webpack-plugin` v7 or higher.
