### ISSUE TITLE
Random 401 errors on `npm ci` in GitHub Actions

### ISSUE THREAD

**Issue by TheDutchCoder** [dependabot/dependabot-core#4041]
**Package ecosystem**
npm
**Package manager version**
npm 7
**Language version**
node 16
**dependabot.yml content**
```yml
version: 2
registries:
  github:
    type: "npm-registry"
    url: "https://npm.pkg.github.com"
    token: ${{ secrets.SEMANTIC_RELEASE }}
updates:
  # Enable version updates for npm in the chalk-icons folder.
  - package-ecosystem: "npm"
    directory: "./packages/chalk-icons"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "vite" # Pin Vite for now.
    reviewers:
      - "TheDutchCoder"

  # Enable version updates for npm in the chalk-ui folder.
  - package-ecosystem: "npm"
    directory: "./packages/chalk-ui"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "vite" # Pin Vite for now.
    reviewers:
      - "TheDutchCoder"

  # Enable version updates for npm in the workflow folder.
  - package-ecosystem: "npm"
    directory: "./workflow"
    registries: "*"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "vite" # Pin Vite for now.
    reviewers:
      - "TheDutchCoder"

  # Enable version updates for npm in the workflow folder.
  - package-ecosystem: "npm"
    directory: "./apps/proofflow"
    registries: "*"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "vite" # Pin Vite for now.
    reviewers:
      - "TheDutchCoder"
```
**Updated dependency**
N/A
**What you expected to see, versus what you actually saw**
`npm ci` errors with 401 randomly, sometimes multiple times in a row when re-running jobs, until it suddenly doesn't 401 and installs fine.
**Native package manager behavior**
N/A
**Images of the diff or a link to the PR, issue or logs**
```
-    "autoprefixer": "^10.2.6",
+   "autoprefixer": "^10.3.0",
```

This has happened very frequently for us the last few weeks and it seems to start showing up more and more. I sometimes have to re-run only once, and sometimes up to 10 times on order to get `npm ci` to work. Nothing changes in the mean time, it just seems to hit some bug somewhere.

We do use private repos in the projects where this seems to happen, so it might be related to that, because our other projects (without private repos) have never hit this issue as far as I can tell.

**Comment by TheDutchCoder** [comment]
I wonder if it's container or even timezone related or something?
Here's a view of what we see pretty much each morning:
![image](https://user-images.githubusercontent.com/1668207/125490614-163d41df-1aee-4ac7-913e-1aeeed099b00.png)

Note how everything in `/packages` works fine (no private repos to install from), but the other ones all fail.

They also kept failing on re-runs this morning.

However, when re-running them now (noon EST), they suddenly all start to pass.

**Comment by feelepxyz** [comment]
@TheDutchCoder it sounds like an issue with npm credentials and not dependabot unless the updated diff was somehow broken. It also doesn't sound an actions issue as the response is from the registry.

I would get in touch with npm support if you're using private npm packages or attempt to debug things on the registry side if you control it.

**Comment by TheDutchCoder** [comment]
I respectfully disagree :)

It's not an NPM registry (it's GH) and if it was an actual credential issue, it would never pass anyway.
Re-running the GH actions should have no impact whatsoever if it was an actual credentials issue. Nothing changes in between the runs, except for (what I can tell) the time of day.

**Comment by TheDutchCoder** [comment]
After some more digging, I'm finding the following difference after a rerun:

Failing run:
```
Run npm ci
  npm ci
  shell: /usr/bin/bash -e {0}
  env:
    NPM_TOKEN:
```

Successful run:
```
Run npm ci
  npm ci
  shell: /usr/bin/bash -e {0}
  env:
    NPM_TOKEN: ***
```

It looks like the token isn't correctly picked up when dependabot initiates the run?

Just to be clear: this all worked fine 2 weeks ago or so, we haven't changed our CI when it comes to dependabot.

**Comment by feelepxyz** [comment]
Oh yes you're right, pull requests created by dependabot are now treated like forks so only have read access and no secrets. There's a FAQ with recommendations here: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544

**Comment by TheDutchCoder** [comment]
Oh boy that explains at least part of it. It seems this change was done a while ago already even though it didn't seem to affect us (yet), but maybe they rolled it out in phases or something.

It's not great that this happens unannounced but at least I can now try to fix it.

I'll create a `pull_request_target` workflow and see if that fixes it. Thanks!

**Comment by feelepxyz** [comment]
@TheDutchCoder we'll publish any breaking changes and new features on the [GitHub Changelog](https://github.blog/changelog/).

**Comment by TheDutchCoder** [comment]
I'm still confused.

That issue mentions dependabot being used in pull request templates, but I'm talking about dependabot creating OR's itself to update dependencies. I see no mention of that and I'm unsure how to proceed.

Dependabot doesn't have its own workflow, only a config file (see original issue above).

**Comment by feelepxyz** [comment]
@TheDutchCoder this issue is for pull requests created by dependabot itself. If  have a actions workflow and this gets triggered on a pull request that dependabot opens, it won't have access to secrets by default (just like a fork), unless you use `pull_request_target` as the trigger and manually checkout the target pull  request:

```
### .github/workflows/dependabot_automerge.yml
### As of 2300 UTC on 11 March, this workflow has secrets and a read-write token
name: Dependabot Workflow
on:
  pull_request_target
  
permissions:
  # down scope as necessary via https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

> Edit: the docs also still tell me to do it the "old "way? (https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#registries)

This only applies to update run by dependabot, not any actions workflow runs. It's unfortunate that we can't share these secrets so you only need to set them up once. You'll only need to change the actions workflow if dependabot can successfully create the pull request.

**Comment by TheDutchCoder** [comment]
So I just need to add a workflow in order to expose the secret to dependabot?

Is there a reason why there's no reference at all to this in the docs? They still just say to add a dependabot.yml file with a secret in it, but if that secret never works it seems the docs are incorrect?

I will add the workflow and see if that gets rid of the issue, but it seems like this needs to be explicitly added to the documentation about private repos.

**Comment by feelepxyz** [comment]
> So I just need to add a workflow in order to expose the secret to dependabot?

No you shouldn't need to add any new workflows. I was under the impression the issue was with existing workflow/ci runs failing because they can't talk to npm? I think you just need to update these workflows that are running on dependabot pull requests.

**Comment by TheDutchCoder** [comment]
I'm so confused haha.

We only use dependabot to auto-update dependencies, that's it. That's also why we only have `dependabot.yml` which I pasted above.

Dependabot is configured to have access to our private packages (through GitHub packages) as instructed by the documentation.

This all worked up until ~2 weeks ago when it started randomly failing with 401's and (what looks like) missing tokens.

We don't have any workflows that use dependabot (but we do have a couple of workflows).

I'm just not clear on where to look for a fix.

**Comment by feelepxyz** [comment]
No worries, we felt this change was necessary to mitigate an attack vector that could affect a lot of users on github but has left the product a lot harder to set up with actions.

So going back to your screenshot here: https://github.com/dependabot/dependabot-core/issues/4041#issuecomment-879235162

It looks like dependabot itself is configured correctly and working fine (as you're receiving pull requests), so we can probably leave out any changes to `dependaboy.yml`. From the screenshot it looks like the thing that is failing is one of these workflows you mention? Is this the issue you're seeing? e.g. you test ci workflow that runs on all new pull requests?

If this is the case, you should only need to modify the workflow file that's failing. It will be workflows that are triggered on `pull_request` or `push`, and might look something like this:

```
name: Existing workflow
on:
  pull_request

jobs:
  existing-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      ...
```

You'll need to update your workflows that run on `push` or `pull_request` to run on `pull_request_target` instead and specify which ref to checkout, something like this:

```
name: Existing workflow
on:
  pull_request_target

jobs:
  existing-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by TheDutchCoder** [comment]
Okay thanks, let me go through our other workflows to see which ones fail and make adjustments there.

I'll let you know if it solves the issue (might take a day or two)

**Comment by TheDutchCoder** [comment]
Update: with this config, dependabot seems to be able to get the secret again.
Just waiting for you to confirm if I still need the NPM_TOKEN or not, then I'll close this issue.

Can I suggest adding this to the documentation for private repos as well?

**Comment by feelepxyz** [comment]
@TheDutchCoder you'll need `NPM_TOKEN` if this is required to run `npm ci`, this is independent of dependabot so should be whatever you need to run this locally. 

> ```yaml
>       - uses: actions/checkout@v2 # Do I add the ref/github-token here?
>         with:
>           ref: ${{ github.event.pull_request.head.sha }}
>           github-token: ${{ secrets.DEPENDABOT }}
> ```

I see now that the key is wrong, you might need to give this the GITHUB_TOKEN to allow it to pull the repo (this is from actions):

```yaml
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
