### ISSUE TITLE
Unable to authenticate against private azure artifacts npm registry

### ISSUE THREAD

**Issue by marcuslindfeldt** [dependabot/dependabot-core#4049]
**Package ecosystem**
npm
**dependabot.yml content**
```
version: 2
registries:
  azure-registry:
    type: npm-registry
    url: https://pkgs.dev.azure.com/<org>/_packaging/<feed>/npm/registry/
    username: <username>
    password: ${{secrets.AZURE_EXT_PAT_BASE64}}

updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Allow up to 10 open pull requests at a time
    open-pull-requests-limit: 10
    registries:
      - azure-registry
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
```
**What you expected to see, versus what you actually saw**
Dependabot should resolve dependencies but is unable to authenticate against the registry and throws the error `private_source_authentication_failure`. Azure artifacts does not use npm tokens but a username and password solution instead. 

This is the official way of connecting to a private Azure artifacts npm registry via `.npmrc`:
```
; .npmrc
registry=https://pkgs.dev.azure.com/<org>/_packaging/<feed>/npm/registry/ 
                        
always-auth=true

; begin auth token
//pkgs.dev.azure.com/<org>/_packaging/<feed>/npm/registry/:username=<username>
//pkgs.dev.azure.com/<org>/_packaging/<feed>/npm/registry/:_password=[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]
//pkgs.dev.azure.com/<org>/_packaging/<feed>/npm/registry/:email=npm requires email to be set but doesn't use the value
//pkgs.dev.azure.com/<org>/_packaging/<feed>/npm/:username=<username>
//pkgs.dev.azure.com/<org>/_packaging/<feed>/npm/:_password=[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]
//pkgs.dev.azure.com/<org>/_packaging/<feed>/npm/:email=npm requires email to be set but doesn't use the value
; end auth token
```
**Native package manager behavior**
It manages to authenticate properly from credentials in .npmrc
