### ISSUE TITLE
Dependabot not fixing conflicts by itself

### ISSUE THREAD

**Issue by hodgef** [dependabot/dependabot-core#4109]
Dependabot is not always triggering rebases for conflicted PRs since the migration to from Preview to Native. Before the migration, PR conflicts triggered an immediate rebase.

Repro PR: https://github.com/hodgef/js-library-boilerplate/pull/1233
![image](https://user-images.githubusercontent.com/25509135/127978549-06b30e3a-eb16-41e7-be20-5ff8f4cb9cfd.png)

Configuration
```
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Montreal
  open-pull-requests-limit: 10
  versioning-strategy: increase
```
