### ISSUE TITLE
Update correctly go.sum in case of several modules in the same project with references between them

### ISSUE THREAD

**Issue by mmorel-35** [dependabot/dependabot-core#4124]
**Package ecosystem**
gomod
**Package manager version**

**Language version**

**Manifest location and content prior to update**
`/go.mod` (module gocloud.dev)
`/pubsub/kafkapubsub/go.mod`(module gocloud.dev/pubsub/kafkapubsub) contains
```
replace gocloud.dev => ../../
```

**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /pubsub/kafkapubsub
    schedule:
      interval: weekly
```

**Updated dependency**
github.com/aws/aws-sdk-go@v1.40.16

**What you expected to see, versus what you actually saw**
```
******************************
* Running Go tests for module: pubsub/kafkapubsub
******************************
go: gocloud.dev@v0.23.0 requires
	github.com/aws/aws-sdk-go@v1.40.16: missing go.sum entry; to add it:
	go mod download github.com/aws/aws-sdk-go
```

I would like to see the go.sum updated appropriately when there are references between several modules in the same project.
**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**
