### ISSUE TITLE
Dependabot PR updating 2 dependencies. Is it OK?

### ISSUE THREAD

**Issue by alexandrusavin** [dependabot/dependabot-core#4163]
My understanding is that dependabot should create a PR per dependency update. I've attached here a screenshot showing dependabot trying to update 2 dependencies but only mentions one in the PR description. Is this expected behaviour from dependabot? Should it update multiple dependencies in one PR?

**Package ecosystem**
npm

**Package manager version**
npm 6.14.14

**Language version**
node 14

**Manifest location and content prior to update**
package.json

**dependabot.yml content**

```yml
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

```

**Updated dependency**
`mocha` from 8.4.0 to 9.0.3
`serverless-offline` form 6.9.0 to 8.0.0

**What you expected to see, versus what you actually saw**
Dependabot should only update `serverless-offline`.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/1612455/130213056-a3a14256-91d3-4943-9d4d-702f3287a324.png)

![image](https://user-images.githubusercontent.com/1612455/130214905-cbcf1fd4-3857-4c68-be23-7ae234f3ac47.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**

I'm not sure how to reproduce this issue.
