### ISSUE TITLE
Terraform module versions with 'v' prefix

### ISSUE THREAD

**Issue by declan-fitzpatrick** [dependabot/dependabot-core#4181]
**Package ecosystem**
terraform

**Language version**
Terraform v1.0.5

**dependabot.yml content**

```yaml
version: 2
registries:
  terraform-cloud:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${{secrets.TERRAFORM_API_TOKEN}}

updates:
  - package-ecosystem: "terraform"
    registries:
      - terraform-cloud
    directory: "/"
    target-branch: "release"
    labels:
      - "terraform"
    schedule:
      interval: "daily"

```
**Description**

Terraform registry allows for semantic version, which can [optionally be prefixed with a `v`](https://www.terraform.io/docs/registry/modules/publish.html#requirements). 
Dependabot throws a `BadRequirementError` when module versions are prefixed with a `v`. The full error: 

**Steps to reproduce**
1. set requirement_string to v1.0.0 in `terraform/spec/dependabot/terraform/requirement_spec.rb` 
2. run `bundle exec rspec spec`
output looks like: 
```shell
Randomized with seed 59800
....................................................F........................................................................................................................

Failures:

  1) Dependabot::Terraform::Requirement.new 
     Failure/Error: raise BadRequirementError, msg
     
     Gem::Requirement::BadRequirementError:
       Illformed requirement ["v1.0.0"]
     # ./lib/dependabot/terraform/requirement.rb:15:in `parse'
     # ./lib/dependabot/terraform/requirement.rb:37:in `initialize'
     # ./spec/dependabot/terraform/requirement_spec.rb:7:in `new'
     # ./spec/dependabot/terraform/requirement_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./spec/dependabot/terraform/requirement_spec.rb:11:in `block (3 levels) in <top (required)>'
     # /home/declan/Documents/repo/projects/dependabot-core/common/spec/spec_helper.rb:49:in `block (2 levels) in <top (required)>'
     # /var/lib/gems/2.7.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 32.72 seconds (files took 0.56344 seconds to load)
173 examples, 1 failure

Failed examples:

rspec ./spec/dependabot/terraform/requirement_spec.rb:11 # Dependabot::Terraform::Requirement.new 

Randomized with seed 59800
```
