### ISSUE TITLE
PR incorrectly links to dependency from public registry, when it has the same name as one from a private registry

### ISSUE THREAD

**Issue by efung** [dependabot/dependabot-core#4197]
**Package ecosystem**
pip
**Package manager version**
pip 21.0.1
**Language version**
Python 3.8.4
**Manifest location and content prior to update**
`/requirements.txt`
**dependabot.yml content**
Redacted contents below:

<details>

```
version: 2
registries:
  python-private:
    type: python-index
    url: https://pkgs.example.com/basic/data/python/simple
    username: "token"
    password: ${{secrets.PYTHON_CLOUDSMITH_TOKEN}}
  github-com:
    type: git
    url: https://github.com
    username: ${{secrets.DEPENDENCIES_GITHUB_USER}}
    password: ${{secrets.DEPENDENCIES_GITHUB_TOKEN}}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    insecure-external-code-execution: allow
    registries: "*"
```

</details>

**Updated dependency**
Public dependency is https://github.com/micolous/monorail

**What you expected to see, versus what you actually saw**
In one of our private repositories, we have a dependency on a Python package named `monorail`, which is available from our private Python registry.

In the automated Dependabot PRs, the links included to the dependency are for a completely unrelated open-source package. 

The version numbers are correct, matching our private registry's dependency version numbers. But the links are going to some other dependency, with the same name.

**Native package manager behavior**
N/A
**Images of the diff or a link to the PR, issue or logs**

> Bumps [monorail](https://github.com/micolous/monorail) from 1.2.300.1234 to 1.2.300.2345.
> <details>
> <summary>Commits</summary>
> <ul>
> <li>See full diff in <a href="https://github.com/micolous/monorail/commits">compare view</a></li>
> </ul>
> </details>
