### ISSUE TITLE
`automerge` label is not being added to PRs

### ISSUE THREAD

**Issue by Maxim-Mazurok** [dependabot/dependabot-core#4217]
**dependabot.yml content**
```yaml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '10:00'
      timezone: 'Australia/Sydney'
    labels:
      - 'dependencies'
      - 'automerge'
```
**What you expected to see, versus what you actually saw**
I expected dependabot to open PR with `automerge` label, as per config
**Images of the diff or a link to the PR, issue or logs**
https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/551 (had to add automerge label manually)
