### ISSUE TITLE
Dependabot not respecting private registry config

### ISSUE THREAD

**Issue by dermyhughes** [dependabot/dependabot-core#4275]
**Package ecosystem**
npm

**dependabot.yml content**
```
version: 2
registries:
  my-nexus-registry:
    type: npm-registry
    url: https://[url-to-nexus-registry]
    username: ${{secrets.PRIVATE_REPOSITORY_USERNAME}}
    password: ${{secrets.PRIVATE_REPOSITORY_PASSWORD}}
updates:
  - package-ecosystem: npm
    directory: '/'
    registries:
      - my-nexus-registry
    schedule:
      interval: daily
      time: '02:00'
    open-pull-requests-limit: 10
    target-branch: develop
```

**What you expected to see, versus what you actually saw**
I expect Dependabot to update dependancies using the private registry as set in the dependabot.yml file, but Dependabot continues to use the public npm registry (https://registry.npmjs.org) for public packages.
Dependabot _will_ use the private registry for private packages which are only available on the private Nexus registry but I want Dependabot to use that registry for _all_ packages.
