### ISSUE TITLE
Dependabot and Gradle - Ignore dependencies using version 'latest.release'

### ISSUE THREAD

**Issue by JeremyTwiggs** [dependabot/dependabot-core#4276]
**Package ecosystem**
  gradle
**Package manager version**
  Maven Nexus Repository
**Language version**
  Java 11
**Manifest location and content prior to update**
  n/a
**dependabot.yml content**
```
version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    # Look for `build.gradle` in the `root` directory
    directory: "/"
    # Check for updates once daily
    schedule:
      interval: "daily"
```
**Updated dependency**
  org.owasp.dependencycheck from latest.release to 6.3.2.
**What you expected to see, versus what you actually saw**
  I'd expect dependabot to skip/ignore dependencies using version of 'latest.release'
  If there's a config work around, great, but I have quite a few "reporting" plugins, that have no impact on the deliverable, where I always want (my CD pipeline) to use the latest version, so it would, I feel, be nicer if that was the default behaviour.
**Native package manager behavior**
  n/a
**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/14995082/135623568-6752079e-7216-4eba-88b0-28b36ab45ef6.png)
**🕹 Bonus points: Smallest manifest that reproduces the issue**
