### ISSUE TITLE
List trusted workflows initialised by dependabot in PR checks

### ISSUE THREAD

**Issue by ashlinchak** [dependabot/dependabot-core#4305]
In our organisation, we're using environment variables for accessing private packages and make Docker container builds as a part of CI checks. According to the latest changes with decreasing level of accessibility for dependabot now it's not possible to build the right workflow for PRs which are created by dependabot.

With the newest changes, dependabot can't get secrets on `push` and `pull_request` events, which we're using for our CI checks. According to [this](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#handling-push-events) documentation, we're forced to create 2 workflows, e.g.:

```yml
name: Dependabot Push Check
on:
  push:
jobs:
  check_dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "Push initiated by Dependabot"
```
```yml
name: Dependabot Trusted Workflow
on:
  workflow_run:
    workflows:
      - Dependabot Push Check
    types:
      - completed
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: npm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
When depenedabot creates its PR, it'll have only 1 check in it:
<img width="916" alt="Screenshot 2021-10-11 at 14 26 01" src="https://user-images.githubusercontent.com/3256846/136782554-f356ec80-3359-435f-8b3a-2c3dd7db0cac.png">

`Dependabot Push Check` workflow triggers `Dependabot Trusted Workflow` but the last one is not part of CI checks for the PR.  

Could we implement the feature where we could specify that the workflow is a part of PR checks? 

Also, in our case, we need to have  `Dependabot Trusted Workflow` workflow to be part of checks for PRs initialized not only dependabot but regular developers.
