### ISSUE TITLE
Superseded pull requests which were assigned a reviewer from a team end up with multiple reviewers from that team

### ISSUE THREAD

**Issue by chrisfosterelli** [dependabot/dependabot-core#4363]
**Package ecosystem**
npm
**Package manager version**
N/A (multiple repositories with multiple versions)
**Language version**
N/A (multiple repositories with multiple versions)
**Manifest location and content prior to update**
`./package.json`
**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
      timezone: America/Vancouver
    open-pull-requests-limit: 10
    reviewers: 
      - '@TwoStoryRobot/<snip>'
```
**Updated dependency**
N/A
**What you expected to see, versus what you actually saw**
When a dependabot PR is automatically assigned a reviewer from a team, and then that PR is superseded by another PR, I expect the new PR to have the same reviewer assigned.

What I actually see is that dependabot assigns two reviewers to the new PR: one from the prior PR and another randomly selected from the team.
**Native package manager behavior**
N/A
**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/2072672/139947094-a260253a-61c5-4713-ad33-06bc98bbc37e.png)
