### ISSUE TITLE
NPM updates aren't creating new project-lock as expected

### ISSUE THREAD

**Issue by babyhuey** [dependabot/dependabot-core#4370]
We are using dependabot on Gitlab. 

In the past, when we do npm updates on our private repo, the "from" section had the version number. When using dependabot, it now has the sha for both the "version" and the "from" section.

**Package ecosystem**
npm

**Package manager version**
npm 7

**Language version**
Node 14.x

**Dependabot version** 
We are on dependabot-gitlab, and I'm pretty sure we're on v0.162.2

**dependabot.yml content**
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: all
    open-pull-requests-limit: 100
```

Screenshot showing what dependabot MR looks like
![image](https://user-images.githubusercontent.com/7751607/140220894-a791399e-56a3-499d-a803-ffcc98e310cd.png)

Screenshot showing what it looks like after doing a local `npm update`
![image](https://user-images.githubusercontent.com/7751607/140221068-9d87d57b-bfde-4b13-8f89-7fe45079069a.png)
