### ISSUE TITLE
Documentation should clarify semver ignore behavior for non-SemVer versions

### ISSUE THREAD

**Issue by akomakom** [dependabot/dependabot-core#4386]
Current documentation does not describe dependabot update behavior in the following situations:

1. Ignore set to `update-types: ["version-update:semver-major"]` with a version like `1.2` or `1.2.3.4`.  
2. Same with an update between SemVer and not, eg `1.2->1.2.3` or `1.2.3->1.3`

In the above situations I can reasonably expect that dependabot will either:

1. Treat `1` as  **major** in `1.2` and ignore major updates on a 2-digit version.  
2. Treat `1` as **major** in `1.2.3` but not in `1.2` and thus ignore only one of these updates: `1.2->1.2.3`, `1.2.3->1.3` (I have no idea which)
3. Not honor the ignore instruction at all for any non-SemVer versions and process updates regardless of ignore configuration.

In a similar vein, what is the expected behavior for processing semver instructions on completely non-semver versions?  
* 1.2-monkey3
* 1234
* 1-SOME-WORD

**Comment by PerchunPak** [comment]
This could be done by adding `update-types` in `allow`, so users will convert

```yaml
  ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-patch" ]
```
to
```yaml
  allow:
    - dependency-name: "*"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    - dependency-name: "non-semver-dep"
```
