### ISSUE TITLE
Transitive requirement missed and even removed from existing lock file

### ISSUE THREAD

**Issue by tuky** [dependabot/dependabot-core#4390]
**Package ecosystem**
python 3 with pipenv
**Package manager version**
pipenv, version 2021.11.5.post0
**Language version**
Python 3.8.10
**Manifest location and content prior to update**
/Pipfile and /Pipfile.lock
**dependabot.yml content**

```yml
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "04:00"
  open-pull-requests-limit: 8
  allow:
  - dependency-type: direct
  - dependency-type: indirect
```

**Updated dependency**
`celery = {extras = ["sqs", "s3"],version = "*"}`
**What you expected to see, versus what you actually saw**
`celery` with `sqs` depends on `kombu` (https://github.com/celery/celery/blob/master/requirements/extras/sqs.txt) which again depends on `pycurl` (https://github.com/celery/kombu/blob/master/requirements/extras/sqs.txt) so `pycurl` should not be removed from `Pipfile.lock` when creating any update PR, e.g. for `boto3`.
**Native package manager behavior**
it correctly detects and locks the transitive dependency:

```
        "pycurl": {
            "hashes": [
                "sha256:5bcef4d988b74b99653602101e17d8401338d596b9234d263c728a0c3df003e8"
            ],
            "version": "==7.44.1"
        },
```

**Images of the diff or a link to the PR, issue or logs**

![scrnli_9-11-2021_10-43-49](https://user-images.githubusercontent.com/2981274/140900653-9a21a7bf-1adb-47ce-a73e-53637014f2c0.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**
should be
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
boto3 = "*"
celery = {extras = ["sqs", "s3"],version = "*"}

[requires]
python_version = "3.8"
```
