### ISSUE TITLE
Dependabot to target only given dependency or dependencies

### ISSUE THREAD

**Issue by nisevi** [dependabot/dependabot-core#4404]
Instead of configuring which dependencies I want to ignore, I would like configure which dependencies I want the bot to target as the only dependencies the bot should focus on:

```yml
# dependabot.yml file with updates
# disabled for Docker and limited for npm

version: 2
updates:
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore updates to packages that start with 'aws'
      # Wildcards match zero or more arbitrary characters
      - dependency-name: "aws*"
      # Ignore some updates to the 'express' package
      - dependency-name: "express"
        # Ignore only new versions for 4.x and 5.x
        versions: ["4.x", "5.x"]
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
```

So, instead of having that, I would like to have something like:

```yml
# dependabot.yml file with updates
# disabled for Docker and limited for npm

version: 2
updates:
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target:
      - dependency-name: "react"
```

My apologies if this is a duplicated request, I haven't been able to find a feature request like this one 🤖
