### ISSUE TITLE
Poetry cannot use file based dependency in repo, fails with file does not exist

### ISSUE THREAD

**Issue by phillipuniverse** [dependabot/dependabot-core#4456]
File-based dependencies (.tar.gz, .whl) do not seem to work with Poetry. If I extract it and point to the dependency as a directory, that works ok. This also only appears to error out when a dependency needs to update.

Demo project at https://github.com/phillipuniverse/dependabot-patherror/ with various attempts to fix.

**Package ecosystem**
pip (poetry)

**Package manager version**
1.1.11

**Language version**
3.8.7
**Manifest location and content prior to update**

`pyproject.toml` contents:

```toml
[tool.poetry]
name = "dependabot-patherror"
version = "0.1.0"
description = ""
authors = ["Phillip Verheyden <pverheyden@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
routing = { file = "./routing-8.22.2.tar.gz" }
geocoding = { file = "./geocoding-7.74.tar.gz" }
psycopg2-binary = "2.8.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
**dependabot.yml content**

Using GitHub dependabot:

```
version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: daily
```

**Updated dependency**
N/A

**What you expected to see, versus what you actually saw**

I expected a new PR to be opened to recommend an update to FastAPI. Instead, I got an error.

**Native package manager behavior**

.tar.gz file dependency resolved fine

Logs from Dependabot:

```
updater | ERROR <job_236977012> Error processing psycopg2-binary (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_236977012> ValueError
updater | <job_236977012> 
updater | <job_236977012>   File geocoding-7.74.tar.gz does not exist
updater | <job_236977012> 
updater | <job_236977012>   at /usr/local/.pyenv/versions/3.8.7/lib/python3.8/site-packages/poetry/core/packages/file_dependency.py:40 in __init__
updater | <job_236977012>        36│             except FileNotFoundError:
updater | <job_236977012>        37│                 raise ValueError("Directory {} does not exist".format(self._path))
updater | <job_236977012>        38│ 
updater | <job_236977012>        39│         if not self._full_path.exists():
updater | <job_236977012>     →  40│             raise ValueError("File {} does not exist".format(self._path))
updater | <job_236977012>        41│ 
updater | <job_236977012>        42│         if self._full_path.is_dir():
updater | <job_236977012>        43│             raise ValueError("{} is a directory, expected a file".format(self._path))
updater | <job_236977012>        44│
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:324:in `run_poetry_command'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:89:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/shared_helpers.rb:164:in `with_git_configured'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:77:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/shared_helpers.rb:48:in `block in in_a_temporary_directory'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/shared_helpers.rb:48:in `chdir'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/shared_helpers.rb:48:in `in_a_temporary_directory'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:76:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:49:in `latest_resolvable_version'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.0/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/update_checkers/base.rb:257:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:431:in `requirements_to_unlock'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:226:in `check_and_create_pull_request'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_236977012> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_236977012> bin/update_files.rb:22:in `<main>'
```

**Comment by phillipuniverse** [comment]
If you modify the above `pyproject.toml` to use `path = ` instead of `file = ` then dependabot will check for updates correctly:

```toml
[tool.poetry]
name = "dependabot-patherror"
version = "0.1.0"
description = ""
authors = ["Phillip Verheyden <pverheyden@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
routing = { path = "./routing-8.22.2.tar.gz" }
geocoding = { path = "./geocoding-7.74.tar.gz" }
psycopg2-binary = "2.8.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
