### ISSUE TITLE
Considering main branch as a default one for bundler

### ISSUE THREAD

**Issue by CrazyPit** [dependabot/dependabot-core#4459]
**Package ecosystem**

Bundler.

**Package manager version**
2.2.29

**Language version**
Ruby 3.0.2

**Dependabot config**

```yaml
version: 2
registries:
  toptal-github:
    type: "git"
    url: "https://github.com"
    username: "x-access-token"
    password: "${{ secret }}"
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - toptal-github
    schedule:
      interval: "daily"
    labels:
      - "no-jira"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "no-jira"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "no-jira"
```

**Updated dependency**
yard

`gem 'yard', github: 'lsegal/yard'`

**What you expected to see, versus what you actually saw**

I'm getting this message: 
<img width="926" alt="Screenshot 2021-11-24 at 15 01 04" src="https://user-images.githubusercontent.com/2117/143579631-432d1601-2b21-47d4-88a2-f1f4086ee4a5.png">

The issue is that yard is using `main` branch instead of `master` and dependbot is not considering main branch as default. 
I've fixed it by adding `branch: 'main'`. But I think that since main is a default branch name better to update dependabot.
