### ISSUE TITLE
Docker image can't be used to run a dependabot script

### ISSUE THREAD

**Issue by TabithaLarkin** [dependabot/dependabot-core#4469]
When running dependabot in our Azure Dev Ops repository we have previously used the supplied dependabot docker image to run our custom scripts in.

```yml
  - job: RunDependabot
    # This version corresponds to the version in the Gemfile
    container: "dependabot/dependabot-core:0.169.1"
    variables:
      - group: dependabot
    steps:
      - script: |
          unset BUNDLE_PATH
          unset BUNDLE_BIN
          bundle install --retry=3 --jobs=4 --path vendor
        displayName: "Install Ruby Dependencies"
        workingDirectory: $(Build.SourcesDirectory)/dependabot

      - script: |
          bundle exec ruby ./update.rb
        env:
          AZURE_AUTH_TOKEN: $(DependabotPAT)
          GIT_AUTH_TOKEN: $(GitAuthToken)
        displayName: "Update dependencies"
        workingDirectory: $(Build.SourcesDirectory)/dependabot
```

The above code does not work however, the last container that I could get to work is `dependabot/dependabot-core:0.138.0`.

It reports the following output instead:
```
Digest: sha256:ab9e915bb428e911013da552a02d5be794e0d15cae6ec5207442de8c0d636d36
Status: Downloaded newer image for dependabot/dependabot-core:0.169.1
docker.io/dependabot/dependabot-core:0.169.1
/usr/bin/docker info -f "{{range .Plugins.Network}}{{println .}}{{end}}"
bridge
host
ipvlan
macvlan
null
overlay
/usr/bin/docker network create --label 90e8b1 vsts_network_f5051b3b058b4ad181e2c69f6f445c58
2907818d858ec6e442d8c28d847440eae564a419847323df7c9cab6cf9442da1
/usr/bin/docker inspect --format="{{index .Config.Labels \"com.azure.dev.pipelines.agent.handler.node.path\"}}" dependabot/dependabot-core:0.169.1
/usr/bin/docker create --name e049359bde694437b4488713c19d6889_dependabotdependabotcore01691_418d6a --label 90e8b1 --network vsts_network_f5051b3b058b4ad181e2c69f6f445c58  -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/agents/2.195.1/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" dependabot/dependabot-core:0.169.1 "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
87c097a0fdbcbec1c672968b776cc445d892e58baab5ef44daf4fedde4b9310d
/usr/bin/docker start 87c097a0fdbcbec1c672968b776cc445d892e58baab5ef44daf4fedde4b9310d
87c097a0fdbcbec1c672968b776cc445d892e58baab5ef44daf4fedde4b9310d
/usr/bin/docker ps --all --filter id=87c097a0fdbcbec1c672968b776cc445d892e58baab5ef44daf4fedde4b9310d --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
87c097a0fdbcbec1c672968b776cc445d892e58baab5ef44daf4fedde4b9310d Up Less than a second
/usr/bin/docker exec  87c097a0fdbcbec1c672968b776cc445d892e58baab5ef44daf4fedde4b9310d sh -c "command -v bash"
/bin/bash
whoami 
vsts
id -u vsts
1001
Try to create a user with UID '1001' inside the container.
/usr/bin/docker exec  87c097a0fdbcbec1c672968b776cc445d892e58baab5ef44daf4fedde4b9310d bash -c "getent passwd 1001 | cut -d: -f1 "
/usr/bin/docker exec  87c097a0fdbcbec1c672968b776cc445d892e58baab5ef44daf4fedde4b9310d useradd -m -u 1001 vsts_azpcontainer
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
```

I believe that this is because it can't create the user that is used to execute the tasks in the pipeline.

Is there a way of configuring the docker image such that this functionality is available again? It is unfortunately a blocker for us updating dependabot at all.
