### ISSUE TITLE
dependabot doesn't update quay images

### ISSUE THREAD

**Issue by georgettica** [dependabot/dependabot-core#4500]
**Package ecosystem**
docker

**Package manager version**
brew (but is irrelevant)

**Language version**
Irrelevant

**Manifest location and content prior to update**
Irrelevant

**dependabot.yml content**
```
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
//- directory: "/"
//  labels:
//  - "dependency"
//  package-ecosystem: "github-actions"
//  schedule:
//    interval: "daily"
- directory: "/"
  labels:
  - "dependency"
  package-ecosystem: "docker"
  schedule:
    interval: "daily"
```

**Updated dependency**
Irrelevant

**What you expected to see, versus what you actually saw**
I expect that quay.io version updates will create a PR that will bump the version

**Native package manager behavior**
Irrelevant

**Images of the diff or a link to the PR, issue or logs**
no link to PR because none were made

**🕹 Bonus points: Smallest manifest that reproduces the issue**
```
# Dockerfile
FROM: quay.io/app-sre/ubi8-ubi-minimal:8.3-201
# it should update to 8.5-204 at the least
```

```
# dependabot file
version: 2
updates:
- directory: "/"
  labels:
  - "dependency"
  package-ecosystem: "docker"
  schedule:
    interval: "daily"
```
