### ISSUE TITLE
Unable to authenticate to private repository using token option

### ISSUE THREAD

**Issue by vtertre** [dependabot/dependabot-core#4502]
When running dependabot on a private npm registry, we are unable to authenticate to the registry using the `token` option.
However, the run completes if we provide a `.npmrc` file configured with the same token.

```yml
version: 2
registries:
  verdaccio:
    type: npm-registry
    url: http://11.111.111.111:1111
    token: ${{secrets.VERDACCIO_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - verdaccio
    schedule:
      interval: 'monthly'
```

The secret `VERDACCIO_TOKEN` is stored in dependabot secrets.
The above `dependabot.yml` file cannot authenticate the private registry and errors with the following output:
```
updater | I, [2021-12-08T15:12:54.724437 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.5-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_241298830> Starting job processing
updater | INFO <job_241298830> Starting update job for vtertre/apps-dependabot
updater | INFO <job_241298830> Checking if rxjs 6.6.7 needs updating
  proxy | 2021/12/08 15:12:57 [015] GET http://11.111.111.111:1111/rxjs
  proxy | 2021/12/08 15:12:57 [015] 401 http://11.111.111.111:1111/rxjs
updater | INFO <job_241298830> Handled error whilst updating rxjs: private_source_authentication_failure {:source=>"11.111.111.111:1111"}
updater | INFO <job_241298830> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2021-12-08T15:12:58Z" level=info msg="task complete" container_id=job-241298830-updater exit_code=0 job_id=241298830 step=updater
```

If we add the following `.npmrc` file to the repository, dependabot run ends successfully.

```
registry=http://11.111.111.111:1111/
//11.111.111.111:1111/:_authToken=<same string contained in secrets.VERDACCIO_TOKEN>
//11.111.111.111:1111/:always-auth=true
```

**Comment by hfhbd** [comment]
Do you use a private group GitLab npm registry?
If so, try adding two registries:
```
verdaccio:
    type: npm-registry
    url: gitlab.example/api/v4/packages/npm/
    token: ${{secrets.VERDACCIO_TOKEN}}
vErdaccio-group:
    type: npm-registry
    url: gitlab.example.com/api/v4/projects/ID/packages/npm/
    token: ${{secrets.VERDACCIO_TOKEN}}
```
At least this workaround is needed in dependabot-script
```
credentials << {
    "type" => "npm_registry",
    "registry" => "gitlab.example.com/api/v4/packages/npm/",
    "token" => ENV["GITLAB_ACCESS_TOKEN"]
  }

credentials << {
    "type" => "npm_registry",
    "registry" => "gitlab.example.com/api/v4/projects/ID/packages/npm/",
    "token" => ENV["GITLAB_ACCESS_TOKEN"]
  }
```

**Comment by andrcuns** [comment]
I think the github native version might be handling that when parsing the config file, but what I found out recently, core doesn't handle private registry credentials correctly if a registry has protocol.

What ends up happening, [here](https://github.com/dependabot/dependabot-core/blob/2313fbda8d5e57788d4ff79868634bc8a72f1436/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L57) a request will be made to url like `https://https://registry` and [registry_url](https://github.com/dependabot/dependabot-core/blob/2313fbda8d5e57788d4ff79868634bc8a72f1436/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L74) method will also return a malformed url

I don't think it is this case though.

**Comment by jurre** [comment]
@vtertre we recently fixed an issue with Dependabot org secrets not being handled correctly, could that have caused this? Have things started working for you a couple of days ago by any chance?

**Comment by vtertre** [comment]
@hfhbd we don't use a private group GitLab npm registry.

@jurre I'm testing with a Dependabot repository secret. Gave it another try today and we still have the same issue.

**Comment by mctofu** [comment]
@vtertre: Are you using an encoded version of the token in Dependabot secrets? The `.npmrc` usually has a base64 encoded version of the token but Dependabot expects an unencoded token: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#npm-registry

**Comment by vtertre** [comment]
@mctofu I think it's for passwords not tokens? Anyway I noticed this section of the doc before and had a look at it just to be sure. The value we use in Dependabot secrets is the token, not an encoded version of the token.

**Comment by mctofu** [comment]
@vtertre: I took a closer look and it appears that the issue is that Dependabot will not apply credentials over plaintext `http` requests. Is it possible to use `https` with your registry?

**Comment by SubatomicHero** [comment]
Hooking onto this. Does anyone have a working example of connecting to Artifactory and the parameters needed for both npm and java repos? No matter what I do I cannot seem to connect my self hosted Gitlab to our self hosted Artifactory

**Comment by okanthony** [comment]
> I think the github native version might be handling that when parsing the config file, but what I found out recently, core doesn't handle private registry credentials correctly if a registry has protocol.
> 
> What ends up happening, [here](https://github.com/dependabot/dependabot-core/blob/2313fbda8d5e57788d4ff79868634bc8a72f1436/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L57) a request will be made to url like `https://https://registry` and [registry_url](https://github.com/dependabot/dependabot-core/blob/2313fbda8d5e57788d4ff79868634bc8a72f1436/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L74) method will also return a malformed url
> 
> I don't think it is this case though.


Can confirm that removing the protocol from `url` fixed the issue authenticating to the registry using `token`

**Comment by jorgebv** [comment]
> > I think the github native version might be handling that when parsing the config file, but what I found out recently, core doesn't handle private registry credentials correctly if a registry has protocol.
> > What ends up happening, [here](https://github.com/dependabot/dependabot-core/blob/2313fbda8d5e57788d4ff79868634bc8a72f1436/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L57) a request will be made to url like `https://https://registry` and [registry_url](https://github.com/dependabot/dependabot-core/blob/2313fbda8d5e57788d4ff79868634bc8a72f1436/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L74) method will also return a malformed url
> > I don't think it is this case though.
> 
> Can confirm that removing the protocol from `url` fixed the issue authenticating to the registry using `token`

this also worked for me

**Comment by unicornware** [comment]
in my case, the error wasn't including a protocol in `url`. it was not including my organization name in my url.

instead of `https://npm.pkg.github.com`, i needed to use `https://npm.pkg.github.com/<org-name>`:

```yaml
registries:
  github:
    replaces-base: true
    token: ${{ secrets.PAT_BOT }}
    type: npm-registry
    url: https://npm.pkg.github.com/flex-development
```

i'm not sure if this articulated in the github docs, however.

i happened to find an example under [`registries`][1] in [Configuration options for the dependabot.yml file][2] (after missing it several times 😅). i was expecting to find something under [`npm-registry`][3], similar to the note about dependabot not setting environment variables.

<details>
<summary>relevant configurations for those interested</summary>
<br/>

`.npmrc`:

```ini
# https://docs.npmjs.com/cli/configuring-npm/npmrc

@flex-development:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=${PAT_BOT:-GITHUB_TOKEN}
//npm.pkg.github.com/:always-auth=true
```

`.yarnrc.yml`:

```yml
# https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nmHoistingLimits: none

nodeLinker: node-modules

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: ${PAT_BOT:-GITHUB_TOKEN}
    npmRegistryServer: https://npm.pkg.github.com

patchFolder: ./patches

yarnPath: .yarn/releases/yarn-4.0.0-rc.14.cjs
```
</details>

[1]: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#registries
[2]: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
[3]: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#npm-registry
