### ISSUE TITLE
Dependabot suggested upgrading from Django 3.2.9 to 4.0.0 even though 3.2.10 is available (and is the more logical version to upgrade to)

### ISSUE THREAD

**Issue by ahmedsaoudi** [dependabot/dependabot-core#4515]
**Package ecosystem**
Pip

**Manifest location and content prior to update**
`/requirements.txt`

```
Django==3.2.9
gunicorn==20.1.0
pytz==2021.3
sqlparse==0.4.2
```

**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "dependabot"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dependabot"
    schedule:
      interval: "daily"
```

**Updated dependency**
Django: 3.2.9 -> 4.0.0

**What you expected to see, versus what you actually saw**
Expected behavior: 
Dependabot suggests updating Django from 3.2.9 to 3.2.10

Actual behavior: 
Dependabot suggests updating Django from 3.2.9 to 4.0.0

**Native package manager behavior**
The native package manager wouldn't update the dependency as it is pinned to a specific version, namely 3.2.9. 

**Images of the diff or a link to the PR, issue or logs**
> Copy of PR: 
> 
> Bump django from 3.2.9 to 4.0 #14
> 
> Bumps django from 3.2.9 to 4.0.
>
> Commits
> // list of commits
> 
> Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting @dependabot rebase.

**🕹 Bonus points: Smallest manifest that reproduces the issue**
```
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "dependabot"
    schedule:
      interval: "daily"
```
