### ISSUE TITLE
Hyphenated version treated as older (Docker)

### ISSUE THREAD

**Issue by apicht** [dependabot/dependabot-core#4535]
**Package ecosystem**
docker

**Package manager version**
N/A

**Language version**
N/A

**Manifest location and content prior to update**
`/Dockerfile`
```
FROM openresty/openresty:1.19.9.1-4-buster-fat
```

**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/Los_Angeles"
```

**Updated dependency**
`openresty/openresty:1.19.9.1-4-buster-fat` to `openresty/openresty:1.19.9.1-buster-fat`

**What you expected to see, versus what you actually saw**
Expected `openresty/openresty:1.19.9.1-4-buster-fat` to be treated as equal or later than `openresty/openresty:1.19.9.1-buster-fat`

**Native package manager behavior**
N/A

**Images of the diff or a link to the PR, issue or logs**
```
/Dockerfile
@@ -1,4 +1,4 @@
- FROM openresty/openresty:1.19.9.1-4-buster-fat
+ FROM openresty/openresty:1.19.9.1-buster-fat
```

**🕹 Bonus points: Smallest manifest that reproduces the issue**
```
FROM openresty/openresty:1.19.9.1-4-buster-fat
```
