### ISSUE TITLE
Cloudsmith Authentication (Python)

### ISSUE THREAD

**Issue by trent-abc** [dependabot/dependabot-core#4539]
## Request

We'd like to specify a variable, for url.

## Background:

We're trying to use a variable for our private-registry at cloudsmith.io and we get a parsing error.  I think it's going to be similar to issue https://github.com/dependabot/dependabot-core/issues/3478

<img width="922" alt="Screen Shot 2021-12-16 at 4 33 25 PM" src="https://user-images.githubusercontent.com/82410520/146469181-6f8e4f9b-9cf0-447d-93d1-5c1d7d44eeb8.png">

We tried using a URL variable for the whole thing

```
registries:
  # Provide credentials for the private python repo
  company-repo:
    type: python-index
    url: ${{secrets.CLOUDSMITH_URL}}
    replaces-base: false
```

As well as a token

```
registries:
  # Provide credentials for the private python repo
  company-repo:
    type: python-index
    url: https://dl.cloudsmith.io/${{token}}/company/repo/python/simple/
    token: ${{secrets.CLOUDSMITH_URL}}
    replaces-base: false
```
Based on the [documentation](https://help.cloudsmith.io/docs/python-repository) it should work but we seem to be getting a parsing error--basic auth gives us a 401 instead.

## Main point

The only thing that worked was hard coding the password into the URL, which had no issues at all.

**Comment by mctofu** [comment]
Hi @trent-abc, we don't recommend including any secrets as part of the registry url as the url can end up in error messages or the Dependabot logs for the update.

Dependabot does support basic auth for python registries and it seems to be a supported option for Cloudsmith. Do you have any more details about what wasn't working when you tried that? You can also submit a GitHub support request for us to investigate if the details are private.

**Comment by jurre** [comment]
I would expect it to be something like this:

```
url = "https://<username>:${CLOUDSMITH_KEY}@dl.cloudsmith.io/basic/company/repo/python/index/"
```

**Comment by trent-abc** [comment]
@Jurre How will dependabot get access to "`${CLOUDSMITH_KEY}`" or "`<username>`" in the Pipfile? A dependabot secret? In the yaml we use `${{secrets.CLOUDSMITH_TOKEN}}` do we need the same syntax in the Pipfile? I tried this with the same 401 result (I have configured both _KEY and _TOKEN to the same value in my repo, for testing I hard coded username):

```url = "https://<username>:${CLOUDSMITH_KEY}@dl.cloudsmith.io/basic/company/repo/python/index/```

It would be nice if there was a Pipfile example in the [documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#python-index)

**Comment by mctofu** [comment]
@trent-abc: Could you try changing the registry url in the `dependabot.yml` to `https://dl.cloudsmith.io/basic/company/repo/python/` (omitting `index/` at the end).

What's happening is that the wheel url `https://dl.cloudsmith.io:443/basic/company/repo/python/package-version-py3-none-any.whl` isn't under the `index/` path so the registry authentication isn't applied. Broadening the registry url should fix that. Dependabot will make some extra requests to try and find the dependencies under both paths (`basic/company/repo/python/` & `basic/company/repo/python/index/`) but that shouldn't prevent the update from completing.

We've seen this same issue occur with Azure DevOps & adjusting the registry url got it work so hopefully we'll see the same result here. I've added a note that Cloudsmith is also affected by this to our internal issue that tracks this.

**Comment by trent-abc** [comment]
Thanks so much @mctofu ! This was the working configuration for me
## dependabot.yml:
```
registries:
  # Provide credentials for the private python repo
  company-repo:
    type: python-index
    url: "https://dl.cloudsmith.io/basic/company/repo/python/"
    username: my-cloudsmith-name
    password: ${{secrets.CLOUDSMITH_TOKEN}}
    replaces-base: false
```
## Pipfile:
```
[[source]]
url = "https://dl.cloudsmith.io/basic/company/repo/python/index/"
verify_ssl = true
name = "cloudsmith"
```

I'm getting a timeout because I guess the process was taking too long (Several hours) but I'll open another ticket for that.
