### ISSUE TITLE
Correctly handle multiple tags for same terraform module version

### ISSUE THREAD

**Issue by gavinclarkeuk** [dependabot/dependabot-core#4616]
Dependabot is raising unnecessary PRs for private github terraform modules which are tagged using multiple tags to pin at major/minor or patch versions (e.g. `v2`, `v2.2`, `v2.2.0`). A module dependency on v2 is causing a PR to be raised to change the dependency to v2.2, despite both tags pointing at the same version.

**Package ecosystem**
terraform

**dependabot.yml content**

```
version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" 
```

**Updated dependency**

Dependency was for an internal terraform module stored in a private github repo. The module is tagged with 3 tags for pinning at different levels - e.g. `v2`, `v2.2`, `v2.2.0`

The project being scanned had a dependency on `v2` of the module.

**What you expected to see, versus what you actually saw**
Saw a PR raised to update the version from `v2 `to `v2.2`. Given the `v2`, `v2.2`, `v2.2.0` tags all point to the same version. I would expect no PR to be raised

**🕹 Bonus points: Smallest manifest that reproduces the issue**

example.tf
`module "example_module" {
  source       = "git@github.com:my-org/my-module/?ref=v2"
}
`
