### ISSUE TITLE
Dependabot timed out during its update

### ISSUE THREAD

**Issue by trent-abc** [dependabot/dependabot-core#4634]
I finally got dependabot running for our python, and it successfully created 5 pull requests.  However it wasn't able to finish (After a few hours) and ended with the following error message:

Dependabot timed out during its update
Dependabot failed to update your dependencies because it took too long to complete.

<img width="915" alt="Screen Shot 2022-01-14 at 1 32 54 PM" src="https://user-images.githubusercontent.com/82410520/149588130-189a3cb7-668f-41dc-8950-6ba968cba755.png">

I'd like to be able to configure this timeout value so I can allow dependabot to finish our long list of dependencies (perhaps slowed down by the private registry).

Also, the only package in the private registry which we're trying to ignore still has to go through the download process, which may be adding a significant amount of time to the scan.

## dependabot.yml:
```
version: 2
updates:
  # Configuration for Python/Pipenv
  - package-ecosystem: "pip"
    directory: "/python/" # Location of package manifests
    # Check for updates weekly on Monday at 9am
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Vancouver"
    # Commit messages will be prefixed with "pipenv"
    # Followed by a list of dependencies updated in the commit
    commit-message:
      prefix: "pipenv"
      include: "scope"
    ignore:
      - dependency-name: "some-dependency"
    insecure-external-code-execution: allow
    registries: "*"
    open-pull-requests-limit: 5

registries:
  # Provide credentials for the private python repo
  company-repo:
    type: python-index
    url: "https://dl.cloudsmith.io/basic/company/repo/python/"
    username: my-cloudsmith-name
    password: ${{secrets.CLOUDSMITH_TOKEN}}
    replaces-base: false
```

The last lines in the log I see are like so (And it shows 45 minutes total but this log isn't available to click on for at least 4 hours):

```
updater | time="2022-01-17T17:59:18Z" level=info msg="task complete" container_id=job-263717367-updater exit_code=137 job_id=263717367 step=updater
updater | time="2022-01-17T17:59:18Z" level=warning msg="timeout running job" error="waiting for updater: waiting for container: context deadline exceeded" job_id=263717367
```
