### ISSUE TITLE
Python updated to an alpha version. 3.10.1-slim -> 3.11.0a4-slim

### ISSUE THREAD

**Issue by oittaa** [dependabot/dependabot-core#4643]
**Package ecosystem**

docker

**Package manager version**

**Language version**

**Manifest location and content prior to update**

**dependabot.yml content**

```
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
```
**Updated dependency**

-FROM python:3.10.1-slim
+FROM python:3.11.0a4-slim
**What you expected to see, versus what you actually saw**

Dependabot should use stable versions and not update to alpha versions.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

https://github.com/oittaa/gcp-storage-emulator/pull/124

**🕹 Bonus points: Smallest manifest that reproduces the issue**
