### ISSUE TITLE
Yarn.lock is updated with public registry instead of private one

### ISSUE THREAD

**Issue by godric3** [dependabot/dependabot-core#4669]
**Package ecosystem**
yarn
**Package manager version**
yarn 1.22.17
**Language version**
node 12.8.1
**Manifest location and content prior to update**
package.json
yarn.lock
**dependabot.yml content**
```
version: 2
registries:
  artifactory:
    type: npm-registry
    url: https://artifactory.XXX.com/artifactory/api/npm/XXX-npm/
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_PASSWORD}}
updates:
  - package-ecosystem: 'npm'
    registries:
      - artifactory
    directory: '/'
    schedule:
      interval: 'daily'
```
**Updated dependency**
https://github.com/websockets/ws from 6.2.1 to 6.2.2, but happen for other packages too.
**What you expected to see, versus what you actually saw**
yarn.lock changed from
```
resolved "https://artifactory.XXX.com:443/artifactory/api/npm/XXX-npm/ws/-/ws-6.2.1.tgz#442fdf0a47ed64f59b6a5d8ff130f4748ed524fb"
```
to
```
resolved "https://registry.yarnpkg.com/ws/-/ws-6.2.2.tgz#dd5cdbd57a9979916097652d78f1cc5faea0c32e"
```
I expect it to still use private registry.
**Native package manager behavior**
Updating package locally resolve to correct private registry. Locally I have `.npmrc` file that specify registry and credentials, this file is ignored by git so every collaborator can have their file in repo directory.

All logs referencing this package point to correct artifactory, but there are some logs referencing public one:
```
  proxy | 2022/01/26 12:18:28 [118] * authenticating npm registry request (host: artifactory.XXX.com, basic auth)
  proxy | 2022/01/26 12:18:28 [110] 200 https://artifactory.XXX.com:443/artifactory/api/npm/XXX-npm/callsites/-/callsites-0.2.0.tgz
  proxy | 2022/01/26 12:18:28 [120] GET https://registry.yarnpkg.com:443/sass/-/sass-1.49.0.tgz
  proxy | 2022/01/26 12:18:28 [122] GET https://registry.yarnpkg.com:443/chokidar/-/chokidar-3.5.3.tgz
  proxy | 2022/01/26 12:18:28 [112] 200 https://artifactory.XXX.com:443/artifactory/api/npm/XXX-npm/type/-/type-2.0.0.tgz
  proxy | 2022/01/26 12:18:28 [120] 200 https://registry.yarnpkg.com:443/sass/-/sass-1.49.0.tgz
  proxy | 2022/01/26 12:18:28 [122] 200 https://registry.yarnpkg.com:443/chokidar/-/chokidar-3.5.3.tgz
```

**Comment by GuillaumeBenini** [comment]
I believe this is the case because the security updates don't take into account registries config in the dependabot.yml. This is what I noticed at least with my repo.

**Comment by feelepxyz** [comment]
> Locally I have .npmrc file that specify registry and credentials, this file is ignored by git so every collaborator can have their file in repo directory.

If you don't include a `.npmrc` file, dependabot-core will try and guess what should be in this file to tell npm/yarn which registry to use. In your cause, I think you intend to make the artifactory registry "global" so it's used for all packages in your lockfile?

If all dependencies in the lockfile have the same registry, and this matches the `url` in `dependabot.yml`, you should get a `.npmrc` file that looks like this:

```
registry=https://artifactory.XXX.com/artifactory/api/npm/XXX-npm/
always-auth = true
```

It seems like this isn't happening, causing me to think this piece of code isn't matching: https://github.com/dependabot/dependabot-core/blob/9fe65f918bd2e89ab6ac627d3d48b089e30e3a08/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb#L56

Looking at your logs and the config file, I can see that the `lockfile` urls include a port `https://artifactory.XXX.com:443/..` but the `dependabot.yml` doesn't `https://artifactory.XXX.com/...`.

@godric3 could you try adding `:443` to the registry url in `dependabot.yml`? It would be nice to handle this in dependabot tbh but curious if this would fix the issue.

**Comment by godric3** [comment]
Good catch, but I cannot check it right now because it turned out we had(and still have) some problem with artifactory, so it may be that. I will give update once we sort out thing with artifactory

**Comment by godric3** [comment]
Ok we got artifactory working and I tried your suggestion about registry url in dependabot config file. 
It seems that PRs made due to security issues have wrong registry, but normal version updates use proper one.

**Comment by Tadimsky** [comment]
We're running into the same issue as this. 

Our `dependabot.yml` file has this configured:

```yaml
version: 2
registries:
  npm-artifactory:
    type: npm-registry
    url: https://packages.convoy.com/artifactory/api/npm/npm/
    username: <<redacted>>
    password: <<redacted>>
updates:
  - package-ecosystem: npm
    registries:
      - npm-artifactory
    directory: /
    schedule:
      interval: daily
```

Our `.yarnrc` has this:

```
--registry "https://packages.convoy.com/artifactory/api/npm/npm/"

#
# use vendored yarn
#
yarn-path ".yarn/releases/yarn-1.22.4.js"
```

And all entries in our `yarn.lock` file come from that private repo.
However, a security update PR that came out for us just switched it over from this:

```simple-get@^2.7.0:
  version "2.8.1"
  resolved "https://packages.convoy.com/artifactory/api/npm/npm/simple-get/-/simple-get-2.8.1.tgz#0e22e91d4575d87620620bc91308d57a77f44b5d"
  integrity sha1-DiLpHUV12HYgYgvJEwjVenf0S10=
```

to this: 

```
simple-get@^2.7.0:
  version "2.8.2"
  resolved "https://registry.yarnpkg.com/simple-get/-/simple-get-2.8.2.tgz#5708fb0919d440657326cd5fe7d2599d07705019"
  integrity sha512-Ijd/rV5o+mSBBs4F/x9oDPtTx9Zb6X9brmnXvMW4J7IR15ngi9q5xxqWBKU744jTZiaXtxaPL7uHG6vtN8kUkw==
```
