### ISSUE TITLE
allow same package ecosystem directory, but with different constraint

### ISSUE THREAD

**Issue by climba03003** [dependabot/dependabot-core#4672]
We would like to split the update interval for `production` and `development` package of `npm`. The main reason is that most of `development` package is update very fast and it will spam the PR too much.

The below configuration is what we tried to achieve but no luck.
It throws an error `The property '#/updates/2' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'`
https://github.com/fastify/fastify/runs/4952267835

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
 
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "development"
 ```
