### ISSUE TITLE
Dependabot fails with Rust named profiles

### ISSUE THREAD

**Issue by Guara92** [dependabot/dependabot-core#4676]
Dependabot fails to parse `cargo.toml` with named profiles due to outdated Cargo version
![image](https://user-images.githubusercontent.com/12493527/151345966-02a2c33d-a4fa-4b4d-907d-4a26b9a7d36f.png)
**Package ecosystem**
Rust

**Package manager version**
Cargo 1.58.0

**Language version**
Rust 1.58.1

**Profile Example**
```toml
[profile.release]
lto = "off"
opt-level = 2

[profile.production]
inherits = "release"
lto = "thin"
codegen-units = 8
opt-level = 3
incremental = false
```
