### ISSUE TITLE
Having issues with node versions

### ISSUE THREAD

**Issue by johannbotha** [dependabot/dependabot-core#4698]
**Package ecosystem**
npm

**Package manager version**
npm 7.21.1

**Language version**
v16.9.1

**Manifest location and content prior to update**

```
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
    allow:
      - dependency-type: production
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
```

**Updated dependency**

**What you expected to see, versus what you actually saw**

**Native package manager behavior**

Dependabot started failing with
```
...
plugin@1.2.1
updater | <job_275629255> npm WARN   node_modules/webpack-filter-warnings-plugin
updater | <job_275629255> npm WARN     webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.4.1
updater | <job_275629255> npm WARN     node_modules/@storybook/builder-webpack4
updater | <job_275629255> npm ERR! code EBADENGINE
updater | <job_275629255> npm ERR! engine Unsupported engine
updater | <job_275629255> npm ERR! engine Not compatible with your version of node/npm: coin-tracker@1.0.0
updater | <job_275629255> npm ERR! notsup Not compatible with your version of node/npm: coin-tracker@1.0.0
updater | <job_275629255> npm ERR! notsup Required: {"node":"^16.9.1","npm":"^7.21.1"}
updater | <job_275629255> npm ERR! notsup Actual:   {"npm":"7.21.0","node":"v14.18.3"}
updater | <job_275629255> 
updater | <job_275629255> npm ERR! A complete log of this run can be found in:
updater | <job_275629255> npm ERR!     /home/dependabot/.npm/_logs/2022-02-03T14_23_08_823Z-debug.log
...
```

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**
