### ISSUE TITLE
Incorrect file change when a python extra module exists with non-extra

### ISSUE THREAD

**Issue by robbruce** [dependabot/dependabot-core#4720]
**Package ecosystem**
python setup.cfg
**Package manager version**
n/a
**Language version**
python 3.10
**Manifest location and content prior to update**

```ini
[options]
install_requires =
    sqlalchemy==1.4.29
    sqlalchemy[postgresql_asyncpg]==1.4.29
```

```ini
[options]
install_requires =
    sqlalchemy==1.4.31
    sqlalchemy[postgresql_asyncpg]==1.4.29
```
**dependabot.yml content**

```yaml
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
```

**Updated dependency**

PR title was 
> Bump sqlalchemy[postgresql_asyncpg] from 1.4.29 to 1.4.31

**What you expected to see, versus what you actually saw**

Expected `sqlalchemy[postgresql_asyncpg]` to be updated, whereas `sqlalchemy` was. Ideally, both references to `sqlalchemy` should be included in the same PR.

**Native package manager behavior**

n/a

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

```ini
[metadata]
name = test
version = 0.0.1
description = test
author =  Me

[options]
packages = find:
python_requires = >=3.10
install_requires =
    sqlalchemy==1.4.29
    sqlalchemy[postgresql_asyncpg]==1.4.29
```
