### ISSUE TITLE
Exclude specific modules from maven repository

### ISSUE THREAD

**Issue by rtc11** [dependabot/dependabot-core#4762]
Dependabot selects wrong version from maven central when duplicates are found.
In my case, I have to add an extra repository `packages.confluent.io/maven` to get som io.confluent artifact.
To my misfortune, this repo also publishes other packages that I use.

```kotlin
repositories {
    mavenCentral()
    maven("https://packages.confluent.io/maven/")
}
```

I can fix this with Gradle by excluding or including specific groups, but Dependabot will not account for this.
```kotlin
repositories {
    mavenCentral()
    maven("https://packages.confluent.io/maven/") {
        content {
            excludeGroup("org.apache.kafka")
        }
    }
}
```

Because dependabot is not supporting Gradle, there is now two alternatives:
Support this syntax above, or add support in `dependabot.yml´ to exclude dependencies by pattern matching.

**Comment by brrygrdn** [comment]
👋🏻  @rtc11 Thanks for your feedback, this is a tricky one.

To make sure I understand as I don't work with maven day-to-day:

The issue is that `https://packages.confluent.io/maven/` is essentially mirroring `"org.apache.kafka"` which Dependabot seems to be using by preference over the version in Maven Central, is that correct?

I've labelled this as Gradle just to highlight that supporting it is a potential addressable case, but I'd need to check how if and how we address precedence of dependency servers within Dependabot for Maven to see if we have any leverage for a configuration point.

At a very high level, my gut instinct is that we'd value adding Gradle support more than making this configuration option available.

**Comment by rtc11** [comment]
@brrygrdn Yes that is correct! It would be awesome with Gradle support, this way you can customize "complex" behaviours.  

Maybe another option is to add a dependabot PR command, like:
```
@dependabot ignore this package repository
```

Keep up the good work, I love dependabot!

**Comment by olamy** [comment]
Even a simple feature such ignoring a repository listed in the pom would be great.
something such could use only maven-central and ignoring repositories found in poms:
```
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2
    username: ""
    password: ""

updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-central
    target-branch: "master"
    schedule:
      interval: "daily"
```
