### ISSUE TITLE
No update PR created for private github action shared with enterprise/org

### ISSUE THREAD

**Issue by nackerman-nydig** [dependabot/dependabot-core#4777]
**Package ecosystem**

Calling an internal repo's Github Actions, from a private repo. Both repos live in our organizations enterprise github account.

We followed this wiki to enable calling the private action -> https://docs.github.com/en/enterprise-cloud@latest/actions/creating-actions/sharing-actions-and-workflows-with-your-enterprise

And then went through steps on github to allow Dependabot access to the repo that houses the private action.

**Package manager version**

N/A

**Language version**

github-actions stored in an enterprise's internal repo

**Manifest location and content prior to update**

N/A

**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

**Updated dependency**

```
      - name: Check
        uses: {ORGANIZATION}/.github/actions/cruft-check@f007e699e31291de9e2b8810d40962b2ceb21863 #this hash corresponds to release: 1.1.0
        with:
          token: ${{ secrets.TOKEN }}
```

**What you expected to see, versus what you actually saw**

{ORGANIZATION}/.github repo's latest release is v1.2.29
I expect Dependabot to identify this and create a PR updating 1.1.0 -> v1.2.29

However, no PR is created. Checking dependabot logs I see:
```
updater | INFO <job_304479650> Checking if {ORGANIZATION}/.github 1.1.0 needs updating
  proxy | 2022/02/28 15:21:37 [068] GET https://github.com:443/{ORGANIZATION}/.github.git/info/refs?service=git-upload-pack
  proxy | 2022/02/28 15:21:37 [068] * authenticating git server request (host: github.com)
  proxy | 2022/02/28 15:21:37 [068] 200 https://github.com:443/{ORGANIZATION}/.github.git/info/refs?service=git-upload-pack
updater | INFO <job_304479650> Latest version is 
updater | INFO <job_304479650> Requirements to unlock update_not_possible
updater | INFO <job_304479650> Requirements update strategy 
updater | INFO <job_304479650> No update possible for {ORGANIZATION}/.github 1.1.0
```

I'm wondering why dependabot isn't creating an update PR in this case. I believe private github actions should be supported based on these docs -> https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates#supported-repositories-and-ecosystems

Is this case supported? Should dependabot be creating update PRs for github-actions stored in an Organization's private repo? Any thoughts on why dependabot isnt creating a PR to update from 1.1.0 -> v1.2.29?
