### ISSUE TITLE
Errors trying to install from private Azure Artifacts feed for python/poetry

### ISSUE THREAD

**Issue by rsb177** [dependabot/dependabot-core#4780]
**Package ecosystem**
Python/Poetry
**Package manager version**
Poetry 1.1.13
**Language version**
Python 3.10.2
**Manifest location and content prior to update**

**dependabot.yml content**
```
version: 2
registries:
  python-azure:
    type: python-index
    url: https://pkgs.dev.azure.com/<org>/<project_id>/_packaging/<my-python-feed>/pypi/simple/
    token: ${{secrets.MY_AZURE_DEVOPS_TOKEN}}
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    # Look for a `*requirements.txt` (or pyproject.toml in our case) in the `root` directory
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - python-azure # Allow version updates for dependencies in this registry
    # Check for updates once a week
    schedule:
      interval: "weekly"
```

**Updated dependency**
any
**What you expected to see, versus what you actually saw**
We currently get a 401 unauthorized error when trying to install the private library.
**Native package manager behavior**
It installs just fine locally with the same PAT

after reading a lot of other issues in other languages with people trying to use Azure Artifacts, i've tried a bunch of different things for how to specify the token (prepending a `:`, using username & password instead of token, adding a `:` to the end of the token, adding a fake username + `:` to the beginning of the token, etc.).  I've yet to come up with anything that works.  When setting up poetry locally, I have to specify my PAT & a fake username (doesn't matter what it's set to, just has to be something) as environment variables recognized by poetry.  Is there any way to see what dependabot is doing?
