### ISSUE TITLE
Dependabot updating SHA to short semver

### ISSUE THREAD

**Issue by wolf99** [dependabot/dependabot-core#4781]
**Package ecosystem**
GitHub actions, actions/checkout
**Package manager version**
actions/checkout@v3

**dependabot.yml content**
https://github.com/exercism/probby/blob/main/.github/dependabot.yml

**What you expected to see, versus what you actually saw**
Expected to see `actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f` change to `actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846`

Instead it changed to `actions/checkout@v3`

**Images of the diff or a link to the PR, issue or logs**
See diff: https://github.com/exercism/probby/pull/15/files

**🕹 Bonus points: Smallest manifest that reproduces the issue**
How's 8 LoC ? 
Same content as the above link 😉 

```yml
version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```
