### ISSUE TITLE
Exceptions in `ignore: <update-types>` config

### ISSUE THREAD

**Issue by pawelryznar** [dependabot/dependabot-core#4792]
Currently we can ignore some update types https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore
But this will apply to all dependencies.

I would like to be able to add an exception to the ignore:update-type.
For example, in my project I ignore patch updates, but I would like to configure one dependency (main framework) to be checked for all update types.

**Comment by Bullrich** [comment]
I support this. I'm having the same problem and looking for a solution.

Maybe we could write something like:
```yml
version: 2
updates:
  - package-ecosystem: "npm"
    ignore:
      # add a ! like in github gitignore directory
      - dependency-name: "*!package-name"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
```
