### ISSUE TITLE
PR created that *downgrades* semver v2 compliant nuget package

### ISSUE THREAD

**Issue by AArnott** [dependabot/dependabot-core#4805]
**Package ecosystem**
NuGet

**Manifest location and content prior to update**

`/.github/dependabot.yml`

```yml
version: 2
updates:
- package-ecosystem: npm
  directory: /src/nerdbank-streams
  schedule:
    interval: monthly
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: monthly
```

**What you expected to see, versus what you actually saw**

Dependabot created https://github.com/AArnott/Nerdbank.Streams/pull/463, which *downgrades* StyleCop.Analyzers 1.2.0-beta.376 to 1.2.0-beta.66.
Note that this package is using semver v2 rules and that 376 should therefore be seen as better than 66. It seems that Dependabot is treating it as a semver v1 version.

**Native package manager behavior**

NuGet Package Manager recognizers that .376 is better than .66.

**Images of the diff or a link to the PR, issue or logs**

https://github.com/AArnott/Nerdbank.Streams/pull/463

```diff
-   <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.376" PrivateAssets="all" />
+   <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.66" PrivateAssets="all" />
```
