### ISSUE TITLE
dependabot not detecting latest version of github action

### ISSUE THREAD

**Issue by rethab** [dependabot/dependabot-core#4834]
**Package ecosystem**

- github actions

**dependabot.yml content**

```yaml
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'feat(deps)'
```
**Updated dependency**

- nothing was updated

**What you expected to see, versus what you actually saw**

workflow references action like so:
```yaml
        uses: actions/download-artifact@v2
```

In the logs from dependabot I see:

```text
updater | INFO <job_31347D_N_T> Checking if actions/download-artifact 2 needs updating
  proxy | 2022/03/11 14:27:39 [040] GET https://github.com:443/actions/download-artifact.git/info/refs?service=git-upload-pack
  proxy | 2022/03/11 14:27:39 [040] * authenticating git server request (host: github.com)
  proxy | 2022/03/11 14:27:39 [040] 200 https://github.com:443/actions/download-artifact.git/info/refs?service=git-upload-pack
updater | INFO <job_31347D_N_T> Latest version is f023be2c48cc18debc3bacd34cb396e0295e2869
updater | INFO <job_31347D_N_T> No update needed for actions/download-artifact 2
```

but this is wrong: https://github.com/actions/download-artifact/releases there is a version `v3.0.0` as well as a major tag `v3`.

the latest version f023be2c48cc18debc3bacd34cb396e0295e2869 mentioned in the logs points to `v2`.

So I would expect dependabot to create a PR and update this action to `v3`.
