### ISSUE TITLE
Bundler - dependabot updater times out without detailed information

### ISSUE THREAD

**Issue by mobilutz** [dependabot/dependabot-core#4852]
Our dependabot run is running into timeouts, without any obvious information on why they do.
I see that there is an issue here regarding timeout #2416 , but that is related to `composer`

My guess is, that the problem has to do with some dependency we are having. Is there a way to get more debug output what exactly dependabot is doing?

The thing here is, that the logs (see below) is not showing anything for 36 minutes and then just the timeout information.

These are the last line in the update log on Github (without exposing some internal information):
```
...
updater | INFO <job_314771591> Checking if activerecord-postgis-adapter 7.1.1 needs updating
  proxy | 2022/03/15 04:07:58 [164] GET https://rubygems.org:443/api/v1/versions/activerecord-postgis-adapter.json
  proxy | 2022/03/15 04:07:58 [164] 200 https://rubygems.org:443/api/v1/versions/activerecord-postgis-adapter.json
updater | INFO <job_314771591> Latest version is 8.0.0
  proxy | 2022/03/15 04:07:59 [166] GET https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:07:59 [166] * authenticating rubygems server request (host: gems.contribsys.com)
  proxy | 2022/03/15 04:08:00 [166] 206 https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:08:00 [168] GET https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:08:00 [168] * authenticating rubygems server request (host: gems.contribsys.com)
  proxy | 2022/03/15 04:08:00 [168] 200 https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:08:01 [170] GET https://index.rubygems.org:443/versions
  proxy | 2022/03/15 04:08:01 [170] 304 https://index.rubygems.org:443/versions
  proxy | 2022/03/15 04:08:14 [172] GET https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:08:14 [172] * authenticating rubygems server request (host: gems.contribsys.com)
  proxy | 2022/03/15 04:08:14 [172] 206 https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:08:14 [174] GET https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:08:14 [174] * authenticating rubygems server request (host: gems.contribsys.com)
  proxy | 2022/03/15 04:08:14 [174] 200 https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:08:15 [176] GET https://index.rubygems.org:443/versions
  proxy | 2022/03/15 04:08:15 [176] 304 https://index.rubygems.org:443/versions
  proxy | 2022/03/15 04:09:10 [178] GET https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:09:10 [178] * authenticating rubygems server request (host: gems.contribsys.com)
  proxy | 2022/03/15 04:09:10 [178] 206 https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:09:10 [180] GET https://gems.contribsys.com:443/versions
  proxy | 2022/03/15 04:09:10 [180] * authenticating rubygems server request (host: gems.contribsys.com)
  proxy | 2022/03/15 04:09:11 [182] GET https://index.rubygems.org:443/versions
  proxy | 2022/03/15 04:09:11 [182] 206 https://index.rubygems.org:443/versions
updater | time="2022-03-15T04:45:40Z" level=info msg="task complete" container_id=job-314771591-updater exit_code=137 job_id=314771591 step=updater
updater | time="2022-03-15T04:45:41Z" level=warning msg="timeout running job" error="waiting for updater: waiting for container: context deadline exceeded" job_id=314771591
```

**Package ecosystem**
bundler, etc.

**Package manager version**
❯ bundle --version
Bundler version 2.3.3

**Language version**
❯ ruby -v
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin20]

**Manifest location and content prior to update**
/Gemfile

**dependabot.yml content**
```yml
version: 2

registries:
  rubygems-server-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.TOKEN}}

  rubygems-server-gems-contribsys-com:
    type: rubygems-server
    url: https://gems.contribsys.com
    username: "${{secrets.USERNAME}}"
    password: "${{secrets.PASSWORD}}"

  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.TOKEN}}"

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 50
    labels:
      - Rubygems
      - dependencies
    versioning-strategy: increase
    registries:
      - rubygems-server-gems-contribsys-com
      - rubygems-server-github-com
    insecure-external-code-execution: allow

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 50
    registries:
      - npm-registry-npm-pkg-github-com

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```

**What you expected to see, versus what you actually saw**
I am expected to NOT see a timeout. And when, then with some more information 😉 

**What gemservers (sources) are used?**
* rubygems.org
* gems.contribsys.com
* GitHub git repo links

**🕹 Bonus points: Smallest manifest that reproduces the issue**
As this would expose our internal gemfile content which has many private repos in them I cannot do that.
