### ISSUE TITLE
Resolve rubocop warning - either enable or disable these cops, or default to enabling all new cops

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#4860]
I'm seeing this noise in the CI log output that looks like it'd be easy to handle: https://github.com/dependabot/dependabot-core/runs/5559703308?check_suite_focus=true

Does the core team prefer to explicitly enable / disable each linter, or opt-in by default and then disable ones that cause problems?

```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.

Please also note that you can opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable
Gemspec/RequireMFA: # new in 1.23
  Enabled: true
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/OpenStructUse: # new in 1.23
  Enabled: true
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true
Style/SelectByRegexp: # new in 1.22
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
```
