### ISSUE TITLE
bug: `update-type` is sometimes `null`

### ISSUE THREAD

**Issue by vicary** [dependabot/dependabot-core#4893]
I want to auto-merge for minor and patch updates, but the `update-type` is always `null`.

You may see [this job](https://github.com/vicary/test-dependabot/runs/4272654397) for the metadata output.

Am I doing it wrong?

**Comment by brrygrdn** [comment]
I've transferred this issue in from https://github.com/dependabot/fetch-metadata/ as there is a workaround for the action but the bug is effectively that core doesn't populate this on commits sometimes so it isn't fully resolved by that PR

Workaround: https://github.com/dependabot/fetch-metadata/pull/173

**Comment by vicary** [comment]
@brrygrdn Maybe related to the recent fix at https://github.com/dependabot/fetch-metadata/pull/173, I kept my test repo open as a monitor for the progress of this issue.

In fact it had been auto-upgrading normally until today, please see https://github.com/vicary/test-dependabot/pull/50.

`outputs.update-type` is `null` and it's never seen before.

<table>
<tr>
<th>Text</th>
<th>Screenshot</th>
</tr>

<tr>
<td>

```
Run dependabot/fetch-metadata@v1.1.1
  with:
    github-token: ***
Parsing Dependabot metadata
Outputting metadata for 1 updated dependency
  outputs.dependency-names: minimist
  outputs.dependency-type: indirect
  outputs.update-type: null
```

</td>
<td>

![image](https://user-images.githubusercontent.com/85772/159898021-e4ad795d-5d55-4390-93d5-142982701ab1.png)

</td>
</tr>
</table>

**Comment by mwaddell** [comment]
@vicary Your job is still using `fetch-metadata@v1.1.1` - the fix in dependabot/fetch-metadata#173 is only available in `fetch-metadata@main` right now.

You are correct that this bug (#4893) still exists in `dependabot-core` and it does inconsistently fill out the `update-type` property.  dependabot/fetch-metadata#173 is a workaround for this open bug that calculates the `update-type` on the fly if it was not passed in the commit message from `dependabot-core`.

Please update your action to use `fetch-metadata@main` and see if that resolves your issue.

**Comment by vicary** [comment]
@mwaddell Yes, it's now working even with @dependabot commands.

**Comment by jeffwidman** [comment]
Is this only happening on PR rebases and not the initial commit of a PR? 

If so, I wonder if the root cause is the same as described in https://github.com/dependabot/dependabot-core/issues/4652#issuecomment-1021724508?

**Comment by FlorianLeChat** [comment]
I started having this issue when I started using the grouped updates feature on some of my private repositories and on a [public repository](https://github.com/FlorianLeChat/Domego/actions/runs/6033966165/job/16371490114?pr=232) today.

```
Run dependabot/fetch-metadata@v1
  with:
    github-token: ***
    skip-commit-verification: false
    skip-verification: false
Parsing Dependabot metadata
Outputting metadata for [2](https://github.com/FlorianLeChat/Domego/actions/runs/6033966165/job/16371490114?pr=232#step:2:2) updated dependencies
  outputs.dependency-names: mongodb, mongoose
  outputs.dependency-type: direct:production
  outputs.update-type: null
  outputs.directory: /
  outputs.package-ecosystem: npm_and_yarn
  outputs.target-branch: master
  outputs.previous-version: 
  outputs.new-version: 
  outputs.compatibility-score: 0
  outputs.maintainer-changes: false
  outputs.dependency-group: 
  outputs.alert-state: 
  outputs.ghsa-id: 
  outputs.cvss: 0
```
