### ISSUE TITLE
runtime.txt not works 

### ISSUE THREAD

**Issue by lucemia** [dependabot/dependabot-core#4901]
**Package ecosystem**

pip

**Package manager version**

**Language version**

python

**Manifest location and content prior to update**

a requirements file contains numpy

**dependabot.yml content**

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/requirements" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
```

**Updated dependency**

**What you expected to see, versus what you actually saw**

like https://github.com/dependabot/dependabot-core/issues/2792
Since dependabot's default runtime changes to 3.10, The dependabot didn't work with numpy again recently.

If I setup python version by `.python-version` and set content as `3.8.12`, **the dependabot will work!**
However, if I use `runtime.txt` and set content as `python-3.8.12`, **the dependabot will not work!** It will still use python 3.10.

```
updater | <job_323971884>   Collecting pandas==1.3.2
updater | <job_323971884>     Using cached pandas-1.3.2.tar.gz
updater | <job_323971884>     Preparing metadata (pyproject.toml): started
updater | <job_323971884>     Preparing metadata (pyproject.toml): finished with status 'error'
updater | <job_323971884>     ERROR: Command errored out with exit status 1:
updater | <job_323971884>      command: /usr/local/.pyenv/versions/3.10.3/bin/python3.10 /usr/local/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmplvllue7_
updater | <job_323971884>          cwd: /tmp/pip-resolver-7futzml1/pandas
updater | <job_323971884>     Complete output (16 lines):
updater | <job_323971884>     Traceback (most recent call last):
updater | <job_323971884>       File "/usr/local/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
updater | <job_323971884>         main()
updater | <job_323971884>       File "/usr/local/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
updater | <job_323971884>         json_out['return_val'] = hook(**hook_input['kwargs'])
updater | <job_323971884>       File "/usr/local/.pyenv/versions/3.10.3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
updater | <job_323971884>         return hook(metadata_directory, config_settings)
updater | <job_323971884>       File "/usr/local/.pyenv/versions/3.10.3/lib/python3.10/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
updater | <job_323971884>         self.run_setup()
updater | <job_323971884>       File "/usr/local/.pyenv/versions/3.10.3/lib/python3.10/site-packages/setuptools/build_meta.py", line 258, in run_setup
updater | <job_323971884>         super(_BuildMetaLegacyBackend,
updater | <job_323971884>       File "/usr/local/.pyenv/versions/3.10.3/lib/python3.10/site-packages/setuptools/build_meta.py", line 150, in run_setup
updater | <job_323971884>         exec(compile(code, __file__, 'exec'), locals())
updater | <job_323971884>       File "setup.py", line 18, in <module>
updater | <job_323971884>         import numpy
updater | <job_323971884>     ModuleNotFoundError: No module named 'numpy'
```

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**
