### ISSUE TITLE
Allow multiple Dependabots per week, on specified days

### ISSUE THREAD

**Issue by tilo** [dependabot/dependabot-core#4914]
Allow multiple Dependabots per week

```
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/" 
    schedule:
      interval: "weekly"
      days: "tuesday, thursday"
      time: "07:00"
 ```
