### ISSUE TITLE
Failure to update terraform provider when version number in registry.terraform.io contains build metadata (X.X.X+Y)

### ISSUE THREAD

**Issue by robbruce** [dependabot/dependabot-core#4927]
**Package ecosystem**
terraform
**Package manager version**
n/a
**Language version**
1.1
**Manifest location and content prior to update**

`terraform.tf`

```hcl
terraform {
  required_version = ">= 1.1.0"

  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = ">= 0.28.8"
    }

    aws = {
      source                = "hashicorp/aws"
      version               = ">= 4.4.0"
      configuration_aliases = [aws.global]
    }
  }

  experiments = [module_variable_optional_attrs]
}
```

**dependabot.yml content**

```yaml
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
```

**Updated dependency**

N/A

**What you expected to see, versus what you actually saw**

Dependabot errors trying to parse an old version of https://registry.terraform.io/providers/chanzuckerberg/snowflake, version 0.13.0+b2a3596

```
updater | ERROR <job_329871097> Error processing chanzuckerberg/snowflake (ArgumentError)
updater | ERROR <job_329871097> Malformed version number string 0.13.0+b2a3596
updater | ERROR <job_329871097> /usr/local/lib/site_ruby/2.7.0/rubygems/version.rb:214:in `initialize'
updater | ERROR <job_329871097> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.180.2/lib/dependabot/terraform/version.rb:14:in `initialize'
updater | ERROR <job_329871097> /usr/local/lib/site_ruby/2.7.0/rubygems/version.rb:203:in `new'
updater | ERROR <job_329871097> /usr/local/lib/site_ruby/2.7.0/rubygems/version.rb:203:in `new'
```

Expect not see an error

**Native package manager behavior**
N/A

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

`terraform.tf`

```hcl
terraform {
  required_version = ">= 1.1.0"

  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = ">= 0.28.8"
    }
  }
}
```

**Comment by varunkvv** [comment]
Is there a workaround for this? Would it be possible to use the [`ignore` ](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) condition to ignore versions that have the metadata so that the check goes through?

**Comment by robbruce** [comment]
@varunkvv - I don't think so, I just tried updating the dependabot config to

```yaml
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "chanzuckerberg/snowflake"
        versions:
          - "0.13.2-pre+4d09e5e"
          - "0.13.0+5f54964"
          - "0.13.0+b2a3596"
```

which errored in 

> Dependabot encountered the following error when parsing your .github/dependabot.yml:
>
>```
> The property '#/updates/0/ignore/0/versions' includes invalid version requirements for a terraform ignore condition
> ```
>Please update the config file to conform with Dependabot's specification.

I have also tried using a valid range expression

```
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "chanzuckerberg/snowflake"
        versions:
          - "~> 0.13"
```

but the same error occurs 

```
updater | ERROR <job_361616149> Malformed version number string 0.13.0+b2a3596
```

I'll reach out to the chanzuckerberg/snowflake devs to see if they can remove them as they are quite old
