### ISSUE TITLE
Dependabot ignores "pull-request-branch-name.separator" option

### ISSUE THREAD

**Issue by bm-klara** [dependabot/dependabot-core#4940]
Dependabot began to ignore `pull-request-branch-name.separator` option from YML settings.

Details:
- Dependabot  YML file in my repo was not touched last few months 
- newly created Pull Request has the wrong branch name separator
- branch name separator option is configured according to the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#insecure-external-code-execution)
Here is my `.github/dependabot.yml` file content:
```
version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Berlin
  pull-request-branch-name:
    separator: "-"
  target-branch: dependency-updates
```

Newly created PR with unexpected branch name: (separated by `/`):
<img width="700" alt="Screenshot 2022-03-31 at 12 53 15" src="https://user-images.githubusercontent.com/97594803/161029122-bcbffccb-328f-4453-82fa-094695c01c98.png">

Example of existing PR with expected branch name: (separated by `-`), created one week ago:
<img width="730" alt="Screenshot 2022-03-31 at 12 51 12" src="https://user-images.githubusercontent.com/97594803/161028352-108504dc-e236-4b05-bf18-1c77a5a65776.png">

**Comment by qbiqing** [comment]
Any update on this? Also encountered the same issue

**Comment by brandonfl** [comment]
Same here, it seems that it's a recent version of Dependabot that break the separator since previously it was working but now it's not working anymore

**Comment by mctofu** [comment]
:wave: @bm-klara, the affected PR looks to have been created as part of a security update. Security updates will always target the default branch and your branch separator config only applies to the `dependency-updates` branch.

There's two options here:
1. [Disable security updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#managing-dependabot-security-updates-for-your-repositories) so all your update PRs will go through your regular version update flow.
2. [Customize](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file) the branch separator for security updates. You'll need to add an additional ecosystem config to your `dependabot.yml` which applies to the default branch (omit) but disables version updates.
```
version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Berlin
  pull-request-branch-name:
    separator: "-"
  target-branch: dependency-updates
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  # Disable version updates
  open-pull-requests-limit: 0
```
