### ISSUE TITLE
Dependabot ignore message appeared unexpectedly 

### ISSUE THREAD

**Issue by cyrorama** [dependabot/dependabot-core#4941]
**Package ecosystem**: Bundler
**Package manager version**: 2.2.1

**Language version**: Ruby 2.7.2

**Manifest location and content prior to update**

- /Gemfile
- /package.json

**dependabot.yml content**
```yml
version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
  - Needs QA
  allow:
  - dependency-type: direct
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
  - Needs QA
  allow:
  - dependency-type: direct
- package-ecosystem: bundler
  directory: "/.overcommit"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  allow:
  # Allow indirect dependencies (via `all`) here, because we'll auto-merge all
  # of these PRs by using the `development-dependencies` label below in
  # `.github/workflows/dependabot-prs.yml`. We do not allow indirect dependency
  # PRs for other types of dependencies because they are noisy and hard to
  # manually review, and because Dependabot is not currently able to indicate
  # when an indirect dependency is only used in development
  # (see: https://github.com/dependabot/fetch-metadata/issues/43).
  - dependency-type: all
  labels:
  - dependencies
  - Needs QA
  - development-dependencies
```

**Updated dependency**: Bump @babel/runtime from 7.17.2 to 7.17.8

**What you expected to see, versus what you actually saw**
I expected to not see any additional messages from Dependabot. My typical workflow when reviewing dependabots is to comment with what I did to review (e.g. "Looked at the update, compared the diffs, everything looks good") and then merge into our branch. 

I commented on the branch and then merged. I ended up seeing the following message appear from dependabot:

> OK, I won't notify you again about this release, but will get in touch when a new version is available. If you'd rather skip all updates until the next major or minor version, let me know by commenting @dependabot ignore this major version or @dependabot ignore this minor version. You can also ignore all major, minor, or patch releases for a dependency by adding an [ignore condition](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#ignore) with the desired update_types to your config file.

> If you change your mind, just re-open this PR and I'll resolve any conflicts on it.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**
