### ISSUE TITLE
looping in script to reduce length/size of file 

### ISSUE THREAD

**Issue by bruno-salapic** [dependabot/dependabot-core#4970]
Currently the script is very bare-bones, if I have multiple cs projects in a folder I would like to scan over, currently, i would have to copy-paste the same code over and over and change a single world in the directory parameter.

if we could implement some type of looping structure (brainstorming idea below) like 
Ex
```
version: 2

parameters:
  - name: folders
    type: string
    default:
      - "Proj1"
      - "Proj2"
      - "Proj3"
      - "Proj4"
      - "Proj5"
      - "Proj6"
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/SomeFolderNameOtherThenTheOneBelow/SomeSingleProjectIWantToScanHere" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
  - ${{ each folder in parameters.folders }}:
    - package-ecosystem: "nuget" # See documentation for possible values
      directory: "/SomeFolderNameIWantToScanMultiple/${{ folder }}/" # Location of package manifests
      schedule:
        interval: "daily"
      open-pull-requests-limit: 1
```
