### ISSUE TITLE
dependabot.yml contain invalid details with Dependabot secrets

### ISSUE THREAD

**Issue by softwaredevelop** [dependabot/dependabot-core#5006]
**Package ecosystem**

docker, github-actions

**Package manager version**

latest

**dependabot.yml content**

```yaml
---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: ${{secrets.TIMEZONE}}
    labels:
      - "docker dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "friday"
      time: "00:00"
      timezone: ${{secrets.TIMEZONE}}
    labels:
      - "github-actions dependencies"
```

**What you expected to see, versus what you actually saw**

"Your .github/dependabot.yml contained invalid details"

"Dependabot encountered the following error when parsing your .github/dependabot.yml:"

```
The property '#/updates/0/schedule/timezone' value "${{secrets.TIMEZONE}}" is not a valid timezone.
The property '#/updates/1/schedule/timezone' value "${{secrets.TIMEZONE}}" is not a valid timezone.

```

**Images of the diff or a link to the PR, issue or logs**

Insight/Dependency graph/Dependabot:

![dependency_graph](https://user-images.githubusercontent.com/61334390/163603974-f68a2640-cd0f-44c1-979e-027df801b907.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**

Add a repository secret for Dependabot Settings/Secrets/Dependabot/New repository secret

New repository secret Name: TIMEZONE

New repository secret Value: Europe/Berlin
