### ISSUE TITLE
Dependabot not detecting the latest version of a Github action

### ISSUE THREAD

**Issue by tyrann0us** [dependabot/dependabot-core#5017]
**Package ecosystem**
* github-actions

**Manifest location and content before the Dependabot update**
* e.g. https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/assets-compilation.yml#L64-L67

**dependabot.yml content**
```yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
```

**Updated dependency**
* nothing was updated

**What you expected to see, versus what you actually saw**
The workflow references the [`ramsey/composer-install`](https://github.com/ramsey/composer-install) action like so:
```yml
        uses: ramsey/composer-install@v1
```

In the Dependabot [logs](https://github.com/inpsyde/reusable-workflows/network/updates/346693526) I see:
```
updater | INFO <job_346693526> Checking if ramsey/composer-install 1 needs updating
  proxy | 2022/04/14 20:12:36 [044] GET https://github.com:443/ramsey/composer-install.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 20:12:36 [044] * authenticating git server request (host: github.com)
  proxy | 2022/04/14 20:12:36 [044] 200 https://github.com:443/ramsey/composer-install.git/info/refs?service=git-upload-pack
updater | INFO <job_346693526> Latest version is 994bb194a4fefcf39449ccf0f7766a4318f1ac76
updater | INFO <job_346693526> No update needed for ramsey/composer-install 1
```

There are a couple of things off:
* The latest version is `v2` (or to be correct [`v2.1.0`](https://github.com/ramsey/composer-install/releases/tag/2.1.0) at the time of writing)
* The latest version's commit hash is [`f680dac46551dffb2234a240d65ae806c2999dd6`](https://github.com/ramsey/composer-install/commit/f680dac46551dffb2234a240d65ae806c2999dd6)
* The mentioned commit hash [`994bb194a4fefcf39449ccf0f7766a4318f1ac76`](https://github.com/ramsey/composer-install/commit/994bb194a4fefcf39449ccf0f7766a4318f1ac76) is the last commit on the [`v1`](https://github.com/ramsey/composer-install/commits/v1) _branch_
* But it's actually part of the [`v2`](https://github.com/ramsey/composer-install/compare/1.3.0...2.0.0) _tag_

I would expect Dependabot to create a PR and update this action to `v2`.

**🕹 Bonus points: Smallest manifest that reproduces the issue**
```yml
name: Test Dependabot update
on:
  workflow_dispatch:
jobs:
  test-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: ramsey/composer-install@v1
```
(Untested)

**Notes**
This is a follow-up of https://github.com/dependabot/dependabot-core/issues/4834#issuecomment-1098857961.
CC @mctofu, @greysteil, @jurre, @jakecoffman
