### ISSUE TITLE
Dependabot deleted a golang dependency instead of upgrading it

### ISSUE THREAD

**Issue by davidsbond** [dependabot/dependabot-core#5074]
**Package ecosystem**
go modules

**Package manager version**
1.18

**Language version**
1.18

**Manifest location and content before the Dependabot update**
https://github.com/davidsbond/arrebato/blob/master/tools/go.mod

**dependabot.yml content**

```yaml
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
```

**Updated dependency**
https://github.com/anchore/syft

**What you expected to see, versus what you actually saw**
The dependency would be upgraded, not completely removed from the `go.mod` file.

**Native package manager behavior**
Using `go get -u ./...` the version is upgraded as expected

**Images of the diff or a link to the PR, issue, or logs**
https://github.com/davidsbond/arrebato/pull/80
