### ISSUE TITLE
Dependabot shows npm errors when I only configure pip ecosystem

### ISSUE THREAD

**Issue by tutuca** [dependabot/dependabot-core#5077]
I have a repository that is showing npm security advisories from dependabot, even though I only have the "pip" ecosystem configured:

```
version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/src/" # Location of package manifests
    schedule:
      interval: "weekly"
```

My npm packages are only used at build time, and not deployed. But looks like dependabot sees them because they are in the src/static directory.

I haven't found documentation on this particular issue.

Has anyone found the same situation? How did you solve it?
