### ISSUE TITLE
outdated Docker pinned tag not detected

### ISSUE THREAD

**Issue by isaacl** [dependabot/dependabot-core#5090]
I've setup dependabot on a github repo, and even though Actions show it's running, it isn't issuing pull requests to update this outdated pinned tag.  (the tag is currently up to date, but wasn't for a month with no dependabot PR issued)

/Dockerfile

```
ARG BASE_REPO=gradescope/auto-builds
ARG TAG=latest@sha256:39dd59d2a6722baae06d9746dd6edf30acb4e6b195f1701f3f4238574fac1e34

FROM ${BASE_REPO}:${TAG}

...
```

/.github/dependabot.yml
```yml
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
```
