### ISSUE TITLE
Error: Dependabot can't parse your package-lock.json

### ISSUE THREAD

**Issue by jlowcs** [dependabot/dependabot-core#5099]
**Package ecosystem**
npm
**Package manager version**
npm 8.1.2
**Language version**
node 16.13.2
**Manifest location and content before the Dependabot update**
`/package.json` contains private dependencies
**dependabot.yml content**
```
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.ACCESS_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - npm-github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
```
**What you expected to see, versus what you actually saw**
Before recently (2 days at max), dependabot was running properly.
But then, it started failing in some of our repositories that have private dependencies.
![image](https://user-images.githubusercontent.com/3777724/166944832-cab63823-9154-468a-9808-6ab2a4276b8d.png)
