### ISSUE TITLE
Error: Dependabot couldn't fetch all your path-based dependencies

### ISSUE THREAD

**Issue by jlowcs** [dependabot/dependabot-core#5100]
**Package ecosystem**
npm
**Package manager version**
npm 8.1.2
**Language version**
node 16.13.2
**Manifest location and content before the Dependabot update**
`/package.json` contains private dependencies and a path-based dependency (`config/lint-rules/index.js` does exist):
```
  "eslint-plugin-internal-rules": "file:./config/lint-rules",
```
**dependabot.yml content**
```
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.ACCESS_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - npm-github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
```
**What you expected to see, versus what you actually saw**
Before recently (2 days at max), dependabot was running properly.
But then, it started failing in some of our private repositories that have private dependencies and a path-based dependency.
![image](https://user-images.githubusercontent.com/3777724/166945110-995d639f-74ec-4e90-ad6d-4cfe3a9205d4.png)
