### ISSUE TITLE
Dependabot failing to ignore deps having a property that cannot be parsed properly

### ISSUE THREAD

**Issue by vmassol** [dependabot/dependabot-core#5111]
This is [our `dependabot.yml` file](https://github.com/xwiki/xwiki-rendering/blob/master/.github/dependabot.yml):

```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore XWiki dependencies since we always keep them up to date and Dependabot has problems with maven properties
      # defined in parent poms.
      - dependency-name: "org.xwiki.*"
    open-pull-requests-limit: 15
```

Notice the `ignore` used. 

When it's executed, it [fails with `Property not found: commons.version`](https://github.com/xwiki/xwiki-rendering/network/updates/362482346).

All our deps using `commons.version` have a groupid starting with `org.xwiki.`. For example:

```
          <dependency>
            <groupId>org.xwiki.commons</groupId>
            <artifactId>xwiki-commons-tool-test-simple</artifactId>
            <version>${commons.version}</version>
          </dependency>
```

It's as if the parsing was done before the ignore was used., could that be?

Thanks
