### ISSUE TITLE
Dependabot PRs are not getting `major/minor/patch` labels 

### ISSUE THREAD

**Issue by sheenamt** [dependabot/dependabot-core#5125]
**Package ecosystem**
terraform
**Package manager version**
n/a
**Language version**
n/a
**dependabot.yml content**

My dependabot.yml file looks like this: 
```
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/transcom-gov-dev/bootstrap"
    schedule:
      interval: "weekly"
      day: "sunday"
```
Note I ran this as a test and it initially worked:
```
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/transcom-gov-dev/admin-global"
    schedule:
      day: "tuesday"
      time: "22:30"
```

**What you expected to see, versus what you actually saw**
Per closed issue [#134](https://github.com/dependabot/feedback/issues/134), if the repo has the `major`, `minor` and `patch` labels, dependabot will add these (in addition to `dependencies`) automatically. I was able to produce this outcome in a test, but now that I have it setup on a weekly schedule it is not pulling in the labels other than `dependencies`. I have double checked that the `major/minor/patch` labels are in the repo and do not have typos or extra whitespaces. 

**Images of the diff or a link to the PR, issue, or logs**
My test worked: 
![Screen Shot 2022-05-10 at 1 25 34 PM](https://user-images.githubusercontent.com/674486/167715827-ebc61ba9-6b63-4c6e-98bc-970f5be4058a.png)

But then once I let it run on a weekly schedule, it does not add the other labels: 
![Screen Shot 2022-05-10 at 1 26 13 PM](https://user-images.githubusercontent.com/674486/167715911-222da8c7-5c78-4470-b000-876ba8aea5c6.png)
