### ISSUE TITLE
Dependabot raises RuntimeError instead of opening PR for new version 

### ISSUE THREAD

**Issue by AtzeDeVries** [dependabot/dependabot-core#5128]
**Package ecosystem**
terraform
**Package manager version**
1.x
**Language version**
1.x
**Manifest location and content before the Dependabot update**
reference to a private terraform module
**dependabot.yml content**
```yaml
---
version: 2

registries:
  coop-terraform:
    type: terraform-registry
    url: https://terraform.coop.no
    token: ${{ secrets.TFE_TOKEN }}
  coop-ghcr:
    type: docker-registry
    url: ghcr.io
    username: CoopGithubServiceaccount
    password: ${{ secrets.DEPENDABOT_GHCR_PULL }}

updates:
  - package-ecosystem: "terraform"
    directory: "/azure"
    registries:
      - coop-terraform
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "terraform"
    directory: "/management"
    registries:
      - coop-terraform
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "terraform"
    directory: "/projects"
    registries:
      - coop-terraform
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "terraform"
    directory: "/sandboxes"
    registries:
      - coop-terraform
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "terraform"
    directory: "/teams"
    registries:
      - coop-terraform
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "terraform"
    directory: "/tfe-workspaces"
    registries:
      - coop-terraform
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "docker"
    directory: "/docker-compose"
    registries:
      - coop-ghcr
    schedule:
      interval: "daily"
```
**Updated dependency**
from 0.8.0 to 1.0.5 (from old to new version model
**What you expected to see, versus what you actually saw**
Expected: A PR with an update for the new version
Actually: Dependabot throws an error: 
```
updater | ERROR <job_362442582> Error processing coopnorge/repos/github (RuntimeError)
updater | ERROR <job_362442582> Content didn't change!
```
**Native package manager behavior**
it will just update, this error above is from dependabot code [ref](https://github.com/dependabot/dependabot-core/blob/main/terraform/lib/dependabot/terraform/file_updater.rb#L30), not terraform
For me, the question i, why is this `raise` even there, why should it case about the non diff. 
**Images of the diff or a link to the PR, issue, or logs**
```
https://terraform.coop.no:443/api/registry/v1/modules/coopnorge/repos/github/versions
  proxy | 2022/05/10 16:44:57 [053] * authenticating terraform registry request (host: terraform.coop.no)
  proxy | 2022/05/10 16:44:57 [053] 200 https://terraform.coop.no:443/api/registry/v1/modules/coopnorge/repos/github/versions
updater | INFO <job_362442582> Latest version is 1.8.0
updater | INFO <job_362442582> Requirements to unlock own
updater | INFO <job_362442582> Requirements update strategy 
updater | INFO <job_362442582> Updating coopnorge/repos/github from 1.7.0 to 1.8.0
updater | I, [2022-05-10T16:44:57.967954 #7]  INFO -- sentry: ** [Raven] Sending event ae837566be5549c0ae3582df2da0fecf to Sentry
  proxy | 2022/05/10 16:44:58 [055] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/05/10 16:44:58 [055] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_362442582> Error processing coopnorge/repos/github (RuntimeError)
updater | ERROR <job_362442582> Content didn't change!
updater | ERROR <job_362442582> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.185.0/lib/dependabot/terraform/file_updater.rb:30:in `block in updated_dependency_files'
```

Diff between 1.7.0 and 1.8.0 is
```shell
git diff 1.7.0 1.8.0
diff --git a/variables.tf b/variables.tf
index db45747..7cef4e4 100644
--- a/variables.tf
+++ b/variables.tf
@@ -159,7 +159,7 @@ variable "writeback_installation_id" {

 variable "allow_auto_merge" {
   type        = bool
-  default     = false
+  default     = true
   description = "Allow pull requests to auto merge when requirements are met."
 }
```
**🕹 Bonus points: Smallest manifest that reproduces the issue**

The repo (check also dependabot config) contains multiple directories, but this module is only used in the projects directory.
