### ISSUE TITLE
Support wildcard for actions packages

### ISSUE THREAD

**Issue by fmeriaux** [dependabot/dependabot-core#5137]
Actually to update composite actions in a mono-repo, we have to declare something like:

```yaml
version: 2
updates:
  # Maintain dependencies for GitHub Actions (/.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/<my-custom-action-A>"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/<my-custom-action-B>"
    schedule:
      interval: "daily"
```

After some discussions (cf: https://github.com/dependabot/dependabot-core/issues/4178#issuecomment-1118527672), I think it could be interesting to manage wildcards for this kind of use.

```yaml
version: 2
updates:
  # Maintain dependencies for GitHub Actions (/.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/actions/**"
    schedule:
      interval: "daily"
```
