### ISSUE TITLE
Poetry tilde dependence transforming to not tilde

### ISSUE THREAD

**Issue by PerchunPak** [dependabot/dependabot-core#5141]
**Package ecosystem**

PiP, Poetry
**Package manager version**

poetry>=1.0.0
**Language version**

Python ^3.8
**Manifest location and content before the Dependabot update**
pyproject.toml
```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
filelock = "~3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**What you expected to see, versus what you actually saw**
`filelock = "~3.4"` transformed to `filelock = ">=3.4.0,<3.6.0"` instead of `filelock = "~3.5"`

**Native package manager behavior**
`poetry` doesn't update `pyproject.toml` automatically, I using dependabot for this.
