### ISSUE TITLE
workaround: Dependabot PR checks fail, can't find repository for required modules

### ISSUE THREAD

**Issue by sbe-arg** [dependabot/dependabot-core#5146]
Seeking advice.
PR by dependabot with tests that require cloning a repo, :bangbang: fail with repository not found.
```
Run pip3 install -r requirements-dev.txt && pytest -v
Collecting git+https://:****@github.com/org/repo-custom.git@v0.17.0 (from -r requirements.txt (line 1))
  Cloning https://:****@github.com/org/repo-custom.git (to revision v0.17.0) to /tmp/pip-req-build-kgj37xed
  Running command git clone --filter=blob:none --quiet 'https://:****@github.com/org/repo-custom.git' /tmp/pip-req-build-kgj37xed
  remote: Repository not found.
  fatal: Authentication failed for 'https://github.com/org/repo-custom.git/'
  error: subprocess-exited-with-error
```

PRs open by humans :rocket:  succed.

```
Collecting ***github.com/org/repo-custom.git@v0.17.0 (from -r requirements.txt (line 1))
  Cloning ***github.com/org/repo-custom.git (to revision v0.17.0) to /tmp/pip-req-build-ap_r78op
  Running command git clone --filter=blob:none --quiet '***github.com/org/repo-custom.git' /tmp/pip-req-build-ap_r78op
  Running command git checkout -q 91298dfff[9](https://github.com/org/therepowheredependabotpr/runs/12345678?check_suite_focus=true#step:4:9)ldkjfldkfjlkdjfkldjfk2994355
  Resolved ***github.com/org/repo-custom.git to commit
```
Tests workflow.

```
name: ci-autotests

on:

  push:
    branches-ignore:
      - master

env:
  GITHUB_AUTH: ${{ secrets.TOKEN }}:x-oauth-basic

jobs:

  tests:

    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9','3.10']
        node: ['14','16']

    steps:
      - name: checkout-code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: python-${{ matrix.python }}
        if: hashFiles('**/*.py') != ''
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: python-${{ matrix.python }}-tests
        if: hashFiles('requirements-dev.txt') != '' && hashFiles('**/*.py') != ''
        run: pip3 install -r requirements-dev.txt && pytest -v
```

**Package ecosystem**

**Package manager version**

**Language version**

**Manifest location and content before the Dependabot update**

**dependabot.yml content**

**Updated dependency**

**What you expected to see, versus what you actually saw**

**Native package manager behavior**

**Images of the diff or a link to the PR, issue, or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**
