### ISSUE TITLE
Dependabot update only first terraform dependency in a single file

### ISSUE THREAD

**Issue by andrewozh** [dependabot/dependabot-core#5150]
Terraform
If there is multiple dependencies located in a single file dependabot will update only first one!

I reproduced a problem here (Check the Pull Requests ):
https://github.com/andrewozh/dependabot-bug-check

**Example:**

Here's a fake .tf file with a two modules! 
0.42.1 version is available here

```
module "first-dep" {
  source  = "cloudposse/elasticache-redis/aws"
  version = "0.42.0"

  name = "it supposed to be updated by dependabot"
}

module "second-dep" {
  source  = "cloudposse/elasticache-redis/aws"
  version = "0.42.0"

  name = "it supposed not to be updated by dependabot"

}
```

I use github-native dependabot, here's my `.github/dependabot.yaml`

```
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
```

**Expected:**

New version of dependency causes dependabot to create a PRs on updating all dependencies, no matter they located in a single file or not

**Reality:**

Got PR only for first dependency in a file
