### ISSUE TITLE
Dependabot not updating the gradle dependencies

### ISSUE THREAD

**Issue by abhiwatt** [dependabot/dependabot-core#5260]
I have an Android module called "dependencies" in my app. That's how the Gradle file looks like. 

<img width="1741" alt="Screen Shot 2022-06-14 at 9 59 36 AM" src="https://user-images.githubusercontent.com/92097193/173582954-555fecba-3c04-4f7d-92a8-dbc37a1cdeb1.png">

```
dependencies {
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.6.0'
    implementation 'com.google.android.exoplayer:exoplayer:2.17.0'
    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
}
```

and that's how my `dependabot.yml` looks like 

```
version: 2
updates:
# Updates for Gradle dependencies used in the app      
    - package-ecosystem: gradle
      directory: "/dependencies/"
      schedule:
        interval: "daily"
      open-pull-requests-limit: 10
```

All the dependencies above have a higher version available but somehow the dependabot, is only creating the pull request for `testImplementation 'junit:junit:4.13.1'` and not for any other dependency. What's wrong with my setup here.

  [1]: https://i.stack.imgur.com/jBpRB.png
