### ISSUE TITLE
Dependabot `yarn.lock` YAML is invalid.

### ISSUE THREAD

**Issue by jbosse** [dependabot/dependabot-core#5275]
**Package ecosystem**
bundler

**Package manager version**
bundler 2.3.5
yarn 3.1.1

**Language version**
ruby 3.1
node 16.14.0

**Manifest location and content before the Dependabot update**
/Gemfile
/package.json

**dependabot.yml content**
```yml
version: 2
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 25
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "rails"
        update-types: ["version-update:semver-major"]
```

**Updated dependency**
Bump sass-loader from 12.6.0 to 13.0.0

**What you expected to see, versus what you actually saw**
Expected: Passing tests in Travis

Actual: `YAMLException: bad indentation of a mapping entry at line 4, column 15:`

**Native package manager behavior**
Locally yarn generates a valid lock file

**Images of the diff or a link to the PR, issue, or logs**
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/119121/174079652-9a9d56f3-a5b9-46ac-b35c-4020cf4436aa.png">

The issue seems to be that the Dependabot generated lock file is missing colons for `version` and `resolution`.
