### ISSUE TITLE
Pull request named as patch but package.json was updated to major version

### ISSUE THREAD

**Issue by jbosse** [dependabot/dependabot-core#5277]
**Package ecosystem**
bundler
yarn

**dependabot.yml content**
```yml
version: 2
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 25
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "rails"
        update-types: ["version-update:semver-major"]
```

**Updated dependency**
Bump @rails/ujs from 6.0.3 to 6.0.5

**What you expected to see, versus what you actually saw**
A bump from 6.0.3 to 6.0.5
but was bumped to 7.0.3

**Images of the diff or a link to the PR, issue, or logs**
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/119121/174119850-ccff71bb-2257-4ec7-863e-5a63049bc62c.png">

**Comment by jakecoffman** [comment]
You'll need another package-ecosystem to handle the yarn updates, and use a wildcard to catch everything under the @rails scope. Something like this:

```
version: 2
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 25
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "rails"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@rails/*"
        update-types: ["version-update:semver-major"]
```
