### ISSUE TITLE
Dependabot fails to parse a more complex poetry dependency

### ISSUE THREAD

**Issue by mvadari** [dependabot/dependabot-core#5363]
**Package ecosystem**
pip
**Package manager version**
poetry 
**Language version**
Python 3.7-3.10
**Manifest location and content before the Dependabot update**
https://github.com/XRPLF/xrpl-py/blob/master/pyproject.toml
**dependabot.yml content**
```
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "15:00"
  open-pull-requests-limit: 10
```
**What you expected to see, versus what you actually saw**
Dependabot hasn't been running at all on this repo, but it has on a repo with an identical dependabot.yml file. I went to Insights -> Dependency graph -> Dependabot and found this `Illformed requirement` error:
![image](https://user-images.githubusercontent.com/8029314/178514662-fd993341-e991-4c93-bd47-68b3fa47bd73.png)
I'm pretty sure it's coming from this part of the `pyproject.toml` file:
```
websockets = [
    {version = ">=9.0.1 <11.0", python = ">= 3.7, < 3.10"},
    {version = "^10.0", python = "^3.10"}
]
```
This is completely valid in poetry, but Dependabot is struggling.
**🕹 Bonus points: Smallest manifest that reproduces the issue**
See above.
