### ISSUE TITLE
Unknown option --resolver in pip-compile for python3.6 + piptools-6.4.0

### ISSUE THREAD

**Issue by JonathanRenon-EDB** [dependabot/dependabot-core#5405]
**Package ecosystem**

python
**Package manager version**

**Language version**
python3.6 
pip-compile 6.4.0

**dependabot.yml content**

```
version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependabot"
      - "pip dependencies"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
```
**What you expected to see, versus what you actually saw**

Using dependabot on github project fails due to pip-compile trying to use `--resolver` option which is not available in pip-compile 6.4.0, the latest vailable version for python3.6.
error log:
```
updater | ERROR <job_424387440> Error processing boto3 (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_424387440> Usage: pip-compile [OPTIONS] [SRC_FILES]...
updater | <job_424387440> Try 'pip-compile -h' for help.
updater | <job_424387440> 
updater | <job_424387440> Error: No such option: --resolver
```
**Images of the diff or a link to the PR, issue, or logs**

this commit seems to be the one adding the `--resolver` option https://github.com/dependabot/dependabot-core/commit/7969ac892231c5138d0697bc085b0bcd89292c35
**🕹 Bonus points: Smallest manifest that reproduces the issue**

any requirement file will do as long as you use python3.6 via `runtime.txt` file or other method to force python3.6 version.
