### ISSUE TITLE
Dependabot fails to identify latest tag from dependency after default branch changed

### ISSUE THREAD

**Issue by yubiuser** [dependabot/dependabot-core#5421]
**Package ecosystem**
github-actions
**dependabot.yml content**
```
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
```
**Updated dependency**
` uses: actions/checkout@v3.0.0`

**What you expected to see, versus what you actually saw**
Expect new PR for `actions/checkout@v3.0.2`
Observed: No update needed

Log:

```
updater | INFO <job_428051179> Checking if actions/checkout 3.0.0 needs updating
  proxy | 2022/07/26 08:08:48 [028] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/07/26 08:08:48 [028] * authenticating git server request (host: github.com)
  proxy | 2022/07/26 08:08:48 [028] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
updater | INFO <job_428051179> Latest version is 61b9e3751b92087fd0b06925ba6dd6314e06f089
updater | INFO <job_428051179> No update needed for actions/checkout 3.0.0

```

I'm using `dependabot` to update `github-actions`. One of those is https://github.com/actions/checkout. When specifying an "old" tag (v3.0.0) I expect dependabot to open a PR for the latest v3 versio (v3.0.2). See here for tags: https://github.com/actions/checkout/tags.

However, `dependabot` is referencing an "old" commit as `latest version`. This commit is the latest in their `master` branch (https://github.com/actions/checkout/commits/master), but they have changed to `main` as their default branch (https://github.com/actions/checkout/commits/main).
