### ISSUE TITLE
support `-compat` in gomod

### ISSUE THREAD

**Issue by localvar** [dependabot/dependabot-core#5463]
**Package ecosystem**
gomod

**Package manager version**
1.17

**Language version**
Go 1.17

**dependabot.yml content**
```yaml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
```

I'm a developer of https://github.com/megaease/easegress, last month, we add the `-compat=1.17` flag to the `go mod tidy` command in our make file (please refer [Module graph pruning](https://go.dev/ref/mod#graph-pruning) for details of this flag), as below:

```makefile
test:
	cd ${MKFILE_DIR}
	go mod tidy -compat=1.17
	git diff --exit-code go.mod go.sum
	go mod verify
	go test -v ${MKFILE_DIR}pkg/... ${TEST_FLAGS}
```

But we found all PRs created by dependabot this month failed to execute the `git diff` command above because dependabot hasn't used the `-compat=1.17` flag when creating the PRs, which results in a local modification after executing `go mod tidy -compat=1.17`.

The policy of our project is to support the latest two Go versions, so the go directive in `go.mod` is `go 1.17`.

**update(2022-08-08) :**

As Go 1.19 is released, we are now using `go 1.18` in our `go.mod`, and the `-compat=1.17` flag is removed. We are glad to see the issue disappears, because the documentation of the  `go mod tidy` command says: 

> By default, tidy acts as if the -compat flag were set to the version prior to the one indicated by the 'go' directive in the go.mod file.

But I still propose  Dependabot to support the `-compat` flag, as the Go team may add other possible values than `1.17` to it.
