### ISSUE TITLE
dependabot running for npm even when i disabled it

### ISSUE THREAD

**Issue by yashash1511** [dependabot/dependabot-core#5486]
**dependabot.yml content**
```
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
```

**What you expected to see, versus what you actually saw**
I updated the dependabot config yesterday to update gh-actions and removed npm but it still continues to make npm PR's

**Images of the diff or a link to the PR, issue, or logs**
![image](https://user-images.githubusercontent.com/89068816/183044258-8ba81946-0e12-44d3-a229-5d30bd396fb7.png)
https://github.com/blueedgetechno/win11React/pull/622
https://github.com/blueedgetechno/win11React/pull/623

#5112 #5160 i think dependabot is messed up for this repo issues with it have happened before
