### ISSUE TITLE
Increase character limit for `commit-message.prefix` to 50 characters

### ISSUE THREAD

**Issue by bogdannazarenko** [dependabot/dependabot-core#5553]
When trying to set prefix for Dependabot's commit message to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) we always run into character limit.

Example specifying **type(scope): message** is already 24 characters. This can easily be longer as some teams need to include a JIRA ticket (e.g `deps(myawesomeservice): SEC-000`) when working on a monorepo

```yaml
- package-ecosystem: "npm"
   commit-message:
      prefix: "deps(myawesomeservice): "
```
