### ISSUE TITLE
Dependabot is still using previous schedule interval after update

### ISSUE THREAD

**Issue by dduugg** [dependabot/dependabot-core#5619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

2.3.13

### Language version

Ruby >= 2.7.0

### Manifest location and content before the Dependabot update

https://github.com/dduugg/yard-sorbet/blob/main/Gemfile.lock
https://github.com/dduugg/yard-sorbet/blob/main/Gemfile
https://github.com/dduugg/yard-sorbet/blob/main/yard-sorbet.gemspec

### dependabot.yml content

https://github.com/dduugg/yard-sorbet/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

The dependabot schedule interval was changed from `"daily"` to `"weekly"` in this PR: https://github.com/dduugg/yard-sorbet/pull/122/files

However, we're still seeing dependabot open PRs daily: https://github.com/dduugg/yard-sorbet/pulls?q=is%3Apr+is%3Aclosed

### Images of the diff or a link to the PR, issue, or logs

https://github.com/dduugg/yard-sorbet/pull/122/files

### Smallest manifest that reproduces the issue

```yaml
---
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "automerge"
      - "dependencies"
```
