### ISSUE TITLE
Updates in projects with mixed versions

### ISSUE THREAD

**Issue by TomW-Skyline** [dependabot/dependabot-core#5633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### dependabot.yml content

```
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "nuget"
    directory: "/ProtocolEditor/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        # ignore all major updates
        update-types: ["version-update:semver-major"]
```

### Updated dependency

Microsoft.VSSDK.BuildTools

### What you expected to see, versus what you actually saw

When two projects use a different version (range) of a certain NuGet package, and one of the packages have an update available, a PR is opened that updates both projects.

Solution with two (csproj) projects that use a different version of a nuget:
- project A: NuGet x 1.0
- project B: NuGet x 2.0

Both ranges of the NuGet receive an update: 1.1 and 2.1

PR is opened that updates the projects as follows:
- project A: NuGet x 1.1
- project B: NuGet x 1.1

This is a problem for us because we develop a Visual Studio extension that targets two versions of Visual Studio. Each version has its own project. The problematic NuGet is Microsoft.VSSDK.BuildTools NuGet.
16.11.65 -> 16.11.67
17.3.2093 -> 17.3.2094

### Images of the diff or a link to the PR, issue, or logs

![image](https://user-images.githubusercontent.com/97225679/188890999-c8bc6fd4-102a-4eda-af01-5d17797879f9.png)
