### ISSUE TITLE
DependencyFileNotFound when using Directory.Packages.props without a project file

### ISSUE THREAD

**Issue by klemmchr** [dependabot/dependabot-core#5635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Manifest location and content before the Dependabot update

```
src/
├─ Backend/
│  ├─ Project1/
│  │  ├─ Project1.csproj
│  ├─ Project2/
│  │  ├─ Project2.csproj
│  ├─ Directory.Packages.props
├─ App/
├─ Solution.sln

```

### dependabot.yml content
```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: master
```

### What you expected to see, versus what you actually saw

I'm using Central Package Management where my `Directory.Build.Props` file is not placed along a solution file or project file. This file manages the package versions of multiple projects of the solution but not for all of them. Thus, it is placed in a subfolder underneath the solution file.

When execution dependabot with the provided configuration I get a `DependencyFileNotFound` exception. Upon review of the [code](https://github.com/dependabot/dependabot-core/blob/main/nuget/lib/dependabot/nuget/file_fetcher.rb#L39) it seems that a project file is required currently. This however is not needed when using central package versioning, dependabot should be able to run just against a plain `Directory.Build.Props` file.

### Smallest manifest that reproduces the issue

Repro can be found [here](https://github.com/klemmchr/dependabot-repro).
