### ISSUE TITLE
Dependabot registries url protocols

### ISSUE THREAD

**Issue by zma318** [dependabot/dependabot-core#5750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello, we want to add a artifactory registry within dependabot.yml with
`registries:
  coursera-artifactory:
    type: maven-repository
    url: ${{ secrets.ARTIFACTORY_HOST )}}
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_PASSWORD}}`
However, we would like to make this url configurable, right now this is giving me an error url is not in a proper format with `http` or `https`. 

I have searched the docs and only find there is one line [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-private-registries) mentioned we can use optional protocol to override the default restriction.

I tried to add `protocol` in the config as well, while it gave me `additional properties ["protocol"] outside of the schema when none are allowed`.

Is this feature supported, if so what is the proper format to set protocol? 

Thank you!

**Comment by jeffwidman** [comment]
We don't currently support templating values in the registry URL fields.

I'm curious of your use case? Are you trying to open source code that you normally use internally? Or something else?

**Comment by jeffwidman** [comment]
I can envision some realistic use cases for this beyond just a one-time migration... eg, for a templates repo inside a company, or if they want to only have to set the registry URL in one place and then pull it in multiple places in their code...

**Comment by VDuchauffour** [comment]
Any idea when this issues might be resolved ?
I guess this lack of templating is related to the fact that I can't use an URL as a dependabot secret ?
Currently this file works for me:
```yaml
registries:
  python-codeartifact:
    type: python-index
    url: ${{secrets.CODEARTIFACT_URL}}
    url: https://XXX/pypi/kinetix_rd/simple/
    token: ${{secrets.CODEARTIFACT_USERNAME}}:${{secrets.CODEARTIFACT_AUTH_TOKEN}}
    replaces-base: false
```
But I would like to do something like this:
```yaml
registries:
  python-codeartifact:
    type: python-index
    url: ${{secrets.CODEARTIFACT_URL}}
    # or this
    # url: https://${{ secrets.CODEARTIFACT_DOMAIN }}-${{ secrets.CODEARTIFACT_DOMAIN_OWNER }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/pypi/${{ secrets.CODEARTIFACT_REPOSITORY }}/simple/
    token: ${{secrets.CODEARTIFACT_USERNAME}}:${{secrets.CODEARTIFACT_AUTH_TOKEN}}
    replaces-base: false
```
Is possible to use secret for the url field ?
Thank you
