### ISSUE TITLE
branch namer sanitizes slashes in prefix

### ISSUE THREAD

**Issue by mikk150** [dependabot/dependabot-core#5795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

I would like to use [git-flow](https://danielkummer.github.io/git-flow-cheatsheet/) style branch names so for this I have
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "weekly"
      # Check for npm updates on Mondays
      day: "monday"
      time: "09:00"
    pull-request-branch-name:
      prefix: 'feature/dependabot'
```

but since branch namer sanitazes prefix part too, I cannot have slashes in my branch name

https://github.com/dependabot/dependabot-core/blob/6ba5296f550ade045187a1bd8425912faed8009b/common/lib/dependabot/pull_request_creator/branch_namer.rb#L43

**Comment by deivid-rodriguez** [comment]
Hi @mikk150, thanks for reaching out.

Which branch name is GitHub creating that you don't expect? Would you be able to share a public repository that reproduces your issue? Since the default separator is actually `/`, I wouldn't expect sanitization to have any bad effect on your use case.

**Comment by mikk150** [comment]
What I am actually trying to do is more like this

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "weekly"
      # Check for npm updates on Mondays
      day: "monday"
      time: "09:00"
    pull-request-branch-name:
      separator: _
      prefix: 'feature/dependabot'
```

So branch name would be `feature/dependabot_npm_and_yarn_babel_core-7.19.3`
