### ISSUE TITLE
Update container image references in GitHub Action workflows

### ISSUE THREAD

**Issue by lorengordon** [dependabot/dependabot-core#5819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I've used Dependabot to update the FROM argument in a Dockerfile, but now I'm starting to use images directly in GitHub Actions, which does not use a Dockerfile. I would still like Dependabot to update the image reference in the workflow file though. Is there a way to do this today? (I did search the docs and issues but couldn't find anything.)

See: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

Syntax in the workflow files looks like this:

```
name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
```
