### ISSUE TITLE
Support for Google Artifact Repository (docker registry) / GCP Workload Identity Federation

### ISSUE THREAD

**Issue by sebdoido** [dependabot/dependabot-core#5836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi!

any plan to add support for Google Artifact Repository (docker registry) ?

it could be great if we can rely on the same integration that we have in Github Action with a token generated through 
**GCP Workload Identity Federation work with Github Provider**

**Example for GithubAction**
```
- id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: access_token
          workload_identity_provider: xxx
          service_account: xxx

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
```

Thanks
