### ISSUE TITLE
Dependabot could not find newer node docker image

### ISSUE THREAD

**Issue by flaxel** [dependabot/dependabot-core#5861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Package manager version

8.1.2

### Language version

16

### Manifest location and content before the Dependabot update

Dockerfile

### dependabot.yml content

```yml
 - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Berlin"
    target-branch: "master"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    labels:
      - "docker dependency"
```

### Updated dependency

`node:16-alpine3.11` to `node:16-alpine3.15`

### What you expected to see, versus what you actually saw

Currently I see these logs in the run of dependabot. The result is that there is no change for the node image found. 
![image](https://user-images.githubusercontent.com/19373153/194821253-9e6625f5-5dbc-423b-99be-d012d85a875a.png)
I would expect that dependabot find the newer image version of the node image.
