### ISSUE TITLE
Rust: Cargo.toml discovery fails if in a workspace and said manifest is not a member but used in members with workspace dependencies

### ISSUE THREAD

**Issue by poliorcetics** [dependabot/dependabot-core#5864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

rust, cargo

### Package manager version

cargo 1.64.0+

### Language version

rust 1.64.0+

### Manifest location and content before the Dependabot update

The situation appeared after my PR https://github.com/dependabot/dependabot-core/pull/5794, and this use case is a little weird so I didn't think about it.

1) Have a Cargo workspace, e.g:

```
root/
- Cargo.toml (C1)
- crate_in_workspace/Cargo.toml (C2)
- crate_outside_workspace/Cargo.toml (C3)
```

```toml
# In (C1)
[workspace.package]
version  = "1.0.0"

[workspace]
members = [ "crate_in_workspace" ]

[workspace.dependencies]
crate_outside_workspace = { version = "1", path = "./crate_outside_workspace" }
```

```toml
# In (C2)
[package]
version.workspace = true

[dependencies]
crate_outside_workspace.workspace = true
```

### What you expected to see, versus what you actually saw

Dependabot will currently fail on the config presented earlier with the error that it cannot find `crate_outside_workspace/Cargo.toml`.

This happens because the `workspace.dependencies` table is not looked at by the file filter and I forgot to add it when adding the support for workspace dependencies in #5794.
