### ISSUE TITLE
Add support to env variable

### ISSUE THREAD

**Issue by yarinsa** [dependabot/dependabot-core#5870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

**My problem:** dependabot failing to access private npm registry. 
**The root cause:** I am relying on env variable on my yarnrc.  

My yarn.rc
```
npmAlwaysAuth: true

npmAuthIdent: ${JF_USER}:${JF_API_KEY}

npmRegistryServer: 'https://froggy.jfrog.io/artifactory/api/npm/fg-npm-repo/'
```

In my workflow I am making sure that those variable exist on the env. In depandbot run I cant do that. 

Although .yarnrc.yml is a Yarn2+ feature which is not officially supported it could still work analysing my package.json (I am getting security alerts).  

What I see in my logs:
```
updater | ERROR <job_481272521> Error processing nanoid (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_481272521> Usage Error: Environment variable not found (JF_USER) in /home/dependabot/dependabot-updater/repo/.yarnrc.yml (in /home/dependabot/dependabot-updater/repo/.yarnrc.yml)
updater | <job_481272521> 
updater | <job_481272521> Yarn Package Manager - 3.2.2
updater | <job_481272521> 
updater | <job_481272521>   $ yarn <command>
updater | <job_481272521> 
updater | <job_481272521> You can also print more details about any of these commands by calling them with 
updater | <job_481272521> the `-h,--help` flag right after the command name.
```

**Comment by jurre** [comment]
@yarinsa can you share your dependabot config file?

**Comment by jurre** [comment]
@pavera we may need to strip the `npmAuthIdent` out of the yarn config so the proxy can always take over?

**Comment by yarinsa** [comment]
@jurre Thank you for the quick answer! 

here is my config:
```

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    target-branch: 'main'
    schedule:
      interval: 'daily'
    registries:
      - npm-jfrog

registries:
  npm-jfrog:
    type: npm-registry
    url: [Redacted]
    username: ${{ secrets.JF_USER }}
    password: ${{ secrets.JF_PASSWORD }} # Must be an unencoded password

```

I had a similar issue when I was implementing my own actions. I have an action called "setup-yarn". 
And there I accept the creds as inputs. Then in my action I do 

```
        yarn config unset npmAuthIdent
        CREDS="$(echo -n '${{ inputs.artifactory_user }}:${{ inputs.artifactory_password }}'| base64)"
        yarn config set npmAuthIdent $(echo -n '${{ inputs.artifactory_user }}:${{ inputs.artifactory_password }}'| base64)
```
