### ISSUE TITLE
non-sense dependency updates

### ISSUE THREAD

**Issue by castamir** [dependabot/dependabot-core#5890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

1

### Language version

Nodejs 14

### dependabot.yml content

```yaml
version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com/
    token: ${{ secrets.GH_PACKAGES_RW_SECRET }}

updates:
  - package-ecosystem: 'npm' 
    directory: '/' 
    registries:
      - npm-github
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    labels:
      - 'dependencies'
      - 'untracked work'
    commit-message:
      prefix: 'chore'
      include: 'scope'
 ```

### What you expected to see, versus what you actually saw

PR title:
```
chore(deps): bump dd-trace from 0.31.4 to 3.5.0
```

yarn.lock changes:
```diff
lru-cache@^7.10.1:
-  version "7.10.1"
-  resolved "https://registry.yarnpkg.com/lru-cache/-/lru-cache-7.10.1.tgz#db577f42a94c168f676b638d15da8fb073448cab"
-  integrity sha512-BQuhQxPuRl79J5zSXRP+uNzPOyZw2oFI9JLRQ80XswSvg21KMKNtQza9eF42rfI/3Z40RvzBdXgziEkudzjo8A==
+  version "7.14.0"
+  resolved "https://registry.yarnpkg.com/lru-cache/-/lru-cache-7.14.0.tgz#21be64954a4680e303a09e9468f880b98a0b3c7f"
+  integrity sha512-EIRtP1GrSJny0dqb50QXRUNBxHJhcpxHC++M5tD7RYbvLLn5KVWKsbyswSSqDuU15UFi3bgTQIY8nhDMeF6aDQ==
```

### Images of the diff or a link to the PR, issue, or logs

<img width="2008" alt="image" src="https://user-images.githubusercontent.com/1245190/196036372-dce417c3-1c6f-4d71-a84a-6e44470854b0.png">
<img width="1998" alt="image" src="https://user-images.githubusercontent.com/1245190/196036395-6b7a373b-9a3e-41f5-a08a-ac5cb0aa0c47.png">
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1245190/196036611-dcadf514-6276-4a2a-a997-4d880a7c51f2.png">
