### ISSUE TITLE
Incorrect bundler updates after #5581

### ISSUE THREAD

**Issue by CvX** [dependabot/dependabot-core#5892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

2.3.5

### Language version

2.7.6

### Manifest location and content before the Dependabot update

/Gemfile

excerpt:
```
gem 'oj', '3.13.14'
gem 'sassc', '2.0.1', require: false
gem 'active_model_serializers', '~> 0.8.3'
```

### dependabot.yml content

excerpt:

```yml
- package-ecosystem: bundler
  versioning-strategy: lockfile-only
  allow:
    - dependency-type: direct
    - dependency-type: indirect
```

### Updated dependency

`sassc` updated from the locked version (2.0.1) to 2.4.0 https://github.com/discourse/discourse/pull/18617
`oj` updated from the locked version (3.13.14) to 3.13.21 https://github.com/discourse/discourse/pull/18614
`active_model_serializers` updated from the locked version (~> 0.8.3 that resolved to 0.8.4) to 0.10.13 https://github.com/discourse/discourse/pull/18610

### What you expected to see, versus what you actually saw

Before that PR (#5581) Dependabot was correctly ignoring those dependencies. The PRs it now creates update the lockfile versions agains what's in the Gemfile.
