### ISSUE TITLE
Dependabot cannot update to a non-vulnerable version

### ISSUE THREAD

**Issue by billinghamj** [dependabot/dependabot-core#5927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

Yarn 3.2.0

### Manifest location and content before the Dependabot update

[js/yarn.lock](https://github.com/wearemojo/mojo/blob/-/js/yarn.lock)

<img width="1512" alt="Screenshot 2022-10-19 at 18 51 44" src="https://user-images.githubusercontent.com/905772/196767385-1f61a734-7364-4ae8-982d-b69776381950.png">

### dependabot.yml content

```
version: 2

updates:
- package-ecosystem: npm
  directory: "/js"
  schedule:
    interval: daily
  ignore:
  # matched vaguely against Expo's dependency API
  # e.g. https://exp.host/--/api/v2/sdks/46.0.0/native-modules
  - dependency-name: "@react-native-async-storage/async-storage"
  - dependency-name: "@sentry/react-native"
  - dependency-name: "expo-*"
  - dependency-name: "lottie-react-native"
  - dependency-name: "react"
  - dependency-name: "react-dom"
  - dependency-name: "react-native"
  - dependency-name: "react-native-safe-area-context"
  - dependency-name: "react-native-screens"
  - dependency-name: "react-native-svg"
  - dependency-name: "react-native-web"
  - dependency-name: "react-native-webview"
  - dependency-name: "sentry-expo"
```

### Updated dependency

@xmldom/xmldom is currently on 0.7.5

It _should_ be updated to 0.7.6

### What you expected to see, versus what you actually saw

Dependabot should have opened a PR updating @xmldom/xmldom to 0.7.6

Instead, it claims it's not able to, but there's nothing preventing this in the required resolutions

<img width="931" alt="Screenshot 2022-10-19 at 18 55 04" src="https://user-images.githubusercontent.com/905772/196768023-af8de59f-102c-4438-9cbf-0c33cbafe766.png">

### Native package manager behavior

Running `yarn up -R @xmldom/xmldom` works great, no problem:

<img width="668" alt="Screenshot 2022-10-19 at 18 56 44" src="https://user-images.githubusercontent.com/905772/196768419-12ca6348-aa54-45d7-9996-8ea2edf1e896.png">

### Images of the diff or a link to the PR, issue, or logs

Private, but fine for GH staff to look at it:
- https://github.com/wearemojo/mojo/security/dependabot/101
- https://github.com/wearemojo/mojo/security/dependabot/101/update-logs/275815839

```
updater | INFO <job_487160402> Checking if @xmldom/xmldom 0.7.5 needs updating
  proxy | 2022/10/19 17:44:38 [016] GET https://registry.npmjs.org:443/@xmldom%2Fxmldom
  proxy | 2022/10/19 17:44:38 [016] 200 https://registry.npmjs.org:443/@xmldom%2Fxmldom
  proxy | 2022/10/19 17:44:38 [018] GET https://registry.npmjs.org:443/@xmldom%2Fxmldom/0.8.3
  proxy | 2022/10/19 17:44:38 [018] 200 https://registry.npmjs.org:443/@xmldom%2Fxmldom/0.8.3
  proxy | 2022/10/19 17:44:41 [058] GET https://registry.yarnpkg.com:443/@xmldom%2fxmldom
  proxy | 2022/10/19 17:44:41 [058] 200 https://registry.yarnpkg.com:443/@xmldom%2fxmldom
  proxy | 2022/10/19 17:45:02 [046] GET https://registry.yarnpkg.com:443/@xmldom%2fxmldom
  proxy | 2022/10/19 17:45:02 [046] 200 https://registry.yarnpkg.com:443/@xmldom%2fxmldom
  proxy | 2022/10/19 17:45:16 [247] GET https://registry.npmjs.org:443/@xmldom%2Fxmldom/0.7.6
  proxy | 2022/10/19 17:45:16 [247] 200 https://registry.npmjs.org:443/@xmldom%2Fxmldom/0.7.6
updater | INFO <job_487160402> The latest possible version of @xmldom/xmldom that can be installed is 0.7.5
```
