### ISSUE TITLE
Update tapioca definitions when updating gems

### ISSUE THREAD

**Issue by fcheung** [dependabot/dependabot-core#5962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I use sorbet in my rails applications, in conjunction with [tapioca](https://github.com/Shopify/tapioca). Amongst other things, tapioca generates rbi files for all the gems you use, so that sorbet is aware of them. A consequence of this is that when adding/updating gems you need to run

```
tapioca gem
```

to regenerate those rbi files as required.

Could dependabot do this for me whenever updating gems? Removing manual repetitive steps in updates is exactly what I look to dependabot for.

**Comment by jeffwidman** [comment]
👋 Hey there.

Totally valid request, but probably not something we'll do anytime soon. In the meantime, your best bet is to setup a GitHub action that watches for Dependabot PR's and then adds a follow-on commit running `tapioca gem`. Here's an example action to help you get started hacking: https://github.com/dependabot/fetch-metadata/ although 👈  is probably more complicated than what you're looking for so should be easy to strip it down to only what you need.

**Comment by fcheung** [comment]
Thanks - that works well enough. If anyone else runs into this, this workflow seems to work well enough for us:

```
```yaml
name: Dependabot Tapioca updates
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: read
jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
      - uses: actions/checkout@v3
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bundler' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: ruby/setup-ruby@v1
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bundler' }}
        with:
          ruby-version: '3.1.2'
          bundler-cache: true 
      - name: Tapioca update
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bundler' }}
        run: bin/tapioca gem
      - name: git update
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bundler' }}
        run: |
          git config --global user.name 'some user'
          git config --global user.email 'some-user@example.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add sorbet/rbi/gems
          git commit -m "updated tapioca definitions" sorbet/rbi/gems
          git push -u origin HEAD:${{ github.event.pull_request.head.ref }}
```
