### ISSUE TITLE
Dependabot corrupts `package-lock.json` when linking forked libraries as local git submodules

### ISSUE THREAD

**Issue by char0n** [dependabot/dependabot-core#5977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

8.11.0

### Language version

Nodejs@16.16.0

### Manifest location and content before the Dependabot update

https://github.com/swagger-api/swagger-editor/blob/2919f3d5b09fcfe46c29f8263075f265aae78116/package-lock.json

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3
    ignore:
      # node-fetch must be synced manually
      - dependency-name: "node-fetch"
      - dependency-name: "release-it"
      - dependency-name: "@release-it/conventional-changelog"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  ######################
  # SwaggerEditor@next #
  ######################

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    target-branch: "next"
    labels:
      - "swagger-editor@next"
      - "cat: dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3
    ignore:
      # do not update react-scripts as we use forked version of Create React App via git submodule
      - dependency-name: "create-react-app/packages/react-scripts"
      - dependency-name: "react-scripts"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    target-branch: "next"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    labels:
      - "swagger-editor@next"
      - "cat: dependencies"
      - "cat: docker"
      - "docker"

  - package-ecosystem: "github-actions"
    target-branch: "next"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "swagger-editor@next"
      - "cat: dependencies"
      - "github_actions"
```

### Updated dependency

@asyncapi/parser from 1.17.0 to 1.17.1

### What you expected to see, versus what you actually saw

I expected to see that dependabot updates @asyncapi/parser@1.17.0 to @asyncapi/parser@1.17.1.  but dependabot updates also our forked Create React App (specifically `react-scripts`). We use forked Create React App as a git submodule and use the npm local link to insert it into `devDependencies`.

```json
"react-scripts": "file:./create-react-app/packages/react-scripts",
```

This worked like a charm, but last week, dependabot started to issue all PRs in way that it corrupts the `package-lock.json` and npm is unable to install the packages. I've also added some ignores for dependabot but, it had no effect.

```yaml
    ignore:
      # do not update react-scripts as we use forked version of Create React App via git submodule
      - dependency-name: "create-react-app/packages/react-scripts"
      - dependency-name: "react-scripts"
```

![image](https://user-images.githubusercontent.com/193286/198026102-f7f35786-bf0a-4861-b3ee-0ded43bcab61.png)

### Native package manager behavior

By doing update locally, `react-scripts` is not updated in any way.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/swagger-api/swagger-editor/pull/3581
