### ISSUE TITLE
"@dependabot rebase" command recreates PR with new hash for gitsubmodule

### ISSUE THREAD

**Issue by sgarske** [dependabot/dependabot-core#5979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gitsubmodule

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "OurPrivateRepo"
```

### What you expected to see, versus what you actually saw

Using the above `dependabot.yml` we are correctly getting pull requests created to update the submodule to the latest hash of `main` in the specified submodule.  When a developer goes to merge the pull request, they would like to use `@dependabot rebase` first.  However, using that command seems to close the current PR and creates a new PR with a _new_ hash if the submodule has more commits on `main` since the original PR was created.  

We'd like to run our CI checks against a particular hash but then rebase the dependabot PR without picking up any new hashes in the submodule.  Is this already possible?  Bug?  I see some value in always trying to pick up the latest hash, but it wasn't what we were expecting to happen.
