### ISSUE TITLE
Workflows containing Jinja2 code result in dependabot parsing errors

### ISSUE THREAD

**Issue by martinm82** [dependabot/dependabot-core#5987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/{{cookiecutter.repo_name}}/.github/workflows"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

I am using cookiecutter templates that generate as well GitHub workflows that include some Jinja2 code. 

Now that https://github.com/dependabot/dependabot-core/pull/6189 has been implemented, dependabot started to parse the cookiecutter workflow templates but it results in failures:

```
Dependabot can't parse your quality.yml
Dependabot failed to update your dependencies because there was an error parsing the quality.yml found at /{{cookiecutter.repo_name}}/.github/workflows/quality.yml.

Dependabot encountered the following error:

Dependabot::DependencyFileNotParseable
[Learn more](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)
```

Example workflow:

```
name: Quality Checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  workflow_dispatch:

jobs:
  conventional-commit:
    name: Conventional Commit Check
    runs-on: ubuntu-latest
    steps:
      {%- if cookiecutter.release_tool | lower == "commisery" %}
      - uses: tomtom-international/commisery-action@v2
        with:
          token: {% raw %}${{ github.token }}{%- endraw %}
      {%- else %}
      - uses: amannn/action-semantic-pull-request@01d5fd8a8ebb9aafe902c40c53f0f4744f7381eb
        env:
          GITHUB_TOKEN: "{% raw %}${{ secrets.GITHUB_TOKEN }}{%- endraw %}"
      {%- endif %}
```

It seems that Jinja2 is supported but only for Python requirements files: https://github.com/dependabot/dependabot-core/pull/1537
