### ISSUE TITLE
yarn2 workspace monorepo: Can't handle `workspace:` dependencies.

### ISSUE THREAD

**Issue by fjakobs** [dependabot/dependabot-core#6092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

3.2.1

### Language version

Node.js 16.x

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/databricks-sdk-js"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@databricks/*"          
  - package-ecosystem: "npm"
    directory: "/packages/databricks-vscode"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@databricks/*"    
  - package-ecosystem: "npm"
    directory: "/packages/databricks-vscode-types"
    ignore:
      - dependency-name: "@databricks/*"    
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

I'm using the yarn workspace feature to manage a mono repo with several node.js packages. The different packages define dependencies to each other in the form of `workspace:` links:

`"@databricks/databricks-sdk": "workspace:^",`

Dependabot failes to resolve these dependencies and instead tries to look them up on npm, which results in the following error:

```
 Dependabot can't authenticate to a private package registry
The following private package registry was used and caused the update to fail: registry.npmjs.org.
```

![Screenshot 2022-11-09 at 15 08 22](https://user-images.githubusercontent.com/40952/200851767-b5f253cc-a067-47bf-83bd-461fef058a8e.png)

From the logs:
```
  proxy | 2022/11/08 17:06:26 [036] GET https://registry.npmjs.org:443/@databricks%2Fdatabricks-sdk
  proxy | 2022/11/08 17:06:26 [036] 404 https://registry.npmjs.org:443/@databricks%2Fdatabricks-sdk
  proxy | 2022/11/08 17:06:26 [038] GET https://www.npmjs.com:443/package/@databricks/databricks-sdk
  proxy | 2022/11/08 17:06:27 [038] 302 https://www.npmjs.com:443/package/@databricks/databricks-sdk
  proxy | 2022/11/08 17:06:27 [040] GET https://www.npmjs.com:443/login?next=%2Fpackage%2F%40databricks%2Fdatabricks-sdk
  proxy | 2022/11/08 17:06:27 [040] 429 https://www.npmjs.com:443/login?next=%2Fpackage%2F%40databricks%2Fdatabricks-sdk
updater | INFO <job_504761053> Handled error whilst updating @databricks/databricks-sdk: private_source_authentication_failure {:source=>"registry.npmjs.org"}
```

This is not a surprise since the package doesn't exist on NPM.
