### ISSUE TITLE
Option to make PRs for a group of dependencies

### ISSUE THREAD

**Issue by DenBond7** [dependabot/dependabot-core#6108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello. I'm an Android Developer. In Android, we have a lot of dependencies that are grouped. It means they should be updated at the same time, not one by one like `Dependabot` does it.

For example, Please look at [these dependencies](https://developer.android.com/jetpack/androidx/releases/test#espresso-3.5.0). **Version = 3.5.0**
It would be nice to have

```gradle
androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0' //updated
androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.5.0' //updated
androidTestImplementation 'androidx.test.espresso:espresso-intents:3.5.0' //updated
androidTestImplementation 'androidx.test.espresso:espresso-web:3.5.0' //updated
```

instead of this one

```gradle
androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0' //updated
androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.4.0'
androidTestImplementation 'androidx.test.espresso:espresso-intents:3.4.0'
androidTestImplementation 'androidx.test.espresso:espresso-web:3.4.0'
```

In most cases, updating only one dependency produces compilation or runtime issues.

I read https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file but didn't find settings that can help.

Maybe we can use something similar to https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore

For example

```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    grouped:
      - group-name: "'androidx.test.espresso"
      - group-name: "'androidx.test.*"
     
```
