### ISSUE TITLE
Allow customizable prefix delimiter in commit_message_options 

### ISSUE THREAD

**Issue by flovogt** [dependabot/dependabot-core#6122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In https://github.com/dependabot/dependabot-core/blob/cfeac129f37fceb8964534e481e4d816d9066b36/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L80 the colon is hard coded to be used as a delimiter for the prefix and the rest of the commit message.
There might be commit message guidelines enforcing other delimiters. In our scenario we wanna omit the delimiter completely.
Therefore, it would be awesome to have the option to configure the delimiter.

```yaml
  commit-message:
    prefix: "[DEPENDENCY]"
    prefix-development: "[INTERNAL]"
    prefix-delimiter: "-"
```
Would lead to `[DEPENDENCY] - Bump XX from YY to ZZ`

or omit the delimiter completely
```yaml
  commit-message:
    prefix: "[DEPENDENCY]"
    prefix-development: "[INTERNAL]"
    prefix-delimiter: ""
```
Would lead to `[DEPENDENCY] Bump XX from YY to ZZ`

**Comment by flovogt** [comment]
We were able to workaround the omitting option while adding a whitespace after the prefix string.

```yaml
commit-message:
  prefix: "[DEPENDENCY] "
  prefix-development: "[INTERNAL] "
```

Sample project: https://github.com/flovogt/test-lib-gh/blob/main/.github/dependabot.yml
