### ISSUE TITLE
Unable to view dependabot log for security updates

### ISSUE THREAD

**Issue by mbiggs-gresham** [dependabot/dependabot-core#6153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

```
version: 2
registries:
  npm-nexus:
    type: npm-registry
    url: https://xxx.xxxxxx.com/repository/npm-group
    username: xxxxx
    password: ${{secrets.XXX}}
  maven-nexus:
    type: maven-repository
    url: https://xxx.xxxxxx.com/repository/maven-group
    username: xxxxx
    password: ${{secrets.XXX}}

updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 0
    registries:
      - npm-nexus

  - package-ecosystem: "docker"
    directory: "/ui"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/server"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5
    registries:
      - maven-nexus

  - package-ecosystem: "docker"
    directory: "/server/history-service"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5
```

### What you expected to see, versus what you actually saw

The dependabot logfile for version updates can be viewed by clicking the `Last checked` hyperlink from the insights tab. However I can't find a way to view the logfile for security updates. I would expect some means to view the log either via insights of security issues/PR's. 

NOTE: We use `open-pull-requests-limit: 0` to disable version updates for npm and to only receive security updates.

<img width="1267" alt="Screenshot 2022-11-17 at 12 22 17" src="https://user-images.githubusercontent.com/34435305/202448273-2df659b4-d5b7-40ea-b94a-d795cad30db4.png">
