### ISSUE TITLE
Not detecting packages when using dependency groups in poetry 1.2

### ISSUE THREAD

**Issue by xkumiyu** [dependabot/dependabot-core#6209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

poetry 1.2.2

### What you expected to see, versus what you actually saw

Dependency groups were introduced in poetry 1.2.
https://python-poetry.org/docs/master/managing-dependencies/

The following that were previously listed below are now deprecated.

```toml
[tool.poetry.dev-dependencies]
flake8 = "^6.0.0"
```

The new version should state the following:

```toml
[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
```

`[tool.poetry.dev-dependencies]` is detected and works fine, but `[tool.poetry.group.dev.dependencies]` is NOT detected.
