### ISSUE TITLE
"Dependabot encountered an unknown error" or times out systematically since a few weeks

### ISSUE THREAD

**Issue by rpellerin** [dependabot/dependabot-core#6221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

8.19.2

### Language version

NodeJS 19.0.1

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    pull-request-branch-name:
      separator: '-'
    directory: '/'
    ignore:
      - dependency-name: 'bootstrap'
      - dependency-name: 'select2'
      - dependency-name: 'file-type'
      - dependency-name: '@storybook/*'
      - dependency-name: '@opentok/client'
      - dependency-name: 'react-pdf'
    schedule:
      interval: 'daily'
      time: '09:00'
    open-pull-requests-limit: 100
    versioning-strategy: 'increase'
    labels:
      - 'auto-merge'
      - 'auto-approve'
      - 'dependabot-recreate-once'
      - 'dependencies'
      - 'npm'
```

### What you expected to see, versus what you actually saw

Since about two weeks ago, the Dependabot job never completes and systematically times out or fails, with the following error message:

```
Dependabot encountered an unknown error
Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details.
```

![image](https://user-images.githubusercontent.com/5323445/204262613-3bfff389-771b-48a6-b1c3-92729aea53f8.png)

And the very last line of the logs reads: `updater | time="2022-11-28T09:45:42Z" level=warning msg="timeout running job" error="waiting for updater: waiting for container: context deadline exceeded" job_id=526171787`

No significant changes were brought to our codebase, that would explain this.

On top of that, Dependabot rarely opens any PR, maybe one or two PRs, every 3 or 4 runs. While we have more than 10 dependencies out of date. So we suspect something is broken.

Can you please help? Thank you.
