### ISSUE TITLE
Issue accessing private gemfury.io registry

### ISSUE THREAD

**Issue by adnikiforov** [dependabot/dependabot-core#6222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

bundler 2.1.4

### Language version

ruby 2.7.6

### Manifest location and content before the Dependabot update

```
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

source 'https://rubygems.org'

ruby '2.7.6'

...

source 'https://gem.fury.io/cryptopay/' do
  gem 'compliance', '~> 0.21.1'
  gem 'card-service', '~> 1.9.1', require: 'card_service'
  gem 'dillinger'
  gem 'loggy'
end

...
```

### dependabot.yml content

```
version: 2
registries:
  rubygems-server-gem-fury-io-cryptopay:
    type: rubygems-server
    url: https://gem.fury.io/cryptopay/
    token: "${{secrets.RUBYGEMS_SERVER_GEM_FURY_IO_CRYPTOPAY_TOKEN}}"

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "Ruby"
      - "Dependencies"
    open-pull-requests-limit: 20
    target-branch: dependencies
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    registries:
      - rubygems-server-gem-fury-io-cryptopay

  - package-ecosystem: npm
    directory: "/"
    target-branch: dependencies
    schedule:
      interval: daily
    labels:
      - "JavaScript"
      - "Dependencies"
```

### What you expected to see, versus what you actually saw

Expected: Dependabot generating updates for the gems, including/having in mind private registry gems and their dependencies.

Actual:
401 error while trying to access registry
```
  proxy | 2022/11/28 14:10:45 [018] GET https://gem.fury.io:443/cryptopay/versions
  proxy | 2022/11/28 14:10:46 [018] 401 https://gem.fury.io:443/cryptopay/versions
updater | INFO <job_526441464> Handled error whilst updating %GEM_NAME%: private_source_authentication_failure {:source=>"set --global gem.fury.io"}
updater | INFO <job_526441464> Finished job processing
```

What I did trying to fix issue:
- tried another registry URL
- added `BUNDLE_GEM__FURY__IO` to Dependabot secrets with the actual and working deploy token
- regenerated and updated `RUBYGEMS_SERVER_GEM_FURY_IO_CRYPTOPAY_TOKEN` with the actual and working deploy token
- tried to inject token into registry URL

**Comment by honeyankit** [comment]
@adnikiforov : Thank you for filing this bug. The `private_source_authentication_failure` can happen for couple of reasons. I request you to try the below: 
1. Verify the token used to access the private registry `(https://gem.fury.io:443)` is still valid.
2. Verify that the private registry url you are trying to access via dependabot.yaml is correct.
3. Verify the ruby gem package do exist in the private registry.

**Comment by honeyankit** [comment]
@adnikiforov : Could you try following the below document and add `insecure-external-code-execution` to the dependabot.yml file. This settings seems to be missing. This could be the root cause. 

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#insecure-external-code-execution

**Comment by honeyankit** [comment]
@adnikiforov: I am trying to replicate your issue. I tried updating a basic gem file via private registry and it worked for me. 

My dependabot.yml file:
```yaml
version: 2
registries:
  rubygems-server-gem:
    type: rubygems-server
    url: https://gem.fury.io/ankithoney/
    token: "${{secrets.RUBYGEMS_SERVER_GEM_FURY}}"

updates:
  - package-ecosystem: bundler
    directory: /
    vendor: true
    schedule:
      interval: weekly
    registries:
      - rubygems-server-gem
```

Gemfile:
```yaml
# frozen_string_literal: true

source 'https://gem.fury.io/ankithoney/' do
  gem 'ghes-private-package-gem', '~> 1.0.2'
end
```

Gemfile.lock
```yaml
GEM
  remote: https://gem.fury.io/ankithoney/
  specs:
    ghes-private-package-gem (1.0.2)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  ghes-private-package-gem (~> 1.0.2)!

BUNDLED WITH
   2.3.7
```

```bash
updater | I, [2022-11-30T20:32:58.686087 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_528298255> Starting job processing
updater | INFO <job_528298255> Starting update job for dsp-testing/ruby-ecosystem-private-regis-test
updater | INFO <job_528298255> Checking if ghes-private-package-gem 1.0.2 needs updating
  proxy | 2022/11/30 20:33:02 [012] GET https://gem.fury.io:443/ankithoney/versions
  proxy | 2022/11/30 20:33:02 [012] * authenticating rubygems server request (host: gem.fury.io)
  proxy | 2022/11/30 20:33:02 [012] 200 https://gem.fury.io:443/ankithoney/versions
  proxy | 2022/11/30 20:33:02 [014] GET https://gem.fury.io:443/ankithoney/info/ghes-private-package-gem
  proxy | 2022/11/30 20:33:02 [014] * authenticating rubygems server request (host: gem.fury.io)
  proxy | 2022/11/30 20:33:02 [014] 200 https://gem.fury.io:443/ankithoney/info/ghes-private-package-gem
updater | INFO <job_528298255> Latest version is 1.0.3
updater | INFO <job_528298255> Pull request already exists for ghes-private-package-gem with latest version 1.0.3
updater | INFO <job_528298255> Finished job processing
updater | time="2022-11-30T20:33:02Z" level=info msg="task complete" container_id=job-528298255-updater exit_code=0 job_id=528298255 step=updater
```
