### ISSUE TITLE
Support updating action inputs

### ISSUE THREAD

**Issue by abraham** [dependabot/dependabot-core#6247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It would be great if in addition to supporting updating action versions (e.g. `ruby/setup-ruby@v1.125.0` to `ruby/setup-ruby@v1.126.0`) if repos could get PRs updating inputs to actions.

For example the example config of `ruby/setup-ruby` is:

```yaml
name: My workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake
```

The `ruby-version` value of `'3.0'` is already not the latest Ruby version. It would be great to get PR updating that to `'3.1'`.
