### ISSUE TITLE
Dependabot updates outside of directory.

### ISSUE THREAD

**Issue by Dreamsorcerer** [dependabot/dependabot-core#6255]
### Package ecosystem

pip

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

Dependabot created a PR titled 'Bump cryptography from 3.4.8 to 38.0.4 in /requirements'
Which updates requirements.txt.

I specified a directory as a workaround for #1657. But, it still updates requirements.txt which is not under the directory requirements/.

Expected behaviour: No PRs for files outside of requirements/.
