### ISSUE TITLE
Dependabot updates semver patch versions while being configured to ignore them

### ISSUE THREAD

**Issue by gbottari** [dependabot/dependabot-core#6256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip (pipenv)

### Package manager version

pipenv 2022.10.4

### Language version

Python 3.8

### Manifest location and content before the Dependabot update

/.github/dependabot.yml

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    target-branch: "develop"

    schedule:
      interval: "weekly"
      day: "saturday"

    open-pull-requests-limit: 1
    rebase-strategy: "disabled"

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
```

### Updated dependency

`chalice` from ~=1.27.1 to ~=1.27.3

### What you expected to see, versus what you actually saw

Dependabot opened this PR: "Update chalice requirement from ~=1.27.1 to ~=1.27.3" which was unexpected for me since I asked it to ignore patch-version updates in the `dependabot.yml` file:

```yml
...
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
```

**Comment by ggilley** [comment]
I have a similar issue trying to ignore aws updates

```
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  assignees:
  - ggilley
  ignore:
  - dependency-name: "aws-sdk-go" # we don't need a daily update!
    update-types: ["version-update:semver-patch"]
```

**Comment by abdulapopoola** [comment]
@gbottari and @ggilley ; do you still see this happening?

**Comment by gbottari** [comment]
@abdulapopoola I don't remember seeing this happening after a long time. After looking at some repos, the most recent one was on Sep 23rd last year.

**Comment by abdulapopoola** [comment]
Thank you; the team has shipped quite a lot of changes since. I'll close this out as done then.

**Comment by super-cooper** [comment]
I'm still observing this happen for pip. I received [this dependabot PR](https://github.com/super-cooper/memebot/pull/260) to update `pytest-asyncio` from `~=0.25.1` to `~=0.25.2` this morning despite dependabot being [configured](https://github.com/super-cooper/memebot/blob/dc3951bfa0ae8f03e354179489ddba8dc272f4e5/.github/dependabot.yaml#L32-L43) to ignore these.

```yaml
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: America/New_York
    labels:
      - dependencies
    ignore:
      - dependency-name: '\*'
        update-types: ["version-update:semver-patch"]
```
