### ISSUE TITLE
Dependabot not updating package.json

### ISSUE THREAD

**Issue by mloberg** [dependabot/dependabot-core#6285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

7

### Language version

14

### Manifest location and content before the Dependabot update

`/package.json` - removed some content since coming from private project

```json
{
  "name": "...",
  "version": "3.0.0",
  "description": "...",
  "author": "...",
  "license": "UNLICENSED",
  "main": "dist/index.js",
  "files": [
    "dist/**/*"
  ],
  "repository": {
    "type": "git",
    "url": "..."
  },
  "engines": {
    "node": ">=14.0.0",
    "npm": ">=7.4.0"
  },
  "scripts": {
    ...
  },
  "dependencies": {
    ...
    "@notionhq/client": "^2.2.2",
    "@octokit/rest": "^19.0.5",
    "axios": "^0.27.2",
    "date-fns": "^2.29.3",
    "lodash": "^4.17.21",
    "node-vault": "^0.9.22"
  },
  "devDependencies": {
    "@tsconfig/node14": "^1.0.3",
    "@types/jest": "^29.2.4",
    "@types/lodash": "^4.14.191",
    "@typescript-eslint/eslint-plugin": "^5.45.0",
    "@typescript-eslint/parser": "^5.45.0",
    "axios-mock-adapter": "^1.21.2",
    "concurrently": "^7.6.0",
    "dotenv": "^16.0.3",
    "eslint": "^8.29.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jest": "^27.1.6",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-simple-import-sort": "^8.0.0",
    "jest": "^29.3.1",
    "jest-matcher-specific-error": "^1.0.0",
    "nodemon": "^2.0.20",
    "prettier": "^2.8.0",
    "ts-jest": "^29.0.3",
    "typescript": "^4.9.3"
  }
}
```

### dependabot.yml content

```yml
version: 2
registries:
  github:
    type: npm-registry
    url: 'https://npm.pkg.github.com'
    token: ${{ secrets.GH_PACKAGES_AUTH }}

updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    registries:
      - articulate-github
    schedule:
      interval: weekly
      day: wednesday
      time: "10:00"
```

### What you expected to see, versus what you actually saw

PRs are updating `package-lock.json`, but not updating `package.json` anymore.
