### ISSUE TITLE
Dependabot broken after moving manifest (Cargo.toml)

### ISSUE THREAD

**Issue by DarkWanderer** [dependabot/dependabot-core#6307]
After moving `Cargo.toml` from subdirectory to root directory, Dependabot fails to scan the dependencies as it still tries to read manifest via old path

### Is there an existing issue for this?

- [X] I have searched the existing issues

#4951 seems somewhat related but not entirely same

### Package ecosystem

cargo

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

#### Expected

Dependabot picking up new Cargo.toml location

#### Observed

Dependabot broken as it still tries to read file from old location
![image](https://user-images.githubusercontent.com/2542609/207310580-7bf1c109-1115-4f37-ac25-7af45f478a5e.png)

### Images of the diff or a link to the PR, issue, or logs

https://github.com/DarkWanderer/DynamicOperations/network/updates
https://github.com/DarkWanderer/DynamicOperations/commit/0c38ee53145715e0940219828dfa2e6cfcf686a5#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542
