### ISSUE TITLE
Helm file update fails when tags are marked as string

### ISSUE THREAD

**Issue by nilekhc** [dependabot/dependabot-core#6313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### What you expected to see, versus what you actually saw

The following config works:
```yaml
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 1.17.7
```

But following does not (note the quotes around the _tag_):
```yaml
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.17.7"
```
While running dependabot with this configuration it does recognize that the version needs to be updated (from logs):
```bash
Checking if nginx 1.17.7 needs updating
Requirements to unlock own
Updating nginx from 1.17.7 to 1.23.3
```
But actual update fail (from logs):
```bash
...file_updater.rb:158:in `updated_yaml_content': Expected content to change! (RuntimeError)
```

Is this expected?
