### ISSUE TITLE
Dependabot updating major version of terraform modules even though set to ignore semver-major

### ISSUE THREAD

**Issue by adamstirk-ct** [dependabot/dependabot-core#6316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

terraform

### Language version

1.3

### Manifest location and content before the Dependabot update

N/A

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    rebase-strategy: auto
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

### Updated dependency

hashicorp/aws ( from 4.45.0 to 4.47.0 )
terraform-aws-modules/eks/aws ( from 18.30.0 to 19.0.4

### What you expected to see, versus what you actually saw

hashicorp/aws ( from 4.45.0 to 4.47.0 )
terraform-aws-modules/eks/aws ( from 18.30.0 to 18.31.2

### Smallest manifest that reproduces the issue

Here is a test repo that reproduces the issue

https://github.com/adamstirk-ct/test-dependabot

**Comment by yuuki1967** [comment]
The customer raised the similar case as https://github.zendesk.com/agent/tickets/2381911.
Here is the customer repo https://github.com/dbrenecki/test-terraform
His problem is similar as the issue. But when you only specify the version including `~>` in the tag `required_provider`, a PR is generated.
```
google = {
  source = "hashicorp/google"
  version = "~> 4.84.0"
}
```
Here is the dependabot.yml
```
---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
```

Here is the snippet of the log.
```
pdater | 2023/10/24 04:11:57 INFO <job_739839547> Checking if hashicorp/google needs updating
updater | 2023/10/24 04:11:57 INFO <job_739839547> Ignored versions:
updater | 2023/10/24 04:11:57 INFO <job_739839547> version-update:semver-major - from .github/dependabot.yml
proxy | 2023/10/24 04:11:58 [012] GET https://registry.terraform.io:443/.well-known/terraform.json
proxy | 2023/10/24 04:11:58 [012] 200 https://registry.terraform.io:443/.well-known/terraform.json
proxy | 2023/10/24 04:11:58 [014] GET https://registry.terraform.io:443/v1/providers/hashicorp/google/versions
proxy | 2023/10/24 04:11:58 [014] 200 https://registry.terraform.io:443/v1/providers/hashicorp/google/versions
updater | 2023/10/24 04:11:58 INFO <job_739839547> Latest version is 5.3.0
updater | 2023/10/24 04:11:58 INFO <job_739839547> Requirements to unlock update_not_possible
updater | 2023/10/24 04:11:58 INFO <job_739839547> Requirements update strategy
updater | 2023/10/24 04:11:58 INFO <job_739839547> No update possible for hashicorp/google
```
