### ISSUE TITLE
setuptools added to Pipfile.lock

### ISSUE THREAD

**Issue by lukasz-mitka** [dependabot/dependabot-core#6329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pipenv

### Language version

Python 3.11

### Manifest location and content before the Dependabot update

/Pipfile
/Pipfile.lock

### dependabot.yml content
```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: "deploy/terraform"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: ""
    schedule:
      interval: monthly
```

### Updated dependency

setuptools

### What you expected to see, versus what you actually saw

When running pipenv locally it doesn't add `setuptools` to the `Pipfile.lock` file.
But when dependabot does it's thing it appears there.
Happened for two independent dev dependencies.

### Native package manager behavior

no `setuptools` in `Pipfile.lock`

### Images of the diff or a link to the PR, issue, or logs

```json
        "setuptools": {
            "hashes": [
                "sha256:57f6f22bde4e042978bcd50176fdb381d7c21a9efa4041202288d3737a0c6a54",
                "sha256:a7620757bf984b58deaf32fc8a4577a9bbc0850cf92c20e1ce41c38c19e5fb75"
            ],
            "markers": "python_version >= '3.7'",
            "version": "==65.6.3"
        },
```
