### ISSUE TITLE
git-submodules does not work when referencing Azure based repositories

### ISSUE THREAD

**Issue by mburumaxwell** [dependabot/dependabot-core#6340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

git-submodules

### Manifest location and content before the Dependabot update

.gitsubmodules

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "gitsubmodule" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "20:00"
    open-pull-requests-limit: 10
```

### What you expected to see, versus what you actually saw

Exception `Unsupported provider 'azure'.` is thrown instead of getting an actual update.
