### ISSUE TITLE
Pull Request name does not respect separator under certain conditions

### ISSUE THREAD

**Issue by mathe-matician** [dependabot/dependabot-core#6366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip, npm, gomod

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'mathe-matician'

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'mathe-matician'

  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'mathe-matician'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'mathe-matician'
```

### What you expected to see, versus what you actually saw

My Dependabot seems to create two different types of package upgrades where one will work and respect my `pull-request-branch-name.separator`, and one where it won't.

### Scenario 1:
Dependabot will raise a PR:
- Named `Chore(deps): Bump {pkg} from v1 to v2`
- Branch name `dependabot-{ecosystem}-{pkgname}-{version}` (separator respected)
- The package being upgraded is in a subdirectory, for example, `/service1/pip_requirements.txt`

### Scenario 2:
Dependabot will raise a PR:
- Named `chore(deps): bump {pkg} from v1 to v2 in /service1`
- Branch name `dependabot/{ecosystem}/{subdirectory}/{pkgname}/{version}` (separator not respected)
- The package being upgraded is in the same subdirectory as Scenario 1, `/service1/pip_requirements.txt`.

What causes these two separate scenarios to happen when the packages being upgraded are in the same subdirectory? Why isn't the separator respected when the PR name includes `in /my-subdirectory`? I have seen this with my `pip`, `npm`, and `gomod` Dependabot PRs.
