### ISSUE TITLE
Update security updates and all updates for specific package

### ISSUE THREAD

**Issue by ad-m-ss** [dependabot/dependabot-core#6380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi,

By default, Dependabot creates security updates when new advisory available. 

When configuration created, Dependabot follows configuration also for security updates:

> Use the `allow` option to customize which dependencies are updated. This applies to both version and security updates.

> Security updates are raised for vulnerable package manifests only on the default branch. When configuration options are set for the same branch (true unless you use target-branch), and specify a package-ecosystem and directory for the vulnerable manifest, then pull requests for security updates use relevant options.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

I have libraries that I would like to update automatically (for partnership compliance we need to deploy updates quickly). At the same time, I would also like to have security updates delivered. Due to the number of pull requests, we do not want updates for all packages, unless they are security updates.

We have the configuration:
```
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
    - dependency-name: "snowflake-connector-python"    
````

It fails to create new security updates:

```
updater | INFO <job_568201720> Dependabot cannot update to the required version as all versions were ignored for gitpython
```

Have I missed something or is the configuration not allowing to express such a configuration? Configuration `update-types` does not support value `security`.

Kind regards

**Comment by deivid-rodriguez** [comment]
Hei @ad-m-ss, I did some testing and I'm afraid this is not yet supported :(

We do have a hack to configure security updates exclusively using [open-pull-requests-limit: 0](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit). So you could try having two separate update configurations, one for version updates, and another one for security updates, like this:

```yaml
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
    - dependency-name: "snowflake-connector-python"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
```

However, we have a uniqueness requirement where each configuration needs to have uniq `[package-ecosystem, directory, target-branch]` triple, so this does not work 😢.

Hopefully we can improve this area soon.
