### ISSUE TITLE
pub.dev dependencies with an exact version have "exactness" removed on dependabot update

### ISSUE THREAD

**Issue by GregoryConrad** [dependabot/dependabot-core#6446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pub

### dependabot.yml content

```yaml
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/mimir"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/mimir/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_mimir"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_mimir/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/mimir/native"
    schedule:
      interval: weekly
```

### Updated dependency

flutter_rust_bridge 1.60.0 -> 1.61.1

But this doesn't really matter.

### What you expected to see, versus what you actually saw

Before: "1.60.0"

Expected PR contents: "1.61.1"

Actual PR contents: ^1.60.0

### Images of the diff or a link to the PR, issue, or logs

https://github.com/GregoryConrad/mimir/pull/116/files

### Use case

`flutter_rust_bridge`, which needs a consistent version amongst Dart/Rust projects so that the Rust binaries work as expected. The `^` versioning method breaks the Dart project when it jumps ahead of the compiled Rust binary's `flutter_rust_bridge` version.
