### ISSUE TITLE
Update all but one dependencies

### ISSUE THREAD

**Issue by Bullrich** [dependabot/dependabot-core#6481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'm trying to have dependabot ignore all non security dependency updates with the exception of one.

As `@octokit/graphql-schema` has all the latest updates in the schemas, I want to keep that package updated, but I don't want dependabot to try to update all my other dependencies.

```yml
version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        # Ignore version upgrades.
        # Security updates are nevertheless. unaffected by this setting and will continue to work.
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
    allow:
      - dependency-name: "@octokit/graphql-schema"
```

I know this wouldn't work as, [per documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) it will ignore the package:
> Dependabot checks for all allowed dependencies and then filters out any ignored dependencies or versions. So a dependency that is matched by both an `allow` and an `ignore` will be ignored.

Is there any way to achieve this or should this be a feature request? Can we do something like `ignore: *!@octokit/graphql-schema`?

Thank you!
