### ISSUE TITLE
Dependabot doesn't respect it's own rules

### ISSUE THREAD

**Issue by eirnym** [dependabot/dependabot-core#6532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

Gradle 7.6

### Language version

Java 17

### Manifest location and content before the Dependabot update

I have a few separate independent projects inside a single repo: plugin, internal plugin, demo for AGP 7 and java demo.

* https://github.com/jsonschema2dataclass/js2d-gradle/settings.gradle.kts
* https://github.com/jsonschema2dataclass/js2d-gradle/internal/settings.gradle.kts
* https://github.com/jsonschema2dataclass/js2d-gradle/demo/java/settings.gradle.kts
* https://github.com/jsonschema2dataclass/js2d-gradle/demo/android/agp7/settings.gradle.kts

plugin contains a few modules, depending on libraries with conflicting API by design, and it working well:

* https://github.com/jsonschema2dataclass/js2d-gradle/blob/main/plugin-gradle/compat/agp34/build.gradle.kts
* https://github.com/jsonschema2dataclass/js2d-gradle/blob/main/plugin-gradle/compat/agp7/build.gradle.kts

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gradle
    directory: "plugin-gradle/compat/agp7"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: com.android.tools.build:gradle
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: gradle
    directory: "/plugin-gradle/compat/agp34"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: com.android.tools.build:gradle
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: gradle
    directory: "demo/java"
    schedule:
      interval: "daily"
  - package-ecosystem: gradle
    directory: "demo/android/agp7"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: com.android.tools.build:gradle
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "github-actions"
    directory: ""
    schedule:
      interval: "daily"
  - package-ecosystem: gradle
    directory: ""
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

1) Despite on rules created to skip major updates for certain modules, dependabot stubbornly updates the PR for it. example: https://github.com/jsonschema2dataclass/js2d-gradle/pull/620 and there's serveral such PR
2) Despite I remove `includeBuild` from the `settings.build.kts` for a subproject, it still has an attachment to the root project which is incorrect as well
3) Changes in `settings.gradle.kts` are ignored while this file defines a gradle project, not `build.gradle.kts`

### Images of the diff or a link to the PR, issue, or logs

https://github.com/jsonschema2dataclass/js2d-gradle/pull/620
and few recently closed from dependabot. I ususally merge, not close as in most cases it makes more sence
