### ISSUE TITLE
Configure PR author and git committer

### ISSUE THREAD

**Issue by flovogt** [dependabot/dependabot-core#6586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It would be awesome if you could configure another user as PR author and git committer. Either via `author` or `token` property generated by this user.

**Option 1:**

```yaml
version: 2
updates:
- package-ecosystem: npm
  author: my_bot
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  versioning-strategy: increase
```

**Option 2:**

```yaml
version: 2
updates:
- package-ecosystem: npm
  token: ${{secrets.GH_MY_BOT_TOKEN}}
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  versioning-strategy: increase
```

There might be even more options possible. Looking forward to your feedback and ideas!
