### ISSUE TITLE
[BUG] dependabot-core does not update all dependencies in build.gradle

### ISSUE THREAD

**Issue by PhoenixmitX** [dependabot/dependabot-core#6598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

7.5

### Language version

java 17

### Manifest location and content before the Dependabot update

`build.gradle`
```gradle
dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.24'
	annotationProcessor 'org.projectlombok:lombok:1.18.24'
}
```

### dependabot.yml content

```yml
version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      include: "scope"
    open-pull-requests-limit: 16
```

### Updated dependency

`build.gradle`
```gradle
dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.26'
	annotationProcessor 'org.projectlombok:lombok:1.18.24'
}
```

#### Current behavior
Dependabot does not update the annotationProcessor dependency.
I have not tested this, but there may be other dependency types that are not updated.

#### Expected behavior
AnnotationProcessor is also updated.

### Impact
Could be a security impact if dependencies with security implications are not updated.

### Smallest manifest that reproduces the issue

`build.gradle`
```gradle
plugins {
	id 'java'
}

repositories {
	mavenCentral()
}

dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.24'
	annotationProcessor 'org.projectlombok:lombok:1.18.24'
}
```
