### ISSUE TITLE
Unrelated dependencies are updated with bundler

### ISSUE THREAD

**Issue by mkllnk** [dependabot/dependabot-core#6602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Previous issues:

- https://github.com/dependabot/dependabot-core/issues/5926

### Package ecosystem

bundler

### Package manager version

2.4.3

### Language version

Ruby 3.0.3p157

### Manifest location and content before the Dependabot update

* https://github.com/mkllnk/dependabot-rspec-rails-activemerchant/pull/5/files

### dependabot.yml content
```yml
version: 2
updates:

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    # Only specific requirements are specified in Gemfile, so don't touch it.
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # All versions are specified in package.json, so please update them.
    versioning-strategy: increase
```
https://github.com/mkllnk/dependabot-rspec-rails-activemerchant/blob/4e9edc7a75c588ec5bdbd901bb5eb88e18266f84/.github/dependabot.yml

### Updated dependency

Bump rspec-rails from 5.1.2 to 6.0.1

### What you expected to see, versus what you actually saw

I expect rspec-rails and any sub-dependencies to be updated but an unrelated direct dependency, activemerchant, was updated, too.

### Native package manager behavior

Interestingly, `bundle update rspec-rails` says that the version stayed the same. Removing any version restriction from the Gemfile results in the same. Specifying the rspec-rails version as `>= 6.0.0` does update rspec with sub-dependencies and without touching activemerchant.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/mkllnk/dependabot-rspec-rails-activemerchant/pull/5/files

### Smallest manifest that reproduces the issue

Unfortunately, running dependabot-cli failed on my machine: 
```
failed to run updater: failed to create proxy container: Error response from daemon: invalid IP address in add-host: "host-gateway"
```

So I would need to change the main branch of my demo-repository or create a new repository again and wait for dependabot after each update. That would take quite a while. Is it worth me reducing or can you investigate quicker? The demo repository is linked above.
