### ISSUE TITLE
Dependabot does not respect ignore rules when updating `yarn.lock` files

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#6608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

yarn berry (I guess yarn in general, and maybe npm too)

### Language version

I think it doesn't matter

### Manifest location and content before the Dependabot update

https://github.com/dependabot/smoke-tests/tree/6cf39d141962f97109e53c210db1a77639155e77/yarn-berry

### dependabot.yml content

From https://raw.githubusercontent.com/dependabot/smoke-tests/6cf39d141962f97109e53c210db1a77639155e77/tests/smoke-yarn-berry.yaml

```yaml
input:
    job:
        package-manager: npm_and_yarn
        allowed-updates:
            - dependency-name: jquery
        ignore-conditions:
            - dependency-name: jquery
              version-requirement: '>3.6.1'
        source:
            provider: github
            repo: dependabot/smoke-tests
            directory: /yarn-berry/
            commit: 6cf39d141962f97109e53c210db1a77639155e77
        credentials-metadata:
            - host: github.com
              type: git_source
    credentials:
        - host: github.com
          password: $LOCAL_GITHUB_ACCESS_TOKEN
          type: git_source
          username: x-access-token
```

### Updated dependency

JQuery to 3.6.3.

### What you expected to see, versus what you actually saw

jQuery updated to 3.6.1, because of the `>3.6.1` ignore rule.

### Native package manager behavior

Native package manager does not know about ignore rules, so has the same behavior.

An potential idea to fix this would be to add a [resolutions](https://github.com/yarnpkg/rfcs/blob/d0660f7f736c1e27f680ce7ce1d7d6485bebb303/implemented/0000-selective-versions-resolutions.md) field to the package.json with the desired version before generating the `yarn.lock` file.

### Images of the diff or a link to the PR, issue, or logs

See failing spec at https://github.com/dependabot/smoke-tests/pull/29, for example.

### Smallest manifest that reproduces the issue

This is pretty small! :)
