### ISSUE TITLE
Dependabot doesn't recognize updated Docker images.

### ISSUE THREAD

**Issue by skabashnyuk** [dependabot/dependabot-core#6612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Package manager version

No response

### Manifest location and content before the Dependabot update

/bundle.Dockerfile
/oauth.Dockerfile

### dependabot.yml content
```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: daily
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
```
### Updated dependency

from registry.access.redhat.com/ubi8/ubi-minimal:8.7-923.1669829893
to registry.access.redhat.com/ubi8/ubi-minimal:8.7-1049

### What you expected to see, versus what you actually saw

Expect - registry.access.redhat.com/ubi8/ubi-minimal:8.7-1049
SAW- no updates

### Native package manager behavior

No response

### Images of the diff or a link to the PR, issue, or logs

No response

### Smallest manifest that reproduces the issue
```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.7-923.1669829893 as spi-oauth
```
