### ISSUE TITLE
The `increase` strategy should move ranges forward, not widen them

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#6631]
This was first noticed at https://github.com/dependabot/dependabot-core/issues/6625#issuecomment-1424140956.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Python (but not sure if it's specific to it, could be the same in other ecosystems)

### pyproject.toml

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lorem"
version = "2.5.0"
requires-python = ">=3.9,<4.0"
description = "Generator for random text that looks like Latin."
dependencies = [
	"more-itertools>=8,<9",
]
```

### requirements.txt

```
more-itertools==8.14.0
```

### dependabot.yml content

```yaml
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
    # Allow both direct and indirect updates for all packages
    - dependency-type: "all"
  versioning-strategy: increase
```

### Updated dependency

more-itertools from 8.14.0 to 9.0.0

### What you expected to see, versus what you actually saw

I saw

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 788d44b..49a07c9 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -8,5 +8,5 @@ version = "2.5.0"
 requires-python = ">=3.9,<4.0"
 description = "Generator for random text that looks like Latin."
 dependencies = [
-	"more-itertools>=8,<9",
+	"more-itertools>=8,<10",
 ]
```

I would've expected

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 788d44b..49a07c9 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -8,5 +8,5 @@ version = "2.5.0"
 requires-python = ">=3.9,<4.0"
 description = "Generator for random text that looks like Latin."
 dependencies = [
-	"more-itertools>=8,<9",
+	"more-itertools>=9,<10",
 ]
```

because the current behavior is widening, not increasing?

### Images of the diff or a link to the PR, issue, or logs

https://github.com/sanderr/inmanta-module-factory/pull/7/
