### ISSUE TITLE
Dependabot to update composite actions in workflows files from a different repository

### ISSUE THREAD

**Issue by saisatishkarra** [dependabot/dependabot-core#6656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello,

I'd love for Dependabot to update composite actions defined in a separate repository being used in the workflows of another repository with git commit ID's.

I've got a repository with Composite actions with say 3 commits on the repoA
- (X, Y) committed specifically to folder/action-1
- (Z) commit specifically to folder/action-2

```
repoA (public)
 - folder/action-1 (Commits: X, Y)
    - action.yml (type: composite)
 - folder/action-2 (Commits: Z)
    - action.yml (type: composite)
```

I've got a repository with Composite actions with say 2 commits on the repoB 
- <C1, C2>committed specifically to repo root

```
repoB (public)
    - action.yml (type: composite)
```

```
repoC (private)
  - .github
     - workflows
        - ci.yml
           -- uses: repoA/folder/action-1@X
           -- uses: repoA/folder/action-2@Z
           -- uses: repoB@C1
     - dependabot.yml
          version: 2
          updates:
              - package-ecosystem: "github-actions"
                directory: "/" (`# Update workflow files in this repo and look for composite Actions version updates defined in repoB`)
                schedule:
                  interval: "daily"
              - package-ecosystem: "github-actions"
                directory: "/folder/action-1" (`# Look for Composite action-1 version updates in repoA`)
                schedule:
                  interval: "daily"
              - package-ecosystem: "github-actions"
                directory: "/folder/action-2" (`# Look for Composite action-2 version updates in repoA`)
                schedule:
                  interval: "daily"
```

Expected:

1. PR to bump ` repoA/folder/action-1@X` to  `repoA/folder/action-1@Y` where Y is the new commit SHA on repoA for `action-1`
2. PR to bump ` repoB@C1` to  `repoB@C2` where C2 is the new commit SHA on repoB for `action` in root

Existing / Similar Issues found:
1. I have come across https://github.com/dependabot/dependabot-core/issues/4178 and wasn't sure if the actual composite action in the calling workflow can be updated VS of the dependencies of the composite actions themselves.
2. https://github.com/dependabot/dependabot-core/issues/4327 and not sure if this feature is what is expected. If, so pls relate.

Can someone help me understand if this is supported and what the Dependabot configuration should look like?
