### ISSUE TITLE
Dependabot ignores registries configuration on security updates

### ISSUE THREAD

**Issue by ImRodry** [dependabot/dependabot-core#6687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

1.22.19

### Language version

Node.js v18.14.0

### Manifest location and content before the Dependabot update

/package.json
I'm not allowed to share the full file unfortunately

### dependabot.yml content

```yml
version: 2
registries:
    my-registry:
        type: npm-registry
        url: <redacted>
        username: <redacted>
        password: <redacted>
updates:
    - package-ecosystem: npm
      directory: "/"
      registries:
          - my-registry
      schedule:
          interval: weekly
          day: monday
          time: "14:00"
          timezone: "Europe/Lisbon"
      open-pull-requests-limit: 10
      assignees:
          - imrodry
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: weekly
          day: monday
          time: "14:00"
          timezone: "Europe/Lisbon"
      open-pull-requests-limit: 10
      assignees:
          - imrodry
```

### Updated dependency

undici from 5.13.0 to 5.19.1 (indirect dependency, fixes CVE-2023-24807 and CVE-2023-23936)

### What you expected to see, versus what you actually saw

I expected dependabot to correctly update the dependency while keeping my custom registry, instead it updated the dependency and reset the registry url to the yarn one. It also modified the URL on 2 other dependencies that come from the updated one (undici)

### Native package manager behavior

With the proper configuration the package manager keeps the specifies registry

### Images of the diff or a link to the PR, issue, or logs

![image](https://user-images.githubusercontent.com/38259440/219518956-a2d7c023-94bd-41fc-84ed-6e862eaaeb3a.png)

### Smallest manifest that reproduces the issue

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "undici": "5.13.0"
  }
}
```
