### ISSUE TITLE
Support list of schedule.day (schedule.days)

### ISSUE THREAD

**Issue by peaceiris** [dependabot/dependabot-core#6694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Feature Request for `schedule.days`

I would like to be able to check for dependency updates **only on specific days** of the week using the Dependabot settings.

## Background

With the current Dependabot configuration specs, it is possible to set the schedule.interval to weekdays to have the task run every day from Monday to Friday. On the other hand, we cannot exclude only certain days of the week. Nor can it be run only on certain days of the week.

As background, our team doesn't want to see any Dependabot pull requests on Fridays. For that reason, we want to exclude only Friday from the schedule. Notification noise can be reduced by enabling that exclusion.

cf. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

## Suggestion for `schedule.days`

Below is an example usecase of the new `schedule.days` I suggest.

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      time: "10:00"
      days:
        - "monday"
        - "tuesday"
        - "wednesday"
        - "thursday"
```
