### ISSUE TITLE
Support vendoring for Go

### ISSUE THREAD

**Issue by greysteil** [dependabot/dependabot-core#670]
Moved from https://github.com/dependabot/feedback/issues/187.

This needs a general strategy for supporting vendoring, but is also probably a sensible first language to look at (since vendoring in Go is so common).

**Comment by saschagrunert** [comment]
I would love to see this feature in! I would go for a simple configuration variable to check if vendoring is enabled and then do something like this afterwards:

````
export GO111MODULE=on \
	go mod tidy && \
	go mod vendor && \
	go mod verify
```

What do you think?

**Comment by emirb** [comment]
@greysteil Any ETA?

**Comment by greysteil** [comment]
I'm going to leave this one for @hmarr, but hopefully soon. We've done a bunch of the required background work here already, and GitHub themselves vendor their dependencies, so we're feeling it as an acute pain internally!

**Comment by saschagrunert** [comment]
I guess we also have to take indirect dependencies into account. Dependabot should check them for updates, too.

**Comment by hmarr** [comment]
This is our top priority for Go, but unfortunately we can't dedicate much time to Go right now. I'm hoping we'll be able to build our much more solid Go support (including vendoring) over the next few months.

Related: https://github.com/dependabot/feedback/issues/215

**Comment by greysteil** [comment]
A workaround function we've seen for Circle CI users, that vendors dependencies in an additional commit:

```yaml
update-vendor:
  <<: *docker_build_image
  steps: 
    - checkout
    - run: GO111MODULE=on go mod vendor
    - run: |
      git config --global user.email "robot@mydomain.com"
      git config --global user.name "Friendly Robot"

      git diff --quiet || ( \
        git commit -am "vendor: go mod vendor" && \
        git push origin "$(git rev-parse --abbrev-ref HEAD)" \
      )
```

**Comment by ndeloof** [comment]
Any update on this feature request ?
This clearly is a blocker for my team to adopt dependabot :'(

**Comment by ggilley** [comment]
Another vote for this. Makes it impossible to use otherwise.

**Comment by jan-xyz** [comment]
This breaks using dependabot with go1.14 and vendording. go1.14 does not allow an inconsistent vendor directory, so without automatic vendoring, we have to manually checkout each branch and do `go mod vendor`.

**Comment by scothis** [comment]
I was able to work around this limitation with a custom Workflow. The downside is that since we're adding a new commit Dependabot will no longer manage the PR. Proper upstream support is still desirable.

```yaml
name: dependabot-gomod
on:
  push:
    branches:
    - dependabot/go_modules/**

jobs:
  go_mod_vendor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
        with:
          # use a personal access token so that the push will trigger new actions
          token: ${{ secrets.PAT_TOKEN }}
      - name: vendor
        run: |
          go mod vendor
      - name: tidy
        run: |
          go mod tidy
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.3.0
        with:
          commit_message: Vendor and tidy go modules
          commit_options: '--no-verify --signoff'
```
