### ISSUE TITLE
Gradle version catalog - Uncaught exception: must be a Dependency object

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Manifest location and content before the Dependabot update

gradle/libs.versions.toml

### What you expected to see, versus what you actually saw

I expected dependabot to continue as usual. But I saw this: 

`Uncaught exception: must be a Dependency object`

![image](https://user-images.githubusercontent.com/8935151/221613759-f2fc0717-865c-4fd0-ae72-5081b8eb6355.png)
![image](https://user-images.githubusercontent.com/8935151/221613880-9f7aa37d-133e-484a-bdce-1f486425f313.png)

### Smallest manifest that reproduces the issue

libs.versions.toml

```toml
[versions]
juice = { strictly = "3.0" }


[libraries]

juice = { module = "com.util.juice:juice", version.ref="juice" }

```
