### ISSUE TITLE
Docker tag pointed to the same image causes the update

### ISSUE THREAD

**Issue by kovayur** [dependabot/dependabot-core#6746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Manifest location and content before the Dependabot update

/probe/Dockerfile

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gomod'
    directory: '/tools'
    schedule:
      interval: 'weekly'
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/probe"
    schedule:
      interval: "weekly"
```

### Updated dependency

From: `registry.access.redhat.com/ubi8/ubi-minimal:8.7`
To: `registry.access.redhat.com/ubi8/ubi-minimal:8.7-1085`

### Expected behavior:
No PR should be raised since tags are pointing to the same image. PR should be raised only if minor version is updated, i.e. `8.7` -> `8.8` (without hyphen).
### Actual behavior:
PR has been raised.

### Native package manager behavior

```
$ docker pull registry.access.redhat.com/ubi8/ubi-minimal:8.7
8.7: Pulling from ubi8/ubi-minimal
c7e856e03741: Pull complete 
Digest: sha256:dc06ba83c6f47fc0a2bca516a9b99f1cf8ef37331fd460f4ca55579a815ee6cb
Status: Downloaded newer image for registry.access.redhat.com/ubi8/ubi-minimal:8.7
registry.access.redhat.com/ubi8/ubi-minimal:8.7
$ docker pull registry.access.redhat.com/ubi8/ubi-minimal:8.7-1085
8.7-1085: Pulling from ubi8/ubi-minimal
Digest: sha256:dc06ba83c6f47fc0a2bca516a9b99f1cf8ef37331fd460f4ca55579a815ee6cb
Status: Downloaded newer image for registry.access.redhat.com/ubi8/ubi-minimal:8.7-1085
registry.access.redhat.com/ubi8/ubi-minimal:8.7-1085
```

### Images of the diff or a link to the PR, issue, or logs

stackrox/acs-fleet-manager#854

### Smallest manifest that reproduces the issue

```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.7
```
