### ISSUE TITLE
Insights about the `updated-dependencies` section of the commit message

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6777]
I am currently running [dependabot-script](https://github.com/dependabot/dependabot-script) in a private instance of GHE, and I would like to leverage [fetch-metadata](https://github.com/dependabot/fetch-metadata) to extract additional information about my pull requests 

While going through their code, I noticed that the `updated-dependencies` block is a requirement to make that action work, but that the logic to derive that block is not present in core as far as I understand

Would it be possible to release some insights about how this block is currently derived in Dependabot? 

Example: 

```yml

---
updated-dependencies:
- dependency-name: io.quarkus:quarkus-bom
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: io.quarkus:quarkus-maven-plugin
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: io.quarkus:quarkus-bootstrap-maven-plugin
  dependency-type: direct:production
  update-type: version-update:semver-patch
- dependency-name: io.quarkus:quarkus-extension-processor
  dependency-type: direct:production
  update-type: version-update:semver-patch
```

I can probably calculate `dependency-name` and `update-type`, but I am not sure where `dependency-type` comes from

Additionally, I am not sure what are the different options possible here

If this information is secret/private to the Dependabot-hosted version, feel free to close this

Thank you!
