### ISSUE TITLE
Dependabot is ignoring `labels: []` setting

### ISSUE THREAD

**Issue by jtbandes** [dependabot/dependabot-core#6858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

  "packageManager": "yarn@3.3.1"

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: [] # disable default labels

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [] # disable default labels
```

### What you expected to see, versus what you actually saw

About 2 days ago, Dependabot started ignoring a `labels: []` setting in our config file.

The config file, which hasn't been updated in months: https://github.com/foxglove/studio/blob/main/.github/dependabot.yml

List of dependabot PRs: https://github.com/foxglove/studio/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+

<img width="746" alt="image" src="https://user-images.githubusercontent.com/14237/225774477-d1540cc3-72f3-4c34-ab9a-173e6df76ab1.png">
