### ISSUE TITLE
Add support for Hugo modules

### ISSUE THREAD

**Issue by razonyang** [dependabot/dependabot-core#6860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi, is it possible to add support for [Hugo modules](https://gohugo.io/hugo-modules/use-modules/#prerequisite), which base on Golang Modules?

I set up the Dependabot on my repo with `gomod`, but found that `go.mod` and `go.sum` will be emptied.

Related Config: 

```yaml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "gomod"
    directory: "/modules/blog"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "gomod"
    directory: "/modules/meta/recommended"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
```

Related PRs:

- https://github.com/razonyang/hb/pull/208/files
- https://github.com/razonyang/hb/pull/209/files
- https://github.com/razonyang/hb/pull/210/files

Is there a way to replace the `go get` and `go mod tidy` with `hugo mod get` and `hugo mod tidy` respectively?
