### ISSUE TITLE
Not skipping unstable versions

### ISSUE THREAD

**Issue by danielferromeral** [dependabot/dependabot-core#6874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### Manifest location and content before the Dependabot update

./pom.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>COMPANY</groupId>
  <artifactId>PROJECT</artifactId>
  <name>PROJECT</name>
  <packaging>pom</packaging>
  <version>VERSION</version>

  <modules>
    <module>...</module>
  </modules>

  <properties>
    <COMPANY_DEPENDENCIE_VERSION>23.1.2</COMPANY_DEPENDENCIE_VERSION>
    ...
  </properties>
  <build>
    ...
  </build>
  <dependencies>
    <dependency>
      <groupId>COMPANY.PROJECT_DEPENDENCIE</groupId>
      <artifactId>COMPANY_DEPENDENCIE</artifactId>
      <version>${COMPANY_DEPENDENCIE_VERSION}</version>
      <scope>provided</scope>
    </dependency>
    ...
 </dependencies>
</project>
```

### dependabot.yml content

```yml
version: 2

registries:
  maven-nexus:
    type: maven-repository
    url: COMPANY_NEXUS_REPOSITORY
    username: USER
    password: PASSWORD

updates:
  - package-ecosystem: "maven"
    target-branch: "main"
    directory: "/"
    reviewers:
      - TEAM
    registries:
      - maven-nexus
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Madrid"
    allow:
      - dependency-name: "*COMPANY*"
```

### Updated dependency

Bump COMPANY_DEPENDENCY from 23.1.2 to 23.3.0-6-j39dj27sh

### What you expected to see, versus what you actually saw

I expected to see:
- Bump COMPANY_DEPENDENCY from 23.1.2 to 23.3.0

But I got:
- Bump COMPANY_DEPENDENCY from 23.1.2 to 23.3.0-6-j39dj27sh

Dependabot used the latest versions, but that was unstable, it should have used the latest stable version
