### ISSUE TITLE
Authenticate with private registry/Azure artifacts on Azure pipelines 

### ISSUE THREAD

**Issue by vaishnav-canarys** [dependabot/dependabot-core#6876]
Hi ,

**Agent: Azure Cloud Hosted ubuntu-latest**
**pipeline: yaml**

I have currently setup a azure pipelines yaml, and i am using dependabot to perform version updates from packages in azure artifacts. Please suggest the best way to specify the credentials to azure artifacts so my dependabot script can authenticate to do version updates. Below is the pipeline snippet showing the current dependabot configuration. 

```
trigger: none
displayName: Every day at 2:25am UTC
  branches:    include:    - main
jobs:
- job: dependabot
  displayName: Dependabot Execution
  pool:    
    vmImage: ubuntu-latest
  variables:  
  - name: DIRECTORY_PATH
    value: /
  - name: PACKAGE_MANAGER
    value: maven
  - name: PROJECT_PATH
    value: 'SW4ZF/$(System.TeamProject)/_git/$(Build.Repository.Name)'  
 steps:  
  - script: git clone https://github.com/dependabot/dependabot-script.git
    displayName: Clone Dependabot repository
  - script: |      
        cd dependabot-script      
        docker build -t "dependabot/dependabot-script" -f Dockerfile .    
     displayName: Build Dependabot Image  
    - script: |      
         docker run --rm -e AZURE_ACCESS_TOKEN='$(System.AccessToken)' \                      
         -e  PACKAGE_MANAGER='$(PACKAGE_MANAGER)' \                      
         -e PROJECT_PATH='$(PROJECT_PATH)' \                     
         -e DIRECTORY_PATH='$(DIRECTORY_PATH)' \                      
         -e DEPENDABOT_EXTRA_CREDENTIALS='$(System.AccessToken)' \                     
          dependabot/dependabot-script || true    
       displayName: Run Dependabot    
       continueOnError: true
 
```

Error received

```
The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): [https://pkgs.dev.azure.com/{organisation}/{project}/_packaging/{feed-name}/maven/v1](https://pkgs.dev.azure.com/%7Borganisation%7D/%7Bproject%7D/_packaging/%7Bfeed-name/maven/v1) (Dependabot::PrivateSourceAuthenticationFailure)
```
