### ISSUE TITLE
Allow wildcards in `target-branch`

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [dependabot/dependabot-core#6890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

This is a complement to:
* #2511

I have a project where branches that are not being actively maintained are just removed, so I want to enable dependabot basically in all branches matching a wildcard, so I don't have to update the dependabot file every time we release a new branch or stop supporting an old branch.

Copying the example in #2511, I suggest:

```yaml
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: "v*"
  labels:
    - "3. to review"
    - "feature: dependencies"
```
