### ISSUE TITLE
Identical Version Tags of Docker Images in Helm Values Files are not Differentiated

### ISSUE THREAD

**Issue by imRentable** [dependabot/dependabot-core#6891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### dependabot.yml content
```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

registries:
  nexus: # Define access for a private registry
    type: docker-registry
    url: company.nexus.com
    username: ${{ secrets.NEXUS_USERNAME }}
    password: ${{ secrets.NEXUS_PASSWORD }}

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/helm/charts/app" # Location of package manifests
    registries:
      - nexus # Allow version updates for dependencies in this registry
    schedule:
      interval: "weekly"
```

### Updated dependency

foo: from `1.0.0` to `1.0.1`
bar: from `1.0.0` to `1.0.14`

These are just example dependencies that correspond to internal images at our organization.

## Image Dependencies in `/helm/charts/app/values.yaml`

```
fooDependency:
  image:
    repository: foo
    tag: "1.0.0"
    registry: company.nexus.com

barDependency:
  image:
    repository: bar
    tag: "1.0.0"
    registry: company.nexus.com
```

## Expectation

Two pull requests where one updates the `foo` tag to the latest version and the other updates the `bar` tag to the latest version.

## Actual 

Two pull requests where one updates the `foo` **and** `bar` tag to the latest version of `foo` and the other updates the `foo` **and** `bar`  tag to the latest version of `bar`.

There is already a [TODO](https://github.com/dependabot/dependabot-core/blob/e64b21e4304b98570a585b8ed6fd74cd90142cfb/docker/lib/dependabot/docker/file_updater.rb#L166) within the corresponding code file that points out that the aforementioned scenario could lead to problems. As a workaround, I moved these dependencies into their own values file which leads to the expected behaviour. However, this is quite inconvenient.
