### ISSUE TITLE
[Docker] Update docker images declared in `action.yaml` files

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add option in dependabot to parse docker images declared in `action.yaml` files

Example file 

```yml

runs:
  using: 'composite'
  steps:
    - name: Run
      shell: bash
      run: >
        docker run ubuntu@sha256:7a57c69fe1e9d5b97c5fe649849e79f2cfc3bf11d10bbd5218b4eb61716aebe6
```
