### ISSUE TITLE
Bundler: Dependabot downgrades a direct dependency during update of another

### ISSUE THREAD

**Issue by jakecoffman** [dependabot/dependabot-core#6895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

2.3.24

### Language version

3.1.2

### What you expected to see, versus what you actually saw

This dependency downgraded while upgrading activesupport: `govuk_app_config (0.1.0)`

### Images of the diff or a link to the PR, issue, or logs

https://github.com/alphagov/email-alert-monitoring/pull/91

### Smallest manifest that reproduces the issue

You can use the Dependabot CLI to create this issue:

```yaml
job:
  package-manager: bundler
  source:
    provider: github
    repo: alphagov/email-alert-monitoring
    directory: "/."
    commit: e7190f270fd58cdf5f1f6f19854216f795babe11
  dependencies:
    - activesupport
  allowed-updates:
    - dependency-name: activesupport
```
