### ISSUE TITLE
Dependabot fails when upgrade found 

### ISSUE THREAD

**Issue by jozephp** [dependabot/dependabot-core#6896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### Language version

go 1.18.10

### dependabot.yml content

```yaml
# Maintain dependencies for gomod everyday
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Dependabot:Gomod:"
```

### What you expected to see, versus what you actually saw

I was expecting to see the dependency check sees a upgrade and hence proceeds ahead raising a PR but what i observe is an error 
```
Checking if github.com/Azure/azure-sdk-for-go 67.3.0+incompatible needs updating
Requirements to unlock own
Requirements update strategy 
Error working on updates for github.com/Azure/azure-sdk-for-go 67.3.0+incompatible (continuing)
bin/update-script.rb:223:in `match?': target of repeat operator is not specified: /*/ (RegexpError)
	from bin/update-script.rb:223:in `block in allow_conditions_for'
	from bin/update-script.rb:223:in `each'
	from bin/update-script.rb:223:in `find'
	from bin/update-script.rb:223:in `allow_conditions_for'
	from bin/update-script.rb:601:in `block in <main>'
	from bin/update-script.rb:533:in `each'
	from bin/update-script.rb:533:in `<main>'
```
```
Checking if golang 1.18.10 needs updating
Requirements to unlock own
Requirements update strategy 
Error working on updates for golang 1.18.10 (continuing)
bin/update-script.rb:223:in `match?': target of repeat operator is not specified: /*/ (RegexpError)
	from bin/update-script.rb:223:in `block in allow_conditions_for'
	from bin/update-script.rb:223:in `each'
	from bin/update-script.rb:223:in `find'
	from bin/update-script.rb:223:in `allow_conditions_for'
	from bin/update-script.rb:601:in `block in <main>'
	from bin/update-script.rb:533:in `each'
	from bin/update-script.rb:533:in `<main>'
Done

```
