### ISSUE TITLE
[Github Actions] Allow discovery of workflows from other keys besides `uses`

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#6897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Normally, dependabot [detects workflows](https://github.com/dependabot/dependabot-core/blob/main/github_actions/lib/dependabot/github_actions/file_parser.rb#LL39C2-L55C32
) from the `uses` key within a workflow

In our use case, we're defining and passing workflows as arguments to other workflows. I'd like to receive upgrades for them as well

```yml

test:
    name: 🔮 Test
    uses: org/.github/.github/workflows/update-checker.yml@sha
    with:
      workflow_version: |
        org/repo/.github/workflows/checker.yml@hash
        org/repo/.github/workflows/other.yml@hash
```
