### ISSUE TITLE
Support for patch-based version bumps on dockerfiles

### ISSUE THREAD

**Issue by cvirtucio** [dependabot/dependabot-core#6909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello, dependabot team 👋 

We have docker images that follow a naming convention of `<language>-<major>.<minor>.<patch>-<platform>`. We noticed that [fetch_latest_version](https://github.com/dependabot/dependabot-core/blob/5120469e108e343a030ffc7159e23150d025a7d4/docker/lib/dependabot/docker/update_checker.rb#L146) essentially only [sorts](https://github.com/dependabot/dependabot-core/blob/5120469e108e343a030ffc7159e23150d025a7d4/docker/lib/dependabot/docker/update_checker.rb#L156) by [this regex](https://github.com/dependabot/dependabot-core/blob/5120469e108e343a030ffc7159e23150d025a7d4/docker/lib/dependabot/docker/update_checker.rb#L45) and picks up the [last one](https://github.com/dependabot/dependabot-core/blob/5120469e108e343a030ffc7159e23150d025a7d4/docker/lib/dependabot/docker/update_checker.rb#L158). So given a `FROM` statement that [references 2.4.0-slim](https://github.com/dependabot/dependabot-core/blob/main/docker/spec/dependabot/docker/update_checker_spec.rb#L199) and [this set of tags](https://github.com/dependabot/dependabot-core/blob/5120469e108e343a030ffc7159e23150d025a7d4/docker/spec/fixtures/docker/registry_tags/ruby_25.json#L212-L257), `2.5.0-slim` is recommended instead of `2.4.1-slim`.

Is there any plan to support patch-based version updates, somehow? If not, do you have any recommendations on how we can customize dependabot to have this behavior, through say a plugin or something similar?

Thank you!

**Comment by deivid-rodriguez** [comment]
Did you try something like

```
version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
```

**Comment by cvirtucio** [comment]
Hi David, thanks for responding.

[We have](﻿﻿https://github.com/cvirtucio/test-dependabot/blob/d0990a1478b3191b7dfe29e600ada0d9ac7be4d6/.github/dependabot.yml#L10-L12), but unfortunately [it still recommended a minor bump instead of a patch bump](https://github.com/cvirtucio/test-dependabot/pull/2/files).

**Comment by cvirtucio** [comment]
yup, that worked for us. and just mentioning this here for future readers since it's not explicitly described in the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore), you can include repository name and the image name like so:

```yaml
# given an image tag <account ID>.dkr.ecr.us-west-2.amazonaws.com/base/foo/bar/ruby:3.2.1-focal-jemalloc
version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "base/foo/bar/ruby"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
```
