### ISSUE TITLE
Failure to bump complex version tag.

### ISSUE THREAD

**Issue by matthew-parry-cc** [dependabot/dependabot-core#6948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
```

### What you expected to see, versus what you actually saw

 _Expected:_
Both Ruby and Alpine versions are bumped to the latest, without affecting major release:
`from 3.1.1-alpine3.15 to 3.1.3-alpine3.17 `

_Actual Outcome:_
Ruby version is bumped, but alpine version remains the same:
`from 3.1.1-alpine3.15 to 3.1.3-alpine3.15 `

Could the Alpine tag be being ignored as it is not in full semver version format?

### Smallest manifest that reproduces the issue

```
FROM ruby:3.1.1-alpine3.15 as base1
```
