### ISSUE TITLE
Support GitHub Actions that aren't exclusively in the `.github` directory

### ISSUE THREAD

**Issue by alexrosenfeld10** [dependabot/dependabot-core#6949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It's a fairly common scenario where an organization might centralize workflows / actions into a common repository, to make a "private action marketplace" if you will. Referencing these actions from a separate repo would look like:

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: NPM Setup
        uses: my-org/github-actions/team-name/path-to-action/npm-setup@1.0.0
```

As you can see here, in the `my-org/github-actions` repo, the path to the composite action is not `.github/**`. Instead, it's organized into a team level basis. From the docs, it appears that dependabot exclusively updates values in `.github/**`, which means composite actions will be missed. Can we make this path more configurable?
