### ISSUE TITLE
Dependabot does not send pr

### ISSUE THREAD

**Issue by karinarastsinskagia** [dependabot/dependabot-core#6958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Composer

### Package manager version

composer/semver  3.3.2  

### Language version

Php 8.1

### Manifest location and content before the Dependabot update

composer.json
```

{
    "name": "test/repo",
    "description": "",
    "require": {
        "illuminate/support": "^10.1",
        "jenssegers/agent": "^2.6",
        "phpunit/phpunit": "^10",
        "psr/simple-cache": "^2.0|^3.0",
        "react/promise": "^2.8",
        "spatie/laravel-package-tools": "^1.14",
    },
    "autoload": {
        "psr-4": {
            "Test\\Repo\\": "src/",
            "Test\\Repo\\Database\\Factories\\": "database/factories/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Test\\Repo\\Tests\\": "tests"
        }
    },
    "config": {
        "sort-packages": true,
    }
    }
}
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
```

### What you expected to see, versus what you actually saw

We have noticed that Dependabot is unable to create prs for packages which are identified as out of date. Particularly, despite the fact of detecting the packages newest versions, it fails to send a pull request  by displaying the message "Requirements to unlock update_not_possible".  

An example of this situation is shared below.

Does anyone know why this is happening and how to resolve it ?

Thank you

### Images of the diff or a link to the PR, issue, or logs

![Screenshot from 2023-03-31 14-54-36](https://user-images.githubusercontent.com/32904307/229113608-dc55f69b-2813-4577-9ecb-e223a4251510.png)

![Screenshot from 2023-03-31 14-49-23](https://user-images.githubusercontent.com/32904307/229113614-53bfa628-e82d-479d-a571-b81130c340db.png)

![Screenshot from 2023-03-31 14-48-57](https://user-images.githubusercontent.com/32904307/229113619-1b7e7eb1-eb4a-458d-9338-24a47ee54221.png)

![Screenshot from 2023-03-31 14-47-41](https://user-images.githubusercontent.com/32904307/229113627-a12b8941-6758-4993-b1e9-fdc27983d84b.png)

![Screenshot from 2023-03-31 14-48-25](https://user-images.githubusercontent.com/32904307/229113622-956007d7-ece2-481b-9df4-515910a47d09.png)
