### ISSUE TITLE
Dependabot can't upgrade certifi

### ISSUE THREAD

**Issue by rik** [dependabot/dependabot-core#6959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip-compile

### Package manager version

6.12.2

### Language version

Python 3.10

### Manifest location and content before the Dependabot update

Manifest:
[/requirements.in](https://github.com/betagouv/SPPNautInterface/blob/3c0d313958cd645b4bdb3113f7ee207d4c243c00/requirements.in)
[/dev-requirements.in](https://github.com/betagouv/SPPNautInterface/blob/3c0d313958cd645b4bdb3113f7ee207d4c243c00/dev-requirements.in)

Lock files:
[/requirements.txt](https://github.com/betagouv/SPPNautInterface/blob/3c0d313958cd645b4bdb3113f7ee207d4c243c00/requirements.txt)
[/dev-requirements.txt](https://github.com/betagouv/SPPNautInterface/blob/3c0d313958cd645b4bdb3113f7ee207d4c243c00/dev-requirements.txt)

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00" # UTC
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00" # UTC
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00" # UTC
```

[Link](https://github.com/betagouv/SPPNautInterface/blob/3c0d313958cd645b4bdb3113f7ee207d4c243c00/.github/dependabot.yml)

### Updated dependency

certifi from 2022.5.18.1 to 2022.12.7

#### Actual
certifi is not updated and dependabot says `The latest possible version of certifi that can be installed is 2022.5.18.1`

#### Expected
certifi is updated to 2022.12.7

I suspect the constraint in `dev-requirements.txt` to `requirements.txt` is tripping up dependabot. Ideally, it would update both lock files.

### Images of the diff or a link to the PR, issue, or logs

```
...
updater | 2023/03/31 08:23:29 INFO <job_635426589> Starting job processing
updater | 2023/03/31 08:23:33 INFO <job_635426589> Starting update job for betagouv/SPPNautInterface
updater | 2023/03/31 08:23:33 INFO <job_635426589> Checking if certifi 2022.5.18.1 needs updating
updater | 2023/03/31 08:23:34 INFO <job_635426589> Latest version is 2022.12.7
...
updater | 2023/03/31 08:24:03 INFO <job_635426589> Requirements to unlock update_not_possible
updater | 2023/03/31 08:24:03 INFO <job_635426589> Requirements update strategy bump_versions
updater | 2023/03/31 08:24:03 INFO <job_635426589> The latest possible version of certifi that can be installed is 2022.5.18.1
updater | 2023/03/31 08:24:03 INFO <job_635426589> The earliest fixed version is 2022.12.7.
updater | 2023/03/31 08:24:03 INFO <job_635426589> Finished job processing
updater | 2023/03/31 08:24:03 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +------------------------------+
updater | |            Errors            |
updater | +------------------------------+
updater | | security_update_not_possible |
updater | +------------------------------+
updater | time="2023-03-31T08:24:03Z" level=info msg="task complete" container_id=job-635426589-updater exit_code=0 job_id=635426589 step=updater
```
