### ISSUE TITLE
Support for updating devcontainer.json files (for dev containers)

### ISSUE THREAD

**Issue by apgrucza** [dependabot/dependabot-core#7000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Dev containers are growing in popularity. They are used in VSCode and GitHub Codespaces, and support is being added to other tools such as Gitpod. Dependabot itself even uses them [here](https://github.com/dependabot/dependabot-core/blob/main/.devcontainer/devcontainer.json).

Dependabot should support updating versions in the `devcontainer.json` file (specification [here](https://containers.dev/implementors/json_reference/)). This should include updating both the `image` and `features` properties.

Image example:

```json
{
  "image": "mcr.microsoft.com/devcontainers/go:1"
}
```

Features example (note that both [feature versions and package versions](https://containers.dev/implementors/features/#devcontainer-json-properties) can appear in this object):

```json
"features": {
  "ghcr.io/user/repo/go": {},
  "ghcr.io/user/repo1/go:1": {},
  "ghcr.io/user/repo2/go:latest": {},
  "https://github.com/user/repo/releases/devcontainer-feature-go.tgz": { 
        "optionA": "value" 
  },
  "./myGoFeature": { 
        "optionA": true,
        "optionB": "hello",
        "version" : "1.0.0"
  }
}
```

**Comment by jeffwidman** [comment]
👋 it's a good suggestion, we've had an internal team request this as well. 

No idea if/when we'll support this, given that we're (mostly) on pause for new ecosystems right now... long term we'd like to figure out a way to be more of a platform that others can build on top of so that if you wanted something you could build it yourself but that's still closer to a dream rather than reality.

For anyone else coming along, if adding support for this ecosystem is of interest please 👍 it as we use that as one signal of impact when prioritizing what to work on.

**Comment by hfhbd** [comment]
Do you also have a configuration sample for the yaml file to enable the devcontainers ecosystem?

**Comment by deivid-rodriguez** [comment]
Sorry, this is not yet fully released, let me reopen this and I'll share a link to documentation once it's working.

**Comment by chris-bateman** [comment]
Might be too early to try this but I did anyway :)
Purposely mistyped devcontainer to generate the below error - 
![image](https://github.com/dependabot/dependabot-core/assets/12206103/6fc9d18e-cbd6-422a-a15a-2db13c98503a)

So devcontainers is in the package list.

I then update it to use that and get this error - 
![image](https://github.com/dependabot/dependabot-core/assets/12206103/c26ccaf1-b100-42ca-b7c3-fdd3f033dc25)


Config used - 
```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "devcontainers" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
``` 

What am I missing?
