### ISSUE TITLE
npm bump not working: Dependabot::RepoNotFound

### ISSUE THREAD

**Issue by punkratz312** [dependabot/dependabot-core#7039]
Dependabot::RepoNotFound:

dependabot.yml
```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "02_Software/e2e-acceptance-test"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "02_Software/TherapyApp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "02_Software/TherapyExecutor/dsl"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "02_Software/TherapyExecutor/dsl-id-generator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "02_Software/TherapyExecutor/dsl-implementation"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "02_Software/TherapyExecutor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "02_Software/TherapyExecutor/executor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "02_Software/TherapyExecutor/scheduler"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "02_Software/TherapyExecutor/scheduler"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "02_Software/TherapyExecutor/serverless"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "02_Software/TherapyExecutor/serverless"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "02_Software/TherapyManager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "02_Software/TherapyManager/hasura"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "02_Software/TherapyManager/keycloak"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "02_Software/TherapyManager/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "02_Software/TherapyManager/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "02_Software/TherapyManager/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "02_Software/TherapyManager/backend"
    schedule:
      interval: "weekly"
```
.dependabot-gitlab-ci.yml
```
.dependabot:
  extends:
    - .executor
  stage: lint
  rules:
  #    - if: $CI_PIPELINE_SOURCE == "schedule"
  image:
    name: $DEPENDABOT_IMAGE
    entrypoint: [ "" ]
  variables:
    DEPENDABOT_IMAGE: docker.io/andrcuns/dependabot-gitlab:latest
    GIT_STRATEGY: none
    PROJECT_PATH: "127"
    SECRET_KEY_BASE: key
    SETTINGS__GITLAB_URL: $CI_SERVER_URL
    SETTINGS__LOG_COLOR: "true"
    SETTINGS__STANDALONE: "true"
  script:
    - echo $DEPENDABOT_IMAGE
    - echo $CI_SERVER_URL
    - echo $CI_PROJECT_NAME
    - echo $DIRECTORY
    - echo $PACKAGE_MANAGER
    - cd /home/dependabot/app
    - bundle exec rake "dependabot:update[$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME,$PACKAGE_MANAGER,$DIRECTORY]"

app-pub-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyApp"
    PACKAGE_MANAGER: "pub"
  extends:
    - .dependabot

tm-frontend-npm-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyManager/frontend"
    PACKAGE_MANAGER: "npm"
  extends:
    - .dependabot

tm-backend-npm-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyManager/backend"
    PACKAGE_MANAGER: "npm"
  extends:
    - .dependabot

td-npm-dependabot-lint:
  variables:
    DIRECTORY: "/"
    PACKAGE_MANAGER: "npm"
  extends:
    - .dependabot

tm-frontend-docker-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyManager/frontend"
    PACKAGE_MANAGER: "docker"
  extends:
    - .dependabot

tm-backend-docker-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyManager/backend"
    PACKAGE_MANAGER: "docker"
  extends:
    - .dependabot

e2e-gradle-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/e2e-acceptance-test"
    PACKAGE_MANAGER: "gradle"
  extends:
    - .dependabot


exe-gradle-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyExecutor"
    PACKAGE_MANAGER: "gradle"
  extends:
    - .dependabot

exe-scheduler-docker-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyExecutor/scheduler"
    PACKAGE_MANAGER: "docker"
  extends:
    - .dependabot

exe-serverless-docker-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyExecutor/serverless"
    PACKAGE_MANAGER: "docker"
  extends:
    - .dependabot

tm-docker-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyManager"
    PACKAGE_MANAGER: "docker"
  extends:
    - .dependabot

tm-hasura-docker-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyManager/hasura"
    PACKAGE_MANAGER: "docker"
  extends:
    - .dependabot

tm-keycloak-docker-dependabot-lint:
  variables:
    DIRECTORY: "02_Software/TherapyManager/keycloak"
    PACKAGE_MANAGER: "docker"
  extends:
    - .dependabot
```

docker is working fine:
Dockerfile

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/8830888/230903848-275aedd6-6292-4f19-bd77-a38a1584b612.png">

Error: see comments as i cant commit because too its big: There was an error posting your comment: Body is too long
