### ISSUE TITLE
Add a configuration boolean switch "enabled" to enable or disable the current dependabot actions for one repository

### ISSUE THREAD

**Issue by MaledongGit** [dependabot/dependabot-core#7072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Refs: https://github.com/dependabot/feedback/issues/216

From the previous discussion (sorry I didn't find related issues in the current issue list). We know that we can only disable dependabot for all repositories, it would be better if we can add a boolean switch through which we can decide whether the current config file can be "applied" or not for the dependabot actions. Something like this following (Take "enabled" as a switch example, if you miss writing it, the default means "true"):

```yml
version: 2
enabled: false ## This will enable/disable the current dependabot or not, missing it means "true" 
               ## UNLESS you set it "false" exclipitly
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
```

Ignore me if there're such related issues or has been fixed anyway....Without such settings, we have to remove the file and re-add it later.
