### ISSUE TITLE
Support for cargo dependencies using ssh://git@github.com

### ISSUE THREAD

**Issue by pocesar** [dependabot/dependabot-core#7079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Having this inside `.cargo/config`:

```toml
# .cargo/config
[net]
git-fetch-with-cli = true
```

makes currently impossible to have a dependency as:

```toml
# Cargo.toml
[dependencies]
some_dependency = { tag = "0.0.1", git = "ssh://git@github.com/org/repo.git" }
```

The current flow works fine with Docker, local dev and github actions (with [webfactory/ssh-agent](https://github.com/webfactory/ssh-agent)), only missing dependabot ability to do so

**Comment by AdamLeyshon** [comment]
I know this is a year old now but I hope this can be added soon. We have many internal crates that we use via Git+SSH that we would like dependabot to work with.

**Comment by gerriet-hinrichs** [comment]
I've managed to make it work with a configuration like this:

```yaml
# .github/dependabot.yaml
version: 2
updates:
  - package-ecosystem: "cargo"
    registries: "*" # <- have Dependabot use all available repos
    directory: "/"
    schedule:
      interval: "weekly"
registries:
  github-http: # as found in the private registry config docs
    type: git
    url: https://github.com
    username: ${{secrets.GIT_ACCESS_USER}}
    password: ${{secrets.GIT_ACCESS_TOKEN}}
  github-ssh: # similar to the one above but with an ssh url
    type: git
    url: ssh://git@github.com
    username: ${{secrets.GIT_ACCESS_USER}}
    password: ${{secrets.GIT_ACCESS_TOKEN}}
```

I've configured the two used secrets with:
 - `GIT_ACCESS_USER` as the actual GitHub user name (not just 'git')
 - `GIT_ACCESS_TOKEN` with the related GitHub access token (a classic one) that has the appropriate access rights (`repo`, `read:packages` in my case)

I also have a `.cargo/config.toml` with:
```toml
# .cargo/config.toml
[net]
git-fetch-with-cli = true
```
and the dependency specified with:
```toml
# Cargo.toml
[dependencies]
private_crate_name = { git = "ssh://git@github.com/your_org_or_user/private_repo.git", tag = "v1.0.0" }
```

It might be that you can further simplify the config, but this is good enough for me.

Dependabot was able to properly detect a version update in the git dependency and created a pull request with the tag change as expected. Even if you have a tag with a prefix like `some_path/v1.0.0`.

**Comment by v-thavaahariharangit** [comment]
With this [comment](https://github.com/dependabot/dependabot-core/issues/7079#issuecomment-2663131924) I am closing this ticket

**Comment by CramBL** [comment]
This does not work properly.

It doesn't update the `Cargo.toml` entry like it does with regular cargo ecosystem updates.

With Cargo you can add dependencies with e.g.

```
cargo add foo --git git+ssh://git@github.com/org/foo
```

Which will correctly add the current version of `foo` from that repository in your `Cargo.toml`

```toml
foo = { git = "git+ssh://git@github.com/org/foo", version = "0.1.0" }
```

That does not work with dependabot at all though, it will always fail to authenticate when performing dependabot updates.

If you REMOVE the leading `git+` and change it to a tag instead it will work as far as updating `Cargo.lock` but it does not touch `Cargo.toml`, which makes it super misleading, looks like you're on tag `v0.1.0` but really you might be on tag `v4.7.0`. Only way to find out is to read the lockfile, that is not really an acceptable solution.

All of these variants work just fine for Cargo, and it works just fine in GitHub actions, as long as you have SSH auth, but dependabot fails as described above.

```toml
foo = { git = "ssh://git@github.com/org/foo.git", tag = "v0.1.0" }
foo = { git = "ssh://git@github.com/org/foo", tag = "v0.1.0" }
foo = { git = "git+ssh://git@github.com/org/foo", tag = "v0.1.0" }
```

If it worked well with git tags it would be alright, but the proper solution is to work with cargo versions, such that you can use version constraints in the `Cargo.toml` just like with the regular cargo ecosystems.
