### ISSUE TITLE
Relative repo path urls fail for git operations

### ISSUE THREAD

**Issue by timfallmk** [dependabot/dependabot-core#7096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip, golan, npm, etc.

### Package manager version

latest/NA

### Language version

latest/NA

### dependabot.yml content

(applies to all dependabot, including gitlab and hosted github)

### What you expected to see, versus what you actually saw

Dependabot instances that point to github/gitlab installed at a relative path location fail to construct proper urls for clone logic and error with `RepoNotFound` errors.

(This issue was originally filed in https://gitlab.com/dependabot-gitlab/dependabot/-/issues/295#note_1344527276 for the `dependabot-gitlab` repo, but the relevant logic appears to be upstream in this repo, and would affect any installs at a relative path not just gitlab. More details can be found there if needed).

Very basically, the url construction logic for dependabot is different between non-`git` and `git` related operations. When dealing with non-git operations, the url is constructed from the appropriate relative path. When using git operations, the url is constructed with a hardcoded path pattern that matches the default install location, but will not match relative installs.
e.g. This works
```shell
https://gitbaseurl/team/repo
```
This does not
```shell
https://gitbaseurl/github/team/repo
```

This results in a difference in behavior depending on the package ecosystem. For package ecosystems that don't use git as part of their flow (e.g. `pip`), everything works. For package ecosystems that do use git (e.g. golang, npm, etc.), initial repo operations will work, but anything involving git (like `clone`s and `fetch`es) will not.

All of the correct information appears to exist, but it's not used to construct the url for git. I suspect this is due to the original tied-to-github-public nature of dependabot.

Relevant code: 
- https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/file_fetchers/base.rb#L612
- https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/source.rb#L127-L129

### Native package manager behavior

Native package managers (that use `git`) follow `remote` pathing.

### Images of the diff or a link to the PR, issue, or logs

See downstream gitlab issue for examples

### Smallest manifest that reproduces the issue

At an install like `https://baseurl/gitlab/`
This will work
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    rebase-strategy: auto
    auto-merge: false
```
This will not work
```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    rebase-strategy: auto
    target-branch: develop
```
