### ISSUE TITLE
Fails to detect letter case with gitmoji prefixed commit messages

### ISSUE THREAD

**Issue by ttytm** [dependabot/dependabot-core#7103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

cargo

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
    assignees:
      - tobealive
    commit-message:
      prefix: "⬆️ "

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
    assignees:
      - tobealive
    commit-message:
      prefix: "⬆️ "
```

### What you expected to see, versus what you actually saw

Dependabot won't detect the letter case after merging previous commits with lowercase. 

Commit message submitted by dependabot:
```
⬆️ Bump h2 from 0.3.16 to 0.3.17
```
Merged message:
```
⬆️ bump h2 from 0.3.16 to 0.3.17
```
Consecutive commits:
```
⬆️ Bump h2 from 0.3.16 to 0.3.17
```

### Images of the diff or a link to the PR, issue, or logs

This project uses the gitmoji code for its commit prefixes where the problem occurs.

https://github.com/tobealive/wthrr-the-weathercrab

Related issues I've searched and read include it's linked relatives:
* https://github.com/dependabot/feedback/issues/292
* https://github.com/dependabot/feedback/issues/74
