### ISSUE TITLE
PR isn't closed after cherry-picking Dependabot commit

### ISSUE THREAD

**Issue by hsz** [dependabot/dependabot-core#7105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

8.1

### Manifest location and content before the Dependabot update

`build.gradle.kts`:

```kotlin
plugins {
    alias(libs.plugins.kotlin)
}

version = "1.0.0"
group = "bar"

repositories {
    mavenCentral()
}
```

`gradle/libs.versions.toml`:

```toml
[versions]
kotlin = "1.8.10"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

I have initiated the repository with a single Kotlin plugin dependency in the `libs.versions.toml` file with an outdated version set: `1.8.10`.
After receiving the PR, I have cherry-picked Dependabot's commit with `1.8.20` version and pushed it to the `main` branch.

Unfortunately, Dependabot did not close the PR.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/hsz/dependabot-pr-not-closed-after-satisfying-update-request/pull/1

commit already cherry-picked to `main` here:
https://github.com/hsz/dependabot-pr-not-closed-after-satisfying-update-request/commit/8b45a0136195fcf2b53bde0d87e2ebfe01dc236b

### Smallest manifest that reproduces the issue

https://github.com/hsz/dependabot-pr-not-closed-after-satisfying-update-request
