### ISSUE TITLE
Support custom `update-types` (e.g. sub-patch versions)

### ISSUE THREAD

**Issue by sambostock** [dependabot/dependabot-core#7123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## What?

It would be nice if Dependabot allowed a mechanism for defining custom `update-types`.

## How?

Perhaps this could work via some sort of regex to normalize the version, whereby the consumer would provide a regex to extract the part of the version to compare by. Then if the extracted portions of the previous and new versions both match, Dependabot would ignore the version update.

```yaml
# ...
    ignore:
      - dependency-name: 'internal-gem-name'
        update-types: ['regex-diff:/^\d+\.\d+\.\d+(?:(?=\.\d+$)|$)/']
```

Given the above regular expression, all of the following would be equivalent, and Dependabot could know to consider the versions safe to ignore:

- `1.2.3`: `1.2.3`
- `1.2.3.1`: `1.2.3`
- `1.2.3.2`: `1.2.3`

If regular expressions are too complex, perhaps a more limited masking/matching syntax would be appropriate.

## Why?

We have an internal gem that includes a number of schema files. It extends Semver by adding a sub-patch component in it's version number, when the release exclusively adds a new schema file. That is:

```
MAJOR.MINOR.PATCH.SUBPATCH
^^^^^                      Updated on breaking API changes
      ^^^^^                Updated on compatible new API feature
            ^^^^^          Updated on compatible bug fixes
                  ^^^^^^^^ Updated on new schema file with no code changes
```

This gem is released very frequently (sub-patch released automatically every time someone merges in a new schema file). However, the only reason to do a sub-patch bump in the host app is if it needs to use one of the new schemas.

**As this creates a lot of noise, it would be nice if there was a way to tell Dependabot to ignore these sub-patch updates.**

Currently, the closest thing to supporting this is to ignore patch updates:

```yaml
# ...
    ignore:
      - dependency-name: 'internal-gem-name'
        update-types: ['version-update:semver-patch']
```

However, this has the downside of also ignoring bug fixes.
