### ISSUE TITLE
is there a way to test if we configured dependabot correctly?

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#7125]
is there a way to test if we configured dependabot correctly?

here is our YAML:
https://github.com/paulz/self-hosted-runner-example/blob/main/.github/dependabot.yml

```
# Set update schedule for GitHub Actions

# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
```

adding it to the repo did not do anything, do we just wait a week to see if works?

_Originally posted by @paulz in https://github.com/dependabot/dependabot-core/issues/2980#issuecomment-1512359544_
