### ISSUE TITLE
Docker image with multiple architectures is updated to the same tag

### ISSUE THREAD

**Issue by yeikel** [dependabot/dependabot-core#7144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### Manifest location and content before the Dependabot update

```

# https://github.com/zulu-openjdk/zulu-openjdk/blob/7e5fcfad3a22416db51719e4d80ca07004ac2f91/17-jre-headless-latest/Dockerfile
# https://hub.docker.com/r/azul/zulu-openjdk/tags?page=1&name=17-jre-headless

FROM azul/zulu-openjdk@sha256:59fe77a0432aa1393d3b8c8d0cf39b551c2516e899508fa809346b1fe9966d13 as zulu-amd64
FROM azul/zulu-openjdk@sha256:6292231e5fb042c01caa573f6ffeeb5da1b9c82586bff6086770b8ea42575cc7 as zulu-arm64

```

### dependabot.yml content

```yml

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule: 
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule: 
      interval: "daily"     
  - package-ecosystem: "docker"
    directory: "/"
    schedule: 
      interval: "daily"  


```

### Updated dependency

azul/zulu-openjdk

### What you expected to see, versus what you actually saw

I expected dependabot to either 

1. Create two separate pull requests
2. Create a single pull request where each entry is treated independently 

### Images of the diff or a link to the PR, issue, or logs

Pull request 

https://github.com/yeikel/dependabot-playground/pull/66/files

### Smallest manifest that reproduces the issue

```

# https://github.com/zulu-openjdk/zulu-openjdk/blob/7e5fcfad3a22416db51719e4d80ca07004ac2f91/17-jre-headless-latest/Dockerfile
# https://hub.docker.com/r/azul/zulu-openjdk/tags?page=1&name=17-jre-headless

FROM azul/zulu-openjdk@sha256:59fe77a0432aa1393d3b8c8d0cf39b551c2516e899508fa809346b1fe9966d13 as zulu-amd64
FROM azul/zulu-openjdk@sha256:6292231e5fb042c01caa573f6ffeeb5da1b9c82586bff6086770b8ea42575cc7 as zulu-arm64

```
