### ISSUE TITLE
Using secret for url field

### ISSUE THREAD

**Issue by VDuchauffour** [dependabot/dependabot-core#7191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello,
I tried to use a dependabot secret (or combinaison of ones) for the url field but it seems impossible. I always get an error message saying that it's not a proper http or https valid url.
I guess this due to a lack of templating ([issue here](https://github.com/dependabot/dependabot-core/issues/5750)) ?

To be more specific, my current `dependabot.yml` file that works for me is:

```yaml
registries:
  python-codeartifact:
    type: python-index
    url: https://XXX/pypi/XXX/simple/
    token: ${{secrets.CODEARTIFACT_USERNAME}}:${{secrets.CODEARTIFACT_AUTH_TOKEN}}
    replaces-base: false
```
But I would like to do something like this:

```yaml
registries:
  python-codeartifact:
    type: python-index
    url: ${{secrets.CODEARTIFACT_URL}}
    # or this
    # url: https://${{ secrets.CODEARTIFACT_DOMAIN }}-${{ secrets.CODEARTIFACT_DOMAIN_OWNER }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/pypi/${{ secrets.CODEARTIFACT_REPOSITORY }}/simple/
    token: ${{secrets.CODEARTIFACT_USERNAME}}:${{secrets.CODEARTIFACT_AUTH_TOKEN}}
    replaces-base: false
```
Is possible to use secret for the url field ?
Thank you
