### ISSUE TITLE
Unable to get Tags List from private Artifactory Registry (404 - missing "library" prefix)

### ISSUE THREAD

**Issue by mpoqq** [dependabot/dependabot-core#7210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Manifest location and content before the Dependabot update

```
FROM dockerhub-remote.private.artifactory.int/node:18.15.0
...
```

### dependabot.yml content

```
version: 2

registries:
  artifactory-docker:
    type: docker-registry
    url: dockerhub-remote.private.artifactory.int
    username: username
    password: ${{secrets.ARTIFACTORY_PASSWORD}}
    replaces-base: true
updates:
  - package-ecosystem: "docker"
    registries:
      - artifactory-docker
```

### What you expected to see, versus what you actually saw

I would expect that dependabot is able to update the node docker image version.
Instead I get following error: `Error processing node (DockerRegistry2::NotFound)`.
Dependabot tries to get the tags list via following url: `https://dockerhub-remote.private.artifactory.int:443/v2/node/tags/list` which returns 404. Valid url would be `https://dockerhub-remote.vegistry.vg.vector.int:443/v2/library/node/tags/list`. 
Some kind of logic to add `library` as prefix is already implemented https://github.com/dependabot/dependabot-core/blob/3cacb3999356ac04e2189170c6d27db6ad209acf/docker/lib/dependabot/docker/update_checker.rb#L306-L311, unfortunately only when the registry is dockerhub. 

Possible workaround is to add the `library` prefix in the dockerfile itself `FROM dockerhub-remote.private.artifactory.int/library/node:18.15.0`.

**Comment by ericpaul-8451** [comment]
I have the same issue, and have resorted to using the `library` prefix in my dockerfiles for these public resources. I don't like it very much, but it works. I'd like to know if this behavior is intended for some reason, or if this is a real bug?

**Comment by risset** [comment]
I also have this problem (dockerhub proxied to a private domain).

Would a possible solution for there to be some sort of default namespace/prefix option for registry configurations, that could then be set to "library"? If omitted and the domain is "registry.hub.docker.com", the current behaviour could remain the same.  

Some other software like argocd-image-updater are designed like this: https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/#configuring-a-registrys-default-namespace

**Comment by cedric-appdirect** [comment]
A solution that work for us is to move to run dependabot on a self hosted runner inside our infrastructure that has access to our private registry. See https://docs.github.com/en/enterprise-server@3.10/admin/github-actions/enabling-github-actions-for-github-enterprise-server/managing-self-hosted-runners-for-dependabot-updates .

**Comment by karrukola** [comment]
Sharing our experience, where also dockerhub is proxied to a private domain, we solved this problem by updating Artifactory configuration.

Here is Jfrog support's feedback :

> As for the second issue you raised, related to listing tags for mirrored images via a virtual repository, after further internal investigation, I was able to confirm that this is expected behavior.
This is due to the introduction of a new property designed to mitigate Docker rate limits by reducing the number of direct requests sent to remote repositories like docker.io or gcr.io.
Accordingly, I have modified the relevant Artifactory system property so that you can now retrieve the desired tags successfully through the virtual repository.

**Comment by v-thavaahariharangit** [comment]
Unable to reproduce the issue reported.


File used for testing

`Dockerfile`
```
# Use the image from JFrog Artifactory
FROM jfrogghdemo.jfrog.io/e2e-tests-dependabot-docker-repo/docker-package:1.0

# Optional: Add more layers or override behavior
WORKDIR /app
COPY . .
CMD ["node", "index.js"]
```

`github/dependabot.yml`
```
ersion: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - dockerhub

registries:
  dockerhub:
    type: docker-registry
    url: jfrogghdemo.jfrog.io
    username: thavaahariharangit@github.com
    password: ${{secrets.MY_DOCKERHUB_PASSWORD}}
    replaces-base: true
```

Test `docker-package` deployed in jfrog artifactory

<img width="1410" height="764" alt="Image" src="https://github.com/user-attachments/assets/9212b829-94b1-4385-b1d9-76143533f69c" />

And the PR generated by dependabot

<img width="1356" height="806" alt="Image" src="https://github.com/user-attachments/assets/b2998234-6b61-4a36-ab2c-4dc9c76a7ca5" />

WIth this note I am closing this ticket.
