### ISSUE TITLE
GitHub Actions with mixed versions not getting updated

### ISSUE THREAD

**Issue by radeksimko** [dependabot/dependabot-core#7214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

GitHub Actions

### Package manager version

2

### Manifest location and content before the Dependabot update

 - `.github/workflows/build.yml` - https://github.com/hashicorp/terraform-ls/blob/main/.github/workflows/build.yml
 - `.github/workflows/test.yml` - https://github.com/hashicorp/terraform-ls/blob/main/.github/workflows/test.yml

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies"]
```

### Updated dependency

No updates detected/suggested.

### What you expected to see, versus what you actually saw

 - Expected `actions/upload-artifact` to be upgraded from `v3.1.1` to `v3.1.2`.
   - `build.yml` has this Action pinned to `v3.1.1`, e.g. https://github.com/hashicorp/terraform-ls/blob/410c012bc4a46e644bad8333ba2ab2a77efba055/.github/workflows/build.yml#L54
   - There is another workflow `benchmarks.yml` with this Action [is already pinned](https://github.com/hashicorp/terraform-ls/blob/410c012bc4a46e644bad8333ba2ab2a77efba055/.github/workflows/benchmarks.yml#L70) to `v3.1.2`
 - Expected `actions/checkout` to be upgraded from `v3.5.0` to `v3.5.2`
   - One job in the `test.yml` workflow has this Action pinned to `v3.5.0` https://github.com/hashicorp/terraform-ls/blob/410c012bc4a46e644bad8333ba2ab2a77efba055/.github/workflows/test.yml#L20
   - The same Action within the same workflow [is already pinned](https://github.com/hashicorp/terraform-ls/blob/410c012bc4a46e644bad8333ba2ab2a77efba055/.github/workflows/test.yml#L38) to `v.3.5.2`

### Images of the diff or a link to the PR, issue, or logs

I found https://github.com/dependabot/dependabot-core/pull/6082 and https://github.com/dependabot/dependabot-core/issues/3750 which probably should have addressed this issue. Could this be just a caching problem somewhere then?
