### ISSUE TITLE
[PNPM] Branch name contains yarn

### ISSUE THREAD

**Issue by anehx** [dependabot/dependabot-core#7220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm 8.1.0

### Language version

Node.js 18

### Manifest location and content before the Dependabot update

https://github.com/projectcaluma/ember-caluma/blob/main/package.json
https://github.com/projectcaluma/ember-caluma/blob/main/packages/-ember-caluma/package.json
https://github.com/projectcaluma/ember-caluma/blob/main/packages/analytics/package.json
https://github.com/projectcaluma/ember-caluma/blob/main/packages/core/package.json
https://github.com/projectcaluma/ember-caluma/blob/main/packages/distribution/package.json
https://github.com/projectcaluma/ember-caluma/blob/main/packages/form-builder/package.json
https://github.com/projectcaluma/ember-caluma/blob/main/packages/form/package.json
https://github.com/projectcaluma/ember-caluma/blob/main/packages/testing/package.json
https://github.com/projectcaluma/ember-caluma/blob/main/packages/workflow/package.json

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      # graphql-tools v5+ breaks generic mocking
      - dependency-name: graphql-tools
        versions:
          - ">= 5"
      - dependency-name: graphql
        versions:
          - ">= 16"
      # 4.1.0 is broken
      - dependency-name: ember-apollo-client
        versions:
          - "4.1.0"
      # https://github.com/villander/ember-engines-router-service/issues/67
      - dependency-name: ember-engines-router-service
        versions:
          - ">= 0.4.0 <= 4.4.1"
```

### What you expected to see, versus what you actually saw

The branch name contains `yarn` but we use `pnpm`.

Current: `dependabot/npm_and_yarn/babel/core-7.21.8`
Expected: `dependabot/npm_and_pnpm/babel/core-7.21.8`

### Images of the diff or a link to the PR, issue, or logs

https://github.com/projectcaluma/ember-caluma/pull/2388
