### ISSUE TITLE
Dependabot frequently failing to raise PR for pub packages

### ISSUE THREAD

**Issue by cpswan** [dependabot/dependabot-core#7223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pub

### Package manager version

NA

### Language version

2.19.6

### Manifest location and content before the Dependabot update

[/packages/at_secondary_server/pubspec.yaml](https://github.com/atsign-foundation/at_server/blob/trunk/packages/at_secondary_server/pubspec.yaml)

### dependabot.yml content

```yaml
version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/tools/build_secondary"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/tools/build_virtual_environment/ve"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/tools/build_virtual_environment/ve_base"
    schedule:
      interval: "daily"     
  - package-ecosystem: "docker"
    directory: "/packages/at_root_server"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/at_secondary_server"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/tools" # Location of package manifests
    schedule:
      interval: "daily"
      
```

### Updated dependency

| Dependency | From version | To version |
|---|---|---|
| collection | 1.17.0 | 1.17.1 |
| basic_utils | 5.4.2 | 5.5.4 |
| meta | 1.8.0 | 1.9.1 |
| args | 2.3.1 | 2.4.0 |

### What you expected to see, versus what you actually saw

I'd expect to see a PR for the dependencies that need to be updated. Instead the [logs](https://gist.github.com/cpswan/9884347c0cddc7e29b6bb5bf9113fd45) show that a PR couldn't be raised:

They conclude with:

```
updater | 2023/05/03 10:40:54 INFO Results:
updater | Dependabot encountered '4' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | | Dependencies failed to update |
updater | +---------------+---------------+
updater | | collection    | unknown_error |
updater | | basic_utils   | unknown_error |
updater | | meta          | unknown_error |
updater | | args          | unknown_error |
updater | +---------------+---------------+
```

and on the way show ERROR block for each dependency like:

```
updater | 2023/05/03 10:40:17 ERROR <job_656542567> Error processing collection (Dependabot::ApiError)
updater | 2023/05/03 10:40:17 ERROR <job_656542567> {"errors":[{"status":500,"title":"Internal Server Error"}]}
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/api_client.rb:30:in `create_pull_request'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/service.rb:31:in `create_pull_request'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:250:in `create_pull_request'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:134:in `check_and_create_pull_request'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:65:in `check_and_create_pr_with_error_handling'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `block in perform'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `each'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `perform'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:72:in `run'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/05/03 10:40:17 ERROR <job_656542567> bin/update_files.rb:23:in `<main>'
```

### Native package manager behavior

NA

### Images of the diff or a link to the PR, issue, or logs

Logs are at https://gist.github.com/cpswan/9884347c0cddc7e29b6bb5bf9113fd45

**Comment by jakecoffman** [comment]
@cpswan I just pushed a fix for this on the server. Can you run the job again and verify it works now? Thanks!

**Comment by cpswan** [comment]
Thanks for the quick response @jakecoffman 

It's still saying `Dependabot encountered an unknown error` `Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details.`, but I'm seeing far less evidence of errors in the logs ([new gist](https://gist.github.com/cpswan/30215ec53a9e21f3c83ce53e06b9c337)). No sign of a PR though :(

There's also another dependency needing updating since yesterday, and better reporting of the changes that should be happening:

```
updater | +------------------------------------------------+
updater | |      Changes to Dependabot Pull Requests       |
updater | +---------+--------------------------------------+
updater | | created | args ( from 2.3.1 to 2.4.1 )         |
updater | | created | crypto ( from 3.0.2 to 3.0.3 )       |
updater | | created | collection ( from 1.17.0 to 1.17.1 ) |
updater | | created | basic_utils ( from 5.4.2 to 5.5.4 )  |
updater | | created | meta ( from 1.8.0 to 1.9.1 )         |
updater | +---------+--------------------------------------+
```

**Comment by jakecoffman** [comment]
@cpswan thanks for checking, looks like it made more progress. I made another change if you want to try again. I think this time it should put up some PRs. 🤞

**Comment by cpswan** [comment]
Thanks @jakecoffman the overnight run beat me to it...

This time I see a green tick before `Dependabot encountered an unknown error` rather than the usual red triangle, which is a bit weird. But still no PR.

![image](https://user-images.githubusercontent.com/478926/236409931-95604d05-5b1d-41ff-8e00-06e029552cb7.png)

I've put the latest logs in [another gist](https://gist.github.com/cpswan/fe1d2fe06b045d5db2b1e8b0d66d00da), though once again they don't have much to say about what went wrong in raising the PR.

**Comment by jakecoffman** [comment]
Dependabot is receiving the following error from GitHub when it tries to put up the PR:

```
422 - tree.path contains a malformed path component
```

I ran the Dependabot CLI to diagnose further: `dependabot update pub atsign-foundation/at_server --directory /packages/at_root_server -o out.yml`

In the `out.yml` the symlink mentioned [here](https://github.com/atsign-foundation/at_server/tree/trunk/tests/at_functional_test/lib/secondary/base) seems to be included in the update even though the symlink itself didn't change, just the contents of the file that it points to. 

That's probably a bug in Dependabot's Pub implementation we'll have to sort out.

**Comment by jakecoffman** [comment]
That error was due to running jobs without credentials in the CLI. I fixed it in #7277, so if you pull a new version of the pub updater it should work: `docker pull ghcr.io/dependabot/dependabot-updater-pub:latest`

It looks like the issue here is Pub considers all pubspecs under the directory that is configured: https://github.com/dependabot/dependabot-core/blob/03069cc49e07fb3b658b0a5f1bda900171d1889f/pub/lib/dependabot/pub/file_fetcher.rb#L27

So we should filter out symlinks since they're either already covered by the glob, or they're outside the directory and shouldn't be considered. I can fix that up soon.

**Comment by cpswan** [comment]
Some progress... I'm now seeing clean runs with the `dependabot` CLI and in Dependency Graph > Dependabot.

But, no PR actually raised. So it's still silently failing somewhere.

**Comment by sigurdm** [comment]
@cpswan  Has this improved since https://github.com/dependabot/dependabot-core/pull/7265 was deployed?

**Comment by cpswan** [comment]
@sigurdm sadly no improvement. The [logs](https://gist.github.com/cpswan/f5b897003dc50219e0a5c84a4c8f570f) conclude in a way that suggests that PRs have been raised:

```
updater | 2023/06/02 01:11:39 INFO Results:
updater | +------------------------------------------------+
updater | |      Changes to Dependabot Pull Requests       |
updater | +---------+--------------------------------------+
updater | | created | collection ( from 1.17.0 to 1.17.2 ) |
updater | | created | crypto ( from 3.0.2 to 3.0.3 )       |
updater | | created | meta ( from 1.8.0 to 1.9.1 )         |
updater | | created | yaml ( from 3.1.1 to 3.1.2 )         |
updater | | created | basic_utils ( from 5.4.2 to 5.5.4 )  |
updater | +---------+--------------------------------------+
```

But no actual PRs:

![image](https://github.com/dependabot/dependabot-core/assets/478926/8682c393-f485-4a9f-8e36-7ed26b8d83c0)

**Comment by sigurdm** [comment]
@jeffwidman not sure I understand those logs. Does this look like a problem with the pub integration?

**Comment by abdulapopoola** [comment]
Thanks @cpswan ; yes we're working on improving and surfacing actionable error messages. I hope this helps!

**Comment by cpswan** [comment]
After adding groups to my `dependabot.yml` it looks like things are working when they weren't before.

![image](https://github.com/dependabot/dependabot-core/assets/478926/920cc325-bcc4-49fd-8bf0-07d899676cdd)

But there's no actual PR from that run :(

Full logs in this gist: [825091200.log](https://gist.github.com/cpswan/ea29d919f4c1a81d41163f4c8d0a4876)

The pub section of my [dependabot.yml](https://github.com/atsign-foundation/at_server/blob/trunk/.github/dependabot.yml) now look like this:

```yml
  - package-ecosystem: "pub"
    directories:
      - "/packages/at_root_server"
      - "/packages/at_secondary_server"
    schedule:
      interval: "daily"
    groups:
      pub:
        patterns:
          - "*"     
```
