### ISSUE TITLE
Gems that require Ruby 3.0+ are giving updates when on Ruby 2.7.8 that don't run or work

### ISSUE THREAD

**Issue by broksonic21** [dependabot/dependabot-core#7257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

2.4.12

### Language version

2.7.8

### Manifest location and content before the Dependabot update

/Gemfile

### dependabot.yml content

```
package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    insecure-external-code-execution: deny
    commit-message:
      prefix: "[bundler] "
    allow:
      - dependency-type: "all"
 ```

### Updated dependency

plaid, for example ---> from 16.0.0 to anything beyond

same as selenium-webdriver (4.9.0) to 4.9.1 ( see https://github.com/SeleniumHQ/selenium/commit/cd3216e68dbc4ae61c0efae6e2969d5e18776bdb)

### What you expected to see, versus what you actually saw

Dependabot should either:

* Not propose a gem update that conflicts with ruby version (and perhaps a config for which ruby version to use, or read .ruby-version)
* have a separate error message in the Dependabot.yml to suggest ruby upgrade

Note: I am aware Ruby 2.7.8 is EOL (or soon to be), but dependabot can handle this better, in my opinion

### Native package manager behavior

it doesn't suggest an update is available when running `bundler update`

### Images of the diff or a link to the PR, issue, or logs

n/a

### Smallest manifest that reproduces the issue

.ruby_version of 2.7.8 (or any other way to set based on your environment.

A Gemfile with
```
gem "plaid",          "~> 16.0.0"
gem "selenium-webdriver", "~> 4.9.0"
```
