### ISSUE TITLE
Dependabot picking up wrong changelog for Go dependency

### ISSUE THREAD

**Issue by radeksimko** [dependabot/dependabot-core#7261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Go

### Language version

1.18

### Manifest location and content before the Dependabot update

`/go.mod` - https://github.com/hashicorp/hcl-lang/blob/9fa7f34dab856d0061f8dec48ddede3857faeaab/go.mod
`/go.sum` - https://github.com/hashicorp/hcl-lang/blob/9fa7f34dab856d0061f8dec48ddede3857faeaab/go.sum

### dependabot.yml content

https://github.com/hashicorp/hcl-lang/blob/9fa7f34dab856d0061f8dec48ddede3857faeaab/.github/dependabot.yml

```yml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies"]
```

### Updated dependency

`golang.org/x/tools` from 0.8.0 to 0.9.0

### What you expected to see, versus what you actually saw

**Expected to see** either no changelog, or just a summary pulled from tag description at [`v0.9.0`](https://github.com/golang/tools/releases/tag/v0.9.0)

**Actually saw** changelog pulled from a release/tag [`gopls/v0.9.0`](https://github.com/golang/tools/releases/tag/gopls%2Fv0.9.0).

### Images of the diff or a link to the PR, issue, or logs

https://github.com/hashicorp/hcl-lang/pull/273

<img width="865" alt="Screenshot 2023-05-09 at 10 43 15" src="https://user-images.githubusercontent.com/287584/237058659-87c9faed-48e0-4c2c-b47e-6b36ffc5aa39.png">
