### ISSUE TITLE
Grouped dependencies - Old PR not closing when new PR added by dependabot

### ISSUE THREAD

**Issue by planetf1** [dependabot/dependabot-core#7305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

8.0.2

### Language version

Java 17

### Manifest location and content before the Dependabot update

https://github.com/odpi/egeria/blob/main/bom/build.gradle

### dependabot.yml content

https://github.com/odpi/egeria/blob/main/.github/dependabot.yml

### Updated dependency

Handling several groups

```
  groups:
    spring:
      patterns:
        - "*spring*"
        - "*tomcat*"
    janusgraph:
      patterns:
        - "*janus*"
        - "*gremlin*"
        - "*elasticsearch*"
        - "*lucene*"
    slf4j:
      patterns:
        - "*slf4j*"
    jackson:
      patterns:
        - "com.fasterxml.*"
```

### What you expected to see, versus what you actually saw

When new updates were available within a dependency group, or the dependency group definition was changed, a new PR should be opened, and the old one closed (or the original updated)

What actually happened is I ended up with multiple PRs for each group

I suspect it was editing of the dependabot.xml that resulted in this behaviour, as I would have added additional wildcards to the group as I started experimenting

(Will close manually)

### Native package manager behavior

n/a

### Images of the diff or a link to the PR, issue, or logs

```
➜  egeria git:(dependabotgrp1) gh pr list | grep prototype
7674	Bump the jackson group with 2 updates	dependabot/gradle/jackson/prototype-1683827379	OPEN	2023-05-11 17:49:41 +0000 UTC
7673	Bump the spring group with 17 updates	dependabot/gradle/spring/prototype-1683827337	OPEN	2023-05-11 17:48:59 +0000 UTC
7667	Bump the janusgraph group with 16 updates	dependabot/gradle/janusgraph/prototype-1683825802	OPEN	2023-05-11 17:23:24 +0000 UTC
7666	Bump the jackson group with 2 updates	dependabot/gradle/jackson/prototype-1683825609	OPEN	2023-05-11 17:20:11 +0000 UTC
7665	Bump the spring group with 17 updates	dependabot/gradle/spring/prototype-1683825567	OPEN	2023-05-11 17:19:29 +0000 UTC
```
