### ISSUE TITLE
Dependabot failing to authenticate to Github Packages ruby registry, for all bundler dependencies not just ones stored in GHP

### ISSUE THREAD

**Issue by wwebster-rr** [dependabot/dependabot-core#7327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

Bundler 2.4.12

### Language version

ruby 2.7.8p225

### Manifest location and content before the Dependabot update

/Gemfile

### dependabot.yml content

```
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GITHUB_TOKEN }}
    replaces-base: false
  ruby-github:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/<MyORG>/github_api
    username: <my username>
    password: ${{ a PAT with all repo and packages perms }}
   replaces-base: false
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - ruby-github
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm" 
    directory: "/" # Location of package manifests
    registries:
      - npm-github
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    
  - package-ecosystem: "github-actions" #github actions dependencies,
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
```

### Updated dependency

Puma 3.12 -> 4.3.12

### What you expected to see, versus what you actually saw

I expect dependabot to either create a PR or error out because of transitive dependencies,  But we get this error instead:

Dependabot can't authenticate to a private package registry
The following private package registry was used and caused the update to fail: set --global rubygems.pkg.github.com.

Our Gemfile looks like this:
```
source 'https://rubygems.org'
ruby '2.7.8'

gem 'puma', '~> 3.11'

source 'https://rubygems.pkg.github.com/<myORG>' do
  gem '<MY_DEP>', '~> 2.5'
end
```

When I go to the https://rubygems.pkg.github.com:443/<MyORG>/versions link, it prompts for username and password, I provide my username and the PAT as the password and it goes through, so I know the authentication is working on its own.

### Images of the diff or a link to the PR, issue, or logs

`  proxy | 2023/05/16 14:47:31 proxy starting, commit: d719b9b9871e853c5fd63bf3552f3f857d979f3c
  proxy | 2023/05/16 14:47:31 Listening (:1080)
updater | 2023-05-16T14:47:32.871934870 [663577045:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-05-16T14:47:35Z" level=info msg="guest starting" commit=8ab4a20db815b67034070152643b9878c12b051d
updater | time="2023-05-16T14:47:35Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=663577045 updater_timeout=45m0s updater_version=49704c16cb0893c0ab8c5f884471c324baf39b83-bundler
updater | 2023/05/16 14:47:37 INFO Raven 3.1.2 ready to catch errors
updater | 2023/05/16 14:47:38 INFO <job_663577045> Starting job processing
  proxy | 2023/05/16 14:47:38 [002] GET https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp
  proxy | 2023/05/16 14:47:38 [002] * authenticating github api request with token for api.github.com
  proxy | 2023/05/16 14:47:39 [002] 200 https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp
  proxy | 2023/05/16 14:47:39 [004] GET https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp/git/refs/heads/main
  proxy | 2023/05/16 14:47:39 [004] * authenticating github api request with token for api.github.com
  proxy | 2023/05/16 14:47:39 [004] 200 https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp/git/refs/heads/main
  proxy | 2023/05/16 14:47:39 [006] GET https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp/contents/?ref=3e5322d6b15a5b45d84fc4ae5d23f1810c2a00da
  proxy | 2023/05/16 14:47:39 [006] * authenticating github api request with token for api.github.com
  proxy | 2023/05/16 14:47:39 [006] 200 https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp/contents/?ref=3e5322d6b15a5b45d84fc4ae5d23f1810c2a00da
  proxy | 2023/05/16 14:47:39 [008] GET https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp/contents/Gemfile.lock?ref=3e5322d6b15a5b45d84fc4ae5d23f1810c2a00da
  proxy | 2023/05/16 14:47:39 [008] * authenticating github api request with token for api.github.com
  proxy | 2023/05/16 14:47:39 [008] 200 https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp/contents/Gemfile.lock?ref=3e5322d6b15a5b45d84fc4ae5d23f1810c2a00da
  proxy | 2023/05/16 14:47:39 [012] GET https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp/contents/Gemfile?ref=3e5322d6b15a5b45d84fc4ae5d23f1810c2a00da
  proxy | 2023/05/16 14:47:39 [012] * authenticating github api request with token for api.github.com
  proxy | 2023/05/16 14:47:39 [012] 200 https://api.github.com:443/repos/<MyORG>/test-dependabot-ghp/contents/Gemfile?ref=3e5322d6b15a5b45d84fc4ae5d23f1810c2a00da
updater | 2023/05/16 14:47:40 INFO <job_663577045> Finished job processing
updater | time="2023-05-16T14:47:40Z" level=info msg="task complete" container_id=job-663577045-file-fetcher exit_code=0 job_id=663577045 step=fetcher
updater | 2023/05/16 14:47:41 INFO Raven 3.1.2 ready to catch errors
updater | 2023/05/16 14:47:43 INFO <job_663577045> Starting job processing
updater | 2023/05/16 14:47:43 INFO <job_663577045> Starting update job for <MyORG>/test-dependabot-ghp
updater | 2023/05/16 14:47:43 INFO <job_663577045> Checking if puma 3.12.6 needs updating
  proxy | 2023/05/16 14:47:44 [018] GET https://rubygems.org:443/api/v1/versions/puma.json
  proxy | 2023/05/16 14:47:44 [018] 200 https://rubygems.org:443/api/v1/versions/puma.json
updater | 2023/05/16 14:47:44 INFO <job_663577045> Latest version is 6.2.2
  proxy | 2023/05/16 14:47:45 [020] GET https://rubygems.pkg.github.com:443/<MyORG>/versions
  proxy | 2023/05/16 14:47:45 [020] 401 https://rubygems.pkg.github.com:443/<MyORG>/versions
  proxy | 2023/05/16 14:47:46 [022] GET https://rubygems.pkg.github.com:443/<MyORG>/versions
  proxy | 2023/05/16 14:47:46 [022] 401 https://rubygems.pkg.github.com:443/<MyORG>/versions
updater | 2023/05/16 14:47:46 INFO <job_663577045> Handled error whilst updating puma: private_source_authentication_failure {:source=>"set --global rubygems.pkg.github.com"}
updater | 2023/05/16 14:47:46 INFO <job_663577045> Finished job processing
updater | 2023/05/16 14:47:46 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +----------------------------------------------+
updater | |        Dependencies failed to update         |
updater | +------+---------------------------------------+
updater | | puma | private_source_authentication_failure |
updater | +------+---------------------------------------+
updater | time="2023-05-16T14:47:46Z" level=info msg="task complete" container_id=job-663577045-updater exit_code=0 job_id=663577045 step=updater`

### Smallest manifest that reproduces the issue

The manifest is linked but its a private registry so you cant use my manifest to reproduce it.
