### ISSUE TITLE
Dependabot does not respect ingored packages in security patches

### ISSUE THREAD

**Issue by NoNameProvided** [dependabot/dependabot-core#7341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

9.6.6

### Language version

Node 18.x LTS

### dependabot.yml content

```yml
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Budapest
  open-pull-requests-limit: 0
  versioning-strategy: increase
  commit-message:
    prefix: build
    include: scope
  ignore:
    - dependency-name: "husky"
      update-types: ["version-update:semver-major"]
```

### Updated dependency

```diff
diff --git a/package.json b/package.json
index d4b649f3..f88ac7fb 100644
--- a/package.json
+++ b/package.json
@@ -72,7 +72,7 @@
     "@typescript-eslint/parser": "^5.50.0",
     "eslint": "^8.33.0",
     "eslint-config-prettier": "^8.6.0",
-    "husky": "^4.3.8",
+    "husky": "^8.0.3",
     "jest": "^29.4.1",
     "lint-staged": "^13.1.0",
     "prettier": "^2.8.3",
```

### What you expected to see, versus what you actually saw

Dependabot update logic respects ignored versions from the `dependabot.yml` config file and no PR is created for this security alert.

### Native package manager behavior

Not applicable, NPM doesn't respect the Dependabot config file.
