### ISSUE TITLE
Dependabot couldn't find a pom.xml

### ISSUE THREAD

**Issue by j-koziel** [dependabot/dependabot-core#7347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### Package manager version

3.8.7

### Language version

Java 17

### Manifest location and content before the Dependabot update

/pom.xml -> https://github.com/j-koziel/wol-api/blob/dev/pom.xml

### dependabot.yml content

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
```

### What you expected to see, versus what you actually saw

I expected dependabot to make a pull request to update the vulnerable dependency but instead it just shows this error. What's strange is that the normal dependabot updates (not the security related ones) work perfectly fine. 

Screenshot showing that normal dependabot updates work fine:
![image](https://github.com/dependabot/dependabot-core/assets/68497216/9f9a58f7-9f47-448a-9250-5417c9c44388)

Screenshot showing the security update failing:
![image](https://github.com/dependabot/dependabot-core/assets/68497216/b0066856-c29f-4f48-8479-adb964a94547)

### Images of the diff or a link to the PR, issue, or logs

logs:
```
proxy | 2023/05/16 20:46:38 proxy starting, commit: d719b9b9871e853c5fd63bf3552f3f857d979f3c
  proxy | 2023/05/16 20:46:38 Listening (:1080)
updater | 2023-05-16T20:46:39.485070417 [663711530:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-05-16T20:46:41Z" level=info msg="guest starting" commit=8ab4a20db815b67034070152643b9878c12b051d
updater | time="2023-05-16T20:46:41Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=663711530 updater_timeout=45m0s updater_version=49704c16cb0893c0ab8c5f884471c324baf39b83-maven
updater | 2023/05/16 20:46:43 INFO Raven 3.1.2 ready to catch errors
updater | 2023/05/16 20:46:45 INFO <job_663711530> Starting job processing
  proxy | 2023/05/16 20:46:45 [002] GET https://api.github.com:443/repos/j-koziel/wol-api
  proxy | 2023/05/16 20:46:45 [002] * authenticating github api request with token for api.github.com
  proxy | 2023/05/16 20:46:45 [002] 200 https://api.github.com:443/repos/j-koziel/wol-api
  proxy | 2023/05/16 20:46:45 [004] GET https://api.github.com:443/repos/j-koziel/wol-api/git/refs/heads/dev
  proxy | 2023/05/16 20:46:45 [004] * authenticating github api request with token for api.github.com
  proxy | 2023/05/16 20:46:45 [004] 200 https://api.github.com:443/repos/j-koziel/wol-api/git/refs/heads/dev
  proxy | 2023/05/16 20:46:45 [006] GET https://api.github.com:443/repos/j-koziel/wol-api/contents/home/runner/work/wol-api/wol-api/pom.xml?ref=65b45e7bf01b2a99ea6abcdb5ff069e472460054
  proxy | 2023/05/16 20:46:45 [006] * authenticating github api request with token for api.github.com
  proxy | 2023/05/16 20:46:45 [006] 404 https://api.github.com:443/repos/j-koziel/wol-api/contents/home/runner/work/wol-api/wol-api/pom.xml?ref=65b45e7bf01b2a99ea6abcdb5ff069e472460054
updater | 2023/05/16 20:46:45 ERROR <job_663711530> Error during file fetching; aborting
updater | 2023/05/16 20:46:46 INFO <job_663711530> Finished job processing
updater | 2023/05/16 20:46:46 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------+
updater | |          Errors           |
updater | +---------------------------+
updater | | dependency_file_not_found |
updater | +---------------------------+
updater | time="2023-05-16T20:46:46Z" level=info msg="task complete" container_id=job-663711530-file-fetcher exit_code=0 job_id=663711530 step=fetcher
updater | time="2023-05-16T20:46:46Z" level=warning msg="failed during fetch, skipping updater" job_id=663711530
```

screenshot
![image](https://github.com/dependabot/dependabot-core/assets/68497216/1f8dad37-4414-4b35-9d11-5891fed0fb4d)
