### ISSUE TITLE
open-pull-requests-limit: 0 not being respected for yarn

### ISSUE THREAD

**Issue by zomgbre** [dependabot/dependabot-core#7353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

npm v9.2.0 yarn 1.21.1

### Language version

node v16.14.2

### dependabot.yml content
```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    open-pull-requests-limit: 0
```
### Updated dependency

One example:

Bumps aws-sdk from 2.1372.0 to 2.1381.0.

### What you expected to see, versus what you actually saw

I expect dependabot to open no pull requests, but it is still opening them.

Major reason for wanting this to work as intended is so that we can exclude dependabot alerts from our PR channel. The Slack integration (at least two months ago lol) did not have the ability to filter out dependabot PRs. :( 

### Smallest manifest that reproduces the issue

1. Create a node project using yarn.
2. Configure dependabot with the provided dependabot.yml.
3. Set one of the dependencies to a previous version.
4. Observe PR request.
