### ISSUE TITLE
Dependabot opens MRs even if disabled

### ISSUE THREAD

**Issue by Germandrummer92** [dependabot/dependabot-core#7361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

8.5.0

### Language version

v18.16.0

### dependabot.yml content

```yml
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# pnpm is not yet supported, will activate once https://github.com/dependabot/dependabot-core/issues/1736 is released
#  - package-ecosystem: "pnpm"
#    directory: "ts"
#    schedule:
#      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "ts/apps/next-automagically/"
    schedule:
      interval: "daily"

```

### Updated dependency

playwright-core 1.33.0 to 1.34.1

### What you expected to see, versus what you actually saw

Expected: no merge request to be openened.

Actual: merge request opened repeatedly even after closing it
