### ISSUE TITLE
Error to parse pyproject.toml on poetry>=1.5.0

### ISSUE THREAD

**Issue by jairhenrique** [dependabot/dependabot-core#7369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

poetry

### Package manager version

`>=1.5.0`

### Language version

python 3.11

### Manifest location and content before the Dependabot update

Poetry 1.5.0 introduces priority key to sources.

https://python-poetry.org/docs/master/repositories#default-package-source
https://python-poetry.org/docs/master/repositories#project-configuration

```toml
[[tool.poetry.source]]
  name = "PyPI"
  priority = "primary"

[[tool.poetry.source]]
  name = "PrivateFeed"
  url = "https://pkgs.dev.azure.com/privatefeed/_packaging/privatefeed/pypi/simple/"
  priority = "explicit"

[tool.poetry.dependencies.my_private_lib]
  version = "^3.7.5"
  source = "PrivateFeed"
```

### What you expected to see, versus what you actually saw

Error

```
updater | 2023/05/24 23:46:46 ERROR <job_667969159> Error processing psycopg2-binary (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/05/24 23:46:46 ERROR <job_667969159> The Poetry configuration is invalid:
updater |   - [source.0] Additional properties are not allowed ('priority' was unexpected)
```
