### ISSUE TITLE
Dependabot checks for update in the wrong registry

### ISSUE THREAD

**Issue by sapfelaft** [dependabot/dependabot-core#7371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

```yaml
version: 2
registries:
    npm-github:
        type: npm-registry
        url: https://npm.pkg.github.com
        token: ${{ secrets.DEPENDABOT_TOKEN }}
        replaces-base: true
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          time: "05:00"
          timezone: "Europe/Berlin"
      commit-message:
          prefix: "build(deps): "
      open-pull-requests-limit: 50
    - package-ecosystem: "npm"
      directory: "/"
      registries:
          - npm-github
      ignore:
          - dependency-name: "*"
            update-types: ["version-update:semver-major"]
      schedule:
          interval: "weekly"
          time: "05:00"
          timezone: "Europe/Berlin"
      commit-message:
          prefix: "build(deps): "
      open-pull-requests-limit: 50
```

### What you expected to see, versus what you actually saw

We have two repositories with the exact same configuration. Both have Dependabot enabled (see config) and both repositories have a npmrc file which contains the GitHub registry for the organization scope: `@organization:registry=https://npm.pkg.github.com` (we use a private npm package from our organization)

In the first repository, everything works as expected. See some logs here:

updater | 2023/05/22 04:03:04 INFO <job_665691547> Checking if react-router-dom 6.11.1 needs updating
updater | 2023/05/22 04:03:04 INFO <job_665691547> Ignored versions:
updater | 2023/05/22 04:03:04 INFO <job_665691547>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2023/05/22 04:03:04 [032] GET https://registry.npmjs.org:443/react-router-dom
  proxy | 2023/05/22 04:03:04 [032] 200 https://registry.npmjs.org:443/react-router-dom
  proxy | 2023/05/22 04:03:04 [034] GET https://registry.npmjs.org:443/react-router-dom/6.11.2
  proxy | 2023/05/22 04:03:04 [034] 200 https://registry.npmjs.org:443/react-router-dom/6.11.2
updater | 2023/05/22 04:03:04 INFO <job_665691547> Latest version is 6.11.2

updater | 2023/05/22 04:04:43 INFO <job_665691547> Checking if react 18.2.0 needs updating
updater | 2023/05/22 04:04:43 INFO <job_665691547> Ignored versions:
updater | 2023/05/22 04:04:43 INFO <job_665691547>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2023/05/22 04:04:43 [218] GET https://registry.npmjs.org:443/react
  proxy | 2023/05/22 04:04:43 [218] 200 https://registry.npmjs.org:443/react
  proxy | 2023/05/22 04:04:44 [220] GET https://registry.npmjs.org:443/react/18.2.0
  proxy | 2023/05/22 04:04:44 [220] 200 https://registry.npmjs.org:443/react/18.2.0
updater | 2023/05/22 04:04:44 INFO <job_665691547> Latest version is 18.2.0

Whereas in our second repository, some of the dependencies were looked up in the wrong registry:

updater | 2023/05/22 04:23:56 INFO <job_665689454> Checking if react-router-dom 6.11.2 needs updating
updater | 2023/05/22 04:23:56 INFO <job_665689454> Ignored versions:
updater | 2023/05/22 04:23:56 INFO <job_665689454>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2023/05/22 04:23:56 [078] GET https://registry.npmjs.org:443/react-router-dom
  proxy | 2023/05/22 04:23:56 [078] 200 https://registry.npmjs.org:443/react-router-dom
  proxy | 2023/05/22 04:23:56 [080] GET https://registry.npmjs.org:443/react-router-dom/6.11.2
  proxy | 2023/05/22 04:23:56 [080] 200 https://registry.npmjs.org:443/react-router-dom/6.11.2
updater | 2023/05/22 04:23:56 INFO <job_665689454> Latest version is 6.11.2

updater | 2023/05/22 04:23:56 INFO <job_665689454> Checking if react 18.2.0 needs updating
updater | 2023/05/22 04:23:56 INFO <job_665689454> Ignored versions:
updater | 2023/05/22 04:23:56 INFO <job_665689454>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2023/05/22 04:23:56 [082] GET https://npm.pkg.github.com:443/react
  proxy | 2023/05/22 04:23:56 [082] * authenticating npm registry request (host: npm.pkg.github.com, token auth)
  proxy | 2023/05/22 04:23:56 [082] 404 https://npm.pkg.github.com:443/react
  proxy | 2023/05/22 04:23:56 [084] GET https://npm.pkg.github.com:443/react
  proxy | 2023/05/22 04:23:56 [084] * authenticating npm registry request (host: npm.pkg.github.com, token auth)
  proxy | 2023/05/22 04:23:56 [084] 404 https://npm.pkg.github.com:443/react
updater | 2023/05/22 04:23:56 INFO <job_665689454> Handled error whilst updating react: private_source_authentication_failure {:source=>"npm.pkg.github.com"}

As you can see, for react-router-dom the right registry is accessed by both repositories, but for react the Dependabot of the second repository tries to get the data from the GitHub registry, which fails.

We have about 10 repositories, 8 of them are working fine whereas 2 of them are having problems. All the repositories share the same configuration for Dependabot and the npmrc file. 

Checking for the latest version of our test package, everything works as expected for both repositories:

updater | 2023/05/22 04:23:55 INFO <job_665689454> Checking if @organization/npm-package 0.6.2 needs updating
updater | 2023/05/22 04:23:55 INFO <job_665689454> Ignored versions:
updater | 2023/05/22 04:23:55 INFO <job_665689454>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2023/05/22 04:23:55 [060] GET https://npm.pkg.github.com:443/@organization%2Fnpm-package
  proxy | 2023/05/22 04:23:55 [060] * authenticating npm registry request (host: npm.pkg.github.com, token auth)
  proxy | 2023/05/22 04:23:55 [060] 200 https://npm.pkg.github.com:443/@organization%2Fnpm-package
  proxy | 2023/05/22 04:23:55 [062] GET https://npm.pkg.github.com:443/@organization%2Fnpm-package/0.6.2
  proxy | 2023/05/22 04:23:55 [062] * authenticating npm registry request (host: npm.pkg.github.com, token auth)
  proxy | 2023/05/22 04:23:55 [062] 405 https://npm.pkg.github.com:443/@organization%2Fnpm-package/0.6.2
updater | 2023/05/22 04:23:55 INFO <job_665689454> Latest version is 0.6.2
