### ISSUE TITLE
Docker image `mcr.microsoft.com/devcontainers/python` bumped from `0.204.3-3.11` to `3.11`

### ISSUE THREAD

**Issue by simensol** [dependabot/dependabot-core#7378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Manifest location and content before the Dependabot update

`/Dockerfile`:

```txt
# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/devcontainers/python:0.204.3-3.11
```

### dependabot.yml content

```yml
version: 2
updates:
    - package-ecosystem: "docker"
      directory: "/"
      open-pull-requests-limit: 10
      allow:
          - dependency-type: "all"
      ignore:
          - dependency-name: "mcr.microsoft.com/devcontainers/python"
```

### What you expected to see, versus what you actually saw

Dependabot raises a PR with a bump of `mcr.microsoft.com/devcontainers/python` from `0.204.3-3.11` to `3.11`.

I expected Dependabot to bump `mcr.microsoft.com/devcontainers/python` from `0.204.3-3.11` to `0.204.9-3.11`, since this is the latest image with Python 3.11 according to the [list of available tags](https://mcr.microsoft.com/v2/devcontainers/python/tags/list).
