### ISSUE TITLE
Nuget update of .config/dotnet-tools.json is not correct

### ISSUE THREAD

**Issue by kaby76** [dependabot/dependabot-core#7390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

NuGet Version: 5.11.0.10

### Language version

Dotnet 7.0.400-preview.23225.8

### Manifest location and content before the Dependabot update

* /console contains a CSharp console program.
```
Console.WriteLine("Hello, World!");
```
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>test_dependabot</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```
* /.config contains the dotnet-tools.json file.
```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "trgen": {
      "version": "0.20.20",
      "commands": [
        "trgen"
      ]
    }
  }
}
```
* `dotnet tool restore` in /console correctly restores the tools.
/console should NOT contain .config/; it should be at /.

### dependabot.yml content

version: 2
# enable-beta-ecosystems: true
updates:
  - package-ecosystem: "nuget"
    directory: "/console"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"

### Updated dependency

trgen

### What you expected to see, versus what you actually saw

"dotnet tool restore" works from /console or even /. This is correct behavior.

The problem is that there is an assumption in the dependabot-core code that whatever reason, the .config/ directory *must* exist where the .csproj file resides. This is BS. Consequently, the tool dependency doesn't get updated by dependabot.

It would be preferable if I could add an update to /.config explicitly.
```
version: 2
# enable-beta-ecosystems: true
updates:
  - package-ecosystem: "nuget"
    directory: "/console"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/.config"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
```

The workaround, really distasteful, is to create a fake.csproj file in /. This fake.csproj file isn't really used, but is provided to get Dependabot to update the tool dependency.
```
version: 2
# enable-beta-ecosystems: true
updates:
  - package-ecosystem: "nuget"
    directory: "/console"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "infrastructure"
      - "dependencies"
```
