### ISSUE TITLE
Dependabot tries to bump PHP 8.2.6 to 8.3.0alpha1-fpm / 8.3.0beta2-fpm-bullseye

### ISSUE THREAD

**Issue by ruudk** [dependabot/dependabot-core#7416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Language version

8.3

### Manifest location and content before the Dependabot update

8.2.6

### dependabot.yml content

```yaml
version: 2
updates:
- package-ecosystem: docker
  directory: "/etc/php-fpm"
  rebase-strategy: disabled
  ignore:
    - dependency-name: php
      versions: [">= 8.3.0"]
```

### What you expected to see, versus what you actually saw

8.2.7 (because we're on 8.2.6 and 8.2.7 is newly released)

8.3.0 we have excluded, but somehow that doesn't work for alpha releases?

**Comment by ruudk** [comment]
Today it proposed this again:
> Bump php from 8.2.7-fpm-bullseye to 8.3.0alpha3-fpm-bullseye in /etc/php-fpm

This doesn't make any sense.

**Comment by ruudk** [comment]
Today I received another bump:
> Bump php from 8.2.8-fpm-bullseye to 8.3.0beta2-fpm-bullseye in /etc/php-fpm

**Comment by deivid-rodriguez** [comment]
Hei! Thanks for sticking with us and logging the different issues you're getting.

I tried to reproduce this at https://github.com/dsp-testing/dependabot-core-7416/pull/2, but I think I'm late because https://hub.docker.com/layers/library/php/8.2.9-fpm-bullseye/images/sha256-45b0a2a588f2d0589aff73d092c461019d39710787d7e658aff0a2d6a3511049?context=explore was pushed a few hours ago and things are working as expected again.

I'm adding some logging at #7842 to make this easier to figure out next time it happens.

Can you share the update logs and the exact configuration you are using? The configuration you posted does not seem valid because it doesn't define a `schedule`.

Thanks!

**Comment by ruudk** [comment]
Thanks @deivid-rodriguez 💙 

Here's the full config:
```yaml
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  open-pull-requests-limit: 20
  schedule:
    interval: "daily"
    time: "06:00"
    timezone: Europe/Amsterdam
- package-ecosystem: docker
  directory: "/etc/php-fpm"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 20
  rebase-strategy: disabled  
  ignore:
  - dependency-name: php
    versions: [">= 8.3.0"]
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 20
  rebase-strategy: disabled
  groups:
    symfony:
      patterns:
        - "symfony/*"
    php-http:
      patterns:
        - "php-http/*"
```

Some snips from the logs:
```
updater | 2023/08/18 04:20:31 INFO <job_710768610> Starting job processing
updater | 2023/08/18 04:20:31 INFO <job_710768610> Starting update job for org/repo
updater | 2023/08/18 04:20:31 INFO <job_710768610> Checking all dependencies for version updates...
updater | 2023/08/18 04:20:31 INFO <job_710768610> Checking if php 8.2.8-fpm-bullseye needs updating
updater | 2023/08/18 04:20:31 INFO <job_710768610> Ignored versions:
updater | 2023/08/18 04:20:31 INFO <job_710768610>   >= 8.3.0 - from .github/dependabot.yml
// ....
updater | 2023/08/18 04:20:37 INFO <job_710768610> Latest version is 8.3.0beta2-fpm-bullseye
updater | 2023/08/18 04:20:37 INFO <job_710768610> Requirements to unlock own
updater | 2023/08/18 04:20:37 INFO <job_710768610> Requirements update strategy 
updater | 2023/08/18 04:20:37 INFO <job_710768610> Updating php from 8.2.8-fpm-bullseye to 8.3.0beta2-fpm-bullseye
updater | 2023/08/18 04:20:37 INFO <job_710768610> Submitting php pull request for creation
  proxy | 2023/08/18 04:20:37 [124] GET https://api.github.com:443/repos/org/repo/commits?per_page=100
  proxy | 2023/08/18 04:20:37 [124] * authenticating github api request with token for api.github.com
  proxy | 2023/08/18 04:20:37 [124] 200 https://api.github.com:443/repos/org/repo/commits?per_page=100
updater | 2023/08/18 04:20:38 INFO <job_710768610> Finished job processing
updater | 2023/08/18 04:20:38 INFO Results:
updater | +----------------------------------------------------------------------+
updater | |                 Changes to Dependabot Pull Requests                  |
updater | +---------+------------------------------------------------------------+
updater | | created | php ( from 8.2.8-fpm-bullseye to 8.3.0beta2-fpm-bullseye ) |
updater | +---------+------------------------------------------------------------+
updater | time="2023-08-18T04:20:38Z" level=info msg="task complete" container_id=job-710768610-updater exit_code=0 job_id=710768610 step=updater
```
