### ISSUE TITLE
Issue with npm lock file v3 and sub modules: "npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing."

### ISSUE THREAD

**Issue by ctsstc** [dependabot/dependabot-core#7441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

NPM: `9.5.1`

### Language version

Node: `18.16.0`

### Manifest location and content before the Dependabot update

- `./package.json`
- `./package-lock.json`

### dependabot.yml content

```yml
name: Dependabot Test

on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  dependabot:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_TOKEN }}
          submodules: 'recursive'

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 'Installing Packages'
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_TOKEN }}

      - name: Run Lint
        run: npm run lint:dry

      - name: Run Build
        run: npm run build:all:noemit

      - name: Run Tests
        run: npm run test
```

### What you expected to see, versus what you actually saw

npm packages should install successfully.

## What I Saw

`api-shared` is the submodule/package we're using.

```
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: api-shared@0.0.1 from lock file
npm ERR! Missing: @prisma/client@4.15.0 from lock file
npm ERR! Missing: @types/node@18.16.18 from lock file
... list continues for everything within the submodule's dependencies
```

### Smallest manifest that reproduces the issue

These have been provided above in the form of the dependabot build/test yml

### Related Issues

- #6270 (has been closed, but doesn't seem resolved?)
