### ISSUE TITLE
Dependabot tried to update this pull request, but something went wrong.

### ISSUE THREAD

**Issue by JohnnyDevNull** [dependabot/dependabot-core#7444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm ^9.5.1
Node ^18.16.0

#### dependabot.yml content

```
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: '04:00'
    # Disable rebasing for npm pull requests
    rebase-strategy: "disabled"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
```

#### package.json content
```
...
  "engines": {
    "node": "^18.16.0",
    "npm": "^9.5.1"
  },
...
```

#### .npmrc content
```
engine-strict=true
legacy-peer-deps=true
```

### What you expected to see, versus what you actually saw

- Dependabot does not open PR's anymore.
- Existing PR's can't be updated.

The bot just posts this on the PR's, also for triggering any command:
```
Dependabot tried to update this pull request, but something went wrong.
We're looking into it, but in the meantime you can retry the update by commenting @dependabot rebase.
```

- The Security Tab is empty
- The Insights > Dependency graph > Dependabot page shows just a package.json with an red exclamation mark, but no error message or anything helpful
