### ISSUE TITLE
pnpm: `private_source_authentication_failure` on private dependency

### ISSUE THREAD

**Issue by marcdeop** [dependabot/dependabot-core#7445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

pnpm `7.13.0`

### Language version

Node.js `16.14.0`

### Manifest location and content before the Dependabot update

`dependabot-test/pnpm/package.json`:
```
{
  "name": "ci-team-testlab",
  "private": true,
  "engines": {
    "node": ">=16.14"
  },
  "dependencies": {
    "@apollo/federation": "0.13.2",
    "apollo-server-express": "2.12.0",
    "@PRIVATE/PRIVATE_LIBRARY_A": "0.1.0",
    "@PRIVATE/PRIVATE_LIBRARY_B": "1.9.3",
    "@PRIVATE/PRIVATE_LIBRARY_C": "0.24.1"
  },
  "devDependencies": {
    "@babel/plugin-transform-modules-commonjs": "7.9.0",
    "chalk": "4.1.2"
  },
  "volta": {
      "node": "16.14.0",
      "pnpm": "7.13.0"
  }
}
```
`dependabot-test/pnpm/pnpm-lock.yaml`
I apologise for now adding the contents of the lock file but I don't want to risk the leak of private/confidential information

### dependabot.yml content

```
version: 2

registries:

  artifactory-npm:
    type: npm-registry
    url: https://${FQDN}:443/artifactory/api/npm/npm
    token: ${{secrets.DEPENDABOT_NPM}}
    replaces-base: true

updates:
  - package-ecosystem: "npm"
    directory: "/dependabot-test/npm"
    registries:
      - artifactory-npm
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/dependabot-test/pnpm"
    registries:
      - artifactory-npm
    schedule:
      interval: "daily"
```

### Updated dependency

`@PRIVATE/PRIVATE_LIBRARY_C` from version `0.24.1` to `0.27.1`

### What you expected to see, versus what you actually saw

We expect dependabot to create a PR with an update of the library ( `npm` works while `pnpm` fails).

Dependabot can access the registry and detect there is an update available:
```
...
updater | 2023/06/15 14:06:01 INFO <job_679034772> Checking if @PRIVATE/PRIVATE_LIBRARY_C 0.24.1 needs updating
...
proxy | 2023/06/15 14:06:02 [058] 200 https://${FQDN}:443/artifactory/api/npm/npm/@PRIVATE/PRIVATE_LIBRARY_C/0.27.1
updater | 2023/06/15 14:06:02 INFO <job_679034772> Latest version is 0.27.1
```

However, later on we see:
```
...
updater | 2023/06/15 14:06:37 INFO <job_679034772> Requirements to unlock own
updater | 2023/06/15 14:06:37 INFO <job_679034772> Requirements update strategy bump_versions
updater | 2023/06/15 14:06:37 INFO <job_679034772> Updating @PRIVATE/PRIVATE_LIBRARY_C from 0.24.1 to 0.27.1
  proxy | 2023/06/15 14:06:39 [919] GET https://registry.npmjs.org:443/@PRIVATE%2FPRIVATE_LIBRARY_C
  proxy | 2023/06/15 14:06:39 [920] GET https://registry.npmjs.org:443/pnpm
  proxy | 2023/06/15 14:06:39 [920] 200 https://registry.npmjs.org:443/pnpm
  proxy | 2023/06/15 14:06:39 [919] 404 https://registry.npmjs.org:443/@PRIVATE%2FPRIVATE_LIBRARY_C
  proxy | 2023/06/15 14:06:40 [922] GET https://${FQDN}:443/artifactory/api/npm/npm/@PRIVATE%2FPRIVATE_LIBRARY_C
  proxy | 2023/06/15 14:06:40 [922] * authenticating npm registry request (host: $FQDN, token auth)
  proxy | 2023/06/15 14:06:40 [922] 200 https://${FQDN}:443/artifactory/api/npm/npm/@PRIVATE%2FPRIVATE_LIBRARY_C
updater | 2023/06/15 14:06:40 INFO <job_679034772> Handled error whilst updating @PRIVATE/PRIVATE_LIBRARY_C: private_source_authentication_failure {:source=>"${FQDN}/artifactory/api/npm/npm"}
...
updater | 2023/06/15 14:06:41 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------------------------------------+
updater | |          Dependencies failed to update           |
updater | +----------+---------------------------------------+
updater | | @PRIVATE/PRIVATE_LIBRARY_C | private_source_authentication_failure |
updater | +----------+---------------------------------------+
updater | time="2023-06-15T14:06:41Z" level=info msg="task complete" container_id=job-679034772-updater exit_code=0 
```
