### ISSUE TITLE
Can't tell Dependabot to ignore an individual package if running grouped beta

### ISSUE THREAD

**Issue by broksonic21** [dependabot/dependabot-core#7461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 9.7.1

### Language version

node 18.16.1

### Manifest location and content before the Dependabot update

n/a

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    versioning-strategy: increase
    open-pull-requests-limit: 30
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
      time: "08:30"
      timezone: "America/New_York"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "@etchteam/storybook*"
```

### Updated dependency

storybook

### What you expected to see, versus what you actually saw

Really, storybook is just an example. let's say we wanted to ignore a patch version of it. We no longer can using grouped beta as you can't just "close" the PR like you can with individual. It would be nice to have a `@dependabot` command to ignore a specific package and have it removed from the PR.

**Comment by xt0rted** [comment]
I was just about to add grouped updates to one of my repos only to realize I won't be able to merge one of the groups for the foreseeable future.

There's a bug in the current version of jest's bundled typescript types when used with the latest `@types/jest` package. The bug has been fixed in jest for a few months, but a new release hasn't been made yet. Until then I need to ignore all updates to `@types/jest` since the build will always fail, but I do want everything else in the group to continue to be updated.

Adding an exclude pattern argument to `@dependabot recreate` and/or `@dependabot rebase` would be really helpful. At a high level it would take whatever pattern is passed in and append it to the list from in `dependabot.yml` for that group, then recreate or rebase. That would let me comment `@dependabot recreate exclude:@types/jest` on the `jest` group PR until a new release is published and the build passes.

**Comment by Nishnha** [comment]
Hi there is an `exclude-patterns` key available!

You should be able to do something along the lines of:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      typed:
        patterns:
          - "@types/*"
        exclude-patterns:
          - "@types/jest"
```

I'll update our documentation to include information about exclude patterns.
