### ISSUE TITLE
Dependabot doesn't update composite action file

### ISSUE THREAD

**Issue by metaclips** [dependabot/dependabot-core#7495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

I have a workflow as below

    ├── ...
    ├── .github
    │   ├── workflows
    │   │   └── a_workflow.yml                    # Workflow that uses a_reusable_workflow/action.yml composite action
    │   └── actions                               # Folder that contains reusable workflow
    │       └── a_reusable_workflow
    │           └── action.yml                    # A reusable workflow file
    └── ...

Using Dependabot to update GitHub actions with the below config updates only actions versions in the `a_workflow.yml` and not in the reusable `action.yml` files.
```yaml
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Component: CI/CD"
```

### dependabot.yml content

https://github.com/build-trust/ockam/blob/develop/.github/dependabot.yml

### What you expected to see, versus what you actually saw

All action version used in all yaml file get updated

**Comment by Jason3S** [comment]
@metaclips,

I have been running into the same issue.

I took a look at the [code](https://github.com/dependabot/dependabot-core/blob/main/github_actions/lib/dependabot/github_actions/file_fetcher.rb). It also looks for `action.yml` and `action.yaml` in the directory specified. Which means, there is workaround, a bit painful, but it works.

`.github/dependabot.yml`

```yaml
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/.github/actions/a_reusable_workflow"
    schedule:
      interval: "daily"
```

It means you will need to add an entry in `dependabot.yml` for every single `.github/actions` folder.
