### ISSUE TITLE
Private Repository credentials not used in rare case (without definition of https-port 443)

### ISSUE THREAD

**Issue by dangerground** [dependabot/dependabot-core#7514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Manifest location and content before the Dependabot update

/build.gradle

### dependabot.yml content

version: 2
registries:
 artifact-repository:
    type: maven-repository
    url: https://private-repository.example/artifactory/libs-release
    username: ${{secrets.ORG_ARTIFACTORY_USER}}
    password: ${{secrets.ORG_ARTIFACTORY_PASS}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - artifact-repository
    schedule:
      interval: "daily"

### What you expected to see, versus what you actually saw

I expected that Dependabot used the configured credentials from the `dependabot.yml`. This works in 60+ other repositories with the same configuration (copy&pasted config).

It didn't work in exactly one repository.

A Workaround was to configure an additional repository with the explicit https-port configured. This is only neccesary in one repository, all other repositories also access the private repository via https port (according to the Dependabot-logs).

```
version: 2
registries:
 artifact-repository:
    type: maven-repository
    url: https://private-repository.example/artifactory/libs-release
    username: ${{secrets.ORG_ARTIFACTORY_USER}}
    password: ${{secrets.ORG_ARTIFACTORY_PASS}}
 artifact-repository2:
    type: maven-repository
    url: https://private-repository.example:443/artifactory/libs-release
    username: ${{secrets.ORG_ARTIFACTORY_USER}}
    password: ${{secrets.ORG_ARTIFACTORY_PASS}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - artifact-repository
      - artifact-repository2
    schedule:
      interval: "daily"
```

Also this repository tried to access previously configured repositories, which are not used/configured for months and where no reference in the build-system exists.
