### ISSUE TITLE
Cannot configure grouped dependencies due to 50-character limit

### ISSUE THREAD

**Issue by yurishkuro** [dependabot/dependabot-core#7521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### dependabot.yml content

https://github.com/jaegertracing/jaeger/commit/ba6320fd68459615d6d31e4a24fefdf8ace58f4d

Relevant part:
```yaml
    groups:
      otel-collector:
        patterns:
          - "go.opentelemetry.io/collector*"
          - "github.com/open-telemetry/opentelemetry-collector-contrib/*"
```

### What you expected to see, versus what you actually saw

The `dependabot.yml` from the above commit was considered invalid:

```
The property '#/updates/0/groups/otel-collector/patterns/1' was not of a maximum string length of 50
```

The value I wanted to specify is naturally longer than 50 characters:
```
"github.com/open-telemetry/opentelemetry-collector-contrib/*"
```

As a workaround, I replaced some of it with another wildcard:
```
"github.com/open-telemetry/o*-collector-contrib/*"
```

I suspect there are other ecosystems where package names may be longer than 50 characters (e.g. in .NET)
