### ISSUE TITLE
Option to exclude a directory

### ISSUE THREAD

**Issue by spenserblack** [dependabot/dependabot-core#7522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'm surprised I didn't find any duplicates :laughing:

Basically, I think it would be nice to have an option like this:
```yaml
updates:
  - package-ecosystem: npm
    directory: "/"
    exclude:
      - "/packages/foo"  # maybe this could be a glob pattern?
```

******

I have a project with a root-level `package.json`, and two nested packages with their own `package.json` files. So basically this:
```
/package.json
/packages/foo/package.json
/packages/bar/package.json
```

In the root level there are some dev dependencies that I'm keeping up to date with `directory: "/"`. I also want to keep `foo` up-to-date, but I don't want to update `bar`.

Right now the best workaround seems to be to ignore all of the dependencies in `bar`.

As a side-note, when directories overlap, it possibly conflicts with the new group option?
With a config like this:
```yaml
updates:
  - package-ecosystem: npm
    directory: "/"
  - package-ecosystem: npm
    directory: "/packages/foo"
    groups:
      jest:
        patterns:
          - "jest"
          - "@jest/*"
```
It didn't seem to group the updates as expected. I'm guessing because the `"/"` update took precedence. An option to exclude a subdirectory could help with this.
