### ISSUE TITLE
exclude-patterns for groups not working when the patterns declares a `*` pattern

### ISSUE THREAD

**Issue by FrelliBB** [dependabot/dependabot-core#7523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### dependabot.yml content

https://github.com/FrelliBB/dependabot-grouping-test/blob/main/.github/dependabot.yml

### Updated dependency

https://github.com/FrelliBB/dependabot-grouping-test/pull/1

### What you expected to see, versus what you actually saw

When using `*` for `patterns` in addition to another dependency in `exclude-patterns` I expected it to work as a form of blocklist where all dependencies are upgraded except for the patterns specified. However in the PRs I link it appears that this is not working as expected.

I did not expect `spring-boot-starter-parent` and `spring-boot-starter-web` to be upgraded in the linked PR. Apologies if this is me misunderstanding how to use this configuration correctly. I was hoping we could find a way to only declare the dependencies that we _don't_ want to be grouped into a single PR.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/FrelliBB/dependabot-grouping-test/pull/1

### Smallest manifest that reproduces the issue

https://github.com/FrelliBB/dependabot-grouping-test

**Comment by FrelliBB** [comment]
I was missing the groupId prefix for the dependency. It needed to be:

```yaml
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    groups:
      non-critical-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "org.springframework.boot:spring-boot-*"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

```
