### ISSUE TITLE
Dependabot groups not working for TRPC

### ISSUE THREAD

**Issue by slimshreydy** [dependabot/dependabot-core#7524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NPM

### Package manager version

8.19.4

### Language version

Node 18.15.0

### Manifest location and content before the Dependabot update

`/package.json`

```
{
  "name": "project-name",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    ...
  },
  "dependencies": {
    "@trpc/client": "^10.33.0",
    "@trpc/next": "^10.33.0",
    "@trpc/react-query": "^10.33.0",
    "@trpc/server": "^10.33.0",
    ...
  },
}
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      # @trpc packages must be bumped in lockstep
      trpc:
        patterns:
          - "@trpc/server"
          - "@trpc/react-query"
          - "@trpc/next"
          - "@trpc/client"
```

### Updated dependency

@trpc/client updated from 10.33.0 to 10.34.0.
@trpc/next updated from 10.33.0 to 10.34.0.

### What you expected to see, versus what you actually saw
TRPC is a set of packages that all bump in lockstep. The 4 TRPC packages we use are all peer dependencies of each other.

We only saw 2 of the 4 expected bumps in `package.json`:
@trpc/client updated from 10.33.0 to 10.34.0
@trpc/next updated from 10.33.0 to 10.34.0

We were missing the following two bumps in `package.json`:
@trpc/react-query updated from 10.33.0 to 10.34.0.
@trpc/server updated from 10.33.0 to 10.34.0.

### Images of the diff or a link to the PR, issue, or logs

`package.json`:
![image](https://github.com/dependabot/dependabot-core/assets/10700914/ebddeaa1-4696-4f46-98c8-d9aceb58141c)

`package-lock.json`: As you can see, the `@trpc/server` and `@trpc/react-query` deps do get bumped, but ONLY in the lockfile. We're missing those bumps in the `package.json` itself. I figure this means the actual resolved set of packages is fine, but this will end up being confusing to us in the long term since it will seem like the trpc packages are out of sync whenever we manually review our `package.json`.
![image](https://github.com/dependabot/dependabot-core/assets/10700914/2f04aa38-dac1-424b-9464-b28992181685)
![image](https://github.com/dependabot/dependabot-core/assets/10700914/91068c79-506b-40ed-a3d1-74fd3fc4f03f)
![image](https://github.com/dependabot/dependabot-core/assets/10700914/70a2854c-846e-4d69-8861-beecfc9c519f)
