### ISSUE TITLE
Dependabot groups does not include all dependencies

### ISSUE THREAD

**Issue by v3gard** [dependabot/dependabot-core#7530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

8.3.1

### Language version

16.14.0

### Manifest location and content before the Dependabot update

/package.json

### dependabot.yml content

```yml
version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "sunday"
      open-pull-requests-limit: 10
      reviewers:
          - "equinor/kpd-team"
      groups:
          ag-grid:
              patterns:
                  - "*ag-grid-*"
                  - "*fusion-framework-module-ag-grid"
      ignore:
          # Ignore react/react-dom related major upgrades until Fusion support major version upgrade.
          - dependency-name: "react-dom"
            update-types: ["version-update:semver-major"]
          - dependency-name: "@types/react-dom"
            update-types: ["version-update:semver-major"]
          - dependency-name: "react"
            update-types: ["version-update:semver-major"]
          - dependency-name: "@types/react"
            update-types: ["version-update:semver-major"]
```

### What you expected to see, versus what you actually saw

 I expected all AG grid packges to be updated at the same time. Instead, some were left out, e.g.:
 
 * `@ag-grid-community/core`
 * `@ag-grid-community/react`

![image](https://github.com/dependabot/dependabot-core/assets/343078/b8eb2d5f-a961-4b88-807c-c67532719229)
