### ISSUE TITLE
Dependabot doesn't create PR

### ISSUE THREAD

**Issue by monaka** [dependabot/dependabot-core#7542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### Manifest location and content before the Dependabot update

https://github.com/pizzafactory-contorno/piatto/blob/main/debian-10.1/Dockerfile

### dependabot.yml content

```
version: 2
updates:
- package-ecosystem: docker
  directory: /alpine-3.10
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.10"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /alpine-3.15.0
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.15.0"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /alpine-3.16
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.16"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /alpine-3.17
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.17"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /alpine-3.18
  ignore:
  - dependency-name: alpine
    versions:
    - "!= 3.18"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-10
  ignore:
  - dependency-name: debian
    versions:
    - "!= 10.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-10.1
  ignore:
  - dependency-name: debian
    versions:
    - "!= 10.1.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-10.2
  ignore:
  - dependency-name: debian
    versions:
    - "!= 10.2.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-11.1
  ignore:
  - dependency-name: debian
    versions:
    - "!= 11.1.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /debian-9.11
  ignore:
  - dependency-name: debian
    versions:
    - "!= 9.11.pre.slim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-16.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "!= 16.04"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-18.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "!= 18.04"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-20.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "!= 20.04"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /ubuntu-22.04
  ignore:
  - dependency-name: ubuntu
    versions:
    - "!= 22.04"
  schedule:
    interval: daily
```

### Updated dependency

Update logs in Dependency-graph

```
updater | 2023/07/08 10:38:14 INFO <job_690289655> Finished job processing
updater | 2023/07/08 10:38:14 INFO Results:
updater | +--------------------------------------------------+
updater | |       Changes to Dependabot Pull Requests        |
updater | +---------+----------------------------------------+
updater | | created | debian ( from `a893719` to `1125379` ) |
updater | +---------+----------------------------------------+
updater | time="2023-07-08T10:38:15Z" level=info msg="task complete" container_id=job-690289655-updater exit_code=0 job_id=690289655 step=updater
```

### What you expected to see, versus what you actually saw

I expect a pull request is created.
I see no pull requests.
