### ISSUE TITLE
Grouped updates: Dependabot encountered an unknown error

### ISSUE THREAD

**Issue by bmulholland** [dependabot/dependabot-core#7549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### dependabot.yml content

```
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      timezone: "Asia/Tbilisi"
      time: "17:00"
    commit-message:
      # Use our PR title naming convention
      prefix: "UPGRADE - "
    groups:
      # Dependabot grouped updates:
      # Docs at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      # This is the name of your group, it will be used in PR titles and branch
      # names
      low-risk:
        patterns:
          - "core-js"
          - "nuxt-edge"
          - "@nuxt/*"
          - "postcss*"
          - "autoprefixer"
          - "@vue*"
          - "*jsdom*"
          - "*babel*"
          - "path-parse"
          - "^vue$"
          - "lodash"
          - "*typescript*"
          - "msw"
          - "chromatic"
          - "*storybook*"
          - "*faker*"
          - "*jest*"
          - "*chai*"
          - "*cypress*"
          - "*lint*"
          - "*prettier*"
          - "json5"
          - "husky"
          - "office-addin*"
            # matching all packages that start with "@types"
          - "@types*"
      high-risk:
        patterns:
          - "ahoy.js"
          - "@nylas/components-mailbox"
          - "vue-infinite-loading"
          - "vue-clamp"
          - "floating-vue"
          - "portal-vue"
          - "line-awesome"
          - "graphql*"
          - "@rails/actioncable"
          - "*apollo*"
          - "@nuxtjs/*"
          - "tailwindcss"
          - "@tailwindcss/forms"
          - "*sentry*"
        exclude-patterns:
          - "@nuxtjs/storybook"
```

### What you expected to see, versus what you actually saw

Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details.

```

updater | ➤ YN0007: │ recital-frontend@workspace:. must be built because it never has been before or the last one failed
updater | ➤ YN0009: │ recital-frontend@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-3833ad4b/build.log)
updater | ➤ YN0000: └ Completed in 43s 252ms
updater | ➤ YN0000: Failed with errors in 48s 193ms
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb:121:in `run_yarn_command'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:159:in `run_yarn_berry_top_level_updater'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:110:in `block (2 levels) in run_yarn_updater'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:107:in `chdir'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:107:in `block in run_yarn_updater'
updater | 	from /home/dependabot/common/lib/dependabot/shared_helpers.rb:187:in `with_git_configured'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:106:in `run_yarn_updater'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:79:in `run_current_yarn_update'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:60:in `block in updated_yarn_lock'
updater | 	from /home/dependabot/common/lib/dependabot/workspace/base.rb:26:in `block in change'
updater | 	from /home/dependabot/common/lib/dependabot/workspace/base.rb:26:in `chdir'
updater | 	from /home/dependabot/common/lib/dependabot/workspace/base.rb:26:in `change'
updater | 	from /home/dependabot/common/lib/dependabot/shared_helpers.rb:33:in `in_a_temporary_repo_directory'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:56:in `updated_yarn_lock'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:32:in `updated_yarn_lock_content'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:240:in `updated_yarn_lock_content'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:171:in `yarn_lock_changed?'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:199:in `block in updated_lockfiles'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:198:in `each'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:198:in `updated_lockfiles'
updater | 	from /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:43:in `updated_dependency_files'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:86:in `generate_dependency_files'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:36:in `run'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:25:in `create_from'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:87:in `create_change_for'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:48:in `block in compile_all_dependency_changes_for'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:28:in `each'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:28:in `compile_all_dependency_changes_for'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:41:in `perform'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:97:in `run_update_for'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:82:in `block in run_grouped_dependency_updates'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:73:in `each'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:73:in `run_grouped_dependency_updates'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:41:in `perform'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:62:in `run'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 	from bin/update_files.rb:23:in `<main>'
updater | time="2023-07-11T14:15:51Z" level=info msg="task complete" container_id=job-692272807-updater exit_code=1 job_id=692272807 step=updater
updater | time="2023-07-11T14:15:53Z" level=warning msg="updater container failed" error="waiting for updater: bad response from container: 1" exit_code=1 job_id=692272807

```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/recitalsoftware/recital-frontend/network/updates/692272807
