### ISSUE TITLE
Dependabot opening PRs for ignored versions

### ISSUE THREAD

**Issue by sarajend** [dependabot/dependabot-core#7577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### Package manager version

3.9.3

### Language version

Spring Boot 3.0.7, kotlin 1.8.21, java 17. 

### dependabot.yml content

```yaml
version: 2

# Allow Dependabot to use private registry
registries:
  artifact-registry:
    type: maven-repository
    url: https://europe-west1-maven.pkg.dev/vcm-shared/vcm-maven-artifacts
    username: _json_key
    password: ${{secrets.DEPENDABOT_SA_JSON}}
updates:
  - package-ecosystem: maven
    directory: "/"
    registries:
      - artifact-registry # Allow version updates for dependencies in this registry
    schedule:
      interval: daily
    ignore:
      - dependency-name: "sh.vcm.backend-commons-*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sh.vcm.graphql-*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "sh.vcm.feature-toggle-client"
        update-types: [ "version-update:semver-major" ]
    open-pull-requests-limit: 50
    labels:
      - "kotlin"
      - "microservice"
      - "backend"
      - "dependencies"
```

### Updated dependency

graphql-utils-auth

### What you expected to see, versus what you actually saw

What I expected to see:
- No PR opened for a major update

What I actually saw:
- Bump graphql-utils-auth from 0.0.49 to 1.0.10
