### ISSUE TITLE
Grouped update creating multiple PRs for the same group within the same package-ecosystem

### ISSUE THREAD

**Issue by nedrebo** [dependabot/dependabot-core#7602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip-compile 7.1.0

### Language version

Python 3.10.10

### dependabot.yml content

Directory names are replaced with `...`, but are all unique.

```yaml
# Generated file, do not edit @ 2023-07-20 14:42:30
#
# Command: common/scripts/github-actions/helpers/_generate_dependabot_config.py

version: 2
updates:
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
    - package-ecosystem: pip
      groups:
          all:
              patterns:
                  - "*"
      directory: ...
      schedule:
          interval: daily
      open-pull-requests-limit: 1
      commit-message:
          prefix: "Dependabot: "
```

### What you expected to see, versus what you actually saw

**Expected:**

One PR bumping all requirement files across the entire mono repository since I only got one group `all`.

**Actually:**

Tons of PRs, causing CI overload :(

### Smallest manifest that reproduces the issue

Is this a configuration error on my end or a bug in the new grouped updates beta?

If the former, how can I change my `depebdabot.yml` to use grouped updates to achieve 1 PR per day bumping all Python dependencies in our repository?
