### ISSUE TITLE
Dependabot can't update bundler dependency files that reference private git repositories

### ISSUE THREAD

**Issue by gustavothecoder** [dependabot/dependabot-core#7605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

Bundler version 2.3.24

### Language version

ruby 2.7.6p219

### Manifest location and content before the Dependabot update

```ruby
# Path: ./Gemfile

source 'https://rubygems.org'
ruby '2.7.6'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Public gems...

gem 'nokogiri', '~> 1.12.5' # A gem that Dependabot can't update
gem 'private-gem-1', git: 'https://github.com/company/private-gem-1.git', tag: 'v0.1.3'
gem 'private-gem-2', github: 'company/private-gem-2', tag: 'v0.2.6'

# Public gems...
```

### dependabot.yml content

```yml
version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT_REPO_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "gustavothecoder"
  - package-ecosystem: "bundler"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - github-octocat
    schedule:
      interval: "weekly"
    reviewers:
      - "gustavothecoder"
```

### Updated dependency

I'm seeing this error with a lot of ruby dependencies (probably all of them). An example would be `nokogiri` from `1.12.5` to `1.13.4`.

### What you expected to see, versus what you actually saw

I expect that Dependabot can access my private gems and open PRs successfully.

### Native package manager behavior

```bash
$ bundler update nokogiri
# ...
Fetching nokogiri 1.13.10 (x86_64-linux) (was 1.12.5)
Installing nokogiri 1.13.10 (x86_64-linux) (was 1.12.5)
# ...
Bundle updated!
```

### Images of the diff or a link to the PR, issue, or logs

Dependabot generates this logs when trying to update `nokogiri`:
```
# ...
updater | 2023/07/21 13:45:10 INFO <job_698730294> Handled error whilst updating nokogiri: git_dependencies_not_reachable {:"dependency-urls"=>["https://github.com/company/private-gem-1.git", "https://github.com/company/private-gem-2.git"]}
updater | 2023/07/21 13:45:10 INFO <job_698730294> Finished job processing
updater | 2023/07/21 13:45:10 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------------------------------------+
updater | |       Dependencies failed to update       |
updater | +----------+--------------------------------+
updater | | nokogiri | git_dependencies_not_reachable |
updater | +----------+--------------------------------+
updater | time="2023-07-21T13:45:10Z" level=info msg="task complete" container_id=job-698730294-updater exit_code=0 job_id=698730294 step=updater
```
