### ISSUE TITLE
Group patches only

### ISSUE THREAD

**Issue by Schascha** [dependabot/dependabot-core#7618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Language version

Node 16.17

### dependabot.yml content

```yml
version: 2
updates:

- package-ecosystem: 'npm'
  directory: '/'
  schedule:
    interval: 'weekly'
    time: '05:00'
  target-branch: 'develop'
  groups:
    dev-dependencies:
      patterns:
        - '*'
  ignore:
    - dependency-name: '*'
      update-types: ['version-update:semver-major', 'version-update:semver-minor']

- package-ecosystem: 'npm'
  directory: '/'
  schedule:
    interval: 'weekly'
    time: '05:00'
  target-branch: 'develop'
  ignore:
    - dependency-name: '*'
      update-types: ['version-update:semver-patch']
```

### What you expected to see, versus what you actually saw

First of all, I would like to thank you for enabling the group updates. Is there any possibility to group patches only? I tried via `ignore` and `update-types`, but this settings seems to be ignored for now.
