### ISSUE TITLE
Grouped version update didn't group the PRs

### ISSUE THREAD

**Issue by andyleejordan** [dependabot/dependabot-core#7624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

N/A

### Language version

N/A

### Manifest location and content before the Dependabot update

https://github.com/PowerShell/vscode-powershell/blob/eadf2c9956c3326347881d33871a3680addbf624/package.json

### dependabot.yml content

https://github.com/PowerShell/vscode-powershell/blob/eadf2c9956c3326347881d33871a3680addbf624/.github/dependabot.yml

```yaml
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    ESLint:
      patterns:
        - esbuild
        - eslint
        - "@typescript-eslint/*"
```

### Updated dependency

- https://github.com/PowerShell/vscode-powershell/pull/4675
- https://github.com/PowerShell/vscode-powershell/pull/4674
- https://github.com/PowerShell/vscode-powershell/pull/4673

### What you expected to see, versus what you actually saw

I expected to see the above three updates to be in a grouped PR, as they all match the patterns specified for the group `ESLint` in my GitHub-native Dependabot file, per https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/. Did I misconfigure it? If so, I can't spot the error.

### Native package manager behavior

N/A

### Images of the diff or a link to the PR, issue, or logs

N/A

**Comment by carogalvin** [comment]
@andyleejordan can you try with your package names all in `"`? i.e.
```
groups:
    ESLint:
      patterns:
        - "esbuild"
        - "eslint"
        - "@typescript-eslint/*"
 ```

**Comment by jakecoffman** [comment]
Since you're grouping NPM dependencies I think it needs to be:

```yaml
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    ESLint:
      patterns:
        - esbuild
        - eslint
        - "@typescript-eslint/*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly

```
