### ISSUE TITLE
dependabot igonores pull-request-branch-name. separator when setting underscore(_).

### ISSUE THREAD

**Issue by shuhei14** [dependabot/dependabot-core#7642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### Language version

1.19

### Manifest location and content before the Dependabot update

```
/go.mod
/plugins/auth/go.mod
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    pull-request-branch-name:
      separator: _
```

### What you expected to see, versus what you actually saw

We are developping in go.
We set "pull-request-branch-name.separator: _" to separate the PR branch names created by dependabot with underscores.
However, the branch names are stil separated by / without reflecting the setting.

Example of expected result.
```
dependabot_go_modules_golang.org_x_oauth2-0.6.0
```
Example of actual result.
```
dependabot/go_modules/golang.org/x/oauth2-0.6.0
```

I confirmed this settings are work correctly  in npm.
So is this a specific issue of go?

**Comment by shuhei14** [comment]
I resolved this problem by changing dependabot.yml as follow.
```
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    pull-request-branch-name:
      separator: _
  - package-ecosystem: "gomod"
    directory: "/plugins/auth"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    pull-request-branch-name:
      separator: _
```
