### ISSUE TITLE
add label when creating the PR

### ISSUE THREAD

**Issue by vrnvu** [dependabot/dependabot-core#7645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The current behavior we are experiencing is as follows: we specify the labels for Dependabot according to the documentation, as shown below:

```yaml
# Specify labels for pull requests

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
```

All these tags are added after creating the PR.

The problem with this setup is that there is a delay between PR creation and the update that adds the label. Our bot assigns people to the PR, and we want to avoid this.

Can the labels be added during PR creation, and why is it currently done through an update?
