### ISSUE TITLE
`pnpm-lock.yaml` incorrectly updated for url dependencies.

### ISSUE THREAD

**Issue by Jason3S** [dependabot/dependabot-core#7656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

8.5.1

### Manifest location and content before the Dependabot update

At the root: `./package.json`

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
```

### Updated dependency

build(deps-dev): bump inject-markdown from 1.5.0 to 2.0.0

https://github.com/streetsidesoftware/cspell-dicts/pull/2376

### What you expected to see, versus what you actually saw

The issues seem to come from when a version specifier contains a url and not a version number.

`dictionaries/en_US/package.json`
```json
  "devDependencies": {
    "@cspell/dict-en-shared": "workspace:*",
    "aoo-mozilla-en-dict": "https://github.com/marcoagpinto/aoo-mozilla-en-dict"
  }
```

The updater changes unrelated entries in the `pnpm-lock.yaml` file.

Example:

```diff
      aoo-mozilla-en-dict:
        specifier: https://github.com/marcoagpinto/aoo-mozilla-en-dict
-       version: github.com/marcoagpinto/aoo-mozilla-en-dict/649ef961082001eac808db982736f52aac8ebc1e
+       version: git/github.com+marcoagpinto/aoo-mozilla-en-dict/649ef961082001eac808db982736f52aac8ebc1e

```

### Native package manager behavior

`pnpm` doesn't change those entries.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/streetsidesoftware/cspell-dicts/pull/2376
