### ISSUE TITLE
Dependabot groups don't fetch all dependencies latest version

### ISSUE THREAD

**Issue by 23pointsNorth** [dependabot/dependabot-core#7661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Manifest location and content before the Dependabot update

/client/package.json

### dependabot.yml content

```
version: 2

# Set update schedule for GitHub Actions
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

# Check for NPM packages
  - package-ecosystem: "npm"
    directory: "/client/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 10
    # Create a group of dependencies to be updated together in one pull request
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
       angular-dependencies:
          patterns:
            - "@angular*"
       types-dependencies:
          patterns:
            - "@types*"

# Check for PIP packages
  - package-ecosystem: "pip"
    directory: "/dataset_manager/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/itf_model_registry/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/lux/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/message_queue_manager/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/metamorph/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/model_wrapper/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/monitoring/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/orm/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/report_manager/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/server/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"

  - package-ecosystem: "pip"
    directory: "/test_run_manager/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
```

### Updated dependency

```
<html>
<body>
<!--StartFragment--><p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Bumps the angular-dependencies group in /client with 14 updates:</p>

Package | Update
-- | --
@angular-material-components/datetime-picker | 8.0.0 to 16.0.0
@angular/animations | 14.1.3 to 16.1.7
@angular/cdk | 14.1.3 to 15.1.6
@angular/common | 14.1.3 to 16.1.7
@angular/compiler | 14.1.3 to 16.1.7
@angular/core | 14.1.3 to 16.1.7
@angular/forms | 14.1.3 to 16.1.7
@angular/material | 14.1.3 to 15.1.6
@angular/platform-browser | 14.1.3 to 16.1.7
@angular/platform-browser-dynamic | 14.1.3 to 16.1.7
@angular/router | 14.1.3 to 16.1.7
@angular-devkit/build-angular | 14.2.12 to 16.1.6
@angular/cli | 14.2.12 to 15.1.6
@angular/compiler-cli | 14.1.3 to 16.1.7

<!--EndFragment-->
</body>
</html>Bumps the angular-dependencies group in /client with 14 updates:

Package	Update
[@angular-material-components/datetime-picker](https://github.com/h2qutc/angular-material-components)	8.0.0 to 16.0.0
[@angular/animations](https://github.com/angular/angular/tree/HEAD/packages/animations)	14.1.3 to 16.1.7
[@angular/cdk](https://github.com/angular/components)	14.1.3 to 15.1.6
[@angular/common](https://github.com/angular/angular/tree/HEAD/packages/common)	14.1.3 to 16.1.7
[@angular/compiler](https://github.com/angular/angular/tree/HEAD/packages/compiler)	14.1.3 to 16.1.7
[@angular/core](https://github.com/angular/angular/tree/HEAD/packages/core)	14.1.3 to 16.1.7
[@angular/forms](https://github.com/angular/angular/tree/HEAD/packages/forms)	14.1.3 to 16.1.7
[@angular/material](https://github.com/angular/components)	14.1.3 to 15.1.6
[@angular/platform-browser](https://github.com/angular/angular/tree/HEAD/packages/platform-browser)	14.1.3 to 16.1.7
[@angular/platform-browser-dynamic](https://github.com/angular/angular/tree/HEAD/packages/platform-browser-dynamic)	14.1.3 to 16.1.7
[@angular/router](https://github.com/angular/angular/tree/HEAD/packages/router)	14.1.3 to 16.1.7
[@angular-devkit/build-angular](https://github.com/angular/angular-cli)	14.2.12 to 16.1.6
[@angular/cli](https://github.com/angular/angular-cli)	14.2.12 to 15.1.6
[@angular/compiler-cli](https://github.com/angular/angular/tree/HEAD/packages/compiler-cli)	14.1.3 to 16.1.7
```

### What you expected to see, versus what you actually saw

All versions that contain a 16.x.x package to be selected (see @angular/cdk, material, cli that are moved to 15.x.x)

**Comment by jakecoffman** [comment]
I tried to reproduce this but it worked for me: https://github.com/dsp-testing/angular-grouped-update/pull/5

There's a chance there's an ignore rule interfering. When a PR is closed Dependabot automatically adds an ignore. Would you mind providing the Job ID? It appears in the logs as something like `job_702189558`. I can use that to look up any ignores that might be lurking.

**Comment by 23pointsNorth** [comment]
Where should I look up the job id?

**Comment by jakecoffman** [comment]
Yep that must be it because I see these ignores on the repo:

<details>
<summary>Ignore Conditions</summary>

```
ignore-conditions:
  - dependency-name: "@angular-devkit/build-angular"
    version-requirement: ">= 14.0.0.a, < 14.0.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cdk"
    version-requirement: ">= 14.0.0.a, < 14.0.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cdk"
    version-requirement: ">= 14.0.1.a, < 14.0.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cdk"
    version-requirement: ">= 14.0.a, < 14.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cdk"
    version-requirement: ">= 15.2.a, < 15.3"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cdk"
    version-requirement: ">= 16.0.a, < 16.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cdk"
    version-requirement: ">= 16.1.a, < 16.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cli"
    version-requirement: ">= 14.0.0.a, < 14.0.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cli"
    version-requirement: ">= 14.0.1.a, < 14.0.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cli"
    version-requirement: ">= 14.0.a, < 14.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cli"
    version-requirement: ">= 15.2.a, < 15.3"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cli"
    version-requirement: ">= 16.0.a, < 16.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cli"
    version-requirement: ">= 16.1.a, < 16.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/compiler"
    version-requirement: ">= 14.0.0.a, < 14.0.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/compiler"
    version-requirement: ">= 14.0.1.a, < 14.0.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/compiler"
    version-requirement: ">= 14.0.a, < 14.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/core"
    version-requirement: ">= 15.1.a, < 15.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/core"
    version-requirement: ">= 15.2.a, < 15.3"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/material"
    version-requirement: ">= 14.0.0.a, < 14.0.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/material"
    version-requirement: ">= 14.0.1.a, < 14.0.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/material"
    version-requirement: ">= 14.0.a, < 14.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/material"
    version-requirement: ">= 15.2.a, < 15.3"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/material"
    version-requirement: ">= 16.0.a, < 16.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/material"
    version-requirement: ">= 16.1.a, < 16.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@types/node"
    version-requirement: ">= 20.1.a, < 20.2"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@types/node"
    version-requirement: ">= 20.2.a, < 20.3"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@types/node"
    version-requirement: ">= 20.3.a, < 20.4"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: rxjs
    version-requirement: ">= 7.5.5.a, < 7.5.6"
    update-types: 
    source: "@dependabot ignore command"
```

</details>

The relevant ones are 

```
  - dependency-name: "@angular/cdk"
    version-requirement: ">= 16.0.a, < 16.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cdk"
    version-requirement: ">= 16.1.a, < 16.2"
    update-types: 
    source: "@dependab
```

and

```
  - dependency-name: "@angular/cli"
    version-requirement: ">= 16.0.a, < 16.1"
    update-types: 
    source: "@dependabot ignore command"
  - dependency-name: "@angular/cli"
    version-requirement: ">= 16.1.a, < 16.2"
    update-types: 
    source: "@dependabot ignore command"
```

The way to remove the ignore is to reopen the pull request that the ignore was added on. Or I can use a command to remove them on my side, let me know if you'd like me to do that.
