### ISSUE TITLE
Dependabot not creating PR

### ISSUE THREAD

**Issue by arununzer** [dependabot/dependabot-core#7672]
Hello Team,

I was working on integrating dependabot with my repo and all of a sudden , it stops creating a PR 

```
updater | 2023/07/31 14:19:11 INFO <job_702837663> Finished job processing
updater | 2023/07/31 14:19:11 INFO Results:
updater | +----------------------------------------------------------------------------------------------+
updater | |                             Changes to Dependabot Pull Requests                              |
updater | +---------+------------------------------------------------------------------------------------+
updater | | created | docker/library/eclipse-temurin ( from 17.0.5_8-jre-alpine to 17.0.8_7-jre-alpine ) |
updater | +---------+------------------------------------------------------------------------------------+
updater | time="2023-07-31T14:19:11Z" level=info msg="task complete" container_id=job-702837663-updater exit_code=0 job_id=702837663 step=updater
Footer
```

It shows created in log but couldnt find it in the PR list

Dependabot.yaml

```
version: 2
updates:
  - package-ecosystem: "docker" 
    directory: "/base-images/test" 
    schedule:
      interval: "daily"
      time: "16:17"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "[test]"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
```

Expected :

A PR to be created which inturn triggers a GHA workflow

It was working fine two days ago .. now its not working.. i guess 17.0.5_8-jre-alpine has underscore and hyphens which is not semver thing.. is it due to That ?
