### ISSUE TITLE
Dependabot creating PR to update to a lower version

### ISSUE THREAD

**Issue by lwasyl** [dependabot/dependabot-core#7775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

8.2.1

### Language version

-

### Manifest location and content before the Dependabot update

![image](https://github.com/dependabot/dependabot-core/assets/3951580/558a2c77-1ae2-46aa-a21e-dbcdc653614c)

### dependabot.yml content

```yaml
version: 2
registries:
  maven-google: # https://github.com/dependabot/dependabot-core/issues/6888
    type: maven-repository
    url: "https://dl.google.com/dl/android/maven2/"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "no-jira"
      - "dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
    labels:
      - "no-jira"
      - "dependencies"

  - package-ecosystem: "gradle"
    directory: "dependencies-platform"
    registries: "*"
    schedule:
      interval: "weekly"
    labels:
      - "no-jira"
      - "dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"
```

### Updated dependency

![image](https://github.com/dependabot/dependabot-core/assets/3951580/558a2c77-1ae2-46aa-a21e-dbcdc653614c)

### What you expected to see, versus what you actually saw

I expect Dependabot to not update to a version which according to [SemVer](![image](https://github.com/dependabot/dependabot-core/assets/3951580/558a2c77-1ae2-46aa-a21e-dbcdc653614c) is a pre-release version. Relevant bits bolded:

> A **pre-release version** MAY be denoted by **appending a hyphen and a series of dot separated identifiers** immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. **Pre-release versions have a lower precedence than the associated normal version**. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.--.

According to the spec, `2.4.7` is a release version, and `2.4.7-1-8` is a pre-release version. Dependabot should *not* attempt to downgrade the dependency like that
