### ISSUE TITLE
Dependabot stopped working with private sonatype nexus hosted npm registry

### ISSUE THREAD

**Issue by WIStudent** [dependabot/dependabot-core#7793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

```yml
registries:
  nexus:
    type: npm-registry
    url: redacted.domain/repository/redacted-repository-name/
    username: redacted-username
    password: ${{secrets.NEXUS_NPM_PASSWORD}}

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "redacted-sub-directory/"
    schedule:
      interval: "daily"
      time: "21:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 100
    versioning-strategy: increase
    registries:
      - nexus
    labels:
      - dependencies
      - javascript
```

### What you expected to see, versus what you actually saw

We are using a private sonatype nexus hosted npm registry to host some internal npm packages. Recently dependabot stopped working with this registry. I attached the relevant part of the dependabot log below. This seems to be caused by nexus not implementing the /{package}/{version} endpoint correctly. I already created a [corresponding issue](https://github.com/sonatype/nexus-public/issues/224) in the nexus project.

The other issue is that dependabot does not seem to be able to handle the 400 response gracefully. Instead of just skipping this dependency, dependabot crashes and stops.

### Images of the diff or a link to the PR, issue, or logs

Relevant part of the dependabot log provided by github.com. I had to use a file as the log exceeded the maximum character limit for issues.
[log.txt](https://github.com/dependabot/dependabot-core/files/12320584/log.txt)
