### ISSUE TITLE
Group updates on Semantic Versioning level Beta

### ISSUE THREAD

**Issue by jurre** [dependabot/dependabot-core#7795]
As part of our effort to release grouped updates for Dependabot, we're rolling out a new feature in closed beta that will allow you to group by semver level.

What this looks like:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      non-major-versions: # the name of the group
        update-types:     # the key used to specify the semver level to include in the group
        - "minor"         # an array, possible values being minor, patch and major
        - "patch"
```

For the above configuration, Dependabot will open a grouped PR for any dependencies where the highest resolvable version is a `patch` or `minor` SemVer update, and any dependencies that will be updated to a new `major` version will be opened as separate, individual PRs.

The `update-types` key can be combined with other group rules, for these examples I will only specify the `groups` section, assume the rest of the config file is the same as the one listed above:

```yaml
groups:
  angular:
    patterns: 
    - "@angular*"
    update-types:
    - "minor"
    - "patch"
```

For this configuration, any packages matching the pattern `@angular*` where the highest resolvable version is `minor` or `patch` will be grouped together, any package that does not match the pattern or that does not update to a `minor` or `patch` version will be opened as a separate PR. For cases where you do not want updates to `major` versions of `@angular*` packages, you can specify an `ignore` condition:

```yaml
groups:
  angular:
    patterns: 
    - "@angular*"
    update-types:
    - "minor"
    - "patch"
ignore:
  - dependency-name: "@angular*"
    update-types: ["version-update:semver-major"]
```

If you want grouped PRs for development dependencies that have `patch` updates, you would specify:

```yaml
groups:
  patch-dev-dependencies:
    dependency-type: "development"
    update-types:
    - "patch"
```

If you want to join the private beta, please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSd1UV2rSi057SJfLYVqVHf6xxX5tV2mE81Jw_Nt9kzZ3FMeNg/viewform?usp=sf_link) and we'll enable the feature.

Any other feedback or thoughts are much appreciated
