### ISSUE TITLE
Dependabot opens multiple grouped and ungrouped PRs for the same updates

### ISSUE THREAD

**Issue by carogalvin** [dependabot/dependabot-core#7830]
We're seeing customer reports of duplicate grouped and ungrouped PRs being opened for the same updates.

One `dependabot.yaml` example:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    versioning-strategy: increase
    open-pull-requests-limit: 30
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "America/New_York"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
          - "@etchteam/storybook*"
      nxAndFriends:
        patterns:
          - "nx"
          - "@nx/*"
          - "@jscutlery/semver"
          - "semantic-release"
          - "cz-conventional-changelog"
          - "ngx-deploy-npm"
```

Here's a screenshot of the duplicate PRs they saw:

![Image](https://github.com/github/dependabot-updates/assets/749864/22d4648c-9ada-4b4c-a644-df4cafe753d2)

In this case I would expect the `storybook*` dependencies to only show up in the `storybook` group.

After some investigation, we discovered the problem:

> npm is throwing an error and so then gets treated as "not updated" and it attempts to make an individual PR for it. So we need to account for the dependency SHOULD have been updated in the group but failed to. [This code](https://github.com/dependabot/dependabot-core/blob/a3e2c09b300a0b8816ae689b8ffef0e7341c52e1/updater/lib/dependabot/updater/operations/group_update_all_versions.rb#L85-L86)
