### ISSUE TITLE
Python poetry undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by HariSekhon** [dependabot/dependabot-core#7864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

python poetry

### Manifest location and content before the Dependabot update

`/pyproject.toml`

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "11:30"
    groups:
      python-packages:
        patterns:
          - "*"
```

### What you expected to see, versus what you actually saw

Expected to see a useful error message.

Got this raw unhandled code error instead:

```
updater | 2023/08/21 23:48:50 ERROR <job_712118307> undefined method `strip' for nil:NilClass
updater | 
updater |           url = url.strip.gsub(%r{/*$}, "") + "/"
updater |                    ^^^^^^
```
