### ISSUE TITLE
Grouped Dependabot pull requests rebase on all ecosystem changes

### ISSUE THREAD

**Issue by PetroSilenius** [dependabot/dependabot-core#7882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 9.6.

### Language version

node 18.17

### Manifest location and content before the Dependabot update

`/modules/backend/package.json`
https://github.com/PetroSilenius/grouped-dependabot-rebases-all/blob/main/modules/backend/package.json
```
{
  "name": "backend",
  "version": "1.0.0",
  "scripts": {
    "test": "true"
  },
  "license": "MIT",
  "dependencies": {
    "is-odd": "3.0.1"
  }
}
```

`/modules/frontend/package.json`
https://github.com/PetroSilenius/grouped-dependabot-rebases-all/blob/main/modules/frontend/package.json
```
{
  "name": "backend",
  "version": "1.0.0",
  "scripts": {
    "test": "true"
  },
  "license": "MIT",
  "dependencies": {
    "is-odd": "2.0.0"
  }
}
```

### dependabot.yml content

https://github.com/PetroSilenius/grouped-dependabot-rebases-all/blob/main/.github/dependabot.yml

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/modules/backend"
    schedule:
      interval: "daily"
    groups:
       backend:
          patterns:
            - "*"

  - package-ecosystem: "npm"
    directory: "/modules/frontend"
    schedule:
      interval: "daily"
    groups:
       frontend:
          patterns:
            - "*"
```

### Updated dependency

is-odd v2.0.0 -> v3.1.1

https://github.com/PetroSilenius/grouped-dependabot-rebases-all/pull/1

## What I expected
I expected merging dependabot pull request targeting `/modules/backend` dependencies not to trigger a rebase on another dependabot pull request to `modules/frontend` as these modules are separated modules.

## What I actually saw
Merging https://github.com/PetroSilenius/grouped-dependabot-rebases-all/pull/1 triggered a rebase in https://github.com/PetroSilenius/grouped-dependabot-rebases-all/pull/2

This becomes quite a big issue in larger a monorepo with multiple modules etc and more CI pipelines that will get triggered by dependabot rebasing pull requests

### Smallest manifest that reproduces the issue

Reproduction Steps:

- Set up a monorepo with a multiple modules, with each module running on the npm package ecosystem.
- Set up Dependabot to do dependency updates to each module in separate pull requests, each defined as a separate group.
- Make changes to the target branch of one module.
- Observe that Dependabot rebases all the pull requests, even for other modules that do not have conflicts with the updated target branch.

## Example

1. After merging the dependabot PR to update the backend module https://github.com/PetroSilenius/grouped-dependabot-rebases-all/pull/1

2. The frontend module dependabot PR was rebased https://github.com/PetroSilenius/grouped-dependabot-rebases-all/pull/2
