### ISSUE TITLE
Dependabot can not automatically create PRs for alerts generated when pnpm vulnerability support was rolled out

### ISSUE THREAD

**Issue by gavacq** [dependabot/dependabot-core#7887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm 7

### Language version

Node 18.17

### dependabot.yml content

```
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_READ_TOKEN}}
    replaces-base: true
updates:
  # root npm package.json
  - package-ecosystem: 'npm'
    directory: '/project-name'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: 'moment-timezone'
    open-pull-requests-limit: 0
```

### What you expected to see, versus what you actually saw

My team's project was managed with `yarn` and we switched to `pnpm` mid-July. We lost all of our security alerts when we did this as dependabot didn't support pnpm yet. On July 31st, (I think this is when dependabot rolled out support for pnpm), the alerts were regenerated, but no PRs were opened. Since then, dependabot only automatically creates PRs for newly added dependencies, i.e. new alerts. 

Is there a way to "refresh" the alerts for dependabot such that it will try to create PRs? We have around 2000 open alerts so checking each alert manually and clicking the "open PR" button is not an ideal workaround.
