### ISSUE TITLE
Properties ["groups"] outside of the schema when none are allowed

### ISSUE THREAD

**Issue by joakim-sch** [dependabot/dependabot-core#7897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### dependabot.yml content

```
version: 2
      
registries: 
  artifactory:
    type: npm-registry
    url: ***
    username: ${{ secrets.ARTIFACTORY_USERNAME }}
    password: ${{ secrets.ARTIFACTORY_PASSWORD }}
    
updates:
  - package-ecosystem: "npm"
    registries:
      - artifactory
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "Europe/Copenhagen"
    groups:
      wdio:
        patterns:
          - "@wdio*"
```

### What you expected to see, versus what you actually saw

Expected dependabot to group dependencies, but instead it says that;

The property '#/updates/0/' contains additional properties ["groups"] outside of the schema when none are allowed
