### ISSUE TITLE
Adding individual package ignores via grouped PRs is not working.

### ISSUE THREAD

**Issue by Vossekop** [dependabot/dependabot-core#7910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### dependabot.yml content

``` yml
version: 2

updates:
  - package-ecosystem: nuget
    directory: "/Server"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Amsterdam"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "nuget"
      include: "scope"
    reviewers:
      - "priva-platform/groot"
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/Tests/Cloud"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Amsterdam"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "nuget"
      include: "scope"
    reviewers:
      - "priva-platform/groot"
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/Tests/Local"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Amsterdam"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "nuget"
      include: "scope"
    reviewers:
      - "priva-platform/groot"
    open-pull-requests-limit: 10
```

### Updated dependency

Package | Update
-- | --
Microsoft.EntityFrameworkCore | 7.0.9 to 7.0.10
Microsoft.EntityFrameworkCore.Design | 7.0.9 to 7.0.10
Microsoft.AspNetCore.DataProtection.EntityFrameworkCore | 6.0.20 to 7.0.10
Microsoft.EntityFrameworkCore.SqlServer | 7.0.9 to 7.0.10
Microsoft.AspNetCore.Authentication.OpenIdConnect | 6.0.20 to 7.0.10
dotnet-ef | 7.0.9 to 7.0.10

### What you expected to see, versus what you actually saw

With this set of updates I actually want to ignore 2 of them, I try to do this using the following commands:

`@dependabot ignore Microsoft.AspNetCore.DataProtection.EntityFrameworkCore major version`
`@dependabot ignore Microsoft.AspNetCore.Authentication.OpenIdConnect major version`

I expect dependabot to give me a thumbsup and recreate the PR without the specified major version of these packages. However, dependabot does not respond at all. I've tried this by doing each command in a separate comment in the PR or both together in one comment, neither works.

Other commands do work, for instance: `@dependabot show Microsoft.AspNetCore.DataProtection.EntityFrameworkCore ignore conditions` responds with: No ignore conditions found for the dependency microsoft.aspnetcore.dataprotection.entityframeworkcore

One thing of note is that we use GitHub EMU (Enterprise Managed Users).
