### ISSUE TITLE
Version comment in SHA-pinned github actions is not updated if it's incorrect

### ISSUE THREAD

**Issue by ThiefMaster** [dependabot/dependabot-core#7912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

```yaml
name: Test dependabot updates

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      # this is simply an outdated version
      - uses: docker/setup-buildx-action@2e941f2defb78a11da0f277a3a76fb347dfd084b # v1.4.0
      # this is also an outdated version, but within the same major
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      # this is an outdated version and the version comment behind it is incorrect (the SHA is from v3.2.4)
      - uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.4.5
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
       github-actions:
          patterns: ['*']
```

### What you expected to see, versus what you actually saw

I would have expected the comment to be updated, regardless of the fact that it was incorrect before.

Here's the PR Dependabot sent: ThiefMaster/depbot-actions-bug#1

### Smallest manifest that reproduces the issue

ThiefMaster/depbot-actions-bug#1
