### ISSUE TITLE
path_dependencies_not_reachable error for git submodule

### ISSUE THREAD

**Issue by johnnymetz** [dependabot/dependabot-core#7916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Manifest location and content before the Dependabot update

`/package.json`

Applicable lines in `package.json`:

```
"devDependencies": {
  ...,
  "@pixiebrix/extension": "file:pixiebrix-extension",
  ...
}
```

Note `@pixiebrix/extension` points to a submodule. Here is our `/.gitmodules` file:

```
[submodule "pixiebrix-extension"]
	path = pixiebrix-extension
	url = https://github.com/pixiebrix/pixiebrix-extension.git
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    assignees:
      - johnnymetz
```

### What you expected to see, versus what you actually saw

**Expected**

`@pixiebrix/extension` is a submodule so npm dependabot should not touch it. I even tried ignoring it by appending `ignore` to the dependabot config:

```
updates:
  - package-ecosystem: npm
    ...
    ignore:
      - dependency-name: "@pixiebrix/extension"
```

**Actual**

<img width="1133" alt="Screenshot 2023-08-28 at 11 35 05 AM" src="https://github.com/dependabot/dependabot-core/assets/20693145/66b03074-8462-4e4d-a018-70690a81d2b9">

Dependabot logs:

```
updater | 2023/08/28 18:41:23 ERROR <job_714829645> Error during file fetching; aborting
updater | 2023/08/28 18:41:23 INFO <job_714829645> Finished job processing
updater | 2023/08/28 18:41:23 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------------+
updater | |             Errors              |
updater | +---------------------------------+
updater | | path_dependencies_not_reachable |
updater | +---------------------------------+
updater | time="2023-08-28T18:41:23Z" level=info msg="task complete" container_id=job-714829645-file-fetcher exit_code=0 job_id=714829645 step=fetcher
updater | time="2023-08-28T18:41:23Z" level=warning msg="failed during fetch, skipping updater" job_id=714829645
```

### Native package manager behavior

`npm install` works fine locally. No errors.
