### ISSUE TITLE
dependabot updater still check poetry `explicit` source 

### ISSUE THREAD

**Issue by lucemia** [dependabot/dependabot-core#7918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

poetry

### Package manager version

poetry 1.6

### Language version

python 3.10

### Manifest location and content before the Dependabot update

`/pyproject.toml` and `/poetry.lock`

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
```

### What you expected to see, versus what you actually saw

Poetry 1.5.0 introduced explicit package source
https://python-poetry.org/docs/repositories/#explicit-package-sources

> If package sources are configured as explicit, these sources are only searched when a package configuration [explicitly indicates](https://python-poetry.org/docs/repositories/#package-source-constraint) that it should be found on this package source.

However, in latest dependabot, the updater will still check package against source marked as `explicit`. Which double the execution time. 

```
updater | 2023/08/29 06:15:39 INFO <job_715108988> Checking if protobuf 3.20.3 needs updating
  proxy | 2023/08/29 06:15:39 [044] GET https://pypi.org:443/simple/protobuf/
  proxy | 2023/08/29 06:15:39 [044] 200 https://pypi.org:443/simple/protobuf/
  proxy | 2023/08/29 06:15:40 [046] GET https://[my private pypi]/pypi/protobuf/
  proxy | 2023/08/29 06:15:40 [046] 404 https://[my private pypi]/pypi/protobuf/
```

### Native package manager behavior

will not check protobuf against my private pypi
