### ISSUE TITLE
Grouped package update being assigned to multiple Dependabot groups

### ISSUE THREAD

**Issue by edmorley** [dependabot/dependabot-core#7939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Cargo

### Package manager version

1.72

### Language version

1.72

### Manifest location and content before the Dependabot update

https://github.com/heroku/languages-github-actions/blob/e3c1fe2066215a6b20ace90150474351a885a716/Cargo.toml
https://github.com/heroku/languages-github-actions/blob/e3c1fe2066215a6b20ace90150474351a885a716/Cargo.lock

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      libcnb:
        patterns:
          - "libcnb*"
          - "libherokubuildpack"
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
```

### Updated dependency

See: https://github.com/heroku/languages-github-actions/pull/137

### What you expected to see, versus what you actually saw

The [Dependabot docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) for the new grouped updates feature say:

> Dependabot creates groups in the order they appear in your `dependabot.yml` file. If a dependency update could belong to more than one group, it is only assigned to the first group it matches with.

However, we're seeing the `libcnb-data` and `libcnb-package` packages being assigned to both the `libcnb` and `rust-dependencies` groups, even though they should be only seen in the `libcnb` group PR.

libcnb group (correct):
https://github.com/heroku/languages-github-actions/pull/120

rust-dependencies group (not correct, the libcnb packages shouldn't be in here):
https://github.com/heroku/languages-github-actions/pull/137
