### ISSUE TITLE
Dependabot proxy does not inject python registry credentials for poetry's requests

### ISSUE THREAD

**Issue by maksbotan** [dependabot/dependabot-core#7940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

python poetry

### Package manager version

poetry 1.5.1 locally

### Language version

python 3.10

### Manifest location and content before the Dependabot update

private repository

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - github
      - REDACTED

    # https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#insecure-external-code-execution
    insecure-external-code-execution: allow
    reviewers:
      - "REDACTED"
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GITHUB_TOKEN}}
  REDACTED: # Define access for a private registry
    type: python-index
    url: https://REDACTED/api/v4/groups/REDACTED/-/packages/pypi/simple
    username: ${{secrets.REGISTRY_USERNAME}}
    password: ${{secrets.REGISTRY_PASSWORD}}
```

### What you expected to see, versus what you actually saw

I expect dependabot to be able to create PRs, but in fact it does not create any.

Log ends with:

```
updater | Dependabot encountered '26' error(s) during execution, please check the logs for more details.
updater | +--------------------------------+
updater | | Dependencies failed to update  |
updater | +----------------+---------------+
updater | | statsmodels    | unknown_error |
updater | | kaleido        | unknown_error |
updater | | matplotlib     | unknown_error |
updater | | plotly         | unknown_error |
updater | | pymongo        | unknown_error |
updater | | numpy          | unknown_error |
... and so on
```

The problem is related to a private source being used in the `pyproject.toml`. We have specified credentials for that source, but looks like they do not get injected into requests made by `poetry` itself. See in the log:

```
  proxy | 2023/08/31 11:11:01 [080] GET https://REDACTED:443/api/v4/groups/REDACTED/-/packages/pypi/simple/REDACTED/
  proxy | 2023/08/31 11:11:01 [080] * authenticating python index request (host: REDACTED)
  proxy | 2023/08/31 11:11:02 [080] 200 https://REDACTED:443/api/v4/groups/REDACTED/-/packages/pypi/simple/REDACTED/
  proxy | 2023/08/31 11:11:02 [082] GET https://REDACTED:443/api/v4/groups/6/-/packages/pypi/files/58a0bffb9045eecc28eab3c9be2ba4687fa27ea467d4f3c8d8ede8560f1c10d0/REDACTED-0.4.35-py3-none-any.whl
  proxy | 2023/08/31 11:11:02 [082] 401 https://REDACTED:443/api/v4/groups/6/-/packages/pypi/files/58a0bffb9045eecc28eab3c9be2ba4687fa27ea467d4f3c8d8ede8560f1c10d0/REDACTED-0.4.35-py3-none-any.whl
  proxy | 2023/08/31 11:11:02 [082] {"message":"401 Unauthorized"}
updater | 2023/08/31 11:11:03 INFO <job_716295681> Sending event 3b3fbb215ae44cb191fb2fb86cf50e75 to Sentry
  proxy | 2023/08/31 11:11:04 [085] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/08/31 11:11:04 [085] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/08/31 11:11:04 ERROR <job_716295681> Error processing statsmodels (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/08/31 11:11:04 ERROR <job_716295681> Creating virtualenv REDACTED-Us7jV1go-py3.11 in /home/dependabot/.cache/pypoetry/virtualenvs
updater | 
updater | 401 Client Error: Unauthorized for url: https://REDACTED/api/v4/groups/6/-/packages/pypi/files/58a0bffb9045eecc28eab3c9be2ba4687fa27ea467d4f3c8d8ede8560f1c10d0/REDACTED-0.4.35-py3-none-any.whl#sha256=58a0bffb9045eecc28eab3c9be2ba4687fa27ea467d4f3c8d8ede8560f1c10d0
updater | 2023/08/31 11:11:04 ERROR <job_716295681> /home/dependabot/python/lib/dependabot/python/helpers.rb:22:in `run_poetry_command'
updater | 2023/08/31 11:11:04 ERROR <job_716295681> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:311:in `run_poetry_command'
updater | 2023/08/31 11:11:04 ERROR <job_716295681> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:149:in `run_poetry_update_command'
updater | 2023/08/31 11:11:04 ERROR <job_716295681> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:89:in `block (2 levels) in fetch_latest_resolvable_version_string'
...
```

Looks like for dependabot's own requests (to check versions, etc) credentials are included (look at `200 https://REDACTED:443/api/v4/groups/REDACTED/-/packages/pypi/simple/REDACTED/`) , but for any `poetry` command they are not, since the line `401 Client Error: Unauthorized for url:  ...` comes from poetry's output, not from dependabot log. I suppose the error lies in the `proxy` part of dependabot infrastructure.

This error blocks us from getting __any__ updates on our repo, since poetry queries private registry when resolving dependencies for every package, even for ones from pypi.

The registry is self-hosted Gitlab, if that matters.
