### ISSUE TITLE
NPM conflicting dependencies not detected, leads to package downgrade

### ISSUE THREAD

**Issue by brettfo** [dependabot/dependabot-core#7952]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 8.19.4

### What you expected to see, versus what you actually saw

If the `package(-lock).json` files contain incompatible dependency versions and the update is not stopped at the update checker level, the update can continue to "update" the package via a downgrade.

This specific example is trying to update with the following `job.yaml` snippet:

``` yaml
job:
  package-manager: npm_and_yarn
  allowed-updates:
    - update-type: all
  dependencies:
    - underscore
  security-advisories:
    - dependency-name: underscore
      affected-versions:
        - '>= 1.3.2, < 1.12.1'
      patched-version:
        - 1.12.1
      unaffected-versions: []
      security-updates-only: true
```

The attached .zip file contains 3 sets of dependency files: "full" is the original files that result in an improper package downgrade, "simple" contains a reduced set of dependencies that is properly detected as incompatible (and results in the expected `security_update_not_possible`, and "fixed" contains the files from "full", but with the lock file re-generated and it also results in the expected `security_update_not_possible`.

[package-downgrade.zip](https://github.com/dependabot/dependabot-core/files/12501078/package-downgrade.zip)
