### ISSUE TITLE
Group updates by `direct` and `indirect` updates

### ISSUE THREAD

**Issue by simensol** [dependabot/dependabot-core#7959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

With the new `groups` syntax, it is possible to group updates by `dependency-type`, that is, `development` or `production`. The `allow.dependency-type` [syntax](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) supports `direct` and `indirect` types, in addition to `development` or `production` (and `all`).

I want an individual PR for each direct dependency, but all indirect dependencies should be grouped. However, since `groups.dependency-type` doesn't support the `direct` and `indirect` types, this is not possible.

In addition to the `direct` and `indirect` types, the `all` type could also replace the `"*"` pattern used to group all dependencies:

```yml
      groups:
          all:
              patterns:
                  - "*"
```

**Comment by andriijas** [comment]
```
    allow:
      - dependency-type: 'all'
    groups:
      basic:
        update-types:
          - 'minor'
          - 'patch'
      indirect-basic:
        dependency-type: 'indirect'
        update-types:
          - 'minor'
          - 'patch'

```

Would be nice to be able to do this
