### ISSUE TITLE
Yarn v4 version not picked up by corepack - causes mass replacement of dependencies

### ISSUE THREAD

**Issue by coolbaluk** [dependabot/dependabot-core#7962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

4.0.0-rc.50

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"

```

### What you expected to see, versus what you actually saw

Due to yarn changing their zip library in v4 [here](https://github.com/yarnpkg/berry/pull/4247) the cache key of the dependencies has changed.

Dependabot does not seem to respect the local version, even though these properties are both set as following:

`"packageManager": "yarn@4.0.0-rc.50"` and `yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs`

This leads to a mass replacement of zips, and pull requests which look like the following:

![263787582-6a7e4486-90fe-4cfa-824e-4b810fa220a2](https://github.com/dependabot/dependabot-core/assets/5834683/92a11f1a-dbff-4ed9-961d-8dd398a093e5)

Possibly related to: #7134
