### ISSUE TITLE
Support multiple config for one ecosystem

### ISSUE THREAD

**Issue by BBboy01** [dependabot/dependabot-core#7965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When update some dependencies, is possible to have a special config for same ecosystem, for example:

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: '@bable*'
 
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    versioning-strategy: increase
    assignees:
      - john_doe
    allow:
      - dependency-name: '@bable*'
```
