### ISSUE TITLE
GitHub Actions version pinning dropped

### ISSUE THREAD

**Issue by na-jakobs** [dependabot/dependabot-core#7971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

Expected to see an update to the latest sha along with an update to the comment.

Removed:
```
steps:
   - name: Checkout repo
     uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
```

Added:
```
steps:
   - name: Checkout repo
     uses: actions/checkout@v4 # v3.5.2
```

### Images of the diff or a link to the PR, issue, or logs

![dependabot-removing-sha](https://github.com/dependabot/dependabot-core/assets/64911732/871fe484-e6d9-4905-9c87-5f669265837d)
