### ISSUE TITLE
grouped updates didn't group gomod updates

### ISSUE THREAD

**Issue by wadey** [dependabot/dependabot-core#7974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### Language version

1.20

### Manifest location and content before the Dependabot update

`go.mod`: https://github.com/slackhq/nebula/blob/06b480e17751eb5d719ec85cb34e1abd51280a64/go.mod

### dependabot.yml content

https://github.com/slackhq/nebula/blob/06b480e17751eb5d719ec85cb34e1abd51280a64/.github/dependabot.yml

### Updated dependency

- `Bump golang.org/x/term from 0.11.0 to 0.12.0`: https://github.com/slackhq/nebula/pull/967
- `Bump golang.org/x/sys from 0.11.0 to 0.12.0`: https://github.com/slackhq/nebula/pull/968

### What you expected to see, versus what you actually saw

These dependencies should have been grouped together. My dependabot config has the follow, so I expected them to be grouped with `golang-x-dependencies`:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      golang-x-dependencies:
        patterns:
          - "golang.org/x/*"
      zx2c4-dependencies:
        patterns:
          - "golang.zx2c4.com/*"
      protobuf-dependencies:
        patterns:
          - "github.com/golang/protobuf"
          - "google.golang.org/protobuf"
```
