### ISSUE TITLE
.github/dependabot.yml configuration conflicts dependabot docs

### ISSUE THREAD

**Issue by kirilllzaitsev** [dependabot/dependabot-core#7987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

Python 3.9

### dependabot.yml content
```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 15
    groups:
      python-packages:
        patterns:
          - "*"
      update-types: 
          - "minor"
          - "patch"
```

### What you expected to see, versus what you actually saw

It should match the configuration from the docs at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups.

What I see is:

`The property '#/updates/0/groups/update-types' of type array did not match the following type: object`

What I also tried: `update-types: "version-update:semver-minor"`

If that's important, the repository has the GitHub Enterprise plan.

**Comment by Foteno** [comment]
With your provided dependabot.yml I get:
`The property '#/updates/0/groups' of type object did not match the following type: array`.

What seems to pass parsing is this, but without update-types:
```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
        schedule:
      interval: "weekly"
    groups:
       - development-dependencies:
          patterns:
          - "*"

**Comment by kirilllzaitsev** [comment]
@Foteno thank you. The version seems to play a significant role. Using your suggested config I get:

`The property '#/updates/0/groups' of type array did not match the following type: object`

**Comment by deivid-rodriguez** [comment]
@kirilllzaitsev The `update-types` key in your original post seems to have wrong indentation. Can you double check?

**Comment by jakecoffman** [comment]
YAML is a tricky beast. 

This is valid, it puts the pattern and update-types under the "python-packages" group:

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 15
    groups:
      python-packages:
        patterns:
          - "*"
        update-types: 
          - "minor"
          - "patch"
```

As @deivid-rodriguez mentioned, it looks like this is what you were going for, but `update-types` is not indented enough.

@Foteno Grouped updates haven't been released for GHES yet.
