### ISSUE TITLE
Error processing <package> (NoMethodError): undefined method `split'

### ISSUE THREAD

**Issue by adam-hotait-voodoo** [dependabot/dependabot-core#8003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

Python 3.11

### Manifest location and content before the Dependabot update

`requirements/requirements.txt`:

```
boto3==1.28.32
fastapi==0.101.1
⋮
[private packages here]
⋮
gunicorn==21.2.0
pydantic==2.2.1
redis==5.0.0
uvicorn==0.23.2
```

`requirements/tests.txt`:

```
coverage==7.3.0
fakeredis==2.18.0
⋮
[private packages here]
⋮
httpx==0.24.1
moto==4.1.15
pytest-mock==3.11.1
pytest==7.4.0
requests==2.31.0

```

`requirements/dev.txt`:

```
mypy
pylint

types-requests
types-redis
```

### dependabot.yml content

```yaml
version: 2
registries:
  python-codeartifact:
    type: python-index
    url: https://<private>.d.codeartifact.us-west-2.amazonaws.com/pypi/<private>/simple/
    username: aws
    password: ${{secrets.<secret for internal repository>}}
    replaces-base: true
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    insecure-external-code-execution: allow
    target-branch: "develop"
    registries:
      - python-codeartifact
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    groups:
      non-major-versions:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
    reviewers:
      - <internal GitHub group>

```

### Updated dependency

All dependencies are affected. See below Dependabot's logs for `requests`, all dependencies show the same error.

### What you expected to see, versus what you actually saw

Dependabot ran successfully last week. Now we get the following issue (here I just copy/pasted the Dependabot logs for `requests`, but we get the same issue for every package):

```
⋮
updater | 2023/09/11 09:13:33 INFO <job_720270953> Checking if requests 2.31.0 needs updating
  proxy | 2023/09/11 09:13:33 [070] GET https://<private-repository>.d.codeartifact.us-west-2.amazonaws.com:443/pypi/<private>/simple/requests/
  proxy | 2023/09/11 09:13:33 [070] * authenticating python index request (host: <private-repository>.d.codeartifact.us-west-2.amazonaws.com)
  proxy | 2023/09/11 09:13:34 [070] 200 https://<private-repository>.d.codeartifact.us-west-2.amazonaws.com:443/pypi/<private>/simple/requests/
updater | 2023/09/11 09:13:34 INFO <job_720270953> Latest version is 2.31.0
updater | 2023/09/11 09:13:34 INFO <job_720270953> Sending event b4cfd6d0b90644c5a0132e83d950bdde to Sentry
  proxy | 2023/09/11 09:13:34 [072] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/09/11 09:13:34 [072] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/09/11 09:13:34 ERROR <job_720270953> Error processing requests (NoMethodError)
updater | 2023/09/11 09:13:34 ERROR <job_720270953> undefined method `split' for #<Dependabot::Python::Version 2.31.0>
updater | 
updater |         version, @local_version = version.split("+")
updater |                                          ^^^^^^
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/python/lib/dependabot/python/version.rb:31:in `initialize'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:204:in `new'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:204:in `new'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:221:in `semver_rules_allow_grouping?'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:127:in `compile_updates_for'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:40:in `block in compile_all_dependency_changes_for'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:28:in `each'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:28:in `compile_all_dependency_changes_for'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:43:in `perform'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:105:in `run_update_for'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:89:in `block in run_grouped_dependency_updates'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:74:in `each'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:74:in `run_grouped_dependency_updates'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:42:in `perform'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:63:in `run'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/09/11 09:13:34 ERROR <job_720270953> bin/update_files.rb:23:in `<main>'
⋮
```
