### ISSUE TITLE
Dependabot encountered an unknown error, Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details.

### ISSUE THREAD

**Issue by visuman** [dependabot/dependabot-core#8004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

python 3.8

### Manifest location and content before the Dependabot update

```python
flask
jinja2
werkzeug
marshmallow
flask-sqlalchemy
sqlalchemy
alembic
marshmallow-sqlalchemy
flask-smorest

Flask-Cors
flask-talisman
sqlalchemy-utils
sqlalchemy-history==2.0.0



passlib



Flask-Babel

plotly
celery[redis]


python-dateutil
networkx<2.7; python_version=='3.7'
networkx; python_version>='3.8'

numpy
pandas
pyjnius
onnxruntime

stringcase
fs
dulwich
pyflakes
cryptography
dynaconf
dogpile.cache
cachetools
notifiers
click
requests
python-daemon

kaleido

jsonschema
zipp
webargs
typing-extensions
pyrsistent
pyparsing
protobuf
markupsafe
mako
kombu
itsdangerous
importlib-resources
importlib-metadata
decorator
apispec[marshmallow]
charset-normalizer==2.1.1
stevedore<4; python_version == "3.7" 
stevedore; python_version >= "3.8"
docutils

```

### dependabot.yml content

```yml
version: 2
updates:
    - package-ecosystem: pip
      directory: '/apps/project-api'
      schedule:
          interval: weekly
          day: sunday
          time: '01:00'
          timezone: 'Asia/Kolkata'
      groups:
          api-dependencies:
              patterns:
                  - '*'
              exclude-patterns:
                  - 'pandas'
                  - 'numpy'
          data-sci-dependencies:
              patterns:
                  - 'pandas'
                  - 'numpy'

      open-pull-requests-limit: 20
```

### What you expected to see, versus what you actually saw

I expected 2 PRs to be raised but pr was only raised for data-sci-dependencies

Dependabot log ends with return code = 0

There is no issue in the logs but the api-dependencies pr is not created for some reason
refer below for the update log
```bash

updater | +------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | ipython ( from  to 8.15.0 ), flask ( from 2.2.3 to 2.3.3 ), werkzeug ( from 2.2.3 to 2.3.7 ), marshmallow ( from 3.19... |
updater | | created | numpy ( from 1.24.2 to 1.25.2 ), pandas ( from 1.5.3 to 2.1.0 ) ..
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | time="2023-09-11T12:14:55Z" level=info msg="task complete" container_id=job-12345678-updater exit_code=0 job_id=720365914 step=updater
```

But seeing this error

<img width="913" alt="image" src="https://github.com/dependabot/dependabot-core/assets/57613660/7ff85bf1-865d-4da9-be7a-20f3ab53a251">

<img width="932" alt="image" src="https://github.com/dependabot/dependabot-core/assets/57613660/cae3c677-a1cf-41af-ae60-659310c5aafb">

**Comment by yeikel** [comment]
Can you provide a like to your repository? Or at least a snippet of your manifest?

**Comment by visuman** [comment]
@yeikel Modified the comment to add the content of base.txt in my project

**Comment by visuman** [comment]
@yeikel Let me know if you have some insights related to the issue. Thanks in advance

**Comment by vincentnonim** [comment]
Hi,

I have a similar issue with docker ecosystem.
![image](https://github.com/dependabot/dependabot-core/assets/2472342/2c28b290-19f8-4fbe-97d4-8207dceb8d48)
(Notice the green check mark)

No clear error in the logs and a message suggesting a PR will be created at the end :
```
updater | 2023/09/13 07:00:13 INFO Results:
updater | +-------------------------------------------------------+
updater | |          Changes to Dependabot Pull Requests          |
updater | +---------+---------------------------------------------+
updater | | created | keycloak/keycloak ( from 21.1.2 to 22.0.3 ) |
updater | +---------+---------------------------------------------+
updater | time="2023-09-13T07:00:13Z" level=info msg="task complete" container_id=job-721346619-updater exit_code=0 job_id=721346619 step=updater
```
But not PR created...
I also found this issue https://github.com/dependabot/dependabot-core/issues/7223 which looks related.

**Comment by jakecoffman** [comment]
@visuman we recently improved the error message around PR creation, can you try again and see if the error is more helpful now?

**Comment by cervebar** [comment]
We have same issue with `npm` package manager, this error and no logs generated at all:
```
  - directory: "/"
    package-ecosystem: npm
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      minor-patch-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "react-native"
        update-types:
          - "version-update:semver-minor"
```
<img width="825" alt="Screenshot 2023-11-28 at 18 28 50" src="https://github.com/dependabot/dependabot-core/assets/2403914/da38f8ff-4970-41e0-9fda-1fa5d488c051">

**Comment by visuman** [comment]
@ jakecoffman 
I can still observe the problem; the error message merely states that there was a failure in creating a pull request, providing no additional details.

**Comment by Lemon73-Computing** [comment]
I have same issue (`nuget`)

dependabot.yml
```yml
version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```


error code
```
updater | Dependabot encountered '2' error(s) during execution, please check the logs for more details.
updater | +----------------------------------------------------+
updater | |           Dependencies failed to update            |
updater | +------------------------------------+---------------+
updater | | CommunityToolkit.Maui.MediaElement | unknown_error |
updater | | CommunityToolkit.Maui              | unknown_error |
updater | +------------------------------------+---------------+
updater | time="2024-04-24T11:38:44Z" level=info msg="task complete" container_id=job-819224915-updater exit_code=0 job_id=819224915 step=updater
```



> <img alt="Screenshot 2023-11-28 at 18 28 50" width="825" src="https://private-user-images.githubusercontent.com/2403914/286347759-da38f8ff-4970-41e0-9fda-1fa5d488c051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTkxMjgsIm5iZiI6MTcxMzk1ODgyOCwicGF0aCI6Ii8yNDAzOTE0LzI4NjM0Nzc1OS1kYTM4ZjhmZi00OTcwLTQxZTAtOWZkYS0xZmE1ZDQ4OGMwNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMTE0MDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWYxMDgxMzJmOGI1MDhlNDQ3ODk4MjlmYzEwYzE0YjU1YzZmNjRkYzJlZTJhMDRjODRjMjAzNWZhMGZlNTc3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LOOq7SXaGcbFKbFB66pnvlBlV4FVhffol-7oIRSYO7Y">

**Comment by Lemon73-Computing** [comment]
In my case, it was fixed after nuget update.

```diff xml
<ItemGroup>
- 	<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
+ 	<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.21" />
- 	<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
+ 	<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.21" />
- 	<PackageReference Include="CommunityToolkit.Maui" Version="7.0.1" />
+ 	<PackageReference Include="CommunityToolkit.Maui" Version="9.0.0" />
- 	<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="3.0.1" />
+ 	<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="3.1.1" />
	<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
</ItemGroup>
```

**Comment by PawelLipski** [comment]
Same for Gradle ☹️ 

<img width="561" alt="image" src="https://github.com/user-attachments/assets/88cae177-a48b-4fd1-861c-b6cdf80fab71">

<img width="817" alt="image" src="https://github.com/user-attachments/assets/70092b8f-4971-474a-b449-e09bfa5e66ac">

**Comment by yeikel** [comment]
> Same for Gradle ☹️ 
> 
> <img width="561" alt="image" src="https://github.com/user-attachments/assets/88cae177-a48b-4fd1-861c-b6cdf80fab71">
> 
> <img width="817" alt="image" src="https://github.com/user-attachments/assets/70092b8f-4971-474a-b449-e09bfa5e66ac">
> 

Can you share your repository and/or more reproducible details? Every ecosystem is different

**Comment by PawelLipski** [comment]
> Can you share your repository and/or more reproducible details? Every ecosystem is different

Sure, the repository is https://github.com/VirtusLab/git-machete-intellij-plugin/, with [dependabot.yml](https://github.com/VirtusLab/git-machete-intellij-plugin/blob/develop/.github/dependabot.yml#L1) defined as follows (comments removed for clarity):

```yml
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - PawelLipski
    target-branch: develop
    ignore:
      - dependency-name: "org.slf4j:slf4j-simple"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
  - package-ecosystem: "gradle"
    directory: "/buildSrc/"
    schedule:
      interval: daily
    reviewers:
      - PawelLipski
    target-branch: develop
    ignore:
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
```

I've noticed I [stopped receiving dependabot updates](https://github.com/VirtusLab/git-machete-intellij-plugin/pulls?q=is%3Apr+is%3Aclosed+from%3A%40dependabot) after July 10th:

<img width="876" alt="image" src="https://github.com/user-attachments/assets/951611bf-dc45-47f6-9ba3-e77c2f9e5c91">

Let me know if I can provide more useful info here.
