### ISSUE TITLE
Dependabot stopped working with unknown_error

### ISSUE THREAD

**Issue by JohnnyDevNull** [dependabot/dependabot-core#8023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

^9.8.0

### Language version

Node 18.16.0

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: '04:00'
    # Disable rebasing for npm pull requests
    rebase-strategy: "disabled"
    open-pull-requests-limit: 10
    ignore:
        # we have an update process for our own packages, no need to check them
      - dependency-name: "@redmedical/datamodels"
      - dependency-name: "@redmedical/pruefmodule"
      - dependency-name: "@redmedical/rules-engine"
      - dependency-name: "@redmedical/server"
      - dependency-name: "@redmedical/webrtc-server"
      - dependency-name: "@redmedical/cardreaders"
      - dependency-name: "@redmedical/reddocker"
        # kbv package updates needs manual investigation and is due to its own repo not possible through dependabot
      - dependency-name: "kbv.ita.eau"
      - dependency-name: "kbv.ita.for"
        # updates broke our special character handling with non utf8 charset
      - dependency-name: "bwip-js"
        # we just allow to update fix and minor versions
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
```

### What you expected to see, versus what you actually saw

Dependabot stopped opending PR's. The log says nothing specific just unknown_error's

```
updater | Dependabot encountered '10' error(s) during execution, please check the logs for more details.
updater | +----------------------------------------------+
updater | |        Dependencies failed to update         |
updater | +------------------------------+---------------+
updater | | cypress-terminal-report      | unknown_error |
updater | | ibankit                      | unknown_error |
updater | | jest-environment-jsdom       | unknown_error |
updater | | zone.js                      | unknown_error |
updater | | tinymce-i18n                 | unknown_error |
updater | | jest                         | unknown_error |
updater | | @swc/core                    | unknown_error |
updater | | @types/node                  | unknown_error |
updater | | cypress-mochawesome-reporter | unknown_error |
updater | | eslint                       | unknown_error |
updater | +------------------------------+---------------+
```

e.g. (I've replaced the internal url with ..., this packages are btw on the ignore list)

```
updater | 2023/09/13 04:14:38 INFO <job_721289479>   version-update:semver-major - from .github/dependabot.yml
  proxy | 2023/09/13 04:14:38 [014] GET https://registry.npmjs.org:443/cypress-terminal-report
  proxy | 2023/09/13 04:14:38 [014] 200 https://registry.npmjs.org:443/cypress-terminal-report
  proxy | 2023/09/13 04:14:38 [016] GET https://registry.npmjs.org:443/cypress-terminal-report/5.3.4
  proxy | 2023/09/13 04:14:39 [016] 200 https://registry.npmjs.org:443/cypress-terminal-report/5.3.4
updater | 2023/09/13 04:14:39 INFO <job_721289479> Latest version is 5.3.4
  proxy | 2023/09/13 04:15:13 [018] GET https://registry.npmjs.org:443/cypress-terminal-report
  proxy | 2023/09/13 04:15:13 [018] 200 https://registry.npmjs.org:443/cypress-terminal-report
  proxy | 2023/09/13 04:15:14 [020] GET https://.../@redmedical%2fserver/-/server-77.2.0.tgz
  proxy | 2023/09/13 04:15:14 [020] WARN: Cannot read TLS response from mitm'd server dial tcp 45.95.108.137:443: connect: connection refused
  proxy | 2023/09/13 04:15:24 [022] GET https://.../@redmedical%2fserver/-/server-77.2.0.tgz
  proxy | 2023/09/13 04:15:24 [022] WARN: Cannot read TLS response from mitm'd server dial tcp 45.95.108.137:443: connect: connection refused
  proxy | 2023/09/13 04:16:24 [024] GET https://.../@redmedical%2fserver/-/server-77.2.0.tgz
  proxy | 2023/09/13 04:16:24 [024] WARN: Cannot read TLS response from mitm'd server dial tcp 45.95.108.137:443: connect: connection refused
updater | 2023/09/13 04:16:24 INFO <job_721289479> Requirements to unlock own
updater | 2023/09/13 04:16:24 INFO <job_721289479> Requirements update strategy bump_versions
updater | 2023/09/13 04:16:24 INFO <job_721289479> Updating cypress-terminal-report from 5.3.3 to 5.3.4
  proxy | 2023/09/13 04:16:52 [026] GET https://.../@redmedical%2fserver/-/server-77.2.0.tgz
  proxy | 2023/09/13 04:16:52 [026] WARN: Cannot read TLS response from mitm'd server dial tcp 45.95.108.137:443: connect: connection refused
  proxy | 2023/09/13 04:17:02 [028] GET https://.../@redmedical%2fserver/-/server-77.2.0.tgz
  proxy | 2023/09/13 04:17:02 [028] WARN: Cannot read TLS response from mitm'd server dial tcp 45.95.108.137:443: connect: connection refused
  proxy | 2023/09/13 04:18:02 [030] GET https://.../@redmedical%2fserver/-/server-77.2.0.tgz
  proxy | 2023/09/13 04:18:02 [030] WARN: Cannot read TLS response from mitm'd server dial tcp 45.95.108.137:443: connect: connection refused
updater | 2023/09/13 04:18:02 INFO <job_721289479> Sending event 5a98466377e845a78012ec3931f54161 to Sentry
  proxy | 2023/09/13 04:18:03 [032] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/09/13 04:18:03 [032] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/09/13 04:18:03 ERROR <job_721289479> Error processing cypress-terminal-report 
```

The same picture for all `unknown_error` and no PR's opened.
