### ISSUE TITLE
Add `ignore-update-types` at the group level

### ISSUE THREAD

**Issue by jasongitmail** [dependabot/dependabot-core#8055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Given the below, the `major` group will actually update major, minor, & patch versions. However, my goal is for that group to match `major` versions only.  

(This would allow greater me to automate minor and patch updates, but never major updates.) 

```yml
  - package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
    directory: '/'
    target-branch: 'main'
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'npm'
    groups:
      minor-and-patch-only:
        patterns: '*'
        update-types: ['minor', 'patch']
      major-only: # This is *not* major only; PRs are opened for major, minor, & patch.
        patterns: '*'
        update-types: 'major'
```

However, currently, `ignore` seems only supported at a higher level, meaning that to use it would require duplicating the entire block, and then specifying only one "group" in each of their "groups" properties. Not DRY and is verbose.

Suggestion:

```yml
  - package-ecosystem: 'npm'
    schedule:
      interval: 'monthly'
    directory: '/'
    target-branch: 'main'
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'npm'
    groups:
      minor-and-patch-only:
        patterns: '*'
        update-types: ['minor', 'patch']
      major-only: 
        patterns: '*'
        update-types: 'major'
        ignore-update-types: ['minor', 'patch']  # <- suggestion
```
