### ISSUE TITLE
cannot find module providing package

### ISSUE THREAD

**Issue by alekc** [dependabot/dependabot-core#8063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Golang

### Language version

1.21

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: [ dependencies ]
    assignees: [ alekc ]
    reviewers: [ alekc ]
    commit-message:
      prefix: "*:"
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directory: "/"
    labels: [ dependencies ]
    assignees: [ alekc ]
    reviewers: [ alekc ]
    commit-message:
      prefix: "*:"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

Possibly duplicate of https://github.com/dependabot/dependabot-core/issues/4925.

While running dependabot on latest head (https://github.com/alekc/terraform-provider-kubectl/commit/4ec82ee81700368394abb7e094fa5264e4c1fcb5) gives following error:

```
  proxy | 2023/09/18 19:45:51 [300] 200 https://proxy.golang.org:443/github.com/hashicorp/terraform/@v/list
updater | 2023/09/18 19:45:51 INFO <job_723263844> Handled error whilst updating github.com/hashicorp/terraform: dependency_file_not_resolvable {:message=>"github.com/hashicorp/terraform/lang/funcs: cannot find module providing package github.com/hashicorp/terraform/lang/funcs"}
```

Compilation works fine and go.mod looks fine to me.
