### ISSUE TITLE
[Poetry] Dependabot does not ignore an explicitly excluded version in pyproject.toml

### ISSUE THREAD

**Issue by Mindstan** [dependabot/dependabot-core#8080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Poetry

### Package manager version

1.5.2

### Language version

3.9

### Manifest location and content before the Dependabot update

The `pyproject.toml` is located in `/server/pyproject.toml`, with a content like the following:

```toml
[tool.poetry]
name = "example"
version = "3"
description = "Example"
authors = []

[tool.poetry.dependencies]
python = "~3.9"
Django = "~4.2, !=4.2.5"
```

We are using a private registry for some of the packages, but not for Django.

### dependabot.yml content

```yaml
version: 2

updates:
  - package-ecosystem: pip
    directory: /server
    insecure-external-code-execution: "allow"
    groups:
      django:
        patterns:
          - "Django"
          - "django-*"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Paris"
    target-branch: master
    open-pull-requests-limit: 10
    rebase-strategy: disabled
```

### Updated dependency

Django has been updated from `4.2.4` to `4.2.5`.

### What you expected to see, versus what you actually saw

I expect Dependabot to skip Django version `4.2.5` and not trigger a PR because it is explicitly excluded. This syntax is valid according to [Poetry documentation](https://python-poetry.org/docs/dependency-specification/#multiple-requirements).

Dependabot did open a PR to update Django to `4.2.5`, it also removed the excluded version from `pyproject.toml`.

### Native package manager behavior

```
❯ poetry update
Warning: In a future version of Poetry, PyPI will be disabled automatically if at least one custom source is configured with another priority than 'explicit'. In order to avoid a breaking change and make your pyproject.toml forward compatible, add PyPI explicitly via 'poetry source add pypi'. By the way, this has the advantage that you can set the priority of PyPI as with any other source.
Updating dependencies
Resolving dependencies... (23.8s)

No dependencies to install or update

❯ poetry show django
[Warning: …]
 name         : django                                                                                           
 version      : 4.2.4 
```

### Images of the diff or a link to the PR, issue, or logs

In `pyproject.toml`:

```
-Django = "~4.2, !=4.2.5"
+Django = "~4.2"
```

In `poetry.lock`:

```
 [[package]]
 name = "django"
-version = "4.2.4"
+version = "4.2.5"
 description = "A high-level Python web framework that encourages rapid development and clean, pragmatic design."
 optional = false
 python-versions = ">=3.8"
 files = [
-    {file = "Django-4.2.4-py3-none-any.whl", hash = "sha256:860ae6a138a238fc4f22c99b52f3ead982bb4b1aad8c0122bcd8c8a3a02e409d"},
-    {file = "Django-4.2.4.tar.gz", hash = "sha256:7e4225ec065e0f354ccf7349a22d209de09cc1c074832be9eb84c51c1799c432"},
+    {file = "Django-4.2.5-py3-none-any.whl", hash = "sha256:b6b2b5cae821077f137dc4dade696a1c2aa292f892eca28fa8d7bfdf2608ddd4"},
+    {file = "Django-4.2.5.tar.gz", hash = "sha256:5e5c1c9548ffb7796b4a8a4782e9a2e5a3df3615259fc1bfd3ebc73b646146c1"},
 ]
```

### Smallest manifest that reproduces the issue

```toml
[tool.poetry]
name = "example"
version = "3"
description = "Example"
authors = []

[tool.poetry.dependencies]
python = "~3.9"
Django = "~4.2, !=4.2.5"
```
