### ISSUE TITLE
Casing for group names not kept using grouped NuGet packages

### ISSUE THREAD

**Issue by Gakk** [dependabot/dependabot-core#8111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### dependabot.yml content

```yaml
version: 2

registries:

  nuget-org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

  github-packages:
    type: nuget-feed
    url: https://xxxxxxxx

updates:

  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"

    groups:
      EntityFrameworkCore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
```

### What you expected to see, versus what you actually saw

For regular updates outside the group, I get a title like:

> **Bump Polly from 7.2.4 to 8.0.0**

For grouped updates the casing is lost. Even though the group name in `.dependabot.yml` is `EntityFrameworkCore`, the opened pull request's title is:

> **Bump the entityframeworkcore group with 4 updates**

I would have expected it to be:

> **Bump the EntityFrameworkCore group with 4 updates**

Even better would be if I in the `.dependabot.yml` could specify a group name with special characters like period (`.`) that is common using NuGet. Ideally the name for my group should be `Microsoft.EntityFrameworkCore`, and I would like the title to be:

> **Bump the Microsoft.EntityFrameworkCore group with 4 updates**

**Comment by aalsamoht** [comment]
It is possible to use a period in the group name by wrapping the group name with quotations.
This does not fix the casing problem and the periods are replaced with hyphens.

```yml
groups:
  'Microsoft.EntityFrameworkCore':
    patterns:
      - "Microsoft.EntityFrameworkCore.*"
```
*Bump the microsoft-entityframeworkcore group with 2 updates*
