### ISSUE TITLE
YAML string quotes prevent version comment updates

### ISSUE THREAD

**Issue by kurtmckee** [dependabot/dependabot-core#8125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

GitHub Actions

### What you expected to see, versus what you actually saw

I tried using git SHAs with version comments and expected Dependabot to keep the version comment updated. However, when YAML string quotes are present, the version comment doesn't get updated. Easy example:

```yaml
- uses: "actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81" # v2.1.0
```

Dependabot will submit a PR to update only the git SHA, but not the comment.

### Smallest manifest that reproduces the issue

```yaml
on: ["push"]

name: "Integration"
jobs:
  chore:
    steps:
      - uses: "actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81" # v2.1.0
```
