### ISSUE TITLE
Dependabot tries to access to private repos that are ignored

### ISSUE THREAD

**Issue by evandam** [dependabot/dependabot-core#8136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Git

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # NOTE: Try lots of options to see if any work
    ignore:
      - dependency-name: "unicorn/my_github_actions"
      - dependency-name: "*unicorn/*"
      - dependency-name: "*unicorn*"
      - dependency-name: "*"
      - dependency-name: "*/*"
```

### What you expected to see, versus what you actually saw

Expect dependabot to run successfully. Instead, the Dependabot run fails because it fails to access private GitHub actions like `unicorn/my_github_actions`, which should be ignored.

Logs:

```
  proxy | 2023/10/03 23:20:10 [034] * authenticating git server request (host: github.com)
  proxy | 2023/10/03 23:20:10 [034] 404 https://github.com:443/unicorn/my_github_actions.git/info/refs?service=git-upload-pack
  proxy | 2023/10/03 23:20:10 [034] * auth'd git request returned 404, retrying without auth
  proxy | 2023/10/03 23:20:10 [034] * de-auth'd request returned 401, replacing response
updater | 2023/10/03 23:20:11 INFO <job_730154402> Finished job processing
updater | 2023/10/03 23:20:11 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------------------+
updater | |             Errors             |
updater | +--------------------------------+
updater | | git_dependencies_not_reachable |
updater | +--------------------------------+
updater | time="2023-10-03T23:20:11Z" level=info msg="task complete" container_id=job-730154402-updater exit_code=0 job_id=730154402 step=updater

```

### Smallest manifest that reproduces the issue

Can try to have a GitHub workflow that references a private GitHub workflow:

```yaml
name: Test

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: unicorn/my_github_actions
        with:
          ...
```
