### ISSUE TITLE
Dependency update has individual PR *and* included in group

### ISSUE THREAD

**Issue by bd-g** [dependabot/dependabot-core#8145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

cargo

### Manifest location and content before the Dependabot update

/Cargo.toml
/Cargo.lock

### dependabot.yml content

```
version: 2
registries:
  github:
    type: git
    url: https://api.github.com
    username: x-access-token
    password: ********
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    registries:
      - github
    schedule:
      interval: "daily"
    groups:
      dependencies:
        update-types: [ patch, minor ]
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    registries:
      - github
    schedule:
      interval: "weekly"
    groups:
      submodules:
        patterns:
        - "*"
```

### Updated dependency

Bump aws-sdk-s3 from 0.31.2 to 0.32.0
Bump csv from 1.2.2 to 1.3.0
...(many others)

### What you expected to see, versus what you actually saw

I have a dependency group for Cargo that is successfully grouping updates. The above `aws-sdk-s3` and `csv` updates, among others, are being groups in a single PR.

However, Dependabot is also opening individual PRs for each dependency. So the dependency bump is being included in two places, when it should only be included in the group PR.
