### ISSUE TITLE
Dependabot is bumping exact versions in Poetry

### ISSUE THREAD

**Issue by winstxnhdw** [dependabot/dependabot-core#8160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

poetry

### Package manager version

1.6.1

### Language version

3.12

### dependabot.yml content

```yaml
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
       dependencies:
          patterns: ['*']
```

### Updated dependency

`torch` keeps being bumped from 2.0.0 to 2.1.0.

### What you expected to see, versus what you actually saw

```toml
[tool.poetry.group.special.dependencies]
torch = "2.0.0"
```

```toml
[tool.poetry.group.special.dependencies]
torch = "2.1.0"
```

Should not be bumped at all.
