### ISSUE TITLE
NuGet: updates are offered despite ignore rules

### ISSUE THREAD

**Issue by bkoelman** [dependabot/dependabot-core#8182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Package manager version

NuGet Command Line 6.7.0.127

### Language version

C# 10, .NET 6

### Manifest location and content before the Dependabot update

Applicable snippet from `Directory.Build.props`, which defines the version properties:
```xml
<Project>
  <PropertyGroup>
    <TargetFrameworkName>net6.0</TargetFrameworkName>
    <EntityFrameworkCoreFrozenVersion>6.0.0</EntityFrameworkCoreFrozenVersion>
    <EntityFrameworkCoreVersion>7.0.*</EntityFrameworkCoreVersion>
  </PropertyGroup>
</Project>
```

Usage in .csproj file that produces our NuGet package (uses frozen version to prevent breaking changes):
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkName)</TargetFramework>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EntityFrameworkCoreFrozenVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkCoreFrozenVersion)" />
  </ItemGroup>
</Project>
```

Usage in .csproj files for tests (uses non-frozen version):
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkName)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkCoreVersion)" />
  </ItemGroup>
</Project>
```

### dependabot.yml content

```
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  pull-request-branch-name:
    separator: "-"
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 25
  ignore:
  # Block updates to all exposed dependencies of the NuGet packages we produce, as updating them would be a breaking change.
  - dependency-name: 'Ben.Demystifier'
  - dependency-name: 'Humanizer*'
  - dependency-name: 'Microsoft.CodeAnalysis*'
  - dependency-name: 'Microsoft.EntityFrameworkCore*'
  # Block major updates of packages that require a matching .NET version.
  - dependency-name: 'Microsoft.AspNetCore*'
    update-types: ["version-update:semver-major"]
```

### Updated dependency

Bumps EntityFrameworkCoreVersion from 6.0.0 to 7.0.12.
Updates Microsoft.EntityFrameworkCore.Relational from 6.0.0 to 7.0.12

### What you expected to see, versus what you actually saw

We have two version properties in `Directory.Build.props`: 
- `EntityFrameworkCoreFrozenVersion` = 6.0.0
- `EntityFrameworkCoreVersion` = 7.0.*

The first one must never be updated, because it would introduce a breaking change in the NuGet package we produce. The second one is used from our test projects, where we always want to use the latest version, so we'll know when something breaks. Because dependabot doesn't support ignore rules per project/directory, we decided to ignore the package completely using the below configuration:

```yaml
- package-ecosystem: nuget
  directory: "/"
  ignore:
  # Block updates to all exposed dependencies of the NuGet packages we produce, as updating them would be a breaking change.
  - dependency-name: 'Microsoft.EntityFrameworkCore*'
```

However, dependabot still offers to update the `Microsoft.EntityFrameworkCore.Relational` package by changing the value of `EntityFrameworkCoreFrozenVersion` to 7.0.12. This is unexpected.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1356
