### ISSUE TITLE
NuGet: package update is offered that is incompatible with the target framework

### ISSUE THREAD

**Issue by bkoelman** [dependabot/dependabot-core#8183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Package manager version

NuGet Command Line 6.7.0.127

### Language version

C# 10, .NET 6

### Manifest location and content before the Dependabot update

Applicable snippet from `Directory.Build.props`, which defines the version property:
```xml
<Project>
  <PropertyGroup>
    <TargetFrameworkName>net6.0</TargetFrameworkName>
    <AspNetCoreVersion>6.0.*</AspNetCoreVersion>
  </PropertyGroup>
</Project>
```

Usage in .csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkName)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(AspNetCoreVersion)" />
  </ItemGroup>
</Project>
```

### dependabot.yml content

```yml
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  pull-request-branch-name:
    separator: "-"
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 25
  ignore:
  # Block updates to all exposed dependencies of the NuGet packages we produce, as updating them would be a breaking change.
  - dependency-name: 'Ben.Demystifier'
  - dependency-name: 'Humanizer*'
  - dependency-name: 'Microsoft.CodeAnalysis*'
  - dependency-name: 'Microsoft.EntityFrameworkCore*'
  # Block major updates of packages that require a matching .NET version.
  - dependency-name: 'Microsoft.AspNetCore*'
    update-types: ["version-update:semver-major"]
```

### Updated dependency

Updates the requirements on [Microsoft.AspNetCore.Mvc.Testing](https://github.com/dotnet/aspnetcore) to permit the latest version.

The PR updates `AspNetCoreVersion` in `Directory.Build.props` from 6.0.* to 7.0.*.

### What you expected to see, versus what you actually saw

First of all, the update should not be offered because we have an ignore rule in `dependabot.yml` (possibly related to #8182):
```yml
- package-ecosystem: nuget
  directory: "/"
  ignore:
  # Block major updates of packages that require a matching .NET version.
  - dependency-name: 'Microsoft.AspNetCore*'
    update-types: ["version-update:semver-major"]
```

Assuming the ignore rule does not work, the package update should still not be offered. Because v6.0.* is compatible solely with .NET 6 (see [here](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing/6.0.23#supportedframeworks-body-tab)), whereas v7.* is solely compatible with .NET 7 (see [here](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing/7.0.12#supportedframeworks-body-tab)). Because our project does not target .NET 7, the update can never work.

Error from continuous integration build:
```
error NU1202: Package Microsoft.AspNetCore.Mvc.Testing 7.0.12 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.Mvc.Testing 7.0.12 supports: net7.0 (.NETCoreApp,Version=v7.0)
```

There are many more packages whose versions are tightly bound to the .NET framework version. They can only be updated when updating the target framework as well. For example:
- Microsoft.AspNetCore.Authentication.Certificate
- Microsoft.AspNetCore.Authentication.JwtBearer
- Microsoft.AspNetCore.Authentication.OpenIdConnect
- Microsoft.AspNetCore.Cryptography.KeyDerivation
- Microsoft.AspNetCore.DataProtection
- Microsoft.AspNetCore.DataProtection.StackExchangeRedis
- Microsoft.AspNetCore.TestHost
- Microsoft.Extensions.Caching.StackExchangeRedis
- Microsoft.Extensions.Diagnostics.HealthChecks

Unless dependabot also updates the target framework (which, fortunately, it does not), there is no point in offering PRs for major version changes.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1355
