### ISSUE TITLE
libs.toml doesn't mean the dependency is used!

### ISSUE THREAD

**Issue by xenoterracide** [dependabot/dependabot-core#8205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

8.4

### Manifest location and content before the Dependabot update

`/gradle/libs.toml`

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```

### What you expected to see, versus what you actually saw

given

```toml
dgs-platform = "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:4.+"
```

when no reference to `libs.dgs.platform` in any `build.gradle*` or `*gradle.lockfile` exists
then this dependency doesn't need to be updated because it *isn't* used.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/xenoterracide/ai-wh40k/pull/33

### Smallest manifest that reproduces the issue

```toml
dgs-platform = "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:4.+"
```
