### ISSUE TITLE
On GH Enterprise, can't update private github-action from same organization

### ISSUE THREAD

**Issue by Drowze** [dependabot/dependabot-core#8283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

Some GitHub Actions workflow at `.github/workflows/`:

```yml
name: Move Tickets To Ready To Test
on:
  release:
    types:
      - published
jobs:
  move-ok-tickets-from-rfd-to-rtt:
    name: Move Tickets To Ready To Test
    runs-on: ubuntu-latest
    steps:
      - uses: Over-haul/private-actions/action-move-jira-tickets-to-ready-to-test@v2
        with:
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          jira_user_email: ${{ secrets.JIRA_USER_EMAIL }}
```

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[Dependabot]"
    pull-request-branch-name:
      separator: "-"
```

### What you expected to see, versus what you actually saw

Here at Over-haul, we have a single repository (mentioned here as `private-actions`) defining multiple actions (in the example here, `action-move-jira-tickets-to-ready-to-test`), that repository is then configured to share actions with all repositories within our organzation (I think this is a GitHub Enterprise feature - we use GitHub Enterprise Cloud), see:
![Screenshot 2023-10-26 at 10 29 49](https://github.com/dependabot/dependabot-core/assets/9031589/ca1bc6c9-581e-4f92-b0b3-57fcfe781a83)

This works fine for us - a lot of our repositories have been using the centralized actions defined at `private-actions` repository for a while.
We're now trying to add Dependabot to the mix, so repositories are able to update whatever actions they use (including actions defined at `private-actions`), but apparently Dependabot is not able to access `private-actions` repository. See an excerpt from the logs:
```
updater | 2023/10/26 12:56:52 INFO Raven 3.1.2 ready to catch errors
updater | 2023/10/26 12:56:53 INFO <job_741321542> Starting job processing
  proxy | 2023/10/26 12:56:54 [022] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2023/10/26 12:56:54 [022] * authenticating git server request (host: github.com)
  proxy | 2023/10/26 12:56:54 [022] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2023/10/26 12:56:54 [024] GET https://github.com:443/over-haul/private-actions.git/info/refs?service=git-upload-pack
  proxy | 2023/10/26 12:56:54 [024] * authenticating git server request (host: github.com)
  proxy | 2023/10/26 12:56:54 [024] 404 https://github.com:443/over-haul/private-actions.git/info/refs?service=git-upload-pack
  proxy | 2023/10/26 12:56:54 [024] * auth'd git request returned 404, retrying without auth
  proxy | 2023/10/26 12:56:54 [024] * de-auth'd request returned 401, replacing response
  proxy | 2023/10/26 12:56:54 [026] GET https://github.com:443/over-haul/private-actions.git/info/refs?service=git-upload-pack
  proxy | 2023/10/26 12:56:54 [026] * authenticating git server request (host: github.com)
  proxy | 2023/10/26 12:56:54 [026] 404 https://github.com:443/over-haul/private-actions.git/info/refs?service=git-upload-pack
  proxy | 2023/10/26 12:56:54 [026] * auth'd git request returned 404, retrying without auth
  proxy | 2023/10/26 12:56:54 [026] * de-auth'd request returned 401, replacing response
updater | 2023/10/26 12:56:54 INFO <job_741321542> Finished job processing
updater | 2023/10/26 12:56:54 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------------------+
updater | |             Errors             |
updater | +--------------------------------+
updater | | git_dependencies_not_reachable |
updater | +--------------------------------+
updater | time="2023-10-26T12:56:55Z" level=info msg="task complete" container_id=job-741321542-updater exit_code=0 job_id=741321542 step=updater
```

We would expect that Dependabot is able to actions from `private-actions`, e.g.:
```
Over-haul/private-actions/action-move-jira-tickets-to-ready-to-test@v2
to
Over-haul/private-actions/action-move-jira-tickets-to-ready-to-test@v3
```
