### ISSUE TITLE
PRs aren't grouped despite a valid configuration

### ISSUE THREAD

**Issue by kirilllzaitsev** [dependabot/dependabot-core#8325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

Python 3.9

### dependabot.yml content
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 15
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
```

As in https://github.com/dependabot/dependabot-core/issues/7987.

### What you expected to see, versus what you actually saw

All updates as per the YAML should be grouped in a single PR.
This is what I got instead:
![image](https://github.com/dependabot/dependabot-core/assets/44346535/3500b129-b0ea-423f-a6df-ef26584edd0b)
