### ISSUE TITLE
Fails to find latest version of Maven plugins from Apache

### ISSUE THREAD

**Issue by ppkarwasz** [dependabot/dependabot-core#8329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

maven

### Manifest location and content before the Dependabot update

https://github.com/apache/logging-parent/blob/main/pom.xml

### dependabot.yml content

https://github.com/apache/logging-parent/blob/main/.github/dependabot.yaml

### Updated dependency

`org.apache.maven.plugins:maven-artifact-plugin`

### Expected behavior ###

I expected Dependabot to detect that the `maven-artifact-plugin` has a new 3.5.0 version and open a PR.

### Actual behavior ###

As you can see in [this Dependabot run](https://github.com/apache/logging-parent/network/updates/744995003), Dependabot fails to even determine the latest versions of all plugins based on the newest ASF parent POM ( [`org.apache:apache:30`](https://repo.maven.apache.org/maven2/org/apache/apache/30/)) and the version of the parent POM itself. Only the `snapshots` repository in the `<pluginRepositories>` is used and the `release` repository is not even queried: I don't see a `GET https://repo.maven.apache.org:443/<...>/maven-metadata.xml` there.

```
updater | 2023/11/03 09:05:39 INFO <job_744995003> Checking if org.apache.maven.plugins:maven-artifact-plugin 3.4.1 needs updating
  proxy | 2023/11/03 09:05:39 [162] GET https://repo.maven.apache.org:443/maven2/org/apache/apache/30/apache-30.pom
  proxy | 2023/11/03 09:05:39 [162] 200 https://repo.maven.apache.org:443/maven2/org/apache/apache/30/apache-30.pom
  proxy | 2023/11/03 09:05:39 [164] GET https://repository.apache.org:443/snapshots/org/apache/maven/plugins/maven-artifact-plugin/maven-metadata.xml
  proxy | 2023/11/03 09:05:39 [164] 200 https://repository.apache.org:443/snapshots/org/apache/maven/plugins/maven-artifact-plugin/maven-metadata.xml
updater | 2023/11/03 09:05:39 INFO <job_744995003> Latest version is 
...
updater | 2023/11/03 09:05:38 INFO <job_744995003> Checking if org.apache:apache 30 needs updating
  proxy | 2023/11/03 09:05:38 [138] GET https://repo.maven.apache.org:443/maven2/org/apache/apache/30/apache-30.pom
  proxy | 2023/11/03 09:05:38 [138] 200 https://repo.maven.apache.org:443/maven2/org/apache/apache/30/apache-30.pom
  proxy | 2023/11/03 09:05:38 [140] GET https://repository.apache.org:443/snapshots/org/apache/apache/maven-metadata.xml
  proxy | 2023/11/03 09:05:38 [140] 200 https://repository.apache.org:443/snapshots/org/apache/apache/maven-metadata.xml
updater | 2023/11/03 09:05:38 INFO <job_744995003> Latest version is 
```

**Comment by ppkarwasz** [comment]
We were able to workaround this problem by configuring Maven Central as a "private registry" explicitly:

```yaml
# Add Maven Central explicitly to work around:
#   https://github.com/dependabot/dependabot-core/issues/8329
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "main"
  registries:
    - maven-central
```

**Comment by kwin** [comment]
I disagree that this should be closed, dependabot should be able to deal with multiple repos.

**Comment by lprimak** [comment]
You are right

**Comment by v-thavaahariharangit** [comment]
I attempted to reproduce the issue described.

`pom.xml`
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.apache</groupId>
    <artifactId>apache</artifactId>
    <version>30</version>
  </parent>

  <groupId>com.example</groupId>
  <artifactId>artifact-plugin-test</artifactId>
  <version>1.0.0</version>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-artifact-plugin</artifactId>
        <version>3.5.0</version>
      </plugin>
    </plugins>
  </build>

  <pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <url>https://repo.maven.apache.org/maven2</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

</project>
```

`.github/dependabot.yml`
```
version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```
Internal repo: maven-dependabot-core-issue-8329


I was unable to reproduce the issue mentioned in the report:
> I expected Dependabot to detect that the maven-artifact-plugin has a new 3.5.0 version and open a PR.

A pull request was successfully created

<img width="1136" height="854" alt="Image" src="https://github.com/user-attachments/assets/8379de79-72b0-4bf9-b6b4-60554e6c2ee4" />

With this confirmation, I am closing the issue.
