### ISSUE TITLE
Support for common dependencies in `melos.yaml`

### ISSUE THREAD

**Issue by spydon** [dependabot/dependabot-core#8349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Many Dart and Flutter projects use [Melos](https://github.com/invertase/melos) to handle their monorepos and from version [3.2.0](https://github.com/invertase/melos/pull/526) Melos supports specifying [shared dependencies](https://melos.invertase.dev/commands/bootstrap#shared-dependencies) in the `melos.yaml` file.

These dependencies are specified in the same manner as in the `pubspec.yaml` file except that they are a subsection of the `bootstrap` section, so it should be fairly trivial to re-use the already existing code for updating the normal `pubspec.yaml` files.

**Comment by spydon** [comment]
From Melos 7.0.0 it will use the root pubspec file and use the same structure as before, but under the `melos` key. Example:
pubspec.yaml
```yaml
melos:
  command:
    bootstrap:
      dependencies:
        ...
      dev_dependencies:
        ...
```
