### ISSUE TITLE
Malformed version number string when recreating using Git SHA

### ISSUE THREAD

**Issue by mering** [dependabot/dependabot-core#8358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### Manifest location and content before the Dependabot update

```
uses: "OWNER/REPO/.github/actions/ACTION@SHA" # ratchet:OWNER/REPO/.github/actions/ACTION@main
```

### dependabot.yml content

```yaml
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

Action Git history:
`SHA1` -> `SHA2` -> `SHA3`

1. The onsumer uses `@SHA1`
2. Dependabot creates a PR to `@SHA2` but nobody merges it
3. Upstream commits `SHA3`

Now when I try `@dependabot recreate` or `@dependabot rebase` dependabot fails with and the logs show "Malformed version number string".

### Related issues

#7387 might be related.
