### ISSUE TITLE
Support bumping `uses: docker://…` in GitHub Actions workflows

### ISSUE THREAD

**Issue by l0b0** [dependabot/dependabot-core#8362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### To reproduce

1. Create a new Git repo
2. Create `.github/workflows/main.yml` containing

   ```
   on: [push]
   jobs:
     main:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Check workflow files
           uses: docker://rhysd/actionlint:1.6.25@sha256:86ebdb1c0df5a8be92b9d53e2e0c636978a2b3c6e52c86c65a77e2c78a6bd594
   ```
3. Create `.github/dependabot.yml` containing

   ```
   version: 2
   updates:
   - package-ecosystem: "github-actions"
     directory: "/"
     schedule:
       interval: daily
   ```
4. Push to GitHub
5. Run Dependabot

What happens: No PRs are created

What should happen: Dependabot should create a PR changing `uses: docker://rhysd/actionlint:1.6.25@sha256:86ebdb1c0df5a8be92b9d53e2e0c636978a2b3c6e52c86c65a77e2c78a6bd594` to `uses: docker://rhysd/actionlint:1.6.26@sha256:2eb91a78b5a19140be099c7b4262d298c2567f2a9f27e10ed2a4323c5bcface8`.

### Other info

This seems to be a known problem based on [this comment](https://github.com/dependabot/dependabot-core/blob/4d22252e0d1afa6b72907d3db0a4243f0a17a941/github_actions/lib/dependabot/github_actions/file_parser.rb#L48), but I couldn't find an associated issue.
