### ISSUE TITLE
Unignore Fails With "Non Grouped Update Pull Requests do not support unignore commands."

### ISSUE THREAD

**Issue by Kurt-von-Laven** [dependabot/dependabot-core#8382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

3.6.3

### Language version

Node.js 20.9.0

### Manifest location and content before the Dependabot update

Relevant excerpt from `package.json`:

```json
{
  "devDependencies": {
    "@types/node": "^20.8.10"
  }
}
```

### dependabot.yml content

Relevant excerpt from `.github/dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
    assignees:
      - Kurt-von-Laven
    reviewers:
      - Kurt-von-Laven
    open-pull-requests-limit: 1
```

### Updated dependency

`@types/node`: 20.8.10 --> 20.9.0

### What you expected to see, versus what you actually saw

I expected it to be possible to use `@dependabot unignore` to remove an ignore condition, but it was not. My end goal was to enable Dependabot to open a pull request to bump `@types/node` to the latest version, 20.9.0.

### Native package manager behavior

`yarn upgrade-interactive` detects that `@types/node` should be updated and does so correctly.

### Images of the diff or a link to the PR, issue, or logs

`@dependabot show @types/node ignore conditions` gives:

<details>
<summary>Ignore Conditions</summary>
<br />

|Dependency| Ignore Condition|
|-|-|
| @types/node | [>= 20.a, < 21] |
</details>

`@dependabot unignore @types/node [>= 20.a, < 21]` and `@dependabot unignore @types/node dependency` both give the same error regardless of whether they are run on the non-grouped `@types/node` bump to v20 where `@dependabot ignore this major version` was originally run or an unrelated grouped pull request:

`Non Grouped Update Pull Requests do not support unignore commands.`

It would be ideal if this restriction could be removed. According to #6489, it is not possible to remove the ignore condition by manually bumping `@types/node`. In our case, we are fortunate that the original pull request bumping `@types/node` to v20 can be reopened, but as evidenced by that issue, this isn't a safe assumption to rely on.

### Smallest manifest that reproduces the issue

I have provided a minimal reproduction above.
