### ISSUE TITLE
Package referenced in dotnet-tools.json still updated despite ignore configuration

### ISSUE THREAD

**Issue by AArnott** [dependabot/dependabot-core#8383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Manifest location and content before the Dependabot update

https://github.com/nerdcash/Nerdbank.Cryptocurrencies/blob/bb1ea9da7eab08db4fb1c3840d7ef3fa0e948bf0/.config/dotnet-tools.json

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "powershell": {
      "version": "7.3.9",
      "commands": [
        "pwsh"
      ]
    },
    "dotnet-format": {
      "version": "5.1.250801",
      "commands": [
        "dotnet-format"
      ]
    },
    "dotnet-coverage": {
      "version": "17.9.3",
      "commands": [
        "dotnet-coverage"
      ]
    },
    "nbgv": {
      "version": "3.6.133",
      "commands": [
        "nbgv"
      ]
    }
  }
}
```

### dependabot.yml content

https://github.com/nerdcash/Nerdbank.Cryptocurrencies/blob/bb1ea9da7eab08db4fb1c3840d7ef3fa0e948bf0/.github/dependabot.yml

```yml
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: weekly
  ignore:
  # This package has unlisted versions on nuget.org that are not supported. Avoid them.
  - dependency-name: dotnet-format
    versions: ["6.x", "7.x", "8.x", "9.x"]
- package-ecosystem: cargo
  directory: /src/nerdbank-zcash-rust
  schedule:
    interval: weekly
```

### Updated dependency

dotnet-format from 5.1.250801 to 9.0.456101

### What you expected to see, versus what you actually saw

I expected no updating PR. My dependabot.yml file says specifically to ignore 9.x versions of `dotnet-format` per [the spec documented here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore), and yet this PR was created anyway.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/nerdcash/Nerdbank.Cryptocurrencies/pull/143
