### ISSUE TITLE
Unknown error running dependabot, `No project file or packages.config` in logs

### ISSUE THREAD

**Issue by alexrosenfeld10** [dependabot/dependabot-core#8393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

net7.0

### Manifest location and content before the Dependabot update

solution file at root of repo

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  nuget-jfrog:
    type: nuget-feed
    url: https://mycompany.jfrog.io/artifactory/api/nuget/nuget
    username: ${{ secrets.ORG_JFROG_USERNAME }}
    password: ${{ secrets.ORG_JFROG_ACCESS_TOKEN }}

updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Los_Angeles"
    groups:
      mygroupname:
        patterns:
          - "MyCompany.*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 50
    registries:
      - nuget-jfrog
```

### What you expected to see, versus what you actually saw

Dependabot runs normally

### Images of the diff or a link to the PR, issue, or logs

```
updater | 2023/11/14 17:15:03 INFO <job_749851513> Starting grouped update job for mycompany/my-app
updater | 2023/11/14 17:15:03 INFO <job_749851513> Found 1 group(s).
updater | 2023/11/14 17:15:03 INFO <job_749851513> Starting update group for 'mygroupname'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> No project file or packages.config!
  proxy | 2023/11/14 17:15:03 [058] POST https://sentry.io:443/api/1451818/store/
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/nuget/lib/dependabot/nuget/file_parser.rb:113:in `check_required_files'
  proxy | 2023/11/14 17:15:03 [058] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/common/lib/dependabot/file_parsers/base.rb:18:in `initialize'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:80:in `new'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:80:in `dependency_file_parser'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:41:in `block in compile_all_dependency_changes_for'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:114:in `run_update_for'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:96:in `block in run_grouped_dependency_updates'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `each'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `run_grouped_dependency_updates'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:45:in `perform'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/14 17:15:03 ERROR <job_749851513> bin/update_files.rb:24:in `<main>'
```
