### ISSUE TITLE
Support for bumping git revisions in github actions actions/checkout actions

### ISSUE THREAD

**Issue by alex** [dependabot/dependabot-core#8425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Given an action like:

```
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: "google/wycheproof"
        path: "wycheproof"
        ref: "b063b4aedae951c69df014cd25fa6d69ae9e8cb9"
```

Dependabot should be able to bump the `ref` to keep up with the primary branch.

This would function basically the same as git submodules, but for `actions/checkout` actions.
