### ISSUE TITLE
Dependabot couldn't fetch all your path-based dependencies

### ISSUE THREAD

**Issue by HangJung97** [dependabot/dependabot-core#8428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

Python

### Manifest location and content before the Dependabot update

https://github.com/HangJung97/test_dependabot/blob/main/pyproject.toml

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "pytorch-lightning"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "torchmetrics"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "production"
```

### What you expected to see, versus what you actually saw

I have a git submodule named ASCENT located at the root. I have included it as a package in my `pyproject.toml` like this `ascent = { path = "./ASCENT/", develop = true }`. I expected dependabot to be able to find the `pyproject.toml` in my ASCENT submodule since my path is relative and correct but got this error instead `Dependabot couldn't fetch all your path-based dependencies`. The exact error looks like this:

updater | 2023/11/17 18:56:10 ERROR <job_751387553> Error during file fetching; aborting: The following path based dependencies could not be retrieved: ASCENT/pyproject.toml.

The public repository I created to debug this problem can be found [here](https://github.com/HangJung97/test_dependabot).
