### ISSUE TITLE
Dependabot encountered an unknown error

### ISSUE THREAD

**Issue by amureki** [dependabot/dependabot-core#8449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

3.11

### Manifest location and content before the Dependabot update

`/Pipfile`

### dependabot.yml content

```
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  groups:
    python-dependencies:
      update-types:
        - "minor"
        - "patch"
  versioning-strategy: lockfile-only
  reviewers:
    - herrbenesch
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  groups:
    javascript-dependencies:
      update-types:
        - "minor"
        - "patch"
  versioning-strategy: lockfile-only
  reviewers:
    - SebastianKapunkt
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
    - herrbenesch

```

### What you expected to see, versus what you actually saw

https://gist.github.com/amureki/c9f0fff4a062f94d4abc38872272a613
