### ISSUE TITLE
Dependabot does not support github-actions/reusable-workflows dependencies from monorepo

### ISSUE THREAD

**Issue by alekspog** [dependabot/dependabot-core#8451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions, reusable-workflows

### Manifest location and content before the Dependabot update

I have and example with two reusable workflows storing in the same repository. We use the name and version git tagging pattern to refer to a specific version of a single package: for example, `path-to-workflow1@workflow1/v1.0.0` & `path-to-workflow2@workflow2/v2.0.0`. We refer these reusable workflows in the two separate workflows in the another repository. 

You can find the workflow examples below that reference reusable workflows.

1. https://github.com/alekspog/reusable-workflows-examples/blob/main/.github/workflows/echo.yml

```yaml
name: echo 1

on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: alekspog/reusable-workflows-examples/.github/workflows/echo.yml@echo/v1.0.0
    with:
      text: 1
```

2. https://github.com/alekspog/test-reusable-workflows/blob/main/.github/workflows/summary.yml

```yaml
name: Echo text to job summary

on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: alekspog/reusable-workflows-examples/.github/workflows/summary.yml@summary/v1.0.0
    with:
      text: 'my summary'
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:00"
```

### What you expected to see, versus what you actually saw

- we already have `echo/v1.0.0` and `summary/v1.0.0` tags for echo and summary reusable workflows
- we updated the `summary` reusable workflow and created `summary/v2.0.0` tag for it https://github.com/alekspog/reusable-workflows-examples/releases/tag/summary%2Fv2.0.0

### Expected result

Dependabot resolves version for `summary` workflow to `summary/v2.0.0`

### Actual result

Dependabot resolves version for `summary` workflow to `echo/v1.0.0`.
Every time I update the tag with `summary prefix`, the dependabot still finds only `v1.0.0`. I see in the dependabot logs for every run: `Latest version is 1.0.0`. It seems that dependabot also respects the alphabetical order of the tags and takes the latest semver tag from the tag which is first from the top of alphabetically sorted list of tags.

Other observations:
- We see the same behaviour for our github-actions that are stored in the monorepo.
- We see that the dependabot resolves properly versions for terraform packages storing in monorepo using the same name and version git tagging pattern to refer to a specific version of a single package. It looks like that a specific way of resolving such tags for the specific `github-actions` dependabot package. It could be done the same way as for `terraform` dependabot package to solve the issue.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/alekspog/test-reusable-workflows/pull/1/files

<img width="1107" alt="Screenshot 2023-11-23 at 13 39 38" src="https://github.com/dependabot/dependabot-core/assets/11749744/22329abf-0b85-446a-ab60-ef668b156986">

### Smallest manifest that reproduces the issue

There are reusable workflows for this example.

https://github.com/alekspog/reusable-workflows-examples/blob/main/.github/workflows/echo.yml

```yaml
name: 'Echo text to stdout'

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string
        default: hello

jobs:
  echo-text:
    name: Echo text to stdout
    runs-on: ubuntu-latest
    steps:
      - name: Echo text to stdout
        run: echo ${{ inputs.text }}
```

https://github.com/alekspog/reusable-workflows-examples/blob/main/.github/workflows/summary.yml

```yaml
name: 'Print text to job summary'

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string
        default: hello

jobs:
  echo-text:
    name: Echo text to summary
    runs-on: ubuntu-latest
    steps:
      - name: Output text to summary
        run: echo ${{ inputs.text }} >> $GITHUB_STEP_SUMMARY
```
