### ISSUE TITLE
Only one package is updated in a PR of grouped package version updates

### ISSUE THREAD

**Issue by steven-oriley-talogy** [dependabot/dependabot-core#8475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### dependabot.yml content

```yaml
version: 2
registries:
  nuget-azdo-artifacts:
    type: nuget-feed
    url: https://***/nuget/v3/index.json
    username: ${{username}}
    password: ${{password}}
updates:
- package-ecosystem: nuget
  directory: "/src/"
  registries:
    - nuget-azdo-artifacts
  schedule:
    interval: weekly
    day: sunday
  groups:
    default:
      patterns:
        - "*"
      exclude-patterns:
          - "Microsoft.VisualStudio.Azure.Containers.Tools.Targets"
  open-pull-requests-limit: 10
```

### What you expected to see, versus what you actually saw

The following list of package version bumps are included in the description of the PR created by dependabot:

| Package | From | To |
| --- | --- | --- |
| [Microsoft.AspNetCore.Authentication.JwtBearer](https://github.com/dotnet/aspnetcore) | `7.0.13` | `7.0.14` |
| [Microsoft.AspNetCore.Authentication.OpenIdConnect](https://github.com/dotnet/aspnetcore) | `7.0.13` | `7.0.14` |
| [Microsoft.Extensions.Http](https://github.com/dotnet/runtime) | `7.0.0` | `8.0.0` |
| [Serilog.AspNetCore](https://github.com/serilog/serilog-aspnetcore) | `7.0.0` | `8.0.0` |
| [System.Net.Http.Json](https://github.com/dotnet/runtime) | `7.0.1` | `8.0.0` |

However, only one version bump is actually included in the code changes:

![image](https://github.com/dependabot/dependabot-core/assets/54543848/1e95113e-a6d7-40f0-9888-830ade339dd7)

In the log for the latest dependabot job, we are also seeing a recurring error that may or may not be related to this issue:

```
proxy | 2023/11/28 11:48:06 [306] 401 https://***/nuget/packages/***/versions/3.1.6/content?sourceProtocolVersion=nuget&api-version=7.0-preview
proxy | 2023/11/28 11:48:06 [306] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

### Images of the diff or a link to the PR, issue, or logs

This issue is occurring on private repositories owned by my organization. A dependabot PR was created yesterday (11/27/2023) morning that we were able to successfully merge because it did not have the issue. This PR was created as a result of the following update to dependabot.yml:

```yaml
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authentication.*"
      update-types: ["version-update:semver-major"]
```

However, PR's that were created by dependabot in the afternoon against other repositories where the same change had been merged all experienced the issue where one revision was included in the code changes despite multiple being listed in the PR description.

We have since reverted the changes to dependabot.yml that were merged before seeing this issue, but the revert was not able to fix the problem.
