### ISSUE TITLE
Dependabot will create an empty Pull Request

### ISSUE THREAD

**Issue by shibayan** [dependabot/dependabot-core#8491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

.NET 6.0

### Manifest location and content before the Dependabot update

https://github.com/shibayan/containerapps-acmebot/blob/master/ContainerApps.Acmebot/ContainerApps.Acmebot.csproj

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
```

### What you expected to see, versus what you actually saw

Dependabot reports in the comments that there are updates to three packages, but the pull request actually created is empty with no changes.

At the same time Dependabot reports that there is an update to `Microsoft.Extensions.Http` to 8.0.0, but Dependabot also reports incorrectly because it explicitly specifies a version range.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/shibayan/containerapps-acmebot/pull/69
