### ISSUE TITLE
while config dependabot.yml with registries, dry_run got Parameter 'registries': Expected type T.nilable(T::Array[T.untyped]), got type Hash with value 

### ISSUE THREAD

**Issue by lucemia** [dependabot/dependabot-core#8533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

python

### Package manager version

poetry 

### Language version

python 3.10

### Manifest location and content before the Dependabot update

`/pyproject.toml`

### dependabot.yml content

```
registries:
  python-gcp:
    password: ${{secrets.ARTIFACT_REGISTRY_PASSWD}}
    replaces-base: true
    type: python-index
    url: XXXXXXX
    username: _json_key_base64
updates:
- allow:
  - dependency-type: all
  directory: /
  groups:
    development-dependencies:
      dependency-type: development
      update-types:
      - minor
      - patch
    production-dependencies:
      dependency-type: production
      update-types:
      - minor
      - patch
  insecure-external-code-execution: allow
  open-pull-requests-limit: 10
  package-ecosystem: pip
  registries:
  - python-gcp
  schedule:
    interval: daily
```

### Updated dependency

N/A

### What you expected to see, versus what you actually saw

While I run dry-run in `dependabot-core-dev`

`LOCAL_GITHUB_ACCESS_TOKEN=XXXXX ./bin/dry-run.rb pip XXXX/XXXX--cache=files`

It will raise following error.
```
/usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'registries': Expected type T.nilable(T::Array[T.untyped]), got type Hash with value {:"python-gcp"=>{:password=...username=>"_json_key_base64"}} (TypeError)
Caller: /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:201
Definition: /home/dependabot/common/lib/dependabot/config/file.rb:26
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/configuration.rb:303:in `call_validation_error_handler'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:286:in `report_error'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:204:in `block in validate_call'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/signature.rb:235:in `block in each_args_value_type'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/signature.rb:229:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/signature.rb:229:in `each_args_value_type'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:201:in `validate_call'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
	from /home/dependabot/common/lib/dependabot/config/file.rb:56:in `new'
	from /home/dependabot/common/lib/dependabot/config/file.rb:56:in `parse'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `bind_call'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `validate_call'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
	from ./bin/dry-run.rb:472:in `<main>'
```

### Native package manager behavior

N/A
