### ISSUE TITLE
Grouped dependency updates being assigned to incorrect group

### ISSUE THREAD

**Issue by edmorley** [dependabot/dependabot-core#8558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Cargo

### Package manager version

1.74

### Language version

1.74

### Manifest location and content before the Dependabot update

https://github.com/heroku/languages-github-actions/blob/e280b86033bbe1f1f5a51a87d2dc71e89da09b76/Cargo.toml
https://github.com/heroku/languages-github-actions/blob/e280b86033bbe1f1f5a51a87d2dc71e89da09b76/Cargo.lock

### dependabot.yml content

https://github.com/heroku/languages-github-actions/blob/e280b86033bbe1f1f5a51a87d2dc71e89da09b76/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Our Dependabot config has the `libcnb*` and `libherokubuildpack` packages assigned to a group named `libcnb` and all other minor/patch dependencies assigned to a group named `rust-dependencies`. The `libcnb` group is defined first, so should "win" if a package could fall into either group.

In this PR, the `libcnb*` packages are incorrectly grouped into the `rust-dependencies` group, rather than their own `libcnb` group:
https://github.com/heroku/languages-github-actions/pull/177

Manually triggering a new Dependabot run (via "Insights" -> Dependency graph -> ... etc) didn't fix the PR.

And in fact the PR was then later recreated again with the same issue:
https://github.com/heroku/languages-github-actions/pull/179

This seems to be a recent regression.

It has also affected other repos, for example this PR too:
https://github.com/heroku/buildpacks-go/pull/193

### Images of the diff or a link to the PR, issue, or logs

The initial broken PR was created in this job:
https://github.com/heroku/languages-github-actions/network/updates/757142572

This is a later rebase job, which I was hoping might fix the PR, but didn't:
https://github.com/heroku/languages-github-actions/network/updates/759606224

And then the second broken PR was opened in:
https://github.com/heroku/languages-github-actions/network/updates/759606988

**Comment by jakecoffman** [comment]
I think this might be an issue where the existing grouped pull requests are affecting new runs. In other words it got into a bad state from the previous code. 

If I run a job locally with the Dependabot CLI it seems to produce the correct groups:

```
updater | +------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | libcnb-common ( from 0.16.0 to 0.17.0 ), libcnb-data ( from 0.16.0 to 0.17.0 ), libcnb-package ( from 0.16.0 to 0.17.0 ) |
updater | | created | clap ( from 4.4.8 to 4.4.12 ), ignore ( from 0.4.20 to 0.4.21 ), semver ( from 1.0.20 to 1.0.21 ), serde_json ( from ... |
updater | | created | markdown ( from 1.0.0-alpha.14 to 1.0.0-alpha.16 )                                                                       |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
```

The input I used for this is: 

`dependabot update -f input.yml`

```yml
job:
  package-manager: cargo
  source:
    provider: github
    repo: heroku/languages-github-actions
    directory: "/."
    api-endpoint: https://api.github.com/
    hostname: github.com
    commit: 1ee2143f5925b1cce189ab663bcfa47bb38d6a18
  allowed-updates:
    - dependency-type: direct
      update-type: all
  dependency-groups:
    - name: libcnb
      rules:
        patterns:
          - libcnb*
          - libherokubuildpack
    - name: rust-dependencies
      rules:
        update-types:
          - minor
          - patch
```

If we can get Dependabot to start over in a clean state I think it will create the correct PRs. Merging the PRs will work, or you can manually bump some of the dependencies and it should close the existing PRs.
