### ISSUE TITLE
Dependabot reports an unknown error

### ISSUE THREAD

**Issue by alex** [dependabot/dependabot-core#8588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Manifest location and content before the Dependabot update

https://github.com/pyca/cryptography/tree/main/.github/requirements:

- `.github/requirements/build-requirements.in`
- `.github/requirements/build-requirements.txt`
- `.github/requirements/publish-requirements.in`
- `.github/requirements/publish-requirements.txt`

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 1024

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/cache/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 1024
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/upload-coverage/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 1024
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/fetch-vectors/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 1024

  - package-ecosystem: cargo
    directory: "/src/rust/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/New_York"
    allow:
      # Also update indirect dependencies
      - dependency-type: all
    open-pull-requests-limit: 1024

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/New_York"
    allow:
      # Also update indirect dependencies
      - dependency-type: all
    open-pull-requests-limit: 1024

  - package-ecosystem: pip
    directory: "/.github/requirements/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/New_York"
    allow:
      # Also update indirect dependencies
      - dependency-type: all
    open-pull-requests-limit: 1024
```

### What you expected to see, versus what you actually saw

The logs contain the following error:

```
updater | 2023/12/08 11:26:11 ERROR <job_760013264> Error processing pydantic[email] (RuntimeError)
updater | 2023/12/08 11:26:11 ERROR <job_760013264> No files have changed!
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/python/lib/dependabot/python/file_updater.rb:42:in `updated_dependency_files'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:89:in `generate_dependency_files'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:41:in `perform_job'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/08 11:26:11 ERROR <job_760013264> bin/update_files.rb:24:in `<main>'
```

I expect either no error or a more specific error message.
