### ISSUE TITLE
Dependabot no longer updates NuGet packages in a repository with only a Directory.Packages.props file

### ISSUE THREAD

**Issue by martincostello** [dependabot/dependabot-core#8590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Package manager version

.NET SDK 8.0.100

### Language version

C# 12

### Manifest location and content before the Dependabot update

`Directory.Packages.props`

```xml
<Project>
  <ItemGroup>
    <PackageVersion Include="coverlet.msbuild" Version="6.0.0" />
    <PackageVersion Include="GitHubActionsTestLogger" Version="2.3.3" />
    <PackageVersion Include="JustEat.HttpClientInterception" Version="4.0.0" />
    <PackageVersion Include="MartinCostello.Logging.XUnit" Version="0.3.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="NSubstitute" Version="5.1.0" />
    <PackageVersion Include="ReportGenerator" Version="5.2.0" />
    <PackageVersion Include="Shouldly" Version="4.2.1" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.507" />
    <PackageVersion Include="xunit" Version="2.6.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.4" />
    <PackageVersion Include="Xunit.SkippableFact" Version="1.4.13" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup Condition=" '$(IsTestProject)' == 'true' ">
    <PackageReference Include="coverlet.msbuild" PrivateAssets="All" />
    <PackageReference Include="GitHubActionsTestLogger" PrivateAssets="All" />
    <PackageReference Include="ReportGenerator" PrivateAssets="All" />
  </ItemGroup>
</Project>
```

### dependabot.yml content

```yaml
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
- package-ecosystem: nuget
  directory: "/"
  groups:
    xunit:
      patterns:
        - xunit*
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/src/CHANGE_ME"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
```

### Updated dependency

None.

### What you expected to see, versus what you actually saw

I have a private template repository where various repo boilerplate files to set up a new project (library, an app, whatever) exist. This repository intentionally doesn't contain any `.csproj` files, but does contain a `Directory.Build.props` file with the `PackageVersion` elements for various NuGet packages that are always nearly present in my repositories, such as the .NET test SDK, xunit, etc.

Previously, Dependabot would update the package versions in the file:

![image](https://github.com/dependabot/dependabot-core/assets/1439341/0320e9ee-e179-421d-84d0-b78aa6eb49b6)

Now it errors:

```text
Dependabot couldn't find a <anything>.(cs|vb|fs)proj
Dependabot requires a .(cs|vb|fs)proj to evaluate your .NET dependencies. It had expected to find one at the path: /<anything>.(cs|vb|fs)proj.
```

Ideally, Dependabot would still be able to process the package versions without requiring any project files that reference them to be present.
