### ISSUE TITLE
Dependabot fails to fully update the Pipenv.lock file

### ISSUE THREAD

**Issue by josejulio** [dependabot/dependabot-core#8592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Language version

3.9

### Manifest location and content before the Dependabot update

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
python-dotenv = "*"
python-decouple = "*"
requests = ">=2.31.0"
rapidfuzz = "*"
jsonpickle = "*"
app-common-python = "==0.2.6"
boto3 = ">=1.24.89"
logstash-formatter = ">=0.5.17"
prometheus-client = ">=0.14.1"
pyjwt = ">=2.7.0"
watchtower = ">=3.0.0"

[dev-packages]
pyopenssl = ">=23.2.0"
pytest = "*"
black = ">=23.9.1"

[api-packages]
rasa = "==3.6.13"

[action-packages]
rasa-sdk = "==3.6.2"

[requires]
python_version = "3.9"
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

### Updated dependency

This shows: Bump boto3 from 1.29.6 to 1.33.11
but having the same issue with all the dependency upgrades

### What you expected to see, versus what you actually saw

After the update, if running `pipenv verify` I expected to see:
> Pipfile.lock is up-to-date.

Instead I see:
> Pipfile.lock is out-of-date. Run $ pipenv lock to update.

### Native package manager behavior

Contents after running `pipenv lock` on top of the PR

https://gist.github.com/josejulio/6914094fe1ff594d24321c21c50dc055

### Images of the diff or a link to the PR, issue, or logs

https://github.com/RedHatInsights/astro-virtual-assistant/pull/195

```
diff --git a/Pipfile.lock b/Pipfile.lock
index 5cdb9f6..f305f44 100644
--- a/Pipfile.lock
+++ b/Pipfile.lock
@@ -1,7 +1,7 @@
 {
     "_meta": {
         "hash": {
-            "sha256": "6b277c1e3de7e880b1a10b43110d879d52a64cfea64164f69b7051baeb55eeb8"
+            "sha256": "231daee5d1aa6ad0da4dbb44fa29a4fa16e3d27b75cb3499c73ad892fded6d5d"
         },
         "pipfile-spec": 6,
         "requires": {
@@ -3583,20 +3583,20 @@
         },
         "boto3": {
             "hashes": [
-                "sha256:d1d0d979a70bf9b0b13ae3b017f8523708ad953f62d16f39a602d67ee9b25554",
-                "sha256:f4d19e01d176c3a5a05e4af733185ff1891b08a3c38d4a439800fa132aa6e9be"
+                "sha256:620f1eb3e18e780be58383b4a4e10db003d2314131190514153996032c8d932d",
+                "sha256:8d54fa3a9290020f9a7f488f9cbe821029de0af05a677751b12973a5f726a5e2"
             ],
             "index": "pypi",
             "markers": "python_version >= '3.7'",
-            "version": "==1.29.6"
+            "version": "==1.33.11"
         },
         "botocore": {
             "hashes": [
-                "sha256:4454f967a4d1a01e3e6205c070455bc4e8fd53b5b0753221581ae679c55a9dfd",
-                "sha256:ecec876103783b5efe6099762dda60c2af67e45f7c0ab4568e8265d11c6c449b"
+                "sha256:b14b328f902d120de0a09eaa657a9a701c0ceeb711197c2f01ef0523f855086c",
+                "sha256:b46227eb3fa9cfdc8f5a83920ef347e67adea8095830ed265a3373b13b54421f"
             ],
             "markers": "python_version >= '3.7'",
-            "version": "==1.32.6"
+            "version": "==1.33.11"
         },
         "certifi": {
             "hashes": [
@@ -3885,11 +3885,11 @@
         },
         "s3transfer": {
             "hashes": [
-                "sha256:10d6923c6359175f264811ef4bf6161a3156ce8e350e705396a7557d6293c33a",
-                "sha256:fd3889a66f5fe17299fe75b82eae6cf722554edca744ca5d5fe308b104883d2e"
+                "sha256:368ac6876a9e9ed91f6bc86581e319be08188dc60d50e0d56308ed5765446283",
+                "sha256:c9e56cbe88b28d8e197cf841f1f0c130f246595e77ae5b5a05b69fe7cb83de76"
             ],
             "markers": "python_version >= '3.7'",
-            "version": "==0.7.0"
+            "version": "==0.8.2"
         },
         "six": {
             "hashes": [
```
