### ISSUE TITLE
Updating dotnet-tools.json results in broken formatting

### ISSUE THREAD

**Issue by JoshWoodArup** [dependabot/dependabot-core#8608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Manifest location and content before the Dependabot update

In .config/dotnet-tools.json
``` json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "csharpier": {
      "version": "0.26.5",
      "commands": ["dotnet-csharpier"]
    },
    "dotnet-ef": {
      "version": "8.0.0",
      "commands": ["dotnet-ef"]
    }
  }
}
```
[Example here](https://github.com/JoshWoodArup/dependabot-issue/blob/main/.config/dotnet-tools.json)

### dependabot.yml content

``` yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```
[Example here](https://github.com/JoshWoodArup/dependabot-issue/blob/main/.github/dependabot.yml)

### Updated dependency

In this case, the dependency is CSharpier, however I have observed this problem with other dependencies

### What you expected to see, versus what you actually saw

The resulting json is:
``` json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "csharpier": {
      "version": "0.26.6",
      "commands": [
        "dotnet-csharpier"
      ]
    },
    "dotnet-ef": {
      "version": "8.0.0"
      "commands": [
        "dotnet-ef"
      ]
    }
  }
}
```
Notice the missing comma after `"version": "8.0.0"`

What I would expect is the following:
``` json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "csharpier": {
      "version": "0.26.6",
      "commands": [
        "dotnet-csharpier"
      ]
    },
    "dotnet-ef": {
      "version": "8.0.0",
      "commands": [
        "dotnet-ef"
      ]
    }
  }
}
```

### Native package manager behavior

Using the command `dotnet tool update "csharpier" --tool-manifest ".config/dotnet-tools.json"`
The resulting dotnet-tools.json is:
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "csharpier": {
      "version": "0.26.6",
      "commands": [
        "dotnet-csharpier"
      ]
    },
    "dotnet-ef": {
      "version": "8.0.0",
      "commands": [
        "dotnet-ef"
      ]
    }
  }
}
```

### Images of the diff or a link to the PR, issue, or logs

The PR can be found [here](https://github.com/JoshWoodArup/dependabot-issue/pull/1)
