### ISSUE TITLE
Dependabot force-pushes an existing update PR and also creates a new one for the same update

### ISSUE THREAD

**Issue by davidstosik** [dependabot/dependabot-core#8652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

bundler 2.4.22

### Language version

ruby 3.3.0.rc1

### Updated dependency

Here's a partial YAML file
```yaml
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "UTC"
    reviewers:
      - Shopify/rails
    labels:
      - "Gem upgrades"
    open-pull-requests-limit: 100
    insecure-external-code-execution: allow
    registries: '*'
    ignore:
    - dependency-name: "whatever" # some ignores, unrelated to the gems I've seen the issue with
```

## What happens

On the same day, Dependabot:
- created a PR titled "Bump debug from `dea10b5` to `557233a`" (11:23 AM GMT+9)
- force-pushed 3 branches for PRs updating the debug gem
  - @dependabot force-pushed the `dependabot/bundler/debug-cbd0f71` branch from 8951669 to 8c62606 (time: 6:23 PM GMT+9)
      (original PR title: "Bump debug from `dea10b5` to `cbd0f71`")
  - @dependabot force-pushed the `dependabot/bundler/debug-2bdb8f8` branch from 7210076 to 570549b (time: 6:25 PM GMT+9)
      (original PR title: "Bump debug from `dea10b5` to `2bdb8f8`")
  - @dependabot force-pushed the `dependabot/bundler/debug-d4feeae` branch from 437d318 to 875d313 (time: 6:26 PM GMT+9)
      (original PR title: "Bump debug from `dea10b5` to `d4feeae`")

Even though one of those earlier PRs had comments on it, none had additional commits.

<details><summary>After that happened, all 4 PRs were showing the exact same diff, with Gemfile.lock pointing to the same revision.</summary>

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 5f3eb9a5ea95..13e0a60263a7 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -312,10 +312,10 @@ GIT

 GIT
   remote: https://github.com/ruby/debug.git
-  revision: dea10b50f2ca65ab3401ef28961b960cd087f98f
+  revision: 557233a90ff623c7dd00384a08471e5a5514f688
   specs:
-    debug (1.8.0)
-      irb (>= 1.5.0)
+    debug (1.9.0)
+      irb (~> 1.10)
       reline (>= 0.3.8)

 PATH
```

</details>

## What I expected to see

Well, 3 open PRs updating the same gem should not co-exist in the first place, but when Dependabot created a new PR, I would expect it to close the outdated ones, not to force-push the same change to all of them.

---

Please note that this has been observed with multiple gems, here are 2 more examples:
- google-cloud-ai_platform-v1
  - Bump google-cloud-ai_platform-v1 from 0.30.0 to 0.35.0
  - Bump google-cloud-ai_platform-v1 from 0.30.0 to 0.34.0
  - Bump google-cloud-ai_platform-v1 from 0.30.0 to 0.33.0
- aws-sdk-sns
  - Bump aws-sdk-sns from 1.67.0 to 1.70.0
  - Bump aws-sdk-sns from 1.67.0 to 1.68.0

All the PRs above were still open yesterday until I closed the old ones.
