### ISSUE TITLE
Dependabot fails to determine the latest GHA workflow version

### ISSUE THREAD

**Issue by vy** [dependabot/dependabot-core#8654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### dependabot.yml content

```
version: 2

# Add Maven Central explicitly to work around:
#   https://github.com/dependabot/dependabot-core/issues/8329
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2

updates:

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries:
      - maven-central
    ignore:
      # Keep `scala-library` baseline
      - dependency-name: "org.scala-lang:scala-library"
        update-types: ["version-update:semver-major"]
      # Keep `scala-reflect` baseline
      - dependency-name: "org.scala-lang:scala-reflect"
        update-types: ["version-update:semver-major"]
      # Keep Mockito baseline (5+ requires Java 11)
      - dependency-name: "org.mockito.kotlin:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.mockito:*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
```

### What you expected to see, versus what you actually saw

Given [this GHA workflow](/apache/logging-log4j-scala/blob/0b4e93062e2321f3580848fd5d1cfb3b06e988cb/.github/workflows/build.yaml) containing following lines:

```
jobs:

  build:
    if: github.actor != 'dependabot[bot]'
    uses: apache/logging-parent/.github/workflows/build-reusable.yaml@e45457c683302242be5e8e7c3c33edf8f0e0ec0e # 10.4.0
```

`dependabot` is not able detect the latest `apache/logging-parent` version: https://github.com/apache/logging-log4j-scala/network/updates/765025652

```
updater | 2023/12/21 11:01:56 INFO <job_765025652> Latest version is 10.4.0
updater | 2023/12/21 11:01:56 INFO <job_765025652> No update needed for apache/logging-parent 10.4.0
updater | 2023/12/21 11:01:56 INFO <job_765025652> Finished job processing
```

Though, prior to this run, `rel/10.5.0` tag was created and [a GitHub Release based on the tag](/apache/logging-parent/releases/tag/rel%2F10.5.0) was cut.

### Smallest manifest that reproduces the issue

`.github/dependabot.yaml`:
```
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
```

`.github/workflows/build.yaml`:
```
name: build
jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    uses: apache/logging-parent/.github/workflows/build-reusable.yaml@e45457c683302242be5e8e7c3c33edf8f0e0ec0e # 10.4.0
```
