### ISSUE TITLE
npm packages not grouped

### ISSUE THREAD

**Issue by CGarces** [dependabot/dependabot-core#8674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

8.19.4

### Language version

node 16.20

### Manifest location and content before the Dependabot update

```json
{
  "name": "web-cartera",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:stats": "ng build --stats-json",
    "analyze": "webpack-bundle-analyzer dist/web_cartera/stats.json",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.2.4",
    "@angular/common": "^16.2.4",
    "@angular/compiler": "^16.2.4",
    "@angular/core": "^16.2.4",
    "@angular/platform-browser": "^16.2.4",
    "@angular/platform-browser-dynamic": "^16.2.4",
    "@angular/router": "^16.2.4",
    "@types/google-one-tap": "^1.2.2",
    "rxjs": "^7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.1",
    "@angular-eslint/builder": "^16.1.2",
    "@angular-eslint/eslint-plugin": "^16.1.2",
    "@angular-eslint/eslint-plugin-template": "^16.1.2",
    "@angular-eslint/schematics": "^16.1.2",
    "@angular-eslint/template-parser": "^16.1.2",
    "@angular/cli": "^16.2.1",
    "@angular/compiler-cli": "^16.2.4",
    "@typescript-eslint/eslint-plugin": "^6.16.0",
    "@typescript-eslint/parser": "^6.16.0",
    "eslint": "^8.39.0",
    "typescript": "^5.1",
    "webpack-bundle-analyzer": "^4.9.1"
  }
}
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
          - "@angular-devkit/*"
          - "jest-preset-angular"
          - "typescript"
          - "zone.js"
        update-types:
          - "minor"
          - "patch"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"

```

### Updated dependency

Angular from 16.x to 17.x

### What you expected to see, versus what you actually saw

I need to group al angular dependencies in order to allow major upgrades
But when I ran the dependecybot I get 5 separate PR

- Bump @angular/router from 16.2.12 to 17.0.8
- Bump @angular/compiler-cli from 16.2.12 to 17.0.8
- Bump @angular/animations from 16.2.12 to 17.0.8 
- Bump @angular/platform-browser-dynamic from 16.2.12 to 17.0.8 
- Bump @angular-devkit/build-angular from 16.2.11 to 17.0.8
