### ISSUE TITLE
Ignore unstable semver versions

### ISSUE THREAD

**Issue by weizhangfd** [dependabot/dependabot-core#8677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently Dependabot seems [only able to ignore major, minor and patch version](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore). Would it be possible to ignore unstable versions, built by adding extensions to the semver versions, such as prereleases?

**Comment by OJFord** [comment]
Concretely, dependabot will suggest an update like:

> Bump tauri-build from 1.2.1 to 2.0.0-alpha.4

but there's not presently a way to say no I don't want that until `2.0.0` is released, but do give me `1.5.4`.

**Comment by ctufekci** [comment]
Is there any decision about this improvement in the future ?

**Comment by dossy** [comment]
Dependabot tried to [bump our golang from 1.25.5 to 1.26rc2](https://github.com/amacneil/dbmate/pull/733).

```yaml
---
updated-dependencies:
- dependency-name: golang
  dependency-version: 1.26rc2
  dependency-type: direct:production
...
```

Tried to prevent this by using this `.github/dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: golang
        versions: ["*rc*"]
```

but, get the following error:

> Dependabot encountered the following error when parsing your `.github/dependabot.yml`:
>
> ```
> The property '#/updates/0/ignore/0/versions' includes invalid version requirements for a docker ignore condition
> ```
>
> Please update the config file to conform with Dependabot's specification.

How do we prevent this in the future?

**Comment by fabiendelpierre** [comment]
Just encountered what seems to be the same issue. 

As an example, I invoke the sourcemeta/jsonschema action like so:

```
- name: Install the JSON Schema CLI
  uses: sourcemeta/jsonschema@b52f6df7e9ec042d6789224bfa07eeaec44fd15b # v16.0.0
```

Dependabot keeps harassing me to update the commit hash above whenever a new commit in that repo is tagged as "continuous", even though the v16.0.0 tag isn't being changed, obviously. This is forcing me to consider ignoring updates to this action altogether, which I don't want to do, but Dependabot's constant pestering is annoying. It would be an easy fix if `updates/0/ignore/0/versions` accepted non-semver values.

I would like to have this config:

```yaml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "sourcemeta/jsonschema"
        versions:
          - "continuous" # ignore updates when tagged as "continuous" in the upstream repo
    commit-message:
      prefix: deps
    schedule:
      interval: weekly
```

I would also settle for a way to ignore non-semver tags and/or untagged commit hashes that are newer than the one I'm pinned to.
