### ISSUE TITLE
Python's grouped configuration does nothing

### ISSUE THREAD

**Issue by kirilllzaitsev** [dependabot/dependabot-core#8683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### dependabot.yml content
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 15
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
```

### What you expected to see, versus what you actually saw

The packages with minor/patch updates should be grouped in a single PR.
What I saw was a single PR per package:
![image](https://github.com/dependabot/dependabot-core/assets/44346535/8f172e33-7b85-4c3f-a51c-ab86bb18889d)
Created at the same time as others, there is a PR that should have done the job, yet it includes only one package update (0.6.1->0.6.3):
![image](https://github.com/dependabot/dependabot-core/assets/44346535/ffa4dd6a-bb2e-4d21-bb8f-1a10a9e24eb7)
