### ISSUE TITLE
Allow ignoring dependency in group where major version is zero

### ISSUE THREAD

**Issue by garryod** [dependabot/dependabot-core#8685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Often times we make use of dependencies which are still in the 'initial development' stage, [section 4 of the semver spec](https://semver.org/#spec-item-4) specifies that these should be given a major version of zero (i.e. `0.y.z`). As such packages are allowed to break their public API at any point it would be useful to be able to filter these out of groups. E.g.:

```yaml
- package-ecosystem: caargo
  groups:
    minor:
      update-types:
        - minor
        - patch
      exclude-update-types:
        - initial-development
```

**Comment by OJFord** [comment]
IMO this is a bug: `0.1.x` -> `0.2.y` should be treated as *major*, not minor.

**Comment by Amund211** [comment]
I still want this. Currently resorting to totally ignoring all 0.y.z versions to not get any potentially breaking changes in my "patch or minor" group. This means having to manually keep 0.y.z dependencies up to date.

I would love to be able to still get (separate) PRs for these updates.

**Comment by caugner** [comment]
How about introducing a `versioning-policy` option with two values:

| `versioning-policy:`   | 0.1.0 → 0.2.0 | 0.0.1 → 0.0.2 |
|------------------------|----------------|----------------|
| `dependabot` (default) | minor | patch |
| `semver`               | **major** | **major** |

This would allow users to opt-in:

```patch
 version: 2
 updates:
   - package-ecosystem: npm
     directory: /
     schedule:
       interval: daily
+    versioning-policy: semver
     groups:
       npm-prod:
         dependency-type: production
         update-types:
           - minor
           - patch
       npm-dev:
         dependency-type: development
         update-types:
           - minor
           - patch
```

Alternatively, this option could be called `semantic-versioning` with two values `relaxed` (default) and `strict`.

Note: For MDN's use case, it would be important that this is reflected in the `update-type` output of the [dependabot/fetch-metadata](https://github.com/dependabot/fetch-metadata) action (see [this GitHub code search](https://github.com/search?q=org%3Amdn+%2F%5C.update-type%2F+path%3A.github%2Fworkflows&type=code) for how we're using this output).

(cc @carlincherry)

**Comment by caugner** [comment]
I just found that this was [recently implemented for Cargo dependencies](https://github.com/dependabot/dependabot-core/pull/13349) in October 2025:

https://github.com/dependabot/dependabot-core/blob/e37c650f4342bda3c1698b6c1091d555e0fb2385/cargo/lib/dependabot/cargo/version.rb#L47-L65

Edit: But it does not seem to work as expected, see [this very recent Dependabot commit](https://github.com/mdn/rari/pull/513/commits/a2809ebc05eccf480e38fe4ad0f7a037b75d538c) that has:

```
---
updated-dependencies:
- dependency-name: memoize
  dependency-version: 0.6.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
...
```
