### ISSUE TITLE
GitHub Actions updater uses LF newline for modified lines even if file uses CRLF

### ISSUE THREAD

**Issue by jakebailey** [dependabot/dependabot-core#8693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

GitHub actions

### Manifest location and content before the Dependabot update

https://github.com/microsoft/TypeScript/blob/main/.github/workflows/nightly.yaml

### dependabot.yml content

https://github.com/microsoft/TypeScript/blob/main/.github/dependabot.yml

```yaml
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
```

### Updated dependency

From:

```
actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
```

To:

```
actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
```

### What you expected to see, versus what you actually saw

When dependabot updates the yaml file, it should use the line endings already used in the file. However, it appears to always use LF line endings on the lines it modifies. This leads to mixed line ending files, which is bad. In the TypeScript repo, this manifests as a CI failure due to the file not being formatted.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/microsoft/TypeScript/pull/56870 is an example of a failing PR.

[microsoft/TypeScript@`d9cabbf` (#56870)](https://github.com/microsoft/TypeScript/pull/56870/commits/d9cabbf055249df15d171b5b488e9a23466e742c) is the commit, but doesn't show the difference.

Locally, I can run a script which splits the lines on just `\n`. On main, the lines changed for one of these files looks like:

```
  '    steps:\r',
  '      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1\r',
  '      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0\r',
  '        with:\r',
  '          # Use NODE_AUTH_TOKEN environment variable to authenticate to this registry.\r',
  '          registry-url: https://registry.npmjs.org/\r',
```

But after:

```
  '    steps:\r',
  '      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1\r',
  '      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1',
  '        with:\r',
  '          # Use NODE_AUTH_TOKEN environment variable to authenticate to this registry.\r',
  '          registry-url: https://registry.npmjs.org/\r',
```

Note the missing `\r` on the updated line.

A workaround is to not use CRLF

**Comment by aaron-kruse** [comment]
This sounds like it's related to another issue:
- #8642

**Comment by jakebailey** [comment]
It's not fixed, no :(

**Comment by yurikuzn** [comment]
I think *.gitattributes* should be honored. Dependabot overrides new lines in *package.json*, then, after I fetch the changes, the local git automatically modifies it back, because of eol=crlf in gitattributes.

**Comment by jakebailey** [comment]
I don't even think that's required. Just look at the existing line endings in a file and use them.

**Comment by fbienz** [comment]
I'm adding to this, since the new gradle wrapper updates change the line endings of `gradlew.bat` to `LF`. From what I've read about batch files, this can cause bugs in those scripts.

Correction: This only happened in Repositories where we had the following gitattributes file:
```
# Normalize checked-in files to LF, force checkout as LF
* text=auto eol=lf

# These are explicitly windows files and should use crlf
*.bat text eol=crlf
```

**Comment by Thunderforge** [comment]
Adding on to the report from @fbienz on Gradle wrapper, running `./gradlew init` on a new project to set up Gradle generates this `.gitattributes` file:

```
#
# https://help.github.com/articles/dealing-with-line-endings/
#
# Linux start script should use lf
/gradlew        text eol=lf

# These are Windows script files and should use crlf
*.bat           text eol=crlf

# Binary files should be left untouched
*.jar           binary

```

With the current version of Dependabot, when it upgrades Gradle, it ignores the `crlf` line endings for `gradlew.bat`.

**Comment by koppor** [comment]
> I'm adding to this, since the new gradle wrapper updates change the line endings of `gradlew.bat` to `LF`. F

As far as I understand, its the other way round: The blob in git is set to `CRLF` by dependabot.

| Commit | Line ending | PR |
  |---|---|---|
  | [`2e90231`](https://github.com/JabRef/jabref/commit/2e9023191e90e8139b7f59ce034e314520ea7740) parent of bump | LF | — |
  | [`197166a`](https://github.com/JabRef/jabref/commit/197166a8cd11e43a1423ad7c37a12bc1f10630d0) Bump gradle-wrapper 9.5.1→9.6.0  (dependabot) | **CRLF** | [#16012](https://github.com/JabRef/jabref/pull/16012) |
  | [`894bfbd`](https://github.com/JabRef/jabref/commit/894bfbdf531bbe8d4f2e6fa7835206e4ddc69b34) Fix CRLF — current HEAD | LF |   [#16019](https://github.com/JabRef/jabref/pull/16019) |

**Comment by fbienz** [comment]
> As far as I understand, its the other way round: The blob in git is set to `CRLF` by dependabot.

My apologies, it seems I mixed up the before and after. After checking again, the file had the correct line ending. I incorrectly assumed git fixes that on commit.

I also checked a few other repositories and found one, where only `lf` was set in gitattributes. There the line endings were also changed to `CRLF`. It's correct insofar, that the gittatributes is missing a part.

**Comment by cfraenkel** [comment]
We're encountering this issue too on PRs where dependabot touches the gradlew.bat. The blob in the repo is commited with CRLF while we expect LF in the blob. Since we check out with `core.autocrlf=true` (windows) or `core.autocrlf=input` (linux) this leaves the workspace both on windows and linux dirty - even in github action runners with the default checkout action. 
Is dependabot maybe not specifying `core.autocrlf=input` ?

**Comment by Mahoney** [comment]
Has anyone got a decent workaround, other than not using CRLF or not letting dependabot upgrade Gradle, since this does not seem to be a priority?

It's driving me nuts, every time dependabot upgrades gradle and I pull, gradlew.bat is marked as changed but it is impossible to revert it locally. Since my main branch is protected that means new branch, commit, PR - frankly it'd be easier just to take responsibility for upgrading gradle myself, at least then it would happen when I was ready for it rather than being forced into it.

**Comment by Mahoney** [comment]
FWIW I am experimenting with this GitHub action. Not seen it work yet, will update as and when it is proven.

```yaml
name: Normalize Dependabot line endings
on:
  pull_request:

permissions:
  contents: write

concurrency:
  group: line-endings-pr-${{ github.event.pull_request.number }}

jobs:
  normalize:
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ your_service_app_client_id_here }}
          private-key: ${{ secrets.SERVICE_APP_PRIVATE_KEY }}

      # Push with the App token so the corrective commit re-triggers the
      # PR's other checks (the default GITHUB_TOKEN would not).
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Renormalize line endings to match .gitattributes
        shell: bash
        run: |
          git add --renormalize .
          if git diff --cached --quiet; then
            echo "Nothing to renormalize."
            exit 0
          fi
          git diff --cached --name-only
          git config user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config user.email '${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          # Fold the fix into Dependabot's commit so the PR stays single-commit.
          git commit --amend --no-edit
          git push --force-with-lease
```
