### ISSUE TITLE
honor `nuget-feed` sources from `dependabot.yml`

### ISSUE THREAD

**Issue by brettfo** [dependabot/dependabot-core#8721]
The NuGet updater doesn't consider feed sources from `dependabot.yml` which means if no `NuGet.config` is present, it always falls back to querying `api.nuget.org` which might not be the desired behavior.

E.g., consider this `dependabot.yml` snippet:

``` yaml
version: 2
registries:
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/ExampleOrganization/index.json
    username: some-user
    password: ${{secrets.NUGET_SECRET_GITHUB}}
# ...
```

In this case if no `NuGet.config` file is present, the GitHub feed should still be used.

These custom feeds should also be passed to the C# tool.  Probably the easiest/cleanest way to do this is to modify the file `~/.nuget/NuGet/NuGet.Config` so that the real NuGet and dotnet tools can use it.
