### ISSUE TITLE
Gradle does not find GH packages library with GITHUB_TOKEN

### ISSUE THREAD

**Issue by mindhaq** [dependabot/dependabot-core#8724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

8.4

### Language version

Kotlin 1.9.20

### dependabot.yml content

version: 2
registries:
  GitHubPackages-rr-common:
    type: maven-repository
    url: https://maven.pkg.github.com/ACCOUNT/rr-common
    username: ACCOUNT
    password: ${{secrets.BUILD_TOKEN}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[Gradle]"

### What you expected to see, versus what you actually saw

My problem is in a kotlin/gradle based private project, which uses a package in another repository of the same pro account. On normal pull requests, building the project works as expected. On PRs from dependabot, gradle cannot find the dependency.

Extract from workflow file:

```yml
name: Build and deploy
on: push
env:
  GITHUB_USERNAME: "ACCOUNT"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: ./.java-version

      - name: Compile
        run: ./gradlew compileKotlin
```

Extract from `build.gradle.kts`:

```kotlin
val githubUsername = System.getenv("GITHUB_USERNAME")
val githubToken = System.getenv("GITHUB_TOKEN")

repositories {
    mavenCentral()
    maven {
        name = "GitHubPackages-rr-common"
        url = uri("https://maven.pkg.github.com/ACCOUNT/rr-common")
        credentials {
            username = githubUsername
            password = githubToken
        }
    }
}

plugins {
    kotlin("jvm")
}

dependencies {
      implementation("de.ACCOUNT:rr-common:2.0.1")
}
```

The compile step fails on PRs from dependabot with the following error, compared to normal PRs which run just fine:

```
> Task :compileKotlin FAILED
FAILURE: Build failed with an exception.

3 actionable tasks: 3 executed
* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find de.ACCOUNT:rr-common:2.0.1.
     Required by:
         project :
```

What do I need to do to make this work?
