### ISSUE TITLE
Update Terraform version at `required_version`

### ISSUE THREAD

**Issue by jfagoagas** [dependabot/dependabot-core#8725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Terraform

### Package manager version

Terraform

### Language version

Terraform

### Manifest location and content before the Dependabot update

Any Terraform file with the following block:
```terraform
terraform {
  required_providers {
    aws = {
      version = "~> 2.13.0"
    }
    random = {
      version = ">= 2.1.2"
    }
  }

  required_version = "~> 0.12.29"
}
```

https://developer.hashicorp.com/terraform/tutorials/configuration-language/versions

### dependabot.yml content

Default `dependabot.yml` to update Terraform.

```yaml
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
```

### Updated dependency

Main Terraform version.

### What you expected to see, versus what you actually saw

Actually, `dependabot` does not update the Terraform version at `required_version`.

Maybe this is an expected behaviour, if not I can give it a go and try to add the code to do it.
