### ISSUE TITLE
npm_and_yarn: git lfs is not used while commiting the update back

### ISSUE THREAD

**Issue by manquer** [dependabot/dependabot-core#8734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

yarn-3.2.3

### Language version

node-20

### Manifest location and content before the Dependabot update

/package.json

### dependabot.yml content

```yml
#file: noinspection YAMLSchemaValidation
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

```

### Updated dependency

Applicable to all PRs with lfs enabled

### What you expected to see, versus what you actually saw

When git lfs is enabled on the yarn 2/3 cache folder ( default ./.yarn/cache) Dependabot correctly pulls the lfs objects and does the check however when it commits back the dependency zip file is pushed as binary and not as a LFS pointer.

![image](https://github.com/dependabot/dependabot-core/assets/3044333/21a9b274-5161-43d5-bc81-a59d05e078cd)

This bypassing of my simple .gitattributes setup

```
*.zip filter=lfs diff=lfs merge=lfs -tex
```
then creates errors in further git operations once the branch is checked out locally. 
```
Encountered 1 file that should have been a pointer, but wasn't
```

### Images of the diff or a link to the PR, issue, or logs

Related PR for the feature here https://github.com/dependabot/dependabot-core/issues/1297 
Here is a link to a log dump from a run https://gist.github.com/manquer/70584c915495290a1b801419ed6165fc
