### ISSUE TITLE
No diff between `dependencies` and `optional-dependencies` for `pyproject.toml`

### ISSUE THREAD

**Issue by superlevure** [dependabot/dependabot-core#8760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

23.3

### Language version

Python 3.10

### Manifest location and content before the Dependabot update

`app/pyproject.toml`:

```toml
[project]
# [...]
dependencies = ["my-private-prod-dep==1.2.3"]

[project.optional-dependencies]
dev = [
    "flake8==7.0.0",
]
```

### dependabot.yml content

```yaml
# [...]
    commit-message:
      prefix: build
      prefix-development: build(deps-dev)
# [...]
```

### Updated dependency

`my-private-prod-dep==1.2.3`

### What you expected to see, versus what you actually saw

I expect the dependency `my-private-prod-dep` to be recognized as a production dependency but Dependabot flags it as a dev one. 

We recently switched from `setup.py` to `pyproject.toml` and this issue appeared 

Looking at https://github.com/dependabot/dependabot-core/blob/main/python/helpers/lib/parser.py#L54 it seems the parser doesn't make a difference between dependencies from `project_toml['dependencies']` and dependencies from `project_toml['optional-dependencies']`
