### ISSUE TITLE
Binary target for private Swift dependency cannot be downloaded from GitHub Package Registry

### ISSUE THREAD

**Issue by MattSkala** [dependabot/dependabot-core#8780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Swift

### Package manager version

5.5

### Manifest location and content before the Dependabot update

iOS project /Packages/FitifyCore/Package.swift
```
// swift-tools-version: 5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "FitifyCore",
    platforms: [ .iOS(.v15)],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "FitifyCore",
            targets: ["FitifyCore"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/Fitify/fitify-android", .exact("0.19.0")),
    ],
    targets: [
        ...
    ]
)
```

private dependency /Package.swift
```
// swift-tools-version:5.3
import PackageDescription

// BEGIN KMMBRIDGE VARIABLES BLOCK (do not edit)
let remoteKotlinUrl = "https://maven.pkg.github.com/Fitify/fitify-android/fitify-android/fitify-model-kmmbridge/0.23.0/fitify-model-kmmbridge-0.23.0.zip"
let remoteKotlinChecksum = "393e3debf7c69036dc779f7340ac3f910c4488b47aeb710fc02de7211ec7a777"
let packageName = "FitifyModel"
// END KMMBRIDGE BLOCK

let package = Package(
    name: packageName,
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: packageName,
            targets: [packageName]
        ),
    ],
    targets: [
        .binaryTarget(
            name: packageName,
            url: remoteKotlinUrl,
            checksum: remoteKotlinChecksum
        )
        ,
    ]
)
```

### dependabot.yml content

```
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GH_KMMBRIDGE_PAT }}
updates:
  - package-ecosystem: "swift"
    directory: "/Packages/FitifyCore"
    schedule:
      interval: "daily"
    registries:
      - github
```

### What you expected to see, versus what you actually saw

Dependabot should find the latest version of the private dependency and create a PR with version bump in Package.swift and Package.resolved.

However, Dependabot clones the private repository, but then fails to download the binary target specified in Package.swift. There seems to be no way to specify authentication for maven.pkg.github.com.

`
error: failed downloading 'https://maven.pkg.github.com/Fitify/fitify-android/fitify-android/fitify-model-kmmbridge/0.19.0/fitify-model-kmmbridge-0.19.0.zip' which is required by binary target 'FitifyModel': badResponseStatusCode(403)
`
