### ISSUE TITLE
dependabot gets error when asking to rebase branch

### ISSUE THREAD

**Issue by trashhalo** [dependabot/dependabot-core#8805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

hex

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  hex-organization-oban:
    type: hex-repository
    repo: oban
    url: https://getoban.pro/repo
    auth-key: ${{ secrets.OBAN_LICENSE_KEY }}
    public-key-fingerprint: ${{ secrets.OBAN_KEY_FINGERPRINT }}
updates:
  - package-ecosystem: "mix" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    registries:
      - hex-organization-oban
    insecure-external-code-execution: allow
```

### Updated dependency

Bump telepoison from 1.3.0 to 1.3.1 

### What you expected to see, versus what you actually saw

it rebases the pr when asked
