### ISSUE TITLE
Dependabot downgrades instead of stated upgrade (related to double tagging?)

### ISSUE THREAD

**Issue by dtrudg** [dependabot/dependabot-core#8847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Go

### Language version

1.21.6

### Manifest location and content before the Dependabot update

https://github.com/sylabs/singularity/blob/637e3eeeaf0265f11814006f271cc00c33532e64/go.mod

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: main
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: release-4.1
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: release-4.0
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: release-3.11
```

### Updated dependency

github.com/opencontainers/image-spec from 1.1.0-rc5 to 1.1.0-rc.6

### What you expected to see, versus what you actually saw

The github.com/opencontainers/image-spec project tagged a new RC.

It appears that this was tagged as both `1.1.0-rc.6` and `1.1.0-rc6` ~(in error?)~, as queried with them here: https://github.com/opencontainers/image-spec/issues/1159

Dependabot opened a PR at https://github.com/sylabs/singularity/pull/2557 which announces that it is updating `github.com/opencontainers/image-spec from 1.1.0-rc5 to 1.1.0-rc.6`. Instead it is downgrading to the `1.1.0-rc3` tag, and causing a large number of other dependencies to be downgraded also.

See - https://github.com/sylabs/singularity/pull/2557/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

### Native package manager behavior

Native `go get -u` updates to `v1.1.0-rc6`, with no other `go.mod` changes.

Note that it picked `v1.1.0-rc6` and not the `v1.1.0-rc.6` that dependabot reported attempting.

```
02:26 pm $ go get -u github.com/opencontainers/image-spec
go: downloading github.com/opencontainers/image-spec v1.1.0-rc6
go: upgraded github.com/opencontainers/image-spec v1.1.0-rc5 => v1.1.0-rc6

02:26 pm $ git diff
diff --git a/go.mod b/go.mod
index 0944c7074..0c22d4b52 100644
--- a/go.mod
+++ b/go.mod
@@ -33,7 +33,7 @@ require (
        github.com/gosimple/slug v1.13.1
        github.com/moby/buildkit v0.12.4
        github.com/moby/term v0.5.0
-       github.com/opencontainers/image-spec v1.1.0-rc5
+       github.com/opencontainers/image-spec v1.1.0-rc6
        github.com/opencontainers/runc v1.1.11
        github.com/opencontainers/runtime-spec v1.1.0
        github.com/opencontainers/runtime-tools v0.9.1-0.20230914150019-408c51e934dc
diff --git a/go.sum b/go.sum
index 82ef1fb40..ed362a295 100644
--- a/go.sum
+++ b/go.sum
@@ -379,6 +379,8 @@ github.com/opencontainers/go-digest v1.0.0/go.mod h1:0JzlMkj0TRzQZfJkVvzbP0HBR3I
 github.com/opencontainers/image-spec v1.0.1/go.mod h1:BtxoFyWECRxE4U/7sNtV5W15zMzWCbyJoFRP3s7yZA0=
 github.com/opencontainers/image-spec v1.1.0-rc5 h1:Ygwkfw9bpDvs+c9E34SdgGOj41dX/cbdlwvlWt0pnFI=
 github.com/opencontainers/image-spec v1.1.0-rc5/go.mod h1:X4pATf0uXsnn3g5aiGIsVnJBR4mxhKzfwmvK/B2NTm8=
+github.com/opencontainers/image-spec v1.1.0-rc6 h1:XDqvyKsJEbRtATzkgItUqBA7QHk58yxX1Ov9HERHNqU=
+github.com/opencontainers/image-spec v1.1.0-rc6/go.mod h1:W4s4sFTMaBeK1BQLXbG4AdM2szdn85PY75RI83NrTrM=
 github.com/opencontainers/runc v1.0.0-rc90/go.mod h1:qT5XzbpPznkRYVz/mWwUaVBUv2rmF59PVA73FjuZG0U=
 github.com/opencontainers/runc v1.1.11 h1:9LjxyVlE0BPMRP2wuQDRlHV4941Jp9rc3F0+YKimopA=
 github.com/opencontainers/runc v1.1.11/go.mod h1:S+lQwSfncpBha7XTy/5lBwWgm5+y5Ma/O44Ekby9FK8=

```

### Images of the diff or a link to the PR, issue, or logs

* https://github.com/sylabs/singularity/pull/2557
* https://github.com/sylabs/singularity/pull/2552
* https://github.com/sylabs/singularity/pull/2550
