### ISSUE TITLE
FileUpdater failed in many repositories

### ISSUE THREAD

**Issue by DavidBoike** [dependabot/dependabot-core#8860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

.NET

### Language version

.NET 8

### Manifest location and content before the Dependabot update

Projects in the pattern `src/{ProjectName}/{ProjectName}.csproj`

### dependabot.yml content

```
version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1000
  groups:
    AWSSDK:
      patterns:
        - "AWSSDK.*"
    NServiceBusCore:
      patterns:
        - "NServiceBus"
        - "NServiceBus.AcceptanceTesting"
        - "NServiceBus.AcceptanceTests.Sources"
        - "NServiceBus.PersistenceTests.Sources"
        - "NServiceBus.TransportTests.Sources"
  ignore:
    # Particular.Analyzers updates are distributed via RepoStandards
    - dependency-name: "Particular.Analyzers"
    # Changing these 3 dependencies affects the .NET SDK and Visual Studio versions we support 
    # These types of updates should be more intentional than an automated update
    - dependency-name: "Microsoft.Build.Utilities.Core"
    - dependency-name: "Microsoft.CodeAnalysis.CSharp"
    - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1000
```

### What you expected to see, versus what you actually saw

Expect Dependabot to run without errors, but here are some examples of error blocks where the FileUpdater failed. I don't know if all are the same error, but I know that these are different from https://github.com/dependabot/dependabot-core/issues/8537 which is also an issue for us in repos that have central package management.

From https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/network/updates/777192726:

```
updater | 2024/01/22 15:38:24 ERROR <job_777192726> Error processing Azure.Messaging.ServiceBus (Dependabot::DependabotError)
updater | 2024/01/22 15:38:24 ERROR <job_777192726> FileUpdater failed
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:38:in `run'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:128:in `run_ungrouped_dependency_updates'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:63:in `perform'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/01/22 15:38:24 ERROR <job_777192726> bin/update_files.rb:24:in `<main>'
```

This stack trace seems to be repeated in other repos:

* https://github.com/Particular/NServiceBus/network/updates/777209595
* https://github.com/Particular/NServiceBus.RavenDB/network/updates/776827269
* https://github.com/Particular/NServiceBus.RabbitMQ/network/updates/777294982
* https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/network/updates/777297634
* https://github.com/Particular/NServiceBus.AmazonSQS/network/updates/777300461
* A few internal repos, but I assume the public ones are easier for troubleshooting?

In any case, it's not every repository in our organization, for example [NServiceBus.SqlServer](https://github.com/Particular/NServiceBus.SqlServer/network/updates/777242232) seems unaffected, but it seems to be hitting quite a lot of them.

We've also sporadically seen this stack trace, here from https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/network/updates/777297591:

```
updater | 2024/01/22 18:47:25 INFO <job_777297591> Sending event 0dcc0447e8d84e50b6b04b64b7c5f4e1 to Sentry
  proxy | 2024/01/22 18:47:25 [968] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/22 18:47:25 [968] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/22 18:47:25 ERROR <job_777297591> Error processing NUnit (NoMethodError)
updater | 2024/01/22 18:47:25 ERROR <job_777297591> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:101:in `updated_dependencies_after_full_unlock'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:61:in `updated_dependencies'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in `check_and_create_pull_request'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:128:in `run_ungrouped_dependency_updates'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:63:in `perform'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/01/22 18:47:25 ERROR <job_777297591> bin/update_files.rb:24:in `<main>'
updater | 2024/01/22 18:47:25 INFO <job_777297591> Checking if Microsoft.NET.Test.Sdk 17.8.0 needs updating
```

That one can also be found in:

* https://github.com/Particular/NServiceBus.AwsLambda.Sqs/network/updates/777302060
