### ISSUE TITLE
Nuget no longer searching subdirectories, erroring with `couldn't find a <anything>.(cs|vb|fs)proj`

### ISSUE THREAD

**Issue by brandonagr** [dependabot/dependabot-core#8872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

net8

### dependabot.yml content
```
version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    - dependency-name: "protobuf-net"
      # ignore all protobuf-net versions, we need 3.0.52 because its the last version that had certain wcf related classes
    - dependency-name: "Apache.NMS*"
      # ignore Apache.NMS and Apache.NMS.ActiveMQ attempting to go from 2.0 to 2.1
    - dependency-name: "System.ServiceModel.*"
      update-types: ["version-update:semver-major"]
      # ignore attempting to update System.ServiceModel.* to 6.0.0, as that doesn't support targetting net48
  open-pull-requests-limit: 16
  groups:
     # Specify a name for the group, which will be used in pull request titles
     # and branch names
     nuget-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*" # A wildcard that matches all dependencies
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
```

### What you expected to see, versus what you actually saw

The same dependabot.yaml had been working for a long time, and sometime in the previous week or two it stopped creating new PRs

It's now logging that it can't find csproj files. We have a large mono repo so the csproj files are located in sub directories, the dependabot.yaml file is specifying `directory: "/"` with the expectation that it would recursively search sub directories (which it did in the past), but that functionality seems to be broken

### Images of the diff or a link to the PR, issue, or logs
```
proxy | 2024/01/23 16:17:22 proxy starting, commit: ebf3724b85167f0333b1131189a46fbdbda0c682
  proxy | 2024/01/23 16:17:22 Listening (:1080)
updater | 2024-01-23T16:17:47.847342155 [777841280:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-01-23T16:17:51Z" level=info msg="guest starting" commit=90af8a6c05b9bffe4b43b13215eded5f1f9b1c00
updater | time="2024-01-23T16:17:51Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=777841280 updater_timeout=45m0s updater_version=fb330c9e82a32335437850614d7989683ae9b6f6-nuget
updater | 2024/01/23 16:17:56 INFO Raven 3.1.2 ready to catch errors
updater | 2024/01/23 16:17:59 INFO <job_777841280> Starting job processing
  proxy | 2024/01/23 16:18:00 [002] GET https://github.com:443/...
updater | 2024/01/23 16:18:03 ERROR <job_777841280> Error during file fetching; aborting: /<anything>.(cs|vb|fs)proj not found
updater | 2024/01/23 16:18:03 INFO <job_777841280> Finished job processing
updater | 2024/01/23 16:18:03 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------+
updater | |          Errors           |
updater | +---------------------------+
updater | | dependency_file_not_found |
updater | +---------------------------+
updater | time="2024-01-23T16:18:03Z" level=info msg="task complete" container_id=job-777841280-file-fetcher exit_code=0 job_id=777841280 step=fetcher
updater | time="2024-01-23T16:18:04Z" level=warning msg="failed during fetch, skipping updater" job_id=777841280
```
