### ISSUE TITLE
Artifactory private nuget package source authentication

### ISSUE THREAD

**Issue by vadimi** [dependabot/dependabot-core#8887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

```
registries:
  nuget-public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

  my-artifactory:
    type: nuget-feed
    url: https://xyz.jfrog.io/artifactory/api/nuget/v3/nuget-local
    username: ${{secrets.ART_USER}}
    password: ${{secrets.ART_PASS}}
```

### What you expected to see, versus what you actually saw

artifactory private nuget package source authentication is not working. I think part of the reason could be that artifactory requires username/password, but it looks like `nuget_config_credential_helpers.rb` uses hardcoded user `user` and `token` instead of password:

<img width="834" alt="image" src="https://github.com/dependabot/dependabot-core/assets/1156106/771f52fa-8ce5-4529-9e4a-da0cfb6b29f4">

is there a way to support username/password, so that artifactory authentication starts working? Otherwise none of the dependencies get updated, event the ones coming from public nuget feed.

By the way public package updates were working fine until something changed in the nuget implementation. Now none of the packages get updates in projects that also use private packages.
