### ISSUE TITLE
Not all updates in group are applied

### ISSUE THREAD

**Issue by SvenGroot** [dependabot/dependabot-core#8888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

.Net 8

### Language version

C# 11

### Manifest location and content before the Dependabot update

[src/Ookii.BinarySize.Test/Ookii.BinarySize.Test.csproj](https://github.com/SvenGroot/Ookii.BinarySize/blob/main/src/Ookii.BinarySize.Test/Ookii.BinarySize.Test.csproj)

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
       # Group all dependencies in one PR.
       nuget-dependencies:
          patterns:
             - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
```

### Updated dependency

In this case, MSTest.TestAdapter and MSTest.TestFramework, but I have seen this with many different dependencies over the last month or so, and in multiple repositories.

### What you expected to see, versus what you actually saw

Whenever there are multiple updates in a group, the description of the PR will list all of them, but the PR itself actually only contains  an update to a single package. I would expect it to update all mentioned packages in a single PR.

This used to work previously (with no changes in dependabot.yml), but has been broken for at least a month.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/SvenGroot/Ookii.BinarySize/pull/16

In this example, both MSTest.TestAdapter and MSTest.TestFramework are mentioned in the PR description, but only MSTest.TestFramework is updated in the commit made by dependabot. I made my own commit to update the missing package before completing the PR.
