### ISSUE TITLE
Allow non-unique combination of 'package-ecosystem', 'directory', and 'target-branch'

### ISSUE THREAD

**Issue by joergi** [dependabot/dependabot-core#8938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I want to be able to define 2 dependency rules for  ONE target-branch and ONE directory and ONE package-ecosystem.

Sometime (especially for front-end) I need to verify the changes visually, so I can't automatically merge the PRs.

So, I want to be able to automatically merge the PRs which are save to merge., but for some I don't want to add the `automatic-merge` label (which will trigger a automatic merge by another workflow)

So the dependabot yaml would look like this.

```yaml
 - package-ecosystem: "gradle"
    directory: "/demo1/"
    allow:
      depedency-name: "org.something:something-for-frontend"
    labels:
      - "dependencies"
      - "automatic-merge"

  - package-ecosystem: "gradle"
    directory: "/demo1/"
    ignore:
      dependency-name: "org.something:something-for-frontend"
    labels:
      - "dependencies"
```
But if I try something like this, I get an error saying:

``` 
Dependabot encountered the following error when parsing your .github/dependabot.yml:
The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'
Please update the config file to conform with Dependabot's specification.
```
Solution would be, that every dependabot job get a unique ID or name. so it could be differentiated.

**Comment by carogalvin** [comment]
@joergi in this case, how do you differentiate between what you would like to get the `automatic-merge` label and which should not? Is it by dependency name or something else?

**Comment by joergi** [comment]
That's why I added at the end a unique name / id would be good.

But I would  do the automatic merge by label. Those who have the label `automatic-merge`  will be merged, the others not

**Comment by mkurz** [comment]
@joergi I think you example is wrong?

```
    allow:
      dependency-name: "org.something:something-for-frontend"
...
    ignore:
      dependency-name: "org.something:something-for-frontend"
```

Here you have `org.something:something-for-frontend` twice. Shouldn't that be something like

```
```
    allow:
      dependency-name: "org.something:something-for-backend"
...
    ignore:
      dependency-name: "org.something:something-for-frontend"
```
?
Otherwise this example doesn't really make sense or no?

**Comment by joergi** [comment]
@mkurz thanks.  I see what you mean.  I changed it.  thanks a lot.

**Comment by mistic100** [comment]
I think the original example made more sense actually, you explicitely declare one rule to allow `org.something:something-for-frontend` and the other to ignore `org.something:something-for-frontend`, this way you are sure of which rule will handle this package.

That being saif the system must have a explicit behaviour of which rule to apply if a package is elligible to multiple rules (either the first one or the last one).

---

I have another usecase for this request : configure different update interval for specific NPM packages. Here I try to get daily NPM updates but for eslint/stylelint which should be weekly. Using the same logic of one rule explicitely ignoring it and the other allowing it.

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - mistic100
    ignore:
      - dependency-name: '*eslint*'
      - dependency-name: '*stylelint*'
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor']
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    assignees:
      - mistic100
    allow:
      - dependency-name: '*eslint*'
      - dependency-name: '*stylelint*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor']
```
