### ISSUE TITLE
Dependabot is prefixing PRs with a JIRA ticket number but I cannot figure out how

### ISSUE THREAD

**Issue by eterhoven** [dependabot/dependabot-core#8939]
The goal of this ticket is to enquire if its possible to change which JIRA ticket Dependabot uses as a prefix for new Pull Requests. 

Background:
We are using dependabot in our repositories to keep actions and workflow versions up to date. Our dependabot configuration is pretty standard, and none of the commit-message parameters have been added to any of them. Example:

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
    assignees:
      - "org/team"
    reviewers:
      - "org/team"
    labels:
      - "dependencies"
      - "automated-pr"
      - "github-actions"
```
      
At the same time, our team has a weekly ticket in Jira that is used to capture work that is otherwise not allocated to a specific ticket. At the start of each week this ticket moves into review while a new one is created and placed in progress.

Since we started using dependabot, it has been making use of this weekly ticket number to open Pull Requests, for every dependabot pr across our organization. This is actually rather useful, but what has me stumped is how it is doing this.

I was reading through the dependabot documentation and I found this sentence about commit messages:
By default, Dependabot attempts to detect your commit message preferences and use similar patterns.

This seems a little vague but I wonder if this is perhaps how it is working...somehow?

My questions:
1. Is it possible to gain some sort of understanding how dependabot is retrieving and making use of that Jira ticket?
2. Is it possible to direct dependabot toward some sort of weekly dependabot ticket instead? We would like to keep the Jira integration, but the many dependabot PRs are clogging up our weekly ticket, so we would prefer to let dependabot have its own space.

Thank you for any help you may be able to offer!

**Comment by yeikel** [comment]
As far as I understand  : 

1. Dependabot traverses your commit history and tries to find patterns to latter apply to the pull request. That is where the JIRA ticket is coming from. Some of the logic can be found here : 

https://github.com/dependabot/dependabot-core/blob/df3e6e1cc9f708c5ae5b6243a8d2e22e4cc43c3e/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L327-L334
https://github.com/dependabot/dependabot-core/blob/df3e6e1cc9f708c5ae5b6243a8d2e22e4cc43c3e/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L166-L204


2. You can however dependabot with a hardcoded prefix that should continue to use for all the future pull requests : 

```yml
- package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with your jira ticket
      prefix: "XXXXX"
```
