### ISSUE TITLE
Gomod dependency gets downgraded after manual update

### ISSUE THREAD

**Issue by achilleas-k** [dependabot/dependabot-core#8949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### Package manager version

go 1.19

### Language version

go 1.19

### dependabot.yml content

https://github.com/osbuild/images/blob/main/.github/dependabot.yml

```yaml
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    groups:
      go-deps:
        patterns:
          - "*"  # group all dependency updates into one PR
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
```

### Updated dependency

github.com/containers/image/v5

### What you expected to see, versus what you actually saw

**What I expect:** dependabot should not be downgrading a dependency 
**What happens:** dependabot PRs downgrade a dependency every time it runs

**Description**

About a week ago, a dependabot PR pulled in updates that were incompatible with a specific dependency.  I manually updated the dependency from v5.22.1 to v5.29.1 and included it in the PR.
- dependabot PR: https://github.com/osbuild/images/pull/390
- Breaking commit: https://github.com/osbuild/images/commit/c8d9c5eff6928931faf7ff9e92d09d4f53572d1e
- Manual dependency update commit: https://github.com/osbuild/images/commit/13622d01ba62ec9a4cb946c5c82ac97bf1bdf0b7

Since then, every dependabot PR reverts the change to v5.22.1 of github.com/containers/image/v5, but fails because of the incompatibility.

Most recent example: https://github.com/osbuild/images/pull/416 (see: https://github.com/osbuild/images/pull/416/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L17)
See also:
- https://github.com/osbuild/images/pull/397
- https://github.com/osbuild/images/pull/401
- https://github.com/osbuild/images/pull/403
- https://github.com/osbuild/images/pull/406

### Images of the diff or a link to the PR, issue, or logs

- https://github.com/osbuild/images/pull/397
- https://github.com/osbuild/images/pull/401
- https://github.com/osbuild/images/pull/403
- https://github.com/osbuild/images/pull/406
