### ISSUE TITLE
gomod does not update the go version that is defined in go.mod

### ISSUE THREAD

**Issue by sbp-bvanb** [dependabot/dependabot-core#9057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### What you expected to see, versus what you actually saw

The expectation is that the patch version of go should be updated from `go 1.21.2` to `go 1.21.7` and since the latest release of `1.22.0` to `1.22.0`.

### Smallest manifest that reproduces the issue

Define: `go 1.21.2` in a go.mod and enable dependabot:

```
---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
```
