### ISSUE TITLE
Error when updating NuGet packages from Public and Private Feed

### ISSUE THREAD

**Issue by FrankRua** [dependabot/dependabot-core#9069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

C# (.NET 6)

### Manifest location and content before the Dependabot update

Manifest files would be kept respectively in the `csproj` files that contain them,

### dependabot.yml content

```
version: 2
registries:
  internal-packages-nuget-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/REDACTED/index.json
    username: REDACTED
    password: REDACTED
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: nuget
    directory: "/"
    registries:
      - internal-packages-nuget-github
      - nuget
    schedule:
      interval: daily
      time: "06:00"
      timezone: America/New_York
    groups:
       private-repo-dependencies:
          patterns:
            - "*"
    open-pull-requests-limit: 10
    labels:
      - "nuget"
      - "dependencies"
    assignees:
      - "REDACTED/REDACTED"
```

### What you expected to see, versus what you actually saw

**What I expect:** Dependabot to raise a PR with the correct depdendcies updates for both public and private feeds.
**What is happening:** Only a few packages are being updated and we are getting errors on the rest. Example for a public package:

```
updater | 2024/02/16 11:43:42 ERROR <job_787880721> Error processing Microsoft.Extensions.Caching.Abstractions (Dependabot::DependabotError)
updater | 2024/02/16 11:43:42 ERROR <job_787880721> FileUpdater failed
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:69:in `run'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:42:in `create_from'
  proxy | 2024/02/16 11:43:42 [722] 200 https://sentry.io:443/api/1451818/envelope/
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `bind_call'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `validate_call_skip_block_type'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:111:in `block in create_validator_slow_skip_block_type'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:114:in `create_change_for'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:72:in `block in compile_all_dependency_changes_for'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:38:in `each'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:38:in `compile_all_dependency_changes_for'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb:110:in `dependency_change'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb:93:in `perform'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/02/16 11:43:42 ERROR <job_787880721> bin/update_files.rb:24:in `<main>'
```

**Comment by brettfo** [comment]
Could you post the whole log?  There's likely something interesting before the failure listed.

**Comment by HavenDV** [comment]
I'm using a similar configuration and have been experiencing this issue for all my repos for the last 2 months or so
In this case, the PR message correctly describes all the necessary updates, but the PR body itself does not contain this
```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"

```


Examples:
- https://github.com/tryAGI/Tiktoken/pull/20
- https://github.com/HavenDV/OpenApiGenerator/pull/7
