### ISSUE TITLE
Dependabot not finding all instances of package upgrades in .NET solution

### ISSUE THREAD

**Issue by matt-mckinstry-cloudm** [dependabot/dependabot-core#9088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### Language version

.NET 8

### Manifest location and content before the Dependabot update

Example of Filesystem/Project structure:

- /src/SolutionFile.sln
- /src/API1/API1.csproj
- /src/API1/API1.Tests.csproj
- /src/API2/API2.csproj
- /src/API2/API2.Tests.csproj
- /src/API3/API3.csproj
- /src/API3/API3.Tests.csproj
- /src/Common.csproj
- /src/Common.Tests.csproj

### dependabot.yml content

- package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    target-branch: "develop"

### Updated dependency

XUnit 2.6.6 -> 2.7.0
However this happens with all dependencies

### What you expected to see, versus what you actually saw

My 4 Test projects in the structure attached all use XUnit (happens for other dependencies too). Dependabot has detected a package upgrade from 2.6.6 -> 2.7.0 and created a PR for the change, this is great. However, it has only 2 of the Test project csproj files in the PR. It has not found the package reference upgrades in the other 2 of my csproj projects. The projects are all referenced correctly from the solution file.

### Native package manager behavior

Update is possible to consolidate across all projects

**Comment by redbaty** [comment]
This seems to be happening to me aswell:

https://github.com/redbaty/Wasari/pull/79

Dependabot found the correct packages to update, yet the commit only changes one csproj:
https://github.com/redbaty/Wasari/pull/79/commits/c0d3cbb6afcb5fcb05a23c6afc5eea43f8142db9

**Comment by IEvangelist** [comment]
Yes, I'm experiencing the same (or similar) issue. In one of my repos, dependabot claims to update three packages, but actually only updates a single package - the last one mentioned:

- See: https://github.com/IEvangelist/profanity-filter/pull/16

Here's my [dependabot.yml](https://github.com/IEvangelist/profanity-filter/blob/main/.github/dependabot.yml):

```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # Core GitHub Actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
    groups:
      # Group .NET updates together for solutions.
      dotnet:
        patterns:
          - "*" # Prefer a single PR per solution update.
```

**Comment by IshakAtLEGO** [comment]
I have same issue - dependabot PR groups several package changes but only the last package in the list is changed.
My dependabot.yml file:

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for nuget 
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
        major: 
          patterns:
          - "*"
          update-types: ["major"]
        minor:
          patterns:
          - "*"
          update-types: 
          - "minor"
          - "patch"
```
