### ISSUE TITLE
Support bearer token authentication with private composer repository

### ISSUE THREAD

**Issue by jankal** [dependabot/dependabot-core#9093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently, Dependabot only supports authentication with private composer repositories by the means of HTTP Basic auth with username and password.

Composer, on the other hand, supports some more authentication methods than currently implemented in Dependabot[^1]:

- http-basic
- HTTP Bearer
- gitlab-oauth
- gitlab-token
- github-oauth
- bitbucket-oauth

Of those listed here, the bearer token authentication method is probably the most widespread one, after plain old basic auth.

So I propose to extend the dependabot.yml schema to also allow specifying a token instead of a username & password combination like this:
```yaml
version: 2
registries:
  private-packages:
    type: composer-repository
    url: https://<url>
    token: ${{secrets.COMPOSER_TOKEN}}
```

Our use-case:
We are using the proprietary packages.shopware.com composer repository to manage Shopware plugin dependencies through composer. Shopware only hands out Bearer tokens for each licensing host to talk to their private composer repository.

[^1]: [Composer Docs - Authentication for privately hosted packages and repositories](https://getcomposer.org/doc/articles/authentication-for-private-packages.md)
