### ISSUE TITLE
Wrong python version detection

### ISSUE THREAD

**Issue by sileht** [dependabot/dependabot-core#9096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

python

### Package manager version

poetry

### Language version

3.12.2

### Manifest location and content before the Dependabot update

pyproject.toml

```
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "xxxx"
version = "0.0.0"
description = "xxxx"
classifiers = ["Intended Audience :: Information Technology", "License :: OSI Approved :: Apache Software License", "Operating System :: POSIX", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.12"]
homepage = "xxxx"
authors = ["xxxx"]

[tool.poetry.dependencies]
python = ">=3.12.2,<4.0"
...
```

### dependabot.yml content

```
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      # yamllint disable-line rule:quoted-strings
      time: "08:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*"
        dependency-type: all
    ignore:
      # FIXME(sileht):
      # https://github.com/redis/redis-py/issues/2995
      - dependency-name: redis
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      # yamllint disable-line rule:quoted-strings
      time: "08:00"
      timezone: Europe/Paris
 ```

### What you expected to see, versus what you actually saw

Dependabot tells us that Python version 3.12.2 is unsupported:

```
Dependabot detected the following Python requirement for your project: '>=3.12.2,<4.0'.

Currently, the following Python versions are supported in Dependabot: 3.12.*, 3.11.*, 3.10.*, 3.9.*, 3.8.*.
```

It worked fine with `>=3.12.1,<4` and python 3.12.1, and broke with `>=3.12.2,<4.0` and python 3.12.2.

### Images of the diff or a link to the PR, issue, or logs

```
proxy | 2024/02/22 08:31:22 proxy starting, commit: 522f7d5de26af655e784f4e36e2c6d2b6eea5882
  proxy | 2024/02/22 08:31:22 Listening (:1080)
updater | 2024-02-22T08:31:23.320757741 [790716673:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-02-22T08:31:25Z" level=info msg="guest starting" commit=079f8d0b3243622975a6ac674f1264d1c8642945
updater | time="2024-02-22T08:31:25Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=790716673 updater_timeout=45m0s updater_version=28ee109dcbf7c79c51ccb514cdf29d2f5660968a-pip
updater | 2024/02/22 08:31:28 INFO <job_790716673> Starting job processing
  proxy | 2024/02/22 08:31:29 [002] GET https://github.com:443/xxx/xxx/info/refs?service=git-upload-pack
  proxy | 2024/02/22 08:31:29 [002] * authenticating git server request (host: github.com)
  proxy | 2024/02/22 08:31:29 [002] 200 https://github.com:443/xxx/xxx/info/refs?service=git-upload-pack
  proxy | 2024/02/22 08:31:29 [004] POST https://github.com:443/xxx/xxx/git-upload-pack
  proxy | 2024/02/22 08:31:29 [004] * authenticating git server request (host: github.com)
  proxy | 2024/02/22 08:31:29 [004] 200 https://github.com:443/xxx/xxx/git-upload-pack
  proxy | 2024/02/22 08:31:29 [006] POST https://github.com:443/xxx/xxx/git-upload-pack
  proxy | 2024/02/22 08:31:29 [006] * authenticating git server request (host: github.com)
  proxy | 2024/02/22 08:31:29 [006] 200 https://github.com:443/xxx/xxx/git-upload-pack
updater | 2024/02/22 08:31:36 ERROR <job_790716673> Error during file fetching; aborting: Dependabot detected the following Python requirement for your project: '>=3.12.2,<4.0'.
updater | 
updater | Currently, the following Python versions are supported in Dependabot: 3.12.*, 3.11.*, 3.10.*, 3.9.*, 3.8.*.
updater | 2024/02/22 08:31:37 INFO <job_790716673> Finished job processing
updater | 2024/02/22 08:31:37 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +----------------------------+
updater | |           Errors           |
updater | +----------------------------+
updater | | tool_version_not_supported |
updater | +----------------------------+
updater | time="2024-02-22T08:31:37Z" level=info msg="task complete" container_id=job-790716673-file-fetcher exit_code=0 job_id=790716673 step=fetcher
updater | time="2024-02-22T08:31:37Z" level=warning msg="failed during fetch, skipping updater" job_id=790716673
Footer
© 2024 GitHub, Inc.
Footer navigation
[Terms](https://docs.github.com/site-policy/github-terms/github-terms-of-service)
[Privacy](https://docs.github.com/site-policy/privacy-policies/github-privacy-statement)
[Security](https://github.com/security)
[Status](https://www.githubstatus.com/)
```
