### ISSUE TITLE
Some packages finish with unknown error, both self-hosted or public packages

### ISSUE THREAD

**Issue by mikebucher** [dependabot/dependabot-core#9114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

.net 8.0.100

### dependabot.yml content

```
version: 2
registries:
  nuget-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/DigitecGalaxus/index.json
    token: ${{ secrets.GH_PACKAGES_READ }}
  public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: nuget
    registries: "*"
    schedule:
      interval: weekly
      time: "07:00"
    directory: /
    groups:
     nonmajor:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      major:
        patterns:
        - "*"
        update-types:
        - "major"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      non-major:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      major:
        patterns:
        - "*"
        update-types:
        - "major"
```

### What you expected to see, versus what you actually saw

Dependabot fails to update some packages, throwing a unknown_error. This only happens for 5 packages in this repository, the rest work fine, and happens with both privately hosted and public packages. We are getting the same errors in another repository as well. Below I posted the log for one of the public ones. The error log seems the same for all packages where this unknown_error occurs. We use central package versioning, and have only seen this error show up more recently, as we have just started migrating teams over to GitHub from ADO. 

### Images of the diff or a link to the PR, issue, or logs

```

updater |   Updating dotnet-tools.json files.
updater |     Dependency [Microsoft.Extensions.Http.Polly] not found in any dotnet-tools.json files.
updater | Running for project [/home/dependabot/dependabot-updater/repo/test/UnitTest/UnitTest.csproj]
updater |   Updating [global.json] file.
updater |     Dependency [Microsoft.Extensions.Http.Polly] not found.
updater |   Running for SDK-style project
updater |     Package [Microsoft.Extensions.Http.Polly] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/test/UnitTest/UnitTest.csproj].
updater | Update complete.
updater | 2024/02/22 07:58:08 INFO <job_790684281> [Transport] Sending envelope with items [event] 5d2a56867d4e428894c2c51853d67a9d to Sentry
updater | 2024/02/22 07:58:08 ERROR <job_790684281> Error processing Microsoft.Extensions.Http.Polly (Dependabot::DependabotError)
updater | 2024/02/22 07:58:08 ERROR <job_790684281> FileUpdater failed
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:69:in `run'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:42:in `create_from'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `bind_call'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `validate_call_skip_block_type'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:111:in `block in create_validator_slow_skip_block_type'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:114:in `create_change_for'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:72:in `block in compile_all_dependency_changes_for'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:38:in `each'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:38:in `compile_all_dependency_changes_for'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb:110:in `dependency_change'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb:93:in `perform'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/02/22 07:58:08 ERROR <job_790684281> bin/update_files.rb:24:in `<main>'
```
