### ISSUE TITLE
Support auth.json for private composer repository

### ISSUE THREAD

**Issue by Dathix** [dependabot/dependabot-core#9115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Regarding the latest feature request (#9093) it would probably be good to support composers `auth.json`[^1] file format for private repositories.

```
version: 2
registries:
  private-packages:
    type: composer-repository
    url: https://<url>
    file: ${{secrets.COMPOSER_AUTH_JSON}}
```

The `COMPOSER_AUTH_JSON` secret would contain the JSON file content. This is also the common way to provide the file to any GitHub actions.  

[^1]: https://getcomposer.org/doc/articles/authentication-for-private-packages.md#authentication-in-auth-json-per-project

**Comment by nlemoine** [comment]
This feature also goes with a custom config file, at least the `repositories` key:

```json
{
    "repositories": {
        "advancedcustomfields": {
             "type": "composer",
             "url": "https://connect.advancedcustomfields.com",
             "only": ["wpengine/advanced-custom-fields-pro"]
        }
    }
}
```

Because you don't necessarily have to list your repositories in your local `composer.json`, they can also live in your global composer config.

**Comment by NicktheGeek** [comment]
Can we get some traction on this? I have several projects using a private repo for a portion of the dependencies in composer, and even if I'm not trying to use dependabot to handle updates from those packages, it fails to update other packages.

**Comment by alex5513** [comment]
Any news on this subject? It's a bit problematic

**Comment by v-thavaahariharangit** [comment]
Looks like things are working as expected. Please let me know what am I missing here

Files used for testing
`auth.json`
```
{
  "http-basic": {
    "jfrogghdemo.jfrog.io": {
      "username": "thavaahariharangit@github.com",
      "password": "${secrets.COMPOSER_TOKEN}"
    }
  }
}
```

`.github/dependabot.yml`
```
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - composer-artifactory

registries:
    composer-artifactory:
       type: "composer-repository"
       url: "https://jfrogghdemo.jfrog.io/artifactory/api/composer/dependabot-php/"
       username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
       password: "${{ secrets.COMPOSER_TOKEN }}"
```

`composer.json`
```
{
    "repositories": [
        {
            "packagist.org": false
        },
        {
            "type": "composer",
            "url": "https://jfrogghdemo.jfrog.io/artifactory/api/composer/dependabot-php/"
        }
    ],
    "require": {
        "phpstan/phpstan": "2.0.0"
    }
}
```
