### ISSUE TITLE
Allow usernames in private registry urls

### ISSUE THREAD

**Issue by PeterJCLaw** [dependabot/dependabot-core#9171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In some configurations `pip` requires that an `--extra-index-url` contains a username (as described at https://github.com/pypa/pip/issues/12543). Currently dependabot enforces the lack of a username in private registry urls and will **insert the url without the username into requirements files**, even if a version of the url (with the username) is already present.

The presence of the url without the username then **breaks workflows** which expect the username to be present.

For context my setup is:
- `pip-compile`, with `--extra-index-url` (containing a username) in the `*.in` files
- `keyring` with Google's plugin to access a Google Artifact Registry PyPI
- dependabot with a private registry config for the plain (i.e: no-username) index url

It would be great if one of the following were true:
- dependabot allowed usernames in private registry urls
   - in my case I actually want to then override that username with a different one for dependabot to actually use, so I'd want support for that too
- dependabot could be configured either with the url to insert or being told not to insert a url (i.e: trust that the url is already present)
- dependabot could automatically detect the presence of an equivalent url and not insert the different one into the generated requirements files

I'm also open to other ways to approach this if there's something around configuring dependabot that I've missed.

**Comment by v-thavaahariharangit** [comment]
I've tested the reported issue using the following repository: 
🔗 [dsp-testing/python-dependabot-private-registry-issue-9171](https://github.com/dsp-testing/python-dependabot-private-registry-issue-9171)



### ✅ Credentials do not need to be embedded in the URL. 
In the generated `requirements.txt`, the registry is correctly referenced using:
`--index-url https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple`

Full `requirements.txt`
```
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --index-url=https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple
#
--index-url https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple

certifi==2024.6.2
    # via requests
charset-normalizer==3.3.2
    # via requests
idna==3.7
    # via requests
requests==2.32.2
    # via -r requirements.in
urllib3==2.2.1
    # via requests
```

### 📌 To ensure proper authentication, confirm that the registry URL is defined in your `dependabot.yml` like so:

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    registries:
      - python-artifactory

registries:
  python-artifactory:
    type: "python-index"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.PYTHON_TOKEN }}"
    replaces-base: true
```
Note: In case of `--extra-index-url` ensure you are not using `replaces-base: true`


### 📦 Dependabot successfully created a pull request: 
🔗 [PR #1](https://github.com/dsp-testing/python-dependabot-private-registry-issue-9171/pull/1)

<img width="1885" height="459" alt="Image" src="https://github.com/user-attachments/assets/878d2fe6-fd35-4e4b-a805-648fd6268d71" />

With this confirmation, I’m closing the ticket.
