### ISSUE TITLE
Dependabot Gradle version update fails with "dependency_file_not_found" for files in git submodule

### ISSUE THREAD

**Issue by haraldk** [dependabot/dependabot-core#9198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Manifest location and content before the Dependabot update

Main entrypoint:

```
build.gradle
```

Referenced via:  `apply from: 'build-system/dependencies-spring.gradle'` in `build.gradle` above.

```
build-system/dependencies-spring.gradle
``` 

Note: `build-system` is a Git submodule.

### dependabot.yml content

```yaml
version: 2
registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/our-org/*
    username: "our-user"
    password: ${{ secrets.GITHUB_PACKAGES_READ_TOKEN }}
updates:
  # Enable version updates for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - github-packages
    schedule:
      interval: "daily"
    # Limit number of open PRs
    open-pull-requests-limit: 10
  # Enable version updates for submodules (build-system)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  # Enable version updates for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
```

### What you expected to see, versus what you actually saw

As noted above, `build-system` is a Git submodule (which is updated via Dependabot too, and it works fine). However, when running the Gradle update check, it seems Dependabot can't find the files in the submodule. My guess it that it isn't fetched at all... 

The above `dependabot.yaml` used to work fine (last PR was merged on January 26. 2024), but now Dependabot complains: "Error during file fetching; aborting: /build-system/dependencies-spring.gradle not found". I guess this is some sort of regression or change in functionality. 

It would be nice if dependabot could fetch submodules for version checks again, or add an option to enable it. 

(The reason we need this to work, is that we have collections of libraries in the submodule, with versions as variables, these variables are defined in the top level `build.gradle`). 

Here's a part of the log for the failing update (full contents in logs below): 

```
updater | 2024/03/04 12:27:27 ERROR <job_795506033> Error during file fetching; aborting: /build-system/dependencies-spring.gradle not found
updater | 2024/03/04 12:27:28 INFO <job_795506033> Finished job processing
updater | 2024/03/04 12:27:28 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------+
updater | |          Errors           |
updater | +---------------------------+
updater | | dependency_file_not_found |
updater | +---------------------------+
updater | time="2024-03-04T12:27:28Z" level=info msg="task complete" container_id=job-795506033-file-fetcher exit_code=0 job_id=795506033 step=fetcher
updater | time="2024-03-04T12:27:28Z" level=warning msg="failed during fetch, skipping updater" job_id=795506033
```

### Images of the diff or a link to the PR, issue, or logs

```
 proxy | 2024/03/04 12:27:16 proxy starting, commit: b46ea0704f16a9103c1637eea8708f9cf4f39684
  proxy | 2024/03/04 12:27:16 Listening (:1080)
updater | 2024-03-04T12:27:18.134492116 [795506033:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-03-04T12:27:20Z" level=info msg="guest starting" commit=684e575d82404ac8cfafa9000ff20dbc9dddb4f6
updater | time="2024-03-04T12:27:20Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=795506033 updater_timeout=45m0s updater_version=29b0328d79f188adc8338958a16d6301018acf30-gradle
updater | 2024/03/04 12:27:26 INFO <job_795506033> Starting job processing
updater | 2024/03/04 12:27:26 INFO <job_795506033> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"include-scope":null,"prefix":null,"prefix-development":null},"credentials-metadata":[{"type":"maven_repository","url":"https://maven.pkg.github.com/nrkno/*"},{"host":"github.com","type":"git_source"}],"debug":null,"dependencies":null,"dependency-group-to-refresh":null,"dependency-groups":[],"existing-group-pull-requests":[],"existing-pull-requests":[],"experiments":{"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"gradle","proxy-log-response-body-on-auth-failure":true,"reject-external-code":false,"repo-private":true,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"api-endpoint":"https://api.github.com/","branch":null,"directory":"/.","hostname":"github.com","provider":"github","repo":"nrkno/mdb-authority-client"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false}}
updater | 
  proxy | 2024/03/04 12:27:27 [002] GET https://github.com:443/nrkno/mdb-authority-client/info/refs?service=git-upload-pack
  proxy | 2024/03/04 12:27:27 [002] * authenticating git server request (host: github.com)
  proxy | 2024/03/04 12:27:27 [002] 200 https://github.com:443/nrkno/mdb-authority-client/info/refs?service=git-upload-pack
  proxy | 2024/03/04 12:27:27 [004] POST https://github.com:443/nrkno/mdb-authority-client/git-upload-pack
  proxy | 2024/03/04 12:27:27 [004] * authenticating git server request (host: github.com)
  proxy | 2024/03/04 12:27:27 [004] 200 https://github.com:443/nrkno/mdb-authority-client/git-upload-pack
  proxy | 2024/03/04 12:27:27 [006] POST https://github.com:443/nrkno/mdb-authority-client/git-upload-pack
  proxy | 2024/03/04 12:27:27 [006] * authenticating git server request (host: github.com)
  proxy | 2024/03/04 12:27:27 [006] 200 https://github.com:443/nrkno/mdb-authority-client/git-upload-pack
updater | 2024/03/04 12:27:27 ERROR <job_795506033> Error during file fetching; aborting: /build-system/dependencies-spring.gradle not found
updater | 2024/03/04 12:27:28 INFO <job_795506033> Finished job processing
updater | 2024/03/04 12:27:28 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------+
updater | |          Errors           |
updater | +---------------------------+
updater | | dependency_file_not_found |
updater | +---------------------------+
updater | time="2024-03-04T12:27:28Z" level=info msg="task complete" container_id=job-795506033-file-fetcher exit_code=0 job_id=795506033 step=fetcher
updater | time="2024-03-04T12:27:28Z" level=warning msg="failed during fetch, skipping updater" job_id=795506033
```
