### ISSUE TITLE
Dependabot does not consider ignore rule

### ISSUE THREAD

**Issue by jscarle** [dependabot/dependabot-core#9201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

netstandard2.0

### Manifest location and content before the Dependabot update

https://github.com/jscarle/AttributeSourceGenerator/blob/main/src/AttributeSourceGenerator/AttributeSourceGenerator.csproj
```xml
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.1" PrivateAssets="all"/>
    </ItemGroup>
```

### dependabot.yml content

https://github.com/jscarle/AttributeSourceGenerator/blob/main/.github/dependabot.yml
```yml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
```

### Updated dependency

Microsoft.CodeAnalysis.CSharp 4.3.1 => 4.9.2

### What you expected to see, versus what you actually saw

Ignore should be respected and PR should not be opened.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/jscarle/AttributeSourceGenerator/pull/4

### Smallest manifest that reproduces the issue

```yml
version: 2
updates:
  - package-ecosystem: "nuget"
    ignore:
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
```
