### ISSUE TITLE
Grouped Update Messages Incorrect

### ISSUE THREAD

**Issue by watercable76** [dependabot/dependabot-core#9248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### Language version

C# 12

### What you expected to see, versus what you actually saw

Nuget grouped updates are updating the packages based on grouping parameters, but the update message is not matching the grouping parameters.

For example, I would only see Microsoft based updates in my microsoft group, but I'm also seeing other packages referenced in the update message.

For the actual file updates, I'm only seeing the packages matched by the grouping filers. Here is what my grouping looks like:  
```yaml
groups:
      microsoft:
        patterns:
          - 'Microsoft*'
      default:
        patterns:
          - '*'
        exclude-patterns:
          - 'Microsoft*'
```
