### ISSUE TITLE
GitHub Actions not getting updated due to another package setting

### ISSUE THREAD

**Issue by bduverger** [dependabot/dependabot-core#9266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### dependabot.yml content

```
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Montreal"
    reviewers:
      - "saq-ineat/Ineat/dev-frontend"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
```

### What you expected to see, versus what you actually saw

Dependabot is supposed to create PRs about github-actions but nothing happens.
If we update the value of open-pull-requests-limit to 5 for npm, we can see PRs about github-actions and of course about npm.

Why suddenly, PRs are created for github-actions after setup npm package.
