### ISSUE TITLE
Allow Dependabot to be configured to ONLY create PRs for private registry updates in a ruby project that uses both public and private sources

### ISSUE THREAD

**Issue by argvniyx-enroute** [dependabot/dependabot-core#9272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I have a Ruby project that has a gemfile with both public (i.e. `rubygems.org`) and private (e.g. `https://rubygems.pkg.github.com/MYORGREPO`) sources, and would like to have dependabot open PRs only for gems that fall into the latter category, whilst preserving security updates.

I read https://github.com/dependabot/dependabot-core/issues/4888, which basically asks this (in the general case) and I followed a reply that pointed to https://docs.github.com/en/code-security/dependabot/working-with-dependabot/removing-dependabot-access-to-public-registries#bundler. However that doesn't seem to work. 

I have a `dependabot.yml` file that looks like this:

```yaml
---
version: 2
registries:
  ruby-github:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/MYORGREPO
    token: "${{secrets.DEPENDABOT_HELPER_PAT}}"
    replaces-base: true
updates:
- package-ecosystem: bundler
  registries:
    - ruby-github
  versioning-strategy: increase
  open-pull-requests-limit: 10
  vendor: true
  directory: "/"
  schedule:
    interval: daily
```

and a Gemfile that looks somewhat like this

```ruby
source 'https://rubygems.org'

gem 'my-cool-public-gem'

source 'https://rubygems.pkg.github.com/MYORGREPO' do
  gem 'my-cool-private-gem'
done
```

It is worth noting that in this project, I am checking my `Gemfile.lock` into git (which I see also gets picked up as a source for dependency updates in the Insights tab)

But that doesn't seem to work. I tried a couple of things, unsuccessfully:
- Breaking off the gemfile into separate files, the main one having the private source as its global source and including the one with public dependencies.
- Using a single gemfile, having the global source be the private repo and throwing all public dependencies into a `source` block

Am I misconfiguring/missing something? If not, would it be possible to add this? Thanks for your time!
