### ISSUE TITLE
Invalid update on NuGet/Directory.Packages.props

### ISSUE THREAD

**Issue by samtrion** [dependabot/dependabot-core#9299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

latest

### Language version

Multiple TargetFrameworks: net6.0;net7.0;net8.0

### dependabot.yml content

```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(ci)"
    labels:
      - "dependency-actions"
    open-pull-requests-limit: 50

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(deps)"
    labels:
      - "dependency-nuget"
    open-pull-requests-limit: 50
    # groups:
    #   coverlet:
    #     patterns:
    #       - "coverlet*"
    #   testcontainers:
    #     patterns:
    #       - "testcontainers*"
    #   verify:
    #     patterns:
    #       - "verify*"
    #   xunit:
    #     patterns:
    #       - "xunit"
    #       - "xunit*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(mods)"
    labels:
      - "dependency-gitmodule"
    open-pull-requests-limit: 50
    groups:
      submodules:
        patterns:
          - "*"
```

### Updated dependency

Microsoft.AspNetCore.TestHost

### What you expected to see, versus what you actually saw

I expect, that the line 23 (see screenshot) will be updated, and the lines 24 and 25 will be skipped because of the conditional update.

### Images of the diff or a link to the PR, issue, or logs

![image](https://github.com/dependabot/dependabot-core/assets/3283596/fb66830a-774b-4237-8ad6-ee77327a203c)
