### ISSUE TITLE
commit messages break conventional commit rules

### ISSUE THREAD

**Issue by shanduur** [dependabot/dependabot-core#9304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

All

### Package manager version

*

### Language version

*

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "area/dependency"
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "area/dependency"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "area/dependency"
```

### What you expected to see, versus what you actually saw

Expected:
> fix(deps): bump github.com/onsi/gomega from 1.27.10 to 1.31.1

Actual:
> fix(deps): Bump github.com/onsi/gomega from 1.27.10 to 1.31.1
