### ISSUE TITLE
Dependabot PR doesn't list what packages were updated but the commit message does

### ISSUE THREAD

**Issue by xt0rted** [dependabot/dependabot-core#9314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Manifest location and content before the Dependabot update

https://github.com/xt0rted/dotnet-sdk-updater/blob/cbb5ab188ac13d464cf19bf5ac4f892f6f836934/package.json

```json
{
  "name": "dotnet-sdk-updater",
  "version": "1.0.0",
  "private": true,
  "description": "Update global.json files with the latest SDK version",
  "main": "dist/index.js",
  "type": "module",
  "scripts": {
    "build": "tsc --project ./tsconfig.build.json",
    "clean": "rimraf coverage dist lib",
    "eslint": "eslint . --ext .js,.cjs,.ts",
    "eslint:fix": "npm run eslint -- --fix",
    "lint": "tsc --noEmit && npm run eslint",
    "local": "ncc run src/main.ts",
    "package": "ncc build ./src/main.ts --source-map --license license.txt",
    "readme": "actions-toolkit update-readme --include-example",
    "prerelease": "npm run clean && npm run lint && npm test && npm run build",
    "release": "npm run package && git add -f dist/",
    "postrelease": "node --loader ts-node/esm ./scripts/prepare-release.ts && git add action.yml",
    "test": "cross-env NODE_OPTIONS=--experimental-vm-modules jest --coverage --config=jest.config.cjs"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/xt0rted/dotnet-sdk-updater.git"
  },
  "keywords": [
    "actions",
    "github",
    "dependabot",
    "dependencies",
    "dotnet",
    "dotnet-core",
    "dotnet-sdk"
  ],
  "author": "xt0rted",
  "license": "MIT",
  "dependencies": {
    "@actions/core": "^1.10.1",
    "json5": "^2.2.3",
    "node-fetch": "^3.3.2",
    "semver": "^7.6.0",
    "xregexp": "^5.1.1"
  },
  "devDependencies": {
    "@types/eslint": "^8.56.2",
    "@types/jest": "^29.5.12",
    "@types/node": "^20.11.25",
    "@types/semver": "^7.5.8",
    "@typescript-eslint/eslint-plugin": "^6.20.0",
    "@typescript-eslint/parser": "^6.20.0",
    "@vercel/ncc": "^0.38.1",
    "@xt0rted/actions-toolkit": "^0.0.1",
    "cross-env": "^7.0.3",
    "dotenv": "^16.4.5",
    "eslint": "^8.56.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jest": "^27.6.3",
    "eslint-plugin-sort-destructure-keys": "^1.5.0",
    "eslint-plugin-typescript-sort-keys": "^3.1.0",
    "eslint-plugin-unicorn": "^50.0.1",
    "jest": "^29.7.0",
    "jest-circus": "^29.6.1",
    "nock": "^13.5.4",
    "rimraf": "^5.0.5",
    "ts-jest": "^29.1.2",
    "ts-node": "^10.9.2",
    "tslib": "^2.6.2",
    "typescript": "^5.4.2"
  }
}
```

### dependabot.yml content

https://github.com/xt0rted/dotnet-sdk-updater/blob/cbb5ab188ac13d464cf19bf5ac4f892f6f836934/.github/dependabot.yml

```yaml
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "actions/*"
      my-actions:
        patterns:
          - "xt0rted/*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        patterns:
          - "@types/eslint"
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
      jest:
        patterns:
          - "@types/jest"
          - "jest"
          - "jest-*"
          - "ts-jest"
      semver:
        patterns:
          - "@types/semver"
          - "semver"
      typescript:
        patterns:
          - "ts-node"
          - "tslib"
          - "typescript"
```

### Updated dependency

| Package | From | To |
| --- | --- | --- |
| [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin) | `6.20.0` | `6.21.0` |
| [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser) | `6.20.0` | `6.21.0` |
| [eslint](https://github.com/eslint/eslint) | `8.56.0` | `8.57.0` |
| [@types/eslint](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/eslint) | `8.56.2` | `8.56.5` |
| [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) | `27.6.3` | `27.9.0` |
| [eslint-plugin-typescript-sort-keys](https://github.com/infctr/eslint-plugin-typescript-sort-keys) | `3.1.0` | `3.2.0` |
| [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) | `50.0.1` | `51.0.1` |

### What you expected to see, versus what you actually saw

The commit message has the list of packages updated, but the PR body doesn't for some reason.

https://github.com/xt0rted/dotnet-sdk-updater/pull/605
