### ISSUE TITLE
Dependabot missing project references on Grouped pull requests

### ISSUE THREAD

**Issue by OwenPattison** [dependabot/dependabot-core#9332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn, nuget

### Package manager version

latest

### Language version

nodejs v20

### Manifest location and content before the Dependabot update

n/a

### dependabot.yml content

```yml- package-ecosystem: nuget
  directory: /api
  schedule:
    interval: daily
  groups:
    entity-framework:
      patterns:
        - "Microsoft*.EntityFrameworkCore*"
  ignore:
    - dependency-name: Microsoft.EntityFrameworkCore*
      update-types: ["version-update:semver-major"]
```

### Updated dependency

I would expect all matching group patterns within my solution which has multiple project
      patterns:
        - "Microsoft*.EntityFrameworkCore*"

### What you expected to see, versus what you actually saw

2 of 3 projects that reference the pattern were updated however one was missed

this issue is linked to: https://github.com/dependabot/dependabot-core/issues/8552

### Native package manager behavior

n/A

### Images of the diff or a link to the PR, issue, or logs

![image](https://github.com/dependabot/dependabot-core/assets/5864244/9bb9521b-b279-4c22-9b92-02fbb54b189e)

![image](https://github.com/dependabot/dependabot-core/assets/5864244/16f2b708-5a85-41e2-84fd-ef616952b87c)

### Smallest manifest that reproduces the issue

```yml- package-ecosystem: nuget
  directory: /api
  schedule:
    interval: daily
  groups:
    entity-framework:
      patterns:
        - "Microsoft*.EntityFrameworkCore*"
  ignore:
    - dependency-name: Microsoft.EntityFrameworkCore*
      update-types: ["version-update:semver-major"]
```
