### ISSUE TITLE
Pull request created for non-existant group

### ISSUE THREAD

**Issue by coreyworrell** [dependabot/dependabot-core#9335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

composer

### Package manager version

2

### Language version

PHP 8.1

### Manifest location and content before the Dependabot update

`/composer.json`

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    groups:
      auto:
        patterns:
          - emrl/block-class-autocomplete
          - roots/*
          - wpackagist-*
      minor:
        update-types:
          - patch
          - minor
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: flickity
        versions: ["^3"]
    groups:
      minor:
        update-types:
          - patch
          - minor
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      minor:
        update-types:
          - patch
          - minor
```

### Updated dependency

`phpunit/phpunit` from 10.5.11 to 10.5.12

### What you expected to see, versus what you actually saw

I expected the `phpunit/phpunit` package to be included in the "minor" group pull request. Instead it is part of an old (removed) group, even though it is only a minor/patch update.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/intervaldev/website/pull/70
https://github.com/intervaldev/website/pull/74

### Smallest manifest that reproduces the issue

```json
{
    "require": {
        "php": ">=8.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^10"
    }
}

```
