### ISSUE TITLE
gitsubmodule: Dependabot ran out of disk space during its update

### ISSUE THREAD

**Issue by agners** [dependabot/dependabot-core#9376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gitsubmodule

### Manifest location and content before the Dependabot update

Using the smart home protocol Matter SDK as submodule `.gitmodules`:

```
[submodule "connectedhomeip"]
	path = connectedhomeip
	url = https://github.com/project-chip/connectedhomeip.git
	branch = master
	fetchRecurseSubmodules = false
```

The repository observing this issue along with the dependencies are all public, see: https://github.com/home-assistant-libs/chip-wheels.

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "connectedhomeip"
    schedule:
      interval: "daily"
    target-branch: main
```

### What you expected to see, versus what you actually saw

Get a PR which updates to the latest version of the submodule.

Instead, Dependabot fails with "Dependabot ran out of disk space during its update".

Cleaning from the logs, it seems that Dependabot recursively checks out submodule for that dependency. This is at least for this dependency update completely unnecessary. Also the git submodule configuration `.gitmodules` I've explicitly disable recursive checkout of submodules. But it seems that Dependabot is not honoring that configuration.

At the very least Dependabot should honor that configuration. But from my point of view, it is never necessary for Dependabot to checkout git submodules recursively for the `gitsubmodule` package ecosystem. It is just a waste of time and resources.
