### ISSUE TITLE
PR description doesn't match diff when using lockfile-only

### ISSUE THREAD

**Issue by devjgm** [dependabot/dependabot-core#9389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

cargo

### Package manager version

cargo 1.79.0-nightly (2fe739fcf 2024-03-15)

### Language version

rustc 1.79.0-nightly (a7e4de13c 2024-03-19)

### Manifest location and content before the Dependabot update

empty

### dependabot.yml content

```yml
# Configures Dependabot to update Cargo.lock files beneath directory "/".
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # While experimenting, only bother devjgm
    reviewers:
      - "devjgm"
    # Only update Cargo.lock, not Cargo.toml
    versioning-strategy: lockfile-only
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    ignore:
      # Ignore major version bumps, which could break API.
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      minor-patch-updates:
        update-types:
          - "minor"
          - "patch"
 ```

### Updated dependency

<img width="1398" alt="image" src="https://github.com/dependabot/dependabot-core/assets/9447643/eb2445c9-fac9-45d5-b76a-8aa94f045741">

### What you expected to see, versus what you actually saw

# Expected

I expected to see a PR title and description that matched the **4 packages** that were updated in the `Cargo.lock` file shown in the diff.

# Actually saw

**build(deps): bump the minor-patch-updates group in /build-tools with 11 updates**
<img width="484" alt="image" src="https://github.com/dependabot/dependabot-core/assets/9447643/2a592d89-7e37-41cd-950b-aafd16cbeb17">

Note that the PR title and description describe 11 changes that were made, yet those changes were not actually made.

# Comment

It seems like the PR  title/description are being generated based on changes to the `Cargo.toml` (note _.toml_, not _.lock_) that dependable would have made if it wasn't configured with `versioning-strategy: lockfile-only`. The _diffs_ that were generated look correct to me, but the PR title and description do not match the diffs.

### Native package manager behavior

N/A

### Images of the diff or a link to the PR, issue, or logs

<img width="1398" alt="image" src="https://github.com/dependabot/dependabot-core/assets/9447643/eb2445c9-fac9-45d5-b76a-8aa94f045741">

### Smallest manifest that reproduces the issue

NA
