### ISSUE TITLE
gitsubmodule doesn't work with git forges that don't have various [uploadpack] configuration settings enabled

### ISSUE THREAD

**Issue by DaanDeMeyer** [dependabot/dependabot-core#9391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gitsubmodule

### dependabot.yml content

```yaml
# SPDX-License-Identifier: LGPL-2.1-or-later

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
  - package-ecosystem: "docker"
    directory: "/.clusterfuzzlite"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
```

### What you expected to see, versus what you actually saw

I expected dependabot to not fail, instead it failed with the following:

```
updater | error: Server does not allow request for unadvertised object 3cf45106c8bc5a050901851be6b2ac85b6f5c571
updater | fatal: Fetched in submodule path 'pkg/centos', but it did not contain 3cf45106c8bc5a050901851be6b2ac85b6f5c571. Direct fetching of that commit failed.
updater | fatal:
updater | 2024/03/30 11:20:28 INFO <job_807505958> Finished job processing
updater | 2024/03/30 11:20:28 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | job_repo_not_found |
updater | +--------------------+
```

This only happens when using git submodules of repositories hosted on pagure (https://pagure.io/pagure/issues). Specifically, pagure does not seem to have the following settings enabled on it's git repos:

```
[uploadpack]
allowTipSha1InWant = true
allowReachableSHA1InWant = true
allowAnySHA1InWant = true
```

Without these settings, the full repository history has to be fetched in order to be able to check out a particular commit. `dependabot-core` currently uses `--depth=1` and `shallow-submodules` when cloning a git repository which means that the history is missing.

Please fetch the full history or provide an option to do so conditionally so dependabot can work with git submodules of repositories hosted on pagure.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/systemd/systemd/issues/31773
