### ISSUE TITLE
Dependabot doesn't update NuGet version in all projects

### ISSUE THREAD

**Issue by prplecake** [dependabot/dependabot-core#9444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

.NET 8

### Manifest location and content before the Dependabot update

Project layout follows a pattern similar to the following:

- `/src/Core/Core.csproj`
- `/src/Infrastructure/Infrastructure.csproj`
- `/src/CLI/CLI.csproj`
- `/tests/Core.Tests/Core.Tests.csproj`
- `/tests/Infrastructure.Tests/Infrastructure.Tests.csproj`
- `/tests/TestHelpers/TestHelpers.csproj`

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```

### Updated dependency

Microsoft.Test.SDK 17.6.0 to 17.9.0

### What you expected to see, versus what you actually saw

I would expect Microsoft.Test.SDK to be updated in all three test projects, but it's only updated in a single project, causing any related restore/builds to fail with a package downgrade error from MSBuild.

### Native package manager behavior

Not applicable.

### Images of the diff or a link to the PR, issue, or logs

![image](https://github.com/dependabot/dependabot-core/assets/83595468/957ae1bd-9525-4df9-b3fe-b1f1aceb6862)

According to the dependabot logs, dependabot knows this dependency is found in other projects:
```
updater |   name: Microsoft.NET.Test.Sdk, version: 17.6.0
updater |     file: tests/UserCreation.Core.Tests/UserCreation.Core.Tests.csproj, metadata: 
updater |     file: tests/UserCreation.Infrastructure.Tests/UserCreation.Infrastructure.Tests.csproj, metadata: 
updater |     file: tests/UserCreation.TestHelpers/UserCreation.TestHelpers.csproj, metadata: 
updater |   name: MSTest.TestAdapter, version: 3.0.4
updater |     file: tests/UserCreation.Core.Tests/UserCreation.Core.Tests.csproj, metadata: 
updater |     file: tests/UserCreation.Infrastructure.Tests/UserCreation.Infrastructure.Tests.csproj, metadata: 
updater |     file: tests/UserCreation.TestHelpers/UserCreation.TestHelpers.csproj, metadata: 
updater |   name: MSTest.TestFramework, version: 3.0.4
updater |     file: tests/UserCreation.Core.Tests/UserCreation.Core.Tests.csproj, metadata: 
updater |     file: tests/UserCreation.Infrastructure.Tests/UserCreation.Infrastructure.Tests.csproj, metadata: 
updater |     file: tests/UserCreation.TestHelpers/UserCreation.TestHelpers.csproj, metadata: 
updater |   name: coverlet.collector, version: 6.0.0
updater |     file: tests/UserCreation.Core.Tests/UserCreation.Core.Tests.csproj, metadata: 
updater |     file: tests/UserCreation.Infrastructure.Tests/UserCreation.Infrastructure.Tests.csproj, metadata: 
updater |     file: tests/UserCreation.TestHelpers/UserCreation.TestHelpers.csproj, metadata: 
```
