### ISSUE TITLE
dependabot creates pr for sub directory for file in root of module

### ISSUE THREAD

**Issue by el-chazmo** [dependabot/dependabot-core#9469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

terraform

### dependabot.yml content

```yml
version: 2

registries:
  Artifactory:
    type: terraform-registry
    url: https://repo.[COMPANY-NAME].com/artifactory/api/terraform
    token: ${{ secrets.TERRAFORM_REGISTRY_TOKEN }}

  - package-ecosystem: terraform
    directory: /
    registries:
      - Artifactory
    schedule:
      interval: daily
    commit-message:
      prefix: feat

  - package-ecosystem: terraform
    directory: "/test/setup/in-region-backup-restore"
    registries:
      - Artifactory
    schedule:
      interval: daily
    commit-message:
      prefix: test
```

### What you expected to see, versus what you actually saw

Expected:
PR = test: update terraform__foundation/security-groups/aws requirement from ~> 1.0 to ~> 2.0 in /test/setup/in-region-backup-restore
files targeted should be in /test/setup/in-region-backup-restore ONLY

Actually saw
PR = test: update terraform__foundation/security-groups/aws requirement from ~> 1.0 to ~> 2.0 in /test/setup/in-region-backup-restore
files targeted were in /

NOTE: the root of the module has a prefix of feat, compared to the subdirectory that has the prefix of test.
