### ISSUE TITLE
Docker group updates don't ignore unstable versions

### ISSUE THREAD

**Issue by pumbaasdad** [dependabot/dependabot-core#9496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### Manifest location and content before the Dependabot update

```
FROM rclone/rclone:1.66.0 as rclone
FROM docker:26.0.0 as docker

FROM alpine:3.19.1 as alpine

FROM python:3.12.2 as python
RUN python -V > .python_version

FROM ghcr.io/pumbaasdad/poetry:1.8.2 as poetry
RUN poetry -V > .poetry_version

FROM ghcr.io/pumbaasdad/poetry:2024-03-16

...
```

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:00"
      timezone: "America/Toronto"
    groups:
      docker:
        update-types:
          - "minor"
          - "patch"
```

### Updated dependency

`python:3.12.2` was updated to `python:3.13.0a6`

### What you expected to see, versus what you actually saw

I expected that the stable version of python was not updated to an alpha release.  Removing the group configuration from dependabot.yml resulted in python being updated to 3.12.3 as expected.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/pumbaasdad/volumerize/pull/50
