### ISSUE TITLE
PR description missing package information

### ISSUE THREAD

**Issue by dhensby** [dependabot/dependabot-core#9502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

10

### Language version

18

### Manifest location and content before the Dependabot update

./package.json

### dependabot.yml content

```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - private-registrty
    schedule:
      interval: "weekly"
    groups:
      azure-libs:
        patterns:
          - "@azure/*"
      release-tools:
        patterns:
          - "@private/repo1"
          - "@private/repo2"
          - "@semantic-release/*"
          - "@commitlint/*"
          - "semantic-release"
      lint-tools:
        patterns:
          - "@private/repo3"
          - "@typescript-eslint/*"
          - "eslint*"
      test-tools:
        patterns:
          - "@private/repo4"
          - "chai"
          - "@types/chai"
          - "mocha*"
          - "@types/mocha"
          - "nyc"
          - "@istanbuljs/nyc-config-typescript"
          - "sinon*"
          - "@types/sinon*"
      build-tools:
        patterns:
          - "@tsconfig/*"
          - "@types/*"
          - "ts-node"
          - "typescript"
        exclude-patterns:
          - "@types/chai"
          - "@types/mocha"
          - "@types/sinon*"
      db-tools:
        patterns:
          - "knex"
          - "mssql"
          - "tedious"
          - "@tediousjs/*"
      dev-tools:
        dependency-type: "development"
        patterns:
          - "@private/*"
        exclude-patterns:
          - "@private/repo1"
          - "@private/repo2"
          - "@private/repo3"
          - "@private/repo4"
      prod-tools:
        dependency-type: "production"
        patterns:
          - "@private/*"
registries:
  private-registry:
    type: npm-registry
    url: https://private.reg.example.com/repo/
    username: user
    password: ${{secrets.DEVOPS_PAT}}
```

### Updated dependency

`@types/node` & `typescript`

### What you expected to see, versus what you actually saw

The PR is opened with no packages listed in the description, but packages are updated in the PR.

![image](https://github.com/dependabot/dependabot-core/assets/563596/fdc4dc8e-2e3b-4e0c-95d9-48a629603717)

I expect that the PR should list out the changed packages with links to the commits/changelog/releasenotes as is normally the case.

### Native package manager behavior

n/a

### Images of the diff or a link to the PR, issue, or logs

```diff
diff --git a/package-lock.json b/package-lock.json
index 9462467..92acb00 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -6919,9 +6919,9 @@
       "dev": true
     },
     "node_modules/@types/node": {
-      "version": "16.18.95",
-      "resolved": "https://registry.npmjs.org/@types/node/-/node-16.18.95.tgz",
-      "integrity": "sha512-z9w+CcR7ahc7UhsKe+PGB25nmPmCERQBAdLdFHhoZ6+FfgSr7gUvdQI0eLH2t7ue8u5wKsLdde6cHKPjhC8vGg==",
+      "version": "16.18.96",
+      "resolved": "https://registry.npmjs.org/@types/node/-/node-16.18.96.tgz",
+      "integrity": "sha512-84iSqGXoO+Ha16j8pRZ/L90vDMKX04QTYMTfYeE1WrjWaZXuchBehGUZEpNgx7JnmlrIHdnABmpjrQjhCnNldQ==",
       "dev": true
     },
     "node_modules/@types/node-forge": {
@@ -16952,9 +16952,9 @@
       }
     },
     "node_modules/typescript": {
-      "version": "5.4.4",
-      "resolved": "https://registry.npmjs.org/typescript/-/typescript-5.4.4.tgz",
-      "integrity": "sha512-dGE2Vv8cpVvw28v8HCPqyb08EzbBURxDpuhJvTrusShUfGnhHBafDsLdS1EhhxyL6BJQE+2cT3dDPAv+MQ6oLw==",
+      "version": "5.4.5",
+      "resolved": "https://registry.npmjs.org/typescript/-/typescript-5.4.5.tgz",
+      "integrity": "sha512-vcI4UpRgg81oIRUFwR0WSIHKt11nJ7SAVlYNIu+QpqeyXP+gpQJy/Z4+F0aGxSE4MqwjyXvW/TzgkLAx2AGHwQ==",
       "dev": true,
       "bin": {
         "tsc": "bin/tsc",
@@ -22049,9 +22049,9 @@
       "dev": true
     },
     "@types/node": {
-      "version": "16.18.95",
-      "resolved": "https://registry.npmjs.org/@types/node/-/node-16.18.95.tgz",
-      "integrity": "sha512-z9w+CcR7ahc7UhsKe+PGB25nmPmCERQBAdLdFHhoZ6+FfgSr7gUvdQI0eLH2t7ue8u5wKsLdde6cHKPjhC8vGg==",
+      "version": "16.18.96",
+      "resolved": "https://registry.npmjs.org/@types/node/-/node-16.18.96.tgz",
+      "integrity": "sha512-84iSqGXoO+Ha16j8pRZ/L90vDMKX04QTYMTfYeE1WrjWaZXuchBehGUZEpNgx7JnmlrIHdnABmpjrQjhCnNldQ==",
       "dev": true
     },
     "@types/node-forge": {
@@ -29332,9 +29332,9 @@
       }
     },
     "typescript": {
-      "version": "5.4.4",
-      "resolved": "https://registry.npmjs.org/typescript/-/typescript-5.4.4.tgz",
-      "integrity": "sha512-dGE2Vv8cpVvw28v8HCPqyb08EzbBURxDpuhJvTrusShUfGnhHBafDsLdS1EhhxyL6BJQE+2cT3dDPAv+MQ6oLw==",
+      "version": "5.4.5",
+      "resolved": "https://registry.npmjs.org/typescript/-/typescript-5.4.5.tgz",
+      "integrity": "sha512-vcI4UpRgg81oIRUFwR0WSIHKt11nJ7SAVlYNIu+QpqeyXP+gpQJy/Z4+F0aGxSE4MqwjyXvW/TzgkLAx2AGHwQ==",
       "dev": true
     },
     "uglify-js": {
```
