### ISSUE TITLE
Poetry dependency containing path to `.whl` file fails

### ISSUE THREAD

**Issue by yehoshuadimarsky** [dependabot/dependabot-core#9524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Poetry / Pip

### Package manager version

Poetry 1.7

### Language version

Python 3.10

### Manifest location and content before the Dependabot update

Relevant section of `pyproject.toml`

```toml
[tool.poetry.group.airflow.dependencies]
# some other packages


# this is the issue
ts-launchpad = {path = "third-party/ts_launchpad-0.2.0-py3-none-any.whl", develop = false}  
```

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"  # See documentation for possible values
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"
```

### What you expected to see, versus what you actually saw

That Dependabot can generate a PR.

This is a private repository, I can share the information with GitHub Support if they want.

I have a local `.whl` file that is in my source code that is used in my dependencies (it's a third party wheel that I need to use).

Instead, I see in the logs:

```
updater | 2024/04/17 22:29:54 INFO <job_816290251> Dependabot is using Python version '3.10'.
updater | 2024/04/17 22:29:54 INFO <job_816290251> Finished job processing
updater | time="2024-04-17T22:29:54Z" level=info msg="task complete" container_id=job-816290251-file-fetcher exit_code=0 job_id=816290251 step=fetcher
updater | 2024/04/17 22:29:57 INFO <job_816290251> Starting job processing
updater | 2024/04/17 22:30:09 INFO <job_816290251> Starting grouped update job for bartonavenue/python
updater | 2024/04/17 22:30:09 INFO <job_816290251> Found 1 group(s).
updater | 2024/04/17 22:30:09 INFO <job_816290251> Starting update group for 'pip'
updater | 2024/04/17 22:30:19 INFO <job_816290251> Checking if pyarrow 9.0.0 needs updating
  proxy | 2024/04/17 22:30:19 [017] GET https://pypi.org:443/simple/pyarrow/
  proxy | 2024/04/17 22:30:19 [017] 200 https://pypi.org:443/simple/pyarrow/
updater | 2024/04/17 22:30:20 INFO <job_816290251> Lowest security fix version is 14.0.1
  proxy | 2024/04/17 22:30:20 [019] GET https://pypi.org:443/pypi/bartonavenue/json/
  proxy | 2024/04/17 22:30:20 [019] 301 https://pypi.org:443/pypi/bartonavenue/json/
  proxy | 2024/04/17 22:30:20 [021] GET https://pypi.org:443/pypi/bartonavenue/json
  proxy | 2024/04/17 22:30:21 [021] 404 https://pypi.org:443/pypi/bartonavenue/json
updater | 2024/04/17 22:30:27 ERROR <job_816290251> Error processing pyarrow (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2024/04/17 22:30:27 ERROR <job_816290251> Path dependabot_tmp_dir/third-party/ts_launchpad-0.2.0-py3-none-any.whl for ts-launchpad does not exist
```
