### ISSUE TITLE
config schema errors

### ISSUE THREAD

**Issue by cihati** [dependabot/dependabot-core#956]
```
The property '#/update_configs/0/allowed_updates/0' contains additional properties ["update_type"] outside of the schema when none are allowed
The property '#/update_configs/0/allowed_updates/0/match' of type null did not match one or more of the required schemas
The property '#/update_configs/0/allowed_updates/1' contains additional properties ["update_type"] outside of the schema when none are allowed
The property '#/update_configs/0/allowed_updates/1/match' of type null did not match one or more of the required schemas
The property '#/update_configs/0/allowed_updates/2' contains additional properties ["update_type"] outside of the schema when none are allowed
The property '#/update_configs/0/allowed_updates/2/match' of type null did not match one or more of the required schemas
The property '#/update_configs/0/ignored_updates/0' of type object did not match one or more of the required schemas
The property '#/update_configs/0/ignored_updates/1' of type object did not match one or more of the required schemas
```

My config file is:
```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"

    # We only want minor & revision upgrades, unless it is a security upgrade.
    # Then we are fine receiving major version increases too.
    allowed_updates:
      - match:
        update_type: "security:patch"
      - match:
        update_type: "semver:patch"
      - match:
        update_type: "semver:minor"

    ignored_updates:
      - match:
        dependency_name: "react"
      - match:
        dependency_name: "material-ui"
```

Not sure how to resolve these without having an accurate schema spec?
