### ISSUE TITLE
Dependabot on Github Actions reporting Node 16 deprecation issue

### ISSUE THREAD

**Issue by broksonic21** [dependabot/dependabot-core#9598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Language version

ruby

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "America/New_York"
    versioning-strategy: increase
    open-pull-requests-limit: 20
    insecure-external-code-execution: deny
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    allow:
      - dependency-type: "all"
    groups:
      monthlybundler:
        patterns:
          - "*"

```

### What you expected to see, versus what you actually saw

<img width="468" alt="image" src="https://github.com/dependabot/dependabot-core/assets/24306571/2b1b9894-c181-401a-8888-352bcedab6f6">

Expected to see no warnings

### Smallest manifest that reproduces the issue

you can see this on any of Dependabots own action runs too... i.e. https://github.com/dependabot/dependabot-core/actions/runs/8816857292
