### ISSUE TITLE
Dependabot tries to update more dependencies than declared

### ISSUE THREAD

**Issue by mauroservienti** [dependabot/dependabot-core#9661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### Language version

C#

### Manifest location and content before the Dependabot update

As you can see from [this dependabot PR](https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/680), the updated dependencies are way more than what they should be. it should only be updating `xunit.runner.visualstudio` and not all the other dependencies.

### dependabot.yml content

```
version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
```

### Updated dependency

xunit.runner.visualstudio from 2.5.7 to 2.8.0, but it's happening for all dependencies

### What you expected to see, versus what you actually saw

Only the mentioned dependency is updated, and not all of the dependencies in the project.
