### ISSUE TITLE
Dependabot generating PR's for all registeries in monorepo

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [dependabot/dependabot-core#9735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pub

### Manifest location and content before the Dependabot update

`/client/dart/app/pubspec.yaml`

### dependabot.yml content

```yaml
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "client/dart/app/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
```

### What you expected to see, versus what you actually saw

I have a monorepo consistly node, python and a flutter client, I have configured dependabot for generating PR's for just `flutter` but it is generating PR for node and python as well.
