### ISSUE TITLE
Terraform provider updates

### ISSUE THREAD

**Issue by ukv001** [dependabot/dependabot-core#9747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have a repo that contains all our infra structure, separated into different environments. Under each environment we have 2 infra structures, one for the actual infra structure and one for uploading secrets to vault
e.g. 
infrastructure/environments/dev/infrastructure
infrastructure/environments/dev/vault
infrastructure/environments/prod/infrastructure
infrastructure/environments/prod/vault
it seems that in the dependabot file I need to specifify each infrastructure
e.g. for dev/infrastructure
  - package-ecosystem: "terraform"
    directory: "infrastructure/environments/dev/infrastructure"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "infrastructure/environments/dev/vault"
    schedule:
      interval: "daily"

From what I have experienced the other types of ecosystems I can just add the / and it will find files needed, e.g. for actions, and pom files and so on.

is this a flaw in the terraform or is it on purpose ? I do realise I would like to separate one environment out, so I can look at the plan for sure before applying.

**Comment by zahorniak** [comment]
Hi @ukv001,

Does a configuration like this not solve your problem?
```yaml
updates:
  # To keep Terraform modules up to date
  - package-ecosystem: "terraform"
    directories:
      - "/infrastructure/environments/dev/infrastructure"
      - "/infrastructure/environments/dev/vault"
      - "/infrastructure/environments/prod/infrastructure"
      - "/infrastructure/environments/prod/vault"
    schedule:
      interval: "daily"
```

**Comment by manumbs** [comment]
Following this today [announcement](https://github.blog/changelog/2024-06-25-simplified-dependabot-yml-configuration-with-multi-directory-key-directories-and-wildcard-glob-support/), theoretically, if I understand it on the right way, you can use glob wildcard with just:

```
updates:
  - package-ecosystem: "terraform"
    directories:
      - "*"
    schedule:
      interval: "daily"
```

I tried to use it, but it's not working yet:

```
updater | 2024/06/25 18:19:55 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
```
