### ISSUE TITLE
No pull requests are created for the NuGet ecosystem

### ISSUE THREAD

**Issue by samtrion** [dependabot/dependabot-core#9762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

latest

### Language version

.NET 5, .NET 6, .NET 7, .NET 8, .NET 9

### Manifest location and content before the Dependabot update

Location: `/Directory.Packages.props`
```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="CSharpier.MSBuild" Version="0.28.0" />
    <GlobalPackageReference Include="GitVersion.MsBuild" Version="5.12.0" Condition=" '$(BuildingInsideVisualStudio)' != 'true' " />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0" />
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.9.28" />
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="9.23.1.88495" Condition=" '$(BuildingInsideVisualStudio)' == 'true' " />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="ClickHouse.Client" Version="7.2.1" />
    <PackageVersion Include="Confluent.Kafka" Version="2.3.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.2" />
    <PackageVersion Include="Dapr.Client" Version="1.13.0" />
    <PackageVersion Include="Glob" Version="1.1.9" />
    <PackageVersion Include="ICSharpCode.Decompiler" Version="8.2.0.7535" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="8.0.1" />
    <PackageVersion Update="Microsoft.AspNetCore.TestHost" Version="7.0.14" Condition=" '$(TargetFramework)' == 'net7.0' " />
    <PackageVersion Update="Microsoft.AspNetCore.TestHost" Version="6.0.26" Condition=" '$(TargetFramework)' == 'net6.0' " />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="17.9.5" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.9.2" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="5.1.5" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="8.0.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Configuration" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageVersion Update="Microsoft.Extensions.Hosting" Version="7.0.1" Condition=" '$(TargetFramework)' == 'net7.0-windows' " />
    <PackageVersion Update="Microsoft.Extensions.Hosting" Version="6.0.1" Condition=" '$(TargetFramework)' == 'net6.0-windows' " />
    <PackageVersion Update="Microsoft.Extensions.Hosting.Abstractions" Version="7.0.0" Condition=" '$(TargetFramework)' == 'net7.0-windows' " />
    <PackageVersion Update="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" Condition=" '$(TargetFramework)' == 'net6.0-windows' " />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageVersion Include="Microsoft.TestPlatform.TestHost" Version="17.9.0" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.3.1" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.3.1" />
    <PackageVersion Include="MySql.Data" Version="8.3.0" />
    <PackageVersion Include="MySqlConnector" Version="2.3.6" />
    <PackageVersion Include="NetEvolve.Arguments" Version="1.1.0" />
    <PackageVersion Include="NetEvolve.Extensions.NUnit" Version="1.2.0" />
    <PackageVersion Include="NetEvolve.Extensions.Tasks" Version="1.1.110" />
    <PackageVersion Include="NetEvolve.Extensions.XUnit" Version="2.0.13" />
    <PackageVersion Include="NetEvolve.Logging.Abstractions" Version="1.0.0" />
    <PackageVersion Include="NetEvolve.Logging.Measurement" Version="1.0.0" />
    <PackageVersion Include="NetEvolve.Logging.XUnit" Version="1.0.0" />
    <PackageVersion Include="NetEvolve.SequentialGuid" Version="1.0.1" />
    <PackageVersion Include="Npgsql" Version="8.0.2" />
    <PackageVersion Include="NSubstitute" Version="5.1.0" />
    <PackageVersion Include="NUnit" Version="4.1.0" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.1.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="3.21.130" />
    <PackageVersion Include="Polyfill" Version="4.4.1" />
    <PackageVersion Include="Spectre.Console" Version="0.48.0" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.48.0" />
    <PackageVersion Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageVersion Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageVersion Include="Testcontainers.ClickHouse" Version="3.8.0" />
    <PackageVersion Include="Testcontainers.Kafka" Version="3.8.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="3.8.0" />
    <PackageVersion Include="Testcontainers.MySql" Version="3.8.0" />
    <PackageVersion Include="Testcontainers.Oracle" Version="3.8.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="3.8.0" />
    <PackageVersion Include="Testcontainers.Redpanda" Version="3.8.0" />
    <PackageVersion Include="Testcontainers.SqlEdge" Version="3.8.0" />
    <PackageVersion Include="TngTech.ArchUnitNET.xUnit" Version="0.10.6" />
    <PackageVersion Include="Ulid" Version="1.3.3" />
    <PackageVersion Include="Verify.MSTest" Version="23.7.2" />
    <PackageVersion Include="Verify.NUnit" Version="23.5.2" />
    <PackageVersion Include="Verify.Xunit" Version="23.5.2" />
    <PackageVersion Include="xunit" Version="2.7.0" />
    <PackageVersion Include="xunit.extensibility.core" Version="2.7.0" />
    <PackageVersion Include="xunit.extensibility.execution" Version="2.7.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.6" />
    <PackageVersion Update="xunit.runner.visualstudio" Version="2.4.5" Condition=" '$(TargetFramework)' == 'net5.0' Or '$(TargetFramework)' == 'netcoreapp3.1' " />
  </ItemGroup>
</Project>
```

### dependabot.yml content

`dependabot.yml`
```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(ci)"
    labels:
      - "dependency-actions"
    open-pull-requests-limit: 50

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(deps)"
    labels:
      - "dependency-nuget"
    open-pull-requests-limit: 50
    # groups:
    #   coverlet:
    #     patterns:
    #       - "coverlet*"
    #   testcontainers:
    #     patterns:
    #       - "testcontainers*"
    #   verify:
    #     patterns:
    #       - "verify*"
    #   xunit:
    #     patterns:
    #       - "xunit"
    #       - "xunit*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(mods)"
    labels:
      - "dependency-gitmodule"
    open-pull-requests-limit: 50
    groups:
      submodules:
        patterns:
          - "*"
```

### What you expected to see, versus what you actually saw

I would expect pull requests to be created for the outstanding 29 packages.
No PR's have been created for the NuGet ecosystem for days.
