### ISSUE TITLE
Empty/incomplete commit message

### ISSUE THREAD

**Issue by mistic100** [dependabot/dependabot-core#9784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

1

### Manifest location and content before the Dependabot update

https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/package.json

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - mistic100
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
      - dependency-name: '@typescript-eslint/*'
        update-types: ['version-update:semver-minor']
      - dependency-name: 'marked'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'chore'
      include: 'scope'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    assignees:
      - mistic100
    commit-message:
      prefix: 'chore'
      include: 'scope'
```

### What you expected to see, versus what you actually saw

Recent update commits message are empty, only containing `---`, see examples bellow.

I didn't made any recent changes in the configuration.

### Images of the diff or a link to the PR, issue, or logs

- https://github.com/mistic100/Photo-Sphere-Viewer/commit/3d1f6a3f182202ea16c360f3355c57f6c03f2e1e
- https://github.com/mistic100/Photo-Sphere-Viewer/commit/06e3921971aa2157169e5830f772420ea07fd601
- https://github.com/mistic100/Photo-Sphere-Viewer/commit/fe078d2f5a9521d243ae676f94f66d9e9bb411b7
- https://github.com/mistic100/Photo-Sphere-Viewer/commit/c144ef11977e557ab4d1703f3b217b92988f526d

**Comment by slawekjaranowski** [comment]
One more example: https://github.com/codehaus-plexus/plexus-xml/pull/34/commits

**Comment by l0b0** [comment]
[Another example](https://github.com/linz/template-python-hello-world/pull/538) (fixed manually to make it pass `gitlint`), with an original commit message of:

```text
---
updated-dependencies:
- dependency-name: github/codeql-action
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>
```

`.github/dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "build(deps)"
```
