### ISSUE TITLE
Dependabot does not update shared action in `.github/actions/*/action.yml`

### ISSUE THREAD

**Issue by ai** [dependabot/dependabot-core#9788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github-actions

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
  - package-ecosystem: pnpm
    directory: '/'
    schedule:
      interval: daily
    security-updates-only: true
  - package-ecosystem: docker
      directory: '/'
      schedule:
        interval: weekly
```

### What you expected to see, versus what you actually saw

https://github.com/hplush/slowreader/pull/216

Dependabot updated `pnpm/action-setup` in `.github/workflows/preview-prepare.yml` and `.github/workflows/proxy.yml
`, but missed [`.github/actions/init-node/action.yml`](https://github.com/hplush/slowreader/blob/main/.github/actions/init-node/action.yml) used in other workflows
