### ISSUE TITLE
Private package causes GetAllPackageDependenciesAsync build failure, No packages exist with this id in source(s):

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [dependabot/dependabot-core#9816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### dependabot.yml content

```yaml
version: 2
registries:
  nuget-org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  releases:
    type: nuget-feed
    url: https://company.com/nexus/repository/custom-repository-name/index.json
    username: ${{secrets.LOGIN}}
    password: ${{secrets.PASSWORD}}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    registries:
      - nuget-org
      - releases
 ```

### What you expected to see, versus what you actually saw

During dependabot update of the any library in the project, for example `Microsoft.Identity.Web` from version `2.18.1` to `2.18.2`, dependabot raises following command

> /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/src/Project/Project.csproj --dependency Microsoft.Identity.Web --new-version 2.18.2 --previous-version 2.18.1  --verbose

That continues with:

```
updater |   No global.json files found.
  No dotnet-tools.json files found.
Running for project [/home/dependabot/dependabot-updater/repo/src/Project/Project.csproj]
  Running for SDK-style project
dotnet build in GetAllPackageDependenciesAsync failed. STDOUT: MSBuild version 17.8.3+195e7f5a3 for .NET
```

And it fails with information that private company packages cannot be resolved from nuget org

```
  Determining projects to restore...
/tmp/package-dependency-resolution_utbYG6/Project.csproj : error NU1101: Unable to find package Project.Http.Client. No packages exist with this id in source(s): nuget.org
/tmp/package-dependency-resolution_utbYG6/Project.csproj : error NU1101: Unable to find package Project.Messaging.ServiceBus. No packages exist with this id in source(s): nuget.org
  Failed to restore /tmp/package-dependency-resolution_utbYG6/Project.csproj (in 1.48 sec).
  ```
  
  It looks like credentials and link to the private source is not used by the restore happening in the process
  
  Environment:
  Github Actions Runner for Linux x64  2.311.0
  'github/dependabot-action@ghes-3.12' (SHA:867a767288b525c0b958f08538f5e61b9e5b3b93)
