### ISSUE TITLE
Auto-rebase does not work when auto-merge enabled

### ISSUE THREAD

**Issue by JuanLUJoanne** [dependabot/dependabot-core#9854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm, Bundler

### What you expected to see, versus what you actually saw

We expected the Dependency bot to still automatically rebase when there are merge conflicts after the [auto-merge workflow is enabled](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions).

However, the current behavior is that the Dependency bot stops automatically rebasing when there are merge conflicts.
And we need to manually type comments in the PR `@dependabot rebase` to ask the Dependency bot to rebase.

### Smallest manifest that reproduces the issue

```
version: 2
updates:
  - directory: /infrastructure
    package-ecosystem: npm
    schedule:
      interval: weekly
      day: wednesday
      time: "10:00"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 50
    allow:
      - dependency-type: all
    commit-message:
      prefix: Dependabot
```
