### ISSUE TITLE
Dependabot action do not trigger with poetry repository

### ISSUE THREAD

**Issue by Rogalek** [dependabot/dependabot-core#9903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

poetry

### Package manager version

poetry 1.8

### Language version

python 3.9

### Manifest location and content before the Dependabot update

`/poetry.lock` or `/pyproject.toml`

### dependabot.yml content

```
version: 2
registries:
  python-codeartifact:
    type: python-index
    url: PRIVATE_URL
    username: USER
    password: ${{secrets.TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    insecure-external-code-execution: allow
    open-pull-requests-limit: 0
    schedule:
      interval: 'daily'
    registries:
      - python-codeartifact
    reviewers:
      - Rogalek
      
```

### What you expected to see, versus what you actually saw

In my organization we have two kinds of repositories with two kinds of package dependency managers.
Pipfile and poetry.

For Pipfiles everything is working correctly, but for all repositories with poetry dependabot stopped creating PRs or do not mark security issues anymore.

I tried marking dependabot in my PRs (@dependabot), I also tried change dependabot.yml file to trigger it again but nothing is helping.

I thought it is maybe problem with poetry, so I ran dependabot cli against that repository and it worked, I got some logs from it:
![image](https://github.com/dependabot/dependabot-core/assets/24922834/5026f5bd-9c70-4c3d-bba1-0c1b6c03471f)

Nothing wrong here.

My question is what is wrong and how I can fix that? Thanks

**Comment by v-thavaahariharangit** [comment]
Please update your dependabot.yml as per the sample below

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    insecure-external-code-execution: allow
    schedule:
      interval: "weekly"
    registries:
      - python-artifactory

registries:
  python-artifactory:
    type: "python-index"
    url: "https://jfrogghdemo.jfrog.io/artifactory/api/pypi/db-dependbot-python/simple"
    username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
    password: "${{ secrets.PYTHON_TOKEN }}"
    replaces-base: true
```

Above example is tested and working as expected
