### ISSUE TITLE
Dependabot removes registry credentials from `Gemfile.lock`

### ISSUE THREAD

**Issue by lucasmazza** [dependabot/dependabot-core#9904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

Bundler 2.5.x

### Language version

Ruby 3.3.1

### Manifest location and content before the Dependabot update

`Gemfile`

```ruby
source "https://rubygems.org"

source "https://USERNAME:PASSWORD@rubygems.org/" do
  gem "activesupport"
end
```

### dependabot.yml content

```
version: 2
registries:
  secret-registry:
    type: rubygems-server
    url: https://rubygems.org
    username: USERNAME
    password: PASSWORD

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    insecure-external-code-execution: "allow"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "daily"
    registries:
      - "secret-registry"
```

### What you expected to see, versus what you actually saw

The Pull Request opened by Dependabot (https://github.com/lucasmazza/dependabot-registry-bug/pull/1) shouldn't remove the `USERNAME` and `PASSWORD` from the `Gemfile.lock`. 

We noticed this on a private repository with real credentials to a private RubyGems server, but the public repo mentioned here has the same behavior as our private app.

### Native package manager behavior

`bundle update activesupport` produces the following diff:

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 6b32d74..c580f09 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,7 +1,7 @@
 GEM
   remote: https://USERNAME:PASSWORD@rubygems.org/
   specs:
-    activesupport (7.1.3.3)
+    activesupport (7.1.3.4)
       base64
       bigdecimal
       concurrent-ruby (~> 1.0, >= 1.0.2)
```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/lucasmazza/dependabot-registry-bug/pull/1
