### ISSUE TITLE
Feature request: support adding per-group labels when grouping

### ISSUE THREAD

**Issue by bdragon** [dependabot/dependabot-core#9908]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

As a Dependabot user, when I configure groups for a particular (ecosystem, directory, target branch), I want to be able to add different labels to each group.

Proposal:

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    groups:
      version-updates:
        applies-to: version-updates
        labels:
          - version-update
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        labels:
          - security-update
        patterns:
          - "*"
```

**Comment by snsinahub** [comment]
thanks @bdragon for creating feature request... I'd like to add the requirement from my customer which might help to address additional questions

My customer has a mono repo based on multiple programming languages such as Python, JavaScript and more... they would like to distinguish between version and security updates PRs... 

I hope this feature request will support more programming languages such as Python, Java, dotnet and more

Thanks

**Comment by Fe1777** [comment]
Certainly! Here is a structured GitHub issue description for the feature request in Dependabot Core repository about supporting per-group labels when grouping.

---

## **Title:** Feature Request: Support Adding Per-group Labels When Grouping

**Type:** Feature Request

**Reported by:** [User who reported the issue]

---

### **Description**

The feature request aims to introduce support for adding per-group labels when grouping dependencies in Dependabot. This enhancement will provide users with more granular control over their dependency management by allowing them to specify labels for individual groups of dependencies.

### **Current Behavior**

Currently, Dependabot does not support assigning labels to dependency groups. Labels are applied uniformly across all dependencies, without the ability to differentiate between groups.

### **Desired Behavior**

Introduce functionality to:

- Allow users to specify labels for individual dependency groups.
- Ensure that these labels are applied to pull requests created for dependencies within the groups.

### **Use Case**

This feature is particularly useful for projects where different types of dependencies need to be categorized and managed distinctly. For example, separating frontend dependencies from backend dependencies and applying specific labels to each category.

### **Proposed Solution**

- **Implementation Details:** 
  - Modify the configuration to allow specifying labels for each dependency group.
  - Ensure that the label assignment logic can handle the new configuration.

- **Example Configuration:**
  ```yaml
  version: 2
  updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "daily"
      groups:
        frontend:
          patterns:
            - "react*"
            - "vue*"
          labels:
            - "frontend"
        backend:
          patterns:
            - "express*"
            - "koa*"
          labels:
            - "backend"
  ```

### **Acceptance Criteria**

- [ ] Users can add labels specific to each dependency group in the configuration.
- [ ] Dependabot applies the specified labels to pull requests created for dependencies within these groups.
- [ ] Clear documentation is available explaining how to use this feature.

### **Benefits**

- Enhanced categorization and management of dependencies.
- Improved visibility and tracking with appropriate labeling.
- Better alignment with project management practices.

### **Impact**

There are no breaking changes anticipated with this feature. It will be an optional enhancement that users can leverage if needed.

### **Related Issues/PRs**

- **Potentially Related Issues/PRs:** 
  - [Link to any related issues or PRs]

### **Thank you!**

Thank you for considering this feature request! The ability to add per-group labels will significantly improve dependency management within projects using Dependabot.

---

Feel free to adjust the template as necessary to fit any additional context or specifics of the feature request. This structured format aligns with standard GitHub requirements for issue reporting.

**Comment by leplatrem** [comment]
We would also be interested in this in order to ignore certain groups from our [autogenerated changelog](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options) 😊 

```yaml
# .github/release.yml
changelog:
  exclude:
    labels:
      - development
  categories:
    - title: Bug Fixes
      labels:
        - "bug"
    - title: Dependency Updates
      labels:
        - "dependencies"
```


```yaml
# .github/dependabot.yml
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  groups:
    production-dependency-patches:
      dependency-type: "production"
      update-types: ["patch"]
    development-dependencies:
      dependency-type: "development"
      update-types: ["major", "minor", "patch"]
      labels:
      - development
```

If this is relatively trivial to implement, and you provide a bit of guidance on where this would have to be done, I'd be willing to give it a try 🙏 

Thank you!
