### ISSUE TITLE
dependabot unignore not working

### ISSUE THREAD

**Issue by na1307** [dependabot/dependabot-core#9916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Asia/Seoul"
    assignees:
      - "na1307"
    pull-request-branch-name:
      separator: _
    reviewers:
      - "na1307"
    groups:
      default:
        patterns:
          - "*"
```

### Updated dependency

JsonSchema.Net

### What you expected to see, versus what you actually saw

I tried to unignore the ignored dependency in dependabot, but I received "No dependency name (jsonschema.net) or ignore conditions found to unignore."

### Images of the diff or a link to the PR, issue, or logs

na1307/SimpleSixtarScorecard#5

**Comment by leorg99** [comment]
I am finding the same issue with nuget packages. Even `@dependabot unignore *` returns the same message.
I am trying to unignore the following for a specific dependency in a pull-request:
```
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
```

### dependabot.yml

```
version: 2
registries:
  github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/{org}/index.json
    username: ${{ github.repository_owner }}
    password: ${{ secrets.ORG_GITHUB_PAT_READ_ONLY  }}
    
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Dependabot]"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - ".net"
    groups:
      test:
        patterns:
          - "xunit*"
          - "AutoFixture*"
          - "Microsoft.NET.Test*"
          - "FluentAssertions*"
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions*"
      mongodb:
        patterns:
          - "mongo*"
      hangfire:
        patterns:
          - "*hangfire*"
      nuke: 
        patterns:
          - "nuke*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "actions/*"
```
