### ISSUE TITLE
Dependabot for github actions considering closed PR's in existing-pull-requests list

### ISSUE THREAD

**Issue by dannystaple** [dependabot/dependabot-core#9920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

github_actions

### Manifest location and content before the Dependabot update

`.github/workflows/on_pr_to_develop_test.yml`

### dependabot.yml content

```yaml
---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

### Updated dependency

actions/checkout

### What you expected to see, versus what you actually saw

I'm expecting ` uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0` to be bumped to a current actions/checkout, with the hash and version comment updated.

No updates were made.

The dependabot log shows that it found many existing PRs.

```json
'existing-pull-requests': [[{'dependency-name': 'actions/download-artifact',
                                      'dependency-version': '4'}],
                                    [{'dependency-name': 'actions/upload-artifact',
                                      'dependency-version': '4'}],
                                    [{'dependency-name': 'tj-actions/changed-files',
                                      'dependency-version': '42'}],
                                    [{'dependency-name': 'super-linter/super-linter',
                                      'dependency-version': '6.0.0'}],
                                    [{'dependency-name': 'super-linter/super-linter',
                                      'dependency-version': '6.1.1'}],
                                    [{'dependency-name': 'super-linter/super-linter',
                                      'dependency-version': '6.2.0'}],
                                    [{'dependency-name': 'super-linter/super-linter',
                                      'dependency-version': '6.3.0'}],
                                    [{'dependency-name': 'oxsecurity/megalinter',
                                      'dependency-version': '7.10.0'}],
                                    [{'dependency-name': 'oxsecurity/megalinter',
                                      'dependency-version': '7.11.1'}],
                                    [{'dependency-name': 'aquasecurity/trivy-action',
                                      'dependency-version': '0.20.0'}]],
```

All but the first 2 have been closed by dependabot instead of merged - because a newer dependancy popped up, or because a commit was made removing the dependancy.

I suspect that this means it has too many existing PR's to 

### Smallest manifest that reproduces the issue

```yaml
---
on:
  pull_request

jobs:
  just_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
```
