### ISSUE TITLE
Customize commit-message prefix for a dependency group

### ISSUE THREAD

**Issue by Ndiritu** [dependabot/dependabot-core#9987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Supporting custom commit-message prefixes within a group would be great. 

_Sample Use-case:_
Some tools automate versioning & tagging based on the commit-message template. Version bumps to dependencies tend to warrant a version bump in the parent package. Customizing the commit message per group would allow developers with such tooling to automate version bumping only when certain critical dependencies are bumped.

e.g. set custom message prefix for patch vs minor updates to a specific group

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      microsoft-graph-core-patch:
        applies-to: version-updates
        patterns:
        - "*microsoft-graph-core*"
        update-types:
        - "patch"
        commit-message:
          prefix: "fix(deps)" # trigger a patch release in parent package after dependabot PR is merged
    microsoft-graph-core-patch:
        applies-to: version-updates
        patterns:
        - "*microsoft-graph-core*"
        update-types:
        - "minor"
        commit-message:
          prefix: "feat(deps)" # trigger a minor release in parent package after dependabot PR is merged
```

Happy to help with implementation if this is viable.
